In [1]:
# ============================================================
# FREIGHT-MNet: Download BTS FMI County-to-County Truck Travel Times
# Years: 2018–2024
# Save root:
#   E:\NetworkOptimization\pythonProject1\Data\02_fmi
#
# What this downloads:
#   Public BTS FMI annual county-pair truck travel-time CSV files.
#
# Output:
#   - raw annual CSV
#   - annual Parquet file for faster future processing
#   - dataset metadata JSON
#   - columns metadata JSON
#   - preview CSV
#   - manifest CSV
#   - download log JSONL
# ============================================================

from pathlib import Path
import os
import sys
import json
import time
import shutil
import hashlib
import requests
import pandas as pd
from tqdm.auto import tqdm
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# Optional but recommended: Polars is faster for large CSV -> Parquet conversion.
try:
    import polars as pl
    HAS_POLARS = True
except Exception:
    HAS_POLARS = False

# ------------------------------------------------------------
# 0. Configuration
# ------------------------------------------------------------

DATA_ROOT = Path(r"E:\NetworkOptimization\pythonProject1\Data")
FMI_ROOT = DATA_ROOT / "02_fmi"
METADATA_ROOT = FMI_ROOT / "_metadata"
MANIFEST_ROOT = DATA_ROOT / "00_manifest"

MANIFEST_PATH = MANIFEST_ROOT / "bts_fmi_download_manifest.csv"
LOG_PATH = MANIFEST_ROOT / "bts_fmi_download_log.jsonl"

# Keep raw CSV. Convert each year to Parquet too, which is much faster for later processing.
CONVERT_TO_PARQUET = True

# If True, existing CSV files will be checked and skipped when they look valid.
# If False, it will redownload everything.
SKIP_EXISTING_VALID_FILES = True

# If True, code will compute sha256 hash for each CSV.
# This is useful but slower for large files.
COMPUTE_SHA256 = False

# BTS / Socrata dataset IDs.
# These are the annual public FMI county-to-county truck travel-time files.
FMI_DATASETS = {
    2018: {
        "dataset_id": "xx4g-5dg2",
        "expected_unique_pairs_million": 2.08,
    },
    2019: {
        "dataset_id": "sn4k-eiea",
        "expected_unique_pairs_million": 4.13,
    },
    2020: {
        "dataset_id": "dggd-bg3y",
        "expected_unique_pairs_million": 4.43,
    },
    2021: {
        "dataset_id": "mayv-2qfz",
        "expected_unique_pairs_million": 4.25,
    },
    2022: {
        "dataset_id": "d7b8-pmxm",
        "expected_unique_pairs_million": 3.81,
    },
    2023: {
        "dataset_id": "ez58-m3b4",
        "expected_unique_pairs_million": 3.64,
    },
    2024: {
        "dataset_id": "uta5-4eu5",
        "expected_unique_pairs_million": 3.58,
    },
}

# data.bts.gov is the user-facing BTS data domain.
# data.transportation.gov is used as fallback because Socrata sometimes exposes DOT data there.
SOCRATA_DOMAINS = [
    "https://data.bts.gov",
    "https://data.transportation.gov",
]

# Create directories.
FMI_ROOT.mkdir(parents=True, exist_ok=True)
METADATA_ROOT.mkdir(parents=True, exist_ok=True)
MANIFEST_ROOT.mkdir(parents=True, exist_ok=True)

for year in FMI_DATASETS:
    (FMI_ROOT / str(year)).mkdir(parents=True, exist_ok=True)

print("=" * 100)
print("BTS FMI downloader")
print("Python executable:", sys.executable)
print("DATA_ROOT:", DATA_ROOT)
print("FMI_ROOT:", FMI_ROOT)
print("HAS_POLARS:", HAS_POLARS)
print("=" * 100)

# ------------------------------------------------------------
# 1. HTTP session with retries
# ------------------------------------------------------------

session = requests.Session()
session.headers.update(
    {
        "User-Agent": (
            "FREIGHT-MNet academic research downloader "
            "(public BTS FMI county-to-county truck travel-time data)"
        )
    }
)

retry = Retry(
    total=8,
    connect=8,
    read=8,
    status=8,
    backoff_factor=2.0,
    status_forcelist=[408, 429, 500, 502, 503, 504],
    allowed_methods=["GET", "HEAD"],
    raise_on_status=False,
)

adapter = HTTPAdapter(max_retries=retry, pool_connections=8, pool_maxsize=8)
session.mount("http://", adapter)
session.mount("https://", adapter)


# ------------------------------------------------------------
# 2. Utility functions
# ------------------------------------------------------------

def log_event(record: dict) -> None:
    record = dict(record)
    record["timestamp"] = pd.Timestamp.now().isoformat()
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def file_size_mb(path: Path) -> float:
    if not path.exists():
        return 0.0
    return round(path.stat().st_size / 1024**2, 3)


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            b = f.read(chunk_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def is_probably_valid_csv(path: Path, min_size_mb: float = 1.0) -> bool:
    """
    Quick validation:
    - file exists
    - file size > min_size_mb
    - pandas can read first few rows
    """
    if not path.exists():
        return False
    if file_size_mb(path) < min_size_mb:
        return False
    try:
        preview = pd.read_csv(path, nrows=3)
        if preview.shape[1] == 0:
            return False
        return True
    except Exception:
        return False


def build_urls(domain: str, dataset_id: str) -> dict:
    return {
        "csv": f"{domain}/api/views/{dataset_id}/rows.csv?accessType=DOWNLOAD",
        "metadata": f"{domain}/api/views/{dataset_id}.json",
        "columns": f"{domain}/api/views/{dataset_id}/columns.json",
        "count": f"{domain}/resource/{dataset_id}.json?$select=count(*)",
        "about": f"{domain}/d/{dataset_id}",
    }


def get_first_working_url(dataset_id: str, kind: str) -> tuple[str, str]:
    """
    Try data.bts.gov first, then data.transportation.gov.
    Returns: (domain, url)
    """
    last_error = None

    for domain in SOCRATA_DOMAINS:
        url = build_urls(domain, dataset_id)[kind]
        try:
            if kind == "csv":
                # HEAD sometimes fails on Socrata, so use a streamed GET and read no content.
                r = session.get(url, stream=True, timeout=60)
            else:
                r = session.get(url, timeout=60)

            if r.status_code < 400:
                r.close()
                return domain, url

            last_error = f"{url} -> HTTP {r.status_code}"
            r.close()

        except Exception as e:
            last_error = f"{url} -> {repr(e)}"

    raise RuntimeError(f"No working {kind} URL found for dataset {dataset_id}. Last error: {last_error}")


def download_streaming(url: str, out_path: Path, desc: str, overwrite: bool = False) -> Path:
    """
    Streaming download with .part temporary file.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if out_path.exists() and not overwrite and is_probably_valid_csv(out_path):
        print(f"[skip existing valid file] {out_path} ({file_size_mb(out_path)} MB)")
        log_event(
            {
                "status": "exists_valid",
                "url": url,
                "path": str(out_path),
                "size_mb": file_size_mb(out_path),
            }
        )
        return out_path

    part_path = out_path.with_suffix(out_path.suffix + ".part")
    if part_path.exists():
        part_path.unlink()

    print("\n" + "-" * 100)
    print("[download]", desc)
    print("URL:", url)
    print("OUT:", out_path)
    print("-" * 100)

    with session.get(url, stream=True, timeout=300) as r:
        if r.status_code >= 400:
            raise RuntimeError(f"HTTP {r.status_code} while downloading {url}")

        total = int(r.headers.get("content-length", 0))
        with part_path.open("wb") as f, tqdm(
            total=total,
            unit="B",
            unit_scale=True,
            desc=desc,
        ) as pbar:
            for chunk in r.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    f.write(chunk)
                    pbar.update(len(chunk))

    part_path.replace(out_path)

    if not is_probably_valid_csv(out_path):
        raise RuntimeError(f"Downloaded file does not look like a valid CSV: {out_path}")

    log_event(
        {
            "status": "downloaded",
            "url": url,
            "path": str(out_path),
            "size_mb": file_size_mb(out_path),
        }
    )

    print(f"[saved] {out_path} ({file_size_mb(out_path)} MB)")
    return out_path


def save_json_from_url(url: str, out_path: Path, desc: str) -> bool:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        r = session.get(url, timeout=120)
        if r.status_code >= 400:
            print(f"[metadata warn] {desc}: HTTP {r.status_code}")
            log_event(
                {
                    "status": "metadata_failed",
                    "url": url,
                    "path": str(out_path),
                    "reason": f"HTTP {r.status_code}",
                }
            )
            return False

        data = r.json()
        out_path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"[metadata saved] {out_path}")
        log_event(
            {
                "status": "metadata_saved",
                "url": url,
                "path": str(out_path),
            }
        )
        return True

    except Exception as e:
        print(f"[metadata warn] {desc}: {e}")
        log_event(
            {
                "status": "metadata_failed",
                "url": url,
                "path": str(out_path),
                "reason": repr(e),
            }
        )
        return False


def get_socrata_row_count(url: str) -> int | None:
    try:
        r = session.get(url, timeout=120)
        if r.status_code >= 400:
            return None
        data = r.json()
        if isinstance(data, list) and len(data) > 0:
            # Socrata returns [{"count": "123"}]
            val = list(data[0].values())[0]
            return int(val)
        return None
    except Exception:
        return None


def write_preview_and_schema(csv_path: Path, out_dir: Path, year: int) -> dict:
    """
    Save:
    - preview first 20 rows
    - schema inferred by pandas from first rows
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    preview_path = out_dir / f"bts_fmi_{year}_preview_first20.csv"
    schema_path = out_dir / f"bts_fmi_{year}_schema_preview.csv"

    preview = pd.read_csv(csv_path, nrows=20)
    preview.to_csv(preview_path, index=False, encoding="utf-8-sig")

    schema_df = pd.DataFrame(
        {
            "column": preview.columns,
            "pandas_preview_dtype": [str(t) for t in preview.dtypes],
        }
    )
    schema_df.to_csv(schema_path, index=False, encoding="utf-8-sig")

    return {
        "preview_path": str(preview_path),
        "schema_preview_path": str(schema_path),
        "preview_columns": list(preview.columns),
        "preview_n_columns": len(preview.columns),
    }


def convert_csv_to_parquet(csv_path: Path, parquet_path: Path, year: int) -> dict:
    """
    Convert annual CSV to Parquet.
    Uses Polars if available. Falls back to pandas if Polars is unavailable.
    """
    parquet_path = Path(parquet_path)
    parquet_path.parent.mkdir(parents=True, exist_ok=True)

    if parquet_path.exists() and parquet_path.stat().st_size > 0:
        print(f"[skip existing parquet] {parquet_path} ({file_size_mb(parquet_path)} MB)")

        if HAS_POLARS:
            try:
                n_rows = pl.scan_parquet(str(parquet_path)).select(pl.len()).collect().item()
            except Exception:
                n_rows = None
        else:
            n_rows = None

        return {
            "parquet_path": str(parquet_path),
            "parquet_size_mb": file_size_mb(parquet_path),
            "row_count_from_conversion": n_rows,
            "conversion_status": "exists",
        }

    print("\n" + "-" * 100)
    print(f"[convert] CSV -> Parquet for {year}")
    print("CSV:", csv_path)
    print("PARQUET:", parquet_path)
    print("-" * 100)

    if HAS_POLARS:
        # For these annual FMI files, reading one year at a time should be manageable.
        df = pl.read_csv(
            str(csv_path),
            infer_schema_length=10000,
            ignore_errors=False,
            try_parse_dates=False,
        )
        n_rows = df.height
        n_cols = len(df.columns)
        df.write_parquet(str(parquet_path), compression="zstd")
        del df

    else:
        # Slower fallback.
        df = pd.read_csv(csv_path)
        n_rows = len(df)
        n_cols = len(df.columns)
        df.to_parquet(parquet_path, index=False)
        del df

    print(f"[parquet saved] {parquet_path} ({file_size_mb(parquet_path)} MB)")

    return {
        "parquet_path": str(parquet_path),
        "parquet_size_mb": file_size_mb(parquet_path),
        "row_count_from_conversion": n_rows,
        "n_columns_from_conversion": n_cols,
        "conversion_status": "converted",
    }


# ------------------------------------------------------------
# 3. Download all FMI annual files
# ------------------------------------------------------------

manifest_rows = []

for year, info in FMI_DATASETS.items():
    dataset_id = info["dataset_id"]
    year_dir = FMI_ROOT / str(year)
    meta_year_dir = METADATA_ROOT / str(year)
    year_dir.mkdir(parents=True, exist_ok=True)
    meta_year_dir.mkdir(parents=True, exist_ok=True)

    csv_path = year_dir / f"bts_fmi_county_travel_times_{year}_{dataset_id}.csv"
    parquet_path = year_dir / f"bts_fmi_county_travel_times_{year}_{dataset_id}.parquet"

    print("\n" + "=" * 100)
    print(f"YEAR {year} | DATASET ID {dataset_id}")
    print("=" * 100)

    # Find working domain and URL.
    domain, csv_url = get_first_working_url(dataset_id, "csv")
    urls = build_urls(domain, dataset_id)

    print("Working Socrata domain:", domain)

    # Save metadata and columns metadata.
    save_json_from_url(
        urls["metadata"],
        meta_year_dir / f"bts_fmi_{year}_{dataset_id}_metadata.json",
        desc=f"{year} metadata",
    )
    save_json_from_url(
        urls["columns"],
        meta_year_dir / f"bts_fmi_{year}_{dataset_id}_columns.json",
        desc=f"{year} columns metadata",
    )

    # Get Socrata row count if API supports it.
    socrata_row_count = get_socrata_row_count(urls["count"])
    print("Socrata API row count:", socrata_row_count)

    # Download CSV.
    download_start = time.time()

    csv_status = "unknown"
    try:
        csv_path = download_streaming(
            csv_url,
            csv_path,
            desc=f"BTS FMI {year}",
            overwrite=not SKIP_EXISTING_VALID_FILES,
        )
        csv_status = "ok"
    except Exception as e:
        # Try fallback domain if first domain failed.
        print(f"[warn] primary download failed for {year}: {e}")
        log_event(
            {
                "status": "download_failed_primary",
                "year": year,
                "dataset_id": dataset_id,
                "url": csv_url,
                "reason": repr(e),
            }
        )

        fallback_domains = [d for d in SOCRATA_DOMAINS if d != domain]
        fallback_ok = False

        for fallback_domain in fallback_domains:
            fallback_url = build_urls(fallback_domain, dataset_id)["csv"]
            try:
                csv_path = download_streaming(
                    fallback_url,
                    csv_path,
                    desc=f"BTS FMI {year} fallback",
                    overwrite=True,
                )
                domain = fallback_domain
                urls = build_urls(domain, dataset_id)
                csv_status = "ok_fallback"
                fallback_ok = True
                break
            except Exception as e2:
                print(f"[warn] fallback failed for {year} on {fallback_domain}: {e2}")

        if not fallback_ok:
            raise RuntimeError(f"All download attempts failed for year {year}, dataset {dataset_id}")

    download_seconds = round(time.time() - download_start, 2)

    # Preview and schema.
    preview_info = write_preview_and_schema(csv_path, meta_year_dir, year)
    print("Preview columns:")
    for c in preview_info["preview_columns"]:
        print("  -", c)

    # Convert to Parquet.
    parquet_info = {}
    if CONVERT_TO_PARQUET:
        try:
            parquet_info = convert_csv_to_parquet(csv_path, parquet_path, year)
        except Exception as e:
            print(f"[warn] Parquet conversion failed for {year}: {e}")
            parquet_info = {
                "parquet_path": str(parquet_path),
                "parquet_size_mb": None,
                "row_count_from_conversion": None,
                "conversion_status": f"failed: {repr(e)}",
            }

    # Optional SHA256.
    if COMPUTE_SHA256:
        csv_sha256 = sha256_file(csv_path)
    else:
        csv_sha256 = None

    row = {
        "year": year,
        "dataset_id": dataset_id,
        "expected_unique_pairs_million": info["expected_unique_pairs_million"],
        "socrata_domain_used": domain,
        "csv_url": csv_url,
        "about_url": urls["about"],
        "csv_path": str(csv_path),
        "csv_size_mb": file_size_mb(csv_path),
        "csv_status": csv_status,
        "csv_sha256": csv_sha256,
        "download_seconds": download_seconds,
        "socrata_api_row_count": socrata_row_count,
        **preview_info,
        **parquet_info,
    }

    manifest_rows.append(row)

    # Save manifest after each year so progress is not lost.
    pd.DataFrame(manifest_rows).to_csv(MANIFEST_PATH, index=False, encoding="utf-8-sig")
    print(f"[manifest updated] {MANIFEST_PATH}")

# ------------------------------------------------------------
# 4. Final manifest and summary
# ------------------------------------------------------------

manifest = pd.DataFrame(manifest_rows)
manifest.to_csv(MANIFEST_PATH, index=False, encoding="utf-8-sig")

print("\n" + "=" * 100)
print("BTS FMI DOWNLOAD COMPLETE")
print("=" * 100)
print("FMI root:", FMI_ROOT)
print("Manifest:", MANIFEST_PATH)
print("Log:", LOG_PATH)
print("=" * 100)

display_cols = [
    "year",
    "dataset_id",
    "csv_status",
    "csv_size_mb",
    "parquet_size_mb",
    "socrata_api_row_count",
    "row_count_from_conversion",
    "download_seconds",
    "csv_path",
]
existing_cols = [c for c in display_cols if c in manifest.columns]
display(manifest[existing_cols])

print("\nNext files to check:")
for year, info in FMI_DATASETS.items():
    dataset_id = info["dataset_id"]
    print(FMI_ROOT / str(year) / f"bts_fmi_county_travel_times_{year}_{dataset_id}.csv")
    if CONVERT_TO_PARQUET:
        print(FMI_ROOT / str(year) / f"bts_fmi_county_travel_times_{year}_{dataset_id}.parquet")

====================================================================================================
BTS FMI downloader
Python executable: D:\apphome\anaconda3\python.exe
DATA_ROOT: E:\NetworkOptimization\pythonProject1\Data
FMI_ROOT: E:\NetworkOptimization\pythonProject1\Data\02_fmi
HAS_POLARS: False
====================================================================================================

====================================================================================================
YEAR 2018 | DATASET ID xx4g-5dg2
====================================================================================================
Working Socrata domain: https://data.bts.gov
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2018\bts_fmi_2018_xx4g-5dg2_metadata.json
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2018\bts_fmi_2018_xx4g-5dg2_columns.json
Socrata API row count: 2080775

----------------------------------------------------------------------------------------------------
[download] BTS FMI 2018
URL: https://data.bts.gov/api/views/xx4g-5dg2/rows.csv?accessType=DOWNLOAD
OUT: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2018\bts_fmi_county_travel_times_2018_xx4g-5dg2.csv
----------------------------------------------------------------------------------------------------

BTS FMI 2018: 0.00B [00:00, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2018\bts_fmi_county_travel_times_2018_xx4g-5dg2.csv (131.977 MB)
Preview columns:
  - Origin CTFIPS
  - Origin State
  - Origin County
  - Destination CTFIPS
  - Destination State
  - Destination County
  - Year
  - Crossings
  - 25th Percentile (minutes)
  - 50th Percentile (minutes)
  - 75th Percentile (minutes)

----------------------------------------------------------------------------------------------------
[convert] CSV -> Parquet for 2018
CSV: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2018\bts_fmi_county_travel_times_2018_xx4g-5dg2.csv
PARQUET: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2018\bts_fmi_county_travel_times_2018_xx4g-5dg2.parquet
----------------------------------------------------------------------------------------------------
[parquet saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2018\bts_fmi_county_travel_times_2018_xx4g-5dg2.parquet (46.312 MB)
[manifest updated] E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_manifest.csv

====================================================================================================
YEAR 2019 | DATASET ID sn4k-eiea
====================================================================================================
Working Socrata domain: https://data.bts.gov
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2019\bts_fmi_2019_sn4k-eiea_metadata.json
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2019\bts_fmi_2019_sn4k-eiea_columns.json
Socrata API row count: 4130615

----------------------------------------------------------------------------------------------------
[download] BTS FMI 2019
URL: https://data.bts.gov/api/views/sn4k-eiea/rows.csv?accessType=DOWNLOAD
OUT: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2019\bts_fmi_county_travel_times_2019_sn4k-eiea.csv
----------------------------------------------------------------------------------------------------

BTS FMI 2019: 0.00B [00:00, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2019\bts_fmi_county_travel_times_2019_sn4k-eiea.csv (261.0 MB)
Preview columns:
  - Origin CTFIPS
  - Origin State
  - Origin County
  - Destination CTFIPS
  - Destination State
  - Destination County
  - Year
  - Movements
  - 25th Percentile (minutes)
  - 50th Percentile (minutes)
  - 75th Percentile (minutes)

----------------------------------------------------------------------------------------------------
[convert] CSV -> Parquet for 2019
CSV: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2019\bts_fmi_county_travel_times_2019_sn4k-eiea.csv
PARQUET: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2019\bts_fmi_county_travel_times_2019_sn4k-eiea.parquet
----------------------------------------------------------------------------------------------------
[parquet saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2019\bts_fmi_county_travel_times_2019_sn4k-eiea.parquet (94.943 MB)
[manifest updated] E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_manifest.csv

====================================================================================================
YEAR 2020 | DATASET ID dggd-bg3y
====================================================================================================
Working Socrata domain: https://data.bts.gov
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2020\bts_fmi_2020_dggd-bg3y_metadata.json
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2020\bts_fmi_2020_dggd-bg3y_columns.json
Socrata API row count: 4429137

----------------------------------------------------------------------------------------------------
[download] BTS FMI 2020
URL: https://data.bts.gov/api/views/dggd-bg3y/rows.csv?accessType=DOWNLOAD
OUT: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2020\bts_fmi_county_travel_times_2020_dggd-bg3y.csv
----------------------------------------------------------------------------------------------------

BTS FMI 2020: 0.00B [00:00, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2020\bts_fmi_county_travel_times_2020_dggd-bg3y.csv (281.613 MB)
Preview columns:
  - Origin CTFIPS
  - Origin State
  - Origin County
  - Destination CTFIPS
  - Destination State
  - Destination County
  - Year
  - Movements
  - 25th Percentile (minutes)
  - 50th Percentile (minutes)
  - 75th Percentile (minutes)

----------------------------------------------------------------------------------------------------
[convert] CSV -> Parquet for 2020
CSV: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2020\bts_fmi_county_travel_times_2020_dggd-bg3y.csv
PARQUET: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2020\bts_fmi_county_travel_times_2020_dggd-bg3y.parquet
----------------------------------------------------------------------------------------------------
[parquet saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2020\bts_fmi_county_travel_times_2020_dggd-bg3y.parquet (102.526 MB)
[manifest updated] E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_manifest.csv

====================================================================================================
YEAR 2021 | DATASET ID mayv-2qfz
====================================================================================================
Working Socrata domain: https://data.bts.gov
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2021\bts_fmi_2021_mayv-2qfz_metadata.json
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2021\bts_fmi_2021_mayv-2qfz_columns.json
Socrata API row count: 4248604

----------------------------------------------------------------------------------------------------
[download] BTS FMI 2021
URL: https://data.bts.gov/api/views/mayv-2qfz/rows.csv?accessType=DOWNLOAD
OUT: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2021\bts_fmi_county_travel_times_2021_mayv-2qfz.csv
----------------------------------------------------------------------------------------------------

BTS FMI 2021: 0.00B [00:00, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2021\bts_fmi_county_travel_times_2021_mayv-2qfz.csv (270.129 MB)
Preview columns:
  - Origin CTFIPS
  - Origin State
  - Origin County
  - Destination CTFIPS
  - Destination State
  - Destination County
  - Year
  - Movements
  - 25th Percentile (minutes)
  - 50th Percentile (minutes)
  - 75th Percentile (minutes)

----------------------------------------------------------------------------------------------------
[convert] CSV -> Parquet for 2021
CSV: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2021\bts_fmi_county_travel_times_2021_mayv-2qfz.csv
PARQUET: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2021\bts_fmi_county_travel_times_2021_mayv-2qfz.parquet
----------------------------------------------------------------------------------------------------
[parquet saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2021\bts_fmi_county_travel_times_2021_mayv-2qfz.parquet (98.444 MB)
[manifest updated] E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_manifest.csv

====================================================================================================
YEAR 2022 | DATASET ID d7b8-pmxm
====================================================================================================
Working Socrata domain: https://data.bts.gov
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2022\bts_fmi_2022_d7b8-pmxm_metadata.json
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2022\bts_fmi_2022_d7b8-pmxm_columns.json
Socrata API row count: 3807134

----------------------------------------------------------------------------------------------------
[download] BTS FMI 2022
URL: https://data.bts.gov/api/views/d7b8-pmxm/rows.csv?accessType=DOWNLOAD
OUT: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2022\bts_fmi_county_travel_times_2022_d7b8-pmxm.csv
----------------------------------------------------------------------------------------------------

BTS FMI 2022: 0.00B [00:00, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2022\bts_fmi_county_travel_times_2022_d7b8-pmxm.csv (241.886 MB)
Preview columns:
  - Origin CTFIPS
  - Origin State
  - Origin County
  - Destination CTFIPS
  - Destination State
  - Destination County
  - Year
  - Movements
  - 25th Percentile (minutes)
  - 50th Percentile (minutes)
  - 75th Percentile (minutes)

----------------------------------------------------------------------------------------------------
[convert] CSV -> Parquet for 2022
CSV: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2022\bts_fmi_county_travel_times_2022_d7b8-pmxm.csv
PARQUET: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2022\bts_fmi_county_travel_times_2022_d7b8-pmxm.parquet
----------------------------------------------------------------------------------------------------
[parquet saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2022\bts_fmi_county_travel_times_2022_d7b8-pmxm.parquet (87.69 MB)
[manifest updated] E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_manifest.csv

====================================================================================================
YEAR 2023 | DATASET ID ez58-m3b4
====================================================================================================
Working Socrata domain: https://data.bts.gov
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2023\bts_fmi_2023_ez58-m3b4_metadata.json
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2023\bts_fmi_2023_ez58-m3b4_columns.json
Socrata API row count: 3642150

----------------------------------------------------------------------------------------------------
[download] BTS FMI 2023
URL: https://data.bts.gov/api/views/ez58-m3b4/rows.csv?accessType=DOWNLOAD
OUT: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2023\bts_fmi_county_travel_times_2023_ez58-m3b4.csv
----------------------------------------------------------------------------------------------------

BTS FMI 2023: 0.00B [00:00, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2023\bts_fmi_county_travel_times_2023_ez58-m3b4.csv (231.176 MB)
Preview columns:
  - Origin CTFIPS
  - Origin State
  - Origin County
  - Destination CTFIPS
  - Destination State
  - Destination County
  - Year
  - Movements
  - 25th Percentile (minutes)
  - 50th Percentile (minutes)
  - 75th Percentile (minutes)

----------------------------------------------------------------------------------------------------
[convert] CSV -> Parquet for 2023
CSV: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2023\bts_fmi_county_travel_times_2023_ez58-m3b4.csv
PARQUET: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2023\bts_fmi_county_travel_times_2023_ez58-m3b4.parquet
----------------------------------------------------------------------------------------------------
[parquet saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2023\bts_fmi_county_travel_times_2023_ez58-m3b4.parquet (83.284 MB)
[manifest updated] E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_manifest.csv

====================================================================================================
YEAR 2024 | DATASET ID uta5-4eu5
====================================================================================================
Working Socrata domain: https://data.bts.gov
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2024\bts_fmi_2024_uta5-4eu5_metadata.json
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\_metadata\2024\bts_fmi_2024_uta5-4eu5_columns.json
Socrata API row count: 3585730

----------------------------------------------------------------------------------------------------
[download] BTS FMI 2024
URL: https://data.bts.gov/api/views/uta5-4eu5/rows.csv?accessType=DOWNLOAD
OUT: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2024\bts_fmi_county_travel_times_2024_uta5-4eu5.csv
----------------------------------------------------------------------------------------------------

BTS FMI 2024: 0.00B [00:00, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2024\bts_fmi_county_travel_times_2024_uta5-4eu5.csv (227.27 MB)
Preview columns:
  - Origin CTFIPS
  - Origin State
  - Origin County
  - Destination CTFIPS
  - Destination State
  - Destination County
  - Year
  - Movements
  - 25th Percentile (minutes)
  - 50th Percentile (minutes)
  - 75th Percentile (minutes)

----------------------------------------------------------------------------------------------------
[convert] CSV -> Parquet for 2024
CSV: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2024\bts_fmi_county_travel_times_2024_uta5-4eu5.csv
PARQUET: E:\NetworkOptimization\pythonProject1\Data\02_fmi\2024\bts_fmi_county_travel_times_2024_uta5-4eu5.parquet
----------------------------------------------------------------------------------------------------
[parquet saved] E:\NetworkOptimization\pythonProject1\Data\02_fmi\2024\bts_fmi_county_travel_times_2024_uta5-4eu5.parquet (82.404 MB)
[manifest updated] E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_manifest.csv

====================================================================================================
BTS FMI DOWNLOAD COMPLETE
====================================================================================================
FMI root: E:\NetworkOptimization\pythonProject1\Data\02_fmi
Manifest: E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_manifest.csv
Log: E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_log.jsonl
====================================================================================================

,year,dataset_id,csv_status,csv_size_mb,parquet_size_mb,socrata_api_row_count,row_count_from_conversion,download_seconds,csv_path
0,2018,xx4g-5dg2,ok,131.977,46.312,2080775,2080775,46.10,E:\NetworkOptimization\pythonProject1\Data\02_...
1,2019,sn4k-eiea,ok,261.000,94.943,4130615,4130615,90.53,E:\NetworkOptimization\pythonProject1\Data\02_...
2,2020,dggd-bg3y,ok,281.613,102.526,4429137,4429137,424.03,E:\NetworkOptimization\pythonProject1\Data\02_...
3,2021,mayv-2qfz,ok,270.129,98.444,4248604,4248604,663.67,E:\NetworkOptimization\pythonProject1\Data\02_...
4,2022,d7b8-pmxm,ok,241.886,87.690,3807134,3807134,77.15,E:\NetworkOptimization\pythonProject1\Data\02_...
5,2023,ez58-m3b4,ok,231.176,83.284,3642150,3642150,482.48,E:\NetworkOptimization\pythonProject1\Data\02_...
6,2024,uta5-4eu5,ok,227.270,82.404,3585730,3585730,176.66,E:\NetworkOptimization\pythonProject1\Data\02_...

Next files to check:
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2018\bts_fmi_county_travel_times_2018_xx4g-5dg2.csv
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2018\bts_fmi_county_travel_times_2018_xx4g-5dg2.parquet
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2019\bts_fmi_county_travel_times_2019_sn4k-eiea.csv
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2019\bts_fmi_county_travel_times_2019_sn4k-eiea.parquet
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2020\bts_fmi_county_travel_times_2020_dggd-bg3y.csv
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2020\bts_fmi_county_travel_times_2020_dggd-bg3y.parquet
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2021\bts_fmi_county_travel_times_2021_mayv-2qfz.csv
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2021\bts_fmi_county_travel_times_2021_mayv-2qfz.parquet
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2022\bts_fmi_county_travel_times_2022_d7b8-pmxm.csv
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2022\bts_fmi_county_travel_times_2022_d7b8-pmxm.parquet
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2023\bts_fmi_county_travel_times_2023_ez58-m3b4.csv
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2023\bts_fmi_county_travel_times_2023_ez58-m3b4.parquet
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2024\bts_fmi_county_travel_times_2024_uta5-4eu5.csv
E:\NetworkOptimization\pythonProject1\Data\02_fmi\2024\bts_fmi_county_travel_times_2024_uta5-4eu5.parquet

In [3]:
# ============================================================
# FREIGHT-MNet: NTAD / ArcGIS Geospatial Downloader v2
#
# FIXED VERSION:
#   - Uses ArcGIS f=json instead of f=geojson
#   - Converts Esri geometry to Shapely manually
#   - No infinite split retry
#   - Fully resumable: rerun the cell and completed chunks are skipped
#
# Save root:
#   E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial
#
# Downloads:
#   1. FAF5 Regions
#   2. FAF5 Network Links
#   3. FAF5 Network Nodes
#   4. NARN Lines
#   5. NARN Nodes
#   6. Intermodal Freight Facilities Rail TOFC/COFC
# ============================================================

from pathlib import Path
import json
import time
import traceback
import math
from typing import Any, Dict, List, Optional, Tuple

import requests
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, LineString, MultiLineString, Polygon, MultiPolygon
from shapely.validation import make_valid
from tqdm.auto import tqdm
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# ------------------------------------------------------------
# 0. Paths and settings
# ------------------------------------------------------------

DATA_ROOT = Path(r"E:\NetworkOptimization\pythonProject1\Data")
NTAD_ROOT = DATA_ROOT / "03_ntad_geospatial"
MANIFEST_ROOT = DATA_ROOT / "00_manifest"

NTAD_ROOT.mkdir(parents=True, exist_ok=True)
MANIFEST_ROOT.mkdir(parents=True, exist_ok=True)

GLOBAL_MANIFEST_PATH = MANIFEST_ROOT / "ntad_arcgis_download_manifest_v2.csv"
GLOBAL_LOG_PATH = MANIFEST_ROOT / "ntad_arcgis_download_log_v2.jsonl"

# Safe batch size. 1000 is more stable than 2000 on some ArcGIS hosted layers.
DEFAULT_BATCH_SIZE = 1000

# Rerun-safe.
RESUME = True

# Keep raw Esri JSON chunks for reproducibility.
SAVE_RAW_JSON = True

# Build combined file for small layers only.
CREATE_SINGLE_FILE_FOR_SMALL_LAYERS = True
SINGLE_FILE_MAX_FEATURES = 10000

# Debug only. Set to None for real full download.
MAX_OBJECTS_PER_LAYER = None

# If True, failed chunks are retried once with smaller sub-batches.
RETRY_FAILED_CHUNKS_WITH_SMALLER_BATCH = True
SMALL_RETRY_BATCH_SIZE = 100

# ------------------------------------------------------------
# 1. Layers
# ------------------------------------------------------------

LAYERS = {
    "faf_regions": {
        "description": "FAF5 Regions / FAF zone polygons",
        "out_subdir": "faf_regions",
        "url": "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Freight_Analysis_Framework_Regions/FeatureServer/0",
    },
    "faf_network_links": {
        "description": "FAF5 Network Links / highway freight network polyline topology",
        "out_subdir": "faf_network_links",
        "url": "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Freight_Analysis_Framework_Network_Links/FeatureServer/0",
    },
    "faf_network_nodes": {
        "description": "FAF5 Network Nodes / highway freight network node topology",
        "out_subdir": "faf_network_nodes",
        "url": "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Freight_Analysis_Framework_Network_Nodes/FeatureServer/0",
    },
    "narn_lines": {
        "description": "North American Rail Network Lines / rail line polyline topology",
        "out_subdir": "narn_lines",
        "url": "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_North_American_Rail_Network_Lines/FeatureServer/0",
    },
    "narn_nodes": {
        "description": "North American Rail Network Nodes / rail node topology",
        "out_subdir": "narn_nodes",
        "url": "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_North_American_Rail_Network_Nodes/FeatureServer/0",
    },
    "intermodal_rail_tofc_cofc": {
        "description": "Intermodal Freight Facilities Rail TOFC/COFC / truck-rail transfer terminals",
        "out_subdir": "intermodal_rail_tofc_cofc",
        "url": "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Intermodal_Freight_Facilities_Rail_TOFC_COFC/FeatureServer/0",
    },
}

# ------------------------------------------------------------
# 2. HTTP session
# ------------------------------------------------------------

session = requests.Session()
session.headers.update({
    "User-Agent": "FREIGHT-MNet academic downloader v2; public USDOT/NTAD ArcGIS REST data"
})

retry = Retry(
    total=8,
    connect=8,
    read=8,
    status=8,
    backoff_factor=1.5,
    status_forcelist=[408, 429, 500, 502, 503, 504],
    allowed_methods=["GET", "POST"],
    raise_on_status=False,
)

adapter = HTTPAdapter(max_retries=retry, pool_connections=8, pool_maxsize=8)
session.mount("http://", adapter)
session.mount("https://", adapter)

# ------------------------------------------------------------
# 3. Helpers
# ------------------------------------------------------------

def log_event(record: Dict[str, Any]) -> None:
    record = dict(record)
    record["timestamp"] = pd.Timestamp.now().isoformat()
    with GLOBAL_LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def request_json(
    url: str,
    params: Optional[Dict[str, Any]] = None,
    method: str = "GET",
    timeout: int = 300,
) -> Dict[str, Any]:
    if method.upper() == "POST":
        r = session.post(url, data=params, timeout=timeout)
    else:
        r = session.get(url, params=params, timeout=timeout)

    if r.status_code >= 400:
        raise RuntimeError(f"HTTP {r.status_code}: {r.text[:500]}")

    try:
        data = r.json()
    except Exception as e:
        raise RuntimeError(f"Could not parse JSON. First 500 chars: {r.text[:500]}") from e

    if isinstance(data, dict) and "error" in data:
        raise RuntimeError(f"ArcGIS error: {data['error']}")

    return data


def file_size_mb(path: Path) -> float:
    if not path.exists():
        return 0.0
    return round(path.stat().st_size / 1024**2, 3)


def get_metadata(layer_url: str) -> Dict[str, Any]:
    return request_json(layer_url, params={"f": "json"}, method="GET", timeout=120)


def get_oid_field(metadata: Dict[str, Any]) -> str:
    if metadata.get("objectIdField"):
        return metadata["objectIdField"]
    if metadata.get("objectIdFieldName"):
        return metadata["objectIdFieldName"]
    for f in metadata.get("fields", []):
        if f.get("type") == "esriFieldTypeOID":
            return f["name"]
    return "OBJECTID"


def get_count(layer_url: str) -> int:
    data = request_json(
        layer_url + "/query",
        params={
            "where": "1=1",
            "returnCountOnly": "true",
            "f": "json",
        },
        method="GET",
        timeout=120,
    )
    return int(data["count"])


def get_object_ids(layer_url: str) -> List[int]:
    data = request_json(
        layer_url + "/query",
        params={
            "where": "1=1",
            "returnIdsOnly": "true",
            "f": "json",
        },
        method="GET",
        timeout=300,
    )
    object_ids = sorted(int(x) for x in data["objectIds"])
    if MAX_OBJECTS_PER_LAYER is not None:
        object_ids = object_ids[:MAX_OBJECTS_PER_LAYER]
    return object_ids


def chunk_list(xs: List[int], size: int) -> List[List[int]]:
    return [xs[i:i + size] for i in range(0, len(xs), size)]


def sanitize_attributes(attrs: Dict[str, Any]) -> Dict[str, Any]:
    clean = {}
    for k, v in attrs.items():
        if isinstance(v, (str, int, float, bool)) or v is None:
            clean[k] = v
        else:
            clean[k] = json.dumps(v, ensure_ascii=False)
    return clean


def close_ring(coords: List[List[float]]) -> List[Tuple[float, float]]:
    pts = [(float(x), float(y)) for x, y, *rest in coords]
    if len(pts) >= 3 and pts[0] != pts[-1]:
        pts.append(pts[0])
    return pts


def ring_signed_area(ring: List[Tuple[float, float]]) -> float:
    area = 0.0
    for i in range(len(ring) - 1):
        x1, y1 = ring[i]
        x2, y2 = ring[i + 1]
        area += x1 * y2 - x2 * y1
    return area / 2.0


def esri_polygon_to_shapely(rings_raw: List[List[List[float]]]):
    """
    Convert Esri polygon rings to Shapely.
    Esri often uses ring orientation to distinguish outer rings and holes.
    This function is conservative and tries to produce valid polygons.
    """
    rings = []
    for r in rings_raw:
        ring = close_ring(r)
        if len(ring) >= 4:
            rings.append(ring)

    if not rings:
        return None

    # Use orientation as a heuristic.
    # If it fails, fallback to first ring as exterior.
    outer_candidates = []
    hole_candidates = []

    for ring in rings:
        area = ring_signed_area(ring)
        # Esri convention often has outer rings clockwise.
        # In lon/lat with this formula, clockwise tends to be negative.
        if area < 0:
            outer_candidates.append(ring)
        else:
            hole_candidates.append(ring)

    if not outer_candidates:
        outer_candidates = [rings[0]]
        hole_candidates = rings[1:]

    polygons = []

    for outer in outer_candidates:
        outer_poly = Polygon(outer)
        holes_for_outer = []

        for hole in hole_candidates:
            try:
                test_point = Point(hole[0])
                if outer_poly.contains(test_point):
                    holes_for_outer.append(hole)
            except Exception:
                pass

        try:
            poly = Polygon(outer, holes=holes_for_outer)
            poly = make_valid(poly)
            if not poly.is_empty:
                polygons.append(poly)
        except Exception:
            pass

    if not polygons:
        try:
            poly = Polygon(rings[0], holes=rings[1:])
            poly = make_valid(poly)
            return poly if not poly.is_empty else None
        except Exception:
            return None

    if len(polygons) == 1:
        return polygons[0]

    mp = MultiPolygon([p for p in polygons if p.geom_type == "Polygon"])
    mp = make_valid(mp)
    return mp if not mp.is_empty else None


def esri_geometry_to_shapely(geom: Optional[Dict[str, Any]], geometry_type: str):
    if geom is None:
        return None

    if "x" in geom and "y" in geom:
        return Point(float(geom["x"]), float(geom["y"]))

    if "paths" in geom:
        lines = []
        for path in geom["paths"]:
            coords = [(float(x), float(y)) for x, y, *rest in path]
            if len(coords) >= 2:
                try:
                    lines.append(LineString(coords))
                except Exception:
                    pass
        if not lines:
            return None
        if len(lines) == 1:
            return lines[0]
        return MultiLineString(lines)

    if "rings" in geom:
        return esri_polygon_to_shapely(geom["rings"])

    return None


def query_features_by_oids_json(layer_url: str, oid_batch: List[int]) -> Dict[str, Any]:
    """
    Query ArcGIS features as Esri JSON.
    This is more stable than f=geojson for these layers.
    """
    params = {
        "objectIds": ",".join(str(x) for x in oid_batch),
        "outFields": "*",
        "returnGeometry": "true",
        "outSR": "4326",
        "f": "json",
    }
    return request_json(layer_url + "/query", params=params, method="POST", timeout=300)


def esri_json_to_gdf(data: Dict[str, Any], geometry_type: str) -> gpd.GeoDataFrame:
    rows = []
    geoms = []

    for feat in data.get("features", []):
        attrs = sanitize_attributes(feat.get("attributes", {}))
        geom = esri_geometry_to_shapely(feat.get("geometry"), geometry_type)
        rows.append(attrs)
        geoms.append(geom)

    if not rows:
        return gpd.GeoDataFrame(columns=["geometry"], geometry=[], crs="EPSG:4326")

    df = pd.DataFrame(rows)
    gdf = gpd.GeoDataFrame(df, geometry=geoms, crs="EPSG:4326")
    return gdf


def parquet_chunk_valid(path: Path) -> bool:
    if not path.exists() or path.stat().st_size == 0:
        return False
    try:
        gdf = gpd.read_parquet(path)
        return len(gdf) > 0
    except Exception:
        return False


def download_chunk(
    layer_name: str,
    layer_url: str,
    geometry_type: str,
    oid_batch: List[int],
    chunk_index: int,
    raw_dir: Path,
    parquet_dir: Path,
) -> Dict[str, Any]:
    parquet_path = parquet_dir / f"{layer_name}__chunk_{chunk_index:05d}.parquet"
    raw_path = raw_dir / f"{layer_name}__chunk_{chunk_index:05d}.json"

    if RESUME and parquet_chunk_valid(parquet_path):
        gdf = gpd.read_parquet(parquet_path)
        return {
            "layer": layer_name,
            "chunk_index": chunk_index,
            "status": "exists_valid",
            "n_oids_requested": len(oid_batch),
            "n_rows": len(gdf),
            "parquet_path": str(parquet_path),
            "parquet_size_mb": file_size_mb(parquet_path),
            "raw_json_path": str(raw_path) if raw_path.exists() else None,
        }

    try:
        data = query_features_by_oids_json(layer_url, oid_batch)

        if SAVE_RAW_JSON:
            tmp_raw = raw_path.with_suffix(".json.part")
            tmp_raw.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
            tmp_raw.replace(raw_path)

        gdf = esri_json_to_gdf(data, geometry_type=geometry_type)

        if len(gdf) == 0:
            raise RuntimeError("ArcGIS returned 0 features for this chunk.")

        tmp_parquet = parquet_path.with_suffix(".parquet.part")
        gdf.to_parquet(tmp_parquet, index=False)
        tmp_parquet.replace(parquet_path)

        return {
            "layer": layer_name,
            "chunk_index": chunk_index,
            "status": "downloaded",
            "n_oids_requested": len(oid_batch),
            "n_rows": len(gdf),
            "parquet_path": str(parquet_path),
            "parquet_size_mb": file_size_mb(parquet_path),
            "raw_json_path": str(raw_path),
            "raw_json_size_mb": file_size_mb(raw_path),
        }

    except Exception as e:
        return {
            "layer": layer_name,
            "chunk_index": chunk_index,
            "status": "failed",
            "n_oids_requested": len(oid_batch),
            "n_rows": None,
            "parquet_path": str(parquet_path),
            "raw_json_path": str(raw_path),
            "error": repr(e),
            "traceback": traceback.format_exc()[:3000],
        }


def combine_small_layer(layer_name: str, layer_dir: Path, expected_count: int) -> Dict[str, Any]:
    if not CREATE_SINGLE_FILE_FOR_SMALL_LAYERS:
        return {"single_file_status": "disabled"}

    if expected_count > SINGLE_FILE_MAX_FEATURES:
        return {"single_file_status": f"skipped_large_layer_{expected_count}_features"}

    parquet_dir = layer_dir / "parquet_chunks_v2"
    parquet_files = sorted(parquet_dir.glob("*.parquet"))

    if not parquet_files:
        return {"single_file_status": "no_parquet_chunks"}

    try:
        gdfs = [gpd.read_parquet(p) for p in parquet_files]
        full = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True), crs="EPSG:4326")

        out_parquet = layer_dir / f"{layer_name}_v2.parquet"
        out_geojson = layer_dir / f"{layer_name}_v2.geojson"
        out_gpkg = layer_dir / f"{layer_name}_v2.gpkg"

        full.to_parquet(out_parquet, index=False)
        full.to_file(out_geojson, driver="GeoJSON")
        full.to_file(out_gpkg, layer=layer_name, driver="GPKG")

        return {
            "single_file_status": "created",
            "single_n_rows": len(full),
            "single_parquet_path": str(out_parquet),
            "single_geojson_path": str(out_geojson),
            "single_gpkg_path": str(out_gpkg),
        }

    except Exception as e:
        return {
            "single_file_status": "failed",
            "single_file_error": repr(e),
        }


def save_fields(metadata: Dict[str, Any], fields_path: Path) -> None:
    fields = metadata.get("fields", [])
    if fields:
        pd.DataFrame(fields).to_csv(fields_path, index=False, encoding="utf-8-sig")


# ------------------------------------------------------------
# 4. Layer downloader
# ------------------------------------------------------------

def download_layer_v2(layer_name: str, cfg: Dict[str, Any]) -> Dict[str, Any]:
    print("\n" + "=" * 120)
    print("LAYER:", layer_name)
    print(cfg["description"])
    print("=" * 120)

    layer_url = cfg["url"]
    layer_dir = NTAD_ROOT / cfg["out_subdir"]

    metadata_dir = layer_dir / "metadata_v2"
    raw_dir = layer_dir / "raw_esri_json_chunks_v2"
    parquet_dir = layer_dir / "parquet_chunks_v2"

    for d in [layer_dir, metadata_dir, raw_dir, parquet_dir]:
        d.mkdir(parents=True, exist_ok=True)

    metadata = get_metadata(layer_url)
    oid_field = get_oid_field(metadata)
    geometry_type = metadata.get("geometryType", "unknown")
    max_record_count = int(metadata.get("maxRecordCount") or DEFAULT_BATCH_SIZE)
    batch_size = min(DEFAULT_BATCH_SIZE, max_record_count)

    expected_count = get_count(layer_url)
    object_ids = get_object_ids(layer_url)

    metadata_path = metadata_dir / f"{layer_name}_metadata_v2.json"
    fields_path = metadata_dir / f"{layer_name}_fields_v2.csv"
    object_ids_path = metadata_dir / f"{layer_name}_object_ids_v2.json"
    source_info_path = metadata_dir / f"{layer_name}_source_info_v2.json"

    metadata_path.write_text(json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")
    save_fields(metadata, fields_path)
    object_ids_path.write_text(json.dumps(object_ids), encoding="utf-8")

    source_info = {
        "layer": layer_name,
        "description": cfg["description"],
        "layer_url": layer_url,
        "oid_field": oid_field,
        "geometry_type": geometry_type,
        "max_record_count": max_record_count,
        "batch_size": batch_size,
        "expected_count": expected_count,
        "n_object_ids": len(object_ids),
        "crs_requested": "EPSG:4326",
    }
    source_info_path.write_text(json.dumps(source_info, indent=2, ensure_ascii=False), encoding="utf-8")

    print("URL:", layer_url)
    print("OID field:", oid_field)
    print("Geometry type:", geometry_type)
    print("Expected count:", expected_count)
    print("Object IDs:", len(object_ids))
    print("Batch size:", batch_size)

    # Tiny probe before full download.
    print("\nProbe first 3 object IDs...")
    probe_ids = object_ids[:3]
    probe_data = query_features_by_oids_json(layer_url, probe_ids)
    probe_gdf = esri_json_to_gdf(probe_data, geometry_type=geometry_type)
    print("Probe rows:", len(probe_gdf))
    print("Probe columns:", list(probe_gdf.columns)[:30])
    if len(probe_gdf) == 0:
        raise RuntimeError(f"Probe failed for {layer_name}: 0 rows returned.")

    batches = chunk_list(object_ids, batch_size)

    chunk_manifest_path = layer_dir / f"{layer_name}_chunk_manifest_v2.csv"
    chunk_records = []

    # Load previous manifest if exists.
    if RESUME and chunk_manifest_path.exists():
        try:
            previous = pd.read_csv(chunk_manifest_path)
            chunk_records = previous.to_dict("records")
            print(f"Loaded existing chunk manifest: {chunk_manifest_path}")
        except Exception:
            chunk_records = []

    completed_chunks = {
        int(r["chunk_index"])
        for r in chunk_records
        if r.get("status") in {"downloaded", "exists_valid"}
    }

    t0 = time.time()

    for chunk_index, oid_batch in enumerate(tqdm(batches, desc=f"Downloading {layer_name}"), start=1):
        if chunk_index in completed_chunks:
            continue

        rec = download_chunk(
            layer_name=layer_name,
            layer_url=layer_url,
            geometry_type=geometry_type,
            oid_batch=oid_batch,
            chunk_index=chunk_index,
            raw_dir=raw_dir,
            parquet_dir=parquet_dir,
        )

        # If failed, retry in smaller subchunks.
        if (
            rec["status"] == "failed"
            and RETRY_FAILED_CHUNKS_WITH_SMALLER_BATCH
            and len(oid_batch) > SMALL_RETRY_BATCH_SIZE
        ):
            print(f"[small retry] {layer_name} chunk {chunk_index} failed. Retrying with batch={SMALL_RETRY_BATCH_SIZE}")
            sub_batches = chunk_list(oid_batch, SMALL_RETRY_BATCH_SIZE)
            sub_success_rows = 0
            sub_failed = 0

            for sub_i, sub_ids in enumerate(sub_batches, start=1):
                sub_chunk_index = int(f"{chunk_index}{sub_i:03d}")
                sub_rec = download_chunk(
                    layer_name=layer_name,
                    layer_url=layer_url,
                    geometry_type=geometry_type,
                    oid_batch=sub_ids,
                    chunk_index=sub_chunk_index,
                    raw_dir=raw_dir,
                    parquet_dir=parquet_dir,
                )
                chunk_records.append(sub_rec)
                if sub_rec["status"] in {"downloaded", "exists_valid"}:
                    sub_success_rows += int(sub_rec.get("n_rows") or 0)
                else:
                    sub_failed += 1

            rec = {
                "layer": layer_name,
                "chunk_index": chunk_index,
                "status": "split_retry_done",
                "n_oids_requested": len(oid_batch),
                "n_rows": sub_success_rows,
                "sub_failed": sub_failed,
                "parquet_path": None,
                "raw_json_path": None,
            }

        chunk_records.append(rec)

        # Save manifest frequently.
        if chunk_index % 5 == 0 or chunk_index == len(batches):
            pd.DataFrame(chunk_records).to_csv(chunk_manifest_path, index=False, encoding="utf-8-sig")

        if rec["status"] == "failed":
            print("[FAILED CHUNK]", layer_name, chunk_index, rec.get("error"))

        time.sleep(0.03)

    chunk_manifest = pd.DataFrame(chunk_records)
    chunk_manifest.to_csv(chunk_manifest_path, index=False, encoding="utf-8-sig")

    # Summarize from actual parquet files, not only manifest.
    parquet_files = sorted(parquet_dir.glob("*.parquet"))
    actual_rows = 0

    for p in tqdm(parquet_files, desc=f"Counting rows {layer_name}"):
        try:
            actual_rows += len(gpd.read_parquet(p))
        except Exception:
            pass

    single_info = combine_small_layer(layer_name, layer_dir, expected_count=len(object_ids))

    elapsed = round(time.time() - t0, 2)

    summary = {
        "layer": layer_name,
        "description": cfg["description"],
        "status": "ok" if actual_rows == len(object_ids) else "check_count_mismatch",
        "layer_url": layer_url,
        "layer_dir": str(layer_dir),
        "metadata_path": str(metadata_path),
        "fields_path": str(fields_path),
        "object_ids_path": str(object_ids_path),
        "source_info_path": str(source_info_path),
        "chunk_manifest_path": str(chunk_manifest_path),
        "expected_count_arcgis": expected_count,
        "n_object_ids": len(object_ids),
        "n_parquet_chunks": len(parquet_files),
        "actual_rows_from_parquet": actual_rows,
        "geometry_type": geometry_type,
        "elapsed_seconds": elapsed,
        "raw_dir": str(raw_dir),
        "parquet_dir": str(parquet_dir),
        **single_info,
    }

    summary_path = layer_dir / f"{layer_name}_summary_v2.json"
    summary_path.write_text(json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")

    log_event(summary)

    print("\nSUMMARY")
    for k, v in summary.items():
        if k not in {"layer_url"}:
            print(f"  {k}: {v}")

    return summary


# ------------------------------------------------------------
# 5. Run
# ------------------------------------------------------------

print("=" * 120)
print("FREIGHT-MNet NTAD / ArcGIS downloader v2")
print("DATA_ROOT:", DATA_ROOT)
print("NTAD_ROOT:", NTAD_ROOT)
print("GLOBAL_MANIFEST_PATH:", GLOBAL_MANIFEST_PATH)
print("=" * 120)

all_summaries = []

for layer_name, cfg in LAYERS.items():
    try:
        summary = download_layer_v2(layer_name, cfg)
        all_summaries.append(summary)
    except Exception as e:
        err = {
            "layer": layer_name,
            "description": cfg.get("description"),
            "status": "failed",
            "error": repr(e),
            "traceback": traceback.format_exc()[:8000],
        }
        all_summaries.append(err)
        log_event(err)
        print("\nFAILED LAYER:", layer_name)
        print(e)
        print(traceback.format_exc())

global_manifest = pd.DataFrame(all_summaries)
global_manifest.to_csv(GLOBAL_MANIFEST_PATH, index=False, encoding="utf-8-sig")

print("\n" + "=" * 120)
print("NTAD / ArcGIS DOWNLOAD v2 COMPLETE")
print("Manifest:", GLOBAL_MANIFEST_PATH)
print("Log:", GLOBAL_LOG_PATH)
print("=" * 120)

cols = [
    "layer",
    "status",
    "expected_count_arcgis",
    "n_object_ids",
    "actual_rows_from_parquet",
    "n_parquet_chunks",
    "single_file_status",
    "layer_dir",
]
cols = [c for c in cols if c in global_manifest.columns]
display(global_manifest[cols])

========================================================================================================================
FREIGHT-MNet NTAD / ArcGIS downloader v2
DATA_ROOT: E:\NetworkOptimization\pythonProject1\Data
NTAD_ROOT: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial
GLOBAL_MANIFEST_PATH: E:\NetworkOptimization\pythonProject1\Data\00_manifest\ntad_arcgis_download_manifest_v2.csv
========================================================================================================================

========================================================================================================================
LAYER: faf_regions
FAF5 Regions / FAF zone polygons
========================================================================================================================
URL: https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Freight_Analysis_Framework_Regions/FeatureServer/0
OID field: OBJECTID
Geometry type: esriGeometryPolygon
Expected count: 132
Object IDs: 132
Batch size: 1000

Probe first 3 object IDs...
Probe rows: 3
Probe columns: ['OBJECTID', 'CFS17_NAME', 'GEOID', 'ALAND', 'AWATER', 'INTPTLAT', 'INTPTLON', 'CFS07_NAME', 'CFS12_NAME', 'CFS17_NA_1', 'FAF_Zone', 'FAF_Zone_D', 'FAF_Zone_1', 'Shape__Area', 'Shape__Length', 'geometry']

Downloading faf_regions:   0%|          | 0/1 [00:00<?, ?it/s]

[small retry] faf_regions chunk 1 failed. Retrying with batch=100

Counting rows faf_regions: 0it [00:00, ?it/s]

SUMMARY
  layer: faf_regions
  description: FAF5 Regions / FAF zone polygons
  status: check_count_mismatch
  layer_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions
  metadata_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\metadata_v2\faf_regions_metadata_v2.json
  fields_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\metadata_v2\faf_regions_fields_v2.csv
  object_ids_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\metadata_v2\faf_regions_object_ids_v2.json
  source_info_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\metadata_v2\faf_regions_source_info_v2.json
  chunk_manifest_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\faf_regions_chunk_manifest_v2.csv
  expected_count_arcgis: 132
  n_object_ids: 132
  n_parquet_chunks: 0
  actual_rows_from_parquet: 0
  geometry_type: esriGeometryPolygon
  elapsed_seconds: 34.04
  raw_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\raw_esri_json_chunks_v2
  parquet_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\parquet_chunks_v2
  single_file_status: no_parquet_chunks

========================================================================================================================
LAYER: faf_network_links
FAF5 Network Links / highway freight network polyline topology
========================================================================================================================
URL: https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Freight_Analysis_Framework_Network_Links/FeatureServer/0
OID field: OBJECTID
Geometry type: esriGeometryPolyline
Expected count: 487394
Object IDs: 487394
Batch size: 1000

Probe first 3 object IDs...
Probe rows: 3
Probe columns: ['OBJECTID', 'ID', 'LENGTH', 'DIR', 'DATA1', 'VERSION', 'Class', 'Class_Description', 'Road_Name', 'Sign_Rte', 'Rte_Type', 'Rte_Number', 'Rte_Qualifier', 'Country', 'STATE', 'STFIPS', 'County_Name', 'CTFIPS', 'Urban_Code', 'FAFZONE', 'Status', 'F_Class', 'Facility_Type', 'NHS', 'STRAHNET', 'NHFN', 'Truck', 'AB_Lanes', 'BA_Lanes', 'Speed_Limit']

Downloading faf_network_links:   0%|          | 0/488 [00:00<?, ?it/s]

[small retry] faf_network_links chunk 1 failed. Retrying with batch=100
[small retry] faf_network_links chunk 2 failed. Retrying with batch=100
[small retry] faf_network_links chunk 3 failed. Retrying with batch=100
[small retry] faf_network_links chunk 4 failed. Retrying with batch=100
[small retry] faf_network_links chunk 5 failed. Retrying with batch=100
[small retry] faf_network_links chunk 6 failed. Retrying with batch=100
[small retry] faf_network_links chunk 7 failed. Retrying with batch=100
[small retry] faf_network_links chunk 8 failed. Retrying with batch=100
[small retry] faf_network_links chunk 9 failed. Retrying with batch=100
[small retry] faf_network_links chunk 10 failed. Retrying with batch=100
[small retry] faf_network_links chunk 11 failed. Retrying with batch=100
[small retry] faf_network_links chunk 12 failed. Retrying with batch=100
[small retry] faf_network_links chunk 13 failed. Retrying with batch=100
[small retry] faf_network_links chunk 14 failed. Retrying with batch=100
[small retry] faf_network_links chunk 15 failed. Retrying with batch=100
[small retry] faf_network_links chunk 16 failed. Retrying with batch=100
[small retry] faf_network_links chunk 17 failed. Retrying with batch=100
[small retry] faf_network_links chunk 18 failed. Retrying with batch=100
[small retry] faf_network_links chunk 19 failed. Retrying with batch=100
[small retry] faf_network_links chunk 20 failed. Retrying with batch=100
[small retry] faf_network_links chunk 21 failed. Retrying with batch=100
[small retry] faf_network_links chunk 22 failed. Retrying with batch=100
[small retry] faf_network_links chunk 23 failed. Retrying with batch=100
[small retry] faf_network_links chunk 24 failed. Retrying with batch=100
[small retry] faf_network_links chunk 25 failed. Retrying with batch=100
[small retry] faf_network_links chunk 26 failed. Retrying with batch=100
[small retry] faf_network_links chunk 27 failed. Retrying with batch=100
[small retry] faf_network_links chunk 28 failed. Retrying with batch=100
[small retry] faf_network_links chunk 29 failed. Retrying with batch=100
[small retry] faf_network_links chunk 30 failed. Retrying with batch=100
[small retry] faf_network_links chunk 31 failed. Retrying with batch=100
[small retry] faf_network_links chunk 32 failed. Retrying with batch=100
[small retry] faf_network_links chunk 33 failed. Retrying with batch=100
[small retry] faf_network_links chunk 34 failed. Retrying with batch=100
[small retry] faf_network_links chunk 35 failed. Retrying with batch=100
[small retry] faf_network_links chunk 36 failed. Retrying with batch=100
[small retry] faf_network_links chunk 37 failed. Retrying with batch=100
[small retry] faf_network_links chunk 38 failed. Retrying with batch=100
[small retry] faf_network_links chunk 39 failed. Retrying with batch=100
[small retry] faf_network_links chunk 40 failed. Retrying with batch=100
[small retry] faf_network_links chunk 41 failed. Retrying with batch=100
[small retry] faf_network_links chunk 42 failed. Retrying with batch=100
[small retry] faf_network_links chunk 43 failed. Retrying with batch=100
[small retry] faf_network_links chunk 44 failed. Retrying with batch=100
[small retry] faf_network_links chunk 45 failed. Retrying with batch=100
[small retry] faf_network_links chunk 46 failed. Retrying with batch=100
[small retry] faf_network_links chunk 47 failed. Retrying with batch=100
[small retry] faf_network_links chunk 48 failed. Retrying with batch=100
[small retry] faf_network_links chunk 49 failed. Retrying with batch=100
[small retry] faf_network_links chunk 50 failed. Retrying with batch=100
[small retry] faf_network_links chunk 51 failed. Retrying with batch=100
[small retry] faf_network_links chunk 52 failed. Retrying with batch=100
[small retry] faf_network_links chunk 53 failed. Retrying with batch=100
[small retry] faf_network_links chunk 54 failed. Retrying with batch=100
[small retry] faf_network_links chunk 55 failed. Retrying with batch=100
[small retry] faf_network_links chunk 56 failed. Retrying with batch=100
[small retry] faf_network_links chunk 57 failed. Retrying with batch=100
[small retry] faf_network_links chunk 58 failed. Retrying with batch=100
[small retry] faf_network_links chunk 59 failed. Retrying with batch=100
[small retry] faf_network_links chunk 60 failed. Retrying with batch=100
[small retry] faf_network_links chunk 61 failed. Retrying with batch=100
[small retry] faf_network_links chunk 62 failed. Retrying with batch=100
[small retry] faf_network_links chunk 63 failed. Retrying with batch=100
[small retry] faf_network_links chunk 64 failed. Retrying with batch=100
[small retry] faf_network_links chunk 65 failed. Retrying with batch=100
[small retry] faf_network_links chunk 66 failed. Retrying with batch=100
[small retry] faf_network_links chunk 67 failed. Retrying with batch=100
[small retry] faf_network_links chunk 68 failed. Retrying with batch=100
[small retry] faf_network_links chunk 69 failed. Retrying with batch=100
[small retry] faf_network_links chunk 70 failed. Retrying with batch=100
[small retry] faf_network_links chunk 71 failed. Retrying with batch=100
[small retry] faf_network_links chunk 72 failed. Retrying with batch=100
[small retry] faf_network_links chunk 73 failed. Retrying with batch=100
[small retry] faf_network_links chunk 74 failed. Retrying with batch=100
[small retry] faf_network_links chunk 75 failed. Retrying with batch=100
[small retry] faf_network_links chunk 76 failed. Retrying with batch=100
[small retry] faf_network_links chunk 77 failed. Retrying with batch=100
[small retry] faf_network_links chunk 78 failed. Retrying with batch=100
[small retry] faf_network_links chunk 79 failed. Retrying with batch=100
[small retry] faf_network_links chunk 80 failed. Retrying with batch=100
[small retry] faf_network_links chunk 81 failed. Retrying with batch=100
[small retry] faf_network_links chunk 82 failed. Retrying with batch=100
[small retry] faf_network_links chunk 83 failed. Retrying with batch=100
[small retry] faf_network_links chunk 84 failed. Retrying with batch=100
[small retry] faf_network_links chunk 85 failed. Retrying with batch=100
[small retry] faf_network_links chunk 86 failed. Retrying with batch=100
[small retry] faf_network_links chunk 87 failed. Retrying with batch=100
[small retry] faf_network_links chunk 88 failed. Retrying with batch=100
[small retry] faf_network_links chunk 89 failed. Retrying with batch=100
[small retry] faf_network_links chunk 90 failed. Retrying with batch=100
[small retry] faf_network_links chunk 91 failed. Retrying with batch=100
[small retry] faf_network_links chunk 92 failed. Retrying with batch=100
[small retry] faf_network_links chunk 93 failed. Retrying with batch=100
[small retry] faf_network_links chunk 94 failed. Retrying with batch=100
[small retry] faf_network_links chunk 95 failed. Retrying with batch=100
[small retry] faf_network_links chunk 96 failed. Retrying with batch=100
[small retry] faf_network_links chunk 97 failed. Retrying with batch=100
[small retry] faf_network_links chunk 98 failed. Retrying with batch=100
[small retry] faf_network_links chunk 99 failed. Retrying with batch=100
[small retry] faf_network_links chunk 100 failed. Retrying with batch=100
[small retry] faf_network_links chunk 101 failed. Retrying with batch=100
[small retry] faf_network_links chunk 102 failed. Retrying with batch=100
[small retry] faf_network_links chunk 103 failed. Retrying with batch=100
[small retry] faf_network_links chunk 104 failed. Retrying with batch=100
[small retry] faf_network_links chunk 105 failed. Retrying with batch=100
[small retry] faf_network_links chunk 106 failed. Retrying with batch=100
[small retry] faf_network_links chunk 107 failed. Retrying with batch=100
[small retry] faf_network_links chunk 108 failed. Retrying with batch=100
[small retry] faf_network_links chunk 109 failed. Retrying with batch=100
[small retry] faf_network_links chunk 110 failed. Retrying with batch=100
[small retry] faf_network_links chunk 111 failed. Retrying with batch=100
[small retry] faf_network_links chunk 112 failed. Retrying with batch=100
[small retry] faf_network_links chunk 113 failed. Retrying with batch=100
[small retry] faf_network_links chunk 114 failed. Retrying with batch=100
[small retry] faf_network_links chunk 115 failed. Retrying with batch=100
[small retry] faf_network_links chunk 116 failed. Retrying with batch=100
[small retry] faf_network_links chunk 117 failed. Retrying with batch=100
[small retry] faf_network_links chunk 118 failed. Retrying with batch=100
[small retry] faf_network_links chunk 119 failed. Retrying with batch=100
[small retry] faf_network_links chunk 120 failed. Retrying with batch=100
[small retry] faf_network_links chunk 121 failed. Retrying with batch=100
[small retry] faf_network_links chunk 122 failed. Retrying with batch=100
[small retry] faf_network_links chunk 123 failed. Retrying with batch=100
[small retry] faf_network_links chunk 124 failed. Retrying with batch=100
[small retry] faf_network_links chunk 125 failed. Retrying with batch=100
[small retry] faf_network_links chunk 126 failed. Retrying with batch=100
[small retry] faf_network_links chunk 127 failed. Retrying with batch=100
[small retry] faf_network_links chunk 128 failed. Retrying with batch=100
[small retry] faf_network_links chunk 129 failed. Retrying with batch=100
[small retry] faf_network_links chunk 130 failed. Retrying with batch=100
[small retry] faf_network_links chunk 131 failed. Retrying with batch=100
[small retry] faf_network_links chunk 132 failed. Retrying with batch=100
[small retry] faf_network_links chunk 133 failed. Retrying with batch=100
[small retry] faf_network_links chunk 134 failed. Retrying with batch=100
[small retry] faf_network_links chunk 135 failed. Retrying with batch=100
[small retry] faf_network_links chunk 136 failed. Retrying with batch=100
[small retry] faf_network_links chunk 137 failed. Retrying with batch=100
[small retry] faf_network_links chunk 138 failed. Retrying with batch=100
[small retry] faf_network_links chunk 139 failed. Retrying with batch=100
[small retry] faf_network_links chunk 140 failed. Retrying with batch=100
[small retry] faf_network_links chunk 141 failed. Retrying with batch=100
[small retry] faf_network_links chunk 142 failed. Retrying with batch=100
[small retry] faf_network_links chunk 143 failed. Retrying with batch=100
[small retry] faf_network_links chunk 144 failed. Retrying with batch=100
[small retry] faf_network_links chunk 145 failed. Retrying with batch=100
[small retry] faf_network_links chunk 146 failed. Retrying with batch=100
[small retry] faf_network_links chunk 147 failed. Retrying with batch=100
[small retry] faf_network_links chunk 148 failed. Retrying with batch=100
[small retry] faf_network_links chunk 149 failed. Retrying with batch=100
[small retry] faf_network_links chunk 150 failed. Retrying with batch=100
[small retry] faf_network_links chunk 151 failed. Retrying with batch=100
[small retry] faf_network_links chunk 152 failed. Retrying with batch=100
[small retry] faf_network_links chunk 153 failed. Retrying with batch=100
[small retry] faf_network_links chunk 154 failed. Retrying with batch=100
[small retry] faf_network_links chunk 155 failed. Retrying with batch=100
[small retry] faf_network_links chunk 156 failed. Retrying with batch=100
[small retry] faf_network_links chunk 157 failed. Retrying with batch=100
[small retry] faf_network_links chunk 158 failed. Retrying with batch=100
[small retry] faf_network_links chunk 159 failed. Retrying with batch=100
[small retry] faf_network_links chunk 160 failed. Retrying with batch=100
[small retry] faf_network_links chunk 161 failed. Retrying with batch=100
[small retry] faf_network_links chunk 162 failed. Retrying with batch=100
[small retry] faf_network_links chunk 163 failed. Retrying with batch=100
[small retry] faf_network_links chunk 164 failed. Retrying with batch=100
[small retry] faf_network_links chunk 165 failed. Retrying with batch=100
[small retry] faf_network_links chunk 166 failed. Retrying with batch=100
[small retry] faf_network_links chunk 167 failed. Retrying with batch=100
[small retry] faf_network_links chunk 168 failed. Retrying with batch=100
[small retry] faf_network_links chunk 169 failed. Retrying with batch=100
[small retry] faf_network_links chunk 170 failed. Retrying with batch=100
[small retry] faf_network_links chunk 171 failed. Retrying with batch=100
[small retry] faf_network_links chunk 172 failed. Retrying with batch=100
[small retry] faf_network_links chunk 173 failed. Retrying with batch=100
[small retry] faf_network_links chunk 174 failed. Retrying with batch=100
[small retry] faf_network_links chunk 175 failed. Retrying with batch=100
[small retry] faf_network_links chunk 176 failed. Retrying with batch=100
[small retry] faf_network_links chunk 177 failed. Retrying with batch=100
[small retry] faf_network_links chunk 178 failed. Retrying with batch=100
[small retry] faf_network_links chunk 179 failed. Retrying with batch=100
[small retry] faf_network_links chunk 180 failed. Retrying with batch=100
[small retry] faf_network_links chunk 181 failed. Retrying with batch=100
[small retry] faf_network_links chunk 182 failed. Retrying with batch=100
[small retry] faf_network_links chunk 183 failed. Retrying with batch=100
[small retry] faf_network_links chunk 184 failed. Retrying with batch=100
[small retry] faf_network_links chunk 185 failed. Retrying with batch=100
[small retry] faf_network_links chunk 186 failed. Retrying with batch=100
[small retry] faf_network_links chunk 187 failed. Retrying with batch=100
[small retry] faf_network_links chunk 188 failed. Retrying with batch=100
[small retry] faf_network_links chunk 189 failed. Retrying with batch=100
[small retry] faf_network_links chunk 190 failed. Retrying with batch=100
[small retry] faf_network_links chunk 191 failed. Retrying with batch=100
[small retry] faf_network_links chunk 192 failed. Retrying with batch=100
[small retry] faf_network_links chunk 193 failed. Retrying with batch=100
[small retry] faf_network_links chunk 194 failed. Retrying with batch=100
[small retry] faf_network_links chunk 195 failed. Retrying with batch=100
[small retry] faf_network_links chunk 196 failed. Retrying with batch=100
[small retry] faf_network_links chunk 197 failed. Retrying with batch=100
[small retry] faf_network_links chunk 198 failed. Retrying with batch=100
[small retry] faf_network_links chunk 199 failed. Retrying with batch=100
[small retry] faf_network_links chunk 200 failed. Retrying with batch=100
[small retry] faf_network_links chunk 201 failed. Retrying with batch=100
[small retry] faf_network_links chunk 202 failed. Retrying with batch=100
[small retry] faf_network_links chunk 203 failed. Retrying with batch=100
[small retry] faf_network_links chunk 204 failed. Retrying with batch=100
[small retry] faf_network_links chunk 205 failed. Retrying with batch=100
[small retry] faf_network_links chunk 206 failed. Retrying with batch=100
[small retry] faf_network_links chunk 207 failed. Retrying with batch=100
[small retry] faf_network_links chunk 208 failed. Retrying with batch=100
[small retry] faf_network_links chunk 209 failed. Retrying with batch=100
[small retry] faf_network_links chunk 210 failed. Retrying with batch=100
[small retry] faf_network_links chunk 211 failed. Retrying with batch=100
[small retry] faf_network_links chunk 212 failed. Retrying with batch=100
[small retry] faf_network_links chunk 213 failed. Retrying with batch=100
[small retry] faf_network_links chunk 214 failed. Retrying with batch=100
[small retry] faf_network_links chunk 215 failed. Retrying with batch=100
[small retry] faf_network_links chunk 216 failed. Retrying with batch=100
[small retry] faf_network_links chunk 217 failed. Retrying with batch=100
[small retry] faf_network_links chunk 218 failed. Retrying with batch=100
[small retry] faf_network_links chunk 219 failed. Retrying with batch=100
[small retry] faf_network_links chunk 220 failed. Retrying with batch=100
[small retry] faf_network_links chunk 221 failed. Retrying with batch=100
[small retry] faf_network_links chunk 222 failed. Retrying with batch=100
[small retry] faf_network_links chunk 223 failed. Retrying with batch=100
[small retry] faf_network_links chunk 224 failed. Retrying with batch=100
[small retry] faf_network_links chunk 225 failed. Retrying with batch=100
[small retry] faf_network_links chunk 226 failed. Retrying with batch=100
[small retry] faf_network_links chunk 227 failed. Retrying with batch=100
[small retry] faf_network_links chunk 228 failed. Retrying with batch=100
[small retry] faf_network_links chunk 229 failed. Retrying with batch=100
[small retry] faf_network_links chunk 230 failed. Retrying with batch=100
[small retry] faf_network_links chunk 231 failed. Retrying with batch=100
[small retry] faf_network_links chunk 232 failed. Retrying with batch=100
[small retry] faf_network_links chunk 233 failed. Retrying with batch=100
[small retry] faf_network_links chunk 234 failed. Retrying with batch=100
[small retry] faf_network_links chunk 235 failed. Retrying with batch=100
[small retry] faf_network_links chunk 236 failed. Retrying with batch=100
[small retry] faf_network_links chunk 237 failed. Retrying with batch=100
[small retry] faf_network_links chunk 238 failed. Retrying with batch=100
[small retry] faf_network_links chunk 239 failed. Retrying with batch=100
[small retry] faf_network_links chunk 240 failed. Retrying with batch=100
[small retry] faf_network_links chunk 241 failed. Retrying with batch=100
[small retry] faf_network_links chunk 242 failed. Retrying with batch=100
[small retry] faf_network_links chunk 243 failed. Retrying with batch=100
[small retry] faf_network_links chunk 244 failed. Retrying with batch=100
[small retry] faf_network_links chunk 245 failed. Retrying with batch=100
[small retry] faf_network_links chunk 246 failed. Retrying with batch=100
[small retry] faf_network_links chunk 247 failed. Retrying with batch=100
[small retry] faf_network_links chunk 248 failed. Retrying with batch=100
[small retry] faf_network_links chunk 249 failed. Retrying with batch=100
[small retry] faf_network_links chunk 250 failed. Retrying with batch=100
[small retry] faf_network_links chunk 251 failed. Retrying with batch=100
[small retry] faf_network_links chunk 252 failed. Retrying with batch=100
[small retry] faf_network_links chunk 253 failed. Retrying with batch=100
[small retry] faf_network_links chunk 254 failed. Retrying with batch=100
[small retry] faf_network_links chunk 255 failed. Retrying with batch=100
[small retry] faf_network_links chunk 256 failed. Retrying with batch=100
[small retry] faf_network_links chunk 257 failed. Retrying with batch=100
[small retry] faf_network_links chunk 258 failed. Retrying with batch=100
[small retry] faf_network_links chunk 259 failed. Retrying with batch=100
[small retry] faf_network_links chunk 260 failed. Retrying with batch=100
[small retry] faf_network_links chunk 261 failed. Retrying with batch=100
[small retry] faf_network_links chunk 262 failed. Retrying with batch=100
[small retry] faf_network_links chunk 263 failed. Retrying with batch=100
[small retry] faf_network_links chunk 264 failed. Retrying with batch=100
[small retry] faf_network_links chunk 265 failed. Retrying with batch=100
[small retry] faf_network_links chunk 266 failed. Retrying with batch=100
[small retry] faf_network_links chunk 267 failed. Retrying with batch=100
[small retry] faf_network_links chunk 268 failed. Retrying with batch=100
[small retry] faf_network_links chunk 269 failed. Retrying with batch=100
[small retry] faf_network_links chunk 270 failed. Retrying with batch=100
[small retry] faf_network_links chunk 271 failed. Retrying with batch=100

Counting rows faf_network_links: 0it [00:00, ?it/s]

SUMMARY
  layer: faf_network_links
  description: FAF5 Network Links / highway freight network polyline topology
  status: check_count_mismatch
  layer_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links
  metadata_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\metadata_v2\faf_network_links_metadata_v2.json
  fields_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\metadata_v2\faf_network_links_fields_v2.csv
  object_ids_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\metadata_v2\faf_network_links_object_ids_v2.json
  source_info_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\metadata_v2\faf_network_links_source_info_v2.json
  chunk_manifest_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\faf_network_links_chunk_manifest_v2.csv
  expected_count_arcgis: 487394
  n_object_ids: 487394
  n_parquet_chunks: 0
  actual_rows_from_parquet: 0
  geometry_type: esriGeometryPolyline
  elapsed_seconds: 1671.2
  raw_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\raw_esri_json_chunks_v2
  parquet_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\parquet_chunks_v2
  single_file_status: skipped_large_layer_487394_features

========================================================================================================================
LAYER: faf_network_nodes
FAF5 Network Nodes / highway freight network node topology
========================================================================================================================
URL: https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Freight_Analysis_Framework_Network_Nodes/FeatureServer/0
OID field: OBJECTID
Geometry type: esriGeometryPoint
Expected count: 974788
Object IDs: 974788
Batch size: 1000

Probe first 3 object IDs...
Probe rows: 3
Probe columns: ['OBJECTID', 'ID', 'DATA1', 'Entry_or_Exit', 'Exit_Number', 'Interchange', 'CentroidID', 'Facility_Type', 'Facility_Name', 'County', 'State', 'StateID', 'StateName', 'FAFID', 'StateNameBak', 'geometry']

Downloading faf_network_nodes:   0%|          | 0/975 [00:00<?, ?it/s]

[small retry] faf_network_nodes chunk 1 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 2 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 3 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 4 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 5 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 6 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 7 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 8 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 9 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 10 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 11 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 12 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 13 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 14 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 15 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 16 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 17 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 18 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 19 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 20 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 21 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 22 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 23 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 24 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 25 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 26 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 27 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 28 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 29 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 30 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 31 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 32 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 33 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 34 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 35 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 36 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 37 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 38 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 39 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 40 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 41 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 42 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 43 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 44 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 45 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 46 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 47 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 48 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 49 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 50 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 51 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 52 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 53 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 54 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 55 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 56 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 57 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 58 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 59 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 60 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 61 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 62 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 63 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 64 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 65 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 66 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 67 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 68 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 69 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 70 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 71 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 72 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 73 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 74 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 75 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 76 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 77 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 78 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 79 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 80 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 81 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 82 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 83 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 84 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 85 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 86 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 87 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 88 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 89 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 90 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 91 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 92 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 93 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 94 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 95 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 96 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 97 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 98 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 99 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 100 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 101 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 102 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 103 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 104 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 105 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 106 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 107 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 108 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 109 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 110 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 111 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 112 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 113 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 114 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 115 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 116 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 117 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 118 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 119 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 120 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 121 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 122 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 123 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 124 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 125 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 126 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 127 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 128 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 129 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 130 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 131 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 132 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 133 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 134 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 135 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 136 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 137 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 138 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 139 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 140 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 141 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 142 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 143 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 144 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 145 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 146 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 147 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 148 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 149 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 150 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 151 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 152 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 153 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 154 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 155 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 156 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 157 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 158 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 159 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 160 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 161 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 162 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 163 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 164 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 165 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 166 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 167 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 168 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 169 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 170 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 171 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 172 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 173 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 174 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 175 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 176 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 177 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 178 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 179 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 180 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 181 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 182 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 183 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 184 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 185 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 186 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 187 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 188 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 189 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 190 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 191 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 192 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 193 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 194 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 195 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 196 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 197 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 198 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 199 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 200 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 201 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 202 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 203 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 204 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 205 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 206 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 207 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 208 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 209 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 210 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 211 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 212 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 213 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 214 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 215 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 216 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 217 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 218 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 219 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 220 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 221 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 222 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 223 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 224 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 225 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 226 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 227 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 228 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 229 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 230 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 231 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 232 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 233 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 234 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 235 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 236 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 237 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 238 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 239 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 240 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 241 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 242 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 243 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 244 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 245 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 246 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 247 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 248 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 249 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 250 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 251 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 252 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 253 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 254 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 255 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 256 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 257 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 258 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 259 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 260 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 261 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 262 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 263 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 264 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 265 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 266 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 267 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 268 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 269 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 270 failed. Retrying with batch=100
[small retry] faf_network_nodes chunk 271 failed. Retrying with batch=100

Counting rows faf_network_nodes: 0it [00:00, ?it/s]

SUMMARY
  layer: faf_network_nodes
  description: FAF5 Network Nodes / highway freight network node topology
  status: check_count_mismatch
  layer_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_nodes
  metadata_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_nodes\metadata_v2\faf_network_nodes_metadata_v2.json
  fields_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_nodes\metadata_v2\faf_network_nodes_fields_v2.csv
  object_ids_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_nodes\metadata_v2\faf_network_nodes_object_ids_v2.json
  source_info_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_nodes\metadata_v2\faf_network_nodes_source_info_v2.json
  chunk_manifest_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_nodes\faf_network_nodes_chunk_manifest_v2.csv
  expected_count_arcgis: 974788
  n_object_ids: 974788
  n_parquet_chunks: 0
  actual_rows_from_parquet: 0
  geometry_type: esriGeometryPoint
  elapsed_seconds: 1851.82
  raw_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_nodes\raw_esri_json_chunks_v2
  parquet_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_nodes\parquet_chunks_v2
  single_file_status: skipped_large_layer_974788_features

========================================================================================================================
LAYER: narn_lines
North American Rail Network Lines / rail line polyline topology
========================================================================================================================
URL: https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_North_American_Rail_Network_Lines/FeatureServer/0
OID field: OBJECTID
Geometry type: esriGeometryPolyline
Expected count: 302743
Object IDs: 302743
Batch size: 1000

Probe first 3 object IDs...
Probe rows: 3
Probe columns: ['OBJECTID', 'FRAARCID', 'FRFRANODE', 'TOFRANODE', 'STFIPS', 'CNTYFIPS', 'STCNTYFIPS', 'STATEAB', 'COUNTRY', 'FRADISTRCT', 'RROWNER1', 'RROWNER2', 'RROWNER3', 'TRKRGHTS1', 'TRKRGHTS2', 'TRKRGHTS3', 'TRKRGHTS4', 'TRKRGHTS5', 'TRKRGHTS6', 'TRKRGHTS7', 'TRKRGHTS8', 'TRKRGHTS9', 'DIVISION', 'SUBDIV', 'BRANCH', 'YARDNAME', 'PASSNGR', 'STRACNET', 'TRACKS', 'NET']

Downloading narn_lines:   0%|          | 0/303 [00:00<?, ?it/s]

[small retry] narn_lines chunk 1 failed. Retrying with batch=100
[small retry] narn_lines chunk 2 failed. Retrying with batch=100
[small retry] narn_lines chunk 3 failed. Retrying with batch=100
[small retry] narn_lines chunk 4 failed. Retrying with batch=100
[small retry] narn_lines chunk 5 failed. Retrying with batch=100
[small retry] narn_lines chunk 6 failed. Retrying with batch=100
[small retry] narn_lines chunk 7 failed. Retrying with batch=100
[small retry] narn_lines chunk 8 failed. Retrying with batch=100
[small retry] narn_lines chunk 9 failed. Retrying with batch=100
[small retry] narn_lines chunk 10 failed. Retrying with batch=100
[small retry] narn_lines chunk 11 failed. Retrying with batch=100
[small retry] narn_lines chunk 12 failed. Retrying with batch=100
[small retry] narn_lines chunk 13 failed. Retrying with batch=100
[small retry] narn_lines chunk 14 failed. Retrying with batch=100
[small retry] narn_lines chunk 15 failed. Retrying with batch=100
[small retry] narn_lines chunk 16 failed. Retrying with batch=100
[small retry] narn_lines chunk 17 failed. Retrying with batch=100
[small retry] narn_lines chunk 18 failed. Retrying with batch=100
[small retry] narn_lines chunk 19 failed. Retrying with batch=100
[small retry] narn_lines chunk 20 failed. Retrying with batch=100
[small retry] narn_lines chunk 21 failed. Retrying with batch=100
[small retry] narn_lines chunk 22 failed. Retrying with batch=100
[small retry] narn_lines chunk 23 failed. Retrying with batch=100
[small retry] narn_lines chunk 24 failed. Retrying with batch=100
[small retry] narn_lines chunk 25 failed. Retrying with batch=100
[small retry] narn_lines chunk 26 failed. Retrying with batch=100
[small retry] narn_lines chunk 27 failed. Retrying with batch=100
[small retry] narn_lines chunk 28 failed. Retrying with batch=100
[small retry] narn_lines chunk 29 failed. Retrying with batch=100
[small retry] narn_lines chunk 30 failed. Retrying with batch=100
[small retry] narn_lines chunk 31 failed. Retrying with batch=100
[small retry] narn_lines chunk 32 failed. Retrying with batch=100
[small retry] narn_lines chunk 33 failed. Retrying with batch=100
[small retry] narn_lines chunk 34 failed. Retrying with batch=100
[small retry] narn_lines chunk 35 failed. Retrying with batch=100
[small retry] narn_lines chunk 36 failed. Retrying with batch=100
[small retry] narn_lines chunk 37 failed. Retrying with batch=100
[small retry] narn_lines chunk 38 failed. Retrying with batch=100
[small retry] narn_lines chunk 39 failed. Retrying with batch=100
[small retry] narn_lines chunk 40 failed. Retrying with batch=100
[small retry] narn_lines chunk 41 failed. Retrying with batch=100
[small retry] narn_lines chunk 42 failed. Retrying with batch=100
[small retry] narn_lines chunk 43 failed. Retrying with batch=100
[small retry] narn_lines chunk 44 failed. Retrying with batch=100
[small retry] narn_lines chunk 45 failed. Retrying with batch=100
[small retry] narn_lines chunk 46 failed. Retrying with batch=100
[small retry] narn_lines chunk 47 failed. Retrying with batch=100
[small retry] narn_lines chunk 48 failed. Retrying with batch=100
[small retry] narn_lines chunk 49 failed. Retrying with batch=100
[small retry] narn_lines chunk 50 failed. Retrying with batch=100
[small retry] narn_lines chunk 51 failed. Retrying with batch=100
[small retry] narn_lines chunk 52 failed. Retrying with batch=100
[small retry] narn_lines chunk 53 failed. Retrying with batch=100
[small retry] narn_lines chunk 54 failed. Retrying with batch=100
[small retry] narn_lines chunk 55 failed. Retrying with batch=100
[small retry] narn_lines chunk 56 failed. Retrying with batch=100
[small retry] narn_lines chunk 57 failed. Retrying with batch=100
[small retry] narn_lines chunk 58 failed. Retrying with batch=100
[small retry] narn_lines chunk 59 failed. Retrying with batch=100
[small retry] narn_lines chunk 60 failed. Retrying with batch=100
[small retry] narn_lines chunk 61 failed. Retrying with batch=100
[small retry] narn_lines chunk 62 failed. Retrying with batch=100
[small retry] narn_lines chunk 63 failed. Retrying with batch=100
[small retry] narn_lines chunk 64 failed. Retrying with batch=100
[small retry] narn_lines chunk 65 failed. Retrying with batch=100
[small retry] narn_lines chunk 66 failed. Retrying with batch=100
[small retry] narn_lines chunk 67 failed. Retrying with batch=100
[small retry] narn_lines chunk 68 failed. Retrying with batch=100
[small retry] narn_lines chunk 69 failed. Retrying with batch=100
[small retry] narn_lines chunk 70 failed. Retrying with batch=100
[small retry] narn_lines chunk 71 failed. Retrying with batch=100
[small retry] narn_lines chunk 72 failed. Retrying with batch=100
[small retry] narn_lines chunk 73 failed. Retrying with batch=100
[small retry] narn_lines chunk 74 failed. Retrying with batch=100
[small retry] narn_lines chunk 75 failed. Retrying with batch=100
[small retry] narn_lines chunk 76 failed. Retrying with batch=100
[small retry] narn_lines chunk 77 failed. Retrying with batch=100
[small retry] narn_lines chunk 78 failed. Retrying with batch=100
[small retry] narn_lines chunk 79 failed. Retrying with batch=100
[small retry] narn_lines chunk 80 failed. Retrying with batch=100
[small retry] narn_lines chunk 81 failed. Retrying with batch=100
[small retry] narn_lines chunk 82 failed. Retrying with batch=100
[small retry] narn_lines chunk 83 failed. Retrying with batch=100
[small retry] narn_lines chunk 84 failed. Retrying with batch=100
[small retry] narn_lines chunk 85 failed. Retrying with batch=100
[small retry] narn_lines chunk 86 failed. Retrying with batch=100
[small retry] narn_lines chunk 87 failed. Retrying with batch=100
[small retry] narn_lines chunk 88 failed. Retrying with batch=100
[small retry] narn_lines chunk 89 failed. Retrying with batch=100
[small retry] narn_lines chunk 90 failed. Retrying with batch=100
[small retry] narn_lines chunk 91 failed. Retrying with batch=100
[small retry] narn_lines chunk 92 failed. Retrying with batch=100
[small retry] narn_lines chunk 93 failed. Retrying with batch=100
[small retry] narn_lines chunk 94 failed. Retrying with batch=100
[small retry] narn_lines chunk 95 failed. Retrying with batch=100
[small retry] narn_lines chunk 96 failed. Retrying with batch=100
[small retry] narn_lines chunk 97 failed. Retrying with batch=100
[small retry] narn_lines chunk 98 failed. Retrying with batch=100
[small retry] narn_lines chunk 99 failed. Retrying with batch=100
[small retry] narn_lines chunk 100 failed. Retrying with batch=100
[small retry] narn_lines chunk 101 failed. Retrying with batch=100
[small retry] narn_lines chunk 102 failed. Retrying with batch=100
[small retry] narn_lines chunk 103 failed. Retrying with batch=100
[small retry] narn_lines chunk 104 failed. Retrying with batch=100
[small retry] narn_lines chunk 105 failed. Retrying with batch=100
[small retry] narn_lines chunk 106 failed. Retrying with batch=100
[small retry] narn_lines chunk 107 failed. Retrying with batch=100
[small retry] narn_lines chunk 108 failed. Retrying with batch=100
[small retry] narn_lines chunk 109 failed. Retrying with batch=100
[small retry] narn_lines chunk 110 failed. Retrying with batch=100
[small retry] narn_lines chunk 111 failed. Retrying with batch=100
[small retry] narn_lines chunk 112 failed. Retrying with batch=100
[small retry] narn_lines chunk 113 failed. Retrying with batch=100
[small retry] narn_lines chunk 114 failed. Retrying with batch=100
[small retry] narn_lines chunk 115 failed. Retrying with batch=100
[small retry] narn_lines chunk 116 failed. Retrying with batch=100
[small retry] narn_lines chunk 117 failed. Retrying with batch=100
[small retry] narn_lines chunk 118 failed. Retrying with batch=100
[small retry] narn_lines chunk 119 failed. Retrying with batch=100
[small retry] narn_lines chunk 120 failed. Retrying with batch=100
[small retry] narn_lines chunk 121 failed. Retrying with batch=100
[small retry] narn_lines chunk 122 failed. Retrying with batch=100
[small retry] narn_lines chunk 123 failed. Retrying with batch=100
[small retry] narn_lines chunk 124 failed. Retrying with batch=100
[small retry] narn_lines chunk 125 failed. Retrying with batch=100
[small retry] narn_lines chunk 126 failed. Retrying with batch=100
[small retry] narn_lines chunk 127 failed. Retrying with batch=100
[small retry] narn_lines chunk 128 failed. Retrying with batch=100
[small retry] narn_lines chunk 129 failed. Retrying with batch=100
[small retry] narn_lines chunk 130 failed. Retrying with batch=100
[small retry] narn_lines chunk 131 failed. Retrying with batch=100
[small retry] narn_lines chunk 132 failed. Retrying with batch=100
[small retry] narn_lines chunk 133 failed. Retrying with batch=100
[small retry] narn_lines chunk 134 failed. Retrying with batch=100
[small retry] narn_lines chunk 135 failed. Retrying with batch=100
[small retry] narn_lines chunk 136 failed. Retrying with batch=100
[small retry] narn_lines chunk 137 failed. Retrying with batch=100
[small retry] narn_lines chunk 138 failed. Retrying with batch=100
[small retry] narn_lines chunk 139 failed. Retrying with batch=100
[small retry] narn_lines chunk 140 failed. Retrying with batch=100
[small retry] narn_lines chunk 141 failed. Retrying with batch=100
[small retry] narn_lines chunk 142 failed. Retrying with batch=100
[small retry] narn_lines chunk 143 failed. Retrying with batch=100
[small retry] narn_lines chunk 144 failed. Retrying with batch=100
[small retry] narn_lines chunk 145 failed. Retrying with batch=100
[small retry] narn_lines chunk 146 failed. Retrying with batch=100
[small retry] narn_lines chunk 147 failed. Retrying with batch=100
[small retry] narn_lines chunk 148 failed. Retrying with batch=100
[small retry] narn_lines chunk 149 failed. Retrying with batch=100
[small retry] narn_lines chunk 150 failed. Retrying with batch=100
[small retry] narn_lines chunk 151 failed. Retrying with batch=100
[small retry] narn_lines chunk 152 failed. Retrying with batch=100
[small retry] narn_lines chunk 153 failed. Retrying with batch=100
[small retry] narn_lines chunk 154 failed. Retrying with batch=100
[small retry] narn_lines chunk 155 failed. Retrying with batch=100
[small retry] narn_lines chunk 156 failed. Retrying with batch=100
[small retry] narn_lines chunk 157 failed. Retrying with batch=100
[small retry] narn_lines chunk 158 failed. Retrying with batch=100
[small retry] narn_lines chunk 159 failed. Retrying with batch=100
[small retry] narn_lines chunk 160 failed. Retrying with batch=100
[small retry] narn_lines chunk 161 failed. Retrying with batch=100
[small retry] narn_lines chunk 162 failed. Retrying with batch=100
[small retry] narn_lines chunk 163 failed. Retrying with batch=100
[small retry] narn_lines chunk 164 failed. Retrying with batch=100
[small retry] narn_lines chunk 165 failed. Retrying with batch=100
[small retry] narn_lines chunk 166 failed. Retrying with batch=100
[small retry] narn_lines chunk 167 failed. Retrying with batch=100
[small retry] narn_lines chunk 168 failed. Retrying with batch=100
[small retry] narn_lines chunk 169 failed. Retrying with batch=100
[small retry] narn_lines chunk 170 failed. Retrying with batch=100
[small retry] narn_lines chunk 171 failed. Retrying with batch=100
[small retry] narn_lines chunk 172 failed. Retrying with batch=100
[small retry] narn_lines chunk 173 failed. Retrying with batch=100
[small retry] narn_lines chunk 174 failed. Retrying with batch=100
[small retry] narn_lines chunk 175 failed. Retrying with batch=100
[small retry] narn_lines chunk 176 failed. Retrying with batch=100
[small retry] narn_lines chunk 177 failed. Retrying with batch=100
[small retry] narn_lines chunk 178 failed. Retrying with batch=100
[small retry] narn_lines chunk 179 failed. Retrying with batch=100
[small retry] narn_lines chunk 180 failed. Retrying with batch=100
[small retry] narn_lines chunk 181 failed. Retrying with batch=100
[small retry] narn_lines chunk 182 failed. Retrying with batch=100
[small retry] narn_lines chunk 183 failed. Retrying with batch=100
[small retry] narn_lines chunk 184 failed. Retrying with batch=100
[small retry] narn_lines chunk 185 failed. Retrying with batch=100
[small retry] narn_lines chunk 186 failed. Retrying with batch=100
[small retry] narn_lines chunk 187 failed. Retrying with batch=100
[small retry] narn_lines chunk 188 failed. Retrying with batch=100
[small retry] narn_lines chunk 189 failed. Retrying with batch=100
[small retry] narn_lines chunk 190 failed. Retrying with batch=100
[small retry] narn_lines chunk 191 failed. Retrying with batch=100
[small retry] narn_lines chunk 192 failed. Retrying with batch=100
[small retry] narn_lines chunk 193 failed. Retrying with batch=100
[small retry] narn_lines chunk 194 failed. Retrying with batch=100
[small retry] narn_lines chunk 195 failed. Retrying with batch=100
[small retry] narn_lines chunk 196 failed. Retrying with batch=100
[small retry] narn_lines chunk 197 failed. Retrying with batch=100
[small retry] narn_lines chunk 198 failed. Retrying with batch=100
[small retry] narn_lines chunk 199 failed. Retrying with batch=100
[small retry] narn_lines chunk 200 failed. Retrying with batch=100
[small retry] narn_lines chunk 201 failed. Retrying with batch=100
[small retry] narn_lines chunk 202 failed. Retrying with batch=100
[small retry] narn_lines chunk 203 failed. Retrying with batch=100
[small retry] narn_lines chunk 204 failed. Retrying with batch=100
[small retry] narn_lines chunk 205 failed. Retrying with batch=100
[small retry] narn_lines chunk 206 failed. Retrying with batch=100
[small retry] narn_lines chunk 207 failed. Retrying with batch=100
[small retry] narn_lines chunk 208 failed. Retrying with batch=100
[small retry] narn_lines chunk 209 failed. Retrying with batch=100
[small retry] narn_lines chunk 210 failed. Retrying with batch=100
[small retry] narn_lines chunk 211 failed. Retrying with batch=100
[small retry] narn_lines chunk 212 failed. Retrying with batch=100
[small retry] narn_lines chunk 213 failed. Retrying with batch=100
[small retry] narn_lines chunk 214 failed. Retrying with batch=100
[small retry] narn_lines chunk 215 failed. Retrying with batch=100
[small retry] narn_lines chunk 216 failed. Retrying with batch=100
[small retry] narn_lines chunk 217 failed. Retrying with batch=100
[small retry] narn_lines chunk 218 failed. Retrying with batch=100
[small retry] narn_lines chunk 219 failed. Retrying with batch=100
[small retry] narn_lines chunk 220 failed. Retrying with batch=100
[small retry] narn_lines chunk 221 failed. Retrying with batch=100
[small retry] narn_lines chunk 222 failed. Retrying with batch=100
[small retry] narn_lines chunk 223 failed. Retrying with batch=100
[small retry] narn_lines chunk 224 failed. Retrying with batch=100
[small retry] narn_lines chunk 225 failed. Retrying with batch=100
[small retry] narn_lines chunk 226 failed. Retrying with batch=100
[small retry] narn_lines chunk 227 failed. Retrying with batch=100
[small retry] narn_lines chunk 228 failed. Retrying with batch=100
[small retry] narn_lines chunk 229 failed. Retrying with batch=100
[small retry] narn_lines chunk 230 failed. Retrying with batch=100
[small retry] narn_lines chunk 231 failed. Retrying with batch=100
[small retry] narn_lines chunk 232 failed. Retrying with batch=100
[small retry] narn_lines chunk 233 failed. Retrying with batch=100
[small retry] narn_lines chunk 234 failed. Retrying with batch=100
[small retry] narn_lines chunk 235 failed. Retrying with batch=100
[small retry] narn_lines chunk 236 failed. Retrying with batch=100
[small retry] narn_lines chunk 237 failed. Retrying with batch=100
[small retry] narn_lines chunk 238 failed. Retrying with batch=100
[small retry] narn_lines chunk 239 failed. Retrying with batch=100
[small retry] narn_lines chunk 240 failed. Retrying with batch=100
[small retry] narn_lines chunk 241 failed. Retrying with batch=100
[small retry] narn_lines chunk 242 failed. Retrying with batch=100
[small retry] narn_lines chunk 243 failed. Retrying with batch=100
[small retry] narn_lines chunk 244 failed. Retrying with batch=100
[small retry] narn_lines chunk 245 failed. Retrying with batch=100
[small retry] narn_lines chunk 246 failed. Retrying with batch=100
[small retry] narn_lines chunk 247 failed. Retrying with batch=100
[small retry] narn_lines chunk 248 failed. Retrying with batch=100
[small retry] narn_lines chunk 249 failed. Retrying with batch=100
[small retry] narn_lines chunk 250 failed. Retrying with batch=100
[small retry] narn_lines chunk 251 failed. Retrying with batch=100
[small retry] narn_lines chunk 252 failed. Retrying with batch=100
[small retry] narn_lines chunk 253 failed. Retrying with batch=100
[small retry] narn_lines chunk 254 failed. Retrying with batch=100
[small retry] narn_lines chunk 255 failed. Retrying with batch=100
[small retry] narn_lines chunk 256 failed. Retrying with batch=100
[small retry] narn_lines chunk 257 failed. Retrying with batch=100
[small retry] narn_lines chunk 258 failed. Retrying with batch=100
[small retry] narn_lines chunk 259 failed. Retrying with batch=100
[small retry] narn_lines chunk 260 failed. Retrying with batch=100
[small retry] narn_lines chunk 261 failed. Retrying with batch=100
[small retry] narn_lines chunk 262 failed. Retrying with batch=100
[small retry] narn_lines chunk 263 failed. Retrying with batch=100
[small retry] narn_lines chunk 264 failed. Retrying with batch=100
[small retry] narn_lines chunk 265 failed. Retrying with batch=100
[small retry] narn_lines chunk 266 failed. Retrying with batch=100
[small retry] narn_lines chunk 267 failed. Retrying with batch=100
[small retry] narn_lines chunk 268 failed. Retrying with batch=100
[small retry] narn_lines chunk 269 failed. Retrying with batch=100
[small retry] narn_lines chunk 270 failed. Retrying with batch=100
[small retry] narn_lines chunk 271 failed. Retrying with batch=100
[small retry] narn_lines chunk 272 failed. Retrying with batch=100
[small retry] narn_lines chunk 273 failed. Retrying with batch=100
[small retry] narn_lines chunk 274 failed. Retrying with batch=100
[small retry] narn_lines chunk 275 failed. Retrying with batch=100
[small retry] narn_lines chunk 276 failed. Retrying with batch=100
[small retry] narn_lines chunk 277 failed. Retrying with batch=100
[small retry] narn_lines chunk 278 failed. Retrying with batch=100
[small retry] narn_lines chunk 279 failed. Retrying with batch=100
[small retry] narn_lines chunk 280 failed. Retrying with batch=100
[small retry] narn_lines chunk 281 failed. Retrying with batch=100
[small retry] narn_lines chunk 282 failed. Retrying with batch=100
[small retry] narn_lines chunk 283 failed. Retrying with batch=100
[small retry] narn_lines chunk 284 failed. Retrying with batch=100
[small retry] narn_lines chunk 285 failed. Retrying with batch=100
[small retry] narn_lines chunk 286 failed. Retrying with batch=100
[small retry] narn_lines chunk 287 failed. Retrying with batch=100
[small retry] narn_lines chunk 288 failed. Retrying with batch=100
[small retry] narn_lines chunk 289 failed. Retrying with batch=100
[small retry] narn_lines chunk 290 failed. Retrying with batch=100
[small retry] narn_lines chunk 291 failed. Retrying with batch=100
[small retry] narn_lines chunk 292 failed. Retrying with batch=100
[small retry] narn_lines chunk 293 failed. Retrying with batch=100
[small retry] narn_lines chunk 294 failed. Retrying with batch=100
[small retry] narn_lines chunk 295 failed. Retrying with batch=100
[small retry] narn_lines chunk 296 failed. Retrying with batch=100
[small retry] narn_lines chunk 297 failed. Retrying with batch=100
[small retry] narn_lines chunk 298 failed. Retrying with batch=100
[small retry] narn_lines chunk 299 failed. Retrying with batch=100
[small retry] narn_lines chunk 300 failed. Retrying with batch=100

Counting rows narn_lines: 0it [00:00, ?it/s]

SUMMARY
  layer: narn_lines
  description: North American Rail Network Lines / rail line polyline topology
  status: check_count_mismatch
  layer_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_lines
  metadata_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_lines\metadata_v2\narn_lines_metadata_v2.json
  fields_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_lines\metadata_v2\narn_lines_fields_v2.csv
  object_ids_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_lines\metadata_v2\narn_lines_object_ids_v2.json
  source_info_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_lines\metadata_v2\narn_lines_source_info_v2.json
  chunk_manifest_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_lines\narn_lines_chunk_manifest_v2.csv
  expected_count_arcgis: 302743
  n_object_ids: 302743
  n_parquet_chunks: 0
  actual_rows_from_parquet: 0
  geometry_type: esriGeometryPolyline
  elapsed_seconds: 688.47
  raw_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_lines\raw_esri_json_chunks_v2
  parquet_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_lines\parquet_chunks_v2
  single_file_status: skipped_large_layer_302743_features

========================================================================================================================
LAYER: narn_nodes
North American Rail Network Nodes / rail node topology
========================================================================================================================
URL: https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_North_American_Rail_Network_Nodes/FeatureServer/0
OID field: OBJECTID
Geometry type: esriGeometryPoint
Expected count: 250178
Object IDs: 250178
Batch size: 1000

Probe first 3 object IDs...
Probe rows: 3
Probe columns: ['OBJECTID', 'FRANODEID', 'COUNTRY', 'STATE', 'STFIPS', 'CTYFIPS', 'STCYFIPS', 'FRADISTRCT', 'PASSNGR', 'PASSNGRSTN', 'BNDRY', 'geometry']

Downloading narn_nodes:   0%|          | 0/251 [00:00<?, ?it/s]

[small retry] narn_nodes chunk 1 failed. Retrying with batch=100
[small retry] narn_nodes chunk 2 failed. Retrying with batch=100
[small retry] narn_nodes chunk 3 failed. Retrying with batch=100
[small retry] narn_nodes chunk 4 failed. Retrying with batch=100
[small retry] narn_nodes chunk 5 failed. Retrying with batch=100
[small retry] narn_nodes chunk 6 failed. Retrying with batch=100
[small retry] narn_nodes chunk 7 failed. Retrying with batch=100
[small retry] narn_nodes chunk 8 failed. Retrying with batch=100
[small retry] narn_nodes chunk 9 failed. Retrying with batch=100
[small retry] narn_nodes chunk 10 failed. Retrying with batch=100
[small retry] narn_nodes chunk 11 failed. Retrying with batch=100
[small retry] narn_nodes chunk 12 failed. Retrying with batch=100
[small retry] narn_nodes chunk 13 failed. Retrying with batch=100
[small retry] narn_nodes chunk 14 failed. Retrying with batch=100
[small retry] narn_nodes chunk 15 failed. Retrying with batch=100
[small retry] narn_nodes chunk 16 failed. Retrying with batch=100
[small retry] narn_nodes chunk 17 failed. Retrying with batch=100
[small retry] narn_nodes chunk 18 failed. Retrying with batch=100
[small retry] narn_nodes chunk 19 failed. Retrying with batch=100
[small retry] narn_nodes chunk 20 failed. Retrying with batch=100
[small retry] narn_nodes chunk 21 failed. Retrying with batch=100
[small retry] narn_nodes chunk 22 failed. Retrying with batch=100
[small retry] narn_nodes chunk 23 failed. Retrying with batch=100
[small retry] narn_nodes chunk 24 failed. Retrying with batch=100
[small retry] narn_nodes chunk 25 failed. Retrying with batch=100
[small retry] narn_nodes chunk 26 failed. Retrying with batch=100
[small retry] narn_nodes chunk 27 failed. Retrying with batch=100
[small retry] narn_nodes chunk 28 failed. Retrying with batch=100
[small retry] narn_nodes chunk 29 failed. Retrying with batch=100
[small retry] narn_nodes chunk 30 failed. Retrying with batch=100
[small retry] narn_nodes chunk 31 failed. Retrying with batch=100
[small retry] narn_nodes chunk 32 failed. Retrying with batch=100
[small retry] narn_nodes chunk 33 failed. Retrying with batch=100
[small retry] narn_nodes chunk 34 failed. Retrying with batch=100
[small retry] narn_nodes chunk 35 failed. Retrying with batch=100
[small retry] narn_nodes chunk 36 failed. Retrying with batch=100
[small retry] narn_nodes chunk 37 failed. Retrying with batch=100
[small retry] narn_nodes chunk 38 failed. Retrying with batch=100
[small retry] narn_nodes chunk 39 failed. Retrying with batch=100
[small retry] narn_nodes chunk 40 failed. Retrying with batch=100
[small retry] narn_nodes chunk 41 failed. Retrying with batch=100
[small retry] narn_nodes chunk 42 failed. Retrying with batch=100
[small retry] narn_nodes chunk 43 failed. Retrying with batch=100
[small retry] narn_nodes chunk 44 failed. Retrying with batch=100
[small retry] narn_nodes chunk 45 failed. Retrying with batch=100
[small retry] narn_nodes chunk 46 failed. Retrying with batch=100
[small retry] narn_nodes chunk 47 failed. Retrying with batch=100
[small retry] narn_nodes chunk 48 failed. Retrying with batch=100
[small retry] narn_nodes chunk 49 failed. Retrying with batch=100
[small retry] narn_nodes chunk 50 failed. Retrying with batch=100
[small retry] narn_nodes chunk 51 failed. Retrying with batch=100
[small retry] narn_nodes chunk 52 failed. Retrying with batch=100
[small retry] narn_nodes chunk 53 failed. Retrying with batch=100
[small retry] narn_nodes chunk 54 failed. Retrying with batch=100
[small retry] narn_nodes chunk 55 failed. Retrying with batch=100
[small retry] narn_nodes chunk 56 failed. Retrying with batch=100
[small retry] narn_nodes chunk 57 failed. Retrying with batch=100
[small retry] narn_nodes chunk 58 failed. Retrying with batch=100
[small retry] narn_nodes chunk 59 failed. Retrying with batch=100
[small retry] narn_nodes chunk 60 failed. Retrying with batch=100
[small retry] narn_nodes chunk 61 failed. Retrying with batch=100
[small retry] narn_nodes chunk 62 failed. Retrying with batch=100
[small retry] narn_nodes chunk 63 failed. Retrying with batch=100
[small retry] narn_nodes chunk 64 failed. Retrying with batch=100
[small retry] narn_nodes chunk 65 failed. Retrying with batch=100
[small retry] narn_nodes chunk 66 failed. Retrying with batch=100
[small retry] narn_nodes chunk 67 failed. Retrying with batch=100
[small retry] narn_nodes chunk 68 failed. Retrying with batch=100
[small retry] narn_nodes chunk 69 failed. Retrying with batch=100
[small retry] narn_nodes chunk 70 failed. Retrying with batch=100
[small retry] narn_nodes chunk 71 failed. Retrying with batch=100
[small retry] narn_nodes chunk 72 failed. Retrying with batch=100
[small retry] narn_nodes chunk 73 failed. Retrying with batch=100
[small retry] narn_nodes chunk 74 failed. Retrying with batch=100
[small retry] narn_nodes chunk 75 failed. Retrying with batch=100
[small retry] narn_nodes chunk 76 failed. Retrying with batch=100
[small retry] narn_nodes chunk 77 failed. Retrying with batch=100
[small retry] narn_nodes chunk 78 failed. Retrying with batch=100
[small retry] narn_nodes chunk 79 failed. Retrying with batch=100
[small retry] narn_nodes chunk 80 failed. Retrying with batch=100
[small retry] narn_nodes chunk 81 failed. Retrying with batch=100
[small retry] narn_nodes chunk 82 failed. Retrying with batch=100
[small retry] narn_nodes chunk 83 failed. Retrying with batch=100
[small retry] narn_nodes chunk 84 failed. Retrying with batch=100
[small retry] narn_nodes chunk 85 failed. Retrying with batch=100
[small retry] narn_nodes chunk 86 failed. Retrying with batch=100
[small retry] narn_nodes chunk 87 failed. Retrying with batch=100
[small retry] narn_nodes chunk 88 failed. Retrying with batch=100
[small retry] narn_nodes chunk 89 failed. Retrying with batch=100
[small retry] narn_nodes chunk 90 failed. Retrying with batch=100
[small retry] narn_nodes chunk 91 failed. Retrying with batch=100
[small retry] narn_nodes chunk 92 failed. Retrying with batch=100
[small retry] narn_nodes chunk 93 failed. Retrying with batch=100
[small retry] narn_nodes chunk 94 failed. Retrying with batch=100
[small retry] narn_nodes chunk 95 failed. Retrying with batch=100
[small retry] narn_nodes chunk 96 failed. Retrying with batch=100
[small retry] narn_nodes chunk 97 failed. Retrying with batch=100
[small retry] narn_nodes chunk 98 failed. Retrying with batch=100
[small retry] narn_nodes chunk 99 failed. Retrying with batch=100
[small retry] narn_nodes chunk 100 failed. Retrying with batch=100
[small retry] narn_nodes chunk 101 failed. Retrying with batch=100
[small retry] narn_nodes chunk 102 failed. Retrying with batch=100
[small retry] narn_nodes chunk 103 failed. Retrying with batch=100
[small retry] narn_nodes chunk 104 failed. Retrying with batch=100
[small retry] narn_nodes chunk 105 failed. Retrying with batch=100
[small retry] narn_nodes chunk 106 failed. Retrying with batch=100
[small retry] narn_nodes chunk 107 failed. Retrying with batch=100
[small retry] narn_nodes chunk 108 failed. Retrying with batch=100
[small retry] narn_nodes chunk 109 failed. Retrying with batch=100
[small retry] narn_nodes chunk 110 failed. Retrying with batch=100
[small retry] narn_nodes chunk 111 failed. Retrying with batch=100
[small retry] narn_nodes chunk 112 failed. Retrying with batch=100
[small retry] narn_nodes chunk 113 failed. Retrying with batch=100
[small retry] narn_nodes chunk 114 failed. Retrying with batch=100
[small retry] narn_nodes chunk 115 failed. Retrying with batch=100
[small retry] narn_nodes chunk 116 failed. Retrying with batch=100
[small retry] narn_nodes chunk 117 failed. Retrying with batch=100
[small retry] narn_nodes chunk 118 failed. Retrying with batch=100
[small retry] narn_nodes chunk 119 failed. Retrying with batch=100
[small retry] narn_nodes chunk 120 failed. Retrying with batch=100
[small retry] narn_nodes chunk 121 failed. Retrying with batch=100
[small retry] narn_nodes chunk 122 failed. Retrying with batch=100
[small retry] narn_nodes chunk 123 failed. Retrying with batch=100
[small retry] narn_nodes chunk 124 failed. Retrying with batch=100
[small retry] narn_nodes chunk 125 failed. Retrying with batch=100
[small retry] narn_nodes chunk 126 failed. Retrying with batch=100
[small retry] narn_nodes chunk 127 failed. Retrying with batch=100
[small retry] narn_nodes chunk 128 failed. Retrying with batch=100
[small retry] narn_nodes chunk 129 failed. Retrying with batch=100
[small retry] narn_nodes chunk 130 failed. Retrying with batch=100
[small retry] narn_nodes chunk 131 failed. Retrying with batch=100
[small retry] narn_nodes chunk 132 failed. Retrying with batch=100
[small retry] narn_nodes chunk 133 failed. Retrying with batch=100
[small retry] narn_nodes chunk 134 failed. Retrying with batch=100
[small retry] narn_nodes chunk 135 failed. Retrying with batch=100
[small retry] narn_nodes chunk 136 failed. Retrying with batch=100
[small retry] narn_nodes chunk 137 failed. Retrying with batch=100
[small retry] narn_nodes chunk 138 failed. Retrying with batch=100
[small retry] narn_nodes chunk 139 failed. Retrying with batch=100
[small retry] narn_nodes chunk 140 failed. Retrying with batch=100
[small retry] narn_nodes chunk 141 failed. Retrying with batch=100
[small retry] narn_nodes chunk 142 failed. Retrying with batch=100
[small retry] narn_nodes chunk 143 failed. Retrying with batch=100
[small retry] narn_nodes chunk 144 failed. Retrying with batch=100
[small retry] narn_nodes chunk 145 failed. Retrying with batch=100
[small retry] narn_nodes chunk 146 failed. Retrying with batch=100
[small retry] narn_nodes chunk 147 failed. Retrying with batch=100
[small retry] narn_nodes chunk 148 failed. Retrying with batch=100
[small retry] narn_nodes chunk 149 failed. Retrying with batch=100
[small retry] narn_nodes chunk 150 failed. Retrying with batch=100
[small retry] narn_nodes chunk 151 failed. Retrying with batch=100
[small retry] narn_nodes chunk 152 failed. Retrying with batch=100
[small retry] narn_nodes chunk 153 failed. Retrying with batch=100
[small retry] narn_nodes chunk 154 failed. Retrying with batch=100
[small retry] narn_nodes chunk 155 failed. Retrying with batch=100
[small retry] narn_nodes chunk 156 failed. Retrying with batch=100
[small retry] narn_nodes chunk 157 failed. Retrying with batch=100
[small retry] narn_nodes chunk 158 failed. Retrying with batch=100
[small retry] narn_nodes chunk 159 failed. Retrying with batch=100
[small retry] narn_nodes chunk 160 failed. Retrying with batch=100
[small retry] narn_nodes chunk 161 failed. Retrying with batch=100
[small retry] narn_nodes chunk 162 failed. Retrying with batch=100
[small retry] narn_nodes chunk 163 failed. Retrying with batch=100
[small retry] narn_nodes chunk 164 failed. Retrying with batch=100
[small retry] narn_nodes chunk 165 failed. Retrying with batch=100
[small retry] narn_nodes chunk 166 failed. Retrying with batch=100
[small retry] narn_nodes chunk 167 failed. Retrying with batch=100
[small retry] narn_nodes chunk 168 failed. Retrying with batch=100
[small retry] narn_nodes chunk 169 failed. Retrying with batch=100
[small retry] narn_nodes chunk 170 failed. Retrying with batch=100
[small retry] narn_nodes chunk 171 failed. Retrying with batch=100
[small retry] narn_nodes chunk 172 failed. Retrying with batch=100
[small retry] narn_nodes chunk 173 failed. Retrying with batch=100
[small retry] narn_nodes chunk 174 failed. Retrying with batch=100
[small retry] narn_nodes chunk 175 failed. Retrying with batch=100
[small retry] narn_nodes chunk 176 failed. Retrying with batch=100
[small retry] narn_nodes chunk 177 failed. Retrying with batch=100
[small retry] narn_nodes chunk 178 failed. Retrying with batch=100
[small retry] narn_nodes chunk 179 failed. Retrying with batch=100
[small retry] narn_nodes chunk 180 failed. Retrying with batch=100
[small retry] narn_nodes chunk 181 failed. Retrying with batch=100
[small retry] narn_nodes chunk 182 failed. Retrying with batch=100
[small retry] narn_nodes chunk 183 failed. Retrying with batch=100
[small retry] narn_nodes chunk 184 failed. Retrying with batch=100
[small retry] narn_nodes chunk 185 failed. Retrying with batch=100
[small retry] narn_nodes chunk 186 failed. Retrying with batch=100
[small retry] narn_nodes chunk 187 failed. Retrying with batch=100
[small retry] narn_nodes chunk 188 failed. Retrying with batch=100
[small retry] narn_nodes chunk 189 failed. Retrying with batch=100
[small retry] narn_nodes chunk 190 failed. Retrying with batch=100
[small retry] narn_nodes chunk 191 failed. Retrying with batch=100
[small retry] narn_nodes chunk 192 failed. Retrying with batch=100
[small retry] narn_nodes chunk 193 failed. Retrying with batch=100
[small retry] narn_nodes chunk 194 failed. Retrying with batch=100
[small retry] narn_nodes chunk 195 failed. Retrying with batch=100
[small retry] narn_nodes chunk 196 failed. Retrying with batch=100
[small retry] narn_nodes chunk 197 failed. Retrying with batch=100
[small retry] narn_nodes chunk 198 failed. Retrying with batch=100
[small retry] narn_nodes chunk 199 failed. Retrying with batch=100
[small retry] narn_nodes chunk 200 failed. Retrying with batch=100
[small retry] narn_nodes chunk 201 failed. Retrying with batch=100
[small retry] narn_nodes chunk 202 failed. Retrying with batch=100
[small retry] narn_nodes chunk 203 failed. Retrying with batch=100
[small retry] narn_nodes chunk 204 failed. Retrying with batch=100
[small retry] narn_nodes chunk 205 failed. Retrying with batch=100
[small retry] narn_nodes chunk 206 failed. Retrying with batch=100
[small retry] narn_nodes chunk 207 failed. Retrying with batch=100
[small retry] narn_nodes chunk 208 failed. Retrying with batch=100
[small retry] narn_nodes chunk 209 failed. Retrying with batch=100
[small retry] narn_nodes chunk 210 failed. Retrying with batch=100
[small retry] narn_nodes chunk 211 failed. Retrying with batch=100
[small retry] narn_nodes chunk 212 failed. Retrying with batch=100
[small retry] narn_nodes chunk 213 failed. Retrying with batch=100
[small retry] narn_nodes chunk 214 failed. Retrying with batch=100
[small retry] narn_nodes chunk 215 failed. Retrying with batch=100
[small retry] narn_nodes chunk 216 failed. Retrying with batch=100
[small retry] narn_nodes chunk 217 failed. Retrying with batch=100
[small retry] narn_nodes chunk 218 failed. Retrying with batch=100
[small retry] narn_nodes chunk 219 failed. Retrying with batch=100
[small retry] narn_nodes chunk 220 failed. Retrying with batch=100
[small retry] narn_nodes chunk 221 failed. Retrying with batch=100
[small retry] narn_nodes chunk 222 failed. Retrying with batch=100
[small retry] narn_nodes chunk 223 failed. Retrying with batch=100
[small retry] narn_nodes chunk 224 failed. Retrying with batch=100
[small retry] narn_nodes chunk 225 failed. Retrying with batch=100
[small retry] narn_nodes chunk 226 failed. Retrying with batch=100
[small retry] narn_nodes chunk 227 failed. Retrying with batch=100
[small retry] narn_nodes chunk 228 failed. Retrying with batch=100
[small retry] narn_nodes chunk 229 failed. Retrying with batch=100
[small retry] narn_nodes chunk 230 failed. Retrying with batch=100
[small retry] narn_nodes chunk 231 failed. Retrying with batch=100
[small retry] narn_nodes chunk 232 failed. Retrying with batch=100
[small retry] narn_nodes chunk 233 failed. Retrying with batch=100
[small retry] narn_nodes chunk 234 failed. Retrying with batch=100
[small retry] narn_nodes chunk 235 failed. Retrying with batch=100
[small retry] narn_nodes chunk 236 failed. Retrying with batch=100
[small retry] narn_nodes chunk 237 failed. Retrying with batch=100
[small retry] narn_nodes chunk 238 failed. Retrying with batch=100
[small retry] narn_nodes chunk 239 failed. Retrying with batch=100
[small retry] narn_nodes chunk 240 failed. Retrying with batch=100
[small retry] narn_nodes chunk 241 failed. Retrying with batch=100
[small retry] narn_nodes chunk 242 failed. Retrying with batch=100
[small retry] narn_nodes chunk 243 failed. Retrying with batch=100
[small retry] narn_nodes chunk 244 failed. Retrying with batch=100
[small retry] narn_nodes chunk 245 failed. Retrying with batch=100
[small retry] narn_nodes chunk 246 failed. Retrying with batch=100
[small retry] narn_nodes chunk 247 failed. Retrying with batch=100
[small retry] narn_nodes chunk 248 failed. Retrying with batch=100
[small retry] narn_nodes chunk 249 failed. Retrying with batch=100
[small retry] narn_nodes chunk 250 failed. Retrying with batch=100
[small retry] narn_nodes chunk 251 failed. Retrying with batch=100

Counting rows narn_nodes: 0it [00:00, ?it/s]

SUMMARY
  layer: narn_nodes
  description: North American Rail Network Nodes / rail node topology
  status: check_count_mismatch
  layer_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_nodes
  metadata_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_nodes\metadata_v2\narn_nodes_metadata_v2.json
  fields_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_nodes\metadata_v2\narn_nodes_fields_v2.csv
  object_ids_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_nodes\metadata_v2\narn_nodes_object_ids_v2.json
  source_info_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_nodes\metadata_v2\narn_nodes_source_info_v2.json
  chunk_manifest_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_nodes\narn_nodes_chunk_manifest_v2.csv
  expected_count_arcgis: 250178
  n_object_ids: 250178
  n_parquet_chunks: 0
  actual_rows_from_parquet: 0
  geometry_type: esriGeometryPoint
  elapsed_seconds: 445.36
  raw_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_nodes\raw_esri_json_chunks_v2
  parquet_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\narn_nodes\parquet_chunks_v2
  single_file_status: skipped_large_layer_250178_features

========================================================================================================================
LAYER: intermodal_rail_tofc_cofc
Intermodal Freight Facilities Rail TOFC/COFC / truck-rail transfer terminals
========================================================================================================================
URL: https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Intermodal_Freight_Facilities_Rail_TOFC_COFC/FeatureServer/0
OID field: OBJECTID
Geometry type: esriGeometryPoint
Expected count: 241
Object IDs: 241
Batch size: 1000

Probe first 3 object IDs...
Probe rows: 3
Probe columns: ['OBJECTID', 'TERMINAL', 'TERM_ADDRESS', 'CITY', 'STATE', 'ZIP_CODE', 'PORT', 'RAIL_CO', 'EQUIPMENT', 'ACCESS_RD', 'SPLC', 'LAT', 'LON', 'geometry']

Downloading intermodal_rail_tofc_cofc:   0%|          | 0/1 [00:00<?, ?it/s]

[small retry] intermodal_rail_tofc_cofc chunk 1 failed. Retrying with batch=100

Counting rows intermodal_rail_tofc_cofc: 0it [00:00, ?it/s]

SUMMARY
  layer: intermodal_rail_tofc_cofc
  description: Intermodal Freight Facilities Rail TOFC/COFC / truck-rail transfer terminals
  status: check_count_mismatch
  layer_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\intermodal_rail_tofc_cofc
  metadata_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\intermodal_rail_tofc_cofc\metadata_v2\intermodal_rail_tofc_cofc_metadata_v2.json
  fields_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\intermodal_rail_tofc_cofc\metadata_v2\intermodal_rail_tofc_cofc_fields_v2.csv
  object_ids_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\intermodal_rail_tofc_cofc\metadata_v2\intermodal_rail_tofc_cofc_object_ids_v2.json
  source_info_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\intermodal_rail_tofc_cofc\metadata_v2\intermodal_rail_tofc_cofc_source_info_v2.json
  chunk_manifest_path: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\intermodal_rail_tofc_cofc\intermodal_rail_tofc_cofc_chunk_manifest_v2.csv
  expected_count_arcgis: 241
  n_object_ids: 241
  n_parquet_chunks: 0
  actual_rows_from_parquet: 0
  geometry_type: esriGeometryPoint
  elapsed_seconds: 0.67
  raw_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\intermodal_rail_tofc_cofc\raw_esri_json_chunks_v2
  parquet_dir: E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\intermodal_rail_tofc_cofc\parquet_chunks_v2
  single_file_status: no_parquet_chunks

========================================================================================================================
NTAD / ArcGIS DOWNLOAD v2 COMPLETE
Manifest: E:\NetworkOptimization\pythonProject1\Data\00_manifest\ntad_arcgis_download_manifest_v2.csv
Log: E:\NetworkOptimization\pythonProject1\Data\00_manifest\ntad_arcgis_download_log_v2.jsonl
========================================================================================================================

,layer,status,expected_count_arcgis,n_object_ids,actual_rows_from_parquet,n_parquet_chunks,single_file_status,layer_dir
0,faf_regions,check_count_mismatch,132,132,0,0,no_parquet_chunks,E:\NetworkOptimization\pythonProject1\Data\03_...
1,faf_network_links,check_count_mismatch,487394,487394,0,0,skipped_large_layer_487394_features,E:\NetworkOptimization\pythonProject1\Data\03_...
2,faf_network_nodes,check_count_mismatch,974788,974788,0,0,skipped_large_layer_974788_features,E:\NetworkOptimization\pythonProject1\Data\03_...
3,narn_lines,check_count_mismatch,302743,302743,0,0,skipped_large_layer_302743_features,E:\NetworkOptimization\pythonProject1\Data\03_...
4,narn_nodes,check_count_mismatch,250178,250178,0,0,skipped_large_layer_250178_features,E:\NetworkOptimization\pythonProject1\Data\03_...
5,intermodal_rail_tofc_cofc,check_count_mismatch,241,241,0,0,no_parquet_chunks,E:\NetworkOptimization\pythonProject1\Data\03_...

In [4]:
# ============================================================
# FREIGHT-MNet: Download STB Public Use Waybill Sample
#
# Scope:
#   3.4 STB Public Use Waybill Sample only
#
# Years:
#   2018–2024
#
# Save root:
#   E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use
#
# What this cell downloads:
#   - Annual Public Use Waybill Sample ZIP files
#   - Annual Reference Guide PDF files
#   - Creation / sampling procedure documents if found
#
# Output structure:
#   Data
#   ├── 00_manifest
#   │   ├── stb_waybill_download_manifest.csv
#   │   ├── stb_waybill_download_log.jsonl
#   │   └── stb_waybill_scraped_links_2018_2024.csv
#   │
#   └── 04_stb
#       └── waybill_public_use
#           ├── 2018
#           │   ├── sample_zip
#           │   ├── reference_guide
#           │   ├── extracted
#           │   └── preview
#           ├── ...
#           └── 2024
#
# This code is resumable:
#   If a file already exists and looks valid, it skips it.
# ============================================================

from pathlib import Path
from urllib.parse import urljoin, urlparse, unquote
import os
import re
import json
import time
import zipfile
import hashlib
import traceback

import requests
import pandas as pd
from bs4 import BeautifulSoup
from tqdm.auto import tqdm
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# ------------------------------------------------------------
# 0. Configuration
# ------------------------------------------------------------

DATA_ROOT = Path(r"E:\NetworkOptimization\pythonProject1\Data")
WAYBILL_ROOT = DATA_ROOT / "04_stb" / "waybill_public_use"
MANIFEST_ROOT = DATA_ROOT / "00_manifest"

MANIFEST_ROOT.mkdir(parents=True, exist_ok=True)
WAYBILL_ROOT.mkdir(parents=True, exist_ok=True)

STB_WAYBILL_PAGE = "https://www.stb.gov/reports-data/waybill/"
YEARS = list(range(2018, 2025))

MANIFEST_PATH = MANIFEST_ROOT / "stb_waybill_download_manifest.csv"
LOG_PATH = MANIFEST_ROOT / "stb_waybill_download_log.jsonl"
SCRAPED_LINKS_PATH = MANIFEST_ROOT / "stb_waybill_scraped_links_2018_2024.csv"

# Set True to extract ZIP files after download.
EXTRACT_ZIPS = True

# Set True if you want SHA256 checksums. Useful but slower.
COMPUTE_SHA256 = False

# If a local file exists and looks valid, skip it.
RESUME = True

# Timeout / retry settings.
CHUNK_SIZE = 1024 * 1024
SLEEP_BETWEEN_DOWNLOADS = 0.8

print("=" * 100)
print("STB Public Use Waybill downloader")
print("DATA_ROOT:", DATA_ROOT)
print("WAYBILL_ROOT:", WAYBILL_ROOT)
print("YEARS:", YEARS)
print("=" * 100)

# ------------------------------------------------------------
# 1. HTTP session
# ------------------------------------------------------------

session = requests.Session()
session.headers.update(
    {
        "User-Agent": (
            "FREIGHT-MNet academic research downloader "
            "(STB Public Use Waybill Samples, 2018-2024)"
        )
    }
)

retry = Retry(
    total=8,
    connect=8,
    read=8,
    status=8,
    backoff_factor=1.5,
    status_forcelist=[408, 429, 500, 502, 503, 504],
    allowed_methods=["GET", "HEAD"],
    raise_on_status=False,
)

adapter = HTTPAdapter(max_retries=retry, pool_connections=8, pool_maxsize=8)
session.mount("http://", adapter)
session.mount("https://", adapter)

# ------------------------------------------------------------
# 2. Helper functions
# ------------------------------------------------------------

def log_event(record: dict) -> None:
    record = dict(record)
    record["timestamp"] = pd.Timestamp.now().isoformat()
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def file_size_mb(path: Path) -> float:
    path = Path(path)
    if not path.exists():
        return 0.0
    return round(path.stat().st_size / 1024**2, 3)


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        while True:
            b = f.read(chunk_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def safe_filename_from_url(url: str, fallback: str) -> str:
    parsed = urlparse(url)
    name = unquote(Path(parsed.path).name)
    if not name:
        name = fallback

    # Clean Windows-unfriendly characters.
    name = re.sub(r'[<>:"/\\|?*]+', "_", name)
    return name


def looks_like_valid_zip(path: Path) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False
    if path.suffix.lower() != ".zip":
        return False
    try:
        with zipfile.ZipFile(path, "r") as zf:
            bad = zf.testzip()
            return bad is None and len(zf.namelist()) > 0
    except Exception:
        return False


def looks_like_valid_pdf(path: Path) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False
    try:
        with path.open("rb") as f:
            header = f.read(5)
        return header == b"%PDF-"
    except Exception:
        return False


def looks_like_valid_file(path: Path, kind: str) -> bool:
    if kind == "sample_zip":
        return looks_like_valid_zip(path)
    if kind == "reference_guide":
        return looks_like_valid_pdf(path)
    if kind == "procedure_doc":
        # Procedure docs can be PDF or other documents.
        return path.exists() and path.stat().st_size > 1024
    return path.exists() and path.stat().st_size > 0


def download_file(url: str, out_path: Path, kind: str, label: str, overwrite: bool = False) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if RESUME and out_path.exists() and not overwrite and looks_like_valid_file(out_path, kind):
        print(f"[skip existing valid] {label}: {out_path} ({file_size_mb(out_path)} MB)")
        log_event(
            {
                "status": "exists_valid",
                "kind": kind,
                "label": label,
                "url": url,
                "path": str(out_path),
                "size_mb": file_size_mb(out_path),
            }
        )
        return out_path

    part_path = out_path.with_suffix(out_path.suffix + ".part")
    if part_path.exists():
        part_path.unlink()

    print("\n" + "-" * 100)
    print("[download]", label)
    print("URL:", url)
    print("OUT:", out_path)
    print("-" * 100)

    with session.get(url, stream=True, timeout=300) as r:
        if r.status_code >= 400:
            raise RuntimeError(f"HTTP {r.status_code} while downloading {url}\n{r.text[:500]}")

        total = int(r.headers.get("content-length", 0))
        with part_path.open("wb") as f, tqdm(
            total=total,
            unit="B",
            unit_scale=True,
            desc=label,
        ) as pbar:
            for chunk in r.iter_content(chunk_size=CHUNK_SIZE):
                if chunk:
                    f.write(chunk)
                    pbar.update(len(chunk))

    part_path.replace(out_path)

    # Validate downloaded file.
    if not looks_like_valid_file(out_path, kind):
        raise RuntimeError(f"Downloaded file does not look valid: {out_path}")

    log_event(
        {
            "status": "downloaded",
            "kind": kind,
            "label": label,
            "url": url,
            "path": str(out_path),
            "size_mb": file_size_mb(out_path),
        }
    )

    print(f"[saved] {out_path} ({file_size_mb(out_path)} MB)")
    return out_path


def extract_zip_if_needed(zip_path: Path, extract_dir: Path) -> dict:
    zip_path = Path(zip_path)
    extract_dir = Path(extract_dir)
    extract_dir.mkdir(parents=True, exist_ok=True)

    marker = extract_dir / f".extracted_{zip_path.stem}.json"

    if RESUME and marker.exists():
        try:
            info = json.loads(marker.read_text(encoding="utf-8"))
            if info.get("status") == "ok":
                print(f"[skip extraction] {zip_path.name}")
                return info
        except Exception:
            pass

    print(f"[extract] {zip_path} -> {extract_dir}")

    extracted_files = []
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(extract_dir)
        for name in zf.namelist():
            p = extract_dir / name
            if p.exists() and p.is_file():
                extracted_files.append(str(p))

    info = {
        "status": "ok",
        "zip_path": str(zip_path),
        "extract_dir": str(extract_dir),
        "n_extracted_files": len(extracted_files),
        "extracted_files": extracted_files,
    }

    marker.write_text(json.dumps(info, indent=2, ensure_ascii=False), encoding="utf-8")

    log_event(
        {
            "status": "extracted",
            "zip_path": str(zip_path),
            "extract_dir": str(extract_dir),
            "n_extracted_files": len(extracted_files),
        }
    )

    return info


def write_text_previews(extract_dir: Path, preview_dir: Path, year: int, max_lines: int = 20) -> list:
    extract_dir = Path(extract_dir)
    preview_dir = Path(preview_dir)
    preview_dir.mkdir(parents=True, exist_ok=True)

    preview_records = []

    candidate_files = []
    for pattern in ["*.txt", "*.TXT", "*.dat", "*.DAT", "*.csv", "*.CSV"]:
        candidate_files.extend(extract_dir.rglob(pattern))

    for p in sorted(set(candidate_files)):
        if not p.is_file():
            continue

        preview_path = preview_dir / f"{year}_{p.stem}_first{max_lines}_lines.txt"

        lines = []
        try:
            # Fixed-width public-use files are usually plain text.
            with p.open("r", encoding="utf-8", errors="replace") as f:
                for _ in range(max_lines):
                    line = f.readline()
                    if not line:
                        break
                    lines.append(line.rstrip("\n"))
        except Exception as e:
            preview_records.append(
                {
                    "year": year,
                    "source_file": str(p),
                    "preview_path": None,
                    "status": "failed",
                    "error": repr(e),
                }
            )
            continue

        preview_path.write_text("\n".join(lines), encoding="utf-8")

        preview_records.append(
            {
                "year": year,
                "source_file": str(p),
                "preview_path": str(preview_path),
                "status": "ok",
                "n_preview_lines": len(lines),
                "source_size_mb": file_size_mb(p),
            }
        )

    return preview_records


def classify_link(text: str, href: str) -> tuple[int | None, str | None]:
    """
    Return (year, kind).
    kind:
      - sample_zip
      - reference_guide
      - procedure_doc
      - None
    """
    combined = f"{text} {href}"

    year_match = re.search(r"(2018|2019|2020|2021|2022|2023|2024)", combined)
    year = int(year_match.group(1)) if year_match else None

    lower = combined.lower()

    if year in YEARS:
        if "public use waybill sample" in lower or "publicusewaybillsample" in lower:
            return year, "sample_zip"
        if "reference guide" in lower or "waybill-reference-guide" in lower:
            return year, "reference_guide"

    # Optional general procedure docs.
    if (
        "creation of the public use waybill sample" in lower
        or "procedure for sampling waybill records" in lower
        or "procedures for sampling waybill records" in lower
    ):
        return None, "procedure_doc"

    return year, None


def scrape_stb_waybill_links() -> pd.DataFrame:
    print("[scrape] STB Waybill page:", STB_WAYBILL_PAGE)
    r = session.get(STB_WAYBILL_PAGE, timeout=120)
    r.raise_for_status()

    soup = BeautifulSoup(r.text, "html.parser")

    rows = []
    for a in soup.find_all("a", href=True):
        text = " ".join(a.get_text(" ", strip=True).split())
        href = urljoin(STB_WAYBILL_PAGE, a["href"])

        year, kind = classify_link(text, href)

        if kind in {"sample_zip", "reference_guide"} and year in YEARS:
            rows.append(
                {
                    "year": year,
                    "kind": kind,
                    "text": text,
                    "url": href,
                    "source": "scraped",
                }
            )

        elif kind == "procedure_doc":
            rows.append(
                {
                    "year": None,
                    "kind": kind,
                    "text": text,
                    "url": href,
                    "source": "scraped",
                }
            )

    df = pd.DataFrame(rows).drop_duplicates(subset=["year", "kind", "url"]).reset_index(drop=True)

    if not df.empty:
        df = df.sort_values(["kind", "year", "text"], na_position="last").reset_index(drop=True)

    return df


# Fallback URLs are only used if page scraping misses a year.
# The scraper is preferred because STB sometimes uses revised filenames.
FALLBACK_LINKS = []
for year in YEARS:
    FALLBACK_LINKS.append(
        {
            "year": year,
            "kind": "sample_zip",
            "text": f"{year} Public Use Waybill Sample",
            "url": f"https://www.stb.gov/wp-content/uploads/PublicUseWaybillSample{year}.zip",
            "source": "fallback_pattern",
        }
    )

    # Reference guide filenames are mostly regular, except 2021 revised/V2.
    if year == 2021:
        ref_url = "https://www.stb.gov/wp-content/uploads/2021-STB-Waybill-Reference-Guide-V2.pdf"
    else:
        ref_url = f"https://www.stb.gov/wp-content/uploads/{year}-STB-Waybill-Reference-Guide.pdf"

    FALLBACK_LINKS.append(
        {
            "year": year,
            "kind": "reference_guide",
            "text": f"Reference Guide – {year} Waybill Sample",
            "url": ref_url,
            "source": "fallback_pattern",
        }
    )


def complete_links_with_fallback(scraped: pd.DataFrame) -> pd.DataFrame:
    """
    Ensure each year has one sample_zip and one reference_guide.
    Prefer scraped links. Fill missing with fallback patterns.
    """
    rows = []

    # Keep all scraped procedure docs.
    if not scraped.empty:
        rows.extend(scraped[scraped["kind"] == "procedure_doc"].to_dict("records"))

    for year in YEARS:
        for kind in ["sample_zip", "reference_guide"]:
            found = pd.DataFrame()
            if not scraped.empty:
                found = scraped[(scraped["year"] == year) & (scraped["kind"] == kind)]

            if len(found) > 0:
                # Prefer first scraped link.
                rows.append(found.iloc[0].to_dict())
            else:
                fallback = [x for x in FALLBACK_LINKS if x["year"] == year and x["kind"] == kind][0]
                rows.append(fallback)

    result = pd.DataFrame(rows).drop_duplicates(subset=["year", "kind", "url"]).reset_index(drop=True)
    result.to_csv(SCRAPED_LINKS_PATH, index=False, encoding="utf-8-sig")
    return result


def out_path_for_item(item: dict) -> Path:
    year = item.get("year")
    kind = item["kind"]
    url = item["url"]

    if kind == "procedure_doc":
        docs_dir = WAYBILL_ROOT / "_docs"
        docs_dir.mkdir(parents=True, exist_ok=True)
        filename = safe_filename_from_url(url, fallback=re.sub(r"\W+", "_", item["text"]) + ".pdf")
        return docs_dir / filename

    year = int(year)
    year_dir = WAYBILL_ROOT / str(year)

    if kind == "sample_zip":
        subdir = year_dir / "sample_zip"
        fallback = f"PublicUseWaybillSample{year}.zip"
    elif kind == "reference_guide":
        subdir = year_dir / "reference_guide"
        fallback = f"{year}-STB-Waybill-Reference-Guide.pdf"
    else:
        subdir = year_dir / "other"
        fallback = f"{year}_{kind}"

    subdir.mkdir(parents=True, exist_ok=True)
    filename = safe_filename_from_url(url, fallback=fallback)
    return subdir / filename


# ------------------------------------------------------------
# 3. Scrape links
# ------------------------------------------------------------

scraped_links = scrape_stb_waybill_links()

print("\nScraped links:")
display(scraped_links)

links = complete_links_with_fallback(scraped_links)

print("\nFinal links to download:")
display(links)

# Sanity check.
required = []
for year in YEARS:
    for kind in ["sample_zip", "reference_guide"]:
        ok = ((links["year"] == year) & (links["kind"] == kind)).any()
        required.append({"year": year, "kind": kind, "found": ok})

required_df = pd.DataFrame(required)
display(required_df)

if not required_df["found"].all():
    missing = required_df[required_df["found"] == False]
    raise RuntimeError(f"Missing required links:\n{missing}")

# ------------------------------------------------------------
# 4. Download all files
# ------------------------------------------------------------

manifest_rows = []
preview_rows = []

for item in links.to_dict("records"):
    kind = item["kind"]
    year = item.get("year")
    url = item["url"]
    text = item.get("text", "")
    source = item.get("source", "")

    out_path = out_path_for_item(item)

    label_year = str(int(year)) if pd.notna(year) else "docs"
    label = f"STB Waybill {label_year} | {kind}"

    record = {
        "year": int(year) if pd.notna(year) else None,
        "kind": kind,
        "text": text,
        "url": url,
        "source": source,
        "out_path": str(out_path),
    }

    try:
        downloaded_path = download_file(url, out_path, kind=kind, label=label)
        record["status"] = "downloaded_or_exists"
        record["size_mb"] = file_size_mb(downloaded_path)

        if COMPUTE_SHA256:
            record["sha256"] = sha256_file(downloaded_path)

        # For sample ZIPs, extract and preview.
        if kind == "sample_zip" and EXTRACT_ZIPS:
            year_int = int(year)
            extract_dir = WAYBILL_ROOT / str(year_int) / "extracted"
            preview_dir = WAYBILL_ROOT / str(year_int) / "preview"

            extract_info = extract_zip_if_needed(downloaded_path, extract_dir)

            record["extract_status"] = extract_info.get("status")
            record["n_extracted_files"] = extract_info.get("n_extracted_files")

            previews = write_text_previews(extract_dir, preview_dir, year_int, max_lines=20)
            preview_rows.extend(previews)

            record["n_preview_files"] = len(previews)

    except Exception as e:
        record["status"] = "failed"
        record["error"] = repr(e)
        record["traceback"] = traceback.format_exc()[:4000]
        print(f"[FAILED] {label}: {e}")

    manifest_rows.append(record)

    # Save progress after every file.
    pd.DataFrame(manifest_rows).to_csv(MANIFEST_PATH, index=False, encoding="utf-8-sig")

    if preview_rows:
        pd.DataFrame(preview_rows).to_csv(
            MANIFEST_ROOT / "stb_waybill_text_preview_manifest.csv",
            index=False,
            encoding="utf-8-sig",
        )

    time.sleep(SLEEP_BETWEEN_DOWNLOADS)

# ------------------------------------------------------------
# 5. Final summary
# ------------------------------------------------------------

manifest = pd.DataFrame(manifest_rows)
manifest.to_csv(MANIFEST_PATH, index=False, encoding="utf-8-sig")

if preview_rows:
    preview_manifest = pd.DataFrame(preview_rows)
    preview_manifest_path = MANIFEST_ROOT / "stb_waybill_text_preview_manifest.csv"
    preview_manifest.to_csv(preview_manifest_path, index=False, encoding="utf-8-sig")
else:
    preview_manifest_path = None

print("\n" + "=" * 100)
print("STB PUBLIC USE WAYBILL DOWNLOAD COMPLETE")
print("=" * 100)
print("WAYBILL_ROOT:", WAYBILL_ROOT)
print("Manifest:", MANIFEST_PATH)
print("Log:", LOG_PATH)
print("Scraped links:", SCRAPED_LINKS_PATH)
print("Preview manifest:", preview_manifest_path)
print("=" * 100)

display_cols = [
    "year",
    "kind",
    "status",
    "source",
    "size_mb",
    "n_extracted_files",
    "n_preview_files",
    "out_path",
]
display_cols = [c for c in display_cols if c in manifest.columns]
display(manifest[display_cols])

# Fail loudly if any required annual sample/reference failed.
required_manifest = manifest[
    manifest["kind"].isin(["sample_zip", "reference_guide"])
].copy()

failed_required = required_manifest[required_manifest["status"] != "downloaded_or_exists"]

if len(failed_required) > 0:
    print("\nRequired files with problems:")
    display(failed_required[["year", "kind", "status", "url", "out_path", "error"]])
    raise RuntimeError("Some required STB Waybill files failed to download. See table above.")

print("\nAll required 2018–2024 Waybill sample ZIPs and Reference Guides are present.")

====================================================================================================
STB Public Use Waybill downloader
DATA_ROOT: E:\NetworkOptimization\pythonProject1\Data
WAYBILL_ROOT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use
YEARS: [2018, 2019, 2020, 2021, 2022, 2023, 2024]
====================================================================================================
[scrape] STB Waybill page: https://www.stb.gov/reports-data/waybill/

Scraped links:

,year,kind,text,url,source
0,NaN,procedure_doc,Creation of the Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/files/d...,scraped
1,NaN,procedure_doc,Procedure for Sampling Waybill Records by Comp...,https://www.stb.gov/wp-content/uploads/Procedu...,scraped
2,NaN,procedure_doc,Procedures for Sampling Waybill Records,https://www.stb.gov/wp-content/uploads/STB-Sta...,scraped
3,2018.0,reference_guide,Reference Guide – 2018 Waybill Sample,https://www.stb.gov/wp-content/uploads/2018-ST...,scraped
4,2019.0,reference_guide,Reference Guide – 2019 Waybill Sample,https://www.stb.gov/wp-content/uploads/2019-ST...,scraped
5,2020.0,reference_guide,Reference Guide – 2020 Waybill Sample,https://www.stb.gov/wp-content/uploads/2020-ST...,scraped
6,2021.0,reference_guide,Reference Guide – 2021 Waybill Sample (REVISED),https://www.stb.gov/wp-content/uploads/2021-ST...,scraped
7,2022.0,reference_guide,Reference Guide – 2022 Waybill Sample,https://www.stb.gov/wp-content/uploads/2022-ST...,scraped
8,2023.0,reference_guide,Reference Guide – 2023 Waybill Sample,https://www.stb.gov/wp-content/uploads/2023-ST...,scraped
9,2024.0,reference_guide,Reference Guide – 2024 Waybill Sample,https://www.stb.gov/wp-content/uploads/2024-ST...,scraped
10,2018.0,sample_zip,2018 Public Use Waybill Sample (REVISED),https://www.stb.gov/wp-content/uploads/PublicU...,scraped
11,2019.0,sample_zip,2019 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
12,2020.0,sample_zip,2020 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
13,2021.0,sample_zip,2021 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
14,2022.0,sample_zip,2022 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
15,2023.0,sample_zip,2023 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
16,2024.0,sample_zip,2024 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped

Final links to download:

,year,kind,text,url,source
0,NaN,procedure_doc,Creation of the Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/files/d...,scraped
1,NaN,procedure_doc,Procedure for Sampling Waybill Records by Comp...,https://www.stb.gov/wp-content/uploads/Procedu...,scraped
2,NaN,procedure_doc,Procedures for Sampling Waybill Records,https://www.stb.gov/wp-content/uploads/STB-Sta...,scraped
3,2018.0,sample_zip,2018 Public Use Waybill Sample (REVISED),https://www.stb.gov/wp-content/uploads/PublicU...,scraped
4,2018.0,reference_guide,Reference Guide – 2018 Waybill Sample,https://www.stb.gov/wp-content/uploads/2018-ST...,scraped
5,2019.0,sample_zip,2019 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
6,2019.0,reference_guide,Reference Guide – 2019 Waybill Sample,https://www.stb.gov/wp-content/uploads/2019-ST...,scraped
7,2020.0,sample_zip,2020 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
8,2020.0,reference_guide,Reference Guide – 2020 Waybill Sample,https://www.stb.gov/wp-content/uploads/2020-ST...,scraped
9,2021.0,sample_zip,2021 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
10,2021.0,reference_guide,Reference Guide – 2021 Waybill Sample (REVISED),https://www.stb.gov/wp-content/uploads/2021-ST...,scraped
11,2022.0,sample_zip,2022 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
12,2022.0,reference_guide,Reference Guide – 2022 Waybill Sample,https://www.stb.gov/wp-content/uploads/2022-ST...,scraped
13,2023.0,sample_zip,2023 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
14,2023.0,reference_guide,Reference Guide – 2023 Waybill Sample,https://www.stb.gov/wp-content/uploads/2023-ST...,scraped
15,2024.0,sample_zip,2024 Public Use Waybill Sample,https://www.stb.gov/wp-content/uploads/PublicU...,scraped
16,2024.0,reference_guide,Reference Guide – 2024 Waybill Sample,https://www.stb.gov/wp-content/uploads/2024-ST...,scraped

    year             kind  found
0   2018       sample_zip   True
1   2018  reference_guide   True
2   2019       sample_zip   True
3   2019  reference_guide   True
4   2020       sample_zip   True
5   2020  reference_guide   True
6   2021       sample_zip   True
7   2021  reference_guide   True
8   2022       sample_zip   True
9   2022  reference_guide   True
10  2023       sample_zip   True
11  2023  reference_guide   True
12  2024       sample_zip   True
13  2024  reference_guide   True

----------------------------------------------------------------------------------------------------
[download] STB Waybill docs | procedure_doc
URL: https://www.stb.gov/wp-content/uploads/files/docs/waybill/Creation%20of%20the%20Public%20Use%20Waybill%20Sample.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\_docs\Creation of the Public Use Waybill Sample.pdf
----------------------------------------------------------------------------------------------------

STB Waybill docs | procedure_doc:   0%|          | 0.00/9.32k [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\_docs\Creation of the Public Use Waybill Sample.pdf (0.009 MB)

----------------------------------------------------------------------------------------------------
[download] STB Waybill docs | procedure_doc
URL: https://www.stb.gov/wp-content/uploads/Procedures-for-Sampling-Waybill-Records-by-Computer-2009-Edition.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\_docs\Procedures-for-Sampling-Waybill-Records-by-Computer-2009-Edition.pdf
----------------------------------------------------------------------------------------------------

STB Waybill docs | procedure_doc:   0%|          | 0.00/95.0k [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\_docs\Procedures-for-Sampling-Waybill-Records-by-Computer-2009-Edition.pdf (0.091 MB)

----------------------------------------------------------------------------------------------------
[download] STB Waybill docs | procedure_doc
URL: https://www.stb.gov/wp-content/uploads/STB-Statement-81-1-Procedures-for-Sampling-Waybill-Records-2021-Edition.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\_docs\STB-Statement-81-1-Procedures-for-Sampling-Waybill-Records-2021-Edition.pdf
----------------------------------------------------------------------------------------------------

STB Waybill docs | procedure_doc:   0%|          | 0.00/143k [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\_docs\STB-Statement-81-1-Procedures-for-Sampling-Waybill-Records-2021-Edition.pdf (0.137 MB)

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2018 | sample_zip
URL: https://www.stb.gov/wp-content/uploads/PublicUseWaybillSample2018-REV-1-13-23.zip
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2018\sample_zip\PublicUseWaybillSample2018-REV-1-13-23.zip
----------------------------------------------------------------------------------------------------

STB Waybill 2018 | sample_zip:   0%|          | 0.00/21.9M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2018\sample_zip\PublicUseWaybillSample2018-REV-1-13-23.zip (20.89 MB)
[extract] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2018\sample_zip\PublicUseWaybillSample2018-REV-1-13-23.zip -> E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2018\extracted

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2018 | reference_guide
URL: https://www.stb.gov/wp-content/uploads/2018-STB-Waybill-Reference-Guide.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2018\reference_guide\2018-STB-Waybill-Reference-Guide.pdf
----------------------------------------------------------------------------------------------------

STB Waybill 2018 | reference_guide:   0%|          | 0.00/5.39M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2018\reference_guide\2018-STB-Waybill-Reference-Guide.pdf (5.141 MB)

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2019 | sample_zip
URL: https://www.stb.gov/wp-content/uploads/PublicUseWaybillSample2019.zip
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2019\sample_zip\PublicUseWaybillSample2019.zip
----------------------------------------------------------------------------------------------------

STB Waybill 2019 | sample_zip:   0%|          | 0.00/21.5M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2019\sample_zip\PublicUseWaybillSample2019.zip (20.46 MB)
[extract] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2019\sample_zip\PublicUseWaybillSample2019.zip -> E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2019\extracted

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2019 | reference_guide
URL: https://www.stb.gov/wp-content/uploads/2019-STB-Waybill-Reference-Guide.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2019\reference_guide\2019-STB-Waybill-Reference-Guide.pdf
----------------------------------------------------------------------------------------------------

STB Waybill 2019 | reference_guide:   0%|          | 0.00/4.33M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2019\reference_guide\2019-STB-Waybill-Reference-Guide.pdf (4.126 MB)

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2020 | sample_zip
URL: https://www.stb.gov/wp-content/uploads/PublicUseWaybillSample2020.zip
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2020\sample_zip\PublicUseWaybillSample2020.zip
----------------------------------------------------------------------------------------------------

STB Waybill 2020 | sample_zip:   0%|          | 0.00/20.2M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2020\sample_zip\PublicUseWaybillSample2020.zip (19.242 MB)
[extract] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2020\sample_zip\PublicUseWaybillSample2020.zip -> E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2020\extracted

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2020 | reference_guide
URL: https://www.stb.gov/wp-content/uploads/2020-STB-Waybill-Reference-Guide.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2020\reference_guide\2020-STB-Waybill-Reference-Guide.pdf
----------------------------------------------------------------------------------------------------

STB Waybill 2020 | reference_guide:   0%|          | 0.00/5.49M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2020\reference_guide\2020-STB-Waybill-Reference-Guide.pdf (5.236 MB)

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2021 | sample_zip
URL: https://www.stb.gov/wp-content/uploads/PublicUseWaybillSample2021.zip
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2021\sample_zip\PublicUseWaybillSample2021.zip
----------------------------------------------------------------------------------------------------

STB Waybill 2021 | sample_zip:   0%|          | 0.00/65.3M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2021\sample_zip\PublicUseWaybillSample2021.zip (62.273 MB)
[extract] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2021\sample_zip\PublicUseWaybillSample2021.zip -> E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2021\extracted

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2021 | reference_guide
URL: https://www.stb.gov/wp-content/uploads/2021-STB-Waybill-Reference-Guide-V2.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2021\reference_guide\2021-STB-Waybill-Reference-Guide-V2.pdf
----------------------------------------------------------------------------------------------------

STB Waybill 2021 | reference_guide:   0%|          | 0.00/5.40M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2021\reference_guide\2021-STB-Waybill-Reference-Guide-V2.pdf (5.152 MB)

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2022 | sample_zip
URL: https://www.stb.gov/wp-content/uploads/PublicUseWaybillSample2022.zip
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2022\sample_zip\PublicUseWaybillSample2022.zip
----------------------------------------------------------------------------------------------------

STB Waybill 2022 | sample_zip:   0%|          | 0.00/66.1M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2022\sample_zip\PublicUseWaybillSample2022.zip (63.023 MB)
[extract] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2022\sample_zip\PublicUseWaybillSample2022.zip -> E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2022\extracted

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2022 | reference_guide
URL: https://www.stb.gov/wp-content/uploads/2022-STB-Waybill-Reference-Guide.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2022\reference_guide\2022-STB-Waybill-Reference-Guide.pdf
----------------------------------------------------------------------------------------------------

STB Waybill 2022 | reference_guide:   0%|          | 0.00/5.26M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2022\reference_guide\2022-STB-Waybill-Reference-Guide.pdf (5.019 MB)

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2023 | sample_zip
URL: https://www.stb.gov/wp-content/uploads/PublicUseWaybillSample2023.zip
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2023\sample_zip\PublicUseWaybillSample2023.zip
----------------------------------------------------------------------------------------------------

STB Waybill 2023 | sample_zip:   0%|          | 0.00/66.1M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2023\sample_zip\PublicUseWaybillSample2023.zip (63.045 MB)
[extract] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2023\sample_zip\PublicUseWaybillSample2023.zip -> E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2023\extracted

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2023 | reference_guide
URL: https://www.stb.gov/wp-content/uploads/2023-STB-Waybill-Reference-Guide.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2023\reference_guide\2023-STB-Waybill-Reference-Guide.pdf
----------------------------------------------------------------------------------------------------

STB Waybill 2023 | reference_guide:   0%|          | 0.00/4.21M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2023\reference_guide\2023-STB-Waybill-Reference-Guide.pdf (4.019 MB)

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2024 | sample_zip
URL: https://www.stb.gov/wp-content/uploads/PublicUseWaybillSample2024.zip
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2024\sample_zip\PublicUseWaybillSample2024.zip
----------------------------------------------------------------------------------------------------

STB Waybill 2024 | sample_zip:   0%|          | 0.00/68.2M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2024\sample_zip\PublicUseWaybillSample2024.zip (65.038 MB)
[extract] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2024\sample_zip\PublicUseWaybillSample2024.zip -> E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2024\extracted

----------------------------------------------------------------------------------------------------
[download] STB Waybill 2024 | reference_guide
URL: https://www.stb.gov/wp-content/uploads/2024-STB-Waybill-Reference-Guide.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2024\reference_guide\2024-STB-Waybill-Reference-Guide.pdf
----------------------------------------------------------------------------------------------------

STB Waybill 2024 | reference_guide:   0%|          | 0.00/5.20M [00:00<?, ?B/s]

[saved] E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2024\reference_guide\2024-STB-Waybill-Reference-Guide.pdf (4.96 MB)

====================================================================================================
STB PUBLIC USE WAYBILL DOWNLOAD COMPLETE
====================================================================================================
WAYBILL_ROOT: E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use
Manifest: E:\NetworkOptimization\pythonProject1\Data\00_manifest\stb_waybill_download_manifest.csv
Log: E:\NetworkOptimization\pythonProject1\Data\00_manifest\stb_waybill_download_log.jsonl
Scraped links: E:\NetworkOptimization\pythonProject1\Data\00_manifest\stb_waybill_scraped_links_2018_2024.csv
Preview manifest: E:\NetworkOptimization\pythonProject1\Data\00_manifest\stb_waybill_text_preview_manifest.csv
====================================================================================================

,year,kind,status,source,size_mb,n_extracted_files,n_preview_files,out_path
0,NaN,procedure_doc,downloaded_or_exists,scraped,0.009,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...
1,NaN,procedure_doc,downloaded_or_exists,scraped,0.091,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...
2,NaN,procedure_doc,downloaded_or_exists,scraped,0.137,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...
3,2018.0,sample_zip,downloaded_or_exists,scraped,20.890,7.0,1.0,E:\NetworkOptimization\pythonProject1\Data\04_...
4,2018.0,reference_guide,downloaded_or_exists,scraped,5.141,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...
5,2019.0,sample_zip,downloaded_or_exists,scraped,20.460,7.0,1.0,E:\NetworkOptimization\pythonProject1\Data\04_...
6,2019.0,reference_guide,downloaded_or_exists,scraped,4.126,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...
7,2020.0,sample_zip,downloaded_or_exists,scraped,19.242,7.0,1.0,E:\NetworkOptimization\pythonProject1\Data\04_...
8,2020.0,reference_guide,downloaded_or_exists,scraped,5.236,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...
9,2021.0,sample_zip,downloaded_or_exists,scraped,62.273,7.0,1.0,E:\NetworkOptimization\pythonProject1\Data\04_...
10,2021.0,reference_guide,downloaded_or_exists,scraped,5.152,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...
11,2022.0,sample_zip,downloaded_or_exists,scraped,63.023,7.0,1.0,E:\NetworkOptimization\pythonProject1\Data\04_...
12,2022.0,reference_guide,downloaded_or_exists,scraped,5.019,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...
13,2023.0,sample_zip,downloaded_or_exists,scraped,63.045,7.0,1.0,E:\NetworkOptimization\pythonProject1\Data\04_...
14,2023.0,reference_guide,downloaded_or_exists,scraped,4.019,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...
15,2024.0,sample_zip,downloaded_or_exists,scraped,65.038,7.0,1.0,E:\NetworkOptimization\pythonProject1\Data\04_...
16,2024.0,reference_guide,downloaded_or_exists,scraped,4.960,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\04_...

All required 2018–2024 Waybill sample ZIPs and Reference Guides are present.

In [5]:
# ============================================================
# FREIGHT-MNet: Download STB Rail Service Performance Data
#
# Scope:
#   3.5 STB Rail Service Performance Data only
#
# Source:
#   https://www.stb.gov/reports-data/rail-service-data/
#
# Save root:
#   E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance
#
# What this downloads:
#   1. Weekly rail service XLSX files, 2020–current page latest year
#      - All Class 1 Railroads consolidated files
#      - Individual carrier files: BNSF, CN, CP, CPKC, CSX, CTCO, KCS, NS, UP
#   2. STB-1145 CSV time-series files if present
#   3. Carrier methodology documents if present
#   4. Full link inventory and download manifest
#
# Resume behavior:
#   - If a file already exists and looks valid, it is skipped.
#   - Manifest is saved after every file.
#   - If interrupted, rerun the same cell.
# ============================================================

from pathlib import Path
from urllib.parse import urljoin, urlparse, unquote
import os
import re
import json
import time
import hashlib
import zipfile
import traceback
from datetime import datetime, date

import requests
import pandas as pd
from bs4 import BeautifulSoup
from tqdm.auto import tqdm
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from requests.utils import requote_uri

# Optional: only used for light workbook metadata.
try:
    import openpyxl
    HAS_OPENPYXL = True
except Exception:
    HAS_OPENPYXL = False

# ------------------------------------------------------------
# 0. Configuration
# ------------------------------------------------------------

DATA_ROOT = Path(r"E:\NetworkOptimization\pythonProject1\Data")
STB_RAIL_ROOT = DATA_ROOT / "04_stb" / "rail_service_performance"
MANIFEST_ROOT = DATA_ROOT / "00_manifest"

STB_PAGE_URL = "https://www.stb.gov/reports-data/rail-service-data/"

# Core research window is 2020-2024.
# We also download 2025-2026 if present because STB service data are current weekly data.
TARGET_YEARS = list(range(2020, datetime.now().year + 1))

# If you only want the core model period, uncomment this:
# TARGET_YEARS = list(range(2020, 2025))

DOWNLOAD_WEEKLY_XLSX = True
DOWNLOAD_WEEKLY_PDF = False       # Usually not needed for 2020+; set True if you want PDF copies too.
DOWNLOAD_STB1145_CSV = True       # Manifest/OETA/local-service time series CSV links, if present.
DOWNLOAD_METHODOLOGY_DOCS = True  # Carrier methodology docs.

# Keep existing valid files and skip them.
RESUME = True

# Compute SHA256 for downloaded files. Useful but slower.
COMPUTE_SHA256 = False

# Validate xlsx by checking ZIP structure. This is fast enough.
VALIDATE_XLSX = True

# Only collect workbook sheet names for first N XLSX files to avoid slow metadata scanning.
COLLECT_SHEET_NAMES_FOR_FIRST_N = 50

# Download pacing.
CHUNK_SIZE = 1024 * 1024
SLEEP_BETWEEN_DOWNLOADS = 0.20

# Paths.
STB_RAIL_ROOT.mkdir(parents=True, exist_ok=True)
MANIFEST_ROOT.mkdir(parents=True, exist_ok=True)

RAW_WEEKLY_ROOT = STB_RAIL_ROOT / "weekly_service_files"
STB1145_ROOT = STB_RAIL_ROOT / "stb_1145_csv"
DOCS_ROOT = STB_RAIL_ROOT / "methodology_docs"
METADATA_ROOT = STB_RAIL_ROOT / "_metadata"

for d in [RAW_WEEKLY_ROOT, STB1145_ROOT, DOCS_ROOT, METADATA_ROOT]:
    d.mkdir(parents=True, exist_ok=True)

LINK_INVENTORY_PATH = METADATA_ROOT / "stb_rail_service_link_inventory.csv"
DOWNLOAD_MANIFEST_PATH = MANIFEST_ROOT / "stb_rail_service_download_manifest.csv"
DOWNLOAD_LOG_PATH = MANIFEST_ROOT / "stb_rail_service_download_log.jsonl"
SHEET_PREVIEW_PATH = METADATA_ROOT / "stb_rail_service_xlsx_sheet_preview.csv"
PAGE_HTML_PATH = METADATA_ROOT / "stb_rail_service_page_snapshot.html"

print("=" * 100)
print("STB Rail Service Performance downloader")
print("DATA_ROOT:", DATA_ROOT)
print("STB_RAIL_ROOT:", STB_RAIL_ROOT)
print("TARGET_YEARS:", TARGET_YEARS)
print("HAS_OPENPYXL:", HAS_OPENPYXL)
print("=" * 100)

# ------------------------------------------------------------
# 1. HTTP session with retry
# ------------------------------------------------------------

session = requests.Session()
session.headers.update(
    {
        "User-Agent": (
            "FREIGHT-MNet academic research downloader "
            "(STB Rail Service Performance Data)"
        )
    }
)

retry = Retry(
    total=8,
    connect=8,
    read=8,
    status=8,
    backoff_factor=1.5,
    status_forcelist=[408, 429, 500, 502, 503, 504],
    allowed_methods=["GET", "HEAD"],
    raise_on_status=False,
)

adapter = HTTPAdapter(max_retries=retry, pool_connections=8, pool_maxsize=8)
session.mount("http://", adapter)
session.mount("https://", adapter)

# ------------------------------------------------------------
# 2. Helpers
# ------------------------------------------------------------

def log_event(record: dict) -> None:
    record = dict(record)
    record["timestamp"] = pd.Timestamp.now().isoformat()
    with DOWNLOAD_LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def file_size_mb(path: Path) -> float:
    path = Path(path)
    if not path.exists():
        return 0.0
    return round(path.stat().st_size / 1024**2, 4)


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        while True:
            b = f.read(chunk_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def clean_windows_filename(name: str) -> str:
    name = unquote(name)
    name = re.sub(r'[<>:"/\\|?*]+', "_", name)
    name = re.sub(r"\s+", " ", name).strip()
    return name[:180]


def short_hash(text: str, n: int = 10) -> str:
    return hashlib.sha1(text.encode("utf-8", errors="ignore")).hexdigest()[:n]


def parse_date_from_text_or_url(text: str, url: str):
    """
    Parse dates like:
      05-13-26.xlsx
      2026-05-13
    Returns: datetime.date or None
    """
    combined = f"{text} {url}"

    # Pattern 1: MM-DD-YY
    m = re.search(r"\b(\d{2})-(\d{2})-(\d{2})\b", combined)
    if m:
        mm, dd, yy = map(int, m.groups())
        yyyy = 2000 + yy if yy <= 69 else 1900 + yy
        try:
            return date(yyyy, mm, dd)
        except Exception:
            pass

    # Pattern 2: YYYY-MM-DD
    m = re.search(r"\b(20\d{2})-(\d{2})-(\d{2})\b", combined)
    if m:
        yyyy, mm, dd = map(int, m.groups())
        try:
            return date(yyyy, mm, dd)
        except Exception:
            pass

    return None


def get_file_ext(url: str, text: str = "") -> str:
    parsed = urlparse(url)
    base = unquote(Path(parsed.path).name).lower()
    m = re.search(r"\.(xlsx|xls|csv|pdf)(?:$|\?)", base)
    if m:
        return "." + m.group(1)

    m = re.search(r"\.(xlsx|xls|csv|pdf)\b", text.lower())
    if m:
        return "." + m.group(1)

    return ""


def guess_carrier_from_url(url: str, text: str = "", context: str = "") -> str:
    """
    Guess source group from URL path / anchor text / local context.
    STB URLs often contain folders like:
      /rsir/All Class 1 Railroads/
      /rsir/BNSF/
      /rsir/NS/
    """
    combined = unquote(f"{url} {text} {context}").lower()

    patterns = [
        ("all_class_1_railroads", [
            "all class 1 railroads",
            "all class i railroads",
            "consolidated data",
            "/all class 1 railroads/",
            "/all%20class%201%20railroads/",
        ]),
        ("bnsf", ["bnsf", "/bn/", "bn methodology"]),
        ("cn", ["canadian national", "/cn/", " cn "]),
        ("cp", ["canadian pacific", "/cp/", " cp "]),
        ("cpkc", ["cpkc"]),
        ("csx", ["csx", "/csx/"]),
        ("ctco", ["ctco", "chicago transportation coordination office"]),
        ("kcs", ["kansas city southern", "/kcs/", "kcsx"]),
        ("ns", ["norfolk southern", "/ns/", " ns "]),
        ("up", ["union pacific", "/up/", "uprr"]),
        ("stb_1145_all", ["stb-1145", "1145"]),
    ]

    for carrier, pats in patterns:
        for p in pats:
            if p in combined:
                return carrier

    return "unknown"


def looks_like_valid_xlsx(path: Path) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False
    # XLSX is a ZIP container.
    return zipfile.is_zipfile(path)


def looks_like_valid_xls(path: Path) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False
    try:
        with path.open("rb") as f:
            header = f.read(8)
        # OLE CFB header for old .xls:
        return header == b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1"
    except Exception:
        return False


def looks_like_valid_pdf(path: Path) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False
    try:
        with path.open("rb") as f:
            return f.read(5) == b"%PDF-"
    except Exception:
        return False


def looks_like_valid_csv(path: Path) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False
    try:
        pd.read_csv(path, nrows=3)
        return True
    except Exception:
        # Some CSVs may have odd encodings; still accept if nonempty.
        return path.stat().st_size > 100


def looks_like_valid_file(path: Path, ext: str) -> bool:
    ext = ext.lower()
    if ext == ".xlsx":
        return looks_like_valid_xlsx(path) if VALIDATE_XLSX else path.exists() and path.stat().st_size > 0
    if ext == ".xls":
        return looks_like_valid_xls(path)
    if ext == ".pdf":
        return looks_like_valid_pdf(path)
    if ext == ".csv":
        return looks_like_valid_csv(path)
    return path.exists() and path.stat().st_size > 0


def download_file(url: str, out_path: Path, ext: str, label: str, overwrite: bool = False) -> Path:
    url = requote_uri(url)
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if RESUME and out_path.exists() and not overwrite and looks_like_valid_file(out_path, ext):
        print(f"[skip existing valid] {label}: {out_path.name} ({file_size_mb(out_path)} MB)")
        log_event({
            "status": "exists_valid",
            "url": url,
            "path": str(out_path),
            "size_mb": file_size_mb(out_path),
            "label": label,
        })
        return out_path

    part_path = out_path.with_suffix(out_path.suffix + ".part")
    if part_path.exists():
        part_path.unlink()

    print("\n" + "-" * 100)
    print("[download]", label)
    print("URL:", url)
    print("OUT:", out_path)
    print("-" * 100)

    with session.get(url, stream=True, timeout=300) as r:
        if r.status_code >= 400:
            raise RuntimeError(f"HTTP {r.status_code} while downloading {url}\n{r.text[:500]}")

        total = int(r.headers.get("content-length", 0))
        with part_path.open("wb") as f, tqdm(
            total=total,
            unit="B",
            unit_scale=True,
            desc=label[:60],
        ) as pbar:
            for chunk in r.iter_content(chunk_size=CHUNK_SIZE):
                if chunk:
                    f.write(chunk)
                    pbar.update(len(chunk))

    part_path.replace(out_path)

    if not looks_like_valid_file(out_path, ext):
        raise RuntimeError(f"Downloaded file does not look valid: {out_path}")

    log_event({
        "status": "downloaded",
        "url": url,
        "path": str(out_path),
        "size_mb": file_size_mb(out_path),
        "label": label,
    })

    return out_path


def collect_xlsx_sheet_names(path: Path) -> dict:
    if not HAS_OPENPYXL:
        return {"sheet_status": "openpyxl_not_available"}

    try:
        wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
        sheets = wb.sheetnames
        wb.close()
        return {
            "sheet_status": "ok",
            "n_sheets": len(sheets),
            "sheet_names": "|".join(sheets),
        }
    except Exception as e:
        return {
            "sheet_status": "failed",
            "sheet_error": repr(e),
        }


# ------------------------------------------------------------
# 3. Scrape STB page
# ------------------------------------------------------------

print("[scrape]", STB_PAGE_URL)
r = session.get(STB_PAGE_URL, timeout=180)
r.raise_for_status()
html = r.text
PAGE_HTML_PATH.write_text(html, encoding="utf-8")

soup = BeautifulSoup(html, "html.parser")

# Gather all candidate links.
candidate_rows = []

for idx, a in enumerate(soup.find_all("a", href=True), start=1):
    raw_href = a["href"]
    url = urljoin(STB_PAGE_URL, raw_href)
    text = " ".join(a.get_text(" ", strip=True).split())
    ext = get_file_ext(url, text)

    if ext not in {".xlsx", ".xls", ".pdf", ".csv"}:
        continue

    # Context from nearby HTML to help classify.
    parent_text = ""
    try:
        parent_text = " ".join(a.parent.get_text(" ", strip=True).split())[:500]
    except Exception:
        parent_text = ""

    report_date = parse_date_from_text_or_url(text, url)
    year = report_date.year if report_date is not None else None

    carrier_guess = guess_carrier_from_url(url, text=text, context=parent_text)

    # Determine dataset group.
    lower_combined = unquote(f"{url} {text} {parent_text}").lower()

    if report_date is not None and ext in {".xlsx", ".xls", ".pdf"}:
        dataset_group = "weekly_service_report"
    elif ext == ".csv" and ("1145" in lower_combined or "stb-1145" in lower_combined):
        dataset_group = "stb_1145_csv"
    elif "methodology" in lower_combined or "methodologies" in lower_combined:
        dataset_group = "methodology_doc"
    else:
        # Keep other file links in inventory, but do not download unless explicitly selected.
        dataset_group = "other_file_link"

    candidate_rows.append({
        "link_seq": idx,
        "dataset_group": dataset_group,
        "carrier_guess": carrier_guess,
        "report_date": report_date.isoformat() if report_date else None,
        "year": year,
        "ext": ext,
        "anchor_text": text,
        "url": url,
        "parent_text": parent_text,
    })

link_inventory = pd.DataFrame(candidate_rows)

if link_inventory.empty:
    raise RuntimeError("No STB rail service file links were found on the page.")

# Filter what to download.
to_download_parts = []

if DOWNLOAD_WEEKLY_XLSX:
    weekly_xlsx = link_inventory[
        (link_inventory["dataset_group"] == "weekly_service_report")
        & (link_inventory["ext"].isin([".xlsx", ".xls"]))
        & (link_inventory["year"].isin(TARGET_YEARS))
    ].copy()
    to_download_parts.append(weekly_xlsx)

if DOWNLOAD_WEEKLY_PDF:
    weekly_pdf = link_inventory[
        (link_inventory["dataset_group"] == "weekly_service_report")
        & (link_inventory["ext"] == ".pdf")
        & (link_inventory["year"].isin(TARGET_YEARS))
    ].copy()
    to_download_parts.append(weekly_pdf)

if DOWNLOAD_STB1145_CSV:
    csv_1145 = link_inventory[
        (link_inventory["dataset_group"] == "stb_1145_csv")
        & (link_inventory["ext"] == ".csv")
    ].copy()
    to_download_parts.append(csv_1145)

if DOWNLOAD_METHODOLOGY_DOCS:
    docs = link_inventory[
        (link_inventory["dataset_group"].isin(["methodology_doc"]))
    ].copy()
    to_download_parts.append(docs)

if len(to_download_parts) == 0:
    raise RuntimeError("No selected download categories are enabled.")

download_inventory = pd.concat(to_download_parts, ignore_index=True).drop_duplicates(
    subset=["dataset_group", "url"]
).reset_index(drop=True)

# Save full inventory and selected inventory.
link_inventory.to_csv(LINK_INVENTORY_PATH, index=False, encoding="utf-8-sig")
selected_path = METADATA_ROOT / "stb_rail_service_selected_download_links.csv"
download_inventory.to_csv(selected_path, index=False, encoding="utf-8-sig")

print("\nFull link inventory:", LINK_INVENTORY_PATH)
print("Selected download links:", selected_path)
print("\nAll candidate link counts:")
display(link_inventory.groupby(["dataset_group", "ext"], dropna=False).size().reset_index(name="n_links"))

print("\nSelected download counts:")
display(download_inventory.groupby(["dataset_group", "carrier_guess", "year", "ext"], dropna=False).size().reset_index(name="n_links").head(50))

print("\nSelected total files:", len(download_inventory))

# ------------------------------------------------------------
# 4. Build output paths
# ------------------------------------------------------------

def output_path_for_row(row: pd.Series) -> Path:
    url = row["url"]
    ext = row["ext"]
    dataset_group = row["dataset_group"]
    carrier = row.get("carrier_guess") or "unknown"
    year = row.get("year")
    report_date = row.get("report_date")

    base = clean_windows_filename(Path(urlparse(url).path).name)
    if not base:
        base = f"stb_file_{row['link_seq']}{ext}"

    h = short_hash(url, 10)

    if dataset_group == "weekly_service_report":
        year_str = str(int(year)) if pd.notna(year) else "unknown_year"
        date_str = str(report_date) if pd.notna(report_date) and report_date else "unknown_date"
        subdir = RAW_WEEKLY_ROOT / carrier / year_str / ext.replace(".", "")
        out_name = f"{date_str}_{h}_{base}"
        return subdir / out_name

    if dataset_group == "stb_1145_csv":
        subdir = STB1145_ROOT / carrier
        out_name = f"{h}_{base}"
        return subdir / out_name

    if dataset_group == "methodology_doc":
        subdir = DOCS_ROOT / carrier
        out_name = f"{h}_{base}"
        return subdir / out_name

    subdir = STB_RAIL_ROOT / "other_file_links"
    out_name = f"{h}_{base}"
    return subdir / out_name


download_inventory["out_path"] = download_inventory.apply(lambda r: str(output_path_for_row(r)), axis=1)

# ------------------------------------------------------------
# 5. Download selected files
# ------------------------------------------------------------

manifest_rows = []
sheet_preview_rows = []
xlsx_sheet_counter = 0

# Load previous manifest if exists, so final output includes past runs.
if RESUME and DOWNLOAD_MANIFEST_PATH.exists():
    try:
        old_manifest = pd.read_csv(DOWNLOAD_MANIFEST_PATH)
        manifest_rows = old_manifest.to_dict("records")
        print(f"Loaded existing manifest with {len(manifest_rows)} rows.")
    except Exception:
        manifest_rows = []

# Use URL+out_path to avoid duplicate manifest rows during reruns.
existing_keys = {
    (str(r.get("url")), str(r.get("out_path")))
    for r in manifest_rows
    if r.get("status") in {"downloaded", "exists_valid", "downloaded_or_exists"}
}

for i, row in tqdm(list(download_inventory.iterrows()), total=len(download_inventory), desc="Downloading STB rail service files"):
    row_dict = row.to_dict()
    url = row_dict["url"]
    ext = row_dict["ext"]
    out_path = Path(row_dict["out_path"])

    key = (str(url), str(out_path))
    if RESUME and key in existing_keys and looks_like_valid_file(out_path, ext):
        continue

    label = f"{row_dict['dataset_group']} | {row_dict.get('carrier_guess')} | {row_dict.get('report_date') or ''} | {out_path.name}"

    rec = dict(row_dict)
    rec["out_path"] = str(out_path)

    try:
        downloaded = download_file(url, out_path, ext=ext, label=label)
        rec["status"] = "downloaded_or_exists"
        rec["size_mb"] = file_size_mb(downloaded)

        if COMPUTE_SHA256:
            rec["sha256"] = sha256_file(downloaded)

        if ext == ".xlsx" and xlsx_sheet_counter < COLLECT_SHEET_NAMES_FOR_FIRST_N:
            sheet_info = collect_xlsx_sheet_names(downloaded)
            sheet_preview_rows.append({
                "out_path": str(downloaded),
                "carrier_guess": rec.get("carrier_guess"),
                "report_date": rec.get("report_date"),
                "year": rec.get("year"),
                **sheet_info,
            })
            xlsx_sheet_counter += 1

    except Exception as e:
        rec["status"] = "failed"
        rec["error"] = repr(e)
        rec["traceback"] = traceback.format_exc()[:4000]
        print(f"\n[FAILED] {label}")
        print(e)

    manifest_rows.append(rec)

    # Save progress after every file.
    pd.DataFrame(manifest_rows).to_csv(DOWNLOAD_MANIFEST_PATH, index=False, encoding="utf-8-sig")

    if sheet_preview_rows:
        pd.DataFrame(sheet_preview_rows).to_csv(SHEET_PREVIEW_PATH, index=False, encoding="utf-8-sig")

    time.sleep(SLEEP_BETWEEN_DOWNLOADS)

# ------------------------------------------------------------
# 6. Final manifest and summary
# ------------------------------------------------------------

manifest = pd.DataFrame(manifest_rows)

# Keep latest row for each URL/path pair.
if not manifest.empty:
    manifest = manifest.drop_duplicates(subset=["url", "out_path"], keep="last").reset_index(drop=True)

manifest.to_csv(DOWNLOAD_MANIFEST_PATH, index=False, encoding="utf-8-sig")

print("\n" + "=" * 100)
print("STB RAIL SERVICE PERFORMANCE DOWNLOAD COMPLETE")
print("=" * 100)
print("Root:", STB_RAIL_ROOT)
print("Full link inventory:", LINK_INVENTORY_PATH)
print("Selected links:", selected_path)
print("Download manifest:", DOWNLOAD_MANIFEST_PATH)
print("Download log:", DOWNLOAD_LOG_PATH)
print("Sheet preview:", SHEET_PREVIEW_PATH if SHEET_PREVIEW_PATH.exists() else "not created")
print("=" * 100)

summary_cols = [
    "dataset_group",
    "carrier_guess",
    "year",
    "ext",
    "status",
]
if not manifest.empty:
    summary = manifest.groupby(summary_cols, dropna=False).size().reset_index(name="n_files")
    display(summary)

    failed = manifest[manifest["status"] == "failed"].copy()
    if len(failed) > 0:
        print("\nFailed files:")
        display(failed[["dataset_group", "carrier_guess", "year", "ext", "url", "out_path", "error"]].head(50))
    else:
        print("\nNo failed files recorded.")

    print("\nDownloaded / existing file count:", len(manifest[manifest["status"].isin(["downloaded_or_exists", "exists_valid", "downloaded"])]))
    print("Total size GB:", round(manifest["size_mb"].fillna(0).sum() / 1024, 3))

====================================================================================================
STB Rail Service Performance downloader
DATA_ROOT: E:\NetworkOptimization\pythonProject1\Data
STB_RAIL_ROOT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance
TARGET_YEARS: [2020, 2021, 2022, 2023, 2024, 2025, 2026]
HAS_OPENPYXL: True
====================================================================================================
[scrape] https://www.stb.gov/reports-data/rail-service-data/

Full link inventory: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\_metadata\stb_rail_service_link_inventory.csv
Selected download links: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\_metadata\stb_rail_service_selected_download_links.csv

All candidate link counts:

           dataset_group    ext  n_links
0        methodology_doc   .pdf        8
1        other_file_link   .csv        1
2        other_file_link   .pdf        1
3           stb_1145_csv   .csv        7
4  weekly_service_report   .pdf     1535
5  weekly_service_report   .xls      439
6  weekly_service_report  .xlsx     4335

Selected download counts:

            dataset_group          carrier_guess    year    ext  n_links
0         methodology_doc                   bnsf     NaN   .pdf        1
1         methodology_doc                     cn     NaN   .pdf        1
2         methodology_doc                     cp     NaN   .pdf        1
3         methodology_doc                   cpkc     NaN   .pdf        1
4         methodology_doc                    csx     NaN   .pdf        1
5         methodology_doc                    kcs     NaN   .pdf        1
6         methodology_doc                     ns     NaN   .pdf        1
7         methodology_doc                     up     NaN   .pdf        1
8            stb_1145_csv                   bnsf     NaN   .csv        1
9            stb_1145_csv                   cpkc     NaN   .csv        1
10           stb_1145_csv                    csx     NaN   .csv        1
11           stb_1145_csv           stb_1145_all     NaN   .csv        4
12  weekly_service_report  all_class_1_railroads  2026.0  .xlsx        1
13  weekly_service_report                   bnsf  2020.0  .xlsx       53
14  weekly_service_report                   bnsf  2021.0  .xlsx       52
15  weekly_service_report                   bnsf  2022.0  .xlsx       52
16  weekly_service_report                   bnsf  2023.0  .xlsx       52
17  weekly_service_report                   bnsf  2024.0  .xlsx       52
18  weekly_service_report                   bnsf  2025.0  .xlsx       53
19  weekly_service_report                   bnsf  2026.0  .xlsx       19
20  weekly_service_report                     cn  2020.0  .xlsx       53
21  weekly_service_report                     cn  2021.0  .xlsx       52
22  weekly_service_report                     cn  2022.0  .xlsx       52
23  weekly_service_report                     cn  2023.0  .xlsx       52
24  weekly_service_report                     cn  2024.0  .xlsx       52
25  weekly_service_report                     cn  2025.0  .xlsx       53
26  weekly_service_report                     cn  2026.0  .xlsx       19
27  weekly_service_report                     cp  2020.0  .xlsx       53
28  weekly_service_report                     cp  2021.0  .xlsx       52
29  weekly_service_report                     cp  2022.0  .xlsx       52
30  weekly_service_report                     cp  2023.0  .xlsx       52
31  weekly_service_report                     cp  2024.0  .xlsx       52
32  weekly_service_report                     cp  2025.0  .xlsx       22
33  weekly_service_report                   cpkc  2025.0  .xlsx       34
34  weekly_service_report                   cpkc  2026.0  .xlsx       19
35  weekly_service_report                    csx  2020.0  .xlsx       53
36  weekly_service_report                    csx  2021.0  .xlsx       52
37  weekly_service_report                    csx  2022.0  .xlsx       52
38  weekly_service_report                    csx  2023.0  .xlsx       52
39  weekly_service_report                    csx  2024.0  .xlsx       52
40  weekly_service_report                    csx  2025.0  .xlsx       53
41  weekly_service_report                    csx  2026.0  .xlsx       19
42  weekly_service_report                   ctco  2020.0  .xlsx       53
43  weekly_service_report                   ctco  2021.0  .xlsx       52
44  weekly_service_report                   ctco  2022.0  .xlsx       52
45  weekly_service_report                   ctco  2023.0  .xlsx       52
46  weekly_service_report                   ctco  2024.0  .xlsx       52
47  weekly_service_report                   ctco  2025.0  .xlsx       53
48  weekly_service_report                   ctco  2026.0  .xlsx       19
49  weekly_service_report                    kcs  2020.0  .xlsx       53

Selected total files: 2625

Downloading STB rail service files:   0%|          | 0/2625 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | all_class_1_railroads | 2026-05-13 | 2026-05-13_f93c394325_EP724 Consolidated Data through 2026-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/All%20Class%201%20Railroads/EP724%20Consolidated%20Data%20through%202026-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\all_class_1_railroads\2026\xlsx\2026-05-13_f93c394325_EP724 Consolidated Data through 2026-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | all_class_1_railroads | 2026-05-13 |:   0%|          | 0.00/7.41M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-05-06 | 2026-05-06_16cfcfcde4_BNSF Data 2026-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-05-06_16cfcfcde4_BNSF Data 2026-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-05-06 | 2026-05-06_16cfc:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-05-13 | 2026-05-13_ca3a6ef451_BNSF Data 2026-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-05-13_ca3a6ef451_BNSF Data 2026-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-05-13 | 2026-05-13_ca3a6:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-04-01 | 2026-04-01_5d43048c28_BNSF Data 2026-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-04-01_5d43048c28_BNSF Data 2026-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-04-01 | 2026-04-01_5d430:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-04-08 | 2026-04-08_c98c8b3aff_BNSF Data 2026-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-04-08_c98c8b3aff_BNSF Data 2026-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-04-08 | 2026-04-08_c98c8:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-04-15 | 2026-04-15_9392f456f3_BNSF Data 2026-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-04-15_9392f456f3_BNSF Data 2026-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-04-15 | 2026-04-15_9392f:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-04-22 | 2026-04-22_cb5550139a_BNSF Data 2026-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-04-22_cb5550139a_BNSF Data 2026-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-04-22 | 2026-04-22_cb555:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-04-29 | 2026-04-29_1046b73cf0_BNSF Data 2026-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-04-29_1046b73cf0_BNSF Data 2026-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-04-29 | 2026-04-29_1046b:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-03-04 | 2026-03-04_e5523ba329_BNSF Data 2026-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-03-04_e5523ba329_BNSF Data 2026-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-03-04 | 2026-03-04_e5523:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-03-11 | 2026-03-11_9df4da457b_BNSF Data 2026-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-03-11_9df4da457b_BNSF Data 2026-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-03-11 | 2026-03-11_9df4d:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-03-18 | 2026-03-18_8c11c73db2_BNSF Data 2026-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-03-18_8c11c73db2_BNSF Data 2026-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-03-18 | 2026-03-18_8c11c:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-03-25 | 2026-03-25_df4c4b6115_BNSF Data 2026-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-03-25_df4c4b6115_BNSF Data 2026-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-03-25 | 2026-03-25_df4c4:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-02-04 | 2026-02-04_52c208c9ed_BNSF Data 2026-02-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-02-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-02-04_52c208c9ed_BNSF Data 2026-02-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-02-04 | 2026-02-04_52c20:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-02-11 | 2026-02-11_89bd0889c8_BNSF Data 2026-02-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-02-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-02-11_89bd0889c8_BNSF Data 2026-02-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-02-11 | 2026-02-11_89bd0:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-02-18 | 2026-02-18_080ce7a8f2_BNSF Data 2026-02-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-02-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-02-18_080ce7a8f2_BNSF Data 2026-02-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-02-18 | 2026-02-18_080ce:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-02-25 | 2026-02-25_bfb43040b0_BNSF Data 2026-02-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-02-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-02-25_bfb43040b0_BNSF Data 2026-02-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-02-25 | 2026-02-25_bfb43:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-01-07 | 2026-01-07_0eb8541d47_BNSF Data 2026-01-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-01-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-01-07_0eb8541d47_BNSF Data 2026-01-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-01-07 | 2026-01-07_0eb85:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-01-14 | 2026-01-14_860aaf576e_BNSF Data 2026-01-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-01-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-01-14_860aaf576e_BNSF Data 2026-01-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-01-14 | 2026-01-14_860aa:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-01-21 | 2026-01-21_4151316d98_BNSF Data 2026-01-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-01-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-01-21_4151316d98_BNSF Data 2026-01-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-01-21 | 2026-01-21_41513:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2026-01-28 | 2026-01-28_4838b283b7_BNSF Data 2026-01-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202026-01-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2026\xlsx\2026-01-28_4838b283b7_BNSF Data 2026-01-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2026-01-28 | 2026-01-28_4838b:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-12-31 | 2025-12-31_b4f98ec027_BNSF Data 2025-12-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-12-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-12-31_b4f98ec027_BNSF Data 2025-12-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-12-31 | 2025-12-31_b4f98:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-12-03 | 2025-12-03_1da125a790_BNSF Data 2025-12-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-12-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-12-03_1da125a790_BNSF Data 2025-12-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-12-03 | 2025-12-03_1da12:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-12-10 | 2025-12-10_be9db3ecad_BNSF Data 2025-12-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-12-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-12-10_be9db3ecad_BNSF Data 2025-12-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-12-10 | 2025-12-10_be9db:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-12-17 | 2025-12-17_e3c402cad7_BNSF Data 2025-12-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-12-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-12-17_e3c402cad7_BNSF Data 2025-12-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-12-17 | 2025-12-17_e3c40:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-12-24 | 2025-12-24_5e187aaa53_BNSF Data 2025-12-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-12-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-12-24_5e187aaa53_BNSF Data 2025-12-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-12-24 | 2025-12-24_5e187:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-11-05 | 2025-11-05_1f5a7c3c09_BNSF Data 2025-11-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-11-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-11-05_1f5a7c3c09_BNSF Data 2025-11-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-11-05 | 2025-11-05_1f5a7:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-11-12 | 2025-11-12_1696696832_BNSF Data 2025-11-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-11-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-11-12_1696696832_BNSF Data 2025-11-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-11-12 | 2025-11-12_16966:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-11-19 | 2025-11-19_23bcdaa86e_BNSF Data 2025-11-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-11-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-11-19_23bcdaa86e_BNSF Data 2025-11-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-11-19 | 2025-11-19_23bcd:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-11-26 | 2025-11-26_1e339c55bb_BNSF Data 2025-11-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-11-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-11-26_1e339c55bb_BNSF Data 2025-11-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-11-26 | 2025-11-26_1e339:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-10-01 | 2025-10-01_fb9dfc9d92_BNSF Data 2025-10-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-10-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-10-01_fb9dfc9d92_BNSF Data 2025-10-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-10-01 | 2025-10-01_fb9df:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-10-08 | 2025-10-08_1b0eb1f5ce_BNSF Data 2025-10-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-10-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-10-08_1b0eb1f5ce_BNSF Data 2025-10-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-10-08 | 2025-10-08_1b0eb:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-10-15 | 2025-10-15_0821728aa6_BNSF Data 2025-10-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-10-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-10-15_0821728aa6_BNSF Data 2025-10-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-10-15 | 2025-10-15_08217:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-10-22 | 2025-10-22_0ac59ce2d2_BNSF Data 2025-10-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-10-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-10-22_0ac59ce2d2_BNSF Data 2025-10-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-10-22 | 2025-10-22_0ac59:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-10-29 | 2025-10-29_f11d0279d6_BNSF Data 2025-10-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-10-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-10-29_f11d0279d6_BNSF Data 2025-10-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-10-29 | 2025-10-29_f11d0:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-09-03 | 2025-09-03_3deeaa6cb7_BNSF Data 2025-09-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-09-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-09-03_3deeaa6cb7_BNSF Data 2025-09-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-09-03 | 2025-09-03_3deea:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-09-10 | 2025-09-10_35ad8bf217_BNSF Data 2025-09-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-09-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-09-10_35ad8bf217_BNSF Data 2025-09-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-09-10 | 2025-09-10_35ad8:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-09-17 | 2025-09-17_65ce0fe9d4_BNSF Data 2025-09-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-09-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-09-17_65ce0fe9d4_BNSF Data 2025-09-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-09-17 | 2025-09-17_65ce0:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-09-24 | 2025-09-24_ef1e839b11_BNSF Data 2025-09-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-09-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-09-24_ef1e839b11_BNSF Data 2025-09-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-09-24 | 2025-09-24_ef1e8:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-08-06 | 2025-08-06_5de2e44f54_BNSF Data 2025-08-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-08-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-08-06_5de2e44f54_BNSF Data 2025-08-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-08-06 | 2025-08-06_5de2e:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-08-13 | 2025-08-13_90d8c413e1_BNSF Data 2025-08-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-08-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-08-13_90d8c413e1_BNSF Data 2025-08-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-08-13 | 2025-08-13_90d8c:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-08-20 | 2025-08-20_f82bd52eb6_BNSF Data 2025-08-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-08-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-08-20_f82bd52eb6_BNSF Data 2025-08-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-08-20 | 2025-08-20_f82bd:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-08-27 | 2025-08-27_e72c1000a9_BNSF Data 2025-08-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-08-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-08-27_e72c1000a9_BNSF Data 2025-08-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-08-27 | 2025-08-27_e72c1:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-07-02 | 2025-07-02_9c8dbceef8_BNSF Data 2025-07-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-07-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-07-02_9c8dbceef8_BNSF Data 2025-07-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-07-02 | 2025-07-02_9c8db:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-07-09 | 2025-07-09_995850d2af_BNSF Data 2025-07-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-07-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-07-09_995850d2af_BNSF Data 2025-07-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-07-09 | 2025-07-09_99585:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-07-16 | 2025-07-16_6563b8e96d_BNSF Data 2025-07-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-07-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-07-16_6563b8e96d_BNSF Data 2025-07-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-07-16 | 2025-07-16_6563b:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-07-23 | 2025-07-23_3e54f05d74_BNSF Data 2025-07-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-07-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-07-23_3e54f05d74_BNSF Data 2025-07-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-07-23 | 2025-07-23_3e54f:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-07-30 | 2025-07-30_5971101f29_BNSF Data 2025-07-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-07-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-07-30_5971101f29_BNSF Data 2025-07-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-07-30 | 2025-07-30_59711:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-06-04 | 2025-06-04_e147d30998_BNSF Data 2025-06-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-06-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-06-04_e147d30998_BNSF Data 2025-06-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-06-04 | 2025-06-04_e147d:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-06-11 | 2025-06-11_a3f1e43993_BNSF Data 2025-06-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-06-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-06-11_a3f1e43993_BNSF Data 2025-06-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-06-11 | 2025-06-11_a3f1e:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-06-18 | 2025-06-18_f49b106c61_BNSF Data 2025-06-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-06-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-06-18_f49b106c61_BNSF Data 2025-06-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-06-18 | 2025-06-18_f49b1:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-06-25 | 2025-06-25_8ea8584ba8_BNSF Data 2025-06-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-06-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-06-25_8ea8584ba8_BNSF Data 2025-06-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-06-25 | 2025-06-25_8ea85:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-05-07 | 2025-05-07_024cd1df73_BNSF Data 2025-05-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-05-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-05-07_024cd1df73_BNSF Data 2025-05-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-05-07 | 2025-05-07_024cd:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-05-14 | 2025-05-14_a72a20fec4_BNSF Data 2025-05-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-05-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-05-14_a72a20fec4_BNSF Data 2025-05-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-05-14 | 2025-05-14_a72a2:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-05-21 | 2025-05-21_8a0606e605_BNSF Data 2025-05-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-05-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-05-21_8a0606e605_BNSF Data 2025-05-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-05-21 | 2025-05-21_8a060:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-05-28 | 2025-05-28_d819cbb728_BNSF Data 2025-05-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-05-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-05-28_d819cbb728_BNSF Data 2025-05-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-05-28 | 2025-05-28_d819c:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-04-02 | 2025-04-02_2a1217d4f2_BNSF Data 2025-04-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-04-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-04-02_2a1217d4f2_BNSF Data 2025-04-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-04-02 | 2025-04-02_2a121:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-04-09 | 2025-04-09_f8c8329aae_BNSF Data 2025-04-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-04-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-04-09_f8c8329aae_BNSF Data 2025-04-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-04-09 | 2025-04-09_f8c83:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-04-16 | 2025-04-16_597c7882cc_BNSF Data 2025-04-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-04-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-04-16_597c7882cc_BNSF Data 2025-04-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-04-16 | 2025-04-16_597c7:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-04-23 | 2025-04-23_b3353288cd_BNSF Data 2025-04-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-04-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-04-23_b3353288cd_BNSF Data 2025-04-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-04-23 | 2025-04-23_b3353:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-04-30 | 2025-04-30_8350e5c1c1_BNSF Data 2025-04-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-04-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-04-30_8350e5c1c1_BNSF Data 2025-04-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-04-30 | 2025-04-30_8350e:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-03-05 | 2025-03-05_6d0d3b5890_BNSF Data 2025-03-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-03-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-03-05_6d0d3b5890_BNSF Data 2025-03-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-03-05 | 2025-03-05_6d0d3:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-03-12 | 2025-03-12_079a461bef_BNSF Data 2025-03-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-03-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-03-12_079a461bef_BNSF Data 2025-03-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-03-12 | 2025-03-12_079a4:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-03-19 | 2025-03-19_c17ef02a54_BNSF Data 2025-03-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-03-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-03-19_c17ef02a54_BNSF Data 2025-03-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-03-19 | 2025-03-19_c17ef:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-03-26 | 2025-03-26_85e414e9a1_BNSF Data 2025-03-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-03-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-03-26_85e414e9a1_BNSF Data 2025-03-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-03-26 | 2025-03-26_85e41:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-02-05 | 2025-02-05_4776f38d3f_BNSF Data 2025-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-02-05_4776f38d3f_BNSF Data 2025-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-02-05 | 2025-02-05_4776f:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-02-12 | 2025-02-12_376edea429_BNSF Data 2025-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-02-12_376edea429_BNSF Data 2025-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-02-12 | 2025-02-12_376ed:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-02-19 | 2025-02-19_3f001fb9c4_BNSF Data 2025-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-02-19_3f001fb9c4_BNSF Data 2025-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-02-19 | 2025-02-19_3f001:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-02-26 | 2025-02-26_f4aeccb3e9_BNSF Data 2025-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-02-26_f4aeccb3e9_BNSF Data 2025-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-02-26 | 2025-02-26_f4aec:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-01-01 | 2025-01-01_8d0c13be10_BNSF Data 2025-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-01-01_8d0c13be10_BNSF Data 2025-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-01-01 | 2025-01-01_8d0c1:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-01-08 | 2025-01-08_8489095c6c_BNSF Data 2025-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-01-08_8489095c6c_BNSF Data 2025-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-01-08 | 2025-01-08_84890:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-01-15 | 2025-01-15_503744ef92_BNSF Data 2025-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-01-15_503744ef92_BNSF Data 2025-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-01-15 | 2025-01-15_50374:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-01-22 | 2025-01-22_acd43601d3_BNSF Data 2025-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-01-22_acd43601d3_BNSF Data 2025-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-01-22 | 2025-01-22_acd43:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2025-01-29 | 2025-01-29_2383667ab6_BNSF Data 2025-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202025-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2025\xlsx\2025-01-29_2383667ab6_BNSF Data 2025-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2025-01-29 | 2025-01-29_23836:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-12-04 | 2024-12-04_4b89d744c3_BNSF Data 2024-12-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-12-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-12-04_4b89d744c3_BNSF Data 2024-12-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-12-04 | 2024-12-04_4b89d:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-12-11 | 2024-12-11_afd928c56a_BNSF Data 2024-12-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-12-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-12-11_afd928c56a_BNSF Data 2024-12-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-12-11 | 2024-12-11_afd92:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-12-18 | 2024-12-18_673fc36349_BNSF Data 2024-12-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-12-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-12-18_673fc36349_BNSF Data 2024-12-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-12-18 | 2024-12-18_673fc:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-12-25 | 2024-12-25_60c50fd456_BNSF Data 2024-12-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-12-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-12-25_60c50fd456_BNSF Data 2024-12-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-12-25 | 2024-12-25_60c50:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-11-06 | 2024-11-06_d8bb8a9ed2_BNSF Data 2024-11-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-11-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-11-06_d8bb8a9ed2_BNSF Data 2024-11-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-11-06 | 2024-11-06_d8bb8:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-11-13 | 2024-11-13_e5857a7b32_BNSF Data 2024-11-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-11-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-11-13_e5857a7b32_BNSF Data 2024-11-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-11-13 | 2024-11-13_e5857:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-11-20 | 2024-11-20_afce29566e_BNSF Data 2024-11-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-11-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-11-20_afce29566e_BNSF Data 2024-11-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-11-20 | 2024-11-20_afce2:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-11-27 | 2024-11-27_6c5d52c019_BNSF Data 2024-11-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-11-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-11-27_6c5d52c019_BNSF Data 2024-11-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-11-27 | 2024-11-27_6c5d5:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-10-02 | 2024-10-02_f66dfb346e_BNSF Data 2024-10-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-10-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-10-02_f66dfb346e_BNSF Data 2024-10-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-10-02 | 2024-10-02_f66df:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-10-09 | 2024-10-09_76a526e33d_BNSF Data 2024-10-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-10-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-10-09_76a526e33d_BNSF Data 2024-10-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-10-09 | 2024-10-09_76a52:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-10-16 | 2024-10-16_5594511615_BNSF Data 2024-10-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-10-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-10-16_5594511615_BNSF Data 2024-10-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-10-16 | 2024-10-16_55945:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-10-23 | 2024-10-23_08b1452d55_BNSF Data 2024-10-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-10-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-10-23_08b1452d55_BNSF Data 2024-10-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-10-23 | 2024-10-23_08b14:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-10-30 | 2024-10-30_7a21e211fb_BNSF Data 2024-10-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-10-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-10-30_7a21e211fb_BNSF Data 2024-10-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-10-30 | 2024-10-30_7a21e:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-09-04 | 2024-09-04_8cd7358d20_BNSF Data 2024-09-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-09-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-09-04_8cd7358d20_BNSF Data 2024-09-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-09-04 | 2024-09-04_8cd73:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-09-11 | 2024-09-11_2118369198_BNSF Data 2024-09-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-09-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-09-11_2118369198_BNSF Data 2024-09-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-09-11 | 2024-09-11_21183:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-09-18 | 2024-09-18_94a73e2425_BNSF Data 2024-09-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-09-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-09-18_94a73e2425_BNSF Data 2024-09-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-09-18 | 2024-09-18_94a73:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-09-25 | 2024-09-25_083d0bac0f_BNSF Data 2024-09-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-09-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-09-25_083d0bac0f_BNSF Data 2024-09-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-09-25 | 2024-09-25_083d0:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-08-07 | 2024-08-07_b9cdaabe01_BNSF Data 2024-08-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-08-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-08-07_b9cdaabe01_BNSF Data 2024-08-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-08-07 | 2024-08-07_b9cda:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-08-14 | 2024-08-14_7485c8be81_BNSF Data 2024-08-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-08-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-08-14_7485c8be81_BNSF Data 2024-08-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-08-14 | 2024-08-14_7485c:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-08-21 | 2024-08-21_ab227f99a0_BNSF Data 2024-08-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-08-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-08-21_ab227f99a0_BNSF Data 2024-08-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-08-21 | 2024-08-21_ab227:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-08-28 | 2024-08-28_26ad33d6a3_BNSF Data 2024-08-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-08-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-08-28_26ad33d6a3_BNSF Data 2024-08-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-08-28 | 2024-08-28_26ad3:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-07-03 | 2024-07-03_f69c79e747_BNSF Data 2024-07-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-07-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-07-03_f69c79e747_BNSF Data 2024-07-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-07-03 | 2024-07-03_f69c7:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-07-10 | 2024-07-10_d616acc597_BNSF Data 2024-07-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-07-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-07-10_d616acc597_BNSF Data 2024-07-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-07-10 | 2024-07-10_d616a:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-07-17 | 2024-07-17_1fdc6ac9a7_BNSF Data 2024-07-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-07-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-07-17_1fdc6ac9a7_BNSF Data 2024-07-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-07-17 | 2024-07-17_1fdc6:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-07-24 | 2024-07-24_6b21317406_BNSF Data 2024-07-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-07-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-07-24_6b21317406_BNSF Data 2024-07-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-07-24 | 2024-07-24_6b213:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-07-31 | 2024-07-31_14017541ae_BNSF Data 2024-07-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-07-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-07-31_14017541ae_BNSF Data 2024-07-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-07-31 | 2024-07-31_14017:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-06-05 | 2024-06-05_392eb6c625_BNSF Data 2024-06-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-06-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-06-05_392eb6c625_BNSF Data 2024-06-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-06-05 | 2024-06-05_392eb:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-06-12 | 2024-06-12_1242ab7d1f_BNSF Data 2024-06-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-06-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-06-12_1242ab7d1f_BNSF Data 2024-06-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-06-12 | 2024-06-12_1242a:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-06-19 | 2024-06-19_c44534354a_BNSF Data 2024-06-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-06-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-06-19_c44534354a_BNSF Data 2024-06-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-06-19 | 2024-06-19_c4453:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-06-26 | 2024-06-26_7d7ba0c464_BNSF Data 2024-06-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-06-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-06-26_7d7ba0c464_BNSF Data 2024-06-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-06-26 | 2024-06-26_7d7ba:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-05-01 | 2024-05-01_95a15e794e_BNSF Data 2024-05-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-05-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-05-01_95a15e794e_BNSF Data 2024-05-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-05-01 | 2024-05-01_95a15:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-05-08 | 2024-05-08_578516e887_BNSF Data 2024-05-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-05-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-05-08_578516e887_BNSF Data 2024-05-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-05-08 | 2024-05-08_57851:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-05-15 | 2024-05-15_f4be542d3e_BNSF Data 2024-05-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-05-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-05-15_f4be542d3e_BNSF Data 2024-05-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-05-15 | 2024-05-15_f4be5:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-05-22 | 2024-05-22_9b7acd5967_BNSF Data 2024-05-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-05-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-05-22_9b7acd5967_BNSF Data 2024-05-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-05-22 | 2024-05-22_9b7ac:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-05-29 | 2024-05-29_ec7606779f_BNSF Data 2024-05-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-05-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-05-29_ec7606779f_BNSF Data 2024-05-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-05-29 | 2024-05-29_ec760:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-04-03 | 2024-04-03_240d0e42f0_BNSF Data 2024-04-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-04-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-04-03_240d0e42f0_BNSF Data 2024-04-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-04-03 | 2024-04-03_240d0:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-04-10 | 2024-04-10_4bfc7ada39_BNSF Data 2024-04-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-04-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-04-10_4bfc7ada39_BNSF Data 2024-04-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-04-10 | 2024-04-10_4bfc7:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-04-17 | 2024-04-17_11e64fceed_BNSF Data 2024-04-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-04-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-04-17_11e64fceed_BNSF Data 2024-04-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-04-17 | 2024-04-17_11e64:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-04-24 | 2024-04-24_7fb700c7af_BNSF Data 2024-04-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-04-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-04-24_7fb700c7af_BNSF Data 2024-04-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-04-24 | 2024-04-24_7fb70:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-03-06 | 2024-03-06_d8c1fdf7bb_BNSF Data 2024-03-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-03-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-03-06_d8c1fdf7bb_BNSF Data 2024-03-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-03-06 | 2024-03-06_d8c1f:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-03-13 | 2024-03-13_90f3b7daf7_BNSF Data 2024-03-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-03-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-03-13_90f3b7daf7_BNSF Data 2024-03-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-03-13 | 2024-03-13_90f3b:   0%|          | 0.00/37.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-03-20 | 2024-03-20_ecfc99f007_BNSF Data 2024-03-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-03-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-03-20_ecfc99f007_BNSF Data 2024-03-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-03-20 | 2024-03-20_ecfc9:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-03-27 | 2024-03-27_b8a3e10d6e_BNSF Data 2024-03-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-03-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-03-27_b8a3e10d6e_BNSF Data 2024-03-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-03-27 | 2024-03-27_b8a3e:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-02-07 | 2024-02-07_f6dfe2abc1_BNSF Data 2024-02-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-02-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-02-07_f6dfe2abc1_BNSF Data 2024-02-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-02-07 | 2024-02-07_f6dfe:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-02-14 | 2024-02-14_5696e37c91_BNSF Data 2024-02-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-02-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-02-14_5696e37c91_BNSF Data 2024-02-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-02-14 | 2024-02-14_5696e:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-02-21 | 2024-02-21_2da347b0ff_BNSF Data 2024-02-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-02-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-02-21_2da347b0ff_BNSF Data 2024-02-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-02-21 | 2024-02-21_2da34:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-02-28 | 2024-02-28_eb283b2a90_BNSF Data 2024-02-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-02-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-02-28_eb283b2a90_BNSF Data 2024-02-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-02-28 | 2024-02-28_eb283:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-01-03 | 2024-01-03_c57421d2de_BNSF Data 2024-01-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-01-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-01-03_c57421d2de_BNSF Data 2024-01-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-01-03 | 2024-01-03_c5742:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-01-10 | 2024-01-10_0176992a8c_BNSF Data 2024-01-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-01-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-01-10_0176992a8c_BNSF Data 2024-01-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-01-10 | 2024-01-10_01769:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-01-17 | 2024-01-17_80751c67e4_BNSF Data 2024-01-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-01-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-01-17_80751c67e4_BNSF Data 2024-01-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-01-17 | 2024-01-17_80751:   0%|          | 0.00/43.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-01-24 | 2024-01-24_fd75dfc54a_BNSF Data 2024-01-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-01-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-01-24_fd75dfc54a_BNSF Data 2024-01-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-01-24 | 2024-01-24_fd75d:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2024-01-31 | 2024-01-31_b0936df880_BNSF Data 2024-01-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202024-01-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2024\xlsx\2024-01-31_b0936df880_BNSF Data 2024-01-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2024-01-31 | 2024-01-31_b0936:   0%|          | 0.00/37.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-12-06 | 2023-12-06_c6479a3f6c_BNSF Data 2023-12-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-12-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-12-06_c6479a3f6c_BNSF Data 2023-12-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-12-06 | 2023-12-06_c6479:   0%|          | 0.00/37.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-12-13 | 2023-12-13_a29695759b_BNSF Data 2023-12-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-12-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-12-13_a29695759b_BNSF Data 2023-12-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-12-13 | 2023-12-13_a2969:   0%|          | 0.00/37.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-12-20 | 2023-12-20_2259dbd819_BNSF Data 2023-12-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-12-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-12-20_2259dbd819_BNSF Data 2023-12-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-12-20 | 2023-12-20_2259d:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-12-27 | 2023-12-27_4da23fde6b_BNSF Data 2023-12-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-12-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-12-27_4da23fde6b_BNSF Data 2023-12-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-12-27 | 2023-12-27_4da23:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-11-01 | 2023-11-01_a8998a4e87_BNSF Data 2023-11-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-11-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-11-01_a8998a4e87_BNSF Data 2023-11-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-11-01 | 2023-11-01_a8998:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-11-08 | 2023-11-08_0e27f9f116_BNSF Data 2023-11-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-11-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-11-08_0e27f9f116_BNSF Data 2023-11-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-11-08 | 2023-11-08_0e27f:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-11-15 | 2023-11-15_defafe46b9_BNSF Data 2023-11-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-11-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-11-15_defafe46b9_BNSF Data 2023-11-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-11-15 | 2023-11-15_defaf:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-11-22 | 2023-11-22_91775c2638_BNSF Data 2023-11-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-11-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-11-22_91775c2638_BNSF Data 2023-11-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-11-22 | 2023-11-22_91775:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-11-29 | 2023-11-29_f3f9d38fba_BNSF Data 2023-11-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-11-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-11-29_f3f9d38fba_BNSF Data 2023-11-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-11-29 | 2023-11-29_f3f9d:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-10-04 | 2023-10-04_33f42c63c3_BNSF Data 2023-10-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-10-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-10-04_33f42c63c3_BNSF Data 2023-10-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-10-04 | 2023-10-04_33f42:   0%|          | 0.00/37.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-10-11 | 2023-10-11_c25041d453_BNSF Data 2023-10-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-10-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-10-11_c25041d453_BNSF Data 2023-10-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-10-11 | 2023-10-11_c2504:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-10-18 | 2023-10-18_78c52a908f_BNSF Data 2023-10-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-10-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-10-18_78c52a908f_BNSF Data 2023-10-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-10-18 | 2023-10-18_78c52:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-10-25 | 2023-10-25_be4777fc25_BNSF Data 2023-10-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-10-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-10-25_be4777fc25_BNSF Data 2023-10-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-10-25 | 2023-10-25_be477:   0%|          | 0.00/37.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-09-06 | 2023-09-06_9940def2ab_BNSF Data 2023-09-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-09-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-09-06_9940def2ab_BNSF Data 2023-09-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-09-06 | 2023-09-06_9940d:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-09-13 | 2023-09-13_268f6551a4_BNSF Data 2023-09-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-09-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-09-13_268f6551a4_BNSF Data 2023-09-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-09-13 | 2023-09-13_268f6:   0%|          | 0.00/37.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-09-20 | 2023-09-20_07d3ced8e9_BNSF Data 2023-09-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-09-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-09-20_07d3ced8e9_BNSF Data 2023-09-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-09-20 | 2023-09-20_07d3c:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-09-27 | 2023-09-27_6413856508_BNSF Data 2023-09-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-09-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-09-27_6413856508_BNSF Data 2023-09-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-09-27 | 2023-09-27_64138:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-08-02 | 2023-08-02_9d1a329950_BNSF Data 2023-08-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-08-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-08-02_9d1a329950_BNSF Data 2023-08-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-08-02 | 2023-08-02_9d1a3:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-08-09 | 2023-08-09_2265cfe83d_BNSF Data 2023-08-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-08-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-08-09_2265cfe83d_BNSF Data 2023-08-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-08-09 | 2023-08-09_2265c:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-08-16 | 2023-08-16_b2f60243c9_BNSF Data 2023-08-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-08-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-08-16_b2f60243c9_BNSF Data 2023-08-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-08-16 | 2023-08-16_b2f60:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-08-23 | 2023-08-23_827d674976_BNSF Data 2023-08-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-08-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-08-23_827d674976_BNSF Data 2023-08-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-08-23 | 2023-08-23_827d6:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-08-30 | 2023-08-30_08e19f7375_BNSF Data 2023-08-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-08-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-08-30_08e19f7375_BNSF Data 2023-08-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-08-30 | 2023-08-30_08e19:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-07-05 | 2023-07-05_f55d941688_BNSF Data 2023-07-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-07-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-07-05_f55d941688_BNSF Data 2023-07-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-07-05 | 2023-07-05_f55d9:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-07-12 | 2023-07-12_e3fa691c13_BNSF Data 2023-07-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-07-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-07-12_e3fa691c13_BNSF Data 2023-07-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-07-12 | 2023-07-12_e3fa6:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-07-19 | 2023-07-19_1db897a5bb_BNSF Data 2023-07-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-07-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-07-19_1db897a5bb_BNSF Data 2023-07-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-07-19 | 2023-07-19_1db89:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-07-26 | 2023-07-26_19b75670c0_BNSF Data 2023-07-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-07-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-07-26_19b75670c0_BNSF Data 2023-07-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-07-26 | 2023-07-26_19b75:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-06-07 | 2023-06-07_44a5a70225_BNSF Data 2023-06-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-06-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-06-07_44a5a70225_BNSF Data 2023-06-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-06-07 | 2023-06-07_44a5a:   0%|          | 0.00/37.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-06-14 | 2023-06-14_837bf5656e_BNSF Data 2023-06-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-06-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-06-14_837bf5656e_BNSF Data 2023-06-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-06-14 | 2023-06-14_837bf:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-06-21 | 2023-06-21_ea2c2336ee_BNSF Data 2023-06-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-06-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-06-21_ea2c2336ee_BNSF Data 2023-06-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-06-21 | 2023-06-21_ea2c2:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-06-28 | 2023-06-28_2041ba3230_BNSF Data 2023-06-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-06-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-06-28_2041ba3230_BNSF Data 2023-06-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-06-28 | 2023-06-28_2041b:   0%|          | 0.00/41.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-05-03 | 2023-05-03_bc22807131_BNSF Data 2023-05-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-05-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-05-03_bc22807131_BNSF Data 2023-05-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-05-03 | 2023-05-03_bc228:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-05-10 | 2023-05-10_e7901f4f2c_BNSF Data 2023-05-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-05-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-05-10_e7901f4f2c_BNSF Data 2023-05-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-05-10 | 2023-05-10_e7901:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-05-17 | 2023-05-17_bcef6022c5_BNSF Data 2023-05-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-05-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-05-17_bcef6022c5_BNSF Data 2023-05-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-05-17 | 2023-05-17_bcef6:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-05-24 | 2023-05-24_07a777a4e2_BNSF Data 2023-05-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-05-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-05-24_07a777a4e2_BNSF Data 2023-05-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-05-24 | 2023-05-24_07a77:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-05-31 | 2023-05-31_863564ed6a_BNSF Data 2023-05-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-05-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-05-31_863564ed6a_BNSF Data 2023-05-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-05-31 | 2023-05-31_86356:   0%|          | 0.00/37.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-04-05 | 2023-04-05_1be878ffd7_BNSF Data 2023-04-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-04-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-04-05_1be878ffd7_BNSF Data 2023-04-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-04-05 | 2023-04-05_1be87:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-04-12 | 2023-04-12_a73ba09d3a_BNSF Data 2023-04-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-04-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-04-12_a73ba09d3a_BNSF Data 2023-04-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-04-12 | 2023-04-12_a73ba:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-04-19 | 2023-04-19_93655e2a8b_BNSF Data 2023-04-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-04-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-04-19_93655e2a8b_BNSF Data 2023-04-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-04-19 | 2023-04-19_93655:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-04-26 | 2023-04-26_5adaad4998_BNSF Data 2023-04-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-04-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-04-26_5adaad4998_BNSF Data 2023-04-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-04-26 | 2023-04-26_5adaa:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-03-01 | 2023-03-01_22d7dc0058_BNSF Data 2023-03-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-03-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-03-01_22d7dc0058_BNSF Data 2023-03-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-03-01 | 2023-03-01_22d7d:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-03-08 | 2023-03-08_777118490d_BNSF Data 2023-03-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-03-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-03-08_777118490d_BNSF Data 2023-03-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-03-08 | 2023-03-08_77711:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-03-15 | 2023-03-15_ee3ac6d81a_BNSF Data 2023-03-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-03-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-03-15_ee3ac6d81a_BNSF Data 2023-03-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-03-15 | 2023-03-15_ee3ac:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-03-22 | 2023-03-22_7e97b1e4c5_BNSF Data 2023-03-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-03-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-03-22_7e97b1e4c5_BNSF Data 2023-03-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-03-22 | 2023-03-22_7e97b:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-03-29 | 2023-03-29_7f58ecacf2_BNSF Data 2023-03-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-03-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-03-29_7f58ecacf2_BNSF Data 2023-03-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-03-29 | 2023-03-29_7f58e:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-02-01 | 2023-02-01_ce0f0e90e1_BNSF Data 2023-02-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-02-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-02-01_ce0f0e90e1_BNSF Data 2023-02-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-02-01 | 2023-02-01_ce0f0:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-02-08 | 2023-02-08_f6b21df945_BNSF Data 2023-02-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-02-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-02-08_f6b21df945_BNSF Data 2023-02-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-02-08 | 2023-02-08_f6b21:   0%|          | 0.00/37.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-02-15 | 2023-02-15_78a7bb4f1c_BNSF Data 2023-02-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-02-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-02-15_78a7bb4f1c_BNSF Data 2023-02-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-02-15 | 2023-02-15_78a7b:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-02-22 | 2023-02-22_0b6f6de96b_BNSF Data 2023-02-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-02-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-02-22_0b6f6de96b_BNSF Data 2023-02-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-02-22 | 2023-02-22_0b6f6:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-01-04 | 2023-01-04_8b0309d100_BNSF Data 2023-01-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-01-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-01-04_8b0309d100_BNSF Data 2023-01-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-01-04 | 2023-01-04_8b030:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-01-11 | 2023-01-11_54a4baee13_BNSF Data 2023-01-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-01-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-01-11_54a4baee13_BNSF Data 2023-01-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-01-11 | 2023-01-11_54a4b:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-01-18 | 2023-01-18_e8947e27b6_BNSF Data 2023-01-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-01-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-01-18_e8947e27b6_BNSF Data 2023-01-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-01-18 | 2023-01-18_e8947:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2023-01-25 | 2023-01-25_f091f3f4a4_BNSF Data 2023-01-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202023-01-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2023\xlsx\2023-01-25_f091f3f4a4_BNSF Data 2023-01-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2023-01-25 | 2023-01-25_f091f:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-12-07 | 2022-12-07_4a1d9a00a3_BNSF Data 2022-12-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-12-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-12-07_4a1d9a00a3_BNSF Data 2022-12-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-12-07 | 2022-12-07_4a1d9:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-12-14 | 2022-12-14_4dc9e53f28_BNSF Data 2022-12-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-12-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-12-14_4dc9e53f28_BNSF Data 2022-12-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-12-14 | 2022-12-14_4dc9e:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-12-21 | 2022-12-21_efad107a3f_BNSF Data 2022-12-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-12-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-12-21_efad107a3f_BNSF Data 2022-12-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-12-21 | 2022-12-21_efad1:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-12-28 | 2022-12-28_97cf3def25_BNSF Data 2022-12-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-12-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-12-28_97cf3def25_BNSF Data 2022-12-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-12-28 | 2022-12-28_97cf3:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-11-02 | 2022-11-02_f12bdb04cc_BNSF Data 2022-11-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-11-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-11-02_f12bdb04cc_BNSF Data 2022-11-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-11-02 | 2022-11-02_f12bd:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-11-09 | 2022-11-09_f04cf5bae0_BNSF Data 2022-11-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-11-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-11-09_f04cf5bae0_BNSF Data 2022-11-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-11-09 | 2022-11-09_f04cf:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-11-16 | 2022-11-16_4b4091ef1c_BNSF Data 2022-11-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-11-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-11-16_4b4091ef1c_BNSF Data 2022-11-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-11-16 | 2022-11-16_4b409:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-11-23 | 2022-11-23_c255068550_BNSF Data 2022-11-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-11-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-11-23_c255068550_BNSF Data 2022-11-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-11-23 | 2022-11-23_c2550:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-11-30 | 2022-11-30_7894168051_BNSF Data 2022-11-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-11-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-11-30_7894168051_BNSF Data 2022-11-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-11-30 | 2022-11-30_78941:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-10-05 | 2022-10-05_84daa2a20c_BNSF Data 2022-10-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-10-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-10-05_84daa2a20c_BNSF Data 2022-10-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-10-05 | 2022-10-05_84daa:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-10-12 | 2022-10-12_3f164ac4cb_BNSF Data 2022-10-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-10-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-10-12_3f164ac4cb_BNSF Data 2022-10-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-10-12 | 2022-10-12_3f164:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-10-19 | 2022-10-19_b7cf574905_BNSF Data 2022-10-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-10-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-10-19_b7cf574905_BNSF Data 2022-10-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-10-19 | 2022-10-19_b7cf5:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-10-26 | 2022-10-26_42c65222d4_BNSF Data 2022-10-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-10-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-10-26_42c65222d4_BNSF Data 2022-10-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-10-26 | 2022-10-26_42c65:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-09-07 | 2022-09-07_f09b4359d1_BNSF Data 2022-09-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-09-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-09-07_f09b4359d1_BNSF Data 2022-09-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-09-07 | 2022-09-07_f09b4:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-09-14 | 2022-09-14_ae834bbe43_BNSF Data 2022-09-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-09-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-09-14_ae834bbe43_BNSF Data 2022-09-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-09-14 | 2022-09-14_ae834:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-09-21 | 2022-09-21_749d0e1a26_BNSF Data 2022-09-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-09-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-09-21_749d0e1a26_BNSF Data 2022-09-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-09-21 | 2022-09-21_749d0:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-09-28 | 2022-09-28_16ff16ab0a_BNSF Data 2022-09-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-09-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-09-28_16ff16ab0a_BNSF Data 2022-09-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-09-28 | 2022-09-28_16ff1:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-08-03 | 2022-08-03_b8c49209f7_BNSF Data 2022-08-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-08-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-08-03_b8c49209f7_BNSF Data 2022-08-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-08-03 | 2022-08-03_b8c49:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-08-10 | 2022-08-10_8d08aa9985_BNSF Data 2022-08-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-08-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-08-10_8d08aa9985_BNSF Data 2022-08-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-08-10 | 2022-08-10_8d08a:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-08-17 | 2022-08-17_01b8bbf9ed_BNSF Data 2022-08-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-08-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-08-17_01b8bbf9ed_BNSF Data 2022-08-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-08-17 | 2022-08-17_01b8b:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-08-24 | 2022-08-24_8fc330dcef_BNSF Data 2022-08-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-08-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-08-24_8fc330dcef_BNSF Data 2022-08-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-08-24 | 2022-08-24_8fc33:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-08-31 | 2022-08-31_6a70524e22_BNSF Data 2022-08-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-08-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-08-31_6a70524e22_BNSF Data 2022-08-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-08-31 | 2022-08-31_6a705:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-07-06 | 2022-07-06_5103ec22d0_BNSF Data 2022-07-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-07-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-07-06_5103ec22d0_BNSF Data 2022-07-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-07-06 | 2022-07-06_5103e:   0%|          | 0.00/45.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-07-13 | 2022-07-13_ac9142dac4_BNSF Data 2022-07-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-07-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-07-13_ac9142dac4_BNSF Data 2022-07-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-07-13 | 2022-07-13_ac914:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-07-20 | 2022-07-20_5bbfa1a0ad_BNSF Data 2022-07-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-07-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-07-20_5bbfa1a0ad_BNSF Data 2022-07-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-07-20 | 2022-07-20_5bbfa:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-07-27 | 2022-07-27_0d04a25830_BNSF Data 2022-07-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-07-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-07-27_0d04a25830_BNSF Data 2022-07-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-07-27 | 2022-07-27_0d04a:   0%|          | 0.00/37.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-06-01 | 2022-06-01_d698485255_BNSF Data 2022-06-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-06-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-06-01_d698485255_BNSF Data 2022-06-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-06-01 | 2022-06-01_d6984:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-06-08 | 2022-06-08_aeb9536c24_BNSF Data 2022-06-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-06-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-06-08_aeb9536c24_BNSF Data 2022-06-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-06-08 | 2022-06-08_aeb95:   0%|          | 0.00/45.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-06-15 | 2022-06-15_0153fcf3d5_BNSF Data 2022-06-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-06-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-06-15_0153fcf3d5_BNSF Data 2022-06-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-06-15 | 2022-06-15_0153f:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-06-22 | 2022-06-22_3089c71468_BNSF Data 2022-06-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-06-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-06-22_3089c71468_BNSF Data 2022-06-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-06-22 | 2022-06-22_3089c:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-06-29 | 2022-06-29_9a67058cb2_BNSF Data 2022-06-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-06-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-06-29_9a67058cb2_BNSF Data 2022-06-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-06-29 | 2022-06-29_9a670:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-05-04 | 2022-05-04_5068c82fcc_BNSF Data 2022-05-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-05-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-05-04_5068c82fcc_BNSF Data 2022-05-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-05-04 | 2022-05-04_5068c:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-05-11 | 2022-05-11_ef8da804ef_BNSF Data 2022-05-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-05-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-05-11_ef8da804ef_BNSF Data 2022-05-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-05-11 | 2022-05-11_ef8da:   0%|          | 0.00/45.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-05-18 | 2022-05-18_a1ae33d54d_BNSF Data 2022-05-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-05-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-05-18_a1ae33d54d_BNSF Data 2022-05-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-05-18 | 2022-05-18_a1ae3:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-05-25 | 2022-05-25_ebfa8ff6f6_BNSF Data 2022-05-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-05-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-05-25_ebfa8ff6f6_BNSF Data 2022-05-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-05-25 | 2022-05-25_ebfa8:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-04-06 | 2022-04-06_8085caa911_BNSF Data 2022-04-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-04-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-04-06_8085caa911_BNSF Data 2022-04-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-04-06 | 2022-04-06_8085c:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-04-13 | 2022-04-13_ab40fbf94a_BNSF Data 2022-04-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-04-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-04-13_ab40fbf94a_BNSF Data 2022-04-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-04-13 | 2022-04-13_ab40f:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-04-20 | 2022-04-20_86899b192b_BNSF Data 2022-04-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-04-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-04-20_86899b192b_BNSF Data 2022-04-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-04-20 | 2022-04-20_86899:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-04-27 | 2022-04-27_92beab016d_BNSF Data 2022-04-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-04-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-04-27_92beab016d_BNSF Data 2022-04-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-04-27 | 2022-04-27_92bea:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-03-02 | 2022-03-02_b0e952cd35_BNSF Data 2022-03-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-03-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-03-02_b0e952cd35_BNSF Data 2022-03-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-03-02 | 2022-03-02_b0e95:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-03-09 | 2022-03-09_0ea20d4a07_BNSF Data 2022-03-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-03-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-03-09_0ea20d4a07_BNSF Data 2022-03-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-03-09 | 2022-03-09_0ea20:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-03-16 | 2022-03-16_0d0aa25a57_BNSF Data 2022-03-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-03-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-03-16_0d0aa25a57_BNSF Data 2022-03-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-03-16 | 2022-03-16_0d0aa:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-03-23 | 2022-03-23_0547caf859_BNSF Data 2022-03-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-03-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-03-23_0547caf859_BNSF Data 2022-03-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-03-23 | 2022-03-23_0547c:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-03-30 | 2022-03-30_f7f8fc31d9_BNSF Data 2022-03-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-03-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-03-30_f7f8fc31d9_BNSF Data 2022-03-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-03-30 | 2022-03-30_f7f8f:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-02-02 | 2022-02-02_df7796eb64_BNSF Data 2022-02-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-02-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-02-02_df7796eb64_BNSF Data 2022-02-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-02-02 | 2022-02-02_df779:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-02-09 | 2022-02-09_dd36a0269b_BNSF Data 2022-02-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-02-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-02-09_dd36a0269b_BNSF Data 2022-02-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-02-09 | 2022-02-09_dd36a:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-02-16 | 2022-02-16_01bdb0433d_BNSF Data 2022-02-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-02-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-02-16_01bdb0433d_BNSF Data 2022-02-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-02-16 | 2022-02-16_01bdb:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-02-23 | 2022-02-23_a65454333d_BNSF Data 2022-02-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-02-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-02-23_a65454333d_BNSF Data 2022-02-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-02-23 | 2022-02-23_a6545:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-01-05 | 2022-01-05_d8e774d111_BNSF Data 2022-01-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-01-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-01-05_d8e774d111_BNSF Data 2022-01-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-01-05 | 2022-01-05_d8e77:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-01-12 | 2022-01-12_b468516a67_BNSF Data 2022-01-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-01-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-01-12_b468516a67_BNSF Data 2022-01-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-01-12 | 2022-01-12_b4685:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-01-19 | 2022-01-19_609f0e8633_BNSF Data 2022-01-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-01-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-01-19_609f0e8633_BNSF Data 2022-01-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-01-19 | 2022-01-19_609f0:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2022-01-26 | 2022-01-26_7a1291489a_BNSF Data 2022-01-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202022-01-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2022\xlsx\2022-01-26_7a1291489a_BNSF Data 2022-01-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2022-01-26 | 2022-01-26_7a129:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-12-01 | 2021-12-01_ec0efeb72d_BNSF Data 2021-12-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-12-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-12-01_ec0efeb72d_BNSF Data 2021-12-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-12-01 | 2021-12-01_ec0ef:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-12-08 | 2021-12-08_d47d4b1fd0_BNSF Data 2021-12-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-12-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-12-08_d47d4b1fd0_BNSF Data 2021-12-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-12-08 | 2021-12-08_d47d4:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-12-15 | 2021-12-15_716f1a9c4f_BNSF Data 2021-12-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-12-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-12-15_716f1a9c4f_BNSF Data 2021-12-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-12-15 | 2021-12-15_716f1:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-12-22 | 2021-12-22_25d657cf00_BNSF Data 2021-12-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-12-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-12-22_25d657cf00_BNSF Data 2021-12-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-12-22 | 2021-12-22_25d65:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-12-29 | 2021-12-29_fbb4328253_BNSF Data 2021-12-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-12-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-12-29_fbb4328253_BNSF Data 2021-12-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-12-29 | 2021-12-29_fbb43:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-11-03 | 2021-11-03_4d84eee2f2_BNSF Data 2021-11-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-11-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-11-03_4d84eee2f2_BNSF Data 2021-11-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-11-03 | 2021-11-03_4d84e:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-11-10 | 2021-11-10_807c337d86_BNSF Data 2021-11-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-11-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-11-10_807c337d86_BNSF Data 2021-11-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-11-10 | 2021-11-10_807c3:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-11-17 | 2021-11-17_4488aa888d_BNSF Data 2021-11-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-11-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-11-17_4488aa888d_BNSF Data 2021-11-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-11-17 | 2021-11-17_4488a:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-11-24 | 2021-11-24_597615849c_BNSF Data 2021-11-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-11-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-11-24_597615849c_BNSF Data 2021-11-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-11-24 | 2021-11-24_59761:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-10-06 | 2021-10-06_2693b23133_BNSF Data 2021-10-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-10-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-10-06_2693b23133_BNSF Data 2021-10-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-10-06 | 2021-10-06_2693b:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-10-13 | 2021-10-13_c01b42cd85_BNSF Data 2021-10-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-10-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-10-13_c01b42cd85_BNSF Data 2021-10-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-10-13 | 2021-10-13_c01b4:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-10-20 | 2021-10-20_db63283b0c_BNSF Data 2021-10-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-10-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-10-20_db63283b0c_BNSF Data 2021-10-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-10-20 | 2021-10-20_db632:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-10-27 | 2021-10-27_05225684bb_BNSF Data 2021-10-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-10-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-10-27_05225684bb_BNSF Data 2021-10-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-10-27 | 2021-10-27_05225:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-09-01 | 2021-09-01_897dd14dfd_BNSF Data 2021-09-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-09-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-09-01_897dd14dfd_BNSF Data 2021-09-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-09-01 | 2021-09-01_897dd:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-09-08 | 2021-09-08_29dd6d26bb_BNSF Data 2021-09-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-09-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-09-08_29dd6d26bb_BNSF Data 2021-09-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-09-08 | 2021-09-08_29dd6:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-09-15 | 2021-09-15_f289a9e4b7_BNSF Data 2021-09-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-09-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-09-15_f289a9e4b7_BNSF Data 2021-09-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-09-15 | 2021-09-15_f289a:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-09-22 | 2021-09-22_e6e5b37c9d_BNSF Data 2021-09-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-09-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-09-22_e6e5b37c9d_BNSF Data 2021-09-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-09-22 | 2021-09-22_e6e5b:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-09-29 | 2021-09-29_1ae42ef06f_BNSF Data 2021-09-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-09-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-09-29_1ae42ef06f_BNSF Data 2021-09-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-09-29 | 2021-09-29_1ae42:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-08-04 | 2021-08-04_a72ef2011e_BNSF Data 2021-08-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-08-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-08-04_a72ef2011e_BNSF Data 2021-08-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-08-04 | 2021-08-04_a72ef:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-08-11 | 2021-08-11_17d07c98ef_BNSF Data 2021-08-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-08-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-08-11_17d07c98ef_BNSF Data 2021-08-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-08-11 | 2021-08-11_17d07:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-08-18 | 2021-08-18_40f5a9314e_BNSF Data 2021-08-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-08-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-08-18_40f5a9314e_BNSF Data 2021-08-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-08-18 | 2021-08-18_40f5a:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-08-25 | 2021-08-25_2c1e4d8991_BNSF Data 2021-08-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-08-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-08-25_2c1e4d8991_BNSF Data 2021-08-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-08-25 | 2021-08-25_2c1e4:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-07-07 | 2021-07-07_f2db076270_BNSF Data 2021-07-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-07-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-07-07_f2db076270_BNSF Data 2021-07-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-07-07 | 2021-07-07_f2db0:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-07-14 | 2021-07-14_7d6c1b481e_BNSF Data 2021-07-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-07-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-07-14_7d6c1b481e_BNSF Data 2021-07-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-07-14 | 2021-07-14_7d6c1:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-07-21 | 2021-07-21_405c4ecc27_BNSF Data 2021-07-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-07-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-07-21_405c4ecc27_BNSF Data 2021-07-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-07-21 | 2021-07-21_405c4:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-07-28 | 2021-07-28_a21bef3299_BNSF Data 2021-07-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-07-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-07-28_a21bef3299_BNSF Data 2021-07-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-07-28 | 2021-07-28_a21be:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-06-02 | 2021-06-02_42723ec79a_BNSF Data 2021-06-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-06-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-06-02_42723ec79a_BNSF Data 2021-06-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-06-02 | 2021-06-02_42723:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-06-09 | 2021-06-09_d828464920_BNSF Data 2021-06-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-06-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-06-09_d828464920_BNSF Data 2021-06-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-06-09 | 2021-06-09_d8284:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-06-16 | 2021-06-16_078fbeb799_BNSF Data 2021-06-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-06-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-06-16_078fbeb799_BNSF Data 2021-06-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-06-16 | 2021-06-16_078fb:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-06-23 | 2021-06-23_4e9ef6f80a_BNSF Data 2021-06-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-06-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-06-23_4e9ef6f80a_BNSF Data 2021-06-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-06-23 | 2021-06-23_4e9ef:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-06-30 | 2021-06-30_34d44ac578_BNSF Data 2021-06-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-06-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-06-30_34d44ac578_BNSF Data 2021-06-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-06-30 | 2021-06-30_34d44:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-05-05 | 2021-05-05_c03ec782f9_BNSF Data 2021-05-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-05-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-05-05_c03ec782f9_BNSF Data 2021-05-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-05-05 | 2021-05-05_c03ec:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-05-12 | 2021-05-12_68b0448fa0_BNSF Data 2021-05-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-05-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-05-12_68b0448fa0_BNSF Data 2021-05-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-05-12 | 2021-05-12_68b04:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-05-19 | 2021-05-19_b56a718833_BNSF Data 2021-05-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-05-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-05-19_b56a718833_BNSF Data 2021-05-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-05-19 | 2021-05-19_b56a7:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-05-26 | 2021-05-26_c5a6d28125_BNSF Data 2021-05-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-05-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-05-26_c5a6d28125_BNSF Data 2021-05-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-05-26 | 2021-05-26_c5a6d:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-04-07 | 2021-04-07_bf8c86d611_BNSF Data 2021-04-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-04-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-04-07_bf8c86d611_BNSF Data 2021-04-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-04-07 | 2021-04-07_bf8c8:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-04-14 | 2021-04-14_6bf96bb0c2_BNSF Data 2021-04-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-04-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-04-14_6bf96bb0c2_BNSF Data 2021-04-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-04-14 | 2021-04-14_6bf96:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-04-21 | 2021-04-21_eb150a9b46_BNSF Data 2021-04-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-04-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-04-21_eb150a9b46_BNSF Data 2021-04-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-04-21 | 2021-04-21_eb150:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-04-28 | 2021-04-28_39d811273c_BNSF Data 2021-04-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-04-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-04-28_39d811273c_BNSF Data 2021-04-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-04-28 | 2021-04-28_39d81:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-03-03 | 2021-03-03_3a5a3e9ed1_BNSF Data 2021-03-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-03-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-03-03_3a5a3e9ed1_BNSF Data 2021-03-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-03-03 | 2021-03-03_3a5a3:   0%|          | 0.00/46.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-03-10 | 2021-03-10_7f3345476d_BNSF Data 2021-03-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-03-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-03-10_7f3345476d_BNSF Data 2021-03-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-03-10 | 2021-03-10_7f334:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-03-17 | 2021-03-17_e1f40bd656_BNSF Data 2021-03-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-03-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-03-17_e1f40bd656_BNSF Data 2021-03-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-03-17 | 2021-03-17_e1f40:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-03-24 | 2021-03-24_8aaed9382d_BNSF Data 2021-03-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-03-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-03-24_8aaed9382d_BNSF Data 2021-03-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-03-24 | 2021-03-24_8aaed:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-03-31 | 2021-03-31_807a6892d6_BNSF Data 2021-03-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-03-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-03-31_807a6892d6_BNSF Data 2021-03-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-03-31 | 2021-03-31_807a6:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-02-03 | 2021-02-03_e41c5943c5_BNSF Data 2021-02-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-02-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-02-03_e41c5943c5_BNSF Data 2021-02-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-02-03 | 2021-02-03_e41c5:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-02-10 | 2021-02-10_ab3505ecdc_BNSF Data 2021-02-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-02-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-02-10_ab3505ecdc_BNSF Data 2021-02-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-02-10 | 2021-02-10_ab350:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-02-17 | 2021-02-17_6055743d16_BNSF Data 2021-02-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-02-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-02-17_6055743d16_BNSF Data 2021-02-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-02-17 | 2021-02-17_60557:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-02-24 | 2021-02-24_a5cc35f473_BNSF Data 2021-02-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-02-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-02-24_a5cc35f473_BNSF Data 2021-02-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-02-24 | 2021-02-24_a5cc3:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-01-06 | 2021-01-06_9050af7bc7_BNSF Data 2021-01-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-01-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-01-06_9050af7bc7_BNSF Data 2021-01-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-01-06 | 2021-01-06_9050a:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-01-13 | 2021-01-13_14506418d5_BNSF Data 2021-01-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-01-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-01-13_14506418d5_BNSF Data 2021-01-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-01-13 | 2021-01-13_14506:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-01-20 | 2021-01-20_6da98f765c_BNSF Data 2021-01-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-01-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-01-20_6da98f765c_BNSF Data 2021-01-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-01-20 | 2021-01-20_6da98:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2021-01-27 | 2021-01-27_66b2b2c8fe_BNSF Data 2021-01-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202021-01-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2021\xlsx\2021-01-27_66b2b2c8fe_BNSF Data 2021-01-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2021-01-27 | 2021-01-27_66b2b:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-12-02 | 2020-12-02_3dbbb1921d_BNSF Data 2020-12-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-12-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-12-02_3dbbb1921d_BNSF Data 2020-12-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-12-02 | 2020-12-02_3dbbb:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-12-09 | 2020-12-09_99bd5c863d_BNSF Data 2020-12-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-12-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-12-09_99bd5c863d_BNSF Data 2020-12-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-12-09 | 2020-12-09_99bd5:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-12-16 | 2020-12-16_623f42088e_BNSF Data 2020-12-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-12-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-12-16_623f42088e_BNSF Data 2020-12-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-12-16 | 2020-12-16_623f4:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-12-23 | 2020-12-23_29be98f0f3_BNSF Data 2020-12-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-12-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-12-23_29be98f0f3_BNSF Data 2020-12-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-12-23 | 2020-12-23_29be9:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-12-30 | 2020-12-30_4547de8359_BNSF Data 2020-12-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-12-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-12-30_4547de8359_BNSF Data 2020-12-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-12-30 | 2020-12-30_4547d:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-11-04 | 2020-11-04_27bef57d73_BNSF Data 2020-11-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-11-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-11-04_27bef57d73_BNSF Data 2020-11-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-11-04 | 2020-11-04_27bef:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-11-11 | 2020-11-11_561f053e10_BNSF Data 2020-11-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-11-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-11-11_561f053e10_BNSF Data 2020-11-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-11-11 | 2020-11-11_561f0:   0%|          | 0.00/37.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-11-18 | 2020-11-18_0697464a09_BNSF Data 2020-11-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-11-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-11-18_0697464a09_BNSF Data 2020-11-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-11-18 | 2020-11-18_06974:   0%|          | 0.00/37.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-11-25 | 2020-11-25_5c7c4228cc_BNSF Data 2020-11-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-11-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-11-25_5c7c4228cc_BNSF Data 2020-11-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-11-25 | 2020-11-25_5c7c4:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-10-07 | 2020-10-07_594be2dd3b_BNSF Data 2020-10-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-10-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-10-07_594be2dd3b_BNSF Data 2020-10-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-10-07 | 2020-10-07_594be:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-10-14 | 2020-10-14_788c535f7c_BNSF Data 2020-10-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-10-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-10-14_788c535f7c_BNSF Data 2020-10-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-10-14 | 2020-10-14_788c5:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-10-21 | 2020-10-21_e6592352eb_BNSF Data 2020-10-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-10-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-10-21_e6592352eb_BNSF Data 2020-10-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-10-21 | 2020-10-21_e6592:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-10-28 | 2020-10-28_44ad571f9c_BNSF Data 2020-10-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-10-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-10-28_44ad571f9c_BNSF Data 2020-10-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-10-28 | 2020-10-28_44ad5:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-09-02 | 2020-09-02_fe452ca0dd_BNSF Data 2020-09-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-09-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-09-02_fe452ca0dd_BNSF Data 2020-09-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-09-02 | 2020-09-02_fe452:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-09-09 | 2020-09-09_509317a1af_BNSF Data 2020-09-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-09-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-09-09_509317a1af_BNSF Data 2020-09-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-09-09 | 2020-09-09_50931:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-09-16 | 2020-09-16_96d216627d_BNSF Data 2020-09-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-09-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-09-16_96d216627d_BNSF Data 2020-09-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-09-16 | 2020-09-16_96d21:   0%|          | 0.00/43.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-09-23 | 2020-09-23_ae40050a6d_BNSF Data 2020-09-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-09-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-09-23_ae40050a6d_BNSF Data 2020-09-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-09-23 | 2020-09-23_ae400:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-09-30 | 2020-09-30_3ecd69235d_BNSF Data 2020-09-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-09-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-09-30_3ecd69235d_BNSF Data 2020-09-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-09-30 | 2020-09-30_3ecd6:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-08-05 | 2020-08-05_20cb11bf7c_BNSF Data 2020-08-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-08-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-08-05_20cb11bf7c_BNSF Data 2020-08-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-08-05 | 2020-08-05_20cb1:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-08-12 | 2020-08-12_d74b029102_BNSF Data 2020-08-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-08-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-08-12_d74b029102_BNSF Data 2020-08-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-08-12 | 2020-08-12_d74b0:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-08-19 | 2020-08-19_c0b446093d_BNSF Data 2020-08-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-08-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-08-19_c0b446093d_BNSF Data 2020-08-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-08-19 | 2020-08-19_c0b44:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-08-26 | 2020-08-26_967756c921_BNSF Data 2020-08-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-08-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-08-26_967756c921_BNSF Data 2020-08-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-08-26 | 2020-08-26_96775:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-07-01 | 2020-07-01_fee12d9412_bnsf_data_2020-07-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-07-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-07-01_fee12d9412_bnsf_data_2020-07-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-07-01 | 2020-07-01_fee12:   0%|          | 0.00/48.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-07-08 | 2020-07-08_76f7eba909_bnsf_data_2020-07-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-07-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-07-08_76f7eba909_bnsf_data_2020-07-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-07-08 | 2020-07-08_76f7e:   0%|          | 0.00/48.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-07-15 | 2020-07-15_1283a74933_bnsf_data_2020-07-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-07-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-07-15_1283a74933_bnsf_data_2020-07-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-07-15 | 2020-07-15_1283a:   0%|          | 0.00/48.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-07-22 | 2020-07-22_65598e30ef_bnsf_data_2020-07-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-07-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-07-22_65598e30ef_bnsf_data_2020-07-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-07-22 | 2020-07-22_65598:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-07-29 | 2020-07-29_beb620a40d_BNSF Data 2020-07-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/BNSF%20Data%202020-07-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-07-29_beb620a40d_BNSF Data 2020-07-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-07-29 | 2020-07-29_beb62:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-06-03 | 2020-06-03_c8edb3ab94_bnsf_data_2020-06-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-06-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-06-03_c8edb3ab94_bnsf_data_2020-06-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-06-03 | 2020-06-03_c8edb:   0%|          | 0.00/48.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-06-10 | 2020-06-10_d52aa42c66_bnsf_data_2020-06-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-06-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-06-10_d52aa42c66_bnsf_data_2020-06-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-06-10 | 2020-06-10_d52aa:   0%|          | 0.00/48.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-06-17 | 2020-06-17_67b3f2830f_bnsf_data_2020-06-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-06-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-06-17_67b3f2830f_bnsf_data_2020-06-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-06-17 | 2020-06-17_67b3f:   0%|          | 0.00/48.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-06-24 | 2020-06-24_f548fba0db_bnsf_data_2020-06-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-06-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-06-24_f548fba0db_bnsf_data_2020-06-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-06-24 | 2020-06-24_f548f:   0%|          | 0.00/48.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-05-06 | 2020-05-06_69a934451a_bnsf_data_2020-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-05-06_69a934451a_bnsf_data_2020-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-05-06 | 2020-05-06_69a93:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-05-13 | 2020-05-13_a6b6f372ca_bnsf_data_2020-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-05-13_a6b6f372ca_bnsf_data_2020-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-05-13 | 2020-05-13_a6b6f:   0%|          | 0.00/48.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-05-20 | 2020-05-20_ece37aa838_bnsf_data_2020-05-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-05-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-05-20_ece37aa838_bnsf_data_2020-05-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-05-20 | 2020-05-20_ece37:   0%|          | 0.00/48.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-05-27 | 2020-05-27_a617d2606f_bnsf_data_2020-05-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-05-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-05-27_a617d2606f_bnsf_data_2020-05-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-05-27 | 2020-05-27_a617d:   0%|          | 0.00/48.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-04-01 | 2020-04-01_965b9db43a_bnsf_data_2020-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-04-01_965b9db43a_bnsf_data_2020-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-04-01 | 2020-04-01_965b9:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-04-08 | 2020-04-08_7e9ccc4032_bnsf_data_2020-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-04-08_7e9ccc4032_bnsf_data_2020-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-04-08 | 2020-04-08_7e9cc:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-04-15 | 2020-04-15_0c39c581b1_bnsf_data_2020-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-04-15_0c39c581b1_bnsf_data_2020-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-04-15 | 2020-04-15_0c39c:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-04-22 | 2020-04-22_8e5fe0f400_bnsf_data_2020-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-04-22_8e5fe0f400_bnsf_data_2020-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-04-22 | 2020-04-22_8e5fe:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-04-29 | 2020-04-29_3558282042_bnsf_data_2020-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-04-29_3558282042_bnsf_data_2020-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-04-29 | 2020-04-29_35582:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-03-04 | 2020-03-04_926e8a76d7_bnsf_data_2020-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-03-04_926e8a76d7_bnsf_data_2020-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-03-04 | 2020-03-04_926e8:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-03-11 | 2020-03-11_e2ee5fe5f1_bnsf_data_2020-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-03-11_e2ee5fe5f1_bnsf_data_2020-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-03-11 | 2020-03-11_e2ee5:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-03-18 | 2020-03-18_d4c2a16af8_bnsf_data_2020-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-03-18_d4c2a16af8_bnsf_data_2020-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-03-18 | 2020-03-18_d4c2a:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-03-25 | 2020-03-25_ad15de5bd2_bnsf_data_2020-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-03-25_ad15de5bd2_bnsf_data_2020-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-03-25 | 2020-03-25_ad15d:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-02-05 | 2020-02-05_2195e25ce9_bnsf_data_2020-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-02-05_2195e25ce9_bnsf_data_2020-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-02-05 | 2020-02-05_2195e:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-02-12 | 2020-02-12_63a8d375ae_bnsf_data_2020-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-02-12_63a8d375ae_bnsf_data_2020-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-02-12 | 2020-02-12_63a8d:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-02-19 | 2020-02-19_aeeaffa8c6_bnsf_data_2020-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-02-19_aeeaffa8c6_bnsf_data_2020-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-02-19 | 2020-02-19_aeeaf:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-02-26 | 2020-02-26_6060d1a768_bnsf_data_2020-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-02-26_6060d1a768_bnsf_data_2020-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-02-26 | 2020-02-26_6060d:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-01-01 | 2020-01-01_f28e2613c0_bnsf_data_2020-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-01-01_f28e2613c0_bnsf_data_2020-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-01-01 | 2020-01-01_f28e2:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-01-08 | 2020-01-08_e0ba864c3b_bnsf_data_2020-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-01-08_e0ba864c3b_bnsf_data_2020-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-01-08 | 2020-01-08_e0ba8:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-01-15 | 2020-01-15_4913e9f1ee_bnsf_data_2020-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-01-15_4913e9f1ee_bnsf_data_2020-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-01-15 | 2020-01-15_4913e:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-01-22 | 2020-01-22_829e25195f_bnsf_data_2020-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-01-22_829e25195f_bnsf_data_2020-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-01-22 | 2020-01-22_829e2:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | bnsf | 2020-01-29 | 2020-01-29_c804dde471_bnsf_data_2020-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/BNSF/bnsf_data_2020-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\bnsf\2020\xlsx\2020-01-29_c804dde471_bnsf_data_2020-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | bnsf | 2020-01-29 | 2020-01-29_c804d:   0%|          | 0.00/47.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-05-06 | 2026-05-06_2fc6541e0c_CN Data 2026-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-05-06_2fc6541e0c_CN Data 2026-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-05-06 | 2026-05-06_2fc6541:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-05-13 | 2026-05-13_8aff752f9b_CN Data 2026-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-05-13_8aff752f9b_CN Data 2026-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-05-13 | 2026-05-13_8aff752:   0%|          | 0.00/23.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-04-01 | 2026-04-01_e276f0de0c_CN Data 2026-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-04-01_e276f0de0c_CN Data 2026-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-04-01 | 2026-04-01_e276f0d:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-04-08 | 2026-04-08_473d4ae9fa_CN Data 2026-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-04-08_473d4ae9fa_CN Data 2026-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-04-08 | 2026-04-08_473d4ae:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-04-15 | 2026-04-15_d250de547f_CN Data 2026-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-04-15_d250de547f_CN Data 2026-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-04-15 | 2026-04-15_d250de5:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-04-22 | 2026-04-22_9de2f49574_CN Data 2026-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-04-22_9de2f49574_CN Data 2026-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-04-22 | 2026-04-22_9de2f49:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-04-29 | 2026-04-29_548283abeb_CN Data 2026-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-04-29_548283abeb_CN Data 2026-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-04-29 | 2026-04-29_548283a:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-03-04 | 2026-03-04_a693ae11de_CN Data 2026-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-03-04_a693ae11de_CN Data 2026-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-03-04 | 2026-03-04_a693ae1:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-03-11 | 2026-03-11_b0240db3f9_CN Data 2026-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-03-11_b0240db3f9_CN Data 2026-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-03-11 | 2026-03-11_b0240db:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-03-18 | 2026-03-18_9f56bc1ae6_CN Data 2026-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-03-18_9f56bc1ae6_CN Data 2026-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-03-18 | 2026-03-18_9f56bc1:   0%|          | 0.00/23.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-03-25 | 2026-03-25_fd658de03a_CN Data 2026-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-03-25_fd658de03a_CN Data 2026-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-03-25 | 2026-03-25_fd658de:   0%|          | 0.00/23.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-02-04 | 2026-02-04_5f8ac5e517_CN Data 2026-02-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-02-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-02-04_5f8ac5e517_CN Data 2026-02-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-02-04 | 2026-02-04_5f8ac5e:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-02-11 | 2026-02-11_87057837d5_CN Data 2026-02-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-02-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-02-11_87057837d5_CN Data 2026-02-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-02-11 | 2026-02-11_8705783:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-02-18 | 2026-02-18_6dde908a93_CN Data 2026-02-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-02-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-02-18_6dde908a93_CN Data 2026-02-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-02-18 | 2026-02-18_6dde908:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-02-25 | 2026-02-25_0288f70540_CN Data 2026-02-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-02-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-02-25_0288f70540_CN Data 2026-02-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-02-25 | 2026-02-25_0288f70:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-01-07 | 2026-01-07_379e02ac84_CN Data 2026-01-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-01-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-01-07_379e02ac84_CN Data 2026-01-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-01-07 | 2026-01-07_379e02a:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-01-14 | 2026-01-14_9f81d9c2df_CN Data 2026-01-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-01-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-01-14_9f81d9c2df_CN Data 2026-01-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-01-14 | 2026-01-14_9f81d9c:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-01-21 | 2026-01-21_2f316bd36c_CN Data 2026-01-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-01-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-01-21_2f316bd36c_CN Data 2026-01-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-01-21 | 2026-01-21_2f316bd:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2026-01-28 | 2026-01-28_3cbf7e3a76_CN Data 2026-01-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202026-01-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2026\xlsx\2026-01-28_3cbf7e3a76_CN Data 2026-01-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2026-01-28 | 2026-01-28_3cbf7e3:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-12-31 | 2025-12-31_879b5e250e_CN Data 2025-12-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-12-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-12-31_879b5e250e_CN Data 2025-12-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-12-31 | 2025-12-31_879b5e2:   0%|          | 0.00/24.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-12-03 | 2025-12-03_8fb1fc1dc0_CN Data 2025-12-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-12-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-12-03_8fb1fc1dc0_CN Data 2025-12-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-12-03 | 2025-12-03_8fb1fc1:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-12-10 | 2025-12-10_e04065e248_CN Data 2025-12-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-12-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-12-10_e04065e248_CN Data 2025-12-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-12-10 | 2025-12-10_e04065e:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-12-17 | 2025-12-17_e6ca19cbc3_CN Data 2025-12-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-12-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-12-17_e6ca19cbc3_CN Data 2025-12-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-12-17 | 2025-12-17_e6ca19c:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-12-24 | 2025-12-24_8543703c1d_CN Data 2025-12-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-12-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-12-24_8543703c1d_CN Data 2025-12-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-12-24 | 2025-12-24_8543703:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-11-05 | 2025-11-05_1197ddf7de_CN Data 2025-11-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-11-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-11-05_1197ddf7de_CN Data 2025-11-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-11-05 | 2025-11-05_1197ddf:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-11-12 | 2025-11-12_10febf60d6_CN Data 2025-11-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-11-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-11-12_10febf60d6_CN Data 2025-11-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-11-12 | 2025-11-12_10febf6:   0%|          | 0.00/24.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-11-19 | 2025-11-19_c07e17478f_CN Data 2025-11-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-11-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-11-19_c07e17478f_CN Data 2025-11-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-11-19 | 2025-11-19_c07e174:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-11-26 | 2025-11-26_79d41038ea_CN Data 2025-11-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-11-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-11-26_79d41038ea_CN Data 2025-11-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-11-26 | 2025-11-26_79d4103:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-10-01 | 2025-10-01_97456e5b0d_CN Data 2025-10-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-10-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-10-01_97456e5b0d_CN Data 2025-10-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-10-01 | 2025-10-01_97456e5:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-10-08 | 2025-10-08_21e8dde6b7_CN Data 2025-10-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-10-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-10-08_21e8dde6b7_CN Data 2025-10-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-10-08 | 2025-10-08_21e8dde:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-10-15 | 2025-10-15_490612739f_CN Data 2025-10-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-10-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-10-15_490612739f_CN Data 2025-10-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-10-15 | 2025-10-15_4906127:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-10-22 | 2025-10-22_92468388f2_CN Data 2025-10-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-10-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-10-22_92468388f2_CN Data 2025-10-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-10-22 | 2025-10-22_9246838:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-10-29 | 2025-10-29_f20bc363ee_CN Data 2025-10-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-10-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-10-29_f20bc363ee_CN Data 2025-10-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-10-29 | 2025-10-29_f20bc36:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-09-03 | 2025-09-03_6ede2870e1_CN Data 2025-09-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-09-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-09-03_6ede2870e1_CN Data 2025-09-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-09-03 | 2025-09-03_6ede287:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-09-10 | 2025-09-10_60b911a240_CN Data 2025-09-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-09-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-09-10_60b911a240_CN Data 2025-09-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-09-10 | 2025-09-10_60b911a:   0%|          | 0.00/23.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-09-17 | 2025-09-17_dc31304349_CN Data 2025-09-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-09-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-09-17_dc31304349_CN Data 2025-09-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-09-17 | 2025-09-17_dc31304:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-09-24 | 2025-09-24_38089c9d55_CN Data 2025-09-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-09-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-09-24_38089c9d55_CN Data 2025-09-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-09-24 | 2025-09-24_38089c9:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-08-06 | 2025-08-06_7272d068a1_CN Data 2025-08-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-08-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-08-06_7272d068a1_CN Data 2025-08-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-08-06 | 2025-08-06_7272d06:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-08-13 | 2025-08-13_05a1c10b85_CN Data 2025-08-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-08-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-08-13_05a1c10b85_CN Data 2025-08-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-08-13 | 2025-08-13_05a1c10:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-08-20 | 2025-08-20_2c78c238c4_CN Data 2025-08-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-08-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-08-20_2c78c238c4_CN Data 2025-08-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-08-20 | 2025-08-20_2c78c23:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-08-27 | 2025-08-27_eaf56f3953_CN Data 2025-08-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-08-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-08-27_eaf56f3953_CN Data 2025-08-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-08-27 | 2025-08-27_eaf56f3:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-07-02 | 2025-07-02_d415febaad_CN Data 2025-07-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-07-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-07-02_d415febaad_CN Data 2025-07-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-07-02 | 2025-07-02_d415feb:   0%|          | 0.00/23.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-07-09 | 2025-07-09_a3cf605ff7_CN Data 2025-07-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-07-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-07-09_a3cf605ff7_CN Data 2025-07-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-07-09 | 2025-07-09_a3cf605:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-07-16 | 2025-07-16_ece76e8440_CN Data 2025-07-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-07-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-07-16_ece76e8440_CN Data 2025-07-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-07-16 | 2025-07-16_ece76e8:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-07-23 | 2025-07-23_8588e11e60_CN Data 2025-07-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-07-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-07-23_8588e11e60_CN Data 2025-07-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-07-23 | 2025-07-23_8588e11:   0%|          | 0.00/23.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-07-30 | 2025-07-30_0d3afdbc22_CN Data 2025-07-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-07-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-07-30_0d3afdbc22_CN Data 2025-07-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-07-30 | 2025-07-30_0d3afdb:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-06-04 | 2025-06-04_befa65a527_CN Data 2025-06-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-06-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-06-04_befa65a527_CN Data 2025-06-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-06-04 | 2025-06-04_befa65a:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-06-11 | 2025-06-11_839c6211e1_CN Data 2025-06-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-06-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-06-11_839c6211e1_CN Data 2025-06-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-06-11 | 2025-06-11_839c621:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-06-18 | 2025-06-18_f43f08a52f_CN Data 2025-06-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-06-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-06-18_f43f08a52f_CN Data 2025-06-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-06-18 | 2025-06-18_f43f08a:   0%|          | 0.00/23.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-06-25 | 2025-06-25_83a4810e2d_CN Data 2025-06-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-06-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-06-25_83a4810e2d_CN Data 2025-06-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-06-25 | 2025-06-25_83a4810:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-05-07 | 2025-05-07_9ec0d07faa_CN Data 2025-05-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-05-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-05-07_9ec0d07faa_CN Data 2025-05-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-05-07 | 2025-05-07_9ec0d07:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-05-14 | 2025-05-14_a42c45b5c0_CN Data 2025-05-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-05-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-05-14_a42c45b5c0_CN Data 2025-05-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-05-14 | 2025-05-14_a42c45b:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-05-21 | 2025-05-21_e90572fe50_CN Data 2025-05-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-05-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-05-21_e90572fe50_CN Data 2025-05-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-05-21 | 2025-05-21_e90572f:   0%|          | 0.00/23.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-05-28 | 2025-05-28_304118b8e9_CN Data 2025-05-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-05-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-05-28_304118b8e9_CN Data 2025-05-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-05-28 | 2025-05-28_304118b:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-04-02 | 2025-04-02_72502242de_CN Data 2025-04-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-04-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-04-02_72502242de_CN Data 2025-04-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-04-02 | 2025-04-02_7250224:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-04-09 | 2025-04-09_28ea0edb5f_CN Data 2025-04-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-04-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-04-09_28ea0edb5f_CN Data 2025-04-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-04-09 | 2025-04-09_28ea0ed:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-04-16 | 2025-04-16_d2d0d9a5e4_CN Data 2025-04-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-04-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-04-16_d2d0d9a5e4_CN Data 2025-04-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-04-16 | 2025-04-16_d2d0d9a:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-04-23 | 2025-04-23_a7c206ee9f_CN Data 2025-04-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-04-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-04-23_a7c206ee9f_CN Data 2025-04-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-04-23 | 2025-04-23_a7c206e:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-04-30 | 2025-04-30_7fcc0eb289_CN Data 2025-04-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-04-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-04-30_7fcc0eb289_CN Data 2025-04-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-04-30 | 2025-04-30_7fcc0eb:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-03-05 | 2025-03-05_9fa03e6eca_CN Data 2025-03-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-03-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-03-05_9fa03e6eca_CN Data 2025-03-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-03-05 | 2025-03-05_9fa03e6:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-03-12 | 2025-03-12_07b08c96a9_CN Data 2025-03-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-03-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-03-12_07b08c96a9_CN Data 2025-03-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-03-12 | 2025-03-12_07b08c9:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-03-19 | 2025-03-19_f3900cbb5e_CN Data 2025-03-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-03-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-03-19_f3900cbb5e_CN Data 2025-03-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-03-19 | 2025-03-19_f3900cb:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-03-26 | 2025-03-26_e1e784dceb_CN Data 2025-03-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-03-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-03-26_e1e784dceb_CN Data 2025-03-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-03-26 | 2025-03-26_e1e784d:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-02-05 | 2025-02-05_97fa0e0098_CN Data 2025-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-02-05_97fa0e0098_CN Data 2025-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-02-05 | 2025-02-05_97fa0e0:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-02-12 | 2025-02-12_98234b0341_CN Data 2025-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-02-12_98234b0341_CN Data 2025-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-02-12 | 2025-02-12_98234b0:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-02-19 | 2025-02-19_97c2ee1785_CN Data 2025-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-02-19_97c2ee1785_CN Data 2025-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-02-19 | 2025-02-19_97c2ee1:   0%|          | 0.00/22.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-02-26 | 2025-02-26_04c5489dc1_CN Data 2025-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-02-26_04c5489dc1_CN Data 2025-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-02-26 | 2025-02-26_04c5489:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-01-01 | 2025-01-01_b3c78d8800_CN Data 2025-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-01-01_b3c78d8800_CN Data 2025-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-01-01 | 2025-01-01_b3c78d8:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-01-08 | 2025-01-08_73929c91ce_CN Data 2025-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-01-08_73929c91ce_CN Data 2025-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-01-08 | 2025-01-08_73929c9:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-01-15 | 2025-01-15_594537617a_CN Data 2025-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-01-15_594537617a_CN Data 2025-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-01-15 | 2025-01-15_5945376:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-01-22 | 2025-01-22_1b86c63172_CN Data 2025-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-01-22_1b86c63172_CN Data 2025-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-01-22 | 2025-01-22_1b86c63:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2025-01-29 | 2025-01-29_e851cccd3a_CN Data 2025-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202025-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2025\xlsx\2025-01-29_e851cccd3a_CN Data 2025-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2025-01-29 | 2025-01-29_e851ccc:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-12-04 | 2024-12-04_c6d6ab9e03_CN Data 2024-12-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-12-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-12-04_c6d6ab9e03_CN Data 2024-12-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-12-04 | 2024-12-04_c6d6ab9:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-12-11 | 2024-12-11_7f582b98c4_CN Data 2024-12-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-12-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-12-11_7f582b98c4_CN Data 2024-12-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-12-11 | 2024-12-11_7f582b9:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-12-18 | 2024-12-18_666f735720_CN Data 2024-12-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-12-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-12-18_666f735720_CN Data 2024-12-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-12-18 | 2024-12-18_666f735:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-12-25 | 2024-12-25_fcc12cbb84_CN Data 2024-12-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-12-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-12-25_fcc12cbb84_CN Data 2024-12-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-12-25 | 2024-12-25_fcc12cb:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-11-06 | 2024-11-06_0b7ae8a069_CN Data 2024-11-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-11-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-11-06_0b7ae8a069_CN Data 2024-11-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-11-06 | 2024-11-06_0b7ae8a:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-11-13 | 2024-11-13_a71ca0eb73_CN Data 2024-11-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-11-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-11-13_a71ca0eb73_CN Data 2024-11-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-11-13 | 2024-11-13_a71ca0e:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-11-20 | 2024-11-20_b5739a8a87_CN Data 2024-11-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-11-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-11-20_b5739a8a87_CN Data 2024-11-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-11-20 | 2024-11-20_b5739a8:   0%|          | 0.00/23.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-11-27 | 2024-11-27_9256a6f33a_CN Data 2024-11-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-11-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-11-27_9256a6f33a_CN Data 2024-11-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-11-27 | 2024-11-27_9256a6f:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-10-02 | 2024-10-02_f08fa89f36_CN Data 2024-10-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-10-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-10-02_f08fa89f36_CN Data 2024-10-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-10-02 | 2024-10-02_f08fa89:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-10-09 | 2024-10-09_b35cc87e12_CN Data 2024-10-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-10-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-10-09_b35cc87e12_CN Data 2024-10-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-10-09 | 2024-10-09_b35cc87:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-10-16 | 2024-10-16_d5f2391e55_CN Data 2024-10-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-10-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-10-16_d5f2391e55_CN Data 2024-10-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-10-16 | 2024-10-16_d5f2391:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-10-23 | 2024-10-23_07de71dff4_CN Data 2024-10-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-10-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-10-23_07de71dff4_CN Data 2024-10-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-10-23 | 2024-10-23_07de71d:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-10-30 | 2024-10-30_34c59f1fa0_CN Data 2024-10-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-10-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-10-30_34c59f1fa0_CN Data 2024-10-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-10-30 | 2024-10-30_34c59f1:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-09-04 | 2024-09-04_f51251fc98_CN Data 2024-09-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-09-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-09-04_f51251fc98_CN Data 2024-09-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-09-04 | 2024-09-04_f51251f:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-09-11 | 2024-09-11_dc4c28d19f_CN Data 2024-09-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-09-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-09-11_dc4c28d19f_CN Data 2024-09-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-09-11 | 2024-09-11_dc4c28d:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-09-18 | 2024-09-18_7f34f17295_CN Data 2024-09-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-09-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-09-18_7f34f17295_CN Data 2024-09-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-09-18 | 2024-09-18_7f34f17:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-09-25 | 2024-09-25_ab118ecb30_CN Data 2024-09-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-09-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-09-25_ab118ecb30_CN Data 2024-09-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-09-25 | 2024-09-25_ab118ec:   0%|          | 0.00/23.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-08-07 | 2024-08-07_5742591dfd_CN Data 2024-08-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-08-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-08-07_5742591dfd_CN Data 2024-08-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-08-07 | 2024-08-07_5742591:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-08-14 | 2024-08-14_2a377f8138_CN Data 2024-08-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-08-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-08-14_2a377f8138_CN Data 2024-08-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-08-14 | 2024-08-14_2a377f8:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-08-21 | 2024-08-21_6483481bd3_CN Data 2024-08-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-08-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-08-21_6483481bd3_CN Data 2024-08-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-08-21 | 2024-08-21_6483481:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-08-28 | 2024-08-28_60f5da303e_CN Data 2024-08-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-08-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-08-28_60f5da303e_CN Data 2024-08-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-08-28 | 2024-08-28_60f5da3:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-07-03 | 2024-07-03_e8aaeb0d85_CN Data 2024-07-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-07-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-07-03_e8aaeb0d85_CN Data 2024-07-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-07-03 | 2024-07-03_e8aaeb0:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-07-10 | 2024-07-10_e008b90314_CN Data 2024-07-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-07-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-07-10_e008b90314_CN Data 2024-07-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-07-10 | 2024-07-10_e008b90:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-07-17 | 2024-07-17_3f21208cba_CN Data 2024-07-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-07-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-07-17_3f21208cba_CN Data 2024-07-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-07-17 | 2024-07-17_3f21208:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-07-24 | 2024-07-24_5f8a11ef05_CN Data 2024-07-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-07-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-07-24_5f8a11ef05_CN Data 2024-07-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-07-24 | 2024-07-24_5f8a11e:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-07-31 | 2024-07-31_d5354b3fa9_CN Data 2024-07-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-07-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-07-31_d5354b3fa9_CN Data 2024-07-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-07-31 | 2024-07-31_d5354b3:   0%|          | 0.00/23.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-06-05 | 2024-06-05_fea20c37ef_CN Data 2024-06-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-06-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-06-05_fea20c37ef_CN Data 2024-06-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-06-05 | 2024-06-05_fea20c3:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-06-12 | 2024-06-12_409b111e52_CN Data 2024-06-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-06-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-06-12_409b111e52_CN Data 2024-06-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-06-12 | 2024-06-12_409b111:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-06-19 | 2024-06-19_6fd335d111_CN Data 2024-06-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-06-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-06-19_6fd335d111_CN Data 2024-06-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-06-19 | 2024-06-19_6fd335d:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-06-26 | 2024-06-26_4148234f92_CN Data 2024-06-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-06-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-06-26_4148234f92_CN Data 2024-06-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-06-26 | 2024-06-26_4148234:   0%|          | 0.00/23.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-05-01 | 2024-05-01_efcec3fff9_CN Data 2024-05-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-05-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-05-01_efcec3fff9_CN Data 2024-05-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-05-01 | 2024-05-01_efcec3f:   0%|          | 0.00/23.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-05-08 | 2024-05-08_ddc7df7e89_CN Data 2024-05-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-05-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-05-08_ddc7df7e89_CN Data 2024-05-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-05-08 | 2024-05-08_ddc7df7:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-05-15 | 2024-05-15_c92d886669_CN Data 2024-05-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-05-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-05-15_c92d886669_CN Data 2024-05-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-05-15 | 2024-05-15_c92d886:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-05-22 | 2024-05-22_11982a5e40_CN Data 2024-05-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-05-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-05-22_11982a5e40_CN Data 2024-05-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-05-22 | 2024-05-22_11982a5:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-05-29 | 2024-05-29_2c36ebc173_CN Data 2024-05-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-05-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-05-29_2c36ebc173_CN Data 2024-05-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-05-29 | 2024-05-29_2c36ebc:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-04-03 | 2024-04-03_2afb18b5c2_CN Data 2024-04-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-04-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-04-03_2afb18b5c2_CN Data 2024-04-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-04-03 | 2024-04-03_2afb18b:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-04-10 | 2024-04-10_a921a0e154_CN Data 2024-04-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-04-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-04-10_a921a0e154_CN Data 2024-04-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-04-10 | 2024-04-10_a921a0e:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-04-17 | 2024-04-17_bd4301934f_CN Data 2024-04-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-04-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-04-17_bd4301934f_CN Data 2024-04-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-04-17 | 2024-04-17_bd43019:   0%|          | 0.00/23.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-04-24 | 2024-04-24_e2c68c7e2e_CN Data 2024-04-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-04-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-04-24_e2c68c7e2e_CN Data 2024-04-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-04-24 | 2024-04-24_e2c68c7:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-03-06 | 2024-03-06_fc2563abb9_CN Data 2024-03-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-03-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-03-06_fc2563abb9_CN Data 2024-03-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-03-06 | 2024-03-06_fc2563a:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-03-13 | 2024-03-13_8aed4b1fec_CN Data 2024-03-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-03-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-03-13_8aed4b1fec_CN Data 2024-03-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-03-13 | 2024-03-13_8aed4b1:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-03-20 | 2024-03-20_f85e165c50_CN Data 2024-03-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-03-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-03-20_f85e165c50_CN Data 2024-03-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-03-20 | 2024-03-20_f85e165:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-03-27 | 2024-03-27_30df38884f_CN Data 2024-03-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-03-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-03-27_30df38884f_CN Data 2024-03-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-03-27 | 2024-03-27_30df388:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-02-07 | 2024-02-07_47a98f6214_CN Data 2024-02-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-02-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-02-07_47a98f6214_CN Data 2024-02-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-02-07 | 2024-02-07_47a98f6:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-02-14 | 2024-02-14_28308f3a3d_CN Data 2024-02-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-02-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-02-14_28308f3a3d_CN Data 2024-02-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-02-14 | 2024-02-14_28308f3:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-02-21 | 2024-02-21_86fc0c182d_CN Data 2024-02-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-02-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-02-21_86fc0c182d_CN Data 2024-02-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-02-21 | 2024-02-21_86fc0c1:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-02-28 | 2024-02-28_2192cf04e9_CN Data 2024-02-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-02-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-02-28_2192cf04e9_CN Data 2024-02-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-02-28 | 2024-02-28_2192cf0:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-01-03 | 2024-01-03_d6bd7644b7_CN Data 2024-01-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-01-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-01-03_d6bd7644b7_CN Data 2024-01-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-01-03 | 2024-01-03_d6bd764:   0%|          | 0.00/28.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-01-10 | 2024-01-10_7d32b57549_CN Data 2024-01-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-01-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-01-10_7d32b57549_CN Data 2024-01-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-01-10 | 2024-01-10_7d32b57:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-01-17 | 2024-01-17_6a09b18b03_CN Data 2024-01-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-01-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-01-17_6a09b18b03_CN Data 2024-01-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-01-17 | 2024-01-17_6a09b18:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-01-24 | 2024-01-24_c983b33dc8_CN Data 2024-01-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-01-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-01-24_c983b33dc8_CN Data 2024-01-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-01-24 | 2024-01-24_c983b33:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2024-01-31 | 2024-01-31_32c4c633a9_CN Data 2024-01-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202024-01-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2024\xlsx\2024-01-31_32c4c633a9_CN Data 2024-01-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2024-01-31 | 2024-01-31_32c4c63:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-12-06 | 2023-12-06_ef20a6d6c4_CN Data 2023-12-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-12-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-12-06_ef20a6d6c4_CN Data 2023-12-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-12-06 | 2023-12-06_ef20a6d:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-12-13 | 2023-12-13_3ad7a52e34_CN Data 2023-12-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-12-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-12-13_3ad7a52e34_CN Data 2023-12-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-12-13 | 2023-12-13_3ad7a52:   0%|          | 0.00/23.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-12-20 | 2023-12-20_ff8781b64c_CN Data 2023-12-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-12-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-12-20_ff8781b64c_CN Data 2023-12-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-12-20 | 2023-12-20_ff8781b:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-12-27 | 2023-12-27_9585735b5e_CN Data 2023-12-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-12-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-12-27_9585735b5e_CN Data 2023-12-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-12-27 | 2023-12-27_9585735:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-11-01 | 2023-11-01_6ebdf9930a_CN Data 2023-11-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-11-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-11-01_6ebdf9930a_CN Data 2023-11-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-11-01 | 2023-11-01_6ebdf99:   0%|          | 0.00/24.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-11-08 | 2023-11-08_2a1cfcd734_CN Data 2023-11-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-11-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-11-08_2a1cfcd734_CN Data 2023-11-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-11-08 | 2023-11-08_2a1cfcd:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-11-15 | 2023-11-15_7bfa88f289_CN Data 2023-11-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-11-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-11-15_7bfa88f289_CN Data 2023-11-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-11-15 | 2023-11-15_7bfa88f:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-11-22 | 2023-11-22_5a58fe3646_CN Data 2023-11-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-11-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-11-22_5a58fe3646_CN Data 2023-11-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-11-22 | 2023-11-22_5a58fe3:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-11-29 | 2023-11-29_446f9d815a_CN Data 2023-11-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-11-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-11-29_446f9d815a_CN Data 2023-11-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-11-29 | 2023-11-29_446f9d8:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-10-04 | 2023-10-04_69668b0520_CN Data 2023-10-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-10-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-10-04_69668b0520_CN Data 2023-10-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-10-04 | 2023-10-04_69668b0:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-10-11 | 2023-10-11_9d77f31064_CN Data 2023-10-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-10-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-10-11_9d77f31064_CN Data 2023-10-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-10-11 | 2023-10-11_9d77f31:   0%|          | 0.00/23.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-10-18 | 2023-10-18_f15bd43bc9_CN Data 2023-10-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-10-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-10-18_f15bd43bc9_CN Data 2023-10-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-10-18 | 2023-10-18_f15bd43:   0%|          | 0.00/24.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-10-25 | 2023-10-25_e2e3a61956_CN Data 2023-10-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-10-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-10-25_e2e3a61956_CN Data 2023-10-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-10-25 | 2023-10-25_e2e3a61:   0%|          | 0.00/24.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-09-06 | 2023-09-06_895aafb20e_CN Data 2023-09-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-09-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-09-06_895aafb20e_CN Data 2023-09-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-09-06 | 2023-09-06_895aafb:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-09-13 | 2023-09-13_bf58969778_CN Data 2023-09-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-09-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-09-13_bf58969778_CN Data 2023-09-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-09-13 | 2023-09-13_bf58969:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-09-20 | 2023-09-20_69c1a4b046_CN Data 2023-09-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-09-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-09-20_69c1a4b046_CN Data 2023-09-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-09-20 | 2023-09-20_69c1a4b:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-09-27 | 2023-09-27_dc2f9cf064_CN Data 2023-09-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-09-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-09-27_dc2f9cf064_CN Data 2023-09-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-09-27 | 2023-09-27_dc2f9cf:   0%|          | 0.00/23.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-08-02 | 2023-08-02_5efb2ea488_CN Data 2023-08-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-08-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-08-02_5efb2ea488_CN Data 2023-08-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-08-02 | 2023-08-02_5efb2ea:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-08-09 | 2023-08-09_e49ec30df4_CN Data 2023-08-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-08-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-08-09_e49ec30df4_CN Data 2023-08-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-08-09 | 2023-08-09_e49ec30:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-08-16 | 2023-08-16_b5525ae04c_CN Data 2023-08-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-08-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-08-16_b5525ae04c_CN Data 2023-08-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-08-16 | 2023-08-16_b5525ae:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-08-23 | 2023-08-23_0feb64549b_CN Data 2023-08-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-08-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-08-23_0feb64549b_CN Data 2023-08-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-08-23 | 2023-08-23_0feb645:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-08-30 | 2023-08-30_050d392fa4_CN Data 2023-08-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-08-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-08-30_050d392fa4_CN Data 2023-08-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-08-30 | 2023-08-30_050d392:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-07-05 | 2023-07-05_b5250d450d_CN Data 2023-07-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-07-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-07-05_b5250d450d_CN Data 2023-07-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-07-05 | 2023-07-05_b5250d4:   0%|          | 0.00/23.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-07-12 | 2023-07-12_ea3a3a0019_CN Data 2023-07-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-07-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-07-12_ea3a3a0019_CN Data 2023-07-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-07-12 | 2023-07-12_ea3a3a0:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-07-19 | 2023-07-19_e041d0f18c_CN Data 2023-07-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-07-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-07-19_e041d0f18c_CN Data 2023-07-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-07-19 | 2023-07-19_e041d0f:   0%|          | 0.00/23.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-07-26 | 2023-07-26_748e9ea0a4_CN Data 2023-07-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-07-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-07-26_748e9ea0a4_CN Data 2023-07-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-07-26 | 2023-07-26_748e9ea:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-06-07 | 2023-06-07_d81a3f2100_CN Data 2023-06-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-06-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-06-07_d81a3f2100_CN Data 2023-06-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-06-07 | 2023-06-07_d81a3f2:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-06-14 | 2023-06-14_75f834fb2a_CN Data 2023-06-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-06-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-06-14_75f834fb2a_CN Data 2023-06-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-06-14 | 2023-06-14_75f834f:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-06-21 | 2023-06-21_0904b576d9_CN Data 2023-06-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-06-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-06-21_0904b576d9_CN Data 2023-06-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-06-21 | 2023-06-21_0904b57:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-06-28 | 2023-06-28_92f78a7230_CN Data 2023-06-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-06-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-06-28_92f78a7230_CN Data 2023-06-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-06-28 | 2023-06-28_92f78a7:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-05-03 | 2023-05-03_51fe85454e_CN Data 2023-05-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-05-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-05-03_51fe85454e_CN Data 2023-05-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-05-03 | 2023-05-03_51fe854:   0%|          | 0.00/23.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-05-10 | 2023-05-10_5f761a0a25_CN Data 2023-05-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-05-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-05-10_5f761a0a25_CN Data 2023-05-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-05-10 | 2023-05-10_5f761a0:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-05-17 | 2023-05-17_16fdae348a_CN Data 2023-05-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-05-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-05-17_16fdae348a_CN Data 2023-05-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-05-17 | 2023-05-17_16fdae3:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-05-24 | 2023-05-24_79289fa0ad_CN Data 2023-05-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-05-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-05-24_79289fa0ad_CN Data 2023-05-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-05-24 | 2023-05-24_79289fa:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-05-31 | 2023-05-31_e0f9524022_CN Data 2023-05-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-05-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-05-31_e0f9524022_CN Data 2023-05-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-05-31 | 2023-05-31_e0f9524:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-04-05 | 2023-04-05_d76546c6af_CN Data 2023-04-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-04-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-04-05_d76546c6af_CN Data 2023-04-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-04-05 | 2023-04-05_d76546c:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-04-12 | 2023-04-12_07f6c6783f_CN Data 2023-04-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-04-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-04-12_07f6c6783f_CN Data 2023-04-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-04-12 | 2023-04-12_07f6c67:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-04-19 | 2023-04-19_5244e53670_CN Data 2023-04-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-04-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-04-19_5244e53670_CN Data 2023-04-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-04-19 | 2023-04-19_5244e53:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-04-26 | 2023-04-26_df88aaf3e5_CN Data 2023-04-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-04-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-04-26_df88aaf3e5_CN Data 2023-04-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-04-26 | 2023-04-26_df88aaf:   0%|          | 0.00/23.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-03-01 | 2023-03-01_fd0d0033bc_CN Data 2023-03-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-03-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-03-01_fd0d0033bc_CN Data 2023-03-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-03-01 | 2023-03-01_fd0d003:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-03-08 | 2023-03-08_2f25324dc7_CN Data 2023-03-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-03-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-03-08_2f25324dc7_CN Data 2023-03-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-03-08 | 2023-03-08_2f25324:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-03-15 | 2023-03-15_9ac3478457_CN Data 2023-03-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-03-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-03-15_9ac3478457_CN Data 2023-03-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-03-15 | 2023-03-15_9ac3478:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-03-22 | 2023-03-22_f9d82dfdb6_CN Data 2023-03-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-03-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-03-22_f9d82dfdb6_CN Data 2023-03-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-03-22 | 2023-03-22_f9d82df:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-03-29 | 2023-03-29_28b0e85a75_CN Data 2023-03-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-03-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-03-29_28b0e85a75_CN Data 2023-03-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-03-29 | 2023-03-29_28b0e85:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-02-01 | 2023-02-01_e4d97ae11b_CN Data 2023-02-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-02-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-02-01_e4d97ae11b_CN Data 2023-02-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-02-01 | 2023-02-01_e4d97ae:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-02-08 | 2023-02-08_50319db934_CN Data 2023-02-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-02-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-02-08_50319db934_CN Data 2023-02-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-02-08 | 2023-02-08_50319db:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-02-15 | 2023-02-15_658b3e6d16_CN Data 2023-02-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-02-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-02-15_658b3e6d16_CN Data 2023-02-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-02-15 | 2023-02-15_658b3e6:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-02-22 | 2023-02-22_7d72075a18_CN Data 2023-02-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-02-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-02-22_7d72075a18_CN Data 2023-02-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-02-22 | 2023-02-22_7d72075:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-01-04 | 2023-01-04_fb9f0c37ff_CN Data 2023-01-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-01-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-01-04_fb9f0c37ff_CN Data 2023-01-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-01-04 | 2023-01-04_fb9f0c3:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-01-11 | 2023-01-11_9a3e2e555e_CN Data 2023-01-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-01-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-01-11_9a3e2e555e_CN Data 2023-01-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-01-11 | 2023-01-11_9a3e2e5:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-01-18 | 2023-01-18_621499b461_CN Data 2023-01-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-01-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-01-18_621499b461_CN Data 2023-01-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-01-18 | 2023-01-18_621499b:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2023-01-25 | 2023-01-25_ecc1798306_CN Data 2023-01-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202023-01-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2023\xlsx\2023-01-25_ecc1798306_CN Data 2023-01-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2023-01-25 | 2023-01-25_ecc1798:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-12-07 | 2022-12-07_e45195aba1_CN Data 2022-12-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-12-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-12-07_e45195aba1_CN Data 2022-12-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-12-07 | 2022-12-07_e45195a:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-12-14 | 2022-12-14_f5b6a23824_CN Data 2022-12-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-12-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-12-14_f5b6a23824_CN Data 2022-12-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-12-14 | 2022-12-14_f5b6a23:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-12-21 | 2022-12-21_05739a421a_CN Data 2022-12-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-12-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-12-21_05739a421a_CN Data 2022-12-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-12-21 | 2022-12-21_05739a4:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-12-28 | 2022-12-28_6f046a9488_CN Data 2022-12-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-12-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-12-28_6f046a9488_CN Data 2022-12-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-12-28 | 2022-12-28_6f046a9:   0%|          | 0.00/22.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-11-02 | 2022-11-02_c5de2cc064_CN Data 2022-11-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-11-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-11-02_c5de2cc064_CN Data 2022-11-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-11-02 | 2022-11-02_c5de2cc:   0%|          | 0.00/163k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-11-09 | 2022-11-09_1125deada8_CN Data 2022-11-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-11-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-11-09_1125deada8_CN Data 2022-11-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-11-09 | 2022-11-09_1125dea:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-11-16 | 2022-11-16_89c64da55c_CN Data 2022-11-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-11-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-11-16_89c64da55c_CN Data 2022-11-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-11-16 | 2022-11-16_89c64da:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-11-23 | 2022-11-23_589c6a64ec_CN Data 2022-11-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-11-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-11-23_589c6a64ec_CN Data 2022-11-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-11-23 | 2022-11-23_589c6a6:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-11-30 | 2022-11-30_437c0c43cb_CN Data 2022-11-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-11-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-11-30_437c0c43cb_CN Data 2022-11-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-11-30 | 2022-11-30_437c0c4:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-10-05 | 2022-10-05_0d6e1d7ef7_CN Data 2022-10-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-10-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-10-05_0d6e1d7ef7_CN Data 2022-10-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-10-05 | 2022-10-05_0d6e1d7:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-10-12 | 2022-10-12_ba23a47d75_CN Data 2022-10-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-10-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-10-12_ba23a47d75_CN Data 2022-10-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-10-12 | 2022-10-12_ba23a47:   0%|          | 0.00/162k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-10-19 | 2022-10-19_f3e62381d0_CN Data 2022-10-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-10-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-10-19_f3e62381d0_CN Data 2022-10-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-10-19 | 2022-10-19_f3e6238:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-10-26 | 2022-10-26_5743a7a8e8_CN Data 2022-10-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-10-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-10-26_5743a7a8e8_CN Data 2022-10-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-10-26 | 2022-10-26_5743a7a:   0%|          | 0.00/163k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-09-07 | 2022-09-07_46f8f2432d_CN Data 2022-09-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-09-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-09-07_46f8f2432d_CN Data 2022-09-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-09-07 | 2022-09-07_46f8f24:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-09-14 | 2022-09-14_6350a4fb6a_CN Data 2022-09-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-09-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-09-14_6350a4fb6a_CN Data 2022-09-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-09-14 | 2022-09-14_6350a4f:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-09-21 | 2022-09-21_a9fff0a6fe_CN Data 2022-09-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-09-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-09-21_a9fff0a6fe_CN Data 2022-09-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-09-21 | 2022-09-21_a9fff0a:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-09-28 | 2022-09-28_5a5865d7a7_CN Data 2022-09-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-09-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-09-28_5a5865d7a7_CN Data 2022-09-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-09-28 | 2022-09-28_5a5865d:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-08-03 | 2022-08-03_ade94c4438_CN Data 2022-08-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-08-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-08-03_ade94c4438_CN Data 2022-08-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-08-03 | 2022-08-03_ade94c4:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-08-10 | 2022-08-10_98b74a3c6f_CN Data 2022-08-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-08-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-08-10_98b74a3c6f_CN Data 2022-08-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-08-10 | 2022-08-10_98b74a3:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-08-17 | 2022-08-17_a22f4fc8ec_CN Data 2022-08-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-08-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-08-17_a22f4fc8ec_CN Data 2022-08-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-08-17 | 2022-08-17_a22f4fc:   0%|          | 0.00/23.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-08-24 | 2022-08-24_0ebde7ba43_CN Data 2022-08-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-08-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-08-24_0ebde7ba43_CN Data 2022-08-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-08-24 | 2022-08-24_0ebde7b:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-08-31 | 2022-08-31_f6000466d4_CN Data 2022-08-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-08-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-08-31_f6000466d4_CN Data 2022-08-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-08-31 | 2022-08-31_f600046:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-07-06 | 2022-07-06_20e56e2e5a_CN Data 2022-07-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-07-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-07-06_20e56e2e5a_CN Data 2022-07-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-07-06 | 2022-07-06_20e56e2:   0%|          | 0.00/23.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-07-13 | 2022-07-13_5dbce47a7b_CN Data 2022-07-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-07-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-07-13_5dbce47a7b_CN Data 2022-07-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-07-13 | 2022-07-13_5dbce47:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-07-20 | 2022-07-20_8e4c5d06e7_CN Data 2022-07-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-07-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-07-20_8e4c5d06e7_CN Data 2022-07-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-07-20 | 2022-07-20_8e4c5d0:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-07-27 | 2022-07-27_38639323a8_CN Data 2022-07-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-07-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-07-27_38639323a8_CN Data 2022-07-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-07-27 | 2022-07-27_3863932:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-06-01 | 2022-06-01_4af2e87b2f_CN Data 2022-06-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-06-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-06-01_4af2e87b2f_CN Data 2022-06-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-06-01 | 2022-06-01_4af2e87:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-06-08 | 2022-06-08_a549ad6647_CN Data 2022-06-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-06-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-06-08_a549ad6647_CN Data 2022-06-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-06-08 | 2022-06-08_a549ad6:   0%|          | 0.00/24.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-06-15 | 2022-06-15_88929bc87b_CN Data 2022-06-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-06-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-06-15_88929bc87b_CN Data 2022-06-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-06-15 | 2022-06-15_88929bc:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-06-22 | 2022-06-22_a2a216f651_CN Data 2022-06-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-06-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-06-22_a2a216f651_CN Data 2022-06-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-06-22 | 2022-06-22_a2a216f:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-06-29 | 2022-06-29_1aed1bf674_CN Data 2022-06-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-06-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-06-29_1aed1bf674_CN Data 2022-06-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-06-29 | 2022-06-29_1aed1bf:   0%|          | 0.00/23.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-05-04 | 2022-05-04_d0e79358ef_CN Data 2022-05-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-05-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-05-04_d0e79358ef_CN Data 2022-05-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-05-04 | 2022-05-04_d0e7935:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-05-11 | 2022-05-11_ce8ca1ac11_CN Data 2022-05-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-05-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-05-11_ce8ca1ac11_CN Data 2022-05-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-05-11 | 2022-05-11_ce8ca1a:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-05-18 | 2022-05-18_2459c31e87_CN Data 2022-05-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-05-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-05-18_2459c31e87_CN Data 2022-05-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-05-18 | 2022-05-18_2459c31:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-05-25 | 2022-05-25_3e1ea9305f_CN Data 2022-05-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-05-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-05-25_3e1ea9305f_CN Data 2022-05-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-05-25 | 2022-05-25_3e1ea93:   0%|          | 0.00/22.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-04-06 | 2022-04-06_2faed13ff9_CN Data 2022-04-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-04-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-04-06_2faed13ff9_CN Data 2022-04-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-04-06 | 2022-04-06_2faed13:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-04-13 | 2022-04-13_a2676fb6fa_CN Data 2022-04-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-04-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-04-13_a2676fb6fa_CN Data 2022-04-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-04-13 | 2022-04-13_a2676fb:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-04-20 | 2022-04-20_1fe113c7b4_CN Data 2022-04-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-04-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-04-20_1fe113c7b4_CN Data 2022-04-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-04-20 | 2022-04-20_1fe113c:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-04-27 | 2022-04-27_52bffbf61a_CN Data 2022-04-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-04-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-04-27_52bffbf61a_CN Data 2022-04-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-04-27 | 2022-04-27_52bffbf:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-03-02 | 2022-03-02_3a60f8e2a8_CN Data 2022-03-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-03-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-03-02_3a60f8e2a8_CN Data 2022-03-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-03-02 | 2022-03-02_3a60f8e:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-03-09 | 2022-03-09_85da5cfead_CN Data 2022-03-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-03-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-03-09_85da5cfead_CN Data 2022-03-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-03-09 | 2022-03-09_85da5cf:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-03-16 | 2022-03-16_6fcf4b0800_CN Data 2022-03-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-03-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-03-16_6fcf4b0800_CN Data 2022-03-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-03-16 | 2022-03-16_6fcf4b0:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-03-23 | 2022-03-23_36876dff18_CN Data 2022-03-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-03-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-03-23_36876dff18_CN Data 2022-03-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-03-23 | 2022-03-23_36876df:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-03-30 | 2022-03-30_3a5afd7b4a_CN Data 2022-03-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-03-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-03-30_3a5afd7b4a_CN Data 2022-03-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-03-30 | 2022-03-30_3a5afd7:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-02-02 | 2022-02-02_75b4460a46_CN Data 2022-02-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-02-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-02-02_75b4460a46_CN Data 2022-02-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-02-02 | 2022-02-02_75b4460:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-02-09 | 2022-02-09_e252fd6abd_CN Data 2022-02-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-02-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-02-09_e252fd6abd_CN Data 2022-02-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-02-09 | 2022-02-09_e252fd6:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-02-16 | 2022-02-16_7eda152877_CN Data 2022-02-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-02-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-02-16_7eda152877_CN Data 2022-02-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-02-16 | 2022-02-16_7eda152:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-02-23 | 2022-02-23_f50b7fd6a1_CN Data 2022-02-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-02-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-02-23_f50b7fd6a1_CN Data 2022-02-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-02-23 | 2022-02-23_f50b7fd:   0%|          | 0.00/140k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-01-05 | 2022-01-05_3af572a9b5_CN Data 2022-01-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-01-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-01-05_3af572a9b5_CN Data 2022-01-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-01-05 | 2022-01-05_3af572a:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-01-12 | 2022-01-12_949db78fa0_CN Data 2022-01-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-01-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-01-12_949db78fa0_CN Data 2022-01-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-01-12 | 2022-01-12_949db78:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-01-19 | 2022-01-19_9848b5d6ca_CN Data 2022-01-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-01-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-01-19_9848b5d6ca_CN Data 2022-01-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-01-19 | 2022-01-19_9848b5d:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2022-01-26 | 2022-01-26_b98ee8ac35_CN Data 2022-01-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202022-01-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2022\xlsx\2022-01-26_b98ee8ac35_CN Data 2022-01-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2022-01-26 | 2022-01-26_b98ee8a:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-12-01 | 2021-12-01_884dd8b01b_CN Data 2021-12-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-12-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-12-01_884dd8b01b_CN Data 2021-12-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-12-01 | 2021-12-01_884dd8b:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-12-08 | 2021-12-08_64a56ea853_CN Data 2021-12-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-12-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-12-08_64a56ea853_CN Data 2021-12-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-12-08 | 2021-12-08_64a56ea:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-12-15 | 2021-12-15_da4bfabf22_CN Data 2021-12-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-12-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-12-15_da4bfabf22_CN Data 2021-12-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-12-15 | 2021-12-15_da4bfab:   0%|          | 0.00/22.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-12-22 | 2021-12-22_51aed7c72f_CN Data 2021-12-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-12-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-12-22_51aed7c72f_CN Data 2021-12-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-12-22 | 2021-12-22_51aed7c:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-12-29 | 2021-12-29_047aad9e05_CN Data 2021-12-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-12-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-12-29_047aad9e05_CN Data 2021-12-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-12-29 | 2021-12-29_047aad9:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-11-03 | 2021-11-03_5806e33e22_CN Data 2021-11-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-11-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-11-03_5806e33e22_CN Data 2021-11-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-11-03 | 2021-11-03_5806e33:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-11-10 | 2021-11-10_041edf3e3e_CN Data 2021-11-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-11-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-11-10_041edf3e3e_CN Data 2021-11-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-11-10 | 2021-11-10_041edf3:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-11-17 | 2021-11-17_21934a7001_CN Data 2021-11-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-11-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-11-17_21934a7001_CN Data 2021-11-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-11-17 | 2021-11-17_21934a7:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-11-24 | 2021-11-24_ab26d8c917_CN Data 2021-11-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-11-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-11-24_ab26d8c917_CN Data 2021-11-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-11-24 | 2021-11-24_ab26d8c:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-10-06 | 2021-10-06_941b58bc63_CN Data 2021-10-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-10-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-10-06_941b58bc63_CN Data 2021-10-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-10-06 | 2021-10-06_941b58b:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-10-13 | 2021-10-13_a586ddc53c_CN Data 2021-10-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-10-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-10-13_a586ddc53c_CN Data 2021-10-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-10-13 | 2021-10-13_a586ddc:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-10-20 | 2021-10-20_cfd089826d_CN Data 2021-10-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-10-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-10-20_cfd089826d_CN Data 2021-10-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-10-20 | 2021-10-20_cfd0898:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-10-27 | 2021-10-27_0ca0f40f58_CN Data 2021-10-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-10-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-10-27_0ca0f40f58_CN Data 2021-10-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-10-27 | 2021-10-27_0ca0f40:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-09-01 | 2021-09-01_0c3d8e03be_CN Data 2021-09-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-09-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-09-01_0c3d8e03be_CN Data 2021-09-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-09-01 | 2021-09-01_0c3d8e0:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-09-08 | 2021-09-08_a0c997705c_CN Data 2021-09-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-09-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-09-08_a0c997705c_CN Data 2021-09-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-09-08 | 2021-09-08_a0c9977:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-09-15 | 2021-09-15_a3fcc6b435_CN Data 2021-09-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-09-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-09-15_a3fcc6b435_CN Data 2021-09-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-09-15 | 2021-09-15_a3fcc6b:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-09-22 | 2021-09-22_1b0050ef24_CN Data 2021-09-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-09-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-09-22_1b0050ef24_CN Data 2021-09-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-09-22 | 2021-09-22_1b0050e:   0%|          | 0.00/22.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-09-29 | 2021-09-29_5754d7060e_CN Data 2021-09-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-09-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-09-29_5754d7060e_CN Data 2021-09-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-09-29 | 2021-09-29_5754d70:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-08-04 | 2021-08-04_a04770c1d5_CN Data 2021-08-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-08-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-08-04_a04770c1d5_CN Data 2021-08-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-08-04 | 2021-08-04_a04770c:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-08-11 | 2021-08-11_c3ae29bd88_CN Data 2021-08-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-08-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-08-11_c3ae29bd88_CN Data 2021-08-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-08-11 | 2021-08-11_c3ae29b:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-08-18 | 2021-08-18_6d93a94bfb_CN Data 2021-08-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-08-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-08-18_6d93a94bfb_CN Data 2021-08-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-08-18 | 2021-08-18_6d93a94:   0%|          | 0.00/23.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-08-25 | 2021-08-25_12aca390bf_CN Data 2021-08-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-08-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-08-25_12aca390bf_CN Data 2021-08-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-08-25 | 2021-08-25_12aca39:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-07-07 | 2021-07-07_3423c6acc7_CN Data 2021-07-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-07-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-07-07_3423c6acc7_CN Data 2021-07-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-07-07 | 2021-07-07_3423c6a:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-07-14 | 2021-07-14_ae99ad7231_CN Data 2021-07-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-07-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-07-14_ae99ad7231_CN Data 2021-07-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-07-14 | 2021-07-14_ae99ad7:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-07-21 | 2021-07-21_0909fd39c1_CN Data 2021-07-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-07-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-07-21_0909fd39c1_CN Data 2021-07-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-07-21 | 2021-07-21_0909fd3:   0%|          | 0.00/23.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-07-28 | 2021-07-28_26b41b6e8d_CN Data 2021-07-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-07-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-07-28_26b41b6e8d_CN Data 2021-07-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-07-28 | 2021-07-28_26b41b6:   0%|          | 0.00/21.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-06-02 | 2021-06-02_b47382ae6d_CN Data 2021-06-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-06-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-06-02_b47382ae6d_CN Data 2021-06-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-06-02 | 2021-06-02_b47382a:   0%|          | 0.00/117k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-06-09 | 2021-06-09_12ba4a1c93_CN Data 2021-06-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-06-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-06-09_12ba4a1c93_CN Data 2021-06-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-06-09 | 2021-06-09_12ba4a1:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-06-16 | 2021-06-16_9a68d7f2f5_CN Data 2021-06-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-06-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-06-16_9a68d7f2f5_CN Data 2021-06-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-06-16 | 2021-06-16_9a68d7f:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-06-23 | 2021-06-23_8c70875204_CN Data 2021-06-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-06-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-06-23_8c70875204_CN Data 2021-06-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-06-23 | 2021-06-23_8c70875:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-06-30 | 2021-06-30_6a050b2498_CN Data 2021-06-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-06-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-06-30_6a050b2498_CN Data 2021-06-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-06-30 | 2021-06-30_6a050b2:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-05-05 | 2021-05-05_fc9c4883c0_CN Data 2021-05-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-05-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-05-05_fc9c4883c0_CN Data 2021-05-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-05-05 | 2021-05-05_fc9c488:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-05-12 | 2021-05-12_c84407da40_CN Data 2021-05-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-05-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-05-12_c84407da40_CN Data 2021-05-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-05-12 | 2021-05-12_c84407d:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-05-19 | 2021-05-19_d7aac2421f_CN Data 2021-05-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-05-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-05-19_d7aac2421f_CN Data 2021-05-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-05-19 | 2021-05-19_d7aac24:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-05-26 | 2021-05-26_b6602c5c81_CN Data 2021-05-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-05-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-05-26_b6602c5c81_CN Data 2021-05-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-05-26 | 2021-05-26_b6602c5:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-04-07 | 2021-04-07_a86bc8d67d_CN Data 2021-04-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-04-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-04-07_a86bc8d67d_CN Data 2021-04-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-04-07 | 2021-04-07_a86bc8d:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-04-14 | 2021-04-14_8c280945a7_CN Data 2021-04-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-04-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-04-14_8c280945a7_CN Data 2021-04-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-04-14 | 2021-04-14_8c28094:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-04-21 | 2021-04-21_c2e626e3c7_CN Data 2021-04-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-04-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-04-21_c2e626e3c7_CN Data 2021-04-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-04-21 | 2021-04-21_c2e626e:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-04-28 | 2021-04-28_11d46589ae_CN Data 2021-04-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-04-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-04-28_11d46589ae_CN Data 2021-04-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-04-28 | 2021-04-28_11d4658:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-03-03 | 2021-03-03_cf579e43cf_CN Data 2021-03-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-03-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-03-03_cf579e43cf_CN Data 2021-03-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-03-03 | 2021-03-03_cf579e4:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-03-10 | 2021-03-10_48bb62d3fd_CN Data 2021-03-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-03-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-03-10_48bb62d3fd_CN Data 2021-03-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-03-10 | 2021-03-10_48bb62d:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-03-17 | 2021-03-17_fc9ddaf5b5_CN Data 2021-03-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-03-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-03-17_fc9ddaf5b5_CN Data 2021-03-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-03-17 | 2021-03-17_fc9ddaf:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-03-24 | 2021-03-24_019f596723_CN Data 2021-03-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-03-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-03-24_019f596723_CN Data 2021-03-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-03-24 | 2021-03-24_019f596:   0%|          | 0.00/112k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-03-31 | 2021-03-31_d4f6e68556_CN Data 2021-03-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-03-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-03-31_d4f6e68556_CN Data 2021-03-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-03-31 | 2021-03-31_d4f6e68:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-02-03 | 2021-02-03_8f8b0822a1_CN Data 2021-02-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-02-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-02-03_8f8b0822a1_CN Data 2021-02-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-02-03 | 2021-02-03_8f8b082:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-02-10 | 2021-02-10_800ad6def3_CN Data 2021-02-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-02-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-02-10_800ad6def3_CN Data 2021-02-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-02-10 | 2021-02-10_800ad6d:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-02-17 | 2021-02-17_016f8e8ed0_CN Data 2021-02-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-02-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-02-17_016f8e8ed0_CN Data 2021-02-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-02-17 | 2021-02-17_016f8e8:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-02-24 | 2021-02-24_6cfb061c09_CN Data 2021-02-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-02-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-02-24_6cfb061c09_CN Data 2021-02-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-02-24 | 2021-02-24_6cfb061:   0%|          | 0.00/110k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-01-06 | 2021-01-06_80a314be11_CN Data 2021-01-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-01-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-01-06_80a314be11_CN Data 2021-01-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-01-06 | 2021-01-06_80a314b:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-01-13 | 2021-01-13_217c08eb89_CN Data 2021-01-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-01-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-01-13_217c08eb89_CN Data 2021-01-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-01-13 | 2021-01-13_217c08e:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-01-20 | 2021-01-20_8fbbae8367_CN Data 2021-01-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-01-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-01-20_8fbbae8367_CN Data 2021-01-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-01-20 | 2021-01-20_8fbbae8:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2021-01-27 | 2021-01-27_ece2f456dd_CN Data 2021-01-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202021-01-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2021\xlsx\2021-01-27_ece2f456dd_CN Data 2021-01-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2021-01-27 | 2021-01-27_ece2f45:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-12-02 | 2020-12-02_d543869fef_CN Data 2020-12-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-12-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-12-02_d543869fef_CN Data 2020-12-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-12-02 | 2020-12-02_d543869:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-12-09 | 2020-12-09_30f4391d63_CN Data 2020-12-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-12-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-12-09_30f4391d63_CN Data 2020-12-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-12-09 | 2020-12-09_30f4391:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-12-16 | 2020-12-16_784dfbf978_CN Data 2020-12-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-12-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-12-16_784dfbf978_CN Data 2020-12-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-12-16 | 2020-12-16_784dfbf:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-12-23 | 2020-12-23_f419414f55_CN Data 2020-12-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-12-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-12-23_f419414f55_CN Data 2020-12-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-12-23 | 2020-12-23_f419414:   0%|          | 0.00/22.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-12-30 | 2020-12-30_a8e63e8bda_CN Data 2020-12-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-12-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-12-30_a8e63e8bda_CN Data 2020-12-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-12-30 | 2020-12-30_a8e63e8:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-11-04 | 2020-11-04_cfbc0d9226_CN Data 2020-11-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-11-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-11-04_cfbc0d9226_CN Data 2020-11-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-11-04 | 2020-11-04_cfbc0d9:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-11-11 | 2020-11-11_96bf23efc7_CN Data 2020-11-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-11-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-11-11_96bf23efc7_CN Data 2020-11-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-11-11 | 2020-11-11_96bf23e:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-11-18 | 2020-11-18_b8c16aa268_CN Data 2020-11-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-11-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-11-18_b8c16aa268_CN Data 2020-11-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-11-18 | 2020-11-18_b8c16aa:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-11-25 | 2020-11-25_150fd81e7a_CN Data 2020-11-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-11-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-11-25_150fd81e7a_CN Data 2020-11-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-11-25 | 2020-11-25_150fd81:   0%|          | 0.00/22.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-10-07 | 2020-10-07_110c8de979_CN Data 2020-10-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-10-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-10-07_110c8de979_CN Data 2020-10-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-10-07 | 2020-10-07_110c8de:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-10-14 | 2020-10-14_d1a4e92c01_CN Data 2020-10-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-10-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-10-14_d1a4e92c01_CN Data 2020-10-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-10-14 | 2020-10-14_d1a4e92:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-10-21 | 2020-10-21_1000b2fb83_CN Data 2020-10-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-10-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-10-21_1000b2fb83_CN Data 2020-10-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-10-21 | 2020-10-21_1000b2f:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-10-28 | 2020-10-28_c0b8d242a9_CN Data 2020-10-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-10-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-10-28_c0b8d242a9_CN Data 2020-10-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-10-28 | 2020-10-28_c0b8d24:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-09-02 | 2020-09-02_0a0db5515d_CN Data 2020-09-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-09-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-09-02_0a0db5515d_CN Data 2020-09-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-09-02 | 2020-09-02_0a0db55:   0%|          | 0.00/26.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-09-09 | 2020-09-09_7ffe58e220_CN Data 2020-09-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-09-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-09-09_7ffe58e220_CN Data 2020-09-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-09-09 | 2020-09-09_7ffe58e:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-09-16 | 2020-09-16_f5459d2ae0_CN Data 2020-09-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-09-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-09-16_f5459d2ae0_CN Data 2020-09-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-09-16 | 2020-09-16_f5459d2:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-09-23 | 2020-09-23_ae0fc3ea4a_CN Data 2020-09-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-09-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-09-23_ae0fc3ea4a_CN Data 2020-09-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-09-23 | 2020-09-23_ae0fc3e:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-09-30 | 2020-09-30_d07e83af9d_CN Data 2020-09-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-09-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-09-30_d07e83af9d_CN Data 2020-09-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-09-30 | 2020-09-30_d07e83a:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-08-05 | 2020-08-05_6ac5da295d_CN Data 2020-08-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-08-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-08-05_6ac5da295d_CN Data 2020-08-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-08-05 | 2020-08-05_6ac5da2:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-08-12 | 2020-08-12_69e9e3ce8e_CN Data 2020-08-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-08-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-08-12_69e9e3ce8e_CN Data 2020-08-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-08-12 | 2020-08-12_69e9e3c:   0%|          | 0.00/22.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-08-19 | 2020-08-19_8c714ba116_CN Data 2020-08-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-08-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-08-19_8c714ba116_CN Data 2020-08-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-08-19 | 2020-08-19_8c714ba:   0%|          | 0.00/99.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-08-26 | 2020-08-26_20a5816c91_CN Data 2020-08-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-08-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-08-26_20a5816c91_CN Data 2020-08-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-08-26 | 2020-08-26_20a5816:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-07-01 | 2020-07-01_8e88ff994b_cn_data_2020-07-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-07-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-07-01_8e88ff994b_cn_data_2020-07-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-07-01 | 2020-07-01_8e88ff9:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-07-08 | 2020-07-08_1f01026ff7_cn_data_2020-07-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-07-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-07-08_1f01026ff7_cn_data_2020-07-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-07-08 | 2020-07-08_1f01026:   0%|          | 0.00/95.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-07-15 | 2020-07-15_c49560906f_cn_data_2020-07-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-07-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-07-15_c49560906f_cn_data_2020-07-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-07-15 | 2020-07-15_c495609:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-07-22 | 2020-07-22_8601473052_cn_data_2020-07-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-07-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-07-22_8601473052_cn_data_2020-07-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-07-22 | 2020-07-22_8601473:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-07-29 | 2020-07-29_5d1628bfaf_CN Data 2020-07-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/CN%20Data%202020-07-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-07-29_5d1628bfaf_CN Data 2020-07-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-07-29 | 2020-07-29_5d1628b:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-06-03 | 2020-06-03_2d4c058726_cn_data_2020-06-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-06-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-06-03_2d4c058726_cn_data_2020-06-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-06-03 | 2020-06-03_2d4c058:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-06-10 | 2020-06-10_14733b96f3_cn_data_2020-06-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-06-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-06-10_14733b96f3_cn_data_2020-06-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-06-10 | 2020-06-10_14733b9:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-06-17 | 2020-06-17_fe6d18df64_cn_data_2020-06-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-06-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-06-17_fe6d18df64_cn_data_2020-06-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-06-17 | 2020-06-17_fe6d18d:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-06-24 | 2020-06-24_6ee4f80bef_cn_data_2020-06-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-06-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-06-24_6ee4f80bef_cn_data_2020-06-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-06-24 | 2020-06-24_6ee4f80:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-05-06 | 2020-05-06_8bfbfe897b_cn_data_2020-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-05-06_8bfbfe897b_cn_data_2020-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-05-06 | 2020-05-06_8bfbfe8:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-05-13 | 2020-05-13_9b49bb55aa_cn_data_2020-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-05-13_9b49bb55aa_cn_data_2020-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-05-13 | 2020-05-13_9b49bb5:   0%|          | 0.00/22.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-05-20 | 2020-05-20_7233076c36_cn_data_2020-05-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-05-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-05-20_7233076c36_cn_data_2020-05-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-05-20 | 2020-05-20_7233076:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-05-27 | 2020-05-27_a39660cf7b_cn_data_2020-05-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-05-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-05-27_a39660cf7b_cn_data_2020-05-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-05-27 | 2020-05-27_a39660c:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-04-01 | 2020-04-01_5a9c9358a6_cn_data_2020-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-04-01_5a9c9358a6_cn_data_2020-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-04-01 | 2020-04-01_5a9c935:   0%|          | 0.00/22.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-04-08 | 2020-04-08_5be9138304_cn_data_2020-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-04-08_5be9138304_cn_data_2020-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-04-08 | 2020-04-08_5be9138:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-04-15 | 2020-04-15_868ec29f69_cn_data_2020-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-04-15_868ec29f69_cn_data_2020-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-04-15 | 2020-04-15_868ec29:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-04-22 | 2020-04-22_318aacda0d_cn_data_2020-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-04-22_318aacda0d_cn_data_2020-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-04-22 | 2020-04-22_318aacd:   0%|          | 0.00/22.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-04-29 | 2020-04-29_20e71795e4_cn_data_2020-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-04-29_20e71795e4_cn_data_2020-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-04-29 | 2020-04-29_20e7179:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-03-04 | 2020-03-04_c9bc436a0c_cn_data_2020-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-03-04_c9bc436a0c_cn_data_2020-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-03-04 | 2020-03-04_c9bc436:   0%|          | 0.00/22.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-03-11 | 2020-03-11_39eac2368b_cn_data_2020-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-03-11_39eac2368b_cn_data_2020-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-03-11 | 2020-03-11_39eac23:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-03-18 | 2020-03-18_319c531d02_cn_data_2020-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-03-18_319c531d02_cn_data_2020-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-03-18 | 2020-03-18_319c531:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-03-25 | 2020-03-25_5f5f69bcaa_cn_data_2020-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-03-25_5f5f69bcaa_cn_data_2020-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-03-25 | 2020-03-25_5f5f69b:   0%|          | 0.00/22.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-02-05 | 2020-02-05_7eb602d6cc_cn_data_2020-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-02-05_7eb602d6cc_cn_data_2020-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-02-05 | 2020-02-05_7eb602d:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-02-12 | 2020-02-12_de8ad9b8c3_cn_data_2020-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-02-12_de8ad9b8c3_cn_data_2020-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-02-12 | 2020-02-12_de8ad9b:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-02-19 | 2020-02-19_152a2df971_cn_data_2020-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-02-19_152a2df971_cn_data_2020-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-02-19 | 2020-02-19_152a2df:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-02-26 | 2020-02-26_c82a68fa46_cn_data_2020-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-02-26_c82a68fa46_cn_data_2020-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-02-26 | 2020-02-26_c82a68f:   0%|          | 0.00/87.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-01-01 | 2020-01-01_4708d5beec_cn_data_2020-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-01-01_4708d5beec_cn_data_2020-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-01-01 | 2020-01-01_4708d5b:   0%|          | 0.00/21.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-01-08 | 2020-01-08_79b2960b15_cn_data_2020-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-01-08_79b2960b15_cn_data_2020-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-01-08 | 2020-01-08_79b2960:   0%|          | 0.00/21.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-01-15 | 2020-01-15_13c1f290d7_cn_data_2020-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-01-15_13c1f290d7_cn_data_2020-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-01-15 | 2020-01-15_13c1f29:   0%|          | 0.00/21.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-01-22 | 2020-01-22_238df5b23a_cn_data_2020-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-01-22_238df5b23a_cn_data_2020-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-01-22 | 2020-01-22_238df5b:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cn | 2020-01-29 | 2020-01-29_925dc60d05_cn_data_2020-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CN/cn_data_2020-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cn\2020\xlsx\2020-01-29_925dc60d05_cn_data_2020-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cn | 2020-01-29 | 2020-01-29_925dc60:   0%|          | 0.00/85.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-05-07 | 2025-05-07_beecf1e471_CP Data 2025-05-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-05-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-05-07_beecf1e471_CP Data 2025-05-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-05-07 | 2025-05-07_beecf1e:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-05-14 | 2025-05-14_47862fd494_CP Data 2025-05-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-05-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-05-14_47862fd494_CP Data 2025-05-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-05-14 | 2025-05-14_47862fd:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-05-21 | 2025-05-21_19e5ddde49_CP Data 2025-05-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-05-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-05-21_19e5ddde49_CP Data 2025-05-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-05-21 | 2025-05-21_19e5ddd:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-05-28 | 2025-05-28_9739cbc4a7_CP Data 2025-05-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-05-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-05-28_9739cbc4a7_CP Data 2025-05-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-05-28 | 2025-05-28_9739cbc:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-04-02 | 2025-04-02_74421bc212_CP Data 2025-04-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-04-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-04-02_74421bc212_CP Data 2025-04-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-04-02 | 2025-04-02_74421bc:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-04-09 | 2025-04-09_c4408250a6_CP Data 2025-04-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-04-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-04-09_c4408250a6_CP Data 2025-04-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-04-09 | 2025-04-09_c440825:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-04-16 | 2025-04-16_bf6e957087_CP Data 2025-04-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-04-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-04-16_bf6e957087_CP Data 2025-04-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-04-16 | 2025-04-16_bf6e957:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-04-23 | 2025-04-23_5479b3b776_CP Data 2025-04-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-04-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-04-23_5479b3b776_CP Data 2025-04-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-04-23 | 2025-04-23_5479b3b:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-04-30 | 2025-04-30_631486173c_CP Data 2025-04-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-04-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-04-30_631486173c_CP Data 2025-04-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-04-30 | 2025-04-30_6314861:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-03-05 | 2025-03-05_57e6ef9c46_CP Data 2025-03-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-03-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-03-05_57e6ef9c46_CP Data 2025-03-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-03-05 | 2025-03-05_57e6ef9:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-03-12 | 2025-03-12_1b98f323c1_CP Data 2025-03-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-03-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-03-12_1b98f323c1_CP Data 2025-03-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-03-12 | 2025-03-12_1b98f32:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-03-19 | 2025-03-19_9c87ae38f7_CP Data 2025-03-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-03-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-03-19_9c87ae38f7_CP Data 2025-03-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-03-19 | 2025-03-19_9c87ae3:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-03-26 | 2025-03-26_b0e8166f48_CP Data 2025-03-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-03-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-03-26_b0e8166f48_CP Data 2025-03-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-03-26 | 2025-03-26_b0e8166:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-02-05 | 2025-02-05_b21d8d20bf_CP Data 2025-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-02-05_b21d8d20bf_CP Data 2025-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-02-05 | 2025-02-05_b21d8d2:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-02-12 | 2025-02-12_ff9033bbbe_CP Data 2025-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-02-12_ff9033bbbe_CP Data 2025-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-02-12 | 2025-02-12_ff9033b:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-02-19 | 2025-02-19_72b6dd8a94_CP Data 2025-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-02-19_72b6dd8a94_CP Data 2025-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-02-19 | 2025-02-19_72b6dd8:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-02-26 | 2025-02-26_0f90807a3a_CP Data 2025-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-02-26_0f90807a3a_CP Data 2025-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-02-26 | 2025-02-26_0f90807:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-01-01 | 2025-01-01_0196346d31_CP Data 2025-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-01-01_0196346d31_CP Data 2025-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-01-01 | 2025-01-01_0196346:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-01-08 | 2025-01-08_42eefe533f_CP Data 2025-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-01-08_42eefe533f_CP Data 2025-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-01-08 | 2025-01-08_42eefe5:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-01-15 | 2025-01-15_b8bb6f1822_CP Data 2025-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-01-15_b8bb6f1822_CP Data 2025-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-01-15 | 2025-01-15_b8bb6f1:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-01-22 | 2025-01-22_daa3ca6198_CP Data 2025-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-01-22_daa3ca6198_CP Data 2025-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-01-22 | 2025-01-22_daa3ca6:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2025-01-29 | 2025-01-29_41aaa84bdf_CP Data 2025-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202025-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2025\xlsx\2025-01-29_41aaa84bdf_CP Data 2025-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2025-01-29 | 2025-01-29_41aaa84:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-12-04 | 2024-12-04_b763d0a307_CP Data 2024-12-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-12-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-12-04_b763d0a307_CP Data 2024-12-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-12-04 | 2024-12-04_b763d0a:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-12-11 | 2024-12-11_2973b03f7e_CP Data 2024-12-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-12-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-12-11_2973b03f7e_CP Data 2024-12-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-12-11 | 2024-12-11_2973b03:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-12-18 | 2024-12-18_0c658be373_CP Data 2024-12-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-12-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-12-18_0c658be373_CP Data 2024-12-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-12-18 | 2024-12-18_0c658be:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-12-25 | 2024-12-25_b6eee69aef_CP Data 2024-12-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-12-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-12-25_b6eee69aef_CP Data 2024-12-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-12-25 | 2024-12-25_b6eee69:   0%|          | 0.00/43.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-11-06 | 2024-11-06_cfd042402c_CP Data 2024-11-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-11-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-11-06_cfd042402c_CP Data 2024-11-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-11-06 | 2024-11-06_cfd0424:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-11-13 | 2024-11-13_87fb472407_CP Data 2024-11-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-11-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-11-13_87fb472407_CP Data 2024-11-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-11-13 | 2024-11-13_87fb472:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-11-20 | 2024-11-20_49bf8323a9_CP Data 2024-11-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-11-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-11-20_49bf8323a9_CP Data 2024-11-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-11-20 | 2024-11-20_49bf832:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-11-27 | 2024-11-27_191c85157f_CP Data 2024-11-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-11-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-11-27_191c85157f_CP Data 2024-11-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-11-27 | 2024-11-27_191c851:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-10-02 | 2024-10-02_847ad61f5c_CP Data 2024-10-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-10-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-10-02_847ad61f5c_CP Data 2024-10-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-10-02 | 2024-10-02_847ad61:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-10-09 | 2024-10-09_3672fec2e3_CP Data 2024-10-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-10-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-10-09_3672fec2e3_CP Data 2024-10-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-10-09 | 2024-10-09_3672fec:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-10-16 | 2024-10-16_cc2e45c442_CP Data 2024-10-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-10-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-10-16_cc2e45c442_CP Data 2024-10-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-10-16 | 2024-10-16_cc2e45c:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-10-23 | 2024-10-23_03d02dbf70_CP Data 2024-10-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-10-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-10-23_03d02dbf70_CP Data 2024-10-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-10-23 | 2024-10-23_03d02db:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-10-30 | 2024-10-30_15bb1045c1_CP Data 2024-10-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-10-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-10-30_15bb1045c1_CP Data 2024-10-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-10-30 | 2024-10-30_15bb104:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-09-04 | 2024-09-04_deffd6536b_CP Data 2024-09-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-09-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-09-04_deffd6536b_CP Data 2024-09-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-09-04 | 2024-09-04_deffd65:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-09-11 | 2024-09-11_271c3f7ee4_CP Data 2024-09-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-09-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-09-11_271c3f7ee4_CP Data 2024-09-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-09-11 | 2024-09-11_271c3f7:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-09-18 | 2024-09-18_fb183db748_CP Data 2024-09-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-09-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-09-18_fb183db748_CP Data 2024-09-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-09-18 | 2024-09-18_fb183db:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-09-25 | 2024-09-25_b98ad85670_CP Data 2024-09-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-09-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-09-25_b98ad85670_CP Data 2024-09-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-09-25 | 2024-09-25_b98ad85:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-08-07 | 2024-08-07_0459b02fba_CP Data 2024-08-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-08-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-08-07_0459b02fba_CP Data 2024-08-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-08-07 | 2024-08-07_0459b02:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-08-14 | 2024-08-14_4d08e0c073_CP Data 2024-08-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-08-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-08-14_4d08e0c073_CP Data 2024-08-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-08-14 | 2024-08-14_4d08e0c:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-08-21 | 2024-08-21_6b7eea3d7a_CP Data 2024-08-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-08-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-08-21_6b7eea3d7a_CP Data 2024-08-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-08-21 | 2024-08-21_6b7eea3:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-08-28 | 2024-08-28_7f6290dfa2_CP Data 2024-08-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-08-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-08-28_7f6290dfa2_CP Data 2024-08-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-08-28 | 2024-08-28_7f6290d:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-07-03 | 2024-07-03_b05b9f8115_CP Data 2024-07-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-07-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-07-03_b05b9f8115_CP Data 2024-07-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-07-03 | 2024-07-03_b05b9f8:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-07-10 | 2024-07-10_f1ea4bae41_CP Data 2024-07-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-07-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-07-10_f1ea4bae41_CP Data 2024-07-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-07-10 | 2024-07-10_f1ea4ba:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-07-17 | 2024-07-17_dd77884f2a_CP Data 2024-07-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-07-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-07-17_dd77884f2a_CP Data 2024-07-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-07-17 | 2024-07-17_dd77884:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-07-24 | 2024-07-24_bf03498133_CP Data 2024-07-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-07-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-07-24_bf03498133_CP Data 2024-07-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-07-24 | 2024-07-24_bf03498:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-07-31 | 2024-07-31_1152d20b6b_CP Data 2024-07-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-07-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-07-31_1152d20b6b_CP Data 2024-07-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-07-31 | 2024-07-31_1152d20:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-06-05 | 2024-06-05_93c7c674f2_CP Data 2024-06-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-06-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-06-05_93c7c674f2_CP Data 2024-06-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-06-05 | 2024-06-05_93c7c67:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-06-12 | 2024-06-12_cf3b084f9c_CP Data 2024-06-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-06-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-06-12_cf3b084f9c_CP Data 2024-06-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-06-12 | 2024-06-12_cf3b084:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-06-19 | 2024-06-19_651a62ff52_CP Data 2024-06-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-06-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-06-19_651a62ff52_CP Data 2024-06-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-06-19 | 2024-06-19_651a62f:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-06-26 | 2024-06-26_da65d34ee0_CP Data 2024-06-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-06-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-06-26_da65d34ee0_CP Data 2024-06-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-06-26 | 2024-06-26_da65d34:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-05-01 | 2024-05-01_f6bdca59c1_CP Data 2024-05-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-05-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-05-01_f6bdca59c1_CP Data 2024-05-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-05-01 | 2024-05-01_f6bdca5:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-05-08 | 2024-05-08_bb5e2f1e7d_CP Data 2024-05-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-05-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-05-08_bb5e2f1e7d_CP Data 2024-05-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-05-08 | 2024-05-08_bb5e2f1:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-05-15 | 2024-05-15_94a49ba1b0_CP Data 2024-05-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-05-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-05-15_94a49ba1b0_CP Data 2024-05-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-05-15 | 2024-05-15_94a49ba:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-05-22 | 2024-05-22_1aec3d3a34_CP Data 2024-05-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-05-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-05-22_1aec3d3a34_CP Data 2024-05-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-05-22 | 2024-05-22_1aec3d3:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-05-29 | 2024-05-29_a99f0693dd_CP Data 2024-05-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-05-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-05-29_a99f0693dd_CP Data 2024-05-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-05-29 | 2024-05-29_a99f069:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-04-03 | 2024-04-03_2b051a3580_CP Data 2024-04-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-04-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-04-03_2b051a3580_CP Data 2024-04-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-04-03 | 2024-04-03_2b051a3:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-04-10 | 2024-04-10_93905512f6_CP Data 2024-04-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-04-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-04-10_93905512f6_CP Data 2024-04-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-04-10 | 2024-04-10_9390551:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-04-17 | 2024-04-17_fceaf7cdaa_CP Data 2024-04-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-04-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-04-17_fceaf7cdaa_CP Data 2024-04-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-04-17 | 2024-04-17_fceaf7c:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-04-24 | 2024-04-24_c1df591b1f_CP Data 2024-04-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-04-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-04-24_c1df591b1f_CP Data 2024-04-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-04-24 | 2024-04-24_c1df591:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-03-06 | 2024-03-06_5f28d76e0d_CP Data 2024-03-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-03-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-03-06_5f28d76e0d_CP Data 2024-03-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-03-06 | 2024-03-06_5f28d76:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-03-13 | 2024-03-13_78b8928734_CP Data 2024-03-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-03-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-03-13_78b8928734_CP Data 2024-03-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-03-13 | 2024-03-13_78b8928:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-03-20 | 2024-03-20_36262ac30c_CP Data 2024-03-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-03-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-03-20_36262ac30c_CP Data 2024-03-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-03-20 | 2024-03-20_36262ac:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-03-27 | 2024-03-27_ee8feace83_CP Data 2024-03-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-03-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-03-27_ee8feace83_CP Data 2024-03-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-03-27 | 2024-03-27_ee8feac:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-02-07 | 2024-02-07_41ad3a9ea5_CP Data 2024-02-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-02-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-02-07_41ad3a9ea5_CP Data 2024-02-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-02-07 | 2024-02-07_41ad3a9:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-02-14 | 2024-02-14_3cfa18542f_CP Data 2024-02-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-02-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-02-14_3cfa18542f_CP Data 2024-02-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-02-14 | 2024-02-14_3cfa185:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-02-21 | 2024-02-21_8e5b6696bd_CP Data 2024-02-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-02-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-02-21_8e5b6696bd_CP Data 2024-02-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-02-21 | 2024-02-21_8e5b669:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-02-28 | 2024-02-28_2fca4c7bd3_CP Data 2024-02-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-02-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-02-28_2fca4c7bd3_CP Data 2024-02-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-02-28 | 2024-02-28_2fca4c7:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-01-03 | 2024-01-03_cfa8a8bc0f_CP Data 2024-01-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-01-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-01-03_cfa8a8bc0f_CP Data 2024-01-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-01-03 | 2024-01-03_cfa8a8b:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-01-10 | 2024-01-10_16e6203b51_CP Data 2024-01-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-01-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-01-10_16e6203b51_CP Data 2024-01-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-01-10 | 2024-01-10_16e6203:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-01-17 | 2024-01-17_ec52f11019_CP Data 2024-01-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-01-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-01-17_ec52f11019_CP Data 2024-01-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-01-17 | 2024-01-17_ec52f11:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-01-24 | 2024-01-24_678c08d985_CP Data 2024-01-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-01-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-01-24_678c08d985_CP Data 2024-01-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-01-24 | 2024-01-24_678c08d:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2024-01-31 | 2024-01-31_b73b61ba39_CP Data 2024-01-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202024-01-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2024\xlsx\2024-01-31_b73b61ba39_CP Data 2024-01-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2024-01-31 | 2024-01-31_b73b61b:   0%|          | 0.00/44.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-12-06 | 2023-12-06_97ba9e6e67_CP Data 2023-12-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-12-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-12-06_97ba9e6e67_CP Data 2023-12-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-12-06 | 2023-12-06_97ba9e6:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-12-13 | 2023-12-13_dfc20e12af_CP Data 2023-12-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-12-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-12-13_dfc20e12af_CP Data 2023-12-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-12-13 | 2023-12-13_dfc20e1:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-12-20 | 2023-12-20_a680ff0101_CP Data 2023-12-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-12-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-12-20_a680ff0101_CP Data 2023-12-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-12-20 | 2023-12-20_a680ff0:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-12-27 | 2023-12-27_5f9ead4cc7_CP Data 2023-12-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-12-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-12-27_5f9ead4cc7_CP Data 2023-12-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-12-27 | 2023-12-27_5f9ead4:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-11-01 | 2023-11-01_44ba360fe3_CP Data 2023-11-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-11-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-11-01_44ba360fe3_CP Data 2023-11-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-11-01 | 2023-11-01_44ba360:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-11-08 | 2023-11-08_0476fdea53_CP Data 2023-11-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-11-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-11-08_0476fdea53_CP Data 2023-11-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-11-08 | 2023-11-08_0476fde:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-11-15 | 2023-11-15_bfc29e9fbf_CP Data 2023-11-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-11-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-11-15_bfc29e9fbf_CP Data 2023-11-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-11-15 | 2023-11-15_bfc29e9:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-11-22 | 2023-11-22_51ae347cf0_CP Data 2023-11-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-11-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-11-22_51ae347cf0_CP Data 2023-11-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-11-22 | 2023-11-22_51ae347:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-11-29 | 2023-11-29_7e138c05d3_CP Data 2023-11-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-11-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-11-29_7e138c05d3_CP Data 2023-11-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-11-29 | 2023-11-29_7e138c0:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-10-04 | 2023-10-04_375e23680d_CP Data 2023-10-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-10-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-10-04_375e23680d_CP Data 2023-10-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-10-04 | 2023-10-04_375e236:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-10-11 | 2023-10-11_1ae8414d7a_CP Data 2023-10-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-10-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-10-11_1ae8414d7a_CP Data 2023-10-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-10-11 | 2023-10-11_1ae8414:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-10-18 | 2023-10-18_e5d7195221_CP Data 2023-10-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-10-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-10-18_e5d7195221_CP Data 2023-10-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-10-18 | 2023-10-18_e5d7195:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-10-25 | 2023-10-25_cc55daa394_CP Data 2023-10-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-10-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-10-25_cc55daa394_CP Data 2023-10-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-10-25 | 2023-10-25_cc55daa:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-09-06 | 2023-09-06_dc0ef0a26e_CP Data 2023-09-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-09-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-09-06_dc0ef0a26e_CP Data 2023-09-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-09-06 | 2023-09-06_dc0ef0a:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-09-13 | 2023-09-13_029128780f_CP Data 2023-09-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-09-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-09-13_029128780f_CP Data 2023-09-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-09-13 | 2023-09-13_0291287:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-09-20 | 2023-09-20_d76ec9d2e3_CP Data 2023-09-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-09-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-09-20_d76ec9d2e3_CP Data 2023-09-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-09-20 | 2023-09-20_d76ec9d:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-09-27 | 2023-09-27_e8bb452ab0_CP Data 2023-09-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-09-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-09-27_e8bb452ab0_CP Data 2023-09-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-09-27 | 2023-09-27_e8bb452:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-08-02 | 2023-08-02_a9a01a0929_CP Data 2023-08-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-08-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-08-02_a9a01a0929_CP Data 2023-08-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-08-02 | 2023-08-02_a9a01a0:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-08-09 | 2023-08-09_3aa6066d79_CP Data 2023-08-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-08-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-08-09_3aa6066d79_CP Data 2023-08-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-08-09 | 2023-08-09_3aa6066:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-08-16 | 2023-08-16_3b95593a4f_CP Data 2023-08-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-08-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-08-16_3b95593a4f_CP Data 2023-08-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-08-16 | 2023-08-16_3b95593:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-08-23 | 2023-08-23_d214489c38_CP Data 2023-08-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-08-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-08-23_d214489c38_CP Data 2023-08-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-08-23 | 2023-08-23_d214489:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-08-30 | 2023-08-30_5f4fdac1b6_CP Data 2023-08-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-08-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-08-30_5f4fdac1b6_CP Data 2023-08-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-08-30 | 2023-08-30_5f4fdac:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-07-05 | 2023-07-05_6275e93793_CP Data 2023-07-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-07-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-07-05_6275e93793_CP Data 2023-07-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-07-05 | 2023-07-05_6275e93:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-07-12 | 2023-07-12_44e57f8e8b_CP Data 2023-07-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-07-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-07-12_44e57f8e8b_CP Data 2023-07-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-07-12 | 2023-07-12_44e57f8:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-07-19 | 2023-07-19_9bb75b5fb9_CP Data 2023-07-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-07-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-07-19_9bb75b5fb9_CP Data 2023-07-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-07-19 | 2023-07-19_9bb75b5:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-07-26 | 2023-07-26_c3ce07b87d_CP Data 2023-07-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-07-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-07-26_c3ce07b87d_CP Data 2023-07-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-07-26 | 2023-07-26_c3ce07b:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-06-07 | 2023-06-07_ae38d907f7_CP Data 2023-06-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-06-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-06-07_ae38d907f7_CP Data 2023-06-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-06-07 | 2023-06-07_ae38d90:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-06-14 | 2023-06-14_28132c664a_CP Data 2023-06-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-06-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-06-14_28132c664a_CP Data 2023-06-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-06-14 | 2023-06-14_28132c6:   0%|          | 0.00/41.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-06-21 | 2023-06-21_b77cf4c0a0_CP Data 2023-06-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-06-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-06-21_b77cf4c0a0_CP Data 2023-06-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-06-21 | 2023-06-21_b77cf4c:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-06-28 | 2023-06-28_9a1bd73457_CP Data 2023-06-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-06-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-06-28_9a1bd73457_CP Data 2023-06-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-06-28 | 2023-06-28_9a1bd73:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-05-03 | 2023-05-03_2792dc3e1a_CP Data 2023-05-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-05-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-05-03_2792dc3e1a_CP Data 2023-05-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-05-03 | 2023-05-03_2792dc3:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-05-10 | 2023-05-10_aa0af6d38e_CP Data 2023-05-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-05-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-05-10_aa0af6d38e_CP Data 2023-05-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-05-10 | 2023-05-10_aa0af6d:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-05-17 | 2023-05-17_c79d532223_CP Data 2023-05-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-05-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-05-17_c79d532223_CP Data 2023-05-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-05-17 | 2023-05-17_c79d532:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-05-24 | 2023-05-24_3a21f1b556_CP Data 2023-05-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-05-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-05-24_3a21f1b556_CP Data 2023-05-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-05-24 | 2023-05-24_3a21f1b:   0%|          | 0.00/43.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-05-31 | 2023-05-31_6649fd2ea7_CP Data 2023-05-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-05-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-05-31_6649fd2ea7_CP Data 2023-05-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-05-31 | 2023-05-31_6649fd2:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-04-05 | 2023-04-05_5cc89da223_CP Data 2023-04-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-04-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-04-05_5cc89da223_CP Data 2023-04-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-04-05 | 2023-04-05_5cc89da:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-04-12 | 2023-04-12_78b9c50edb_CP Data 2023-04-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-04-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-04-12_78b9c50edb_CP Data 2023-04-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-04-12 | 2023-04-12_78b9c50:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-04-19 | 2023-04-19_5e194d7b3f_CP Data 2023-04-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-04-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-04-19_5e194d7b3f_CP Data 2023-04-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-04-19 | 2023-04-19_5e194d7:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-04-26 | 2023-04-26_916103f26e_CP Data 2023-04-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-04-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-04-26_916103f26e_CP Data 2023-04-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-04-26 | 2023-04-26_916103f:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-03-01 | 2023-03-01_fdddf8000d_CP Data 2023-03-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-03-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-03-01_fdddf8000d_CP Data 2023-03-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-03-01 | 2023-03-01_fdddf80:   0%|          | 0.00/45.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-03-08 | 2023-03-08_e0d5faa06a_CP Data 2023-03-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-03-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-03-08_e0d5faa06a_CP Data 2023-03-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-03-08 | 2023-03-08_e0d5faa:   0%|          | 0.00/45.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-03-15 | 2023-03-15_74e1fe3b5f_CP Data 2023-03-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-03-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-03-15_74e1fe3b5f_CP Data 2023-03-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-03-15 | 2023-03-15_74e1fe3:   0%|          | 0.00/45.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-03-22 | 2023-03-22_a8cd5ee39b_CP Data 2023-03-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-03-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-03-22_a8cd5ee39b_CP Data 2023-03-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-03-22 | 2023-03-22_a8cd5ee:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-03-29 | 2023-03-29_3a1437528e_CP Data 2023-03-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-03-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-03-29_3a1437528e_CP Data 2023-03-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-03-29 | 2023-03-29_3a14375:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-02-01 | 2023-02-01_7a5537e61d_CP Data 2023-02-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-02-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-02-01_7a5537e61d_CP Data 2023-02-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-02-01 | 2023-02-01_7a5537e:   0%|          | 0.00/45.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-02-08 | 2023-02-08_3e075725ad_CP Data 2023-02-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-02-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-02-08_3e075725ad_CP Data 2023-02-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-02-08 | 2023-02-08_3e07572:   0%|          | 0.00/45.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-02-15 | 2023-02-15_6b1a312ed3_CP Data 2023-02-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-02-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-02-15_6b1a312ed3_CP Data 2023-02-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-02-15 | 2023-02-15_6b1a312:   0%|          | 0.00/45.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-02-22 | 2023-02-22_a6204bd86e_CP Data 2023-02-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-02-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-02-22_a6204bd86e_CP Data 2023-02-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-02-22 | 2023-02-22_a6204bd:   0%|          | 0.00/45.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-01-04 | 2023-01-04_2977e01ba8_CP Data 2023-01-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-01-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-01-04_2977e01ba8_CP Data 2023-01-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-01-04 | 2023-01-04_2977e01:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-01-11 | 2023-01-11_176fc7e48b_CP Data 2023-01-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-01-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-01-11_176fc7e48b_CP Data 2023-01-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-01-11 | 2023-01-11_176fc7e:   0%|          | 0.00/45.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-01-18 | 2023-01-18_003caf93d7_CP Data 2023-01-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-01-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-01-18_003caf93d7_CP Data 2023-01-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-01-18 | 2023-01-18_003caf9:   0%|          | 0.00/45.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2023-01-25 | 2023-01-25_7d22750a15_CP Data 2023-01-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202023-01-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2023\xlsx\2023-01-25_7d22750a15_CP Data 2023-01-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2023-01-25 | 2023-01-25_7d22750:   0%|          | 0.00/45.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-12-07 | 2022-12-07_63fec1a694_CP Data 2022-12-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-12-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-12-07_63fec1a694_CP Data 2022-12-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-12-07 | 2022-12-07_63fec1a:   0%|          | 0.00/43.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-12-14 | 2022-12-14_02931fb265_CP Data 2022-12-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-12-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-12-14_02931fb265_CP Data 2022-12-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-12-14 | 2022-12-14_02931fb:   0%|          | 0.00/43.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-12-21 | 2022-12-21_1f06861270_CP Data 2022-12-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-12-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-12-21_1f06861270_CP Data 2022-12-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-12-21 | 2022-12-21_1f06861:   0%|          | 0.00/43.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-12-28 | 2022-12-28_2c47964e86_CP Data 2022-12-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-12-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-12-28_2c47964e86_CP Data 2022-12-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-12-28 | 2022-12-28_2c47964:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-11-02 | 2022-11-02_dbff529d16_CP Data 2022-11-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-11-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-11-02_dbff529d16_CP Data 2022-11-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-11-02 | 2022-11-02_dbff529:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-11-09 | 2022-11-09_771c2a29f6_CP Data 2022-11-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-11-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-11-09_771c2a29f6_CP Data 2022-11-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-11-09 | 2022-11-09_771c2a2:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-11-16 | 2022-11-16_5663b2e35a_CP Data 2022-11-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-11-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-11-16_5663b2e35a_CP Data 2022-11-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-11-16 | 2022-11-16_5663b2e:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-11-23 | 2022-11-23_3abd00f32f_CP Data 2022-11-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-11-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-11-23_3abd00f32f_CP Data 2022-11-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-11-23 | 2022-11-23_3abd00f:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-11-30 | 2022-11-30_8e4a33c817_CP Data 2022-11-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-11-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-11-30_8e4a33c817_CP Data 2022-11-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-11-30 | 2022-11-30_8e4a33c:   0%|          | 0.00/43.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-10-05 | 2022-10-05_4b287bb3f9_CP Data 2022-10-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-10-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-10-05_4b287bb3f9_CP Data 2022-10-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-10-05 | 2022-10-05_4b287bb:   0%|          | 0.00/43.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-10-12 | 2022-10-12_6a436b34e9_CP Data 2022-10-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-10-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-10-12_6a436b34e9_CP Data 2022-10-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-10-12 | 2022-10-12_6a436b3:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-10-19 | 2022-10-19_9e7943bcb5_CP Data 2022-10-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-10-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-10-19_9e7943bcb5_CP Data 2022-10-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-10-19 | 2022-10-19_9e7943b:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-10-26 | 2022-10-26_a6e6866d8b_CP Data 2022-10-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-10-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-10-26_a6e6866d8b_CP Data 2022-10-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-10-26 | 2022-10-26_a6e6866:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-09-07 | 2022-09-07_b4facf2bf2_CP Data 2022-09-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-09-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-09-07_b4facf2bf2_CP Data 2022-09-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-09-07 | 2022-09-07_b4facf2:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-09-14 | 2022-09-14_81bb8bed4e_CP Data 2022-09-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-09-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-09-14_81bb8bed4e_CP Data 2022-09-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-09-14 | 2022-09-14_81bb8be:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-09-21 | 2022-09-21_ff2feb4256_CP Data 2022-09-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-09-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-09-21_ff2feb4256_CP Data 2022-09-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-09-21 | 2022-09-21_ff2feb4:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-09-28 | 2022-09-28_c7f6eb280b_CP Data 2022-09-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-09-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-09-28_c7f6eb280b_CP Data 2022-09-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-09-28 | 2022-09-28_c7f6eb2:   0%|          | 0.00/43.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-08-03 | 2022-08-03_97936a167d_CP Data 2022-08-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-08-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-08-03_97936a167d_CP Data 2022-08-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-08-03 | 2022-08-03_97936a1:   0%|          | 0.00/41.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-08-10 | 2022-08-10_4131d8d04d_CP Data 2022-08-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-08-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-08-10_4131d8d04d_CP Data 2022-08-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-08-10 | 2022-08-10_4131d8d:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-08-17 | 2022-08-17_7159aa71e7_CP Data 2022-08-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-08-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-08-17_7159aa71e7_CP Data 2022-08-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-08-17 | 2022-08-17_7159aa7:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-08-24 | 2022-08-24_d798eb9440_CP Data 2022-08-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-08-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-08-24_d798eb9440_CP Data 2022-08-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-08-24 | 2022-08-24_d798eb9:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-08-31 | 2022-08-31_9cba0f5ca2_CP Data 2022-08-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-08-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-08-31_9cba0f5ca2_CP Data 2022-08-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-08-31 | 2022-08-31_9cba0f5:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-07-06 | 2022-07-06_72245e6e88_CP Data 2022-07-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-07-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-07-06_72245e6e88_CP Data 2022-07-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-07-06 | 2022-07-06_72245e6:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-07-13 | 2022-07-13_b7a972dd2c_CP Data 2022-07-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-07-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-07-13_b7a972dd2c_CP Data 2022-07-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-07-13 | 2022-07-13_b7a972d:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-07-20 | 2022-07-20_8313ce7fc2_CP Data 2022-07-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-07-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-07-20_8313ce7fc2_CP Data 2022-07-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-07-20 | 2022-07-20_8313ce7:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-07-27 | 2022-07-27_1ffb670f1c_CP Data 2022-07-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-07-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-07-27_1ffb670f1c_CP Data 2022-07-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-07-27 | 2022-07-27_1ffb670:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-06-01 | 2022-06-01_b9b893398a_CP Data 2022-06-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-06-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-06-01_b9b893398a_CP Data 2022-06-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-06-01 | 2022-06-01_b9b8933:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-06-08 | 2022-06-08_666fb7e9c4_CP Data 2022-06-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-06-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-06-08_666fb7e9c4_CP Data 2022-06-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-06-08 | 2022-06-08_666fb7e:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-06-15 | 2022-06-15_8295879dd1_CP Data 2022-06-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-06-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-06-15_8295879dd1_CP Data 2022-06-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-06-15 | 2022-06-15_8295879:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-06-22 | 2022-06-22_b0f8a73662_CP Data 2022-06-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-06-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-06-22_b0f8a73662_CP Data 2022-06-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-06-22 | 2022-06-22_b0f8a73:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-06-29 | 2022-06-29_7997a24ce6_CP Data 2022-06-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-06-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-06-29_7997a24ce6_CP Data 2022-06-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-06-29 | 2022-06-29_7997a24:   0%|          | 0.00/41.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-05-04 | 2022-05-04_6d202b2f0c_CP Data 2022-05-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-05-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-05-04_6d202b2f0c_CP Data 2022-05-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-05-04 | 2022-05-04_6d202b2:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-05-11 | 2022-05-11_5b9aa5c026_CP Data 2022-05-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-05-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-05-11_5b9aa5c026_CP Data 2022-05-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-05-11 | 2022-05-11_5b9aa5c:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-05-18 | 2022-05-18_e834ca696e_CP Data 2022-05-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-05-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-05-18_e834ca696e_CP Data 2022-05-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-05-18 | 2022-05-18_e834ca6:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-05-25 | 2022-05-25_3a670dc7ee_CP Data 2022-05-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-05-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-05-25_3a670dc7ee_CP Data 2022-05-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-05-25 | 2022-05-25_3a670dc:   0%|          | 0.00/43.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-04-06 | 2022-04-06_529770a518_CP Data 2022-04-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-04-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-04-06_529770a518_CP Data 2022-04-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-04-06 | 2022-04-06_529770a:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-04-13 | 2022-04-13_e71b9ee2bd_CP Data 2022-04-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-04-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-04-13_e71b9ee2bd_CP Data 2022-04-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-04-13 | 2022-04-13_e71b9ee:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-04-20 | 2022-04-20_0abe66931b_CP Data 2022-04-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-04-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-04-20_0abe66931b_CP Data 2022-04-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-04-20 | 2022-04-20_0abe669:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-04-27 | 2022-04-27_053e903276_CP Data 2022-04-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-04-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-04-27_053e903276_CP Data 2022-04-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-04-27 | 2022-04-27_053e903:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-03-02 | 2022-03-02_95e6109d25_CP Data 2022-03-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-03-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-03-02_95e6109d25_CP Data 2022-03-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-03-02 | 2022-03-02_95e6109:   0%|          | 0.00/43.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-03-09 | 2022-03-09_e645557f6a_CP Data 2022-03-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-03-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-03-09_e645557f6a_CP Data 2022-03-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-03-09 | 2022-03-09_e645557:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-03-16 | 2022-03-16_cb5a8b3102_CP Data 2022-03-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-03-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-03-16_cb5a8b3102_CP Data 2022-03-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-03-16 | 2022-03-16_cb5a8b3:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-03-23 | 2022-03-23_c23809bd02_CP Data 2022-03-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-03-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-03-23_c23809bd02_CP Data 2022-03-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-03-23 | 2022-03-23_c23809b:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-03-30 | 2022-03-30_504f191988_CP Data 2022-03-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-03-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-03-30_504f191988_CP Data 2022-03-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-03-30 | 2022-03-30_504f191:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-02-02 | 2022-02-02_6d21931a77_CP Data 2022-02-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-02-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-02-02_6d21931a77_CP Data 2022-02-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-02-02 | 2022-02-02_6d21931:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-02-09 | 2022-02-09_cf76ee2d4f_CP Data 2022-02-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-02-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-02-09_cf76ee2d4f_CP Data 2022-02-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-02-09 | 2022-02-09_cf76ee2:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-02-16 | 2022-02-16_227ba716a6_CP Data 2022-02-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-02-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-02-16_227ba716a6_CP Data 2022-02-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-02-16 | 2022-02-16_227ba71:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-02-23 | 2022-02-23_00a6444ce3_CP Data 2022-02-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-02-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-02-23_00a6444ce3_CP Data 2022-02-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-02-23 | 2022-02-23_00a6444:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-01-05 | 2022-01-05_58f6cdfab2_CP Data 2022-01-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-01-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-01-05_58f6cdfab2_CP Data 2022-01-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-01-05 | 2022-01-05_58f6cdf:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-01-12 | 2022-01-12_e8d08c3ddd_CP Data 2022-01-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-01-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-01-12_e8d08c3ddd_CP Data 2022-01-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-01-12 | 2022-01-12_e8d08c3:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-01-19 | 2022-01-19_49b6140e3b_CP Data 2022-01-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-01-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-01-19_49b6140e3b_CP Data 2022-01-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-01-19 | 2022-01-19_49b6140:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2022-01-26 | 2022-01-26_dd0d924731_CP Data 2022-01-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202022-01-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2022\xlsx\2022-01-26_dd0d924731_CP Data 2022-01-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2022-01-26 | 2022-01-26_dd0d924:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-12-01 | 2021-12-01_6143b65999_CP Data 2021-12-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-12-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-12-01_6143b65999_CP Data 2021-12-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-12-01 | 2021-12-01_6143b65:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-12-08 | 2021-12-08_5b83f918de_CP Data 2021-12-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-12-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-12-08_5b83f918de_CP Data 2021-12-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-12-08 | 2021-12-08_5b83f91:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-12-15 | 2021-12-15_26de751ac0_CP Data 2021-12-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-12-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-12-15_26de751ac0_CP Data 2021-12-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-12-15 | 2021-12-15_26de751:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-12-22 | 2021-12-22_3558ea4b18_CP Data 2021-12-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-12-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-12-22_3558ea4b18_CP Data 2021-12-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-12-22 | 2021-12-22_3558ea4:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-12-29 | 2021-12-29_c5177b25c8_CP Data 2021-12-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-12-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-12-29_c5177b25c8_CP Data 2021-12-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-12-29 | 2021-12-29_c5177b2:   0%|          | 0.00/43.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-11-03 | 2021-11-03_2bb9be0094_CP Data 2021-11-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-11-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-11-03_2bb9be0094_CP Data 2021-11-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-11-03 | 2021-11-03_2bb9be0:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-11-10 | 2021-11-10_54d84d3527_CP Data 2021-11-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-11-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-11-10_54d84d3527_CP Data 2021-11-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-11-10 | 2021-11-10_54d84d3:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-11-17 | 2021-11-17_0b34fb9403_CP Data 2021-11-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-11-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-11-17_0b34fb9403_CP Data 2021-11-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-11-17 | 2021-11-17_0b34fb9:   0%|          | 0.00/43.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-11-24 | 2021-11-24_e0b71dfbf1_CP Data 2021-11-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-11-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-11-24_e0b71dfbf1_CP Data 2021-11-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-11-24 | 2021-11-24_e0b71df:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-10-06 | 2021-10-06_23f9fe8fe2_CP Data 2021-10-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-10-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-10-06_23f9fe8fe2_CP Data 2021-10-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-10-06 | 2021-10-06_23f9fe8:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-10-13 | 2021-10-13_5061148b86_CP Data 2021-10-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-10-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-10-13_5061148b86_CP Data 2021-10-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-10-13 | 2021-10-13_5061148:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-10-20 | 2021-10-20_5cb676ab1d_CP Data 2021-10-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-10-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-10-20_5cb676ab1d_CP Data 2021-10-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-10-20 | 2021-10-20_5cb676a:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-10-27 | 2021-10-27_aaa34f8218_CP Data 2021-10-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-10-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-10-27_aaa34f8218_CP Data 2021-10-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-10-27 | 2021-10-27_aaa34f8:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-09-01 | 2021-09-01_ed135185c9_CP Data 2021-09-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-09-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-09-01_ed135185c9_CP Data 2021-09-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-09-01 | 2021-09-01_ed13518:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-09-08 | 2021-09-08_da0352227b_CP Data 2021-09-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-09-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-09-08_da0352227b_CP Data 2021-09-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-09-08 | 2021-09-08_da03522:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-09-15 | 2021-09-15_bb0a589828_CP Data 2021-09-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-09-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-09-15_bb0a589828_CP Data 2021-09-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-09-15 | 2021-09-15_bb0a589:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-09-22 | 2021-09-22_59180ce44a_CP Data 2021-09-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-09-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-09-22_59180ce44a_CP Data 2021-09-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-09-22 | 2021-09-22_59180ce:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-09-29 | 2021-09-29_588800a31d_CP Data 2021-09-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-09-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-09-29_588800a31d_CP Data 2021-09-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-09-29 | 2021-09-29_588800a:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-08-04 | 2021-08-04_6aa7a4f052_CP Data 2021-08-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-08-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-08-04_6aa7a4f052_CP Data 2021-08-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-08-04 | 2021-08-04_6aa7a4f:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-08-11 | 2021-08-11_abbca35bb8_CP Data 2021-08-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-08-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-08-11_abbca35bb8_CP Data 2021-08-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-08-11 | 2021-08-11_abbca35:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-08-18 | 2021-08-18_9ad078ae2b_CP Data 2021-08-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-08-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-08-18_9ad078ae2b_CP Data 2021-08-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-08-18 | 2021-08-18_9ad078a:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-08-25 | 2021-08-25_8924b62648_CP Data 2021-08-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-08-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-08-25_8924b62648_CP Data 2021-08-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-08-25 | 2021-08-25_8924b62:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-07-07 | 2021-07-07_b32079e429_CP Data 2021-07-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-07-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-07-07_b32079e429_CP Data 2021-07-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-07-07 | 2021-07-07_b32079e:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-07-14 | 2021-07-14_c55d70a83d_CP Data 2021-07-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-07-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-07-14_c55d70a83d_CP Data 2021-07-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-07-14 | 2021-07-14_c55d70a:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-07-21 | 2021-07-21_07d826d645_CP Data 2021-07-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-07-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-07-21_07d826d645_CP Data 2021-07-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-07-21 | 2021-07-21_07d826d:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-07-28 | 2021-07-28_797ff65e85_CP Data 2021-07-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-07-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-07-28_797ff65e85_CP Data 2021-07-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-07-28 | 2021-07-28_797ff65:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-06-02 | 2021-06-02_381dce4812_CP Data 2021-06-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-06-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-06-02_381dce4812_CP Data 2021-06-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-06-02 | 2021-06-02_381dce4:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-06-09 | 2021-06-09_a571f04bef_CP Data 2021-06-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-06-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-06-09_a571f04bef_CP Data 2021-06-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-06-09 | 2021-06-09_a571f04:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-06-16 | 2021-06-16_ef9b223dc8_CP Data 2021-06-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-06-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-06-16_ef9b223dc8_CP Data 2021-06-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-06-16 | 2021-06-16_ef9b223:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-06-23 | 2021-06-23_bcb069f395_CP Data 2021-06-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-06-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-06-23_bcb069f395_CP Data 2021-06-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-06-23 | 2021-06-23_bcb069f:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-06-30 | 2021-06-30_8aaa10a557_CP Data 2021-06-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-06-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-06-30_8aaa10a557_CP Data 2021-06-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-06-30 | 2021-06-30_8aaa10a:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-05-05 | 2021-05-05_aa72d2eab7_CP Data 2021-05-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-05-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-05-05_aa72d2eab7_CP Data 2021-05-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-05-05 | 2021-05-05_aa72d2e:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-05-12 | 2021-05-12_c068e65d36_CP Data 2021-05-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-05-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-05-12_c068e65d36_CP Data 2021-05-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-05-12 | 2021-05-12_c068e65:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-05-19 | 2021-05-19_0a0bdb0060_CP Data 2021-05-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-05-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-05-19_0a0bdb0060_CP Data 2021-05-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-05-19 | 2021-05-19_0a0bdb0:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-05-26 | 2021-05-26_0f6ecba650_CP Data 2021-05-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-05-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-05-26_0f6ecba650_CP Data 2021-05-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-05-26 | 2021-05-26_0f6ecba:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-04-07 | 2021-04-07_be99d7b057_CP Data 2021-04-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-04-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-04-07_be99d7b057_CP Data 2021-04-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-04-07 | 2021-04-07_be99d7b:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-04-14 | 2021-04-14_fc26bc4d29_CP Data 2021-04-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-04-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-04-14_fc26bc4d29_CP Data 2021-04-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-04-14 | 2021-04-14_fc26bc4:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-04-21 | 2021-04-21_7a90511fb6_CP Data 2021-04-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-04-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-04-21_7a90511fb6_CP Data 2021-04-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-04-21 | 2021-04-21_7a90511:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-04-28 | 2021-04-28_4011cca35c_CP Data 2021-04-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-04-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-04-28_4011cca35c_CP Data 2021-04-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-04-28 | 2021-04-28_4011cca:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-03-03 | 2021-03-03_d46c80d448_CP Data 2021-03-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-03-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-03-03_d46c80d448_CP Data 2021-03-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-03-03 | 2021-03-03_d46c80d:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-03-10 | 2021-03-10_33139e0ed3_CP Data 2021-03-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-03-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-03-10_33139e0ed3_CP Data 2021-03-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-03-10 | 2021-03-10_33139e0:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-03-17 | 2021-03-17_58c0b6959c_CP Data 2021-03-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-03-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-03-17_58c0b6959c_CP Data 2021-03-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-03-17 | 2021-03-17_58c0b69:   0%|          | 0.00/42.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-03-24 | 2021-03-24_3f38eb5612_CP Data 2021-03-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-03-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-03-24_3f38eb5612_CP Data 2021-03-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-03-24 | 2021-03-24_3f38eb5:   0%|          | 0.00/42.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-03-31 | 2021-03-31_a41e3d79c1_CP Data 2021-03-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-03-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-03-31_a41e3d79c1_CP Data 2021-03-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-03-31 | 2021-03-31_a41e3d7:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-02-03 | 2021-02-03_16c58cd2ea_CP Data 2021-02-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-02-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-02-03_16c58cd2ea_CP Data 2021-02-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-02-03 | 2021-02-03_16c58cd:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-02-10 | 2021-02-10_b1a3b8b0d2_CP Data 2021-02-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-02-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-02-10_b1a3b8b0d2_CP Data 2021-02-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-02-10 | 2021-02-10_b1a3b8b:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-02-17 | 2021-02-17_d437b0929e_CP Data 2021-02-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-02-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-02-17_d437b0929e_CP Data 2021-02-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-02-17 | 2021-02-17_d437b09:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-02-24 | 2021-02-24_d6c755b635_CP Data 2021-02-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-02-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-02-24_d6c755b635_CP Data 2021-02-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-02-24 | 2021-02-24_d6c755b:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-01-06 | 2021-01-06_7f5f8f3ffc_CP Data 2021-01-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-01-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-01-06_7f5f8f3ffc_CP Data 2021-01-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-01-06 | 2021-01-06_7f5f8f3:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-01-13 | 2021-01-13_07628d7ae7_CP Data 2021-01-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-01-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-01-13_07628d7ae7_CP Data 2021-01-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-01-13 | 2021-01-13_07628d7:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-01-20 | 2021-01-20_fc445c0f0b_CP Data 2021-01-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-01-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-01-20_fc445c0f0b_CP Data 2021-01-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-01-20 | 2021-01-20_fc445c0:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2021-01-27 | 2021-01-27_4602ff55a7_CP Data 2021-01-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202021-01-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2021\xlsx\2021-01-27_4602ff55a7_CP Data 2021-01-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2021-01-27 | 2021-01-27_4602ff5:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-12-02 | 2020-12-02_be738ce229_CP Data 2020-12-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-12-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-12-02_be738ce229_CP Data 2020-12-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-12-02 | 2020-12-02_be738ce:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-12-09 | 2020-12-09_a92f7f9738_CP Data 2020-12-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-12-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-12-09_a92f7f9738_CP Data 2020-12-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-12-09 | 2020-12-09_a92f7f9:   0%|          | 0.00/42.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-12-16 | 2020-12-16_3fc3b8fc79_CP Data 2020-12-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-12-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-12-16_3fc3b8fc79_CP Data 2020-12-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-12-16 | 2020-12-16_3fc3b8f:   0%|          | 0.00/45.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-12-23 | 2020-12-23_30b0cfc7c6_CP Data 2020-12-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-12-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-12-23_30b0cfc7c6_CP Data 2020-12-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-12-23 | 2020-12-23_30b0cfc:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-12-30 | 2020-12-30_3aee8ec852_CP Data 2020-12-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-12-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-12-30_3aee8ec852_CP Data 2020-12-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-12-30 | 2020-12-30_3aee8ec:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-11-04 | 2020-11-04_fd3c36c359_CP Data 2020-11-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-11-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-11-04_fd3c36c359_CP Data 2020-11-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-11-04 | 2020-11-04_fd3c36c:   0%|          | 0.00/41.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-11-11 | 2020-11-11_e14a08b0ff_CP Data 2020-11-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-11-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-11-11_e14a08b0ff_CP Data 2020-11-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-11-11 | 2020-11-11_e14a08b:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-11-18 | 2020-11-18_68ae445b95_CP Data 2020-11-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-11-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-11-18_68ae445b95_CP Data 2020-11-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-11-18 | 2020-11-18_68ae445:   0%|          | 0.00/42.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-11-25 | 2020-11-25_553a9e2c5d_CP Data 2020-11-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-11-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-11-25_553a9e2c5d_CP Data 2020-11-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-11-25 | 2020-11-25_553a9e2:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-10-07 | 2020-10-07_9d67ae095b_CP Data 2020-10-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-10-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-10-07_9d67ae095b_CP Data 2020-10-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-10-07 | 2020-10-07_9d67ae0:   0%|          | 0.00/41.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-10-14 | 2020-10-14_675ec30bb1_CP Data 2020-10-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-10-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-10-14_675ec30bb1_CP Data 2020-10-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-10-14 | 2020-10-14_675ec30:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-10-21 | 2020-10-21_6e22a0064b_CP Data 2020-10-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-10-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-10-21_6e22a0064b_CP Data 2020-10-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-10-21 | 2020-10-21_6e22a00:   0%|          | 0.00/41.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-10-28 | 2020-10-28_303a3af83a_CP Data 2020-10-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-10-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-10-28_303a3af83a_CP Data 2020-10-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-10-28 | 2020-10-28_303a3af:   0%|          | 0.00/41.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-09-02 | 2020-09-02_668c590efd_CP Data 2020-09-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-09-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-09-02_668c590efd_CP Data 2020-09-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-09-02 | 2020-09-02_668c590:   0%|          | 0.00/42.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-09-09 | 2020-09-09_15d555abcd_CP Data 2020-09-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-09-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-09-09_15d555abcd_CP Data 2020-09-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-09-09 | 2020-09-09_15d555a:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-09-16 | 2020-09-16_09d0047c6e_CP Data 2020-09-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-09-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-09-16_09d0047c6e_CP Data 2020-09-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-09-16 | 2020-09-16_09d0047:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-09-23 | 2020-09-23_02e67ddacc_CP Data 2020-09-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-09-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-09-23_02e67ddacc_CP Data 2020-09-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-09-23 | 2020-09-23_02e67dd:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-09-30 | 2020-09-30_fb53c5712f_CP Data 2020-09-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-09-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-09-30_fb53c5712f_CP Data 2020-09-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-09-30 | 2020-09-30_fb53c57:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-08-05 | 2020-08-05_9ab86a8acd_CP Data 2020-08-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-08-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-08-05_9ab86a8acd_CP Data 2020-08-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-08-05 | 2020-08-05_9ab86a8:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-08-12 | 2020-08-12_a4281c5847_CP Data 2020-08-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-08-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-08-12_a4281c5847_CP Data 2020-08-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-08-12 | 2020-08-12_a4281c5:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-08-19 | 2020-08-19_93644a2783_CP Data 2020-08-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-08-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-08-19_93644a2783_CP Data 2020-08-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-08-19 | 2020-08-19_93644a2:   0%|          | 0.00/42.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-08-26 | 2020-08-26_c6dc0796da_CP Data 2020-08-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-08-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-08-26_c6dc0796da_CP Data 2020-08-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-08-26 | 2020-08-26_c6dc079:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-07-01 | 2020-07-01_8f3e72aecc_cp_data_2020-07-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-07-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-07-01_8f3e72aecc_cp_data_2020-07-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-07-01 | 2020-07-01_8f3e72a:   0%|          | 0.00/43.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-07-08 | 2020-07-08_80917f5c79_cp_data_2020-07-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-07-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-07-08_80917f5c79_cp_data_2020-07-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-07-08 | 2020-07-08_80917f5:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-07-15 | 2020-07-15_5115cd331d_cp_data_2020-07-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-07-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-07-15_5115cd331d_cp_data_2020-07-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-07-15 | 2020-07-15_5115cd3:   0%|          | 0.00/43.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-07-22 | 2020-07-22_82df74cc5a_cp_data_2020-07-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-07-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-07-22_82df74cc5a_cp_data_2020-07-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-07-22 | 2020-07-22_82df74c:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-07-29 | 2020-07-29_64727e6d93_CP Data 2020-07-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/CP%20Data%202020-07-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-07-29_64727e6d93_CP Data 2020-07-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-07-29 | 2020-07-29_64727e6:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-06-03 | 2020-06-03_4ff88ad82e_cp_data_2020-06-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-06-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-06-03_4ff88ad82e_cp_data_2020-06-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-06-03 | 2020-06-03_4ff88ad:   0%|          | 0.00/44.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-06-10 | 2020-06-10_41d932994b_cp_data_2020-06-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-06-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-06-10_41d932994b_cp_data_2020-06-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-06-10 | 2020-06-10_41d9329:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-06-17 | 2020-06-17_7a7833354d_cp_data_2020-06-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-06-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-06-17_7a7833354d_cp_data_2020-06-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-06-17 | 2020-06-17_7a78333:   0%|          | 0.00/43.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-06-24 | 2020-06-24_e2c4120847_cp_data_2020-06-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-06-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-06-24_e2c4120847_cp_data_2020-06-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-06-24 | 2020-06-24_e2c4120:   0%|          | 0.00/43.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-05-06 | 2020-05-06_f50a833ad4_cp_data_2020-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-05-06_f50a833ad4_cp_data_2020-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-05-06 | 2020-05-06_f50a833:   0%|          | 0.00/43.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-05-13 | 2020-05-13_aafe6ab920_cp_data_2020-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-05-13_aafe6ab920_cp_data_2020-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-05-13 | 2020-05-13_aafe6ab:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-05-20 | 2020-05-20_14b1474bb7_cp_data_2020-05-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-05-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-05-20_14b1474bb7_cp_data_2020-05-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-05-20 | 2020-05-20_14b1474:   0%|          | 0.00/43.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-05-27 | 2020-05-27_3693e9b7dc_cp_data_2020-05-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-05-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-05-27_3693e9b7dc_cp_data_2020-05-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-05-27 | 2020-05-27_3693e9b:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-04-01 | 2020-04-01_3a057bf08a_cp_data_2020-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-04-01_3a057bf08a_cp_data_2020-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-04-01 | 2020-04-01_3a057bf:   0%|          | 0.00/43.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-04-08 | 2020-04-08_46f4d1e6d7_cp_data_2020-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-04-08_46f4d1e6d7_cp_data_2020-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-04-08 | 2020-04-08_46f4d1e:   0%|          | 0.00/43.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-04-15 | 2020-04-15_83bf68edf8_cp_data_2020-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-04-15_83bf68edf8_cp_data_2020-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-04-15 | 2020-04-15_83bf68e:   0%|          | 0.00/43.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-04-22 | 2020-04-22_6ff0678317_cp_data_2020-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-04-22_6ff0678317_cp_data_2020-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-04-22 | 2020-04-22_6ff0678:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-04-29 | 2020-04-29_51f43e4624_cp_data_2020-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-04-29_51f43e4624_cp_data_2020-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-04-29 | 2020-04-29_51f43e4:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-03-04 | 2020-03-04_3303bc2b3d_cp_data_2020-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-03-04_3303bc2b3d_cp_data_2020-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-03-04 | 2020-03-04_3303bc2:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-03-11 | 2020-03-11_30fc8e288f_cp_data_2020-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-03-11_30fc8e288f_cp_data_2020-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-03-11 | 2020-03-11_30fc8e2:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-03-18 | 2020-03-18_6fe20b4cf7_cp_data_2020-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-03-18_6fe20b4cf7_cp_data_2020-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-03-18 | 2020-03-18_6fe20b4:   0%|          | 0.00/43.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-03-25 | 2020-03-25_a756b1f64a_cp_data_2020-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-03-25_a756b1f64a_cp_data_2020-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-03-25 | 2020-03-25_a756b1f:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-02-05 | 2020-02-05_ca95d00929_cp_data_2020-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-02-05_ca95d00929_cp_data_2020-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-02-05 | 2020-02-05_ca95d00:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-02-12 | 2020-02-12_f40250d6c2_cp_data_2020-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-02-12_f40250d6c2_cp_data_2020-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-02-12 | 2020-02-12_f40250d:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-02-19 | 2020-02-19_d20d2e7621_cp_data_2020-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-02-19_d20d2e7621_cp_data_2020-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-02-19 | 2020-02-19_d20d2e7:   0%|          | 0.00/43.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-02-26 | 2020-02-26_3a1d7d61f6_cp_data_2020-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-02-26_3a1d7d61f6_cp_data_2020-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-02-26 | 2020-02-26_3a1d7d6:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-01-01 | 2020-01-01_40bdffdf60_cp_data_2020-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-01-01_40bdffdf60_cp_data_2020-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-01-01 | 2020-01-01_40bdffd:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-01-08 | 2020-01-08_f62d9d2211_cp_data_2020-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-01-08_f62d9d2211_cp_data_2020-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-01-08 | 2020-01-08_f62d9d2:   0%|          | 0.00/43.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-01-15 | 2020-01-15_e94caa42d4_cp_data_2020-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-01-15_e94caa42d4_cp_data_2020-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-01-15 | 2020-01-15_e94caa4:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-01-22 | 2020-01-22_fe989fab59_cp_data_2020-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-01-22_fe989fab59_cp_data_2020-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-01-22 | 2020-01-22_fe989fa:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cp | 2020-01-29 | 2020-01-29_050645788c_cp_data_2020-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CP/cp_data_2020-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cp\2020\xlsx\2020-01-29_050645788c_cp_data_2020-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cp | 2020-01-29 | 2020-01-29_0506457:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-05-06 | 2026-05-06_47feaf7321_CPKC Data 2026-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-05-06_47feaf7321_CPKC Data 2026-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-05-06 | 2026-05-06_47fea:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-05-13 | 2026-05-13_73c66fffd2_CPKC Data 2026-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-05-13_73c66fffd2_CPKC Data 2026-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-05-13 | 2026-05-13_73c66:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-04-01 | 2026-04-01_50eb8032e7_CPKC Data 2026-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-04-01_50eb8032e7_CPKC Data 2026-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-04-01 | 2026-04-01_50eb8:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-04-08 | 2026-04-08_3831b1605e_CPKC Data 2026-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-04-08_3831b1605e_CPKC Data 2026-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-04-08 | 2026-04-08_3831b:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-04-15 | 2026-04-15_6aaadc8c73_CPKC Data 2026-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-04-15_6aaadc8c73_CPKC Data 2026-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-04-15 | 2026-04-15_6aaad:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-04-22 | 2026-04-22_b764e17706_CPKC Data 2026-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-04-22_b764e17706_CPKC Data 2026-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-04-22 | 2026-04-22_b764e:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-04-29 | 2026-04-29_fe75eff711_CPKC Data 2026-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-04-29_fe75eff711_CPKC Data 2026-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-04-29 | 2026-04-29_fe75e:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-03-04 | 2026-03-04_6060187ad0_CPKC Data 2026-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-03-04_6060187ad0_CPKC Data 2026-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-03-04 | 2026-03-04_60601:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-03-11 | 2026-03-11_584daf8398_CPKC Data 2026-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-03-11_584daf8398_CPKC Data 2026-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-03-11 | 2026-03-11_584da:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-03-18 | 2026-03-18_6381b9c563_CPKC Data 2026-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-03-18_6381b9c563_CPKC Data 2026-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-03-18 | 2026-03-18_6381b:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-03-25 | 2026-03-25_70cd89322a_CPKC Data 2026-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-03-25_70cd89322a_CPKC Data 2026-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-03-25 | 2026-03-25_70cd8:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-02-04 | 2026-02-04_2e83d55b26_CPKC Data 2026-02-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-02-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-02-04_2e83d55b26_CPKC Data 2026-02-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-02-04 | 2026-02-04_2e83d:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-02-11 | 2026-02-11_3b36e5d4ba_CPKC Data 2026-02-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-02-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-02-11_3b36e5d4ba_CPKC Data 2026-02-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-02-11 | 2026-02-11_3b36e:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-02-18 | 2026-02-18_5f3e77ca26_CPKC Data 2026-02-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-02-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-02-18_5f3e77ca26_CPKC Data 2026-02-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-02-18 | 2026-02-18_5f3e7:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-02-25 | 2026-02-25_15a2d1302d_CPKC Data 2026-02-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-02-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-02-25_15a2d1302d_CPKC Data 2026-02-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-02-25 | 2026-02-25_15a2d:   0%|          | 0.00/43.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-01-07 | 2026-01-07_dadad4e6dc_CPKC Data 2026-01-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-01-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-01-07_dadad4e6dc_CPKC Data 2026-01-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-01-07 | 2026-01-07_dadad:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-01-14 | 2026-01-14_47a24f0853_CPKC Data 2026-01-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-01-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-01-14_47a24f0853_CPKC Data 2026-01-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-01-14 | 2026-01-14_47a24:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-01-21 | 2026-01-21_44bd624f33_CPKC Data 2026-01-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-01-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-01-21_44bd624f33_CPKC Data 2026-01-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-01-21 | 2026-01-21_44bd6:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2026-01-28 | 2026-01-28_061b352655_CPKC Data 2026-01-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202026-01-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2026\xlsx\2026-01-28_061b352655_CPKC Data 2026-01-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2026-01-28 | 2026-01-28_061b3:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-12-31 | 2025-12-31_4a1b6fd2e7_CPKC Data 2025-12-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-12-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-12-31_4a1b6fd2e7_CPKC Data 2025-12-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-12-31 | 2025-12-31_4a1b6:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-12-03 | 2025-12-03_6b1ebe9bab_CPKC Data 2025-12-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-12-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-12-03_6b1ebe9bab_CPKC Data 2025-12-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-12-03 | 2025-12-03_6b1eb:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-12-10 | 2025-12-10_0f1df20052_CPKC Data 2025-12-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-12-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-12-10_0f1df20052_CPKC Data 2025-12-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-12-10 | 2025-12-10_0f1df:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-12-17 | 2025-12-17_f1bc308ac7_CPKC Data 2025-12-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-12-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-12-17_f1bc308ac7_CPKC Data 2025-12-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-12-17 | 2025-12-17_f1bc3:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-12-24 | 2025-12-24_ee53c562c6_CPKC Data 2025-12-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-12-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-12-24_ee53c562c6_CPKC Data 2025-12-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-12-24 | 2025-12-24_ee53c:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-11-05 | 2025-11-05_dae303251f_CPKC Data 2025-11-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-11-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-11-05_dae303251f_CPKC Data 2025-11-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-11-05 | 2025-11-05_dae30:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-11-12 | 2025-11-12_46a8463ff1_CPKC Data 2025-11-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-11-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-11-12_46a8463ff1_CPKC Data 2025-11-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-11-12 | 2025-11-12_46a84:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-11-19 | 2025-11-19_a70aaf9f15_CPKC Data 2025-11-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-11-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-11-19_a70aaf9f15_CPKC Data 2025-11-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-11-19 | 2025-11-19_a70aa:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-11-26 | 2025-11-26_ac58aaf66d_CPKC Data 2025-11-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-11-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-11-26_ac58aaf66d_CPKC Data 2025-11-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-11-26 | 2025-11-26_ac58a:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-10-01 | 2025-10-01_6531530991_CPKC Data 2025-10-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-10-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-10-01_6531530991_CPKC Data 2025-10-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-10-01 | 2025-10-01_65315:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-10-08 | 2025-10-08_457ec970ec_CPKC Data 2025-10-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-10-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-10-08_457ec970ec_CPKC Data 2025-10-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-10-08 | 2025-10-08_457ec:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-10-15 | 2025-10-15_19ae2f64e5_CPKC Data 2025-10-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-10-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-10-15_19ae2f64e5_CPKC Data 2025-10-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-10-15 | 2025-10-15_19ae2:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-10-22 | 2025-10-22_cde9b81b37_CPKC Data 2025-10-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-10-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-10-22_cde9b81b37_CPKC Data 2025-10-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-10-22 | 2025-10-22_cde9b:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-10-29 | 2025-10-29_1e17039e68_CPKC Data 2025-10-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-10-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-10-29_1e17039e68_CPKC Data 2025-10-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-10-29 | 2025-10-29_1e170:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-09-03 | 2025-09-03_096630e529_CPKC Data 2025-09-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-09-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-09-03_096630e529_CPKC Data 2025-09-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-09-03 | 2025-09-03_09663:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-09-10 | 2025-09-10_96293004ae_CPKC Data 2025-09-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-09-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-09-10_96293004ae_CPKC Data 2025-09-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-09-10 | 2025-09-10_96293:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-09-17 | 2025-09-17_59b947d7c1_CPKC Data 2025-09-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-09-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-09-17_59b947d7c1_CPKC Data 2025-09-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-09-17 | 2025-09-17_59b94:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-09-24 | 2025-09-24_ef95895e67_CPKC Data 2025-09-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-09-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-09-24_ef95895e67_CPKC Data 2025-09-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-09-24 | 2025-09-24_ef958:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-08-06 | 2025-08-06_a3f6f190f5_CPKC Data 2025-08-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-08-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-08-06_a3f6f190f5_CPKC Data 2025-08-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-08-06 | 2025-08-06_a3f6f:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-08-13 | 2025-08-13_5d157ed7ab_CPKC Data 2025-08-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-08-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-08-13_5d157ed7ab_CPKC Data 2025-08-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-08-13 | 2025-08-13_5d157:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-08-20 | 2025-08-20_01e7d1f9d8_CPKC Data 2025-08-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-08-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-08-20_01e7d1f9d8_CPKC Data 2025-08-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-08-20 | 2025-08-20_01e7d:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-08-27 | 2025-08-27_f8b532b680_CPKC Data 2025-08-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-08-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-08-27_f8b532b680_CPKC Data 2025-08-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-08-27 | 2025-08-27_f8b53:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-07-02 | 2025-07-02_622f03355c_CPKC Data 2025-07-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-07-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-07-02_622f03355c_CPKC Data 2025-07-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-07-02 | 2025-07-02_622f0:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-07-09 | 2025-07-09_a0ae888cfc_CPKC Data 2025-07-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-07-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-07-09_a0ae888cfc_CPKC Data 2025-07-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-07-09 | 2025-07-09_a0ae8:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-07-16 | 2025-07-16_3767c5f71f_CPKC Data 2025-07-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-07-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-07-16_3767c5f71f_CPKC Data 2025-07-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-07-16 | 2025-07-16_3767c:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-07-23 | 2025-07-23_654930b9d0_CPKC Data 2025-07-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-07-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-07-23_654930b9d0_CPKC Data 2025-07-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-07-23 | 2025-07-23_65493:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-07-30 | 2025-07-30_73d0f087df_CPKC Data 2025-07-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-07-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-07-30_73d0f087df_CPKC Data 2025-07-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-07-30 | 2025-07-30_73d0f:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-06-04 | 2025-06-04_baa568f4e7_CPKC Data 2025-06-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-06-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-06-04_baa568f4e7_CPKC Data 2025-06-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-06-04 | 2025-06-04_baa56:   0%|          | 0.00/47.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-06-11 | 2025-06-11_fb22d52952_CPKC Data 2025-06-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-06-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-06-11_fb22d52952_CPKC Data 2025-06-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-06-11 | 2025-06-11_fb22d:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-06-18 | 2025-06-18_c0ec68f965_CPKC Data 2025-06-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-06-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-06-18_c0ec68f965_CPKC Data 2025-06-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-06-18 | 2025-06-18_c0ec6:   0%|          | 0.00/52.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-06-25 | 2025-06-25_25db0d4e9e_CPKC Data 2025-06-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-06-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-06-25_25db0d4e9e_CPKC Data 2025-06-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-06-25 | 2025-06-25_25db0:   0%|          | 0.00/42.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-05-14 | 2025-05-14_9073bd164b_CPKC Data 2025-05-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-05-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-05-14_9073bd164b_CPKC Data 2025-05-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-05-14 | 2025-05-14_9073b:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-05-21 | 2025-05-21_c33d496d81_CPKC Data 2025-05-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-05-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-05-21_c33d496d81_CPKC Data 2025-05-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-05-21 | 2025-05-21_c33d4:   0%|          | 0.00/42.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | cpkc | 2025-05-28 | 2025-05-28_c73d13db9f_CPKC Data 2025-05-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CPKC/CPKC%20Data%202025-05-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\cpkc\2025\xlsx\2025-05-28_c73d13db9f_CPKC Data 2025-05-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | cpkc | 2025-05-28 | 2025-05-28_c73d1:   0%|          | 0.00/42.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-05-06 | 2026-05-06_2f59515e24_CSX Data 2026-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-05-06_2f59515e24_CSX Data 2026-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-05-06 | 2026-05-06_2f5951:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-05-13 | 2026-05-13_fc69677a09_CSX Data 2026-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-05-13_fc69677a09_CSX Data 2026-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-05-13 | 2026-05-13_fc6967:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-04-01 | 2026-04-01_f97168d4d7_CSX Data 2026-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-04-01_f97168d4d7_CSX Data 2026-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-04-01 | 2026-04-01_f97168:   0%|          | 0.00/51.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-04-08 | 2026-04-08_a4e504b64d_CSX Data 2026-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-04-08_a4e504b64d_CSX Data 2026-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-04-08 | 2026-04-08_a4e504:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-04-15 | 2026-04-15_e35810a406_CSX Data 2026-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-04-15_e35810a406_CSX Data 2026-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-04-15 | 2026-04-15_e35810:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-04-22 | 2026-04-22_27e37c44ad_CSX Data 2026-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-04-22_27e37c44ad_CSX Data 2026-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-04-22 | 2026-04-22_27e37c:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-04-29 | 2026-04-29_af7d451cff_CSX Data 2026-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-04-29_af7d451cff_CSX Data 2026-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-04-29 | 2026-04-29_af7d45:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-03-04 | 2026-03-04_cff34b3d90_CSX Data 2026-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-03-04_cff34b3d90_CSX Data 2026-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-03-04 | 2026-03-04_cff34b:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-03-11 | 2026-03-11_b774f72d55_CSX Data 2026-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-03-11_b774f72d55_CSX Data 2026-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-03-11 | 2026-03-11_b774f7:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-03-18 | 2026-03-18_741ed6546f_CSX Data 2026-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-03-18_741ed6546f_CSX Data 2026-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-03-18 | 2026-03-18_741ed6:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-03-25 | 2026-03-25_c55ede9bd9_CSX Data 2026-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-03-25_c55ede9bd9_CSX Data 2026-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-03-25 | 2026-03-25_c55ede:   0%|          | 0.00/51.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-02-04 | 2026-02-04_64d9643665_CSX Data 2026-02-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-02-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-02-04_64d9643665_CSX Data 2026-02-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-02-04 | 2026-02-04_64d964:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-02-11 | 2026-02-11_2209fffdcb_CSX Data 2026-02-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-02-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-02-11_2209fffdcb_CSX Data 2026-02-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-02-11 | 2026-02-11_2209ff:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-02-18 | 2026-02-18_ddd6ebe034_CSX Data 2026-02-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-02-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-02-18_ddd6ebe034_CSX Data 2026-02-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-02-18 | 2026-02-18_ddd6eb:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-02-25 | 2026-02-25_0bc402f651_CSX Data 2026-02-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-02-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-02-25_0bc402f651_CSX Data 2026-02-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-02-25 | 2026-02-25_0bc402:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-01-07 | 2026-01-07_4daa2a1daf_CSX Data 2026-01-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-01-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-01-07_4daa2a1daf_CSX Data 2026-01-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-01-07 | 2026-01-07_4daa2a:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-01-14 | 2026-01-14_eb7bf48f61_CSX Data 2026-01-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-01-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-01-14_eb7bf48f61_CSX Data 2026-01-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-01-14 | 2026-01-14_eb7bf4:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-01-21 | 2026-01-21_8930dd829b_CSX Data 2026-01-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-01-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-01-21_8930dd829b_CSX Data 2026-01-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-01-21 | 2026-01-21_8930dd:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2026-01-28 | 2026-01-28_5b772d6e7c_CSX Data 2026-01-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202026-01-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2026\xlsx\2026-01-28_5b772d6e7c_CSX Data 2026-01-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2026-01-28 | 2026-01-28_5b772d:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-12-31 | 2025-12-31_2db15d9e41_CSX Data 2025-12-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-12-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-12-31_2db15d9e41_CSX Data 2025-12-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-12-31 | 2025-12-31_2db15d:   0%|          | 0.00/50.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-12-03 | 2025-12-03_60abf94409_CSX Data 2025-12-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-12-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-12-03_60abf94409_CSX Data 2025-12-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-12-03 | 2025-12-03_60abf9:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-12-10 | 2025-12-10_8ea165924e_CSX Data 2025-12-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-12-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-12-10_8ea165924e_CSX Data 2025-12-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-12-10 | 2025-12-10_8ea165:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-12-17 | 2025-12-17_f6212a6b0e_CSX Data 2025-12-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-12-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-12-17_f6212a6b0e_CSX Data 2025-12-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-12-17 | 2025-12-17_f6212a:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-12-24 | 2025-12-24_4d1dd12355_CSX Data 2025-12-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-12-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-12-24_4d1dd12355_CSX Data 2025-12-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-12-24 | 2025-12-24_4d1dd1:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-11-05 | 2025-11-05_7005be140e_CSX Data 2025-11-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-11-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-11-05_7005be140e_CSX Data 2025-11-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-11-05 | 2025-11-05_7005be:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-11-12 | 2025-11-12_fe7a97a61a_CSX Data 2025-11-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-11-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-11-12_fe7a97a61a_CSX Data 2025-11-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-11-12 | 2025-11-12_fe7a97:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-11-19 | 2025-11-19_50679f984c_CSX Data 2025-11-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-11-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-11-19_50679f984c_CSX Data 2025-11-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-11-19 | 2025-11-19_50679f:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-11-26 | 2025-11-26_03b589bfb1_CSX Data 2025-11-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-11-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-11-26_03b589bfb1_CSX Data 2025-11-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-11-26 | 2025-11-26_03b589:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-10-01 | 2025-10-01_73fa72d718_CSX Data 2025-10-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-10-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-10-01_73fa72d718_CSX Data 2025-10-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-10-01 | 2025-10-01_73fa72:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-10-08 | 2025-10-08_ec1b0f5dc5_CSX Data 2025-10-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-10-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-10-08_ec1b0f5dc5_CSX Data 2025-10-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-10-08 | 2025-10-08_ec1b0f:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-10-15 | 2025-10-15_24d1d403e6_CSX Data 2025-10-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-10-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-10-15_24d1d403e6_CSX Data 2025-10-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-10-15 | 2025-10-15_24d1d4:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-10-22 | 2025-10-22_a653d3c3cc_CSX Data 2025-10-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-10-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-10-22_a653d3c3cc_CSX Data 2025-10-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-10-22 | 2025-10-22_a653d3:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-10-29 | 2025-10-29_6fffd48921_CSX Data 2025-10-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-10-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-10-29_6fffd48921_CSX Data 2025-10-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-10-29 | 2025-10-29_6fffd4:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-09-03 | 2025-09-03_7b1589333c_CSX Data 2025-09-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-09-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-09-03_7b1589333c_CSX Data 2025-09-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-09-03 | 2025-09-03_7b1589:   0%|          | 0.00/51.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-09-10 | 2025-09-10_6268632320_CSX Data 2025-09-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-09-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-09-10_6268632320_CSX Data 2025-09-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-09-10 | 2025-09-10_626863:   0%|          | 0.00/50.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-09-17 | 2025-09-17_b7fa772591_CSX Data 2025-09-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-09-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-09-17_b7fa772591_CSX Data 2025-09-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-09-17 | 2025-09-17_b7fa77:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-09-24 | 2025-09-24_1b9055f835_CSX Data 2025-09-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-09-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-09-24_1b9055f835_CSX Data 2025-09-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-09-24 | 2025-09-24_1b9055:   0%|          | 0.00/51.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-08-06 | 2025-08-06_5421cf2678_CSX Data 2025-08-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-08-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-08-06_5421cf2678_CSX Data 2025-08-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-08-06 | 2025-08-06_5421cf:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-08-13 | 2025-08-13_2bd0704de1_CSX Data 2025-08-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-08-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-08-13_2bd0704de1_CSX Data 2025-08-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-08-13 | 2025-08-13_2bd070:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-08-20 | 2025-08-20_7a5ee561d6_CSX Data 2025-08-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-08-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-08-20_7a5ee561d6_CSX Data 2025-08-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-08-20 | 2025-08-20_7a5ee5:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-08-27 | 2025-08-27_2abe4a7307_CSX Data 2025-08-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-08-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-08-27_2abe4a7307_CSX Data 2025-08-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-08-27 | 2025-08-27_2abe4a:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-07-02 | 2025-07-02_d6a4046cab_CSX Data 2025-07-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-07-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-07-02_d6a4046cab_CSX Data 2025-07-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-07-02 | 2025-07-02_d6a404:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-07-09 | 2025-07-09_063e626d77_CSX Data 2025-07-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-07-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-07-09_063e626d77_CSX Data 2025-07-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-07-09 | 2025-07-09_063e62:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-07-16 | 2025-07-16_eba2e654a5_CSX Data 2025-07-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-07-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-07-16_eba2e654a5_CSX Data 2025-07-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-07-16 | 2025-07-16_eba2e6:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-07-23 | 2025-07-23_742730bbf1_CSX Data 2025-07-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-07-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-07-23_742730bbf1_CSX Data 2025-07-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-07-23 | 2025-07-23_742730:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-07-30 | 2025-07-30_40dfdb02f0_CSX Data 2025-07-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-07-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-07-30_40dfdb02f0_CSX Data 2025-07-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-07-30 | 2025-07-30_40dfdb:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-06-04 | 2025-06-04_3e2a90704c_CSX Data 2025-06-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-06-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-06-04_3e2a90704c_CSX Data 2025-06-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-06-04 | 2025-06-04_3e2a90:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-06-11 | 2025-06-11_556a01e908_CSX Data 2025-06-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-06-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-06-11_556a01e908_CSX Data 2025-06-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-06-11 | 2025-06-11_556a01:   0%|          | 0.00/51.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-06-18 | 2025-06-18_2475f5e416_CSX Data 2025-06-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-06-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-06-18_2475f5e416_CSX Data 2025-06-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-06-18 | 2025-06-18_2475f5:   0%|          | 0.00/51.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-06-25 | 2025-06-25_0cd7a51913_CSX Data 2025-06-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-06-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-06-25_0cd7a51913_CSX Data 2025-06-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-06-25 | 2025-06-25_0cd7a5:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-05-07 | 2025-05-07_da4c179e85_CSX Data 2025-05-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-05-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-05-07_da4c179e85_CSX Data 2025-05-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-05-07 | 2025-05-07_da4c17:   0%|          | 0.00/51.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-05-14 | 2025-05-14_279915fb0b_CSX Data 2025-05-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-05-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-05-14_279915fb0b_CSX Data 2025-05-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-05-14 | 2025-05-14_279915:   0%|          | 0.00/51.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-05-21 | 2025-05-21_39c6da6e71_CSX Data 2025-05-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-05-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-05-21_39c6da6e71_CSX Data 2025-05-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-05-21 | 2025-05-21_39c6da:   0%|          | 0.00/51.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-05-28 | 2025-05-28_516c4ee8dc_CSX Data 2025-05-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-05-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-05-28_516c4ee8dc_CSX Data 2025-05-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-05-28 | 2025-05-28_516c4e:   0%|          | 0.00/51.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-04-02 | 2025-04-02_e0d0f69f71_CSX Data 2025-04-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-04-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-04-02_e0d0f69f71_CSX Data 2025-04-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-04-02 | 2025-04-02_e0d0f6:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-04-09 | 2025-04-09_8014cdbbf0_CSX Data 2025-04-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-04-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-04-09_8014cdbbf0_CSX Data 2025-04-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-04-09 | 2025-04-09_8014cd:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-04-16 | 2025-04-16_26c78eef83_CSX Data 2025-04-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-04-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-04-16_26c78eef83_CSX Data 2025-04-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-04-16 | 2025-04-16_26c78e:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-04-23 | 2025-04-23_99999fdda8_CSX Data 2025-04-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-04-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-04-23_99999fdda8_CSX Data 2025-04-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-04-23 | 2025-04-23_99999f:   0%|          | 0.00/51.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-04-30 | 2025-04-30_b58601f807_CSX Data 2025-04-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-04-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-04-30_b58601f807_CSX Data 2025-04-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-04-30 | 2025-04-30_b58601:   0%|          | 0.00/51.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-03-05 | 2025-03-05_a263ddeb87_CSX Data 2025-03-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-03-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-03-05_a263ddeb87_CSX Data 2025-03-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-03-05 | 2025-03-05_a263dd:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-03-12 | 2025-03-12_014b4d26e3_CSX Data 2025-03-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-03-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-03-12_014b4d26e3_CSX Data 2025-03-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-03-12 | 2025-03-12_014b4d:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-03-19 | 2025-03-19_185bcbce77_CSX Data 2025-03-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-03-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-03-19_185bcbce77_CSX Data 2025-03-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-03-19 | 2025-03-19_185bcb:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-03-26 | 2025-03-26_e9b0736df7_CSX Data 2025-03-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-03-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-03-26_e9b0736df7_CSX Data 2025-03-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-03-26 | 2025-03-26_e9b073:   0%|          | 0.00/51.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-02-05 | 2025-02-05_de13d2bc6f_CSX Data 2025-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-02-05_de13d2bc6f_CSX Data 2025-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-02-05 | 2025-02-05_de13d2:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-02-12 | 2025-02-12_fb90d12df0_CSX Data 2025-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-02-12_fb90d12df0_CSX Data 2025-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-02-12 | 2025-02-12_fb90d1:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-02-19 | 2025-02-19_95072919ad_CSX Data 2025-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-02-19_95072919ad_CSX Data 2025-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-02-19 | 2025-02-19_950729:   0%|          | 0.00/50.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-02-26 | 2025-02-26_1a1664a240_CSX Data 2025-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-02-26_1a1664a240_CSX Data 2025-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-02-26 | 2025-02-26_1a1664:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-01-01 | 2025-01-01_310e881097_CSX Data 2025-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-01-01_310e881097_CSX Data 2025-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-01-01 | 2025-01-01_310e88:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-01-08 | 2025-01-08_28a4f37ef3_CSX Data 2025-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-01-08_28a4f37ef3_CSX Data 2025-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-01-08 | 2025-01-08_28a4f3:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-01-15 | 2025-01-15_b4fc68d4c1_CSX Data 2025-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-01-15_b4fc68d4c1_CSX Data 2025-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-01-15 | 2025-01-15_b4fc68:   0%|          | 0.00/50.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-01-22 | 2025-01-22_eca2819ba7_CSX Data 2025-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-01-22_eca2819ba7_CSX Data 2025-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-01-22 | 2025-01-22_eca281:   0%|          | 0.00/50.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2025-01-29 | 2025-01-29_948416edf8_CSX Data 2025-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202025-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2025\xlsx\2025-01-29_948416edf8_CSX Data 2025-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2025-01-29 | 2025-01-29_948416:   0%|          | 0.00/50.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-12-04 | 2024-12-04_fbae3e5500_CSX Data 2024-12-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-12-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-12-04_fbae3e5500_CSX Data 2024-12-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-12-04 | 2024-12-04_fbae3e:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-12-11 | 2024-12-11_e7bda0b336_CSX Data 2024-12-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-12-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-12-11_e7bda0b336_CSX Data 2024-12-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-12-11 | 2024-12-11_e7bda0:   0%|          | 0.00/50.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-12-18 | 2024-12-18_9851314c4e_CSX Data 2024-12-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-12-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-12-18_9851314c4e_CSX Data 2024-12-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-12-18 | 2024-12-18_985131:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-12-25 | 2024-12-25_d4403c9afc_CSX Data 2024-12-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-12-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-12-25_d4403c9afc_CSX Data 2024-12-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-12-25 | 2024-12-25_d4403c:   0%|          | 0.00/50.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-11-06 | 2024-11-06_680be12cc1_CSX Data 2024-11-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-11-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-11-06_680be12cc1_CSX Data 2024-11-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-11-06 | 2024-11-06_680be1:   0%|          | 0.00/50.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-11-13 | 2024-11-13_364e9b90c8_CSX Data 2024-11-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-11-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-11-13_364e9b90c8_CSX Data 2024-11-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-11-13 | 2024-11-13_364e9b:   0%|          | 0.00/50.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-11-20 | 2024-11-20_48bb42e347_CSX Data 2024-11-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-11-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-11-20_48bb42e347_CSX Data 2024-11-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-11-20 | 2024-11-20_48bb42:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-11-27 | 2024-11-27_eeef92991c_CSX Data 2024-11-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-11-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-11-27_eeef92991c_CSX Data 2024-11-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-11-27 | 2024-11-27_eeef92:   0%|          | 0.00/50.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-10-02 | 2024-10-02_8d906a68d6_CSX Data 2024-10-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-10-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-10-02_8d906a68d6_CSX Data 2024-10-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-10-02 | 2024-10-02_8d906a:   0%|          | 0.00/50.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-10-09 | 2024-10-09_79f1982cc7_CSX Data 2024-10-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-10-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-10-09_79f1982cc7_CSX Data 2024-10-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-10-09 | 2024-10-09_79f198:   0%|          | 0.00/50.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-10-16 | 2024-10-16_3b5de67569_CSX Data 2024-10-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-10-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-10-16_3b5de67569_CSX Data 2024-10-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-10-16 | 2024-10-16_3b5de6:   0%|          | 0.00/50.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-10-23 | 2024-10-23_2f889e3fc2_CSX Data 2024-10-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-10-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-10-23_2f889e3fc2_CSX Data 2024-10-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-10-23 | 2024-10-23_2f889e:   0%|          | 0.00/50.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-10-30 | 2024-10-30_0efcf06c66_CSX Data 2024-10-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-10-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-10-30_0efcf06c66_CSX Data 2024-10-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-10-30 | 2024-10-30_0efcf0:   0%|          | 0.00/50.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-09-04 | 2024-09-04_d0e47bfca5_CSX Data 2024-09-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-09-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-09-04_d0e47bfca5_CSX Data 2024-09-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-09-04 | 2024-09-04_d0e47b:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-09-11 | 2024-09-11_65f2a2287d_CSX Data 2024-09-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-09-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-09-11_65f2a2287d_CSX Data 2024-09-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-09-11 | 2024-09-11_65f2a2:   0%|          | 0.00/49.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-09-18 | 2024-09-18_7c122c0fee_CSX Data 2024-09-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-09-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-09-18_7c122c0fee_CSX Data 2024-09-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-09-18 | 2024-09-18_7c122c:   0%|          | 0.00/49.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-09-25 | 2024-09-25_f8611b60dd_CSX Data 2024-09-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-09-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-09-25_f8611b60dd_CSX Data 2024-09-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-09-25 | 2024-09-25_f8611b:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-08-07 | 2024-08-07_7538960c28_CSX Data 2024-08-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-08-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-08-07_7538960c28_CSX Data 2024-08-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-08-07 | 2024-08-07_753896:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-08-14 | 2024-08-14_bbb8b87bb6_CSX Data 2024-08-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-08-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-08-14_bbb8b87bb6_CSX Data 2024-08-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-08-14 | 2024-08-14_bbb8b8:   0%|          | 0.00/50.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-08-21 | 2024-08-21_7c73b1f2dc_CSX Data 2024-08-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-08-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-08-21_7c73b1f2dc_CSX Data 2024-08-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-08-21 | 2024-08-21_7c73b1:   0%|          | 0.00/50.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-08-28 | 2024-08-28_279d111988_CSX Data 2024-08-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-08-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-08-28_279d111988_CSX Data 2024-08-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-08-28 | 2024-08-28_279d11:   0%|          | 0.00/50.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-07-03 | 2024-07-03_ca722d6f76_CSX Data 2024-07-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-07-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-07-03_ca722d6f76_CSX Data 2024-07-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-07-03 | 2024-07-03_ca722d:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-07-10 | 2024-07-10_ee89042d09_CSX Data 2024-07-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-07-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-07-10_ee89042d09_CSX Data 2024-07-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-07-10 | 2024-07-10_ee8904:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-07-17 | 2024-07-17_a1922a0aac_CSX Data 2024-07-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-07-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-07-17_a1922a0aac_CSX Data 2024-07-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-07-17 | 2024-07-17_a1922a:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-07-24 | 2024-07-24_cc7404f2f6_CSX Data 2024-07-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-07-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-07-24_cc7404f2f6_CSX Data 2024-07-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-07-24 | 2024-07-24_cc7404:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-07-31 | 2024-07-31_a285058f2a_CSX Data 2024-07-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-07-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-07-31_a285058f2a_CSX Data 2024-07-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-07-31 | 2024-07-31_a28505:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-06-05 | 2024-06-05_d92c77c209_CSX Data 2024-06-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-06-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-06-05_d92c77c209_CSX Data 2024-06-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-06-05 | 2024-06-05_d92c77:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-06-12 | 2024-06-12_5d656791ec_CSX Data 2024-06-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-06-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-06-12_5d656791ec_CSX Data 2024-06-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-06-12 | 2024-06-12_5d6567:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-06-19 | 2024-06-19_f0a339457c_CSX Data 2024-06-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-06-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-06-19_f0a339457c_CSX Data 2024-06-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-06-19 | 2024-06-19_f0a339:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-06-26 | 2024-06-26_903944bcfc_CSX Data 2024-06-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-06-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-06-26_903944bcfc_CSX Data 2024-06-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-06-26 | 2024-06-26_903944:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-05-01 | 2024-05-01_c0b3bbbfe3_CSX Data 2024-05-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-05-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-05-01_c0b3bbbfe3_CSX Data 2024-05-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-05-01 | 2024-05-01_c0b3bb:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-05-08 | 2024-05-08_397cb03208_CSX Data 2024-05-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-05-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-05-08_397cb03208_CSX Data 2024-05-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-05-08 | 2024-05-08_397cb0:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-05-15 | 2024-05-15_71fe3c729e_CSX Data 2024-05-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-05-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-05-15_71fe3c729e_CSX Data 2024-05-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-05-15 | 2024-05-15_71fe3c:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-05-22 | 2024-05-22_7e16854f47_CSX Data 2024-05-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-05-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-05-22_7e16854f47_CSX Data 2024-05-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-05-22 | 2024-05-22_7e1685:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-05-29 | 2024-05-29_97ca9e475d_CSX Data 2024-05-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-05-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-05-29_97ca9e475d_CSX Data 2024-05-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-05-29 | 2024-05-29_97ca9e:   0%|          | 0.00/49.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-04-03 | 2024-04-03_08f4f8a4a6_CSX Data 2024-04-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-04-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-04-03_08f4f8a4a6_CSX Data 2024-04-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-04-03 | 2024-04-03_08f4f8:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-04-10 | 2024-04-10_54b0f1d0a6_CSX Data 2024-04-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-04-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-04-10_54b0f1d0a6_CSX Data 2024-04-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-04-10 | 2024-04-10_54b0f1:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-04-17 | 2024-04-17_5488b199e9_CSX Data 2024-04-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-04-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-04-17_5488b199e9_CSX Data 2024-04-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-04-17 | 2024-04-17_5488b1:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-04-24 | 2024-04-24_ac860a140c_CSX Data 2024-04-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-04-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-04-24_ac860a140c_CSX Data 2024-04-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-04-24 | 2024-04-24_ac860a:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-03-06 | 2024-03-06_f0e332b7fb_CSX Data 2024-03-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-03-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-03-06_f0e332b7fb_CSX Data 2024-03-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-03-06 | 2024-03-06_f0e332:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-03-13 | 2024-03-13_89c9d87c9c_CSX Data 2024-03-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-03-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-03-13_89c9d87c9c_CSX Data 2024-03-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-03-13 | 2024-03-13_89c9d8:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-03-20 | 2024-03-20_880e7dfc49_CSX Data 2024-03-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-03-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-03-20_880e7dfc49_CSX Data 2024-03-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-03-20 | 2024-03-20_880e7d:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-03-27 | 2024-03-27_a39d646a04_CSX Data 2024-03-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-03-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-03-27_a39d646a04_CSX Data 2024-03-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-03-27 | 2024-03-27_a39d64:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-02-07 | 2024-02-07_52f19a9b5c_CSX Data 2024-02-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-02-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-02-07_52f19a9b5c_CSX Data 2024-02-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-02-07 | 2024-02-07_52f19a:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-02-14 | 2024-02-14_cd7ed4d7c3_CSX Data 2024-02-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-02-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-02-14_cd7ed4d7c3_CSX Data 2024-02-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-02-14 | 2024-02-14_cd7ed4:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-02-21 | 2024-02-21_209bf927cb_CSX Data 2024-02-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-02-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-02-21_209bf927cb_CSX Data 2024-02-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-02-21 | 2024-02-21_209bf9:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-02-28 | 2024-02-28_6719c9f07c_CSX Data 2024-02-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-02-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-02-28_6719c9f07c_CSX Data 2024-02-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-02-28 | 2024-02-28_6719c9:   0%|          | 0.00/50.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-01-03 | 2024-01-03_84396e30d8_CSX Data 2024-01-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-01-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-01-03_84396e30d8_CSX Data 2024-01-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-01-03 | 2024-01-03_84396e:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-01-10 | 2024-01-10_e6a9d18922_CSX Data 2024-01-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-01-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-01-10_e6a9d18922_CSX Data 2024-01-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-01-10 | 2024-01-10_e6a9d1:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-01-17 | 2024-01-17_174a63c777_CSX Data 2024-01-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-01-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-01-17_174a63c777_CSX Data 2024-01-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-01-17 | 2024-01-17_174a63:   0%|          | 0.00/50.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-01-24 | 2024-01-24_390a4aa9d5_CSX Data 2024-01-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-01-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-01-24_390a4aa9d5_CSX Data 2024-01-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-01-24 | 2024-01-24_390a4a:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2024-01-31 | 2024-01-31_4107ba726a_CSX Data 2024-01-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202024-01-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2024\xlsx\2024-01-31_4107ba726a_CSX Data 2024-01-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2024-01-31 | 2024-01-31_4107ba:   0%|          | 0.00/50.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-12-06 | 2023-12-06_acb7728ea5_CSX Data 2023-12-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-12-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-12-06_acb7728ea5_CSX Data 2023-12-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-12-06 | 2023-12-06_acb772:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-12-13 | 2023-12-13_20a092efa3_CSX Data 2023-12-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-12-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-12-13_20a092efa3_CSX Data 2023-12-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-12-13 | 2023-12-13_20a092:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-12-20 | 2023-12-20_0e46cccb3c_CSX Data 2023-12-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-12-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-12-20_0e46cccb3c_CSX Data 2023-12-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-12-20 | 2023-12-20_0e46cc:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-12-27 | 2023-12-27_e60b642a6e_CSX Data 2023-12-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-12-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-12-27_e60b642a6e_CSX Data 2023-12-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-12-27 | 2023-12-27_e60b64:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-11-01 | 2023-11-01_9c0aba5ac2_CSX Data 2023-11-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-11-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-11-01_9c0aba5ac2_CSX Data 2023-11-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-11-01 | 2023-11-01_9c0aba:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-11-08 | 2023-11-08_d12ecc3f5a_CSX Data 2023-11-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-11-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-11-08_d12ecc3f5a_CSX Data 2023-11-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-11-08 | 2023-11-08_d12ecc:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-11-15 | 2023-11-15_24c021f20e_CSX Data 2023-11-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-11-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-11-15_24c021f20e_CSX Data 2023-11-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-11-15 | 2023-11-15_24c021:   0%|          | 0.00/44.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-11-22 | 2023-11-22_ced71c0c70_CSX Data 2023-11-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-11-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-11-22_ced71c0c70_CSX Data 2023-11-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-11-22 | 2023-11-22_ced71c:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-11-29 | 2023-11-29_46f4c5325a_CSX Data 2023-11-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-11-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-11-29_46f4c5325a_CSX Data 2023-11-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-11-29 | 2023-11-29_46f4c5:   0%|          | 0.00/50.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-10-04 | 2023-10-04_0ef62ee765_CSX Data 2023-10-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-10-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-10-04_0ef62ee765_CSX Data 2023-10-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-10-04 | 2023-10-04_0ef62e:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-10-11 | 2023-10-11_8ee964ea25_CSX Data 2023-10-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-10-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-10-11_8ee964ea25_CSX Data 2023-10-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-10-11 | 2023-10-11_8ee964:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-10-18 | 2023-10-18_37cd8cecaf_CSX Data 2023-10-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-10-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-10-18_37cd8cecaf_CSX Data 2023-10-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-10-18 | 2023-10-18_37cd8c:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-10-25 | 2023-10-25_c072f560db_CSX Data 2023-10-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-10-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-10-25_c072f560db_CSX Data 2023-10-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-10-25 | 2023-10-25_c072f5:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-09-06 | 2023-09-06_5972af614d_CSX Data 2023-09-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-09-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-09-06_5972af614d_CSX Data 2023-09-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-09-06 | 2023-09-06_5972af:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-09-13 | 2023-09-13_8618a18f10_CSX Data 2023-09-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-09-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-09-13_8618a18f10_CSX Data 2023-09-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-09-13 | 2023-09-13_8618a1:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-09-20 | 2023-09-20_bf23bed043_CSX Data 2023-09-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-09-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-09-20_bf23bed043_CSX Data 2023-09-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-09-20 | 2023-09-20_bf23be:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-09-27 | 2023-09-27_eeb65e0c49_CSX Data 2023-09-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-09-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-09-27_eeb65e0c49_CSX Data 2023-09-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-09-27 | 2023-09-27_eeb65e:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-08-02 | 2023-08-02_9adac5e24f_CSX Data 2023-08-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-08-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-08-02_9adac5e24f_CSX Data 2023-08-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-08-02 | 2023-08-02_9adac5:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-08-09 | 2023-08-09_08133a88e5_CSX Data 2023-08-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-08-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-08-09_08133a88e5_CSX Data 2023-08-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-08-09 | 2023-08-09_08133a:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-08-16 | 2023-08-16_6a4e48a55c_CSX Data 2023-08-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-08-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-08-16_6a4e48a55c_CSX Data 2023-08-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-08-16 | 2023-08-16_6a4e48:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-08-23 | 2023-08-23_f047b5678d_CSX Data 2023-08-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-08-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-08-23_f047b5678d_CSX Data 2023-08-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-08-23 | 2023-08-23_f047b5:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-08-30 | 2023-08-30_3b626a135d_CSX Data 2023-08-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-08-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-08-30_3b626a135d_CSX Data 2023-08-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-08-30 | 2023-08-30_3b626a:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-07-05 | 2023-07-05_2eda6b49c2_CSX Data 2023-07-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-07-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-07-05_2eda6b49c2_CSX Data 2023-07-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-07-05 | 2023-07-05_2eda6b:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-07-12 | 2023-07-12_b4b99918df_CSX Data 2023-07-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-07-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-07-12_b4b99918df_CSX Data 2023-07-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-07-12 | 2023-07-12_b4b999:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-07-19 | 2023-07-19_c609adc1e0_CSX Data 2023-07-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-07-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-07-19_c609adc1e0_CSX Data 2023-07-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-07-19 | 2023-07-19_c609ad:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-07-26 | 2023-07-26_1046ecaa10_CSX Data 2023-07-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-07-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-07-26_1046ecaa10_CSX Data 2023-07-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-07-26 | 2023-07-26_1046ec:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-06-07 | 2023-06-07_67f3be0c21_CSX Data 2023-06-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-06-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-06-07_67f3be0c21_CSX Data 2023-06-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-06-07 | 2023-06-07_67f3be:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-06-14 | 2023-06-14_bb443d0ce8_CSX Data 2023-06-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-06-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-06-14_bb443d0ce8_CSX Data 2023-06-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-06-14 | 2023-06-14_bb443d:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-06-21 | 2023-06-21_956296a950_CSX Data 2023-06-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-06-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-06-21_956296a950_CSX Data 2023-06-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-06-21 | 2023-06-21_956296:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-06-28 | 2023-06-28_d8b366dcae_CSX Data 2023-06-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-06-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-06-28_d8b366dcae_CSX Data 2023-06-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-06-28 | 2023-06-28_d8b366:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-05-03 | 2023-05-03_66ddad9392_CSX Data 2023-05-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-05-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-05-03_66ddad9392_CSX Data 2023-05-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-05-03 | 2023-05-03_66ddad:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-05-10 | 2023-05-10_13b2ed7b23_CSX Data 2023-05-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-05-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-05-10_13b2ed7b23_CSX Data 2023-05-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-05-10 | 2023-05-10_13b2ed:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-05-17 | 2023-05-17_e310b1e40a_CSX Data 2023-05-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-05-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-05-17_e310b1e40a_CSX Data 2023-05-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-05-17 | 2023-05-17_e310b1:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-05-24 | 2023-05-24_f81853c3b1_CSX Data 2023-05-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-05-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-05-24_f81853c3b1_CSX Data 2023-05-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-05-24 | 2023-05-24_f81853:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-05-31 | 2023-05-31_c633d4e3b1_CSX Data 2023-05-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-05-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-05-31_c633d4e3b1_CSX Data 2023-05-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-05-31 | 2023-05-31_c633d4:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-04-05 | 2023-04-05_8111a102f6_CSX Data 2023-04-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-04-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-04-05_8111a102f6_CSX Data 2023-04-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-04-05 | 2023-04-05_8111a1:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-04-12 | 2023-04-12_7a054e26c4_CSX Data 2023-04-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-04-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-04-12_7a054e26c4_CSX Data 2023-04-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-04-12 | 2023-04-12_7a054e:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-04-19 | 2023-04-19_113c542d80_CSX Data 2023-04-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-04-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-04-19_113c542d80_CSX Data 2023-04-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-04-19 | 2023-04-19_113c54:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-04-26 | 2023-04-26_1db6b69095_CSX Data 2023-04-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-04-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-04-26_1db6b69095_CSX Data 2023-04-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-04-26 | 2023-04-26_1db6b6:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-03-01 | 2023-03-01_bcc9d6d9b5_CSX Data 2023-03-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-03-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-03-01_bcc9d6d9b5_CSX Data 2023-03-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-03-01 | 2023-03-01_bcc9d6:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-03-08 | 2023-03-08_0aed71b4d2_CSX Data 2023-03-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-03-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-03-08_0aed71b4d2_CSX Data 2023-03-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-03-08 | 2023-03-08_0aed71:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-03-15 | 2023-03-15_f0e33d2d06_CSX Data 2023-03-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-03-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-03-15_f0e33d2d06_CSX Data 2023-03-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-03-15 | 2023-03-15_f0e33d:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-03-22 | 2023-03-22_aabee989b0_CSX Data 2023-03-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-03-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-03-22_aabee989b0_CSX Data 2023-03-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-03-22 | 2023-03-22_aabee9:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-03-29 | 2023-03-29_56bda47d9d_CSX Data 2023-03-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-03-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-03-29_56bda47d9d_CSX Data 2023-03-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-03-29 | 2023-03-29_56bda4:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-02-01 | 2023-02-01_4dbc352a35_CSX Data 2023-02-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-02-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-02-01_4dbc352a35_CSX Data 2023-02-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-02-01 | 2023-02-01_4dbc35:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-02-08 | 2023-02-08_257da9943f_CSX Data 2023-02-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-02-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-02-08_257da9943f_CSX Data 2023-02-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-02-08 | 2023-02-08_257da9:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-02-15 | 2023-02-15_c3c4da46ed_CSX Data 2023-02-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-02-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-02-15_c3c4da46ed_CSX Data 2023-02-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-02-15 | 2023-02-15_c3c4da:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-02-22 | 2023-02-22_814fb0d744_CSX Data 2023-02-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-02-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-02-22_814fb0d744_CSX Data 2023-02-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-02-22 | 2023-02-22_814fb0:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-01-04 | 2023-01-04_2059181e49_CSX Data 2023-01-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-01-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-01-04_2059181e49_CSX Data 2023-01-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-01-04 | 2023-01-04_205918:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-01-11 | 2023-01-11_e1009658a1_CSX Data 2023-01-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-01-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-01-11_e1009658a1_CSX Data 2023-01-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-01-11 | 2023-01-11_e10096:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-01-18 | 2023-01-18_3a1c2267de_CSX Data 2023-01-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-01-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-01-18_3a1c2267de_CSX Data 2023-01-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-01-18 | 2023-01-18_3a1c22:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2023-01-25 | 2023-01-25_eef5228718_CSX Data 2023-01-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202023-01-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2023\xlsx\2023-01-25_eef5228718_CSX Data 2023-01-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2023-01-25 | 2023-01-25_eef522:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-12-07 | 2022-12-07_c47d86285e_CSX Data 2022-12-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-12-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-12-07_c47d86285e_CSX Data 2022-12-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-12-07 | 2022-12-07_c47d86:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-12-14 | 2022-12-14_56579ae420_CSX Data 2022-12-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-12-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-12-14_56579ae420_CSX Data 2022-12-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-12-14 | 2022-12-14_56579a:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-12-21 | 2022-12-21_5eaaf2abd9_CSX Data 2022-12-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-12-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-12-21_5eaaf2abd9_CSX Data 2022-12-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-12-21 | 2022-12-21_5eaaf2:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-12-28 | 2022-12-28_05a4f9d7c9_CSX Data 2022-12-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-12-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-12-28_05a4f9d7c9_CSX Data 2022-12-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-12-28 | 2022-12-28_05a4f9:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-11-02 | 2022-11-02_522cb2d8aa_CSX Data 2022-11-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-11-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-11-02_522cb2d8aa_CSX Data 2022-11-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-11-02 | 2022-11-02_522cb2:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-11-09 | 2022-11-09_3ff4146245_CSX Data 2022-11-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-11-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-11-09_3ff4146245_CSX Data 2022-11-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-11-09 | 2022-11-09_3ff414:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-11-16 | 2022-11-16_025e2e3992_CSX Data 2022-11-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-11-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-11-16_025e2e3992_CSX Data 2022-11-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-11-16 | 2022-11-16_025e2e:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-11-23 | 2022-11-23_06483e0124_CSX Data 2022-11-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-11-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-11-23_06483e0124_CSX Data 2022-11-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-11-23 | 2022-11-23_06483e:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-11-30 | 2022-11-30_97766e0830_CSX Data 2022-11-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-11-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-11-30_97766e0830_CSX Data 2022-11-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-11-30 | 2022-11-30_97766e:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-10-05 | 2022-10-05_ebe415a7b0_CSX Data 2022-10-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-10-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-10-05_ebe415a7b0_CSX Data 2022-10-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-10-05 | 2022-10-05_ebe415:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-10-12 | 2022-10-12_d19df900a7_CSX Data 2022-10-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-10-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-10-12_d19df900a7_CSX Data 2022-10-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-10-12 | 2022-10-12_d19df9:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-10-19 | 2022-10-19_263b54d2eb_CSX Data 2022-10-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-10-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-10-19_263b54d2eb_CSX Data 2022-10-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-10-19 | 2022-10-19_263b54:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-10-26 | 2022-10-26_ae077cea9f_CSX Data 2022-10-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-10-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-10-26_ae077cea9f_CSX Data 2022-10-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-10-26 | 2022-10-26_ae077c:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-09-07 | 2022-09-07_0f562d7873_CSX Data 2022-09-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-09-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-09-07_0f562d7873_CSX Data 2022-09-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-09-07 | 2022-09-07_0f562d:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-09-14 | 2022-09-14_e342475764_CSX Data 2022-09-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-09-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-09-14_e342475764_CSX Data 2022-09-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-09-14 | 2022-09-14_e34247:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-09-21 | 2022-09-21_82585893b0_CSX Data 2022-09-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-09-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-09-21_82585893b0_CSX Data 2022-09-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-09-21 | 2022-09-21_825858:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-09-28 | 2022-09-28_a3fb98c1fb_CSX Data 2022-09-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-09-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-09-28_a3fb98c1fb_CSX Data 2022-09-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-09-28 | 2022-09-28_a3fb98:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-08-03 | 2022-08-03_92373a3115_CSX Data 2022-08-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-08-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-08-03_92373a3115_CSX Data 2022-08-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-08-03 | 2022-08-03_92373a:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-08-10 | 2022-08-10_9750ef906b_CSX Data 2022-08-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-08-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-08-10_9750ef906b_CSX Data 2022-08-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-08-10 | 2022-08-10_9750ef:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-08-17 | 2022-08-17_27bba60c32_CSX Data 2022-08-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-08-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-08-17_27bba60c32_CSX Data 2022-08-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-08-17 | 2022-08-17_27bba6:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-08-24 | 2022-08-24_9c75fcabbd_CSX Data 2022-08-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-08-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-08-24_9c75fcabbd_CSX Data 2022-08-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-08-24 | 2022-08-24_9c75fc:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-08-31 | 2022-08-31_ee629f55a3_CSX Data 2022-08-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-08-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-08-31_ee629f55a3_CSX Data 2022-08-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-08-31 | 2022-08-31_ee629f:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-07-06 | 2022-07-06_0b11af7c9c_CSX Data 2022-07-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-07-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-07-06_0b11af7c9c_CSX Data 2022-07-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-07-06 | 2022-07-06_0b11af:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-07-13 | 2022-07-13_5ba9488d21_CSX Data 2022-07-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-07-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-07-13_5ba9488d21_CSX Data 2022-07-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-07-13 | 2022-07-13_5ba948:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-07-20 | 2022-07-20_c241e7d21d_CSX Data 2022-07-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-07-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-07-20_c241e7d21d_CSX Data 2022-07-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-07-20 | 2022-07-20_c241e7:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-07-27 | 2022-07-27_b69be52d07_CSX Data 2022-07-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-07-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-07-27_b69be52d07_CSX Data 2022-07-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-07-27 | 2022-07-27_b69be5:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-06-01 | 2022-06-01_ddf8f779df_CSX Data 2022-06-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-06-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-06-01_ddf8f779df_CSX Data 2022-06-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-06-01 | 2022-06-01_ddf8f7:   0%|          | 0.00/45.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-06-08 | 2022-06-08_969378b392_CSX Data 2022-06-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-06-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-06-08_969378b392_CSX Data 2022-06-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-06-08 | 2022-06-08_969378:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-06-15 | 2022-06-15_5eafe98c99_CSX Data 2022-06-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-06-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-06-15_5eafe98c99_CSX Data 2022-06-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-06-15 | 2022-06-15_5eafe9:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-06-22 | 2022-06-22_a478df677f_CSX Data 2022-06-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-06-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-06-22_a478df677f_CSX Data 2022-06-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-06-22 | 2022-06-22_a478df:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-06-29 | 2022-06-29_d7a1973e3c_CSX Data 2022-06-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-06-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-06-29_d7a1973e3c_CSX Data 2022-06-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-06-29 | 2022-06-29_d7a197:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-05-04 | 2022-05-04_b4b30e094e_CSX Data 2022-05-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-05-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-05-04_b4b30e094e_CSX Data 2022-05-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-05-04 | 2022-05-04_b4b30e:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-05-11 | 2022-05-11_234a192a32_CSX Data 2022-05-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-05-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-05-11_234a192a32_CSX Data 2022-05-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-05-11 | 2022-05-11_234a19:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-05-18 | 2022-05-18_e3634e4e8e_CSX Data 2022-05-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-05-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-05-18_e3634e4e8e_CSX Data 2022-05-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-05-18 | 2022-05-18_e3634e:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-05-25 | 2022-05-25_c3c3f28092_CSX Data 2022-05-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-05-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-05-25_c3c3f28092_CSX Data 2022-05-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-05-25 | 2022-05-25_c3c3f2:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-04-06 | 2022-04-06_af3ae2e0ab_CSX Data 2022-04-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-04-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-04-06_af3ae2e0ab_CSX Data 2022-04-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-04-06 | 2022-04-06_af3ae2:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-04-13 | 2022-04-13_92656ac5ab_CSX Data 2022-04-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-04-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-04-13_92656ac5ab_CSX Data 2022-04-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-04-13 | 2022-04-13_92656a:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-04-20 | 2022-04-20_693ebbd63d_CSX Data 2022-04-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-04-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-04-20_693ebbd63d_CSX Data 2022-04-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-04-20 | 2022-04-20_693ebb:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-04-27 | 2022-04-27_85e958652f_CSX Data 2022-04-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-04-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-04-27_85e958652f_CSX Data 2022-04-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-04-27 | 2022-04-27_85e958:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-03-02 | 2022-03-02_9327a34d60_CSX Data 2022-03-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-03-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-03-02_9327a34d60_CSX Data 2022-03-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-03-02 | 2022-03-02_9327a3:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-03-09 | 2022-03-09_80c5d9c7a1_CSX Data 2022-03-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-03-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-03-09_80c5d9c7a1_CSX Data 2022-03-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-03-09 | 2022-03-09_80c5d9:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-03-16 | 2022-03-16_d7a2c051bb_CSX Data 2022-03-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-03-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-03-16_d7a2c051bb_CSX Data 2022-03-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-03-16 | 2022-03-16_d7a2c0:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-03-23 | 2022-03-23_fb7a8699db_CSX Data 2022-03-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-03-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-03-23_fb7a8699db_CSX Data 2022-03-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-03-23 | 2022-03-23_fb7a86:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-03-30 | 2022-03-30_ff00744846_CSX Data 2022-03-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-03-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-03-30_ff00744846_CSX Data 2022-03-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-03-30 | 2022-03-30_ff0074:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-02-02 | 2022-02-02_4b7f9800d1_CSX Data 2022-02-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-02-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-02-02_4b7f9800d1_CSX Data 2022-02-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-02-02 | 2022-02-02_4b7f98:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-02-09 | 2022-02-09_87a738cf4b_CSX Data 2022-02-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-02-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-02-09_87a738cf4b_CSX Data 2022-02-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-02-09 | 2022-02-09_87a738:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-02-16 | 2022-02-16_51d8d5a31c_CSX Data 2022-02-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-02-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-02-16_51d8d5a31c_CSX Data 2022-02-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-02-16 | 2022-02-16_51d8d5:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-02-23 | 2022-02-23_bd8a50eddf_CSX Data 2022-02-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-02-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-02-23_bd8a50eddf_CSX Data 2022-02-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-02-23 | 2022-02-23_bd8a50:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-01-05 | 2022-01-05_fdc4d53856_CSX Data 2022-01-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-01-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-01-05_fdc4d53856_CSX Data 2022-01-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-01-05 | 2022-01-05_fdc4d5:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-01-12 | 2022-01-12_1a66d7e56d_CSX Data 2022-01-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-01-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-01-12_1a66d7e56d_CSX Data 2022-01-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-01-12 | 2022-01-12_1a66d7:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-01-19 | 2022-01-19_d4dd59635f_CSX Data 2022-01-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-01-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-01-19_d4dd59635f_CSX Data 2022-01-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-01-19 | 2022-01-19_d4dd59:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2022-01-26 | 2022-01-26_8de57b2d09_CSX Data 2022-01-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202022-01-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2022\xlsx\2022-01-26_8de57b2d09_CSX Data 2022-01-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2022-01-26 | 2022-01-26_8de57b:   0%|          | 0.00/44.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-12-01 | 2021-12-01_7f52d86666_CSX Data 2021-12-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-12-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-12-01_7f52d86666_CSX Data 2021-12-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-12-01 | 2021-12-01_7f52d8:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-12-08 | 2021-12-08_3f1a6c6a77_CSX Data 2021-12-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-12-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-12-08_3f1a6c6a77_CSX Data 2021-12-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-12-08 | 2021-12-08_3f1a6c:   0%|          | 0.00/44.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-12-15 | 2021-12-15_8a1feb2757_CSX Data 2021-12-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-12-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-12-15_8a1feb2757_CSX Data 2021-12-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-12-15 | 2021-12-15_8a1feb:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-12-22 | 2021-12-22_89ab034657_CSX Data 2021-12-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-12-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-12-22_89ab034657_CSX Data 2021-12-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-12-22 | 2021-12-22_89ab03:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-12-29 | 2021-12-29_9de329719f_CSX Data 2021-12-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-12-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-12-29_9de329719f_CSX Data 2021-12-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-12-29 | 2021-12-29_9de329:   0%|          | 0.00/44.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-11-03 | 2021-11-03_0ed949798c_CSX Data 2021-11-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-11-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-11-03_0ed949798c_CSX Data 2021-11-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-11-03 | 2021-11-03_0ed949:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-11-10 | 2021-11-10_6aa7c4a3dd_CSX Data 2021-11-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-11-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-11-10_6aa7c4a3dd_CSX Data 2021-11-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-11-10 | 2021-11-10_6aa7c4:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-11-17 | 2021-11-17_ff85220661_CSX Data 2021-11-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-11-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-11-17_ff85220661_CSX Data 2021-11-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-11-17 | 2021-11-17_ff8522:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-11-24 | 2021-11-24_0ae6fd391c_CSX Data 2021-11-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-11-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-11-24_0ae6fd391c_CSX Data 2021-11-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-11-24 | 2021-11-24_0ae6fd:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-10-06 | 2021-10-06_80602ba156_CSX Data 2021-10-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-10-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-10-06_80602ba156_CSX Data 2021-10-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-10-06 | 2021-10-06_80602b:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-10-13 | 2021-10-13_8cf7fbd7e8_CSX Data 2021-10-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-10-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-10-13_8cf7fbd7e8_CSX Data 2021-10-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-10-13 | 2021-10-13_8cf7fb:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-10-20 | 2021-10-20_ad78791557_CSX Data 2021-10-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-10-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-10-20_ad78791557_CSX Data 2021-10-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-10-20 | 2021-10-20_ad7879:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-10-27 | 2021-10-27_10984050c9_CSX Data 2021-10-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-10-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-10-27_10984050c9_CSX Data 2021-10-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-10-27 | 2021-10-27_109840:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-09-01 | 2021-09-01_436cadd5bf_CSX Data 2021-09-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-09-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-09-01_436cadd5bf_CSX Data 2021-09-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-09-01 | 2021-09-01_436cad:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-09-08 | 2021-09-08_13986f52dd_CSX Data 2021-09-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-09-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-09-08_13986f52dd_CSX Data 2021-09-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-09-08 | 2021-09-08_13986f:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-09-15 | 2021-09-15_b1a68411d7_CSX Data 2021-09-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-09-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-09-15_b1a68411d7_CSX Data 2021-09-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-09-15 | 2021-09-15_b1a684:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-09-22 | 2021-09-22_d4dab503ba_CSX Data 2021-09-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-09-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-09-22_d4dab503ba_CSX Data 2021-09-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-09-22 | 2021-09-22_d4dab5:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-09-29 | 2021-09-29_12f39d83f8_CSX Data 2021-09-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-09-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-09-29_12f39d83f8_CSX Data 2021-09-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-09-29 | 2021-09-29_12f39d:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-08-04 | 2021-08-04_3a6eec5649_CSX Data 2021-08-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-08-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-08-04_3a6eec5649_CSX Data 2021-08-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-08-04 | 2021-08-04_3a6eec:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-08-11 | 2021-08-11_81f11f6aec_CSX Data 2021-08-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-08-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-08-11_81f11f6aec_CSX Data 2021-08-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-08-11 | 2021-08-11_81f11f:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-08-18 | 2021-08-18_baafbf5b23_CSX Data 2021-08-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-08-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-08-18_baafbf5b23_CSX Data 2021-08-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-08-18 | 2021-08-18_baafbf:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-08-25 | 2021-08-25_ef147931ac_CSX Data 2021-08-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-08-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-08-25_ef147931ac_CSX Data 2021-08-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-08-25 | 2021-08-25_ef1479:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-07-07 | 2021-07-07_dd7589c2f2_CSX Data 2021-07-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-07-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-07-07_dd7589c2f2_CSX Data 2021-07-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-07-07 | 2021-07-07_dd7589:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-07-14 | 2021-07-14_8f32adc151_CSX Data 2021-07-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-07-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-07-14_8f32adc151_CSX Data 2021-07-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-07-14 | 2021-07-14_8f32ad:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-07-21 | 2021-07-21_c36265f60d_CSX Data 2021-07-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-07-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-07-21_c36265f60d_CSX Data 2021-07-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-07-21 | 2021-07-21_c36265:   0%|          | 0.00/44.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-07-28 | 2021-07-28_b81a72e875_CSX Data 2021-07-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-07-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-07-28_b81a72e875_CSX Data 2021-07-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-07-28 | 2021-07-28_b81a72:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-06-02 | 2021-06-02_d3cbc44e89_CSX Data 2021-06-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-06-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-06-02_d3cbc44e89_CSX Data 2021-06-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-06-02 | 2021-06-02_d3cbc4:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-06-09 | 2021-06-09_67bb436202_CSX Data 2021-06-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-06-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-06-09_67bb436202_CSX Data 2021-06-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-06-09 | 2021-06-09_67bb43:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-06-16 | 2021-06-16_55c56e6204_CSX Data 2021-06-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-06-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-06-16_55c56e6204_CSX Data 2021-06-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-06-16 | 2021-06-16_55c56e:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-06-23 | 2021-06-23_38cc33f6da_CSX Data 2021-06-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-06-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-06-23_38cc33f6da_CSX Data 2021-06-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-06-23 | 2021-06-23_38cc33:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-06-30 | 2021-06-30_4f3ac1eb0d_CSX Data 2021-06-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-06-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-06-30_4f3ac1eb0d_CSX Data 2021-06-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-06-30 | 2021-06-30_4f3ac1:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-05-05 | 2021-05-05_bea45f4854_CSX Data 2021-05-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-05-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-05-05_bea45f4854_CSX Data 2021-05-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-05-05 | 2021-05-05_bea45f:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-05-12 | 2021-05-12_6fa872bac5_CSX Data 2021-05-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-05-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-05-12_6fa872bac5_CSX Data 2021-05-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-05-12 | 2021-05-12_6fa872:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-05-19 | 2021-05-19_4512cf9d8e_CSX Data 2021-05-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-05-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-05-19_4512cf9d8e_CSX Data 2021-05-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-05-19 | 2021-05-19_4512cf:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-05-26 | 2021-05-26_80000ad2a5_CSX Data 2021-05-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-05-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-05-26_80000ad2a5_CSX Data 2021-05-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-05-26 | 2021-05-26_80000a:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-04-07 | 2021-04-07_786fec58b2_CSX Data 2021-04-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-04-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-04-07_786fec58b2_CSX Data 2021-04-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-04-07 | 2021-04-07_786fec:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-04-14 | 2021-04-14_0ba4fdd2dd_CSX Data 2021-04-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-04-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-04-14_0ba4fdd2dd_CSX Data 2021-04-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-04-14 | 2021-04-14_0ba4fd:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-04-21 | 2021-04-21_3c0012137f_CSX Data 2021-04-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-04-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-04-21_3c0012137f_CSX Data 2021-04-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-04-21 | 2021-04-21_3c0012:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-04-28 | 2021-04-28_89869c3e8b_CSX Data 2021-04-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-04-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-04-28_89869c3e8b_CSX Data 2021-04-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-04-28 | 2021-04-28_89869c:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-03-03 | 2021-03-03_fe320bc7db_CSX Data 2021-03-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-03-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-03-03_fe320bc7db_CSX Data 2021-03-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-03-03 | 2021-03-03_fe320b:   0%|          | 0.00/45.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-03-10 | 2021-03-10_d0443d244b_CSX Data 2021-03-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-03-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-03-10_d0443d244b_CSX Data 2021-03-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-03-10 | 2021-03-10_d0443d:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-03-17 | 2021-03-17_541cc119bf_CSX Data 2021-03-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-03-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-03-17_541cc119bf_CSX Data 2021-03-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-03-17 | 2021-03-17_541cc1:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-03-24 | 2021-03-24_76cd69d00d_CSX Data 2021-03-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-03-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-03-24_76cd69d00d_CSX Data 2021-03-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-03-24 | 2021-03-24_76cd69:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-03-31 | 2021-03-31_7b3ebdb44d_CSX Data 2021-03-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-03-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-03-31_7b3ebdb44d_CSX Data 2021-03-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-03-31 | 2021-03-31_7b3ebd:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-02-03 | 2021-02-03_4f28f5bfe5_CSX Data 2021-02-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-02-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-02-03_4f28f5bfe5_CSX Data 2021-02-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-02-03 | 2021-02-03_4f28f5:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-02-10 | 2021-02-10_c2f68fcdab_CSX Data 2021-02-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-02-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-02-10_c2f68fcdab_CSX Data 2021-02-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-02-10 | 2021-02-10_c2f68f:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-02-17 | 2021-02-17_3a731a4dc2_CSX Data 2021-02-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-02-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-02-17_3a731a4dc2_CSX Data 2021-02-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-02-17 | 2021-02-17_3a731a:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-02-24 | 2021-02-24_70d13d953f_CSX Data 2021-02-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-02-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-02-24_70d13d953f_CSX Data 2021-02-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-02-24 | 2021-02-24_70d13d:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-01-06 | 2021-01-06_346c0b5fe9_CSX Data 2021-01-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-01-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-01-06_346c0b5fe9_CSX Data 2021-01-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-01-06 | 2021-01-06_346c0b:   0%|          | 0.00/44.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-01-13 | 2021-01-13_d81ee78052_CSX Data 2021-01-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-01-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-01-13_d81ee78052_CSX Data 2021-01-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-01-13 | 2021-01-13_d81ee7:   0%|          | 0.00/44.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-01-20 | 2021-01-20_49e3d7b755_CSX Data 2021-01-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-01-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-01-20_49e3d7b755_CSX Data 2021-01-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-01-20 | 2021-01-20_49e3d7:   0%|          | 0.00/45.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2021-01-27 | 2021-01-27_685e331dac_CSX Data 2021-01-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202021-01-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2021\xlsx\2021-01-27_685e331dac_CSX Data 2021-01-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2021-01-27 | 2021-01-27_685e33:   0%|          | 0.00/44.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-12-02 | 2020-12-02_ada37665a2_CSX Data 2020-12-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-12-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-12-02_ada37665a2_CSX Data 2020-12-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-12-02 | 2020-12-02_ada376:   0%|          | 0.00/47.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-12-09 | 2020-12-09_94b1804984_CSX Data 2020-12-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-12-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-12-09_94b1804984_CSX Data 2020-12-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-12-09 | 2020-12-09_94b180:   0%|          | 0.00/47.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-12-16 | 2020-12-16_b0eb234e1e_CSX Data 2020-12-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-12-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-12-16_b0eb234e1e_CSX Data 2020-12-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-12-16 | 2020-12-16_b0eb23:   0%|          | 0.00/43.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-12-23 | 2020-12-23_40f618a4d9_CSX Data 2020-12-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-12-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-12-23_40f618a4d9_CSX Data 2020-12-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-12-23 | 2020-12-23_40f618:   0%|          | 0.00/43.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-12-30 | 2020-12-30_ffc28cda66_CSX Data 2020-12-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-12-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-12-30_ffc28cda66_CSX Data 2020-12-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-12-30 | 2020-12-30_ffc28c:   0%|          | 0.00/43.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-11-04 | 2020-11-04_73a6006256_CSX Data 2020-11-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-11-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-11-04_73a6006256_CSX Data 2020-11-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-11-04 | 2020-11-04_73a600:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-11-11 | 2020-11-11_567f70884c_CSX Data 2020-11-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-11-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-11-11_567f70884c_CSX Data 2020-11-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-11-11 | 2020-11-11_567f70:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-11-18 | 2020-11-18_b42956386a_CSX Data 2020-11-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-11-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-11-18_b42956386a_CSX Data 2020-11-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-11-18 | 2020-11-18_b42956:   0%|          | 0.00/43.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-11-25 | 2020-11-25_485d1dd94c_CSX Data 2020-11-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-11-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-11-25_485d1dd94c_CSX Data 2020-11-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-11-25 | 2020-11-25_485d1d:   0%|          | 0.00/43.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-10-07 | 2020-10-07_80d2a78092_CSX Data 2020-10-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-10-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-10-07_80d2a78092_CSX Data 2020-10-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-10-07 | 2020-10-07_80d2a7:   0%|          | 0.00/44.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-10-14 | 2020-10-14_f19f41bf99_CSX Data 2020-10-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-10-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-10-14_f19f41bf99_CSX Data 2020-10-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-10-14 | 2020-10-14_f19f41:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-10-21 | 2020-10-21_fd56f26328_CSX Data 2020-10-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-10-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-10-21_fd56f26328_CSX Data 2020-10-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-10-21 | 2020-10-21_fd56f2:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-10-28 | 2020-10-28_3dbdd1eb98_CSX Data 2020-10-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-10-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-10-28_3dbdd1eb98_CSX Data 2020-10-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-10-28 | 2020-10-28_3dbdd1:   0%|          | 0.00/45.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-09-02 | 2020-09-02_36ce1a364c_CSX Data 2020-09-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-09-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-09-02_36ce1a364c_CSX Data 2020-09-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-09-02 | 2020-09-02_36ce1a:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-09-09 | 2020-09-09_a2a9343683_CSX Data 2020-09-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-09-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-09-09_a2a9343683_CSX Data 2020-09-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-09-09 | 2020-09-09_a2a934:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-09-16 | 2020-09-16_c6322f7aad_CSX Data 2020-09-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-09-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-09-16_c6322f7aad_CSX Data 2020-09-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-09-16 | 2020-09-16_c6322f:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-09-23 | 2020-09-23_2b02b362fd_CSX Data 2020-09-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-09-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-09-23_2b02b362fd_CSX Data 2020-09-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-09-23 | 2020-09-23_2b02b3:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-09-30 | 2020-09-30_75b055a830_CSX Data 2020-09-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-09-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-09-30_75b055a830_CSX Data 2020-09-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-09-30 | 2020-09-30_75b055:   0%|          | 0.00/44.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-08-05 | 2020-08-05_b3d85c7116_CSX Data 2020-08-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-08-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-08-05_b3d85c7116_CSX Data 2020-08-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-08-05 | 2020-08-05_b3d85c:   0%|          | 0.00/45.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-08-12 | 2020-08-12_bada08c41b_CSX Data 2020-08-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-08-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-08-12_bada08c41b_CSX Data 2020-08-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-08-12 | 2020-08-12_bada08:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-08-19 | 2020-08-19_d4e46ec028_CSX Data 2020-08-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-08-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-08-19_d4e46ec028_CSX Data 2020-08-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-08-19 | 2020-08-19_d4e46e:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-08-26 | 2020-08-26_2572fdfc4a_CSX Data 2020-08-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-08-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-08-26_2572fdfc4a_CSX Data 2020-08-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-08-26 | 2020-08-26_2572fd:   0%|          | 0.00/45.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-07-01 | 2020-07-01_12ba57867a_csx_data_2020-07-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-07-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-07-01_12ba57867a_csx_data_2020-07-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-07-01 | 2020-07-01_12ba57:   0%|          | 0.00/43.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-07-08 | 2020-07-08_ce8780aee2_csx_data_2020-07-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-07-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-07-08_ce8780aee2_csx_data_2020-07-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-07-08 | 2020-07-08_ce8780:   0%|          | 0.00/43.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-07-15 | 2020-07-15_447c9f614a_csx_data_2020-07-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-07-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-07-15_447c9f614a_csx_data_2020-07-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-07-15 | 2020-07-15_447c9f:   0%|          | 0.00/43.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-07-22 | 2020-07-22_c010bbf102_csx_data_2020-07-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-07-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-07-22_c010bbf102_csx_data_2020-07-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-07-22 | 2020-07-22_c010bb:   0%|          | 0.00/45.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-07-29 | 2020-07-29_e912077d04_CSX Data 2020-07-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/CSX%20Data%202020-07-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-07-29_e912077d04_CSX Data 2020-07-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-07-29 | 2020-07-29_e91207:   0%|          | 0.00/45.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-06-03 | 2020-06-03_463a7d15e0_csx_data_2020-06-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-06-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-06-03_463a7d15e0_csx_data_2020-06-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-06-03 | 2020-06-03_463a7d:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-06-10 | 2020-06-10_b5efb9f270_csx_data_2020-06-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-06-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-06-10_b5efb9f270_csx_data_2020-06-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-06-10 | 2020-06-10_b5efb9:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-06-17 | 2020-06-17_8f7613e078_csx_data_2020-06-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-06-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-06-17_8f7613e078_csx_data_2020-06-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-06-17 | 2020-06-17_8f7613:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-06-24 | 2020-06-24_0e7e692961_csx_data_2020-06-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-06-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-06-24_0e7e692961_csx_data_2020-06-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-06-24 | 2020-06-24_0e7e69:   0%|          | 0.00/43.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-05-06 | 2020-05-06_b0d3fde47c_csx_data_2020-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-05-06_b0d3fde47c_csx_data_2020-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-05-06 | 2020-05-06_b0d3fd:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-05-13 | 2020-05-13_01f7652ef0_csx_data_2020-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-05-13_01f7652ef0_csx_data_2020-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-05-13 | 2020-05-13_01f765:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-05-20 | 2020-05-20_d7ab764c05_csx_data_2020-05-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-05-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-05-20_d7ab764c05_csx_data_2020-05-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-05-20 | 2020-05-20_d7ab76:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-05-27 | 2020-05-27_96881fe9cb_csx_data_2020-05-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-05-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-05-27_96881fe9cb_csx_data_2020-05-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-05-27 | 2020-05-27_96881f:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-04-01 | 2020-04-01_217169e7ba_csx_data_2020-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-04-01_217169e7ba_csx_data_2020-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-04-01 | 2020-04-01_217169:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-04-08 | 2020-04-08_da84500074_csx_data_2020-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-04-08_da84500074_csx_data_2020-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-04-08 | 2020-04-08_da8450:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-04-15 | 2020-04-15_6469297ab6_csx_data_2020-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-04-15_6469297ab6_csx_data_2020-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-04-15 | 2020-04-15_646929:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-04-22 | 2020-04-22_27c75a4d06_csx_data_2020-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-04-22_27c75a4d06_csx_data_2020-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-04-22 | 2020-04-22_27c75a:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-04-29 | 2020-04-29_190c707c8b_csx_data_2020-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-04-29_190c707c8b_csx_data_2020-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-04-29 | 2020-04-29_190c70:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-03-04 | 2020-03-04_b99c79831e_csx_data_2020-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-03-04_b99c79831e_csx_data_2020-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-03-04 | 2020-03-04_b99c79:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-03-11 | 2020-03-11_84f9e2e140_csx_data_2020-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-03-11_84f9e2e140_csx_data_2020-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-03-11 | 2020-03-11_84f9e2:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-03-18 | 2020-03-18_5c0461bacf_csx_data_2020-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-03-18_5c0461bacf_csx_data_2020-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-03-18 | 2020-03-18_5c0461:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-03-25 | 2020-03-25_70d31695ed_csx_data_2020-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-03-25_70d31695ed_csx_data_2020-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-03-25 | 2020-03-25_70d316:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-02-05 | 2020-02-05_6d82648c95_csx_data_2020-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-02-05_6d82648c95_csx_data_2020-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-02-05 | 2020-02-05_6d8264:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-02-12 | 2020-02-12_bbbcd11411_csx_data_2020-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-02-12_bbbcd11411_csx_data_2020-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-02-12 | 2020-02-12_bbbcd1:   0%|          | 0.00/43.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-02-19 | 2020-02-19_c2be513b0b_csx_data_2020-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-02-19_c2be513b0b_csx_data_2020-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-02-19 | 2020-02-19_c2be51:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-02-26 | 2020-02-26_3501f85d8d_csx_data_2020-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-02-26_3501f85d8d_csx_data_2020-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-02-26 | 2020-02-26_3501f8:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-01-01 | 2020-01-01_a8c584414a_csx_data_2020-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-01-01_a8c584414a_csx_data_2020-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-01-01 | 2020-01-01_a8c584:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-01-08 | 2020-01-08_cb710dc6fd_csx_data_2020-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-01-08_cb710dc6fd_csx_data_2020-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-01-08 | 2020-01-08_cb710d:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-01-15 | 2020-01-15_f99691defa_csx_data_2020-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-01-15_f99691defa_csx_data_2020-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-01-15 | 2020-01-15_f99691:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-01-22 | 2020-01-22_9e10c03423_csx_data_2020-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-01-22_9e10c03423_csx_data_2020-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-01-22 | 2020-01-22_9e10c0:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | csx | 2020-01-29 | 2020-01-29_9b0f34c7de_csx_data_2020-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CSX/csx_data_2020-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\csx\2020\xlsx\2020-01-29_9b0f34c7de_csx_data_2020-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | csx | 2020-01-29 | 2020-01-29_9b0f34:   0%|          | 0.00/43.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-05-06 | 2026-05-06_fc6494e0b3_Chicago Data 2026-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-05-06_fc6494e0b3_Chicago Data 2026-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-05-06 | 2026-05-06_fc649:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-05-13 | 2026-05-13_d95afeda6b_Chicago Data 2026-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-05-13_d95afeda6b_Chicago Data 2026-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-05-13 | 2026-05-13_d95af:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-04-01 | 2026-04-01_a19346feba_Chicago Data 2026-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-04-01_a19346feba_Chicago Data 2026-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-04-01 | 2026-04-01_a1934:   0%|          | 0.00/31.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-04-08 | 2026-04-08_a14168cd06_Chicago Data 2026-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-04-08_a14168cd06_Chicago Data 2026-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-04-08 | 2026-04-08_a1416:   0%|          | 0.00/31.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-04-15 | 2026-04-15_09c7b3e489_Chicago Data 2026-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-04-15_09c7b3e489_Chicago Data 2026-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-04-15 | 2026-04-15_09c7b:   0%|          | 0.00/31.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-04-22 | 2026-04-22_40b9a1f217_Chicago Data 2026-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-04-22_40b9a1f217_Chicago Data 2026-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-04-22 | 2026-04-22_40b9a:   0%|          | 0.00/31.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-04-29 | 2026-04-29_ac73ecd298_Chicago Data 2026-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-04-29_ac73ecd298_Chicago Data 2026-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-04-29 | 2026-04-29_ac73e:   0%|          | 0.00/31.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-03-04 | 2026-03-04_f1c5780ed3_Chicago Data 2026-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-03-04_f1c5780ed3_Chicago Data 2026-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-03-04 | 2026-03-04_f1c57:   0%|          | 0.00/29.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-03-11 | 2026-03-11_2d2321224d_Chicago Data 2026-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-03-11_2d2321224d_Chicago Data 2026-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-03-11 | 2026-03-11_2d232:   0%|          | 0.00/31.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-03-18 | 2026-03-18_e029b41fd3_Chicago Data 2026-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-03-18_e029b41fd3_Chicago Data 2026-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-03-18 | 2026-03-18_e029b:   0%|          | 0.00/29.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-03-25 | 2026-03-25_9610f00b34_Chicago Data 2026-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-03-25_9610f00b34_Chicago Data 2026-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-03-25 | 2026-03-25_9610f:   0%|          | 0.00/29.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-02-04 | 2026-02-04_f02477b7aa_Chicago Data 2026-02-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-02-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-02-04_f02477b7aa_Chicago Data 2026-02-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-02-04 | 2026-02-04_f0247:   0%|          | 0.00/29.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-02-11 | 2026-02-11_f4b8c88883_Chicago Data 2026-02-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-02-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-02-11_f4b8c88883_Chicago Data 2026-02-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-02-11 | 2026-02-11_f4b8c:   0%|          | 0.00/29.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-02-18 | 2026-02-18_cc79993883_Chicago Data 2026-02-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-02-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-02-18_cc79993883_Chicago Data 2026-02-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-02-18 | 2026-02-18_cc799:   0%|          | 0.00/29.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-02-25 | 2026-02-25_4c1b81294a_Chicago Data 2026-02-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-02-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-02-25_4c1b81294a_Chicago Data 2026-02-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-02-25 | 2026-02-25_4c1b8:   0%|          | 0.00/29.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-01-07 | 2026-01-07_5c860ece0a_Chicago Data 2026-01-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-01-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-01-07_5c860ece0a_Chicago Data 2026-01-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-01-07 | 2026-01-07_5c860:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-01-14 | 2026-01-14_243b72b2fd_Chicago Data 2026-01-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-01-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-01-14_243b72b2fd_Chicago Data 2026-01-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-01-14 | 2026-01-14_243b7:   0%|          | 0.00/22.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-01-21 | 2026-01-21_c4b92077e2_Chicago Data 2026-01-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-01-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-01-21_c4b92077e2_Chicago Data 2026-01-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-01-21 | 2026-01-21_c4b92:   0%|          | 0.00/14.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2026-01-28 | 2026-01-28_b0c0b34bbc_Chicago Data 2026-01-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202026-01-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2026\xlsx\2026-01-28_b0c0b34bbc_Chicago Data 2026-01-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2026-01-28 | 2026-01-28_b0c0b:   0%|          | 0.00/29.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-12-31 | 2025-12-31_47db19fa20_Chicago Data 2025-12-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-12-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-12-31_47db19fa20_Chicago Data 2025-12-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-12-31 | 2025-12-31_47db1:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-12-03 | 2025-12-03_3daa7451c0_Chicago Data 2025-12-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-12-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-12-03_3daa7451c0_Chicago Data 2025-12-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-12-03 | 2025-12-03_3daa7:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-12-10 | 2025-12-10_33759ea67a_Chicago Data 2025-12-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-12-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-12-10_33759ea67a_Chicago Data 2025-12-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-12-10 | 2025-12-10_33759:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-12-17 | 2025-12-17_dccd06ff57_Chicago Data 2025-12-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-12-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-12-17_dccd06ff57_Chicago Data 2025-12-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-12-17 | 2025-12-17_dccd0:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-12-24 | 2025-12-24_365e8924e2_Chicago Data 2025-12-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-12-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-12-24_365e8924e2_Chicago Data 2025-12-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-12-24 | 2025-12-24_365e8:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-11-05 | 2025-11-05_563ebae37c_Chicago Data 2025-11-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-11-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-11-05_563ebae37c_Chicago Data 2025-11-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-11-05 | 2025-11-05_563eb:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-11-12 | 2025-11-12_7cc3c49559_Chicago Data 2025-11-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-11-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-11-12_7cc3c49559_Chicago Data 2025-11-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-11-12 | 2025-11-12_7cc3c:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-11-19 | 2025-11-19_307bdfce8d_Chicago Data 2025-11-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-11-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-11-19_307bdfce8d_Chicago Data 2025-11-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-11-19 | 2025-11-19_307bd:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-11-26 | 2025-11-26_011adceed3_Chicago Data 2025-11-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-11-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-11-26_011adceed3_Chicago Data 2025-11-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-11-26 | 2025-11-26_011ad:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-10-01 | 2025-10-01_0ef7154725_Chicago Data 2025-10-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-10-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-10-01_0ef7154725_Chicago Data 2025-10-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-10-01 | 2025-10-01_0ef71:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-10-08 | 2025-10-08_c7d4cf6e68_Chicago Data 2025-10-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-10-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-10-08_c7d4cf6e68_Chicago Data 2025-10-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-10-08 | 2025-10-08_c7d4c:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-10-15 | 2025-10-15_541c961e2b_Chicago Data 2025-10-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-10-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-10-15_541c961e2b_Chicago Data 2025-10-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-10-15 | 2025-10-15_541c9:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-10-22 | 2025-10-22_a843024c49_Chicago Data 2025-10-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-10-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-10-22_a843024c49_Chicago Data 2025-10-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-10-22 | 2025-10-22_a8430:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-10-29 | 2025-10-29_a3fe9babe1_Chicago Data 2025-10-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-10-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-10-29_a3fe9babe1_Chicago Data 2025-10-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-10-29 | 2025-10-29_a3fe9:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-09-03 | 2025-09-03_fb7ae2802b_Chicago Data 2025-09-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-09-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-09-03_fb7ae2802b_Chicago Data 2025-09-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-09-03 | 2025-09-03_fb7ae:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-09-10 | 2025-09-10_8f22d495eb_Chicago Data 2025-09-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-09-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-09-10_8f22d495eb_Chicago Data 2025-09-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-09-10 | 2025-09-10_8f22d:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-09-17 | 2025-09-17_01f788907e_Chicago Data 2025-09-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-09-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-09-17_01f788907e_Chicago Data 2025-09-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-09-17 | 2025-09-17_01f78:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-09-24 | 2025-09-24_1df4b5171e_Chicago Data 2025-09-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-09-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-09-24_1df4b5171e_Chicago Data 2025-09-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-09-24 | 2025-09-24_1df4b:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-08-06 | 2025-08-06_486d1e0341_Chicago Data 2025-08-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-08-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-08-06_486d1e0341_Chicago Data 2025-08-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-08-06 | 2025-08-06_486d1:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-08-13 | 2025-08-13_fad97da1c0_Chicago Data 2025-08-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-08-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-08-13_fad97da1c0_Chicago Data 2025-08-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-08-13 | 2025-08-13_fad97:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-08-20 | 2025-08-20_2f90b4d62d_Chicago Data 2025-08-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-08-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-08-20_2f90b4d62d_Chicago Data 2025-08-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-08-20 | 2025-08-20_2f90b:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-08-27 | 2025-08-27_c8ad1c421a_Chicago Data 2025-08-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-08-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-08-27_c8ad1c421a_Chicago Data 2025-08-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-08-27 | 2025-08-27_c8ad1:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-07-02 | 2025-07-02_c3bc3767f4_Chicago Data 2025-07-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-07-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-07-02_c3bc3767f4_Chicago Data 2025-07-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-07-02 | 2025-07-02_c3bc3:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-07-09 | 2025-07-09_ed4fe3960d_Chicago Data 2025-07-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-07-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-07-09_ed4fe3960d_Chicago Data 2025-07-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-07-09 | 2025-07-09_ed4fe:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-07-16 | 2025-07-16_57288faec6_Chicago Data 2025-07-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-07-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-07-16_57288faec6_Chicago Data 2025-07-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-07-16 | 2025-07-16_57288:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-07-23 | 2025-07-23_93036cce05_Chicago Data 2025-07-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-07-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-07-23_93036cce05_Chicago Data 2025-07-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-07-23 | 2025-07-23_93036:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-07-30 | 2025-07-30_c40851540b_Chicago Data 2025-07-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-07-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-07-30_c40851540b_Chicago Data 2025-07-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-07-30 | 2025-07-30_c4085:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-06-04 | 2025-06-04_b4cf72f6e6_Chicago Data 2025-06-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-06-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-06-04_b4cf72f6e6_Chicago Data 2025-06-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-06-04 | 2025-06-04_b4cf7:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-06-11 | 2025-06-11_e2aff101d1_Chicago Data 2025-06-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-06-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-06-11_e2aff101d1_Chicago Data 2025-06-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-06-11 | 2025-06-11_e2aff:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-06-18 | 2025-06-18_b35d7ab740_Chicago Data 2025-06-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-06-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-06-18_b35d7ab740_Chicago Data 2025-06-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-06-18 | 2025-06-18_b35d7:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-06-25 | 2025-06-25_ccfc3fb706_Chicago Data 2025-06-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-06-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-06-25_ccfc3fb706_Chicago Data 2025-06-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-06-25 | 2025-06-25_ccfc3:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-05-07 | 2025-05-07_c4f1c37d0c_Chicago Data 2025-05-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-05-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-05-07_c4f1c37d0c_Chicago Data 2025-05-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-05-07 | 2025-05-07_c4f1c:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-05-14 | 2025-05-14_1c8a06808a_Chicago Data 2025-05-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-05-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-05-14_1c8a06808a_Chicago Data 2025-05-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-05-14 | 2025-05-14_1c8a0:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-05-21 | 2025-05-21_416b5f6881_Chicago Data 2025-05-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-05-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-05-21_416b5f6881_Chicago Data 2025-05-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-05-21 | 2025-05-21_416b5:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-05-28 | 2025-05-28_768e6269cd_Chicago Data 2025-05-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-05-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-05-28_768e6269cd_Chicago Data 2025-05-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-05-28 | 2025-05-28_768e6:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-04-02 | 2025-04-02_a40462a765_Chicago Data 2025-04-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-04-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-04-02_a40462a765_Chicago Data 2025-04-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-04-02 | 2025-04-02_a4046:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-04-09 | 2025-04-09_9add1fb897_Chicago Data 2025-04-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-04-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-04-09_9add1fb897_Chicago Data 2025-04-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-04-09 | 2025-04-09_9add1:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-04-16 | 2025-04-16_4ab009554e_Chicago Data 2025-04-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-04-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-04-16_4ab009554e_Chicago Data 2025-04-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-04-16 | 2025-04-16_4ab00:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-04-23 | 2025-04-23_f3534a9ed5_Chicago Data 2025-04-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-04-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-04-23_f3534a9ed5_Chicago Data 2025-04-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-04-23 | 2025-04-23_f3534:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-04-30 | 2025-04-30_aeb5ad8a04_Chicago Data 2025-04-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-04-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-04-30_aeb5ad8a04_Chicago Data 2025-04-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-04-30 | 2025-04-30_aeb5a:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-03-05 | 2025-03-05_87b7d1bd99_Chicago Data 2025-03-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-03-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-03-05_87b7d1bd99_Chicago Data 2025-03-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-03-05 | 2025-03-05_87b7d:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-03-12 | 2025-03-12_45a8f18c2a_Chicago Data 2025-03-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-03-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-03-12_45a8f18c2a_Chicago Data 2025-03-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-03-12 | 2025-03-12_45a8f:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-03-19 | 2025-03-19_5115e2c85d_Chicago Data 2025-03-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-03-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-03-19_5115e2c85d_Chicago Data 2025-03-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-03-19 | 2025-03-19_5115e:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-03-26 | 2025-03-26_8b3568646f_Chicago Data 2025-03-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-03-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-03-26_8b3568646f_Chicago Data 2025-03-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-03-26 | 2025-03-26_8b356:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-02-05 | 2025-02-05_87b09e0864_Chicago Data 2025-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-02-05_87b09e0864_Chicago Data 2025-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-02-05 | 2025-02-05_87b09:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-02-12 | 2025-02-12_eff7a25882_Chicago Data 2025-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-02-12_eff7a25882_Chicago Data 2025-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-02-12 | 2025-02-12_eff7a:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-02-19 | 2025-02-19_0f0998ef58_Chicago Data 2025-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-02-19_0f0998ef58_Chicago Data 2025-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-02-19 | 2025-02-19_0f099:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-02-26 | 2025-02-26_d67c94bc07_Chicago Data 2025-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-02-26_d67c94bc07_Chicago Data 2025-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-02-26 | 2025-02-26_d67c9:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-01-01 | 2025-01-01_1f970d36ce_Chicago Data 2025-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-01-01_1f970d36ce_Chicago Data 2025-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-01-01 | 2025-01-01_1f970:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-01-08 | 2025-01-08_42e613f0cb_Chicago Data 2025-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-01-08_42e613f0cb_Chicago Data 2025-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-01-08 | 2025-01-08_42e61:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-01-15 | 2025-01-15_554edafa83_Chicago Data 2025-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-01-15_554edafa83_Chicago Data 2025-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-01-15 | 2025-01-15_554ed:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-01-22 | 2025-01-22_e1eea856ff_Chicago Data 2025-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-01-22_e1eea856ff_Chicago Data 2025-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-01-22 | 2025-01-22_e1eea:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2025-01-29 | 2025-01-29_bb8f479491_Chicago Data 2025-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202025-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2025\xlsx\2025-01-29_bb8f479491_Chicago Data 2025-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2025-01-29 | 2025-01-29_bb8f4:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-12-04 | 2024-12-04_c50b80a4d7_Chicago Data 2024-12-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-12-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-12-04_c50b80a4d7_Chicago Data 2024-12-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-12-04 | 2024-12-04_c50b8:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-12-11 | 2024-12-11_bd6d46f8f3_Chicago Data 2024-12-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-12-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-12-11_bd6d46f8f3_Chicago Data 2024-12-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-12-11 | 2024-12-11_bd6d4:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-12-18 | 2024-12-18_f5c5b2ca82_Chicago Data 2024-12-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-12-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-12-18_f5c5b2ca82_Chicago Data 2024-12-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-12-18 | 2024-12-18_f5c5b:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-12-25 | 2024-12-25_3e59d11bc0_Chicago Data 2024-12-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-12-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-12-25_3e59d11bc0_Chicago Data 2024-12-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-12-25 | 2024-12-25_3e59d:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-11-06 | 2024-11-06_ee60ea1ec1_Chicago Data 2024-11-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-11-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-11-06_ee60ea1ec1_Chicago Data 2024-11-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-11-06 | 2024-11-06_ee60e:   0%|          | 0.00/24.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-11-13 | 2024-11-13_cc16ee6251_Chicago Data 2024-11-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-11-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-11-13_cc16ee6251_Chicago Data 2024-11-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-11-13 | 2024-11-13_cc16e:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-11-20 | 2024-11-20_a0a58727e8_Chicago Data 2024-11-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-11-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-11-20_a0a58727e8_Chicago Data 2024-11-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-11-20 | 2024-11-20_a0a58:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-11-27 | 2024-11-27_1144cef427_Chicago Data 2024-11-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-11-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-11-27_1144cef427_Chicago Data 2024-11-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-11-27 | 2024-11-27_1144c:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-10-02 | 2024-10-02_dcd8f25e22_Chicago Data 2024-10-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-10-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-10-02_dcd8f25e22_Chicago Data 2024-10-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-10-02 | 2024-10-02_dcd8f:   0%|          | 0.00/23.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-10-09 | 2024-10-09_dfccfbf6f1_Chicago Data 2024-10-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-10-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-10-09_dfccfbf6f1_Chicago Data 2024-10-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-10-09 | 2024-10-09_dfccf:   0%|          | 0.00/23.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-10-16 | 2024-10-16_7e2eb2388c_Chicago Data 2024-10-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-10-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-10-16_7e2eb2388c_Chicago Data 2024-10-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-10-16 | 2024-10-16_7e2eb:   0%|          | 0.00/23.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-10-23 | 2024-10-23_6a03bdaef8_Chicago Data 2024-10-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-10-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-10-23_6a03bdaef8_Chicago Data 2024-10-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-10-23 | 2024-10-23_6a03b:   0%|          | 0.00/24.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-10-30 | 2024-10-30_ad40ae0246_Chicago Data 2024-10-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-10-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-10-30_ad40ae0246_Chicago Data 2024-10-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-10-30 | 2024-10-30_ad40a:   0%|          | 0.00/24.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-09-04 | 2024-09-04_ddd7fc05fe_Chicago Data 2024-09-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-09-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-09-04_ddd7fc05fe_Chicago Data 2024-09-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-09-04 | 2024-09-04_ddd7f:   0%|          | 0.00/21.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-09-11 | 2024-09-11_10a2e639b2_Chicago Data 2024-09-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-09-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-09-11_10a2e639b2_Chicago Data 2024-09-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-09-11 | 2024-09-11_10a2e:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-09-18 | 2024-09-18_95410515fe_Chicago Data 2024-09-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-09-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-09-18_95410515fe_Chicago Data 2024-09-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-09-18 | 2024-09-18_95410:   0%|          | 0.00/23.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-09-25 | 2024-09-25_b38511cb55_Chicago Data 2024-09-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-09-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-09-25_b38511cb55_Chicago Data 2024-09-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-09-25 | 2024-09-25_b3851:   0%|          | 0.00/23.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-08-07 | 2024-08-07_da5d3032e7_Chicago Data 2024-08-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-08-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-08-07_da5d3032e7_Chicago Data 2024-08-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-08-07 | 2024-08-07_da5d3:   0%|          | 0.00/21.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-08-14 | 2024-08-14_a010479f5c_Chicago Data 2024-08-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-08-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-08-14_a010479f5c_Chicago Data 2024-08-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-08-14 | 2024-08-14_a0104:   0%|          | 0.00/21.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-08-21 | 2024-08-21_fcaacffcd4_Chicago Data 2024-08-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-08-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-08-21_fcaacffcd4_Chicago Data 2024-08-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-08-21 | 2024-08-21_fcaac:   0%|          | 0.00/21.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-08-28 | 2024-08-28_aa9a045e6e_Chicago Data 2024-08-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-08-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-08-28_aa9a045e6e_Chicago Data 2024-08-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-08-28 | 2024-08-28_aa9a0:   0%|          | 0.00/21.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-07-03 | 2024-07-03_9345eed253_Chicago Data 2024-07-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-07-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-07-03_9345eed253_Chicago Data 2024-07-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-07-03 | 2024-07-03_9345e:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-07-10 | 2024-07-10_5de92c7633_Chicago Data 2024-07-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-07-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-07-10_5de92c7633_Chicago Data 2024-07-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-07-10 | 2024-07-10_5de92:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-07-17 | 2024-07-17_72c76186c2_Chicago Data 2024-07-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-07-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-07-17_72c76186c2_Chicago Data 2024-07-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-07-17 | 2024-07-17_72c76:   0%|          | 0.00/21.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-07-24 | 2024-07-24_e34bb3590d_Chicago Data 2024-07-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-07-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-07-24_e34bb3590d_Chicago Data 2024-07-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-07-24 | 2024-07-24_e34bb:   0%|          | 0.00/21.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-07-31 | 2024-07-31_b468dde2e9_Chicago Data 2024-07-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-07-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-07-31_b468dde2e9_Chicago Data 2024-07-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-07-31 | 2024-07-31_b468d:   0%|          | 0.00/21.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-06-05 | 2024-06-05_d8703eaded_Chicago Data 2024-06-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-06-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-06-05_d8703eaded_Chicago Data 2024-06-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-06-05 | 2024-06-05_d8703:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-06-12 | 2024-06-12_d080ebe8b5_Chicago Data 2024-06-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-06-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-06-12_d080ebe8b5_Chicago Data 2024-06-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-06-12 | 2024-06-12_d080e:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-06-19 | 2024-06-19_c8035b0d54_Chicago Data 2024-06-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-06-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-06-19_c8035b0d54_Chicago Data 2024-06-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-06-19 | 2024-06-19_c8035:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-06-26 | 2024-06-26_ec7f1faa6a_Chicago Data 2024-06-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-06-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-06-26_ec7f1faa6a_Chicago Data 2024-06-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-06-26 | 2024-06-26_ec7f1:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-05-01 | 2024-05-01_bd3c66f618_Chicago Data 2024-05-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-05-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-05-01_bd3c66f618_Chicago Data 2024-05-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-05-01 | 2024-05-01_bd3c6:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-05-08 | 2024-05-08_6c902d4d65_Chicago Data 2024-05-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-05-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-05-08_6c902d4d65_Chicago Data 2024-05-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-05-08 | 2024-05-08_6c902:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-05-15 | 2024-05-15_0e3f0160c8_Chicago Data 2024-05-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-05-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-05-15_0e3f0160c8_Chicago Data 2024-05-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-05-15 | 2024-05-15_0e3f0:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-05-22 | 2024-05-22_747b2e7205_Chicago Data 2024-05-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-05-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-05-22_747b2e7205_Chicago Data 2024-05-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-05-22 | 2024-05-22_747b2:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-05-29 | 2024-05-29_4ac7fe475a_Chicago Data 2024-05-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-05-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-05-29_4ac7fe475a_Chicago Data 2024-05-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-05-29 | 2024-05-29_4ac7f:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-04-03 | 2024-04-03_b4d4a9c521_Chicago Data 2024-04-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-04-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-04-03_b4d4a9c521_Chicago Data 2024-04-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-04-03 | 2024-04-03_b4d4a:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-04-10 | 2024-04-10_28fecb7e0d_Chicago Data 2024-04-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-04-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-04-10_28fecb7e0d_Chicago Data 2024-04-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-04-10 | 2024-04-10_28fec:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-04-17 | 2024-04-17_138ab8004c_Chicago Data 2024-04-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-04-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-04-17_138ab8004c_Chicago Data 2024-04-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-04-17 | 2024-04-17_138ab:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-04-24 | 2024-04-24_95cac46cc2_Chicago Data 2024-04-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-04-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-04-24_95cac46cc2_Chicago Data 2024-04-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-04-24 | 2024-04-24_95cac:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-03-06 | 2024-03-06_dfe3dc17b7_Chicago Data 2024-03-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-03-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-03-06_dfe3dc17b7_Chicago Data 2024-03-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-03-06 | 2024-03-06_dfe3d:   0%|          | 0.00/23.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-03-13 | 2024-03-13_04a663af8d_Chicago Data 2024-03-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-03-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-03-13_04a663af8d_Chicago Data 2024-03-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-03-13 | 2024-03-13_04a66:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-03-20 | 2024-03-20_fd922a1d54_Chicago Data 2024-03-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-03-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-03-20_fd922a1d54_Chicago Data 2024-03-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-03-20 | 2024-03-20_fd922:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-03-27 | 2024-03-27_621cdde537_Chicago Data 2024-03-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-03-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-03-27_621cdde537_Chicago Data 2024-03-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-03-27 | 2024-03-27_621cd:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-02-07 | 2024-02-07_abe46a4c60_Chicago Data 2024-02-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-02-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-02-07_abe46a4c60_Chicago Data 2024-02-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-02-07 | 2024-02-07_abe46:   0%|          | 0.00/24.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-02-14 | 2024-02-14_6f90ff45b0_Chicago Data 2024-02-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-02-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-02-14_6f90ff45b0_Chicago Data 2024-02-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-02-14 | 2024-02-14_6f90f:   0%|          | 0.00/24.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-02-21 | 2024-02-21_776bcc7620_Chicago Data 2024-02-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-02-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-02-21_776bcc7620_Chicago Data 2024-02-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-02-21 | 2024-02-21_776bc:   0%|          | 0.00/24.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-02-28 | 2024-02-28_119ab412b5_Chicago Data 2024-02-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-02-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-02-28_119ab412b5_Chicago Data 2024-02-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-02-28 | 2024-02-28_119ab:   0%|          | 0.00/24.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-01-03 | 2024-01-03_30cb4ffa2f_Chicago Data 2024-01-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-01-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-01-03_30cb4ffa2f_Chicago Data 2024-01-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-01-03 | 2024-01-03_30cb4:   0%|          | 0.00/24.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-01-10 | 2024-01-10_a37819baa1_Chicago Data 2024-01-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-01-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-01-10_a37819baa1_Chicago Data 2024-01-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-01-10 | 2024-01-10_a3781:   0%|          | 0.00/24.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-01-17 | 2024-01-17_7b80644de3_Chicago Data 2024-01-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-01-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-01-17_7b80644de3_Chicago Data 2024-01-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-01-17 | 2024-01-17_7b806:   0%|          | 0.00/24.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-01-24 | 2024-01-24_f3c8d167c5_Chicago Data 2024-01-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-01-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-01-24_f3c8d167c5_Chicago Data 2024-01-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-01-24 | 2024-01-24_f3c8d:   0%|          | 0.00/24.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2024-01-31 | 2024-01-31_213dbcf299_Chicago Data 2024-01-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202024-01-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2024\xlsx\2024-01-31_213dbcf299_Chicago Data 2024-01-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2024-01-31 | 2024-01-31_213db:   0%|          | 0.00/24.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-12-06 | 2023-12-06_b709200b9b_Chicago Data 2023-12-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-12-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-12-06_b709200b9b_Chicago Data 2023-12-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-12-06 | 2023-12-06_b7092:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-12-13 | 2023-12-13_ab431738b4_Chicago Data 2023-12-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-12-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-12-13_ab431738b4_Chicago Data 2023-12-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-12-13 | 2023-12-13_ab431:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-12-20 | 2023-12-20_1722ff77c9_Chicago Data 2023-12-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-12-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-12-20_1722ff77c9_Chicago Data 2023-12-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-12-20 | 2023-12-20_1722f:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-12-27 | 2023-12-27_d0e3d90345_Chicago Data 2023-12-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-12-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-12-27_d0e3d90345_Chicago Data 2023-12-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-12-27 | 2023-12-27_d0e3d:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-11-01 | 2023-11-01_1b1af68aae_Chicago Data 2023-11-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-11-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-11-01_1b1af68aae_Chicago Data 2023-11-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-11-01 | 2023-11-01_1b1af:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-11-08 | 2023-11-08_1fae0fdc7c_Chicago Data 2023-11-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-11-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-11-08_1fae0fdc7c_Chicago Data 2023-11-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-11-08 | 2023-11-08_1fae0:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-11-15 | 2023-11-15_d9b7306aa8_Chicago Data 2023-11-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-11-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-11-15_d9b7306aa8_Chicago Data 2023-11-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-11-15 | 2023-11-15_d9b73:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-11-22 | 2023-11-22_d27dc99fb0_Chicago Data 2023-11-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-11-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-11-22_d27dc99fb0_Chicago Data 2023-11-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-11-22 | 2023-11-22_d27dc:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-11-29 | 2023-11-29_3b7237d556_Chicago Data 2023-11-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-11-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-11-29_3b7237d556_Chicago Data 2023-11-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-11-29 | 2023-11-29_3b723:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-10-04 | 2023-10-04_a1e5ccf1e7_Chicago Data 2023-10-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-10-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-10-04_a1e5ccf1e7_Chicago Data 2023-10-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-10-04 | 2023-10-04_a1e5c:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-10-11 | 2023-10-11_b4304f293d_Chicago Data 2023-10-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-10-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-10-11_b4304f293d_Chicago Data 2023-10-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-10-11 | 2023-10-11_b4304:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-10-18 | 2023-10-18_c7610cc77f_Chicago Data 2023-10-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-10-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-10-18_c7610cc77f_Chicago Data 2023-10-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-10-18 | 2023-10-18_c7610:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-10-25 | 2023-10-25_346d5e6f7b_Chicago Data 2023-10-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-10-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-10-25_346d5e6f7b_Chicago Data 2023-10-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-10-25 | 2023-10-25_346d5:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-09-06 | 2023-09-06_f43ac6edcd_Chicago Data 2023-09-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-09-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-09-06_f43ac6edcd_Chicago Data 2023-09-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-09-06 | 2023-09-06_f43ac:   0%|          | 0.00/24.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-09-13 | 2023-09-13_8fb2fe7f27_Chicago Data 2023-09-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-09-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-09-13_8fb2fe7f27_Chicago Data 2023-09-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-09-13 | 2023-09-13_8fb2f:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-09-20 | 2023-09-20_0a1704ce4f_Chicago Data 2023-09-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-09-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-09-20_0a1704ce4f_Chicago Data 2023-09-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-09-20 | 2023-09-20_0a170:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-09-27 | 2023-09-27_2251360a02_Chicago Data 2023-09-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-09-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-09-27_2251360a02_Chicago Data 2023-09-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-09-27 | 2023-09-27_22513:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-08-02 | 2023-08-02_d9842b12a7_Chicago Data 2023-08-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-08-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-08-02_d9842b12a7_Chicago Data 2023-08-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-08-02 | 2023-08-02_d9842:   0%|          | 0.00/22.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-08-09 | 2023-08-09_db0e11d472_Chicago Data 2023-08-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-08-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-08-09_db0e11d472_Chicago Data 2023-08-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-08-09 | 2023-08-09_db0e1:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-08-16 | 2023-08-16_033023719e_Chicago Data 2023-08-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-08-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-08-16_033023719e_Chicago Data 2023-08-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-08-16 | 2023-08-16_03302:   0%|          | 0.00/24.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-08-23 | 2023-08-23_fc0a825675_Chicago Data 2023-08-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-08-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-08-23_fc0a825675_Chicago Data 2023-08-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-08-23 | 2023-08-23_fc0a8:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-08-30 | 2023-08-30_f839e6fdea_Chicago Data 2023-08-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-08-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-08-30_f839e6fdea_Chicago Data 2023-08-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-08-30 | 2023-08-30_f839e:   0%|          | 0.00/24.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-07-05 | 2023-07-05_262cf3b4b1_Chicago Data 2023-07-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-07-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-07-05_262cf3b4b1_Chicago Data 2023-07-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-07-05 | 2023-07-05_262cf:   0%|          | 0.00/22.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-07-12 | 2023-07-12_633c912fcd_Chicago Data 2023-07-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-07-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-07-12_633c912fcd_Chicago Data 2023-07-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-07-12 | 2023-07-12_633c9:   0%|          | 0.00/22.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-07-19 | 2023-07-19_a1d7cad3fa_Chicago Data 2023-07-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-07-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-07-19_a1d7cad3fa_Chicago Data 2023-07-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-07-19 | 2023-07-19_a1d7c:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-07-26 | 2023-07-26_f1af1ba71d_Chicago Data 2023-07-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-07-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-07-26_f1af1ba71d_Chicago Data 2023-07-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-07-26 | 2023-07-26_f1af1:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-06-07 | 2023-06-07_783bdbfcb1_Chicago Data 2023-06-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-06-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-06-07_783bdbfcb1_Chicago Data 2023-06-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-06-07 | 2023-06-07_783bd:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-06-14 | 2023-06-14_063f00ee1b_Chicago Data 2023-06-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-06-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-06-14_063f00ee1b_Chicago Data 2023-06-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-06-14 | 2023-06-14_063f0:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-06-21 | 2023-06-21_626328500f_Chicago Data 2023-06-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-06-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-06-21_626328500f_Chicago Data 2023-06-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-06-21 | 2023-06-21_62632:   0%|          | 0.00/22.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-06-28 | 2023-06-28_8b309bff15_Chicago Data 2023-06-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-06-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-06-28_8b309bff15_Chicago Data 2023-06-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-06-28 | 2023-06-28_8b309:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-05-03 | 2023-05-03_20aadfcc26_Chicago Data 2023-05-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-05-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-05-03_20aadfcc26_Chicago Data 2023-05-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-05-03 | 2023-05-03_20aad:   0%|          | 0.00/22.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-05-10 | 2023-05-10_7be0aec97d_Chicago Terminal (AAR) 2023-05-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Terminal%20(AAR)%202023-05-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-05-10_7be0aec97d_Chicago Terminal (AAR) 2023-05-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-05-10 | 2023-05-10_7be0a:   0%|          | 0.00/12.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-05-17 | 2023-05-17_65fcf75638_Chicago Data 2023-05-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-05-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-05-17_65fcf75638_Chicago Data 2023-05-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-05-17 | 2023-05-17_65fcf:   0%|          | 0.00/22.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-05-24 | 2023-05-24_67a979ed5a_Chicago Data 2023-05-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-05-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-05-24_67a979ed5a_Chicago Data 2023-05-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-05-24 | 2023-05-24_67a97:   0%|          | 0.00/22.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-05-31 | 2023-05-31_0aa25e64cd_Chicago Data 2023-05-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-05-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-05-31_0aa25e64cd_Chicago Data 2023-05-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-05-31 | 2023-05-31_0aa25:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-04-05 | 2023-04-05_e4da044ec9_Chicago Data 2023-04-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-04-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-04-05_e4da044ec9_Chicago Data 2023-04-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-04-05 | 2023-04-05_e4da0:   0%|          | 0.00/22.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-04-12 | 2023-04-12_a1d65b784c_Chicago Data 2023-04-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-04-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-04-12_a1d65b784c_Chicago Data 2023-04-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-04-12 | 2023-04-12_a1d65:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-04-19 | 2023-04-19_7375027da2_Chicago Data 2023-04-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-04-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-04-19_7375027da2_Chicago Data 2023-04-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-04-19 | 2023-04-19_73750:   0%|          | 0.00/22.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-04-26 | 2023-04-26_65c750c785_Chicago Data 2023-04-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-04-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-04-26_65c750c785_Chicago Data 2023-04-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-04-26 | 2023-04-26_65c75:   0%|          | 0.00/22.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-03-01 | 2023-03-01_6f0cafd559_Chicago Data 2023-03-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-03-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-03-01_6f0cafd559_Chicago Data 2023-03-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-03-01 | 2023-03-01_6f0ca:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-03-08 | 2023-03-08_5df7e40f6f_Chicago Data 2023-03-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-03-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-03-08_5df7e40f6f_Chicago Data 2023-03-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-03-08 | 2023-03-08_5df7e:   0%|          | 0.00/24.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-03-15 | 2023-03-15_dd120cafdd_Chicago Data 2023-03-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-03-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-03-15_dd120cafdd_Chicago Data 2023-03-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-03-15 | 2023-03-15_dd120:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-03-22 | 2023-03-22_143efa072d_Chicago Data 2023-03-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-03-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-03-22_143efa072d_Chicago Data 2023-03-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-03-22 | 2023-03-22_143ef:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-03-29 | 2023-03-29_5a8a84e405_Chicago Data 2023-03-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-03-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-03-29_5a8a84e405_Chicago Data 2023-03-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-03-29 | 2023-03-29_5a8a8:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-02-01 | 2023-02-01_14c3c59852_Chicago Data 2023-02-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-02-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-02-01_14c3c59852_Chicago Data 2023-02-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-02-01 | 2023-02-01_14c3c:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-02-08 | 2023-02-08_2ecaeaec92_Chicago Data 2023-02-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-02-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-02-08_2ecaeaec92_Chicago Data 2023-02-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-02-08 | 2023-02-08_2ecae:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-02-15 | 2023-02-15_a8c973e99d_Chicago Data 2023-02-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-02-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-02-15_a8c973e99d_Chicago Data 2023-02-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-02-15 | 2023-02-15_a8c97:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-02-22 | 2023-02-22_3aa622a203_Chicago Data 2023-02-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-02-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-02-22_3aa622a203_Chicago Data 2023-02-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-02-22 | 2023-02-22_3aa62:   0%|          | 0.00/22.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-01-04 | 2023-01-04_1c1cbe30e4_Chicago Data 2023-01-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-01-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-01-04_1c1cbe30e4_Chicago Data 2023-01-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-01-04 | 2023-01-04_1c1cb:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-01-11 | 2023-01-11_47e24bdc24_Chicago Data 2023-01-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-01-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-01-11_47e24bdc24_Chicago Data 2023-01-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-01-11 | 2023-01-11_47e24:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-01-18 | 2023-01-18_915f927d49_Chicago Data 2023-01-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-01-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-01-18_915f927d49_Chicago Data 2023-01-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-01-18 | 2023-01-18_915f9:   0%|          | 0.00/24.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2023-01-25 | 2023-01-25_e863423fd5_Chicago Data 2023-01-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202023-01-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2023\xlsx\2023-01-25_e863423fd5_Chicago Data 2023-01-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2023-01-25 | 2023-01-25_e8634:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-12-07 | 2022-12-07_d133841efe_Chicago Data 2022-12-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-12-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-12-07_d133841efe_Chicago Data 2022-12-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-12-07 | 2022-12-07_d1338:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-12-14 | 2022-12-14_131aedf43a_Chicago Data 2022-12-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-12-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-12-14_131aedf43a_Chicago Data 2022-12-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-12-14 | 2022-12-14_131ae:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-12-21 | 2022-12-21_bd2c3667fb_Chicago Data 2022-12-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-12-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-12-21_bd2c3667fb_Chicago Data 2022-12-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-12-21 | 2022-12-21_bd2c3:   0%|          | 0.00/22.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-12-28 | 2022-12-28_faad4c8981_Chicago Data 2022-12-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-12-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-12-28_faad4c8981_Chicago Data 2022-12-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-12-28 | 2022-12-28_faad4:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-11-02 | 2022-11-02_e6b3c78285_Chicago Data 2022-11-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-11-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-11-02_e6b3c78285_Chicago Data 2022-11-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-11-02 | 2022-11-02_e6b3c:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-11-09 | 2022-11-09_e0a42e2849_Chicago Data 2022-11-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-11-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-11-09_e0a42e2849_Chicago Data 2022-11-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-11-09 | 2022-11-09_e0a42:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-11-16 | 2022-11-16_94e5e7e87c_Chicago Data 2022-11-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-11-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-11-16_94e5e7e87c_Chicago Data 2022-11-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-11-16 | 2022-11-16_94e5e:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-11-23 | 2022-11-23_21b7aebbf5_Chicago Data 2022-11-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-11-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-11-23_21b7aebbf5_Chicago Data 2022-11-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-11-23 | 2022-11-23_21b7a:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-11-30 | 2022-11-30_93b7e177e6_Chicago Data 2022-11-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-11-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-11-30_93b7e177e6_Chicago Data 2022-11-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-11-30 | 2022-11-30_93b7e:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-10-05 | 2022-10-05_bc85b427bb_Chicago Data 2022-10-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-10-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-10-05_bc85b427bb_Chicago Data 2022-10-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-10-05 | 2022-10-05_bc85b:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-10-12 | 2022-10-12_22a40262dc_Chicago Data 2022-10-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-10-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-10-12_22a40262dc_Chicago Data 2022-10-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-10-12 | 2022-10-12_22a40:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-10-19 | 2022-10-19_ee44d48448_Chicago Data 2022-10-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-10-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-10-19_ee44d48448_Chicago Data 2022-10-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-10-19 | 2022-10-19_ee44d:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-10-26 | 2022-10-26_3d553ffb84_Chicago Data 2022-10-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-10-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-10-26_3d553ffb84_Chicago Data 2022-10-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-10-26 | 2022-10-26_3d553:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-09-07 | 2022-09-07_188cb8f2cd_Chicago Data 2022-09-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-09-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-09-07_188cb8f2cd_Chicago Data 2022-09-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-09-07 | 2022-09-07_188cb:   0%|          | 0.00/23.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-09-14 | 2022-09-14_15d2d17a2c_Chicago Data 2022-09-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-09-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-09-14_15d2d17a2c_Chicago Data 2022-09-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-09-14 | 2022-09-14_15d2d:   0%|          | 0.00/24.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-09-21 | 2022-09-21_ae2dc33369_Chicago Data 2022-09-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-09-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-09-21_ae2dc33369_Chicago Data 2022-09-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-09-21 | 2022-09-21_ae2dc:   0%|          | 0.00/22.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-09-28 | 2022-09-28_1fc68e8615_Chicago Data 2022-09-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-09-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-09-28_1fc68e8615_Chicago Data 2022-09-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-09-28 | 2022-09-28_1fc68:   0%|          | 0.00/22.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-08-03 | 2022-08-03_28868b5642_Chicago Data 2022-08-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-08-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-08-03_28868b5642_Chicago Data 2022-08-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-08-03 | 2022-08-03_28868:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-08-10 | 2022-08-10_9f63323187_Chicago Data 2022-08-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-08-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-08-10_9f63323187_Chicago Data 2022-08-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-08-10 | 2022-08-10_9f633:   0%|          | 0.00/16.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-08-17 | 2022-08-17_971d7a3033_Chicago Data 2022-08-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-08-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-08-17_971d7a3033_Chicago Data 2022-08-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-08-17 | 2022-08-17_971d7:   0%|          | 0.00/23.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-08-24 | 2022-08-24_ce1abe398f_Chicago Data 2022-08-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-08-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-08-24_ce1abe398f_Chicago Data 2022-08-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-08-24 | 2022-08-24_ce1ab:   0%|          | 0.00/23.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-08-31 | 2022-08-31_355e15741b_Chicago Data 2022-08-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-08-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-08-31_355e15741b_Chicago Data 2022-08-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-08-31 | 2022-08-31_355e1:   0%|          | 0.00/22.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-07-06 | 2022-07-06_cbfa0c4cd2_Chicago Data 2022-07-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-07-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-07-06_cbfa0c4cd2_Chicago Data 2022-07-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-07-06 | 2022-07-06_cbfa0:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-07-13 | 2022-07-13_39ec84ec1f_Chicago Data 2022-07-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-07-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-07-13_39ec84ec1f_Chicago Data 2022-07-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-07-13 | 2022-07-13_39ec8:   0%|          | 0.00/22.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-07-20 | 2022-07-20_a782e3519f_Chicago Data 2022-07-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-07-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-07-20_a782e3519f_Chicago Data 2022-07-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-07-20 | 2022-07-20_a782e:   0%|          | 0.00/22.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-07-27 | 2022-07-27_a4493d1e32_Chicago Data 2022-07-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-07-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-07-27_a4493d1e32_Chicago Data 2022-07-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-07-27 | 2022-07-27_a4493:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-06-01 | 2022-06-01_d81a301656_Chicago Data 2022-06-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-06-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-06-01_d81a301656_Chicago Data 2022-06-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-06-01 | 2022-06-01_d81a3:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-06-08 | 2022-06-08_baffcbde65_Chicago Data 2022-06-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-06-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-06-08_baffcbde65_Chicago Data 2022-06-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-06-08 | 2022-06-08_baffc:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-06-15 | 2022-06-15_1de99657d6_Chicago Data 2022-06-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-06-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-06-15_1de99657d6_Chicago Data 2022-06-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-06-15 | 2022-06-15_1de99:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-06-22 | 2022-06-22_b803dc2b46_Chicago Data 2022-06-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-06-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-06-22_b803dc2b46_Chicago Data 2022-06-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-06-22 | 2022-06-22_b803d:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-06-29 | 2022-06-29_b76dc8c2fd_Chicago Data 2022-06-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-06-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-06-29_b76dc8c2fd_Chicago Data 2022-06-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-06-29 | 2022-06-29_b76dc:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-05-04 | 2022-05-04_80c4b227af_Chicago Data 2022-05-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-05-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-05-04_80c4b227af_Chicago Data 2022-05-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-05-04 | 2022-05-04_80c4b:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-05-11 | 2022-05-11_2f4a6efe47_Chicago Data 2022-05-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-05-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-05-11_2f4a6efe47_Chicago Data 2022-05-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-05-11 | 2022-05-11_2f4a6:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-05-18 | 2022-05-18_219311e45d_Chicago Data 2022-05-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-05-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-05-18_219311e45d_Chicago Data 2022-05-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-05-18 | 2022-05-18_21931:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-05-25 | 2022-05-25_5fd9befa19_Chicago Data 2022-05-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-05-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-05-25_5fd9befa19_Chicago Data 2022-05-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-05-25 | 2022-05-25_5fd9b:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-04-06 | 2022-04-06_bcf3c182d9_Chicago Data 2022-04-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-04-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-04-06_bcf3c182d9_Chicago Data 2022-04-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-04-06 | 2022-04-06_bcf3c:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-04-13 | 2022-04-13_7a9aa78fa6_Chicago Data 2022-04-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-04-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-04-13_7a9aa78fa6_Chicago Data 2022-04-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-04-13 | 2022-04-13_7a9aa:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-04-20 | 2022-04-20_cb2f17cc75_Chicago Data 2022-04-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-04-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-04-20_cb2f17cc75_Chicago Data 2022-04-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-04-20 | 2022-04-20_cb2f1:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-04-27 | 2022-04-27_e1771e1333_Chicago Data 2022-04-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-04-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-04-27_e1771e1333_Chicago Data 2022-04-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-04-27 | 2022-04-27_e1771:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-03-02 | 2022-03-02_9120612abc_Chicago Data 2022-03-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-03-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-03-02_9120612abc_Chicago Data 2022-03-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-03-02 | 2022-03-02_91206:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-03-09 | 2022-03-09_f72eeab83a_Chicago Data 2022-03-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-03-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-03-09_f72eeab83a_Chicago Data 2022-03-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-03-09 | 2022-03-09_f72ee:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-03-16 | 2022-03-16_bf02253322_Chicago Data 2022-03-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-03-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-03-16_bf02253322_Chicago Data 2022-03-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-03-16 | 2022-03-16_bf022:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-03-23 | 2022-03-23_81528c3e17_Chicago Data 2022-03-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-03-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-03-23_81528c3e17_Chicago Data 2022-03-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-03-23 | 2022-03-23_81528:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-03-30 | 2022-03-30_dc75a16be0_Chicago Data 2022-03-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-03-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-03-30_dc75a16be0_Chicago Data 2022-03-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-03-30 | 2022-03-30_dc75a:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-02-02 | 2022-02-02_29d8263f2f_Chicago Data 2022-02-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-02-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-02-02_29d8263f2f_Chicago Data 2022-02-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-02-02 | 2022-02-02_29d82:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-02-09 | 2022-02-09_eeeed6430e_Chicago Data 2022-02-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-02-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-02-09_eeeed6430e_Chicago Data 2022-02-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-02-09 | 2022-02-09_eeeed:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-02-16 | 2022-02-16_66711f82a3_Chicago Data 2022-02-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-02-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-02-16_66711f82a3_Chicago Data 2022-02-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-02-16 | 2022-02-16_66711:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-02-23 | 2022-02-23_b61512161a_Chicago Data 2022-02-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-02-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-02-23_b61512161a_Chicago Data 2022-02-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-02-23 | 2022-02-23_b6151:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-01-05 | 2022-01-05_89f34b95f7_Chicago Data 2022-01-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-01-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-01-05_89f34b95f7_Chicago Data 2022-01-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-01-05 | 2022-01-05_89f34:   0%|          | 0.00/14.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-01-12 | 2022-01-12_bca9722e6e_Chicago Data 2022-01-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-01-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-01-12_bca9722e6e_Chicago Data 2022-01-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-01-12 | 2022-01-12_bca97:   0%|          | 0.00/14.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-01-19 | 2022-01-19_0727c36284_Chicago Data 2022-01-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-01-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-01-19_0727c36284_Chicago Data 2022-01-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-01-19 | 2022-01-19_0727c:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2022-01-26 | 2022-01-26_7c7ab0a29c_Chicago Data 2022-01-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202022-01-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2022\xlsx\2022-01-26_7c7ab0a29c_Chicago Data 2022-01-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2022-01-26 | 2022-01-26_7c7ab:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-12-01 | 2021-12-01_ccdd97363e_Chicago Data 2021-12-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-12-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-12-01_ccdd97363e_Chicago Data 2021-12-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-12-01 | 2021-12-01_ccdd9:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-12-08 | 2021-12-08_216bf45d7d_Chicago Data 2021-12-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-12-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-12-08_216bf45d7d_Chicago Data 2021-12-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-12-08 | 2021-12-08_216bf:   0%|          | 0.00/14.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-12-15 | 2021-12-15_7f6406f6ae_Chicago Data 2021-12-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-12-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-12-15_7f6406f6ae_Chicago Data 2021-12-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-12-15 | 2021-12-15_7f640:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-12-22 | 2021-12-22_c64f10e220_Chicago Data 2021-12-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-12-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-12-22_c64f10e220_Chicago Data 2021-12-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-12-22 | 2021-12-22_c64f1:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-12-29 | 2021-12-29_f026e572c7_Chicago Data 2021-12-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-12-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-12-29_f026e572c7_Chicago Data 2021-12-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-12-29 | 2021-12-29_f026e:   0%|          | 0.00/15.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-11-03 | 2021-11-03_bf0682a00f_Chicago Data 2021-11-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-11-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-11-03_bf0682a00f_Chicago Data 2021-11-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-11-03 | 2021-11-03_bf068:   0%|          | 0.00/14.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-11-10 | 2021-11-10_e2163fac6a_Chicago Data 2021-11-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-11-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-11-10_e2163fac6a_Chicago Data 2021-11-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-11-10 | 2021-11-10_e2163:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-11-17 | 2021-11-17_5555a624f3_Chicago Data 2021-11-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-11-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-11-17_5555a624f3_Chicago Data 2021-11-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-11-17 | 2021-11-17_5555a:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-11-24 | 2021-11-24_a918d7f47f_Chicago Data 2021-11-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-11-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-11-24_a918d7f47f_Chicago Data 2021-11-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-11-24 | 2021-11-24_a918d:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-10-06 | 2021-10-06_e8d0a81214_Chicago Data 2021-10-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-10-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-10-06_e8d0a81214_Chicago Data 2021-10-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-10-06 | 2021-10-06_e8d0a:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-10-13 | 2021-10-13_f6fae3b6a7_Chicago Data 2021-10-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-10-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-10-13_f6fae3b6a7_Chicago Data 2021-10-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-10-13 | 2021-10-13_f6fae:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-10-20 | 2021-10-20_cff6333c46_Chicago Data 2021-10-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-10-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-10-20_cff6333c46_Chicago Data 2021-10-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-10-20 | 2021-10-20_cff63:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-10-27 | 2021-10-27_3f01c77a36_Chicago Data 2021-10-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-10-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-10-27_3f01c77a36_Chicago Data 2021-10-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-10-27 | 2021-10-27_3f01c:   0%|          | 0.00/14.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-09-01 | 2021-09-01_a07d44e53f_Chicago Data 2021-09-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-09-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-09-01_a07d44e53f_Chicago Data 2021-09-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-09-01 | 2021-09-01_a07d4:   0%|          | 0.00/15.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-09-08 | 2021-09-08_2141f56148_Chicago Data 2021-09-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-09-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-09-08_2141f56148_Chicago Data 2021-09-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-09-08 | 2021-09-08_2141f:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-09-15 | 2021-09-15_afde1b5d0c_Chicago Data 2021-09-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-09-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-09-15_afde1b5d0c_Chicago Data 2021-09-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-09-15 | 2021-09-15_afde1:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-09-22 | 2021-09-22_189aa994f7_Chicago Data 2021-09-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-09-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-09-22_189aa994f7_Chicago Data 2021-09-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-09-22 | 2021-09-22_189aa:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-09-29 | 2021-09-29_3b86512113_Chicago Data 2021-09-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-09-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-09-29_3b86512113_Chicago Data 2021-09-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-09-29 | 2021-09-29_3b865:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-08-04 | 2021-08-04_c4a027ee51_Chicago Data 2021-08-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-08-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-08-04_c4a027ee51_Chicago Data 2021-08-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-08-04 | 2021-08-04_c4a02:   0%|          | 0.00/15.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-08-11 | 2021-08-11_f807dacc7a_Chicago Data 2021-08-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-08-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-08-11_f807dacc7a_Chicago Data 2021-08-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-08-11 | 2021-08-11_f807d:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-08-18 | 2021-08-18_4b03452e73_Chicago Data 2021-08-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-08-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-08-18_4b03452e73_Chicago Data 2021-08-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-08-18 | 2021-08-18_4b034:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-08-25 | 2021-08-25_9d2b5e1e8d_Chicago Data 2021-08-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-08-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-08-25_9d2b5e1e8d_Chicago Data 2021-08-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-08-25 | 2021-08-25_9d2b5:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-07-07 | 2021-07-07_4c50b51adf_Chicago Data 2021-07-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-07-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-07-07_4c50b51adf_Chicago Data 2021-07-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-07-07 | 2021-07-07_4c50b:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-07-14 | 2021-07-14_0a088652ad_Chicago Data 2021-07-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-07-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-07-14_0a088652ad_Chicago Data 2021-07-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-07-14 | 2021-07-14_0a088:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-07-21 | 2021-07-21_886d2874de_Chicago Data 2021-07-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-07-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-07-21_886d2874de_Chicago Data 2021-07-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-07-21 | 2021-07-21_886d2:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-07-28 | 2021-07-28_a9479fc344_Chicago Data 2021-07-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-07-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-07-28_a9479fc344_Chicago Data 2021-07-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-07-28 | 2021-07-28_a9479:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-06-02 | 2021-06-02_03b3d2695a_Chicago Data 2021-06-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-06-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-06-02_03b3d2695a_Chicago Data 2021-06-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-06-02 | 2021-06-02_03b3d:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-06-09 | 2021-06-09_89ddd6b6a3_Chicago Data 2021-06-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-06-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-06-09_89ddd6b6a3_Chicago Data 2021-06-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-06-09 | 2021-06-09_89ddd:   0%|          | 0.00/15.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-06-16 | 2021-06-16_53bf0902ce_Chicago Data 2021-06-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-06-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-06-16_53bf0902ce_Chicago Data 2021-06-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-06-16 | 2021-06-16_53bf0:   0%|          | 0.00/15.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-06-23 | 2021-06-23_2738d7802e_Chicago Data 2021-06-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-06-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-06-23_2738d7802e_Chicago Data 2021-06-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-06-23 | 2021-06-23_2738d:   0%|          | 0.00/14.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-06-30 | 2021-06-30_1ad70fefd2_Chicago Data 2021-06-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-06-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-06-30_1ad70fefd2_Chicago Data 2021-06-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-06-30 | 2021-06-30_1ad70:   0%|          | 0.00/15.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-05-05 | 2021-05-05_b7a80d1dbd_Chicago Data 2021-05-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-05-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-05-05_b7a80d1dbd_Chicago Data 2021-05-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-05-05 | 2021-05-05_b7a80:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-05-12 | 2021-05-12_e342f7c4c2_Chicago Data 2021-05-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-05-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-05-12_e342f7c4c2_Chicago Data 2021-05-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-05-12 | 2021-05-12_e342f:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-05-19 | 2021-05-19_462d2d0f85_Chicago Data 2021-05-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-05-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-05-19_462d2d0f85_Chicago Data 2021-05-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-05-19 | 2021-05-19_462d2:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-05-26 | 2021-05-26_f86892c9f8_Chicago Data 2021-05-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-05-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-05-26_f86892c9f8_Chicago Data 2021-05-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-05-26 | 2021-05-26_f8689:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-04-07 | 2021-04-07_2ec9e73510_Chicago Data 2021-04-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-04-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-04-07_2ec9e73510_Chicago Data 2021-04-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-04-07 | 2021-04-07_2ec9e:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-04-14 | 2021-04-14_37075cdfe6_Chicago Data 2021-04-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-04-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-04-14_37075cdfe6_Chicago Data 2021-04-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-04-14 | 2021-04-14_37075:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-04-21 | 2021-04-21_13ea84e4d7_Chicago Data 2021-04-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-04-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-04-21_13ea84e4d7_Chicago Data 2021-04-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-04-21 | 2021-04-21_13ea8:   0%|          | 0.00/14.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-04-28 | 2021-04-28_42b14b8cdd_Chicago Data 2021-04-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-04-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-04-28_42b14b8cdd_Chicago Data 2021-04-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-04-28 | 2021-04-28_42b14:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-03-03 | 2021-03-03_d1e63eac8e_Chicago Data 2021-03-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-03-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-03-03_d1e63eac8e_Chicago Data 2021-03-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-03-03 | 2021-03-03_d1e63:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-03-10 | 2021-03-10_530305abea_Chicago Data 2021-03-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-03-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-03-10_530305abea_Chicago Data 2021-03-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-03-10 | 2021-03-10_53030:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-03-17 | 2021-03-17_13a88c2e86_Chicago Data 2021-03-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-03-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-03-17_13a88c2e86_Chicago Data 2021-03-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-03-17 | 2021-03-17_13a88:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-03-24 | 2021-03-24_b9c1195efd_Chicago Data 2021-03-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-03-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-03-24_b9c1195efd_Chicago Data 2021-03-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-03-24 | 2021-03-24_b9c11:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-03-31 | 2021-03-31_6325671307_Chicago Data 2021-03-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-03-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-03-31_6325671307_Chicago Data 2021-03-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-03-31 | 2021-03-31_63256:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-02-03 | 2021-02-03_70b1aa2630_Chicago Data 2021-02-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-02-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-02-03_70b1aa2630_Chicago Data 2021-02-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-02-03 | 2021-02-03_70b1a:   0%|          | 0.00/15.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-02-10 | 2021-02-10_8fecba4d46_Chicago Data 2021-02-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-02-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-02-10_8fecba4d46_Chicago Data 2021-02-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-02-10 | 2021-02-10_8fecb:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-02-17 | 2021-02-17_a710912b31_Chicago Data 2021-02-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-02-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-02-17_a710912b31_Chicago Data 2021-02-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-02-17 | 2021-02-17_a7109:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-02-24 | 2021-02-24_b7ac58b9ab_Chicago Data 2021-02-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-02-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-02-24_b7ac58b9ab_Chicago Data 2021-02-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-02-24 | 2021-02-24_b7ac5:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-01-06 | 2021-01-06_3a519ceb58_Chicago Data 2021-01-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-01-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-01-06_3a519ceb58_Chicago Data 2021-01-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-01-06 | 2021-01-06_3a519:   0%|          | 0.00/17.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-01-13 | 2021-01-13_25aa1ced7a_Chicago Data 2021-01-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-01-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-01-13_25aa1ced7a_Chicago Data 2021-01-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-01-13 | 2021-01-13_25aa1:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-01-20 | 2021-01-20_3a5ce02a8e_Chicago Data 2021-01-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-01-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-01-20_3a5ce02a8e_Chicago Data 2021-01-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-01-20 | 2021-01-20_3a5ce:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2021-01-27 | 2021-01-27_d6681730b2_Chicago Data 2021-01-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202021-01-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2021\xlsx\2021-01-27_d6681730b2_Chicago Data 2021-01-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2021-01-27 | 2021-01-27_d6681:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-12-02 | 2020-12-02_b0fde968df_Chicago Data 2020-12-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-12-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-12-02_b0fde968df_Chicago Data 2020-12-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-12-02 | 2020-12-02_b0fde:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-12-09 | 2020-12-09_900e8a9e40_Chicago Data 2020-12-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-12-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-12-09_900e8a9e40_Chicago Data 2020-12-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-12-09 | 2020-12-09_900e8:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-12-16 | 2020-12-16_8f0b15a588_Chicago Data 2020-12-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-12-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-12-16_8f0b15a588_Chicago Data 2020-12-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-12-16 | 2020-12-16_8f0b1:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-12-23 | 2020-12-23_9e2c13ffe2_Chicago Data 2020-12-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-12-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-12-23_9e2c13ffe2_Chicago Data 2020-12-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-12-23 | 2020-12-23_9e2c1:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-12-30 | 2020-12-30_20a7a56a6f_Chicago Data 2020-12-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-12-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-12-30_20a7a56a6f_Chicago Data 2020-12-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-12-30 | 2020-12-30_20a7a:   0%|          | 0.00/15.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-11-04 | 2020-11-04_e4b8678896_Chicago Data 2020-11-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-11-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-11-04_e4b8678896_Chicago Data 2020-11-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-11-04 | 2020-11-04_e4b86:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-11-11 | 2020-11-11_36ba67dd8c_Chicago Data 2020-11-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-11-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-11-11_36ba67dd8c_Chicago Data 2020-11-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-11-11 | 2020-11-11_36ba6:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-11-18 | 2020-11-18_23727b2f2a_Chicago Data 2020-11-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-11-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-11-18_23727b2f2a_Chicago Data 2020-11-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-11-18 | 2020-11-18_23727:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-11-25 | 2020-11-25_ea1956b120_Chicago Data 2020-11-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-11-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-11-25_ea1956b120_Chicago Data 2020-11-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-11-25 | 2020-11-25_ea195:   0%|          | 0.00/15.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-10-07 | 2020-10-07_f9a7d8461e_Chicago Data 2020-10-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-10-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-10-07_f9a7d8461e_Chicago Data 2020-10-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-10-07 | 2020-10-07_f9a7d:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-10-14 | 2020-10-14_9d8a1ac783_Chicago Data 2020-10-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-10-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-10-14_9d8a1ac783_Chicago Data 2020-10-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-10-14 | 2020-10-14_9d8a1:   0%|          | 0.00/15.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-10-21 | 2020-10-21_b45eb5e167_Chicago Data 2020-10-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-10-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-10-21_b45eb5e167_Chicago Data 2020-10-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-10-21 | 2020-10-21_b45eb:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-10-28 | 2020-10-28_2e8cb1463f_Chicago Data 2020-10-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-10-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-10-28_2e8cb1463f_Chicago Data 2020-10-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-10-28 | 2020-10-28_2e8cb:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-09-02 | 2020-09-02_ec675d2b1d_Chicago Data 2020-09-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-09-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-09-02_ec675d2b1d_Chicago Data 2020-09-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-09-02 | 2020-09-02_ec675:   0%|          | 0.00/15.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-09-09 | 2020-09-09_5533275965_Chicago Data 2020-09-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-09-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-09-09_5533275965_Chicago Data 2020-09-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-09-09 | 2020-09-09_55332:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-09-16 | 2020-09-16_8803a7efad_Chicago Data 2020-09-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-09-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-09-16_8803a7efad_Chicago Data 2020-09-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-09-16 | 2020-09-16_8803a:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-09-23 | 2020-09-23_429fd8012f_Chicago Data 2020-09-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-09-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-09-23_429fd8012f_Chicago Data 2020-09-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-09-23 | 2020-09-23_429fd:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-09-30 | 2020-09-30_d449cac4bd_Chicago Data 2020-09-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-09-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-09-30_d449cac4bd_Chicago Data 2020-09-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-09-30 | 2020-09-30_d449c:   0%|          | 0.00/15.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-08-05 | 2020-08-05_6d783a6376_Chicago Data 2020-08-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-08-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-08-05_6d783a6376_Chicago Data 2020-08-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-08-05 | 2020-08-05_6d783:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-08-12 | 2020-08-12_073a06dac6_Chicago Data 2020-08-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-08-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-08-12_073a06dac6_Chicago Data 2020-08-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-08-12 | 2020-08-12_073a0:   0%|          | 0.00/15.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-08-19 | 2020-08-19_be78e7cb12_Chicago Data 2020-08-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-08-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-08-19_be78e7cb12_Chicago Data 2020-08-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-08-19 | 2020-08-19_be78e:   0%|          | 0.00/15.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-08-26 | 2020-08-26_af620e38cf_Chicago Data 2020-08-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-08-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-08-26_af620e38cf_Chicago Data 2020-08-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-08-26 | 2020-08-26_af620:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-07-01 | 2020-07-01_741f883e5f_ctco_data_2020-07-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-07-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-07-01_741f883e5f_ctco_data_2020-07-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-07-01 | 2020-07-01_741f8:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-07-08 | 2020-07-08_d142c86515_ctco_data_2020-07-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-07-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-07-08_d142c86515_ctco_data_2020-07-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-07-08 | 2020-07-08_d142c:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-07-15 | 2020-07-15_2241acf64f_ctco_data_2020-07-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-07-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-07-15_2241acf64f_ctco_data_2020-07-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-07-15 | 2020-07-15_2241a:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-07-22 | 2020-07-22_b5f7ea1935_ctco_data_2020-07-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-07-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-07-22_b5f7ea1935_ctco_data_2020-07-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-07-22 | 2020-07-22_b5f7e:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-07-29 | 2020-07-29_3255746d37_Chicago Data 2020-07-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/Chicago%20Data%202020-07-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-07-29_3255746d37_Chicago Data 2020-07-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-07-29 | 2020-07-29_32557:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-06-03 | 2020-06-03_1890cf0c42_ctco_data_2020-06-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-06-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-06-03_1890cf0c42_ctco_data_2020-06-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-06-03 | 2020-06-03_1890c:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-06-10 | 2020-06-10_7dc232ae6b_ctco_data_2020-06-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-06-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-06-10_7dc232ae6b_ctco_data_2020-06-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-06-10 | 2020-06-10_7dc23:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-06-17 | 2020-06-17_373a869460_ctco_data_2020-06-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-06-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-06-17_373a869460_ctco_data_2020-06-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-06-17 | 2020-06-17_373a8:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-06-24 | 2020-06-24_a0ce9a5730_ctco_data_2020-06-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-06-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-06-24_a0ce9a5730_ctco_data_2020-06-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-06-24 | 2020-06-24_a0ce9:   0%|          | 0.00/15.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-05-06 | 2020-05-06_935ce6768f_ctco_data_2020-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-05-06_935ce6768f_ctco_data_2020-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-05-06 | 2020-05-06_935ce:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-05-13 | 2020-05-13_94c161ab8a_ctco_data_2020-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-05-13_94c161ab8a_ctco_data_2020-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-05-13 | 2020-05-13_94c16:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-05-20 | 2020-05-20_89c9e869a4_ctco_data_2020-05-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-05-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-05-20_89c9e869a4_ctco_data_2020-05-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-05-20 | 2020-05-20_89c9e:   0%|          | 0.00/15.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-05-27 | 2020-05-27_0c28f22d4c_ctco_data_2020-05-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-05-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-05-27_0c28f22d4c_ctco_data_2020-05-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-05-27 | 2020-05-27_0c28f:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-04-01 | 2020-04-01_f5dad4414b_ctco_data_2020-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-04-01_f5dad4414b_ctco_data_2020-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-04-01 | 2020-04-01_f5dad:   0%|          | 0.00/15.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-04-08 | 2020-04-08_042dd1f20e_ctco_data_2020-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-04-08_042dd1f20e_ctco_data_2020-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-04-08 | 2020-04-08_042dd:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-04-15 | 2020-04-15_16d17d0d49_ctco_data_2020-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-04-15_16d17d0d49_ctco_data_2020-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-04-15 | 2020-04-15_16d17:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-04-22 | 2020-04-22_d5e10b40e9_ctco_data_2020-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-04-22_d5e10b40e9_ctco_data_2020-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-04-22 | 2020-04-22_d5e10:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-04-29 | 2020-04-29_42236c4ab0_ctco_data_2020-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-04-29_42236c4ab0_ctco_data_2020-04-29.xlsx
----------------------------------------------------------------------------------------------------

[FAILED] weekly_service_report | ctco | 2020-04-29 | 2020-04-29_42236c4ab0_ctco_data_2020-04-29.xlsx
HTTP 404 while downloading https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-04-29.xlsx


----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-03-04 | 2020-03-04_cb347ed1cc_ctco_data_2020-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-03-04_cb347ed1cc_ctco_data_2020-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-03-04 | 2020-03-04_cb347:   0%|          | 0.00/14.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-03-11 | 2020-03-11_716eb11f44_ctco_data_2020-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-03-11_716eb11f44_ctco_data_2020-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-03-11 | 2020-03-11_716eb:   0%|          | 0.00/14.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-03-18 | 2020-03-18_45ac75b909_ctco_data_2020-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-03-18_45ac75b909_ctco_data_2020-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-03-18 | 2020-03-18_45ac7:   0%|          | 0.00/14.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-03-25 | 2020-03-25_0dd6679f02_ctco_data_2020-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-03-25_0dd6679f02_ctco_data_2020-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-03-25 | 2020-03-25_0dd66:   0%|          | 0.00/14.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-02-05 | 2020-02-05_a2fd7acf1a_ctco_data_2020-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-02-05_a2fd7acf1a_ctco_data_2020-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-02-05 | 2020-02-05_a2fd7:   0%|          | 0.00/14.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-02-12 | 2020-02-12_d1da58d688_ctco_data_2020-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-02-12_d1da58d688_ctco_data_2020-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-02-12 | 2020-02-12_d1da5:   0%|          | 0.00/14.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-02-19 | 2020-02-19_907894c5a7_ctco_data_2020-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-02-19_907894c5a7_ctco_data_2020-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-02-19 | 2020-02-19_90789:   0%|          | 0.00/14.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-02-26 | 2020-02-26_7d22cc228a_ctco_data_2020-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-02-26_7d22cc228a_ctco_data_2020-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-02-26 | 2020-02-26_7d22c:   0%|          | 0.00/14.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-01-01 | 2020-01-01_9ed9494656_ctco_data_2020-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-01-01_9ed9494656_ctco_data_2020-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-01-01 | 2020-01-01_9ed94:   0%|          | 0.00/14.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-01-08 | 2020-01-08_9df41bdacb_ctco_data_2020-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-01-08_9df41bdacb_ctco_data_2020-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-01-08 | 2020-01-08_9df41:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-01-15 | 2020-01-15_c34c54b9ad_ctco_data_2020-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-01-15_c34c54b9ad_ctco_data_2020-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-01-15 | 2020-01-15_c34c5:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-01-22 | 2020-01-22_ba65daabae_ctco_data_2020-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-01-22_ba65daabae_ctco_data_2020-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-01-22 | 2020-01-22_ba65d:   0%|          | 0.00/14.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ctco | 2020-01-29 | 2020-01-29_0d98f96cbf_ctco_data_2020-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/CTCO/ctco_data_2020-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ctco\2020\xlsx\2020-01-29_0d98f96cbf_ctco_data_2020-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ctco | 2020-01-29 | 2020-01-29_0d98f:   0%|          | 0.00/11.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-05-07 | 2025-05-07_68465157b8_KCS Data 2025-05-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-05-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-05-07_68465157b8_KCS Data 2025-05-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-05-07 | 2025-05-07_684651:   0%|          | 0.00/36.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-04-02 | 2025-04-02_aad8870bd1_KCS Data 2025-04-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-04-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-04-02_aad8870bd1_KCS Data 2025-04-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-04-02 | 2025-04-02_aad887:   0%|          | 0.00/40.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-04-09 | 2025-04-09_e57b9e2660_KCS Data 2025-04-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-04-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-04-09_e57b9e2660_KCS Data 2025-04-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-04-09 | 2025-04-09_e57b9e:   0%|          | 0.00/41.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-04-16 | 2025-04-16_ba2bf48aeb_KCS Data 2025-04-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-04-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-04-16_ba2bf48aeb_KCS Data 2025-04-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-04-16 | 2025-04-16_ba2bf4:   0%|          | 0.00/41.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-04-23 | 2025-04-23_35321f4a70_KCS Data 2025-04-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-04-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-04-23_35321f4a70_KCS Data 2025-04-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-04-23 | 2025-04-23_35321f:   0%|          | 0.00/41.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-04-30 | 2025-04-30_1a9d70a553_KCS Data 2025-04-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-04-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-04-30_1a9d70a553_KCS Data 2025-04-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-04-30 | 2025-04-30_1a9d70:   0%|          | 0.00/40.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-03-05 | 2025-03-05_36d7dfe085_KCS Data 2025-03-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-03-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-03-05_36d7dfe085_KCS Data 2025-03-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-03-05 | 2025-03-05_36d7df:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-03-12 | 2025-03-12_3feca82823_KCS Data 2025-03-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-03-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-03-12_3feca82823_KCS Data 2025-03-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-03-12 | 2025-03-12_3feca8:   0%|          | 0.00/40.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-03-19 | 2025-03-19_157f6ceaec_KCS Data 2025-03-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-03-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-03-19_157f6ceaec_KCS Data 2025-03-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-03-19 | 2025-03-19_157f6c:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-03-26 | 2025-03-26_6c3264c7ef_KCS Data 2025-03-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-03-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-03-26_6c3264c7ef_KCS Data 2025-03-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-03-26 | 2025-03-26_6c3264:   0%|          | 0.00/41.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-02-05 | 2025-02-05_b2872e3b89_KCS Data 2025-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-02-05_b2872e3b89_KCS Data 2025-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-02-05 | 2025-02-05_b2872e:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-02-12 | 2025-02-12_ff99a70f15_KCS Data 2025-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-02-12_ff99a70f15_KCS Data 2025-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-02-12 | 2025-02-12_ff99a7:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-02-19 | 2025-02-19_da9f9cd816_KCS Data 2025-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-02-19_da9f9cd816_KCS Data 2025-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-02-19 | 2025-02-19_da9f9c:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-02-26 | 2025-02-26_5010f143ce_KCS Data 2025-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-02-26_5010f143ce_KCS Data 2025-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-02-26 | 2025-02-26_5010f1:   0%|          | 0.00/40.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-01-01 | 2025-01-01_dae5b16aaa_KCS Data 2025-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-01-01_dae5b16aaa_KCS Data 2025-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-01-01 | 2025-01-01_dae5b1:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-01-08 | 2025-01-08_badd2617bc_KCS Data 2025-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-01-08_badd2617bc_KCS Data 2025-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-01-08 | 2025-01-08_badd26:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-01-15 | 2025-01-15_023be2ab2a_KCS Data 2025-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-01-15_023be2ab2a_KCS Data 2025-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-01-15 | 2025-01-15_023be2:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-01-22 | 2025-01-22_b0864e1ca9_KCS Data 2025-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-01-22_b0864e1ca9_KCS Data 2025-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-01-22 | 2025-01-22_b0864e:   0%|          | 0.00/35.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2025-01-29 | 2025-01-29_3fe59220b0_KCS Data 2025-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202025-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2025\xlsx\2025-01-29_3fe59220b0_KCS Data 2025-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2025-01-29 | 2025-01-29_3fe592:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-12-04 | 2024-12-04_1a4ea75b8b_KCS Data 2024-12-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-12-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-12-04_1a4ea75b8b_KCS Data 2024-12-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-12-04 | 2024-12-04_1a4ea7:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-12-11 | 2024-12-11_d090bbc8f8_KCS Data 2024-12-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-12-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-12-11_d090bbc8f8_KCS Data 2024-12-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-12-11 | 2024-12-11_d090bb:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-12-18 | 2024-12-18_4d22c2e71a_KCS Data 2024-12-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-12-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-12-18_4d22c2e71a_KCS Data 2024-12-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-12-18 | 2024-12-18_4d22c2:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-12-25 | 2024-12-25_db7506cc5c_KCS Data 2024-12-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-12-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-12-25_db7506cc5c_KCS Data 2024-12-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-12-25 | 2024-12-25_db7506:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-11-06 | 2024-11-06_871f2370c1_KCS Data 2024-11-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-11-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-11-06_871f2370c1_KCS Data 2024-11-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-11-06 | 2024-11-06_871f23:   0%|          | 0.00/40.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-11-13 | 2024-11-13_7351623fe5_KCS Data 2024-11-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-11-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-11-13_7351623fe5_KCS Data 2024-11-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-11-13 | 2024-11-13_735162:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-11-20 | 2024-11-20_27ca3f9783_KCS Data 2024-11-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-11-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-11-20_27ca3f9783_KCS Data 2024-11-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-11-20 | 2024-11-20_27ca3f:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-11-27 | 2024-11-27_4ad686f28e_KCS Data 2024-11-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-11-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-11-27_4ad686f28e_KCS Data 2024-11-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-11-27 | 2024-11-27_4ad686:   0%|          | 0.00/40.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-10-02 | 2024-10-02_8e248d169b_KCS Data 2024-10-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-10-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-10-02_8e248d169b_KCS Data 2024-10-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-10-02 | 2024-10-02_8e248d:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-10-09 | 2024-10-09_fe674903ca_KCS Data 2024-10-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-10-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-10-09_fe674903ca_KCS Data 2024-10-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-10-09 | 2024-10-09_fe6749:   0%|          | 0.00/35.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-10-16 | 2024-10-16_028fef70a3_KCS Data 2024-10-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-10-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-10-16_028fef70a3_KCS Data 2024-10-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-10-16 | 2024-10-16_028fef:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-10-23 | 2024-10-23_ca2bbf16a9_KCS Data 2024-10-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-10-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-10-23_ca2bbf16a9_KCS Data 2024-10-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-10-23 | 2024-10-23_ca2bbf:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-10-30 | 2024-10-30_eb3a3800cd_KCS Data 2024-10-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-10-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-10-30_eb3a3800cd_KCS Data 2024-10-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-10-30 | 2024-10-30_eb3a38:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-09-04 | 2024-09-04_e061cff456_KCS Data 2024-09-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-09-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-09-04_e061cff456_KCS Data 2024-09-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-09-04 | 2024-09-04_e061cf:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-09-11 | 2024-09-11_ecdda0b00a_KCS Data 2024-09-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-09-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-09-11_ecdda0b00a_KCS Data 2024-09-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-09-11 | 2024-09-11_ecdda0:   0%|          | 0.00/41.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-09-18 | 2024-09-18_b997143507_KCS Data 2024-09-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-09-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-09-18_b997143507_KCS Data 2024-09-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-09-18 | 2024-09-18_b99714:   0%|          | 0.00/41.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-09-25 | 2024-09-25_acaf16ae75_KCS Data 2024-09-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-09-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-09-25_acaf16ae75_KCS Data 2024-09-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-09-25 | 2024-09-25_acaf16:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-08-07 | 2024-08-07_f7b8132677_KCS Data 2024-08-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-08-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-08-07_f7b8132677_KCS Data 2024-08-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-08-07 | 2024-08-07_f7b813:   0%|          | 0.00/40.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-08-14 | 2024-08-14_9bc4ec0ff2_KCS Data 2024-08-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-08-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-08-14_9bc4ec0ff2_KCS Data 2024-08-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-08-14 | 2024-08-14_9bc4ec:   0%|          | 0.00/40.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-08-21 | 2024-08-21_5dedf34844_KCS Data 2024-08-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-08-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-08-21_5dedf34844_KCS Data 2024-08-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-08-21 | 2024-08-21_5dedf3:   0%|          | 0.00/40.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-08-28 | 2024-08-28_a065ff5940_KCS Data 2024-08-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-08-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-08-28_a065ff5940_KCS Data 2024-08-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-08-28 | 2024-08-28_a065ff:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-07-03 | 2024-07-03_888479aab8_KCS Data 2024-07-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-07-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-07-03_888479aab8_KCS Data 2024-07-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-07-03 | 2024-07-03_888479:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-07-10 | 2024-07-10_9513314bbd_KCS Data 2024-07-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-07-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-07-10_9513314bbd_KCS Data 2024-07-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-07-10 | 2024-07-10_951331:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-07-17 | 2024-07-17_33601ad9c5_KCS Data 2024-07-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-07-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-07-17_33601ad9c5_KCS Data 2024-07-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-07-17 | 2024-07-17_33601a:   0%|          | 0.00/41.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-07-24 | 2024-07-24_3e7bed84f6_KCS Data 2024-07-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-07-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-07-24_3e7bed84f6_KCS Data 2024-07-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-07-24 | 2024-07-24_3e7bed:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-07-31 | 2024-07-31_7b075cfefb_KCS Data 2024-07-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-07-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-07-31_7b075cfefb_KCS Data 2024-07-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-07-31 | 2024-07-31_7b075c:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-06-05 | 2024-06-05_4f64da0102_KCS Data 2024-06-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-06-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-06-05_4f64da0102_KCS Data 2024-06-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-06-05 | 2024-06-05_4f64da:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-06-12 | 2024-06-12_df12621cc8_KCS Data 2024-06-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-06-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-06-12_df12621cc8_KCS Data 2024-06-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-06-12 | 2024-06-12_df1262:   0%|          | 0.00/40.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-06-19 | 2024-06-19_856fc73fd4_KCS Data 2024-06-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-06-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-06-19_856fc73fd4_KCS Data 2024-06-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-06-19 | 2024-06-19_856fc7:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-06-26 | 2024-06-26_e550e88d9d_KCS Data 2024-06-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-06-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-06-26_e550e88d9d_KCS Data 2024-06-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-06-26 | 2024-06-26_e550e8:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-05-01 | 2024-05-01_a99126110e_KCS Data 2024-05-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-05-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-05-01_a99126110e_KCS Data 2024-05-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-05-01 | 2024-05-01_a99126:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-05-08 | 2024-05-08_dc20f14a37_KCS Data 2024-05-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-05-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-05-08_dc20f14a37_KCS Data 2024-05-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-05-08 | 2024-05-08_dc20f1:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-05-15 | 2024-05-15_caa6d8cddb_KCS Data 2024-05-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-05-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-05-15_caa6d8cddb_KCS Data 2024-05-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-05-15 | 2024-05-15_caa6d8:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-05-22 | 2024-05-22_16442911ec_KCS Data 2024-05-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-05-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-05-22_16442911ec_KCS Data 2024-05-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-05-22 | 2024-05-22_164429:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-05-29 | 2024-05-29_915ff4d7a5_KCS Data 2024-05-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-05-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-05-29_915ff4d7a5_KCS Data 2024-05-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-05-29 | 2024-05-29_915ff4:   0%|          | 0.00/35.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-04-03 | 2024-04-03_ca12d666d9_KCS Data 2024-04-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-04-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-04-03_ca12d666d9_KCS Data 2024-04-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-04-03 | 2024-04-03_ca12d6:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-04-10 | 2024-04-10_c36a170ef6_KCS Data 2024-04-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-04-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-04-10_c36a170ef6_KCS Data 2024-04-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-04-10 | 2024-04-10_c36a17:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-04-17 | 2024-04-17_637c98639b_KCS Data 2024-04-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-04-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-04-17_637c98639b_KCS Data 2024-04-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-04-17 | 2024-04-17_637c98:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-04-24 | 2024-04-24_0ff79f80ca_KCS Data 2024-04-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-04-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-04-24_0ff79f80ca_KCS Data 2024-04-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-04-24 | 2024-04-24_0ff79f:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-03-06 | 2024-03-06_13738ed81f_KCS Data 2024-03-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-03-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-03-06_13738ed81f_KCS Data 2024-03-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-03-06 | 2024-03-06_13738e:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-03-13 | 2024-03-13_674eb01203_KCS Data 2024-03-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-03-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-03-13_674eb01203_KCS Data 2024-03-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-03-13 | 2024-03-13_674eb0:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-03-20 | 2024-03-20_464f858305_KCS Data 2024-03-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-03-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-03-20_464f858305_KCS Data 2024-03-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-03-20 | 2024-03-20_464f85:   0%|          | 0.00/43.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-03-27 | 2024-03-27_6b1bed8662_KCS Data 2024-03-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-03-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-03-27_6b1bed8662_KCS Data 2024-03-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-03-27 | 2024-03-27_6b1bed:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-02-07 | 2024-02-07_63ecf66516_KCS Data 2024-02-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-02-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-02-07_63ecf66516_KCS Data 2024-02-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-02-07 | 2024-02-07_63ecf6:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-02-14 | 2024-02-14_f9a846665d_KCS Data 2024-02-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-02-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-02-14_f9a846665d_KCS Data 2024-02-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-02-14 | 2024-02-14_f9a846:   0%|          | 0.00/36.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-02-21 | 2024-02-21_6cdb3a7101_KCS Data 2024-02-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-02-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-02-21_6cdb3a7101_KCS Data 2024-02-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-02-21 | 2024-02-21_6cdb3a:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2024-02-28 | 2024-02-28_8d5938a4d5_KCS Data 2024-02-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202024-02-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2024\xlsx\2024-02-28_8d5938a4d5_KCS Data 2024-02-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2024-02-28 | 2024-02-28_8d5938:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-12-06 | 2023-12-06_5d52106ae2_KCS Data 2023-12-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-12-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-12-06_5d52106ae2_KCS Data 2023-12-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-12-06 | 2023-12-06_5d5210:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-12-13 | 2023-12-13_3851623338_KCS Data 2023-12-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-12-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-12-13_3851623338_KCS Data 2023-12-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-12-13 | 2023-12-13_385162:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-12-20 | 2023-12-20_2ec2d817c2_KCS Data 2023-12-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-12-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-12-20_2ec2d817c2_KCS Data 2023-12-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-12-20 | 2023-12-20_2ec2d8:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-12-27 | 2023-12-27_15719c04a9_KCS Data 2023-12-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-12-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-12-27_15719c04a9_KCS Data 2023-12-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-12-27 | 2023-12-27_15719c:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-11-01 | 2023-11-01_114459938f_KCS Data 2023-11-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-11-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-11-01_114459938f_KCS Data 2023-11-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-11-01 | 2023-11-01_114459:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-11-08 | 2023-11-08_ac6a3b253d_KCS Data 2023-11-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-11-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-11-08_ac6a3b253d_KCS Data 2023-11-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-11-08 | 2023-11-08_ac6a3b:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-11-15 | 2023-11-15_ed5df6d719_KCS Data 2023-11-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-11-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-11-15_ed5df6d719_KCS Data 2023-11-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-11-15 | 2023-11-15_ed5df6:   0%|          | 0.00/41.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-11-22 | 2023-11-22_5e1da226c4_KCS Data 2023-11-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-11-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-11-22_5e1da226c4_KCS Data 2023-11-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-11-22 | 2023-11-22_5e1da2:   0%|          | 0.00/41.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-11-29 | 2023-11-29_28ea3cb6da_KCS Data 2023-11-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-11-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-11-29_28ea3cb6da_KCS Data 2023-11-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-11-29 | 2023-11-29_28ea3c:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-10-04 | 2023-10-04_424d9f1e1b_KCS Data 2023-10-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-10-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-10-04_424d9f1e1b_KCS Data 2023-10-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-10-04 | 2023-10-04_424d9f:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-10-11 | 2023-10-11_298dbba346_KCS Data 2023-10-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-10-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-10-11_298dbba346_KCS Data 2023-10-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-10-11 | 2023-10-11_298dbb:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-10-18 | 2023-10-18_97ab7d8b7c_KCS Data 2023-10-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-10-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-10-18_97ab7d8b7c_KCS Data 2023-10-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-10-18 | 2023-10-18_97ab7d:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-10-25 | 2023-10-25_390dba46d8_KCS Data 2023-10-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-10-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-10-25_390dba46d8_KCS Data 2023-10-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-10-25 | 2023-10-25_390dba:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-09-06 | 2023-09-06_1256afaf53_KCS Data 2023-09-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-09-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-09-06_1256afaf53_KCS Data 2023-09-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-09-06 | 2023-09-06_1256af:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-09-13 | 2023-09-13_7a4b3eeaa3_KCS Data 2023-09-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-09-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-09-13_7a4b3eeaa3_KCS Data 2023-09-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-09-13 | 2023-09-13_7a4b3e:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-09-20 | 2023-09-20_3235639db3_KCS Data 2023-09-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-09-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-09-20_3235639db3_KCS Data 2023-09-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-09-20 | 2023-09-20_323563:   0%|          | 0.00/34.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-09-27 | 2023-09-27_71c331ed73_KCS Data 2023-09-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-09-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-09-27_71c331ed73_KCS Data 2023-09-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-09-27 | 2023-09-27_71c331:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-08-02 | 2023-08-02_ecdd7c8c87_KCS Data 2023-08-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-08-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-08-02_ecdd7c8c87_KCS Data 2023-08-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-08-02 | 2023-08-02_ecdd7c:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-08-09 | 2023-08-09_ed840bde58_KCS Data 2023-08-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-08-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-08-09_ed840bde58_KCS Data 2023-08-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-08-09 | 2023-08-09_ed840b:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-08-16 | 2023-08-16_753a664689_KCS Data 2023-08-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-08-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-08-16_753a664689_KCS Data 2023-08-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-08-16 | 2023-08-16_753a66:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-08-23 | 2023-08-23_cee70f14b9_KCS Data 2023-08-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-08-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-08-23_cee70f14b9_KCS Data 2023-08-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-08-23 | 2023-08-23_cee70f:   0%|          | 0.00/37.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-08-30 | 2023-08-30_8982110093_KCS Data 2023-08-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-08-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-08-30_8982110093_KCS Data 2023-08-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-08-30 | 2023-08-30_898211:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-07-05 | 2023-07-05_1b3f9b92fc_KCS Data 2023-07-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-07-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-07-05_1b3f9b92fc_KCS Data 2023-07-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-07-05 | 2023-07-05_1b3f9b:   0%|          | 0.00/41.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-07-12 | 2023-07-12_8aa51be0f1_KCS Data 2023-07-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-07-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-07-12_8aa51be0f1_KCS Data 2023-07-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-07-12 | 2023-07-12_8aa51b:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-07-19 | 2023-07-19_9cd7327201_KCS Data 2023-07-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-07-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-07-19_9cd7327201_KCS Data 2023-07-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-07-19 | 2023-07-19_9cd732:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-07-26 | 2023-07-26_4cfe6947f2_KCS Data 2023-07-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-07-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-07-26_4cfe6947f2_KCS Data 2023-07-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-07-26 | 2023-07-26_4cfe69:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-06-07 | 2023-06-07_45db30c6b8_KCS Data 2023-06-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-06-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-06-07_45db30c6b8_KCS Data 2023-06-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-06-07 | 2023-06-07_45db30:   0%|          | 0.00/37.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-06-14 | 2023-06-14_a91721058e_KCS Data 2023-06-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-06-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-06-14_a91721058e_KCS Data 2023-06-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-06-14 | 2023-06-14_a91721:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-06-21 | 2023-06-21_2832875e5e_KCS Data 2023-06-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-06-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-06-21_2832875e5e_KCS Data 2023-06-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-06-21 | 2023-06-21_283287:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-06-28 | 2023-06-28_4e340326c0_KCS Data 2023-06-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-06-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-06-28_4e340326c0_KCS Data 2023-06-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-06-28 | 2023-06-28_4e3403:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-05-03 | 2023-05-03_57b33f04d8_KCS Data 2023-05-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-05-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-05-03_57b33f04d8_KCS Data 2023-05-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-05-03 | 2023-05-03_57b33f:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-05-10 | 2023-05-10_716cc77030_KCS Data 2023-05-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-05-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-05-10_716cc77030_KCS Data 2023-05-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-05-10 | 2023-05-10_716cc7:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-05-17 | 2023-05-17_a1e72cba91_KCS Data 2023-05-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-05-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-05-17_a1e72cba91_KCS Data 2023-05-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-05-17 | 2023-05-17_a1e72c:   0%|          | 0.00/38.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-05-24 | 2023-05-24_b0f7b2ee9d_KCS Data 2023-05-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-05-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-05-24_b0f7b2ee9d_KCS Data 2023-05-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-05-24 | 2023-05-24_b0f7b2:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-05-31 | 2023-05-31_7eeeeaba40_KCS Data 2023-05-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-05-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-05-31_7eeeeaba40_KCS Data 2023-05-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-05-31 | 2023-05-31_7eeeea:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-04-05 | 2023-04-05_eea0918978_KCS Data 2023-04-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-04-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-04-05_eea0918978_KCS Data 2023-04-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-04-05 | 2023-04-05_eea091:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-04-12 | 2023-04-12_d90c6ced2b_KCS Data 2023-04-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-04-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-04-12_d90c6ced2b_KCS Data 2023-04-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-04-12 | 2023-04-12_d90c6c:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-04-19 | 2023-04-19_78b94c4301_KCS Data 2023-04-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-04-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-04-19_78b94c4301_KCS Data 2023-04-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-04-19 | 2023-04-19_78b94c:   0%|          | 0.00/35.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-04-26 | 2023-04-26_a388df9182_KCS Data 2023-04-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-04-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-04-26_a388df9182_KCS Data 2023-04-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-04-26 | 2023-04-26_a388df:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-03-01 | 2023-03-01_e19587fe01_KCS Data 2023-03-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-03-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-03-01_e19587fe01_KCS Data 2023-03-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-03-01 | 2023-03-01_e19587:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-03-08 | 2023-03-08_7917ed8d73_KCS Data 2023-03-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-03-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-03-08_7917ed8d73_KCS Data 2023-03-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-03-08 | 2023-03-08_7917ed:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-03-15 | 2023-03-15_78158a070b_KCS Data 2023-03-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-03-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-03-15_78158a070b_KCS Data 2023-03-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-03-15 | 2023-03-15_78158a:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-03-22 | 2023-03-22_3b6549d170_KCS Data 2023-03-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-03-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-03-22_3b6549d170_KCS Data 2023-03-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-03-22 | 2023-03-22_3b6549:   0%|          | 0.00/36.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-03-29 | 2023-03-29_0aea466f90_KCS Data 2023-03-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-03-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-03-29_0aea466f90_KCS Data 2023-03-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-03-29 | 2023-03-29_0aea46:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-02-01 | 2023-02-01_a66137fff0_KCS Data 2023-02-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-02-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-02-01_a66137fff0_KCS Data 2023-02-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-02-01 | 2023-02-01_a66137:   0%|          | 0.00/34.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-02-08 | 2023-02-08_c5a62cdc69_KCS Data 2023-02-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-02-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-02-08_c5a62cdc69_KCS Data 2023-02-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-02-08 | 2023-02-08_c5a62c:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-02-15 | 2023-02-15_7170055115_KCS Data 2023-02-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-02-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-02-15_7170055115_KCS Data 2023-02-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-02-15 | 2023-02-15_717005:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-02-22 | 2023-02-22_f5730400c0_KCS Data 2023-02-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-02-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-02-22_f5730400c0_KCS Data 2023-02-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-02-22 | 2023-02-22_f57304:   0%|          | 0.00/34.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-01-04 | 2023-01-04_d91c054aef_KCS Data 2023-01-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-01-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-01-04_d91c054aef_KCS Data 2023-01-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-01-04 | 2023-01-04_d91c05:   0%|          | 0.00/34.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-01-11 | 2023-01-11_571ae4a674_KCS Data 2023-01-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-01-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-01-11_571ae4a674_KCS Data 2023-01-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-01-11 | 2023-01-11_571ae4:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-01-18 | 2023-01-18_c08e61ffdf_KCS Data 2023-01-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-01-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-01-18_c08e61ffdf_KCS Data 2023-01-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-01-18 | 2023-01-18_c08e61:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2023-01-25 | 2023-01-25_b7f4ab6d97_KCS Data 2023-01-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202023-01-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2023\xlsx\2023-01-25_b7f4ab6d97_KCS Data 2023-01-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2023-01-25 | 2023-01-25_b7f4ab:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-12-07 | 2022-12-07_70011dea8a_KCS Data 2022-12-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-12-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-12-07_70011dea8a_KCS Data 2022-12-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-12-07 | 2022-12-07_70011d:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-12-14 | 2022-12-14_aa30082534_KCS Data 2022-12-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-12-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-12-14_aa30082534_KCS Data 2022-12-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-12-14 | 2022-12-14_aa3008:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-12-21 | 2022-12-21_eb5945e14f_KCS Data 2022-12-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-12-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-12-21_eb5945e14f_KCS Data 2022-12-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-12-21 | 2022-12-21_eb5945:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-12-28 | 2022-12-28_8741695f08_KCS Data 2022-12-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-12-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-12-28_8741695f08_KCS Data 2022-12-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-12-28 | 2022-12-28_874169:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-11-02 | 2022-11-02_9aa1825f58_KCS Data 2022-11-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-11-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-11-02_9aa1825f58_KCS Data 2022-11-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-11-02 | 2022-11-02_9aa182:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-11-09 | 2022-11-09_83af4a9f7f_KCS Data 2022-11-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-11-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-11-09_83af4a9f7f_KCS Data 2022-11-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-11-09 | 2022-11-09_83af4a:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-11-16 | 2022-11-16_c041750ce1_KCS Data 2022-11-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-11-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-11-16_c041750ce1_KCS Data 2022-11-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-11-16 | 2022-11-16_c04175:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-11-23 | 2022-11-23_470a039942_KCS Data 2022-11-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-11-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-11-23_470a039942_KCS Data 2022-11-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-11-23 | 2022-11-23_470a03:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-11-30 | 2022-11-30_6624670fe0_KCS Data 2022-11-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-11-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-11-30_6624670fe0_KCS Data 2022-11-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-11-30 | 2022-11-30_662467:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-10-05 | 2022-10-05_dc69752b25_KCS Data 2022-10-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-10-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-10-05_dc69752b25_KCS Data 2022-10-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-10-05 | 2022-10-05_dc6975:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-10-12 | 2022-10-12_15d8d77661_KCS Data 2022-10-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-10-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-10-12_15d8d77661_KCS Data 2022-10-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-10-12 | 2022-10-12_15d8d7:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-10-19 | 2022-10-19_cb774a34c9_KCS Data 2022-10-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-10-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-10-19_cb774a34c9_KCS Data 2022-10-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-10-19 | 2022-10-19_cb774a:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-10-26 | 2022-10-26_c1c47611ab_KCS Data 2022-10-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-10-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-10-26_c1c47611ab_KCS Data 2022-10-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-10-26 | 2022-10-26_c1c476:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-09-07 | 2022-09-07_7239a7e03b_KCS Data 2022-09-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-09-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-09-07_7239a7e03b_KCS Data 2022-09-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-09-07 | 2022-09-07_7239a7:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-09-14 | 2022-09-14_6f4d3f987a_KCS Data 2022-09-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-09-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-09-14_6f4d3f987a_KCS Data 2022-09-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-09-14 | 2022-09-14_6f4d3f:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-09-21 | 2022-09-21_aa7db24547_KCS Data 2022-09-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-09-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-09-21_aa7db24547_KCS Data 2022-09-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-09-21 | 2022-09-21_aa7db2:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-09-28 | 2022-09-28_88c4b42432_KCS Data 2022-09-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-09-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-09-28_88c4b42432_KCS Data 2022-09-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-09-28 | 2022-09-28_88c4b4:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-08-03 | 2022-08-03_fde3f7fa88_KCS Data 2022-08-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-08-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-08-03_fde3f7fa88_KCS Data 2022-08-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-08-03 | 2022-08-03_fde3f7:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-08-10 | 2022-08-10_c25154579a_KCS Data 2022-08-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-08-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-08-10_c25154579a_KCS Data 2022-08-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-08-10 | 2022-08-10_c25154:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-08-17 | 2022-08-17_4315275802_KCS Data 2022-08-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-08-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-08-17_4315275802_KCS Data 2022-08-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-08-17 | 2022-08-17_431527:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-08-24 | 2022-08-24_4a2fcb1db0_KCS Data 2022-08-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-08-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-08-24_4a2fcb1db0_KCS Data 2022-08-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-08-24 | 2022-08-24_4a2fcb:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-08-31 | 2022-08-31_f264cacc62_KCS Data 2022-08-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-08-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-08-31_f264cacc62_KCS Data 2022-08-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-08-31 | 2022-08-31_f264ca:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-07-06 | 2022-07-06_13a0946fa3_KCS Data 2022-07-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-07-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-07-06_13a0946fa3_KCS Data 2022-07-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-07-06 | 2022-07-06_13a094:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-07-13 | 2022-07-13_0cc71e52f1_KCS Data 2022-07-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-07-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-07-13_0cc71e52f1_KCS Data 2022-07-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-07-13 | 2022-07-13_0cc71e:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-07-20 | 2022-07-20_e6e41cb4de_KCS Data 2022-07-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-07-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-07-20_e6e41cb4de_KCS Data 2022-07-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-07-20 | 2022-07-20_e6e41c:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-07-27 | 2022-07-27_40b7ba603d_KCS Data 2022-07-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-07-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-07-27_40b7ba603d_KCS Data 2022-07-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-07-27 | 2022-07-27_40b7ba:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-06-01 | 2022-06-01_6ed962d0cc_KCS Data 2022-06-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-06-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-06-01_6ed962d0cc_KCS Data 2022-06-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-06-01 | 2022-06-01_6ed962:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-06-08 | 2022-06-08_1d77362899_KCS Data 2022-06-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-06-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-06-08_1d77362899_KCS Data 2022-06-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-06-08 | 2022-06-08_1d7736:   0%|          | 0.00/40.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-06-15 | 2022-06-15_2c1ed23773_KCS Data 2022-06-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-06-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-06-15_2c1ed23773_KCS Data 2022-06-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-06-15 | 2022-06-15_2c1ed2:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-06-22 | 2022-06-22_e853b5769b_KCS Data 2022-06-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-06-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-06-22_e853b5769b_KCS Data 2022-06-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-06-22 | 2022-06-22_e853b5:   0%|          | 0.00/40.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-06-29 | 2022-06-29_7ce8e9568b_KCS Data 2022-06-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-06-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-06-29_7ce8e9568b_KCS Data 2022-06-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-06-29 | 2022-06-29_7ce8e9:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-05-04 | 2022-05-04_83ef6a0e35_KCS Data 2022-05-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-05-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-05-04_83ef6a0e35_KCS Data 2022-05-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-05-04 | 2022-05-04_83ef6a:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-05-11 | 2022-05-11_a05aec3a75_KCS Data 2022-05-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-05-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-05-11_a05aec3a75_KCS Data 2022-05-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-05-11 | 2022-05-11_a05aec:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-05-18 | 2022-05-18_e3410bafe1_KCS Data 2022-05-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-05-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-05-18_e3410bafe1_KCS Data 2022-05-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-05-18 | 2022-05-18_e3410b:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-05-25 | 2022-05-25_800ac91b04_KCS Data 2022-05-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-05-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-05-25_800ac91b04_KCS Data 2022-05-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-05-25 | 2022-05-25_800ac9:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-04-06 | 2022-04-06_9f0d409cbb_KCS Data 2022-04-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-04-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-04-06_9f0d409cbb_KCS Data 2022-04-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-04-06 | 2022-04-06_9f0d40:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-04-13 | 2022-04-13_dcc01cb530_KCS Data 2022-04-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-04-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-04-13_dcc01cb530_KCS Data 2022-04-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-04-13 | 2022-04-13_dcc01c:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-04-20 | 2022-04-20_835c9eafbe_KCS Data 2022-04-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-04-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-04-20_835c9eafbe_KCS Data 2022-04-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-04-20 | 2022-04-20_835c9e:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-04-27 | 2022-04-27_9e5b2d83f0_KCS Data 2022-04-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-04-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-04-27_9e5b2d83f0_KCS Data 2022-04-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-04-27 | 2022-04-27_9e5b2d:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-03-02 | 2022-03-02_3a015d9268_KCS Data 2022-03-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-03-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-03-02_3a015d9268_KCS Data 2022-03-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-03-02 | 2022-03-02_3a015d:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-03-09 | 2022-03-09_7bcbe67c5f_KCS Data 2022-03-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-03-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-03-09_7bcbe67c5f_KCS Data 2022-03-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-03-09 | 2022-03-09_7bcbe6:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-03-16 | 2022-03-16_6ae3661700_KCS Data 2022-03-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-03-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-03-16_6ae3661700_KCS Data 2022-03-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-03-16 | 2022-03-16_6ae366:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-03-23 | 2022-03-23_d2871ec8f2_KCS Data 2022-03-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-03-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-03-23_d2871ec8f2_KCS Data 2022-03-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-03-23 | 2022-03-23_d2871e:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-03-30 | 2022-03-30_1a88488c8e_KCS Data 2022-03-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-03-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-03-30_1a88488c8e_KCS Data 2022-03-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-03-30 | 2022-03-30_1a8848:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-02-02 | 2022-02-02_e099d432e4_KCS Data 2022-02-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-02-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-02-02_e099d432e4_KCS Data 2022-02-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-02-02 | 2022-02-02_e099d4:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-02-09 | 2022-02-09_c99d50c952_KCS Data 2022-02-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-02-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-02-09_c99d50c952_KCS Data 2022-02-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-02-09 | 2022-02-09_c99d50:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-02-16 | 2022-02-16_54d9d75f80_KCS Data 2022-02-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-02-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-02-16_54d9d75f80_KCS Data 2022-02-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-02-16 | 2022-02-16_54d9d7:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-02-23 | 2022-02-23_557e1a9f6f_KCS Data 2022-02-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-02-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-02-23_557e1a9f6f_KCS Data 2022-02-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-02-23 | 2022-02-23_557e1a:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-01-05 | 2022-01-05_767ea97198_KCS Data 2022-01-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-01-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-01-05_767ea97198_KCS Data 2022-01-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-01-05 | 2022-01-05_767ea9:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-01-12 | 2022-01-12_c829867824_KCS Data 2022-01-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-01-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-01-12_c829867824_KCS Data 2022-01-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-01-12 | 2022-01-12_c82986:   0%|          | 0.00/42.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-01-19 | 2022-01-19_1a7d234856_KCS Data 2022-01-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-01-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-01-19_1a7d234856_KCS Data 2022-01-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-01-19 | 2022-01-19_1a7d23:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2022-01-26 | 2022-01-26_8f762a9090_KCS Data 2022-01-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202022-01-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2022\xlsx\2022-01-26_8f762a9090_KCS Data 2022-01-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2022-01-26 | 2022-01-26_8f762a:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-12-01 | 2021-12-01_a87d756077_KCS Data 2021-12-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-12-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-12-01_a87d756077_KCS Data 2021-12-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-12-01 | 2021-12-01_a87d75:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-12-08 | 2021-12-08_df75793b46_KCS Data 2021-12-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-12-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-12-08_df75793b46_KCS Data 2021-12-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-12-08 | 2021-12-08_df7579:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-12-15 | 2021-12-15_edd72236cd_KCS Data 2021-12-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-12-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-12-15_edd72236cd_KCS Data 2021-12-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-12-15 | 2021-12-15_edd722:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-12-22 | 2021-12-22_f631d56209_KCS Data 2021-12-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-12-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-12-22_f631d56209_KCS Data 2021-12-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-12-22 | 2021-12-22_f631d5:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-12-29 | 2021-12-29_9db78f910d_KCS Data 2021-12-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-12-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-12-29_9db78f910d_KCS Data 2021-12-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-12-29 | 2021-12-29_9db78f:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-11-03 | 2021-11-03_480661f5bc_KCS Data 2021-11-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-11-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-11-03_480661f5bc_KCS Data 2021-11-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-11-03 | 2021-11-03_480661:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-11-10 | 2021-11-10_b2cae05169_KCS Data 2021-11-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-11-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-11-10_b2cae05169_KCS Data 2021-11-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-11-10 | 2021-11-10_b2cae0:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-11-17 | 2021-11-17_ee8323581f_KCS Data 2021-11-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-11-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-11-17_ee8323581f_KCS Data 2021-11-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-11-17 | 2021-11-17_ee8323:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-11-24 | 2021-11-24_23cac3b01f_KCS Data 2021-11-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-11-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-11-24_23cac3b01f_KCS Data 2021-11-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-11-24 | 2021-11-24_23cac3:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-10-06 | 2021-10-06_34cacf3a1b_KCS Data 2021-10-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-10-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-10-06_34cacf3a1b_KCS Data 2021-10-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-10-06 | 2021-10-06_34cacf:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-10-13 | 2021-10-13_fc907a0036_KCS Data 2021-10-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-10-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-10-13_fc907a0036_KCS Data 2021-10-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-10-13 | 2021-10-13_fc907a:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-10-20 | 2021-10-20_d8d8449457_KCS Data 2021-10-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-10-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-10-20_d8d8449457_KCS Data 2021-10-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-10-20 | 2021-10-20_d8d844:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-10-27 | 2021-10-27_7dbcc796a7_KCS Data 2021-10-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-10-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-10-27_7dbcc796a7_KCS Data 2021-10-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-10-27 | 2021-10-27_7dbcc7:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-09-01 | 2021-09-01_f3c928834b_KCS Data 2021-09-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-09-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-09-01_f3c928834b_KCS Data 2021-09-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-09-01 | 2021-09-01_f3c928:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-09-08 | 2021-09-08_e77569db6b_KCS Data 2021-09-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-09-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-09-08_e77569db6b_KCS Data 2021-09-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-09-08 | 2021-09-08_e77569:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-09-15 | 2021-09-15_ac26206004_KCS Data 2021-09-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-09-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-09-15_ac26206004_KCS Data 2021-09-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-09-15 | 2021-09-15_ac2620:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-09-22 | 2021-09-22_238c50dd37_KCS Data 2021-09-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-09-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-09-22_238c50dd37_KCS Data 2021-09-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-09-22 | 2021-09-22_238c50:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-09-29 | 2021-09-29_df1e39b361_KCS Data 2021-09-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-09-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-09-29_df1e39b361_KCS Data 2021-09-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-09-29 | 2021-09-29_df1e39:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-08-04 | 2021-08-04_4424e033b2_KCS Data 2021-08-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-08-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-08-04_4424e033b2_KCS Data 2021-08-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-08-04 | 2021-08-04_4424e0:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-08-11 | 2021-08-11_99745e7d7b_KCS Data 2021-08-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-08-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-08-11_99745e7d7b_KCS Data 2021-08-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-08-11 | 2021-08-11_99745e:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-08-18 | 2021-08-18_706e1fd5dc_KCS Data 2021-08-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-08-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-08-18_706e1fd5dc_KCS Data 2021-08-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-08-18 | 2021-08-18_706e1f:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-08-25 | 2021-08-25_d577388983_KCS Data 2021-08-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-08-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-08-25_d577388983_KCS Data 2021-08-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-08-25 | 2021-08-25_d57738:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-07-07 | 2021-07-07_69f846aa4c_KCS Data 2021-07-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-07-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-07-07_69f846aa4c_KCS Data 2021-07-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-07-07 | 2021-07-07_69f846:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-07-14 | 2021-07-14_cf03c85046_KCS Data 2021-07-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-07-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-07-14_cf03c85046_KCS Data 2021-07-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-07-14 | 2021-07-14_cf03c8:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-07-21 | 2021-07-21_fd0cd49021_KCS Data 2021-07-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-07-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-07-21_fd0cd49021_KCS Data 2021-07-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-07-21 | 2021-07-21_fd0cd4:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-07-28 | 2021-07-28_0f32762502_KCS Data 2021-07-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-07-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-07-28_0f32762502_KCS Data 2021-07-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-07-28 | 2021-07-28_0f3276:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-06-02 | 2021-06-02_0adb2ff2f2_KCS Data 2021-06-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-06-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-06-02_0adb2ff2f2_KCS Data 2021-06-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-06-02 | 2021-06-02_0adb2f:   0%|          | 0.00/34.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-06-09 | 2021-06-09_f5c3517d27_KCS Data 2021-06-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-06-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-06-09_f5c3517d27_KCS Data 2021-06-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-06-09 | 2021-06-09_f5c351:   0%|          | 0.00/33.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-06-16 | 2021-06-16_522f33b819_KCS Data 2021-06-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-06-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-06-16_522f33b819_KCS Data 2021-06-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-06-16 | 2021-06-16_522f33:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-06-23 | 2021-06-23_6858d9838f_KCS Data 2021-06-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-06-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-06-23_6858d9838f_KCS Data 2021-06-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-06-23 | 2021-06-23_6858d9:   0%|          | 0.00/34.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-06-30 | 2021-06-30_6ce88b8257_KCS Data 2021-06-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-06-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-06-30_6ce88b8257_KCS Data 2021-06-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-06-30 | 2021-06-30_6ce88b:   0%|          | 0.00/34.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-05-05 | 2021-05-05_6fcf6ec660_KCS Data 2021-05-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-05-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-05-05_6fcf6ec660_KCS Data 2021-05-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-05-05 | 2021-05-05_6fcf6e:   0%|          | 0.00/33.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-05-12 | 2021-05-12_da16d88fab_KCS Data 2021-05-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-05-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-05-12_da16d88fab_KCS Data 2021-05-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-05-12 | 2021-05-12_da16d8:   0%|          | 0.00/34.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-05-19 | 2021-05-19_ff696b6a8c_KCS Data 2021-05-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-05-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-05-19_ff696b6a8c_KCS Data 2021-05-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-05-19 | 2021-05-19_ff696b:   0%|          | 0.00/34.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-05-26 | 2021-05-26_5a85c6dc59_KCS Data 2021-05-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-05-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-05-26_5a85c6dc59_KCS Data 2021-05-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-05-26 | 2021-05-26_5a85c6:   0%|          | 0.00/33.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-04-07 | 2021-04-07_e3d461c5fc_KCS Data 2021-04-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-04-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-04-07_e3d461c5fc_KCS Data 2021-04-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-04-07 | 2021-04-07_e3d461:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-04-14 | 2021-04-14_ad63c66efb_KCS Data 2021-04-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-04-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-04-14_ad63c66efb_KCS Data 2021-04-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-04-14 | 2021-04-14_ad63c6:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-04-21 | 2021-04-21_9bd5d59009_KCS Data 2021-04-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-04-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-04-21_9bd5d59009_KCS Data 2021-04-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-04-21 | 2021-04-21_9bd5d5:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-04-28 | 2021-04-28_d62eb4dd49_KCS Data 2021-04-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-04-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-04-28_d62eb4dd49_KCS Data 2021-04-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-04-28 | 2021-04-28_d62eb4:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-03-03 | 2021-03-03_e9fcf28e47_KCS Data 2021-03-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-03-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-03-03_e9fcf28e47_KCS Data 2021-03-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-03-03 | 2021-03-03_e9fcf2:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-03-10 | 2021-03-10_b18f08a1ff_KCS Data 2021-03-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-03-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-03-10_b18f08a1ff_KCS Data 2021-03-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-03-10 | 2021-03-10_b18f08:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-03-17 | 2021-03-17_f1e559532c_KCS Data 2021-03-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-03-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-03-17_f1e559532c_KCS Data 2021-03-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-03-17 | 2021-03-17_f1e559:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-03-24 | 2021-03-24_7e1e79cfe8_KCS Data 2021-03-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-03-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-03-24_7e1e79cfe8_KCS Data 2021-03-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-03-24 | 2021-03-24_7e1e79:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-03-31 | 2021-03-31_11478864af_KCS Data 2021-03-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-03-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-03-31_11478864af_KCS Data 2021-03-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-03-31 | 2021-03-31_114788:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-02-03 | 2021-02-03_6bb29c9052_KCS Data 2021-02-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-02-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-02-03_6bb29c9052_KCS Data 2021-02-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-02-03 | 2021-02-03_6bb29c:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-02-10 | 2021-02-10_7914b36fa9_KCS Data 2021-02-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-02-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-02-10_7914b36fa9_KCS Data 2021-02-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-02-10 | 2021-02-10_7914b3:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-02-17 | 2021-02-17_81dbaec1ef_KCS Data 2021-02-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-02-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-02-17_81dbaec1ef_KCS Data 2021-02-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-02-17 | 2021-02-17_81dbae:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-02-24 | 2021-02-24_826051dd12_KCS Data 2021-02-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-02-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-02-24_826051dd12_KCS Data 2021-02-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-02-24 | 2021-02-24_826051:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-01-06 | 2021-01-06_e1f3a281a6_KCS Data 2021-01-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-01-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-01-06_e1f3a281a6_KCS Data 2021-01-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-01-06 | 2021-01-06_e1f3a2:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-01-13 | 2021-01-13_7ceb97a85e_KCS Data 2021-01-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-01-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-01-13_7ceb97a85e_KCS Data 2021-01-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-01-13 | 2021-01-13_7ceb97:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-01-20 | 2021-01-20_ba8724bf3d_KCS Data 2021-01-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-01-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-01-20_ba8724bf3d_KCS Data 2021-01-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-01-20 | 2021-01-20_ba8724:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2021-01-27 | 2021-01-27_f26ce0cc13_KCS Data 2021-01-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202021-01-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2021\xlsx\2021-01-27_f26ce0cc13_KCS Data 2021-01-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2021-01-27 | 2021-01-27_f26ce0:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-12-02 | 2020-12-02_934cf2b065_KCS Data 2020-12-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-12-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-12-02_934cf2b065_KCS Data 2020-12-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-12-02 | 2020-12-02_934cf2:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-12-09 | 2020-12-09_a19a66ec5b_KCS Data 2020-12-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-12-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-12-09_a19a66ec5b_KCS Data 2020-12-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-12-09 | 2020-12-09_a19a66:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-12-16 | 2020-12-16_6bfbc171e8_KCS Data 2020-12-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-12-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-12-16_6bfbc171e8_KCS Data 2020-12-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-12-16 | 2020-12-16_6bfbc1:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-12-23 | 2020-12-23_6a151bb159_KCS Data 2020-12-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-12-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-12-23_6a151bb159_KCS Data 2020-12-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-12-23 | 2020-12-23_6a151b:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-12-30 | 2020-12-30_a9ca6c6e92_KCS Data 2020-12-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-12-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-12-30_a9ca6c6e92_KCS Data 2020-12-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-12-30 | 2020-12-30_a9ca6c:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-11-04 | 2020-11-04_3c984d4443_KCS Data 2020-11-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-11-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-11-04_3c984d4443_KCS Data 2020-11-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-11-04 | 2020-11-04_3c984d:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-11-11 | 2020-11-11_5192d74c46_KCS Data 2020-11-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-11-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-11-11_5192d74c46_KCS Data 2020-11-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-11-11 | 2020-11-11_5192d7:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-11-18 | 2020-11-18_9e090aa599_KCS Data 2020-11-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-11-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-11-18_9e090aa599_KCS Data 2020-11-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-11-18 | 2020-11-18_9e090a:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-11-25 | 2020-11-25_a21945cadc_KCS Data 2020-11-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-11-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-11-25_a21945cadc_KCS Data 2020-11-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-11-25 | 2020-11-25_a21945:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-10-07 | 2020-10-07_013db6228e_KCS Data 2020-10-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-10-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-10-07_013db6228e_KCS Data 2020-10-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-10-07 | 2020-10-07_013db6:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-10-14 | 2020-10-14_c160733135_KCS Data 2020-10-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-10-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-10-14_c160733135_KCS Data 2020-10-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-10-14 | 2020-10-14_c16073:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-10-21 | 2020-10-21_d039992055_KCS Data 2020-10-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-10-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-10-21_d039992055_KCS Data 2020-10-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-10-21 | 2020-10-21_d03999:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-10-28 | 2020-10-28_463334a68e_KCS Data 2020-10-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-10-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-10-28_463334a68e_KCS Data 2020-10-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-10-28 | 2020-10-28_463334:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-09-02 | 2020-09-02_2c5eafe95e_KCS Data 2020-09-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-09-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-09-02_2c5eafe95e_KCS Data 2020-09-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-09-02 | 2020-09-02_2c5eaf:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-09-09 | 2020-09-09_735b4b36eb_KCS Data 2020-09-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-09-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-09-09_735b4b36eb_KCS Data 2020-09-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-09-09 | 2020-09-09_735b4b:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-09-16 | 2020-09-16_d2483aa96d_KCS Data 2020-09-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-09-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-09-16_d2483aa96d_KCS Data 2020-09-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-09-16 | 2020-09-16_d2483a:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-09-23 | 2020-09-23_5e7b10c34e_KCS Data 2020-09-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-09-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-09-23_5e7b10c34e_KCS Data 2020-09-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-09-23 | 2020-09-23_5e7b10:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-09-30 | 2020-09-30_ef2a32117f_KCS Data 2020-09-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-09-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-09-30_ef2a32117f_KCS Data 2020-09-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-09-30 | 2020-09-30_ef2a32:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-08-05 | 2020-08-05_34f7c4d13f_KCS Data 2020-08-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-08-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-08-05_34f7c4d13f_KCS Data 2020-08-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-08-05 | 2020-08-05_34f7c4:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-08-12 | 2020-08-12_246e15cad9_KCS Data 2020-08-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-08-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-08-12_246e15cad9_KCS Data 2020-08-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-08-12 | 2020-08-12_246e15:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-08-19 | 2020-08-19_8c4d46ccda_KCS Data 2020-08-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-08-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-08-19_8c4d46ccda_KCS Data 2020-08-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-08-19 | 2020-08-19_8c4d46:   0%|          | 0.00/34.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-08-26 | 2020-08-26_a301654448_KCS Data 2020-08-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-08-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-08-26_a301654448_KCS Data 2020-08-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-08-26 | 2020-08-26_a30165:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-07-01 | 2020-07-01_37281f6d69_kcs_data_2020-07-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-07-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-07-01_37281f6d69_kcs_data_2020-07-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-07-01 | 2020-07-01_37281f:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-07-08 | 2020-07-08_0c1c8ced05_kcs_data_2020-07-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-07-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-07-08_0c1c8ced05_kcs_data_2020-07-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-07-08 | 2020-07-08_0c1c8c:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-07-15 | 2020-07-15_364c5d9de9_kcs_data_2020-07-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-07-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-07-15_364c5d9de9_kcs_data_2020-07-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-07-15 | 2020-07-15_364c5d:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-07-22 | 2020-07-22_6463378224_kcs_data_2020-07-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-07-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-07-22_6463378224_kcs_data_2020-07-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-07-22 | 2020-07-22_646337:   0%|          | 0.00/33.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-07-29 | 2020-07-29_948a51fa72_KCS Data 2020-07-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/KCS%20Data%202020-07-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-07-29_948a51fa72_KCS Data 2020-07-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-07-29 | 2020-07-29_948a51:   0%|          | 0.00/33.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-06-03 | 2020-06-03_77532651d9_kcs_data_2020-06-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-06-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-06-03_77532651d9_kcs_data_2020-06-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-06-03 | 2020-06-03_775326:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-06-10 | 2020-06-10_4048c53870_kcs_data_2020-06-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-06-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-06-10_4048c53870_kcs_data_2020-06-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-06-10 | 2020-06-10_4048c5:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-06-17 | 2020-06-17_08b33183f5_kcs_data_2020-06-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-06-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-06-17_08b33183f5_kcs_data_2020-06-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-06-17 | 2020-06-17_08b331:   0%|          | 0.00/36.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-06-24 | 2020-06-24_3e5364fff1_kcs_data_2020-06-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-06-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-06-24_3e5364fff1_kcs_data_2020-06-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-06-24 | 2020-06-24_3e5364:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-05-06 | 2020-05-06_1df58f6b33_kcs_data_2020-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-05-06_1df58f6b33_kcs_data_2020-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-05-06 | 2020-05-06_1df58f:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-05-13 | 2020-05-13_5820d63d38_kcs_data_2020-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-05-13_5820d63d38_kcs_data_2020-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-05-13 | 2020-05-13_5820d6:   0%|          | 0.00/37.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-05-20 | 2020-05-20_b76b74d832_kcs_data_2020-05-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-05-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-05-20_b76b74d832_kcs_data_2020-05-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-05-20 | 2020-05-20_b76b74:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-05-27 | 2020-05-27_3d59da3fd5_kcs_data_2020-05-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-05-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-05-27_3d59da3fd5_kcs_data_2020-05-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-05-27 | 2020-05-27_3d59da:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-04-01 | 2020-04-01_372fd28bea_kcs_data_2020-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-04-01_372fd28bea_kcs_data_2020-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-04-01 | 2020-04-01_372fd2:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-04-08 | 2020-04-08_8fa1898c51_kcs_data_2020-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-04-08_8fa1898c51_kcs_data_2020-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-04-08 | 2020-04-08_8fa189:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-04-15 | 2020-04-15_033a9f29e8_kcs_data_2020-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-04-15_033a9f29e8_kcs_data_2020-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-04-15 | 2020-04-15_033a9f:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-04-22 | 2020-04-22_981cfb00e5_kcs_data_2020-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-04-22_981cfb00e5_kcs_data_2020-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-04-22 | 2020-04-22_981cfb:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-04-29 | 2020-04-29_f8e19d5ee0_kcs_data_2020-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-04-29_f8e19d5ee0_kcs_data_2020-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-04-29 | 2020-04-29_f8e19d:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-03-04 | 2020-03-04_18ba64ef37_kcs_data_2020-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-03-04_18ba64ef37_kcs_data_2020-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-03-04 | 2020-03-04_18ba64:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-03-11 | 2020-03-11_f8a1d328fb_kcs_data_2020-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-03-11_f8a1d328fb_kcs_data_2020-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-03-11 | 2020-03-11_f8a1d3:   0%|          | 0.00/36.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-03-18 | 2020-03-18_e7120ddfd2_kcs_data_2020-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-03-18_e7120ddfd2_kcs_data_2020-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-03-18 | 2020-03-18_e7120d:   0%|          | 0.00/36.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-03-25 | 2020-03-25_ab70ee5c05_kcs_data_2020-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-03-25_ab70ee5c05_kcs_data_2020-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-03-25 | 2020-03-25_ab70ee:   0%|          | 0.00/36.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-02-05 | 2020-02-05_7d5e09648f_kcs_data_2020-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-02-05_7d5e09648f_kcs_data_2020-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-02-05 | 2020-02-05_7d5e09:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-02-12 | 2020-02-12_cf0fb841b3_kcs_data_2020-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-02-12_cf0fb841b3_kcs_data_2020-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-02-12 | 2020-02-12_cf0fb8:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-02-19 | 2020-02-19_a3c4ad5d22_kcs_data_2020-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-02-19_a3c4ad5d22_kcs_data_2020-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-02-19 | 2020-02-19_a3c4ad:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-02-26 | 2020-02-26_50d8f5cf43_kcs_data_2020-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-02-26_50d8f5cf43_kcs_data_2020-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-02-26 | 2020-02-26_50d8f5:   0%|          | 0.00/36.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-01-01 | 2020-01-01_65d4583129_kcs_data_2020-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-01-01_65d4583129_kcs_data_2020-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-01-01 | 2020-01-01_65d458:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-01-08 | 2020-01-08_899c6b004d_kcs_data_2020-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-01-08_899c6b004d_kcs_data_2020-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-01-08 | 2020-01-08_899c6b:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-01-15 | 2020-01-15_625b0f1867_kcs_data_2020-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-01-15_625b0f1867_kcs_data_2020-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-01-15 | 2020-01-15_625b0f:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-01-22 | 2020-01-22_613c5b632a_kcs_data_2020-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-01-22_613c5b632a_kcs_data_2020-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-01-22 | 2020-01-22_613c5b:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | kcs | 2020-01-29 | 2020-01-29_6b6e83cc43_kcs_data_2020-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/KCS/kcs_data_2020-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\kcs\2020\xlsx\2020-01-29_6b6e83cc43_kcs_data_2020-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | kcs | 2020-01-29 | 2020-01-29_6b6e83:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-05-06 | 2026-05-06_f94fa2ace3_NS Data 2026-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-05-06_f94fa2ace3_NS Data 2026-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-05-06 | 2026-05-06_f94fa2a:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-05-13 | 2026-05-13_7b937ec006_NS Data 2026-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-05-13_7b937ec006_NS Data 2026-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-05-13 | 2026-05-13_7b937ec:   0%|          | 0.00/32.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-04-01 | 2026-04-01_9a6c821e53_NS Data 2026-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-04-01_9a6c821e53_NS Data 2026-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-04-01 | 2026-04-01_9a6c821:   0%|          | 0.00/32.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-04-08 | 2026-04-08_7cb223192d_NS Data 2026-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-04-08_7cb223192d_NS Data 2026-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-04-08 | 2026-04-08_7cb2231:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-04-15 | 2026-04-15_ca32f7733a_NS Data 2026-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-04-15_ca32f7733a_NS Data 2026-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-04-15 | 2026-04-15_ca32f77:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-04-22 | 2026-04-22_07117685b9_NS Data 2026-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-04-22_07117685b9_NS Data 2026-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-04-22 | 2026-04-22_0711768:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-04-29 | 2026-04-29_00383cf5b1_NS Data 2026-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-04-29_00383cf5b1_NS Data 2026-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-04-29 | 2026-04-29_00383cf:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-03-04 | 2026-03-04_39377973bc_NS Data 2026-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-03-04_39377973bc_NS Data 2026-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-03-04 | 2026-03-04_3937797:   0%|          | 0.00/32.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-03-11 | 2026-03-11_75f601d524_NS Data 2026-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-03-11_75f601d524_NS Data 2026-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-03-11 | 2026-03-11_75f601d:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-03-18 | 2026-03-18_19fdd225f9_NS Data 2026-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-03-18_19fdd225f9_NS Data 2026-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-03-18 | 2026-03-18_19fdd22:   0%|          | 0.00/32.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-03-25 | 2026-03-25_4600e5f37f_NS Data 2026-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-03-25_4600e5f37f_NS Data 2026-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-03-25 | 2026-03-25_4600e5f:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-02-04 | 2026-02-04_d489339a82_NS Data 2026-02-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-02-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-02-04_d489339a82_NS Data 2026-02-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-02-04 | 2026-02-04_d489339:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-02-11 | 2026-02-11_b9aa3a5382_NS Data 2026-02-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-02-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-02-11_b9aa3a5382_NS Data 2026-02-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-02-11 | 2026-02-11_b9aa3a5:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-02-18 | 2026-02-18_240ef2f36d_NS Data 2026-02-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-02-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-02-18_240ef2f36d_NS Data 2026-02-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-02-18 | 2026-02-18_240ef2f:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-02-25 | 2026-02-25_b00aba0dde_NS Data 2026-02-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-02-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-02-25_b00aba0dde_NS Data 2026-02-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-02-25 | 2026-02-25_b00aba0:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-01-07 | 2026-01-07_189ef74c6e_NS Data 2026-01-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-01-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-01-07_189ef74c6e_NS Data 2026-01-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-01-07 | 2026-01-07_189ef74:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-01-14 | 2026-01-14_f2ba13fa95_NS Data 2026-01-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-01-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-01-14_f2ba13fa95_NS Data 2026-01-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-01-14 | 2026-01-14_f2ba13f:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-01-21 | 2026-01-21_6cefd2708a_NS Data 2026-01-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-01-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-01-21_6cefd2708a_NS Data 2026-01-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-01-21 | 2026-01-21_6cefd27:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2026-01-28 | 2026-01-28_0c687596ea_NS Data 2026-01-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202026-01-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2026\xlsx\2026-01-28_0c687596ea_NS Data 2026-01-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2026-01-28 | 2026-01-28_0c68759:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-12-31 | 2025-12-31_8a83e5d885_NS Data 2025-12-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-12-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-12-31_8a83e5d885_NS Data 2025-12-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-12-31 | 2025-12-31_8a83e5d:   0%|          | 0.00/32.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-12-03 | 2025-12-03_245ff34c24_NS Data 2025-12-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-12-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-12-03_245ff34c24_NS Data 2025-12-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-12-03 | 2025-12-03_245ff34:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-12-10 | 2025-12-10_8575e9906b_NS Data 2025-12-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-12-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-12-10_8575e9906b_NS Data 2025-12-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-12-10 | 2025-12-10_8575e99:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-12-17 | 2025-12-17_464945a456_NS Data 2025-12-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-12-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-12-17_464945a456_NS Data 2025-12-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-12-17 | 2025-12-17_464945a:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-12-24 | 2025-12-24_a7bec9faa9_NS Data 2025-12-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-12-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-12-24_a7bec9faa9_NS Data 2025-12-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-12-24 | 2025-12-24_a7bec9f:   0%|          | 0.00/32.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-11-05 | 2025-11-05_34aaaec81d_NS Data 2025-11-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-11-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-11-05_34aaaec81d_NS Data 2025-11-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-11-05 | 2025-11-05_34aaaec:   0%|          | 0.00/32.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-11-12 | 2025-11-12_6eab52eaec_NS Data 2025-11-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-11-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-11-12_6eab52eaec_NS Data 2025-11-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-11-12 | 2025-11-12_6eab52e:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-11-19 | 2025-11-19_d8862fa912_NS Data 2025-11-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-11-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-11-19_d8862fa912_NS Data 2025-11-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-11-19 | 2025-11-19_d8862fa:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-11-26 | 2025-11-26_6cdf484ae4_NS Data 2025-11-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-11-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-11-26_6cdf484ae4_NS Data 2025-11-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-11-26 | 2025-11-26_6cdf484:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-10-01 | 2025-10-01_8e92c171d9_NS Data 2025-10-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-10-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-10-01_8e92c171d9_NS Data 2025-10-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-10-01 | 2025-10-01_8e92c17:   0%|          | 0.00/32.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-10-08 | 2025-10-08_1c8ac1f9d9_NS Data 2025-10-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-10-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-10-08_1c8ac1f9d9_NS Data 2025-10-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-10-08 | 2025-10-08_1c8ac1f:   0%|          | 0.00/32.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-10-15 | 2025-10-15_28c5164774_NS Data 2025-10-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-10-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-10-15_28c5164774_NS Data 2025-10-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-10-15 | 2025-10-15_28c5164:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-10-22 | 2025-10-22_a9a269f123_NS Data 2025-10-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-10-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-10-22_a9a269f123_NS Data 2025-10-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-10-22 | 2025-10-22_a9a269f:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-10-29 | 2025-10-29_cfb9c85787_NS Data 2025-10-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-10-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-10-29_cfb9c85787_NS Data 2025-10-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-10-29 | 2025-10-29_cfb9c85:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-09-03 | 2025-09-03_d52d019667_NS Data 2025-09-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-09-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-09-03_d52d019667_NS Data 2025-09-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-09-03 | 2025-09-03_d52d019:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-09-10 | 2025-09-10_88a8c5e647_NS Data 2025-09-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-09-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-09-10_88a8c5e647_NS Data 2025-09-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-09-10 | 2025-09-10_88a8c5e:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-09-17 | 2025-09-17_3caf1bf103_NS Data 2025-09-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-09-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-09-17_3caf1bf103_NS Data 2025-09-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-09-17 | 2025-09-17_3caf1bf:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-09-24 | 2025-09-24_9dd1666858_NS Data 2025-09-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-09-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-09-24_9dd1666858_NS Data 2025-09-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-09-24 | 2025-09-24_9dd1666:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-08-06 | 2025-08-06_30f651d0ac_NS Data 2025-08-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-08-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-08-06_30f651d0ac_NS Data 2025-08-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-08-06 | 2025-08-06_30f651d:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-08-13 | 2025-08-13_4e8c0905d3_NS Data 2025-08-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-08-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-08-13_4e8c0905d3_NS Data 2025-08-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-08-13 | 2025-08-13_4e8c090:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-08-20 | 2025-08-20_f63ad1a379_NS Data 2025-08-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-08-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-08-20_f63ad1a379_NS Data 2025-08-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-08-20 | 2025-08-20_f63ad1a:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-08-27 | 2025-08-27_39f6dbb84c_NS Data 2025-08-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-08-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-08-27_39f6dbb84c_NS Data 2025-08-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-08-27 | 2025-08-27_39f6dbb:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-07-02 | 2025-07-02_d975746e89_NS Data 2025-07-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-07-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-07-02_d975746e89_NS Data 2025-07-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-07-02 | 2025-07-02_d975746:   0%|          | 0.00/31.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-07-09 | 2025-07-09_bf453f22f9_NS Data 2025-07-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-07-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-07-09_bf453f22f9_NS Data 2025-07-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-07-09 | 2025-07-09_bf453f2:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-07-16 | 2025-07-16_2d0b09bf17_NS Data 2025-07-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-07-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-07-16_2d0b09bf17_NS Data 2025-07-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-07-16 | 2025-07-16_2d0b09b:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-07-23 | 2025-07-23_4a01b6426e_NS Data 2025-07-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-07-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-07-23_4a01b6426e_NS Data 2025-07-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-07-23 | 2025-07-23_4a01b64:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-07-30 | 2025-07-30_5d528b16ab_NS Data 2025-07-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-07-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-07-30_5d528b16ab_NS Data 2025-07-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-07-30 | 2025-07-30_5d528b1:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-06-04 | 2025-06-04_598afda8b8_NS Data 2025-06-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-06-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-06-04_598afda8b8_NS Data 2025-06-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-06-04 | 2025-06-04_598afda:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-06-11 | 2025-06-11_a1c19b2638_NS Data 2025-06-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-06-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-06-11_a1c19b2638_NS Data 2025-06-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-06-11 | 2025-06-11_a1c19b2:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-06-18 | 2025-06-18_6f70abe7f0_NS Data 2025-06-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-06-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-06-18_6f70abe7f0_NS Data 2025-06-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-06-18 | 2025-06-18_6f70abe:   0%|          | 0.00/31.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-06-25 | 2025-06-25_aeebf63799_NS Data 2025-06-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-06-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-06-25_aeebf63799_NS Data 2025-06-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-06-25 | 2025-06-25_aeebf63:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-05-07 | 2025-05-07_1a5f0feee0_NS Data 2025-05-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-05-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-05-07_1a5f0feee0_NS Data 2025-05-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-05-07 | 2025-05-07_1a5f0fe:   0%|          | 0.00/31.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-05-14 | 2025-05-14_0873773cc8_NS Data 2025-05-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-05-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-05-14_0873773cc8_NS Data 2025-05-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-05-14 | 2025-05-14_0873773:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-05-21 | 2025-05-21_3ceab17993_NS Data 2025-05-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-05-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-05-21_3ceab17993_NS Data 2025-05-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-05-21 | 2025-05-21_3ceab17:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-05-28 | 2025-05-28_75b844166e_NS Data 2025-05-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-05-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-05-28_75b844166e_NS Data 2025-05-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-05-28 | 2025-05-28_75b8441:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-04-02 | 2025-04-02_f645e8b4d6_NS Data 2025-04-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-04-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-04-02_f645e8b4d6_NS Data 2025-04-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-04-02 | 2025-04-02_f645e8b:   0%|          | 0.00/30.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-04-09 | 2025-04-09_d96da0a3a6_NS Data 2025-04-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-04-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-04-09_d96da0a3a6_NS Data 2025-04-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-04-09 | 2025-04-09_d96da0a:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-04-16 | 2025-04-16_9739f88566_NS Data 2025-04-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-04-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-04-16_9739f88566_NS Data 2025-04-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-04-16 | 2025-04-16_9739f88:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-04-23 | 2025-04-23_3123563f21_NS Data 2025-04-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-04-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-04-23_3123563f21_NS Data 2025-04-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-04-23 | 2025-04-23_3123563:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-04-30 | 2025-04-30_41fbdb4800_NS Data 2025-04-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-04-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-04-30_41fbdb4800_NS Data 2025-04-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-04-30 | 2025-04-30_41fbdb4:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-03-05 | 2025-03-05_fae0641592_NS Data 2025-03-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-03-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-03-05_fae0641592_NS Data 2025-03-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-03-05 | 2025-03-05_fae0641:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-03-12 | 2025-03-12_9963794c99_NS Data 2025-03-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-03-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-03-12_9963794c99_NS Data 2025-03-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-03-12 | 2025-03-12_9963794:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-03-19 | 2025-03-19_b9ab0c1d60_NS Data 2025-03-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-03-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-03-19_b9ab0c1d60_NS Data 2025-03-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-03-19 | 2025-03-19_b9ab0c1:   0%|          | 0.00/30.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-03-26 | 2025-03-26_4c6cca8650_NS Data 2025-03-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-03-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-03-26_4c6cca8650_NS Data 2025-03-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-03-26 | 2025-03-26_4c6cca8:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-02-05 | 2025-02-05_0b7d42a319_NS Data 2025-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-02-05_0b7d42a319_NS Data 2025-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-02-05 | 2025-02-05_0b7d42a:   0%|          | 0.00/30.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-02-12 | 2025-02-12_a9977f164d_NS Data 2025-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-02-12_a9977f164d_NS Data 2025-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-02-12 | 2025-02-12_a9977f1:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-02-19 | 2025-02-19_222f7ed1d6_NS Data 2025-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-02-19_222f7ed1d6_NS Data 2025-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-02-19 | 2025-02-19_222f7ed:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-02-26 | 2025-02-26_30de210bc4_NS Data 2025-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-02-26_30de210bc4_NS Data 2025-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-02-26 | 2025-02-26_30de210:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-01-01 | 2025-01-01_ccc6ca2d89_NS Data 2025-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-01-01_ccc6ca2d89_NS Data 2025-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-01-01 | 2025-01-01_ccc6ca2:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-01-08 | 2025-01-08_90d545db6e_NS Data 2025-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-01-08_90d545db6e_NS Data 2025-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-01-08 | 2025-01-08_90d545d:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-01-15 | 2025-01-15_c0fece0afe_NS Data 2025-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-01-15_c0fece0afe_NS Data 2025-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-01-15 | 2025-01-15_c0fece0:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-01-22 | 2025-01-22_b3847714ab_NS Data 2025-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-01-22_b3847714ab_NS Data 2025-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-01-22 | 2025-01-22_b384771:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2025-01-29 | 2025-01-29_f7fe201acd_NS Data 2025-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202025-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2025\xlsx\2025-01-29_f7fe201acd_NS Data 2025-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2025-01-29 | 2025-01-29_f7fe201:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-12-04 | 2024-12-04_ec4eb73427_NS Data 2024-12-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-12-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-12-04_ec4eb73427_NS Data 2024-12-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-12-04 | 2024-12-04_ec4eb73:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-12-11 | 2024-12-11_074daef987_NS Data 2024-12-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-12-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-12-11_074daef987_NS Data 2024-12-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-12-11 | 2024-12-11_074daef:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-12-18 | 2024-12-18_47a4beb4ce_NS Data 2024-12-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-12-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-12-18_47a4beb4ce_NS Data 2024-12-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-12-18 | 2024-12-18_47a4beb:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-12-25 | 2024-12-25_9461ca2952_NS Data 2024-12-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-12-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-12-25_9461ca2952_NS Data 2024-12-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-12-25 | 2024-12-25_9461ca2:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-11-06 | 2024-11-06_fe15934b26_NS Data 2024-11-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-11-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-11-06_fe15934b26_NS Data 2024-11-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-11-06 | 2024-11-06_fe15934:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-11-13 | 2024-11-13_a6e65742e6_NS Data 2024-11-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-11-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-11-13_a6e65742e6_NS Data 2024-11-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-11-13 | 2024-11-13_a6e6574:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-11-20 | 2024-11-20_0928aafcd7_NS Data 2024-11-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-11-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-11-20_0928aafcd7_NS Data 2024-11-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-11-20 | 2024-11-20_0928aaf:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-11-27 | 2024-11-27_6dfd6db3a7_NS Data 2024-11-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-11-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-11-27_6dfd6db3a7_NS Data 2024-11-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-11-27 | 2024-11-27_6dfd6db:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-10-02 | 2024-10-02_f1c38a2a23_NS Data 2024-10-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-10-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-10-02_f1c38a2a23_NS Data 2024-10-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-10-02 | 2024-10-02_f1c38a2:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-10-09 | 2024-10-09_80cf84cbdc_NS Data 2024-10-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-10-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-10-09_80cf84cbdc_NS Data 2024-10-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-10-09 | 2024-10-09_80cf84c:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-10-16 | 2024-10-16_c640ae38bd_NS Data 2024-10-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-10-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-10-16_c640ae38bd_NS Data 2024-10-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-10-16 | 2024-10-16_c640ae3:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-10-23 | 2024-10-23_0a33529bc9_NS Data 2024-10-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-10-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-10-23_0a33529bc9_NS Data 2024-10-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-10-23 | 2024-10-23_0a33529:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-10-30 | 2024-10-30_504483a97a_NS Data 2024-10-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-10-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-10-30_504483a97a_NS Data 2024-10-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-10-30 | 2024-10-30_504483a:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-09-04 | 2024-09-04_a01ff6c9db_NS Data 2024-09-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-09-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-09-04_a01ff6c9db_NS Data 2024-09-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-09-04 | 2024-09-04_a01ff6c:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-09-11 | 2024-09-11_8e6084de4e_NS Data 2024-09-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-09-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-09-11_8e6084de4e_NS Data 2024-09-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-09-11 | 2024-09-11_8e6084d:   0%|          | 0.00/29.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-09-18 | 2024-09-18_0baa759248_NS Data 2024-09-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-09-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-09-18_0baa759248_NS Data 2024-09-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-09-18 | 2024-09-18_0baa759:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-09-25 | 2024-09-25_5c6ea2341a_NS Data 2024-09-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-09-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-09-25_5c6ea2341a_NS Data 2024-09-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-09-25 | 2024-09-25_5c6ea23:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-08-07 | 2024-08-07_9f646fd503_NS Data 2024-08-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-08-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-08-07_9f646fd503_NS Data 2024-08-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-08-07 | 2024-08-07_9f646fd:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-08-14 | 2024-08-14_a05291bf10_NS Data 2024-08-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-08-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-08-14_a05291bf10_NS Data 2024-08-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-08-14 | 2024-08-14_a05291b:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-08-21 | 2024-08-21_989859ae2b_NS Data 2024-08-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-08-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-08-21_989859ae2b_NS Data 2024-08-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-08-21 | 2024-08-21_989859a:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-08-28 | 2024-08-28_0b7ac9ae65_NS Data 2024-08-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-08-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-08-28_0b7ac9ae65_NS Data 2024-08-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-08-28 | 2024-08-28_0b7ac9a:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-07-03 | 2024-07-03_e8e216dbfc_NS Data 2024-07-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-07-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-07-03_e8e216dbfc_NS Data 2024-07-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-07-03 | 2024-07-03_e8e216d:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-07-10 | 2024-07-10_b5344dbe93_NS Data 2024-07-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-07-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-07-10_b5344dbe93_NS Data 2024-07-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-07-10 | 2024-07-10_b5344db:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-07-17 | 2024-07-17_c5d12063a5_NS Data 2024-07-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-07-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-07-17_c5d12063a5_NS Data 2024-07-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-07-17 | 2024-07-17_c5d1206:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-07-24 | 2024-07-24_48786a697d_NS Data 2024-07-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-07-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-07-24_48786a697d_NS Data 2024-07-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-07-24 | 2024-07-24_48786a6:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-07-31 | 2024-07-31_0dc09b9747_NS Data 2024-07-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-07-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-07-31_0dc09b9747_NS Data 2024-07-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-07-31 | 2024-07-31_0dc09b9:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-06-05 | 2024-06-05_2557c8b9d8_NS Data 2024-06-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-06-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-06-05_2557c8b9d8_NS Data 2024-06-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-06-05 | 2024-06-05_2557c8b:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-06-12 | 2024-06-12_cf4a2d323d_NS Data 2024-06-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-06-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-06-12_cf4a2d323d_NS Data 2024-06-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-06-12 | 2024-06-12_cf4a2d3:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-06-19 | 2024-06-19_37f6808a31_NS Data 2024-06-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-06-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-06-19_37f6808a31_NS Data 2024-06-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-06-19 | 2024-06-19_37f6808:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-06-26 | 2024-06-26_ff449a31e8_NS Data 2024-06-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-06-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-06-26_ff449a31e8_NS Data 2024-06-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-06-26 | 2024-06-26_ff449a3:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-05-01 | 2024-05-01_937a5c9476_NS Data 2024-05-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-05-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-05-01_937a5c9476_NS Data 2024-05-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-05-01 | 2024-05-01_937a5c9:   0%|          | 0.00/31.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-05-08 | 2024-05-08_39a87c76b3_NS Data 2024-05-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-05-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-05-08_39a87c76b3_NS Data 2024-05-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-05-08 | 2024-05-08_39a87c7:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-05-15 | 2024-05-15_4fb65f2524_NS Data 2024-05-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-05-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-05-15_4fb65f2524_NS Data 2024-05-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-05-15 | 2024-05-15_4fb65f2:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-05-22 | 2024-05-22_4eeae52ae1_NS Data 2024-05-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-05-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-05-22_4eeae52ae1_NS Data 2024-05-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-05-22 | 2024-05-22_4eeae52:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-05-29 | 2024-05-29_13934b23df_NS Data 2024-05-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-05-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-05-29_13934b23df_NS Data 2024-05-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-05-29 | 2024-05-29_13934b2:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-04-03 | 2024-04-03_d07d219cdc_NS Data 2024-04-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-04-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-04-03_d07d219cdc_NS Data 2024-04-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-04-03 | 2024-04-03_d07d219:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-04-10 | 2024-04-10_435d838ebf_NS Data 2024-04-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-04-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-04-10_435d838ebf_NS Data 2024-04-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-04-10 | 2024-04-10_435d838:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-04-17 | 2024-04-17_b8248eb90b_NS Data 2024-04-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-04-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-04-17_b8248eb90b_NS Data 2024-04-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-04-17 | 2024-04-17_b8248eb:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-04-24 | 2024-04-24_ce24aaa334_NS Data 2024-04-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-04-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-04-24_ce24aaa334_NS Data 2024-04-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-04-24 | 2024-04-24_ce24aaa:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-03-06 | 2024-03-06_cc4bb38470_NS Data 2024-03-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-03-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-03-06_cc4bb38470_NS Data 2024-03-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-03-06 | 2024-03-06_cc4bb38:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-03-13 | 2024-03-13_80c3c15d6e_NS Data 2024-03-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-03-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-03-13_80c3c15d6e_NS Data 2024-03-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-03-13 | 2024-03-13_80c3c15:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-03-20 | 2024-03-20_041b22633e_NS Data 2024-03-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-03-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-03-20_041b22633e_NS Data 2024-03-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-03-20 | 2024-03-20_041b226:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-03-27 | 2024-03-27_d59e16c057_NS Data 2024-03-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-03-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-03-27_d59e16c057_NS Data 2024-03-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-03-27 | 2024-03-27_d59e16c:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-02-07 | 2024-02-07_244b33c5c5_NS Data 2024-02-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-02-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-02-07_244b33c5c5_NS Data 2024-02-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-02-07 | 2024-02-07_244b33c:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-02-14 | 2024-02-14_45c612424f_NS Data 2024-02-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-02-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-02-14_45c612424f_NS Data 2024-02-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-02-14 | 2024-02-14_45c6124:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-02-21 | 2024-02-21_e899be929f_NS Data 2024-02-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-02-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-02-21_e899be929f_NS Data 2024-02-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-02-21 | 2024-02-21_e899be9:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-02-28 | 2024-02-28_fc693d442c_NS Data 2024-02-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-02-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-02-28_fc693d442c_NS Data 2024-02-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-02-28 | 2024-02-28_fc693d4:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-01-03 | 2024-01-03_1092c755a6_NS Data 2024-01-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-01-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-01-03_1092c755a6_NS Data 2024-01-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-01-03 | 2024-01-03_1092c75:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-01-10 | 2024-01-10_dedeb33f7c_NS Data 2024-01-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-01-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-01-10_dedeb33f7c_NS Data 2024-01-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-01-10 | 2024-01-10_dedeb33:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-01-17 | 2024-01-17_36738cce9d_NS Data 2024-01-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-01-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-01-17_36738cce9d_NS Data 2024-01-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-01-17 | 2024-01-17_36738cc:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-01-24 | 2024-01-24_2a18fe02f2_NS Data 2024-01-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-01-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-01-24_2a18fe02f2_NS Data 2024-01-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-01-24 | 2024-01-24_2a18fe0:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2024-01-31 | 2024-01-31_d23bcfa5b1_NS Data 2024-01-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202024-01-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2024\xlsx\2024-01-31_d23bcfa5b1_NS Data 2024-01-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2024-01-31 | 2024-01-31_d23bcfa:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-12-06 | 2023-12-06_e03e1d8ba0_NS Data 2023-12-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-12-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-12-06_e03e1d8ba0_NS Data 2023-12-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-12-06 | 2023-12-06_e03e1d8:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-12-13 | 2023-12-13_29323464e9_NS Data 2023-12-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-12-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-12-13_29323464e9_NS Data 2023-12-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-12-13 | 2023-12-13_2932346:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-12-20 | 2023-12-20_0ac9356db9_NS Data 2023-12-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-12-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-12-20_0ac9356db9_NS Data 2023-12-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-12-20 | 2023-12-20_0ac9356:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-12-27 | 2023-12-27_9ec4d0b5cc_NS Data 2023-12-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-12-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-12-27_9ec4d0b5cc_NS Data 2023-12-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-12-27 | 2023-12-27_9ec4d0b:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-11-01 | 2023-11-01_abfdfdbdfa_NS Data 2023-11-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-11-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-11-01_abfdfdbdfa_NS Data 2023-11-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-11-01 | 2023-11-01_abfdfdb:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-11-08 | 2023-11-08_d4221f5002_NS Data 2023-11-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-11-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-11-08_d4221f5002_NS Data 2023-11-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-11-08 | 2023-11-08_d4221f5:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-11-15 | 2023-11-15_457bf43417_NS Data 2023-11-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-11-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-11-15_457bf43417_NS Data 2023-11-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-11-15 | 2023-11-15_457bf43:   0%|          | 0.00/32.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-11-22 | 2023-11-22_2fe84e5a60_NS Data 2023-11-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-11-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-11-22_2fe84e5a60_NS Data 2023-11-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-11-22 | 2023-11-22_2fe84e5:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-11-29 | 2023-11-29_62473ed44c_NS Data 2023-11-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-11-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-11-29_62473ed44c_NS Data 2023-11-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-11-29 | 2023-11-29_62473ed:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-10-04 | 2023-10-04_5f53787c91_NS Data 2023-10-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-10-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-10-04_5f53787c91_NS Data 2023-10-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-10-04 | 2023-10-04_5f53787:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-10-11 | 2023-10-11_05246efb37_NS Data 2023-10-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-10-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-10-11_05246efb37_NS Data 2023-10-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-10-11 | 2023-10-11_05246ef:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-10-18 | 2023-10-18_600b0666ba_NS Data 2023-10-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-10-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-10-18_600b0666ba_NS Data 2023-10-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-10-18 | 2023-10-18_600b066:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-10-25 | 2023-10-25_69cbcb16b2_NS Data 2023-10-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-10-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-10-25_69cbcb16b2_NS Data 2023-10-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-10-25 | 2023-10-25_69cbcb1:   0%|          | 0.00/32.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-09-06 | 2023-09-06_0313312ee5_NS Data 2023-09-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-09-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-09-06_0313312ee5_NS Data 2023-09-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-09-06 | 2023-09-06_0313312:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-09-13 | 2023-09-13_7d9950f5ba_NS Data 2023-09-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-09-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-09-13_7d9950f5ba_NS Data 2023-09-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-09-13 | 2023-09-13_7d9950f:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-09-20 | 2023-09-20_feff5c4a72_NS Data 2023-09-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-09-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-09-20_feff5c4a72_NS Data 2023-09-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-09-20 | 2023-09-20_feff5c4:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-09-27 | 2023-09-27_d75c668860_NS Data 2023-09-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-09-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-09-27_d75c668860_NS Data 2023-09-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-09-27 | 2023-09-27_d75c668:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-08-02 | 2023-08-02_a9a91fe9d4_NS Data 2023-08-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-08-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-08-02_a9a91fe9d4_NS Data 2023-08-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-08-02 | 2023-08-02_a9a91fe:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-08-09 | 2023-08-09_eecd87f6ca_NS Data 2023-08-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-08-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-08-09_eecd87f6ca_NS Data 2023-08-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-08-09 | 2023-08-09_eecd87f:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-08-16 | 2023-08-16_1aaab2f9aa_NS Data 2023-08-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-08-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-08-16_1aaab2f9aa_NS Data 2023-08-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-08-16 | 2023-08-16_1aaab2f:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-08-23 | 2023-08-23_e5286e04dd_NS Data 2023-08-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-08-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-08-23_e5286e04dd_NS Data 2023-08-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-08-23 | 2023-08-23_e5286e0:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-08-30 | 2023-08-30_a5ea8fc4a2_NS Data 2023-08-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-08-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-08-30_a5ea8fc4a2_NS Data 2023-08-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-08-30 | 2023-08-30_a5ea8fc:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-07-05 | 2023-07-05_71c019d4ed_NS Data 2023-07-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-07-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-07-05_71c019d4ed_NS Data 2023-07-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-07-05 | 2023-07-05_71c019d:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-07-12 | 2023-07-12_e787c619fe_NS Data 2023-07-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-07-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-07-12_e787c619fe_NS Data 2023-07-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-07-12 | 2023-07-12_e787c61:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-07-19 | 2023-07-19_e10b8a53aa_NS Data 2023-07-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-07-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-07-19_e10b8a53aa_NS Data 2023-07-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-07-19 | 2023-07-19_e10b8a5:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-07-26 | 2023-07-26_4ef35f9014_NS Data 2023-07-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-07-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-07-26_4ef35f9014_NS Data 2023-07-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-07-26 | 2023-07-26_4ef35f9:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-06-07 | 2023-06-07_56fa94330c_NS Data 2023-06-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-06-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-06-07_56fa94330c_NS Data 2023-06-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-06-07 | 2023-06-07_56fa943:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-06-14 | 2023-06-14_de8ecd8958_NS Data 2023-06-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-06-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-06-14_de8ecd8958_NS Data 2023-06-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-06-14 | 2023-06-14_de8ecd8:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-06-21 | 2023-06-21_3993ffa62d_NS Data 2023-06-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-06-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-06-21_3993ffa62d_NS Data 2023-06-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-06-21 | 2023-06-21_3993ffa:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-06-28 | 2023-06-28_1c51342bb6_NS Data 2023-06-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-06-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-06-28_1c51342bb6_NS Data 2023-06-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-06-28 | 2023-06-28_1c51342:   0%|          | 0.00/32.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-05-03 | 2023-05-03_1b0cc87f28_NS Data 2023-05-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-05-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-05-03_1b0cc87f28_NS Data 2023-05-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-05-03 | 2023-05-03_1b0cc87:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-05-10 | 2023-05-10_d5b4901747_NS Data 2023-05-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-05-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-05-10_d5b4901747_NS Data 2023-05-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-05-10 | 2023-05-10_d5b4901:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-05-17 | 2023-05-17_2cdf9e9fbe_NS Data 2023-05-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-05-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-05-17_2cdf9e9fbe_NS Data 2023-05-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-05-17 | 2023-05-17_2cdf9e9:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-05-24 | 2023-05-24_f55aefa216_NS Data 2023-05-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-05-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-05-24_f55aefa216_NS Data 2023-05-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-05-24 | 2023-05-24_f55aefa:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-05-31 | 2023-05-31_26a366edef_NS Data 2023-05-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-05-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-05-31_26a366edef_NS Data 2023-05-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-05-31 | 2023-05-31_26a366e:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-04-05 | 2023-04-05_d44a548d37_NS Data 2023-04-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-04-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-04-05_d44a548d37_NS Data 2023-04-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-04-05 | 2023-04-05_d44a548:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-04-12 | 2023-04-12_a6b5db29cb_NS Data 2023-04-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-04-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-04-12_a6b5db29cb_NS Data 2023-04-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-04-12 | 2023-04-12_a6b5db2:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-04-19 | 2023-04-19_c7636bcd67_NS Data 2023-04-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-04-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-04-19_c7636bcd67_NS Data 2023-04-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-04-19 | 2023-04-19_c7636bc:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-04-26 | 2023-04-26_a152bbc57d_NS Data 2023-04-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-04-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-04-26_a152bbc57d_NS Data 2023-04-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-04-26 | 2023-04-26_a152bbc:   0%|          | 0.00/32.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-03-01 | 2023-03-01_84ac6d9a2e_NS Data 2023-03-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-03-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-03-01_84ac6d9a2e_NS Data 2023-03-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-03-01 | 2023-03-01_84ac6d9:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-03-08 | 2023-03-08_2f7549b833_NS Data 2023-03-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-03-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-03-08_2f7549b833_NS Data 2023-03-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-03-08 | 2023-03-08_2f7549b:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-03-15 | 2023-03-15_b0fc3cf64d_NS Data 2023-03-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-03-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-03-15_b0fc3cf64d_NS Data 2023-03-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-03-15 | 2023-03-15_b0fc3cf:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-03-22 | 2023-03-22_c443cd70cd_NS Data 2023-03-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-03-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-03-22_c443cd70cd_NS Data 2023-03-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-03-22 | 2023-03-22_c443cd7:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-03-29 | 2023-03-29_d7cfdc343b_NS Data 2023-03-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-03-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-03-29_d7cfdc343b_NS Data 2023-03-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-03-29 | 2023-03-29_d7cfdc3:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-02-01 | 2023-02-01_c06cf9c762_NS Data 2023-02-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-02-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-02-01_c06cf9c762_NS Data 2023-02-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-02-01 | 2023-02-01_c06cf9c:   0%|          | 0.00/32.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-02-08 | 2023-02-08_759d8fdc8c_NS Data 2023-02-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-02-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-02-08_759d8fdc8c_NS Data 2023-02-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-02-08 | 2023-02-08_759d8fd:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-02-15 | 2023-02-15_176e39331a_NS Data 2023-02-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-02-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-02-15_176e39331a_NS Data 2023-02-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-02-15 | 2023-02-15_176e393:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-02-22 | 2023-02-22_1c2033636f_NS Data 2023-02-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-02-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-02-22_1c2033636f_NS Data 2023-02-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-02-22 | 2023-02-22_1c20336:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-01-04 | 2023-01-04_a6fc88d6c8_NS Data 2023-01-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-01-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-01-04_a6fc88d6c8_NS Data 2023-01-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-01-04 | 2023-01-04_a6fc88d:   0%|          | 0.00/32.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-01-11 | 2023-01-11_2274ccb46f_NS Data 2023-01-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-01-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-01-11_2274ccb46f_NS Data 2023-01-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-01-11 | 2023-01-11_2274ccb:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-01-18 | 2023-01-18_10aef48583_NS Data 2023-01-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-01-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-01-18_10aef48583_NS Data 2023-01-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-01-18 | 2023-01-18_10aef48:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2023-01-25 | 2023-01-25_f4d07bf22e_NS Data 2023-01-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202023-01-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2023\xlsx\2023-01-25_f4d07bf22e_NS Data 2023-01-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2023-01-25 | 2023-01-25_f4d07bf:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-12-07 | 2022-12-07_29584ae21d_NS Data 2022-12-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-12-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-12-07_29584ae21d_NS Data 2022-12-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-12-07 | 2022-12-07_29584ae:   0%|          | 0.00/32.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-12-14 | 2022-12-14_7f704420a8_NS Data 2022-12-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-12-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-12-14_7f704420a8_NS Data 2022-12-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-12-14 | 2022-12-14_7f70442:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-12-21 | 2022-12-21_65788188c5_NS Data 2022-12-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-12-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-12-21_65788188c5_NS Data 2022-12-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-12-21 | 2022-12-21_6578818:   0%|          | 0.00/32.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-12-28 | 2022-12-28_5b688805eb_NS Data 2022-12-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-12-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-12-28_5b688805eb_NS Data 2022-12-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-12-28 | 2022-12-28_5b68880:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-11-02 | 2022-11-02_fdf37b1e0f_NS Data 2022-11-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-11-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-11-02_fdf37b1e0f_NS Data 2022-11-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-11-02 | 2022-11-02_fdf37b1:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-11-09 | 2022-11-09_87b4db6d97_NS Data 2022-11-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-11-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-11-09_87b4db6d97_NS Data 2022-11-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-11-09 | 2022-11-09_87b4db6:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-11-16 | 2022-11-16_de65a11f76_NS Data 2022-11-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-11-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-11-16_de65a11f76_NS Data 2022-11-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-11-16 | 2022-11-16_de65a11:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-11-23 | 2022-11-23_49bdeaa700_NS Data 2022-11-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-11-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-11-23_49bdeaa700_NS Data 2022-11-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-11-23 | 2022-11-23_49bdeaa:   0%|          | 0.00/32.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-11-30 | 2022-11-30_d365a8c365_NS Data 2022-11-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-11-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-11-30_d365a8c365_NS Data 2022-11-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-11-30 | 2022-11-30_d365a8c:   0%|          | 0.00/31.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-10-05 | 2022-10-05_69b9620e56_NS Data 2022-10-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-10-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-10-05_69b9620e56_NS Data 2022-10-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-10-05 | 2022-10-05_69b9620:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-10-12 | 2022-10-12_204b2b9956_NS Data 2022-10-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-10-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-10-12_204b2b9956_NS Data 2022-10-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-10-12 | 2022-10-12_204b2b9:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-10-19 | 2022-10-19_62120d0fd3_NS Data 2022-10-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-10-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-10-19_62120d0fd3_NS Data 2022-10-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-10-19 | 2022-10-19_62120d0:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-10-26 | 2022-10-26_e10a0ec71d_NS Data 2022-10-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-10-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-10-26_e10a0ec71d_NS Data 2022-10-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-10-26 | 2022-10-26_e10a0ec:   0%|          | 0.00/32.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-09-07 | 2022-09-07_713b728822_NS Data 2022-09-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-09-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-09-07_713b728822_NS Data 2022-09-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-09-07 | 2022-09-07_713b728:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-09-14 | 2022-09-14_1a59c0a073_NS Data 2022-09-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-09-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-09-14_1a59c0a073_NS Data 2022-09-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-09-14 | 2022-09-14_1a59c0a:   0%|          | 0.00/32.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-09-21 | 2022-09-21_939d7e022c_NS Data 2022-09-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-09-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-09-21_939d7e022c_NS Data 2022-09-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-09-21 | 2022-09-21_939d7e0:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-09-28 | 2022-09-28_6e7de9569c_NS Data 2022-09-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-09-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-09-28_6e7de9569c_NS Data 2022-09-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-09-28 | 2022-09-28_6e7de95:   0%|          | 0.00/32.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-08-03 | 2022-08-03_40035a9cff_NS Data 2022-08-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-08-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-08-03_40035a9cff_NS Data 2022-08-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-08-03 | 2022-08-03_40035a9:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-08-10 | 2022-08-10_a8541addca_NS Data 2022-08-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-08-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-08-10_a8541addca_NS Data 2022-08-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-08-10 | 2022-08-10_a8541ad:   0%|          | 0.00/30.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-08-17 | 2022-08-17_4ec921abe8_NS Data 2022-08-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-08-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-08-17_4ec921abe8_NS Data 2022-08-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-08-17 | 2022-08-17_4ec921a:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-08-24 | 2022-08-24_fcdd518110_NS Data 2022-08-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-08-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-08-24_fcdd518110_NS Data 2022-08-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-08-24 | 2022-08-24_fcdd518:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-08-31 | 2022-08-31_533bf3f204_NS Data 2022-08-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-08-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-08-31_533bf3f204_NS Data 2022-08-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-08-31 | 2022-08-31_533bf3f:   0%|          | 0.00/32.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-07-06 | 2022-07-06_1a2fff68b7_NS Data 2022-07-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-07-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-07-06_1a2fff68b7_NS Data 2022-07-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-07-06 | 2022-07-06_1a2fff6:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-07-13 | 2022-07-13_5112903f19_NS Data 2022-07-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-07-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-07-13_5112903f19_NS Data 2022-07-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-07-13 | 2022-07-13_5112903:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-07-20 | 2022-07-20_6b08c4ed82_NS Data 2022-07-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-07-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-07-20_6b08c4ed82_NS Data 2022-07-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-07-20 | 2022-07-20_6b08c4e:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-07-27 | 2022-07-27_cd4d687915_NS Data 2022-07-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-07-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-07-27_cd4d687915_NS Data 2022-07-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-07-27 | 2022-07-27_cd4d687:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-06-01 | 2022-06-01_763a07fcc8_NS Data 2022-06-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-06-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-06-01_763a07fcc8_NS Data 2022-06-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-06-01 | 2022-06-01_763a07f:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-06-08 | 2022-06-08_2fee12999a_NS Data 2022-06-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-06-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-06-08_2fee12999a_NS Data 2022-06-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-06-08 | 2022-06-08_2fee129:   0%|          | 0.00/31.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-06-15 | 2022-06-15_bd81b17011_NS Data 2022-06-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-06-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-06-15_bd81b17011_NS Data 2022-06-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-06-15 | 2022-06-15_bd81b17:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-06-22 | 2022-06-22_e0a46915ae_NS Data 2022-06-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-06-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-06-22_e0a46915ae_NS Data 2022-06-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-06-22 | 2022-06-22_e0a4691:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-06-29 | 2022-06-29_09a46bb956_NS Data 2022-06-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-06-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-06-29_09a46bb956_NS Data 2022-06-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-06-29 | 2022-06-29_09a46bb:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-05-04 | 2022-05-04_9ec4a2cdb8_NS Data 2022-05-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-05-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-05-04_9ec4a2cdb8_NS Data 2022-05-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-05-04 | 2022-05-04_9ec4a2c:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-05-11 | 2022-05-11_3cefa23210_NS Data 2022-05-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-05-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-05-11_3cefa23210_NS Data 2022-05-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-05-11 | 2022-05-11_3cefa23:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-05-18 | 2022-05-18_1bceadaa76_NS Data 2022-05-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-05-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-05-18_1bceadaa76_NS Data 2022-05-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-05-18 | 2022-05-18_1bceada:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-05-25 | 2022-05-25_2a10f0939f_NS Data 2022-05-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-05-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-05-25_2a10f0939f_NS Data 2022-05-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-05-25 | 2022-05-25_2a10f09:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-04-06 | 2022-04-06_8ad44d31dc_NS Data 2022-04-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-04-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-04-06_8ad44d31dc_NS Data 2022-04-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-04-06 | 2022-04-06_8ad44d3:   0%|          | 0.00/30.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-04-13 | 2022-04-13_3d89ba4d22_NS Data 2022-04-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-04-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-04-13_3d89ba4d22_NS Data 2022-04-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-04-13 | 2022-04-13_3d89ba4:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-04-20 | 2022-04-20_8e0b5c2f6d_NS Data 2022-04-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-04-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-04-20_8e0b5c2f6d_NS Data 2022-04-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-04-20 | 2022-04-20_8e0b5c2:   0%|          | 0.00/30.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-04-27 | 2022-04-27_cc87260705_NS Data 2022-04-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-04-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-04-27_cc87260705_NS Data 2022-04-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-04-27 | 2022-04-27_cc87260:   0%|          | 0.00/31.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-03-02 | 2022-03-02_91ffa642a7_NS Data 2022-03-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-03-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-03-02_91ffa642a7_NS Data 2022-03-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-03-02 | 2022-03-02_91ffa64:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-03-09 | 2022-03-09_4ead458eac_NS Data 2022-03-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-03-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-03-09_4ead458eac_NS Data 2022-03-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-03-09 | 2022-03-09_4ead458:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-03-16 | 2022-03-16_b617c19126_NS Data 2022-03-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-03-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-03-16_b617c19126_NS Data 2022-03-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-03-16 | 2022-03-16_b617c19:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-03-23 | 2022-03-23_8db04d97e4_NS Data 2022-03-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-03-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-03-23_8db04d97e4_NS Data 2022-03-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-03-23 | 2022-03-23_8db04d9:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-03-30 | 2022-03-30_3b7a7f35b7_NS Data 2022-03-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-03-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-03-30_3b7a7f35b7_NS Data 2022-03-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-03-30 | 2022-03-30_3b7a7f3:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-02-02 | 2022-02-02_5ac8cca3e5_NS Data 2022-02-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-02-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-02-02_5ac8cca3e5_NS Data 2022-02-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-02-02 | 2022-02-02_5ac8cca:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-02-09 | 2022-02-09_6a7eb84e9b_NS Data 2022-02-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-02-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-02-09_6a7eb84e9b_NS Data 2022-02-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-02-09 | 2022-02-09_6a7eb84:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-02-16 | 2022-02-16_76a1ea4c23_NS Data 2022-02-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-02-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-02-16_76a1ea4c23_NS Data 2022-02-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-02-16 | 2022-02-16_76a1ea4:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-02-23 | 2022-02-23_0f914b5cee_NS Data 2022-02-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-02-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-02-23_0f914b5cee_NS Data 2022-02-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-02-23 | 2022-02-23_0f914b5:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-01-05 | 2022-01-05_d674cf69df_NS Data 2022-01-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-01-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-01-05_d674cf69df_NS Data 2022-01-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-01-05 | 2022-01-05_d674cf6:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-01-12 | 2022-01-12_17754c4eb7_NS Data 2022-01-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-01-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-01-12_17754c4eb7_NS Data 2022-01-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-01-12 | 2022-01-12_17754c4:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-01-19 | 2022-01-19_02f5c7483a_NS Data 2022-01-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-01-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-01-19_02f5c7483a_NS Data 2022-01-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-01-19 | 2022-01-19_02f5c74:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2022-01-26 | 2022-01-26_4eaeb388e8_NS Data 2022-01-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202022-01-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2022\xlsx\2022-01-26_4eaeb388e8_NS Data 2022-01-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2022-01-26 | 2022-01-26_4eaeb38:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-12-01 | 2021-12-01_9e5737f7ad_NS Data 2021-12-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-12-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-12-01_9e5737f7ad_NS Data 2021-12-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-12-01 | 2021-12-01_9e5737f:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-12-08 | 2021-12-08_42a9428e29_NS Data 2021-12-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-12-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-12-08_42a9428e29_NS Data 2021-12-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-12-08 | 2021-12-08_42a9428:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-12-15 | 2021-12-15_82cb461e51_NS Data 2021-12-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-12-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-12-15_82cb461e51_NS Data 2021-12-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-12-15 | 2021-12-15_82cb461:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-12-22 | 2021-12-22_df20c89269_NS Data 2021-12-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-12-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-12-22_df20c89269_NS Data 2021-12-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-12-22 | 2021-12-22_df20c89:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-12-29 | 2021-12-29_df80d9b2c2_NS Data 2021-12-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-12-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-12-29_df80d9b2c2_NS Data 2021-12-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-12-29 | 2021-12-29_df80d9b:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-11-03 | 2021-11-03_e39294d7f9_NS Data 2021-11-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-11-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-11-03_e39294d7f9_NS Data 2021-11-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-11-03 | 2021-11-03_e39294d:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-11-10 | 2021-11-10_5391d7a297_NS Data 2021-11-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-11-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-11-10_5391d7a297_NS Data 2021-11-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-11-10 | 2021-11-10_5391d7a:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-11-17 | 2021-11-17_678ed73a66_NS Data 2021-11-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-11-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-11-17_678ed73a66_NS Data 2021-11-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-11-17 | 2021-11-17_678ed73:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-11-24 | 2021-11-24_b87d289d60_NS Data 2021-11-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-11-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-11-24_b87d289d60_NS Data 2021-11-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-11-24 | 2021-11-24_b87d289:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-10-06 | 2021-10-06_d99be3f790_NS Data 2021-10-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-10-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-10-06_d99be3f790_NS Data 2021-10-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-10-06 | 2021-10-06_d99be3f:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-10-13 | 2021-10-13_51b497aab0_NS Data 2021-10-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-10-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-10-13_51b497aab0_NS Data 2021-10-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-10-13 | 2021-10-13_51b497a:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-10-20 | 2021-10-20_75f4fbdf9f_NS Data 2021-10-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-10-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-10-20_75f4fbdf9f_NS Data 2021-10-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-10-20 | 2021-10-20_75f4fbd:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-10-27 | 2021-10-27_676aa78ddf_NS Data 2021-10-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-10-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-10-27_676aa78ddf_NS Data 2021-10-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-10-27 | 2021-10-27_676aa78:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-09-01 | 2021-09-01_61064249c8_NS Data 2021-09-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-09-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-09-01_61064249c8_NS Data 2021-09-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-09-01 | 2021-09-01_6106424:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-09-08 | 2021-09-08_a0897462dd_NS Data 2021-09-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-09-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-09-08_a0897462dd_NS Data 2021-09-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-09-08 | 2021-09-08_a089746:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-09-15 | 2021-09-15_51bea7ff0f_NS Data 2021-09-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-09-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-09-15_51bea7ff0f_NS Data 2021-09-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-09-15 | 2021-09-15_51bea7f:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-09-22 | 2021-09-22_8113686cbd_NS Data 2021-09-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-09-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-09-22_8113686cbd_NS Data 2021-09-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-09-22 | 2021-09-22_8113686:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-09-29 | 2021-09-29_dbf5e6055a_NS Data 2021-09-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-09-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-09-29_dbf5e6055a_NS Data 2021-09-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-09-29 | 2021-09-29_dbf5e60:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-08-04 | 2021-08-04_7a2b7bc01f_NS Data 2021-08-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-08-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-08-04_7a2b7bc01f_NS Data 2021-08-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-08-04 | 2021-08-04_7a2b7bc:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-08-11 | 2021-08-11_bd263f7af9_NS Data 2021-08-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-08-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-08-11_bd263f7af9_NS Data 2021-08-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-08-11 | 2021-08-11_bd263f7:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-08-18 | 2021-08-18_9c9f36710c_NS Data 2021-08-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-08-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-08-18_9c9f36710c_NS Data 2021-08-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-08-18 | 2021-08-18_9c9f367:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-08-25 | 2021-08-25_488de8b242_NS Data 2021-08-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-08-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-08-25_488de8b242_NS Data 2021-08-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-08-25 | 2021-08-25_488de8b:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-07-07 | 2021-07-07_e33522b0d5_NS Data 2021-07-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-07-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-07-07_e33522b0d5_NS Data 2021-07-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-07-07 | 2021-07-07_e33522b:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-07-14 | 2021-07-14_06e25c13e8_NS Data 2021-07-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-07-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-07-14_06e25c13e8_NS Data 2021-07-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-07-14 | 2021-07-14_06e25c1:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-07-21 | 2021-07-21_baf9d825a7_NS Data 2021-07-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-07-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-07-21_baf9d825a7_NS Data 2021-07-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-07-21 | 2021-07-21_baf9d82:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-07-28 | 2021-07-28_2043d54d61_NS Data 2021-07-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-07-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-07-28_2043d54d61_NS Data 2021-07-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-07-28 | 2021-07-28_2043d54:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-06-02 | 2021-06-02_46c0ff5c36_NS Data 2021-06-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-06-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-06-02_46c0ff5c36_NS Data 2021-06-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-06-02 | 2021-06-02_46c0ff5:   0%|          | 0.00/35.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-06-09 | 2021-06-09_36b5650133_NS Data 2021-06-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-06-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-06-09_36b5650133_NS Data 2021-06-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-06-09 | 2021-06-09_36b5650:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-06-16 | 2021-06-16_aa42e9cb37_NS Data 2021-06-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-06-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-06-16_aa42e9cb37_NS Data 2021-06-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-06-16 | 2021-06-16_aa42e9c:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-06-23 | 2021-06-23_2259d325ec_NS Data 2021-06-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-06-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-06-23_2259d325ec_NS Data 2021-06-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-06-23 | 2021-06-23_2259d32:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-06-30 | 2021-06-30_a6c70c3594_NS Data 2021-06-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-06-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-06-30_a6c70c3594_NS Data 2021-06-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-06-30 | 2021-06-30_a6c70c3:   0%|          | 0.00/23.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-05-05 | 2021-05-05_918c4ddfce_NS Data 2021-05-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-05-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-05-05_918c4ddfce_NS Data 2021-05-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-05-05 | 2021-05-05_918c4dd:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-05-12 | 2021-05-12_fdaf847647_NS Data 2021-05-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-05-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-05-12_fdaf847647_NS Data 2021-05-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-05-12 | 2021-05-12_fdaf847:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-05-19 | 2021-05-19_a02bd90ad7_NS Data 2021-05-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-05-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-05-19_a02bd90ad7_NS Data 2021-05-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-05-19 | 2021-05-19_a02bd90:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-05-26 | 2021-05-26_35038452fa_NS Data 2021-05-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-05-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-05-26_35038452fa_NS Data 2021-05-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-05-26 | 2021-05-26_3503845:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-04-07 | 2021-04-07_1155b264a3_NS Data 2021-04-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-04-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-04-07_1155b264a3_NS Data 2021-04-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-04-07 | 2021-04-07_1155b26:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-04-14 | 2021-04-14_232dda9aeb_NS Data 2021-04-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-04-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-04-14_232dda9aeb_NS Data 2021-04-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-04-14 | 2021-04-14_232dda9:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-04-21 | 2021-04-21_9382a9144d_NS Data 2021-04-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-04-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-04-21_9382a9144d_NS Data 2021-04-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-04-21 | 2021-04-21_9382a91:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-04-28 | 2021-04-28_64529328e3_NS Data 2021-04-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-04-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-04-28_64529328e3_NS Data 2021-04-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-04-28 | 2021-04-28_6452932:   0%|          | 0.00/35.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-03-03 | 2021-03-03_465a2661f7_NS Data 2021-03-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-03-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-03-03_465a2661f7_NS Data 2021-03-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-03-03 | 2021-03-03_465a266:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-03-10 | 2021-03-10_95fabf6445_NS Data 2021-03-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-03-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-03-10_95fabf6445_NS Data 2021-03-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-03-10 | 2021-03-10_95fabf6:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-03-17 | 2021-03-17_bf5def7671_NS Data 2021-03-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-03-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-03-17_bf5def7671_NS Data 2021-03-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-03-17 | 2021-03-17_bf5def7:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-03-24 | 2021-03-24_1599bdf9ff_NS Data 2021-03-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-03-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-03-24_1599bdf9ff_NS Data 2021-03-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-03-24 | 2021-03-24_1599bdf:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-03-31 | 2021-03-31_61af3cdcbc_NS Data 2021-03-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-03-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-03-31_61af3cdcbc_NS Data 2021-03-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-03-31 | 2021-03-31_61af3cd:   0%|          | 0.00/35.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-02-03 | 2021-02-03_1335cbe66d_NS Data 2021-02-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-02-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-02-03_1335cbe66d_NS Data 2021-02-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-02-03 | 2021-02-03_1335cbe:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-02-10 | 2021-02-10_b43787316d_NS Data 2021-02-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-02-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-02-10_b43787316d_NS Data 2021-02-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-02-10 | 2021-02-10_b437873:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-02-17 | 2021-02-17_3121799bd3_NS Data 2021-02-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-02-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-02-17_3121799bd3_NS Data 2021-02-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-02-17 | 2021-02-17_3121799:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-02-24 | 2021-02-24_a0d2c1a830_NS Data 2021-02-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-02-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-02-24_a0d2c1a830_NS Data 2021-02-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-02-24 | 2021-02-24_a0d2c1a:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-01-06 | 2021-01-06_4434126101_NS Data 2021-01-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-01-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-01-06_4434126101_NS Data 2021-01-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-01-06 | 2021-01-06_4434126:   0%|          | 0.00/35.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-01-13 | 2021-01-13_aa12eccad4_NS Data 2021-01-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-01-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-01-13_aa12eccad4_NS Data 2021-01-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-01-13 | 2021-01-13_aa12ecc:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-01-20 | 2021-01-20_ae82331201_NS Data 2021-01-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-01-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-01-20_ae82331201_NS Data 2021-01-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-01-20 | 2021-01-20_ae82331:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2021-01-27 | 2021-01-27_2e09a85102_NS Data 2021-01-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202021-01-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2021\xlsx\2021-01-27_2e09a85102_NS Data 2021-01-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2021-01-27 | 2021-01-27_2e09a85:   0%|          | 0.00/35.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-12-02 | 2020-12-02_2b38dc5822_NS Data 2020-12-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-12-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-12-02_2b38dc5822_NS Data 2020-12-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-12-02 | 2020-12-02_2b38dc5:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-12-09 | 2020-12-09_c9b10149b9_NS Data 2020-12-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-12-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-12-09_c9b10149b9_NS Data 2020-12-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-12-09 | 2020-12-09_c9b1014:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-12-16 | 2020-12-16_e09150d151_NS Data 2020-12-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-12-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-12-16_e09150d151_NS Data 2020-12-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-12-16 | 2020-12-16_e09150d:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-12-23 | 2020-12-23_17da47e4e2_NS Data 2020-12-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-12-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-12-23_17da47e4e2_NS Data 2020-12-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-12-23 | 2020-12-23_17da47e:   0%|          | 0.00/35.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-12-30 | 2020-12-30_8d4426fd20_NS Data 2020-12-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-12-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-12-30_8d4426fd20_NS Data 2020-12-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-12-30 | 2020-12-30_8d4426f:   0%|          | 0.00/35.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-11-04 | 2020-11-04_c9aed8bfdb_NS Data 2020-11-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-11-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-11-04_c9aed8bfdb_NS Data 2020-11-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-11-04 | 2020-11-04_c9aed8b:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-11-11 | 2020-11-11_f493e7cf5a_NS Data 2020-11-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-11-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-11-11_f493e7cf5a_NS Data 2020-11-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-11-11 | 2020-11-11_f493e7c:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-11-18 | 2020-11-18_83080ce96b_NS Data 2020-11-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-11-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-11-18_83080ce96b_NS Data 2020-11-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-11-18 | 2020-11-18_83080ce:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-11-25 | 2020-11-25_7182f14fc8_NS Data 2020-11-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-11-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-11-25_7182f14fc8_NS Data 2020-11-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-11-25 | 2020-11-25_7182f14:   0%|          | 0.00/35.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-10-07 | 2020-10-07_e62802fea4_NS Data 2020-10-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-10-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-10-07_e62802fea4_NS Data 2020-10-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-10-07 | 2020-10-07_e62802f:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-10-14 | 2020-10-14_c91576bd72_NS Data 2020-10-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-10-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-10-14_c91576bd72_NS Data 2020-10-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-10-14 | 2020-10-14_c91576b:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-10-21 | 2020-10-21_73248eb4d0_NS Data 2020-10-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-10-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-10-21_73248eb4d0_NS Data 2020-10-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-10-21 | 2020-10-21_73248eb:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-10-28 | 2020-10-28_251866efd2_NS Data 2020-10-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-10-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-10-28_251866efd2_NS Data 2020-10-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-10-28 | 2020-10-28_251866e:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-09-02 | 2020-09-02_760c628dc0_NS Data 2020-09-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-09-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-09-02_760c628dc0_NS Data 2020-09-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-09-02 | 2020-09-02_760c628:   0%|          | 0.00/34.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-09-09 | 2020-09-09_db025f8626_NS Data 2020-09-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-09-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-09-09_db025f8626_NS Data 2020-09-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-09-09 | 2020-09-09_db025f8:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-09-16 | 2020-09-16_1cc0248bcc_NS Data 2020-09-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-09-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-09-16_1cc0248bcc_NS Data 2020-09-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-09-16 | 2020-09-16_1cc0248:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-09-23 | 2020-09-23_01c7d7c30a_NS Data 2020-09-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-09-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-09-23_01c7d7c30a_NS Data 2020-09-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-09-23 | 2020-09-23_01c7d7c:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-09-30 | 2020-09-30_af8548a957_NS Data 2020-09-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-09-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-09-30_af8548a957_NS Data 2020-09-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-09-30 | 2020-09-30_af8548a:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-08-05 | 2020-08-05_af0494f971_NS Data 2020-08-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-08-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-08-05_af0494f971_NS Data 2020-08-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-08-05 | 2020-08-05_af0494f:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-08-12 | 2020-08-12_86ba5c2cb7_NS Data 2020-08-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-08-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-08-12_86ba5c2cb7_NS Data 2020-08-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-08-12 | 2020-08-12_86ba5c2:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-08-19 | 2020-08-19_68f1599d86_NS Data 2020-08-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-08-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-08-19_68f1599d86_NS Data 2020-08-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-08-19 | 2020-08-19_68f1599:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-08-26 | 2020-08-26_aad082b37f_NS Data 2020-08-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-08-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-08-26_aad082b37f_NS Data 2020-08-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-08-26 | 2020-08-26_aad082b:   0%|          | 0.00/34.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-07-01 | 2020-07-01_93bca92024_ns_data_2020-07-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-07-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-07-01_93bca92024_ns_data_2020-07-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-07-01 | 2020-07-01_93bca92:   0%|          | 0.00/37.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-07-08 | 2020-07-08_e93c6fecbe_ns_data_2020-07-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-07-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-07-08_e93c6fecbe_ns_data_2020-07-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-07-08 | 2020-07-08_e93c6fe:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-07-15 | 2020-07-15_6b1818937a_ns_data_2020-07-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-07-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-07-15_6b1818937a_ns_data_2020-07-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-07-15 | 2020-07-15_6b18189:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-07-22 | 2020-07-22_84df4b1198_ns_data_2020-07-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-07-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-07-22_84df4b1198_ns_data_2020-07-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-07-22 | 2020-07-22_84df4b1:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-07-29 | 2020-07-29_b91d9e991a_NS Data 2020-07-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/NS%20Data%202020-07-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-07-29_b91d9e991a_NS Data 2020-07-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-07-29 | 2020-07-29_b91d9e9:   0%|          | 0.00/36.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-06-03 | 2020-06-03_876b98a5e1_ns_data_2020-06-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-06-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-06-03_876b98a5e1_ns_data_2020-06-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-06-03 | 2020-06-03_876b98a:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-06-10 | 2020-06-10_a7d59f125d_ns_data_2020-06-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-06-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-06-10_a7d59f125d_ns_data_2020-06-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-06-10 | 2020-06-10_a7d59f1:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-06-17 | 2020-06-17_b550d57044_ns_data_2020-06-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-06-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-06-17_b550d57044_ns_data_2020-06-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-06-17 | 2020-06-17_b550d57:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-06-24 | 2020-06-24_b79b1920c5_ns_data_2020-06-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-06-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-06-24_b79b1920c5_ns_data_2020-06-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-06-24 | 2020-06-24_b79b192:   0%|          | 0.00/37.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-05-06 | 2020-05-06_ba6af75fb4_ns_data_2020-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-05-06_ba6af75fb4_ns_data_2020-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-05-06 | 2020-05-06_ba6af75:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-05-13 | 2020-05-13_46f74d3f9d_ns_data_2020-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-05-13_46f74d3f9d_ns_data_2020-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-05-13 | 2020-05-13_46f74d3:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-05-20 | 2020-05-20_6b980fd26b_ns_data_2020-05-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-05-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-05-20_6b980fd26b_ns_data_2020-05-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-05-20 | 2020-05-20_6b980fd:   0%|          | 0.00/37.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-05-27 | 2020-05-27_418cdd39a9_ns_data_2020-05-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-05-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-05-27_418cdd39a9_ns_data_2020-05-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-05-27 | 2020-05-27_418cdd3:   0%|          | 0.00/37.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-04-01 | 2020-04-01_83c209c622_ns_data_2020-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-04-01_83c209c622_ns_data_2020-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-04-01 | 2020-04-01_83c209c:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-04-08 | 2020-04-08_d8bb230459_ns_data_2020-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-04-08_d8bb230459_ns_data_2020-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-04-08 | 2020-04-08_d8bb230:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-04-15 | 2020-04-15_2a5f7fd96c_ns_data_2020-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-04-15_2a5f7fd96c_ns_data_2020-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-04-15 | 2020-04-15_2a5f7fd:   0%|          | 0.00/36.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-04-22 | 2020-04-22_6ef22301a1_ns_data_2020-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-04-22_6ef22301a1_ns_data_2020-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-04-22 | 2020-04-22_6ef2230:   0%|          | 0.00/37.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-04-29 | 2020-04-29_c049f1be89_ns_data_2020-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-04-29_c049f1be89_ns_data_2020-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-04-29 | 2020-04-29_c049f1b:   0%|          | 0.00/36.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-03-04 | 2020-03-04_5021e2b6b8_ns_data_2020-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-03-04_5021e2b6b8_ns_data_2020-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-03-04 | 2020-03-04_5021e2b:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-03-11 | 2020-03-11_8ef7276fa0_ns_data_2020-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-03-11_8ef7276fa0_ns_data_2020-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-03-11 | 2020-03-11_8ef7276:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-03-18 | 2020-03-18_5a97993297_ns_data_2020-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-03-18_5a97993297_ns_data_2020-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-03-18 | 2020-03-18_5a97993:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-03-25 | 2020-03-25_a558d14991_ns_data_2020-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-03-25_a558d14991_ns_data_2020-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-03-25 | 2020-03-25_a558d14:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-02-05 | 2020-02-05_b3d08325e7_ns_data_2020-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-02-05_b3d08325e7_ns_data_2020-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-02-05 | 2020-02-05_b3d0832:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-02-12 | 2020-02-12_3b9d91bcf9_ns_data_2020-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-02-12_3b9d91bcf9_ns_data_2020-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-02-12 | 2020-02-12_3b9d91b:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-02-19 | 2020-02-19_a4a2918bab_ns_data_2020-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-02-19_a4a2918bab_ns_data_2020-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-02-19 | 2020-02-19_a4a2918:   0%|          | 0.00/36.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-02-26 | 2020-02-26_6a1013026a_ns_data_2020-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-02-26_6a1013026a_ns_data_2020-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-02-26 | 2020-02-26_6a10130:   0%|          | 0.00/36.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-01-01 | 2020-01-01_297ddd1d42_ns_data_2020-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-01-01_297ddd1d42_ns_data_2020-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-01-01 | 2020-01-01_297ddd1:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-01-08 | 2020-01-08_3d6b409eed_ns_data_2020-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-01-08_3d6b409eed_ns_data_2020-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-01-08 | 2020-01-08_3d6b409:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-01-15 | 2020-01-15_485fd57ed0_ns_data_2020-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-01-15_485fd57ed0_ns_data_2020-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-01-15 | 2020-01-15_485fd57:   0%|          | 0.00/36.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-01-22 | 2020-01-22_7278b550e7_ns_data_2020-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-01-22_7278b550e7_ns_data_2020-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-01-22 | 2020-01-22_7278b55:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | ns | 2020-01-29 | 2020-01-29_758c5df562_ns_data_2020-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/NS/ns_data_2020-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\ns\2020\xlsx\2020-01-29_758c5df562_ns_data_2020-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | ns | 2020-01-29 | 2020-01-29_758c5df:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-05-06 | 2026-05-06_28d1700bce_UP Data 2026-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-05-06_28d1700bce_UP Data 2026-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-05-06 | 2026-05-06_28d1700:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-05-13 | 2026-05-13_4b183bbd6f_UP Data 2026-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-05-13_4b183bbd6f_UP Data 2026-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-05-13 | 2026-05-13_4b183bb:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-04-01 | 2026-04-01_5cea7118b7_UP Data 2026-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-04-01_5cea7118b7_UP Data 2026-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-04-01 | 2026-04-01_5cea711:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-04-08 | 2026-04-08_16ff2853a1_UP Data 2026-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-04-08_16ff2853a1_UP Data 2026-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-04-08 | 2026-04-08_16ff285:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-04-15 | 2026-04-15_8e0b8bdee5_UP Data 2026-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-04-15_8e0b8bdee5_UP Data 2026-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-04-15 | 2026-04-15_8e0b8bd:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-04-22 | 2026-04-22_91960b5922_UP Data 2026-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-04-22_91960b5922_UP Data 2026-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-04-22 | 2026-04-22_91960b5:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-04-29 | 2026-04-29_a8ca10b679_UP Data 2026-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-04-29_a8ca10b679_UP Data 2026-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-04-29 | 2026-04-29_a8ca10b:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-03-04 | 2026-03-04_9de73b7511_UP Data 2026-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-03-04_9de73b7511_UP Data 2026-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-03-04 | 2026-03-04_9de73b7:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-03-11 | 2026-03-11_4ab8407dd2_UP Data 2026-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-03-11_4ab8407dd2_UP Data 2026-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-03-11 | 2026-03-11_4ab8407:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-03-18 | 2026-03-18_913520409f_UP Data 2026-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-03-18_913520409f_UP Data 2026-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-03-18 | 2026-03-18_9135204:   0%|          | 0.00/40.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-03-25 | 2026-03-25_2d3b90e3af_UP Data 2026-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-03-25_2d3b90e3af_UP Data 2026-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-03-25 | 2026-03-25_2d3b90e:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-02-04 | 2026-02-04_d9b9d34672_UP Data 2026-02-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-02-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-02-04_d9b9d34672_UP Data 2026-02-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-02-04 | 2026-02-04_d9b9d34:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-02-11 | 2026-02-11_cde60656e1_UP Data 2026-02-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-02-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-02-11_cde60656e1_UP Data 2026-02-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-02-11 | 2026-02-11_cde6065:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-02-18 | 2026-02-18_bacfeea892_UP Data 2026-02-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-02-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-02-18_bacfeea892_UP Data 2026-02-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-02-18 | 2026-02-18_bacfeea:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-02-25 | 2026-02-25_3dd632473e_UP Data 2026-02-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-02-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-02-25_3dd632473e_UP Data 2026-02-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-02-25 | 2026-02-25_3dd6324:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-01-07 | 2026-01-07_a9108d8f84_UP Data 2026-01-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-01-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-01-07_a9108d8f84_UP Data 2026-01-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-01-07 | 2026-01-07_a9108d8:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-01-14 | 2026-01-14_86a5c5157e_UP Data 2026-01-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-01-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-01-14_86a5c5157e_UP Data 2026-01-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-01-14 | 2026-01-14_86a5c51:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-01-21 | 2026-01-21_6bb49d48a1_UP Data 2026-01-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-01-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-01-21_6bb49d48a1_UP Data 2026-01-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-01-21 | 2026-01-21_6bb49d4:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2026-01-28 | 2026-01-28_bef827b670_UP Data 2026-01-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202026-01-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2026\xlsx\2026-01-28_bef827b670_UP Data 2026-01-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2026-01-28 | 2026-01-28_bef827b:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-12-31 | 2025-12-31_70b5cec9c8_UP Data 2025-12-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-12-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-12-31_70b5cec9c8_UP Data 2025-12-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-12-31 | 2025-12-31_70b5cec:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-12-03 | 2025-12-03_88f905c0c6_UP Data 2025-12-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-12-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-12-03_88f905c0c6_UP Data 2025-12-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-12-03 | 2025-12-03_88f905c:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-12-10 | 2025-12-10_c0ad79d8e1_UP Data 2025-12-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-12-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-12-10_c0ad79d8e1_UP Data 2025-12-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-12-10 | 2025-12-10_c0ad79d:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-12-17 | 2025-12-17_18d1ec57dc_UP Data 2025-12-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-12-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-12-17_18d1ec57dc_UP Data 2025-12-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-12-17 | 2025-12-17_18d1ec5:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-12-24 | 2025-12-24_d4f3db5925_UP Data 2025-12-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-12-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-12-24_d4f3db5925_UP Data 2025-12-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-12-24 | 2025-12-24_d4f3db5:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-11-05 | 2025-11-05_40b6ccd8ec_UP Data 2025-11-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-11-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-11-05_40b6ccd8ec_UP Data 2025-11-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-11-05 | 2025-11-05_40b6ccd:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-11-12 | 2025-11-12_2f182b6d23_UP Data 2025-11-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-11-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-11-12_2f182b6d23_UP Data 2025-11-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-11-12 | 2025-11-12_2f182b6:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-11-19 | 2025-11-19_e4e0292ec9_UP Data 2025-11-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-11-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-11-19_e4e0292ec9_UP Data 2025-11-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-11-19 | 2025-11-19_e4e0292:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-11-26 | 2025-11-26_2b958ab7dd_UP Data 2025-11-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-11-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-11-26_2b958ab7dd_UP Data 2025-11-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-11-26 | 2025-11-26_2b958ab:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-10-01 | 2025-10-01_b019c74f28_UP Data 2025-10-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-10-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-10-01_b019c74f28_UP Data 2025-10-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-10-01 | 2025-10-01_b019c74:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-10-08 | 2025-10-08_f546c5e9a9_UP Data 2025-10-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-10-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-10-08_f546c5e9a9_UP Data 2025-10-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-10-08 | 2025-10-08_f546c5e:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-10-15 | 2025-10-15_85d7f6f8d9_UP Data 2025-10-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-10-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-10-15_85d7f6f8d9_UP Data 2025-10-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-10-15 | 2025-10-15_85d7f6f:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-10-22 | 2025-10-22_0cc3677cab_UP Data 2025-10-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-10-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-10-22_0cc3677cab_UP Data 2025-10-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-10-22 | 2025-10-22_0cc3677:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-10-29 | 2025-10-29_ff57c04c53_UP Data 2025-10-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-10-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-10-29_ff57c04c53_UP Data 2025-10-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-10-29 | 2025-10-29_ff57c04:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-09-03 | 2025-09-03_ae4896de4d_UP Data 2025-09-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-09-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-09-03_ae4896de4d_UP Data 2025-09-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-09-03 | 2025-09-03_ae4896d:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-09-10 | 2025-09-10_595d003179_UP Data 2025-09-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-09-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-09-10_595d003179_UP Data 2025-09-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-09-10 | 2025-09-10_595d003:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-09-17 | 2025-09-17_5a72d7bea0_UP Data 2025-09-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-09-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-09-17_5a72d7bea0_UP Data 2025-09-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-09-17 | 2025-09-17_5a72d7b:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-09-24 | 2025-09-24_f23df102ba_UP Data 2025-09-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-09-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-09-24_f23df102ba_UP Data 2025-09-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-09-24 | 2025-09-24_f23df10:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-08-06 | 2025-08-06_dea46d66bd_UP Data 2025-08-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-08-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-08-06_dea46d66bd_UP Data 2025-08-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-08-06 | 2025-08-06_dea46d6:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-08-13 | 2025-08-13_ae9401aa28_UP Data 2025-08-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-08-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-08-13_ae9401aa28_UP Data 2025-08-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-08-13 | 2025-08-13_ae9401a:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-08-20 | 2025-08-20_f8d7232aa5_UP Data 2025-08-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-08-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-08-20_f8d7232aa5_UP Data 2025-08-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-08-20 | 2025-08-20_f8d7232:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-08-27 | 2025-08-27_b1bd15a1d7_UP Data 2025-08-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-08-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-08-27_b1bd15a1d7_UP Data 2025-08-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-08-27 | 2025-08-27_b1bd15a:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-07-02 | 2025-07-02_fea065d431_UP Data 2025-07-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-07-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-07-02_fea065d431_UP Data 2025-07-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-07-02 | 2025-07-02_fea065d:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-07-09 | 2025-07-09_10c100d43b_UP Data 2025-07-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-07-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-07-09_10c100d43b_UP Data 2025-07-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-07-09 | 2025-07-09_10c100d:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-07-16 | 2025-07-16_5b015beb15_UP Data 2025-07-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-07-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-07-16_5b015beb15_UP Data 2025-07-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-07-16 | 2025-07-16_5b015be:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-07-23 | 2025-07-23_d54fb4edbd_UP Data 2025-07-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-07-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-07-23_d54fb4edbd_UP Data 2025-07-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-07-23 | 2025-07-23_d54fb4e:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-07-30 | 2025-07-30_ccd7451b27_UP Data 2025-07-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-07-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-07-30_ccd7451b27_UP Data 2025-07-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-07-30 | 2025-07-30_ccd7451:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-06-04 | 2025-06-04_93fa9f4529_UP Data 2025-06-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-06-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-06-04_93fa9f4529_UP Data 2025-06-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-06-04 | 2025-06-04_93fa9f4:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-06-11 | 2025-06-11_ef4052dd5f_UP Data 2025-06-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-06-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-06-11_ef4052dd5f_UP Data 2025-06-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-06-11 | 2025-06-11_ef4052d:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-06-18 | 2025-06-18_1bca793e9d_UP Data 2025-06-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-06-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-06-18_1bca793e9d_UP Data 2025-06-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-06-18 | 2025-06-18_1bca793:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-06-25 | 2025-06-25_71b8775a41_UP Data 2025-06-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-06-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-06-25_71b8775a41_UP Data 2025-06-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-06-25 | 2025-06-25_71b8775:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-05-07 | 2025-05-07_0897f0ea19_UP Data 2025-05-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-05-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-05-07_0897f0ea19_UP Data 2025-05-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-05-07 | 2025-05-07_0897f0e:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-05-14 | 2025-05-14_06de48117a_UP Data 2025-05-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-05-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-05-14_06de48117a_UP Data 2025-05-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-05-14 | 2025-05-14_06de481:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-05-21 | 2025-05-21_f151e3d89a_UP Data 2025-05-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-05-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-05-21_f151e3d89a_UP Data 2025-05-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-05-21 | 2025-05-21_f151e3d:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-05-28 | 2025-05-28_da3c318fd3_UP Data 2025-05-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-05-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-05-28_da3c318fd3_UP Data 2025-05-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-05-28 | 2025-05-28_da3c318:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-04-02 | 2025-04-02_ebc632926a_UP Data 2025-04-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-04-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-04-02_ebc632926a_UP Data 2025-04-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-04-02 | 2025-04-02_ebc6329:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-04-09 | 2025-04-09_3480dbb8b8_UP Data 2025-04-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-04-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-04-09_3480dbb8b8_UP Data 2025-04-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-04-09 | 2025-04-09_3480dbb:   0%|          | 0.00/40.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-04-16 | 2025-04-16_203ef05956_UP Data 2025-04-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-04-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-04-16_203ef05956_UP Data 2025-04-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-04-16 | 2025-04-16_203ef05:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-04-23 | 2025-04-23_a5ea535727_UP Data 2025-04-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-04-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-04-23_a5ea535727_UP Data 2025-04-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-04-23 | 2025-04-23_a5ea535:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-04-30 | 2025-04-30_075a83d435_UP Data 2025-04-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-04-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-04-30_075a83d435_UP Data 2025-04-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-04-30 | 2025-04-30_075a83d:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-03-05 | 2025-03-05_1381c4f131_UP Data 2025-03-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-03-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-03-05_1381c4f131_UP Data 2025-03-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-03-05 | 2025-03-05_1381c4f:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-03-12 | 2025-03-12_369f8f0b2e_UP Data 2025-03-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-03-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-03-12_369f8f0b2e_UP Data 2025-03-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-03-12 | 2025-03-12_369f8f0:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-03-19 | 2025-03-19_e91c40d87f_UP Data 2025-03-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-03-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-03-19_e91c40d87f_UP Data 2025-03-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-03-19 | 2025-03-19_e91c40d:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-03-26 | 2025-03-26_7ee6b3b13a_UP Data 2025-03-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-03-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-03-26_7ee6b3b13a_UP Data 2025-03-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-03-26 | 2025-03-26_7ee6b3b:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-02-05 | 2025-02-05_0939c3b808_UP Data 2025-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-02-05_0939c3b808_UP Data 2025-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-02-05 | 2025-02-05_0939c3b:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-02-12 | 2025-02-12_e0cd887671_UP Data 2025-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-02-12_e0cd887671_UP Data 2025-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-02-12 | 2025-02-12_e0cd887:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-02-19 | 2025-02-19_2445fd1e8b_UP Data 2025-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-02-19_2445fd1e8b_UP Data 2025-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-02-19 | 2025-02-19_2445fd1:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-02-26 | 2025-02-26_1fcaa2f5fa_UP Data 2025-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-02-26_1fcaa2f5fa_UP Data 2025-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-02-26 | 2025-02-26_1fcaa2f:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-01-01 | 2025-01-01_fcc4bfef0a_UP Data 2025-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-01-01_fcc4bfef0a_UP Data 2025-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-01-01 | 2025-01-01_fcc4bfe:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-01-08 | 2025-01-08_b8f17aefe3_UP Data 2025-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-01-08_b8f17aefe3_UP Data 2025-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-01-08 | 2025-01-08_b8f17ae:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-01-15 | 2025-01-15_14ab17d645_UP Data 2025-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-01-15_14ab17d645_UP Data 2025-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-01-15 | 2025-01-15_14ab17d:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-01-22 | 2025-01-22_34e52a40fb_UP Data 2025-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-01-22_34e52a40fb_UP Data 2025-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-01-22 | 2025-01-22_34e52a4:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2025-01-29 | 2025-01-29_bef89c8ee2_UP Data 2025-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202025-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2025\xlsx\2025-01-29_bef89c8ee2_UP Data 2025-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2025-01-29 | 2025-01-29_bef89c8:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-12-04 | 2024-12-04_e344b575e6_UP Data 2024-12-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-12-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-12-04_e344b575e6_UP Data 2024-12-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-12-04 | 2024-12-04_e344b57:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-12-11 | 2024-12-11_664f77f532_UP Data 2024-12-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-12-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-12-11_664f77f532_UP Data 2024-12-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-12-11 | 2024-12-11_664f77f:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-12-18 | 2024-12-18_ae4202d6ed_UP Data 2024-12-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-12-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-12-18_ae4202d6ed_UP Data 2024-12-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-12-18 | 2024-12-18_ae4202d:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-12-25 | 2024-12-25_44355d691f_UP Data 2024-12-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-12-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-12-25_44355d691f_UP Data 2024-12-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-12-25 | 2024-12-25_44355d6:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-11-06 | 2024-11-06_0c1cf9c22a_UP Data 2024-11-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-11-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-11-06_0c1cf9c22a_UP Data 2024-11-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-11-06 | 2024-11-06_0c1cf9c:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-11-13 | 2024-11-13_9f1f8ce5cc_UP Data 2024-11-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-11-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-11-13_9f1f8ce5cc_UP Data 2024-11-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-11-13 | 2024-11-13_9f1f8ce:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-11-20 | 2024-11-20_1dbfa1032f_UP Data 2024-11-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-11-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-11-20_1dbfa1032f_UP Data 2024-11-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-11-20 | 2024-11-20_1dbfa10:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-11-27 | 2024-11-27_ac45a27637_UP Data 2024-11-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-11-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-11-27_ac45a27637_UP Data 2024-11-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-11-27 | 2024-11-27_ac45a27:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-10-02 | 2024-10-02_cbbc9da1f1_UP Data 2024-10-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-10-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-10-02_cbbc9da1f1_UP Data 2024-10-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-10-02 | 2024-10-02_cbbc9da:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-10-09 | 2024-10-09_e99040c7c0_UP Data 2024-10-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-10-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-10-09_e99040c7c0_UP Data 2024-10-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-10-09 | 2024-10-09_e99040c:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-10-16 | 2024-10-16_9f69a8b080_UP Data 2024-10-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-10-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-10-16_9f69a8b080_UP Data 2024-10-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-10-16 | 2024-10-16_9f69a8b:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-10-23 | 2024-10-23_a23171683c_UP Data 2024-10-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-10-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-10-23_a23171683c_UP Data 2024-10-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-10-23 | 2024-10-23_a231716:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-10-30 | 2024-10-30_5531a5553d_UP Data 2024-10-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-10-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-10-30_5531a5553d_UP Data 2024-10-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-10-30 | 2024-10-30_5531a55:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-09-04 | 2024-09-04_de52b89ef0_UP Data 2024-09-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-09-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-09-04_de52b89ef0_UP Data 2024-09-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-09-04 | 2024-09-04_de52b89:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-09-11 | 2024-09-11_047d041152_UP Data 2024-09-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-09-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-09-11_047d041152_UP Data 2024-09-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-09-11 | 2024-09-11_047d041:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-09-18 | 2024-09-18_40acbbe05c_UP Data 2024-09-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-09-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-09-18_40acbbe05c_UP Data 2024-09-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-09-18 | 2024-09-18_40acbbe:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-09-25 | 2024-09-25_7cd0eba035_UP Data 2024-09-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-09-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-09-25_7cd0eba035_UP Data 2024-09-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-09-25 | 2024-09-25_7cd0eba:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-08-07 | 2024-08-07_478c7e7e2c_UP Data 2024-08-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-08-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-08-07_478c7e7e2c_UP Data 2024-08-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-08-07 | 2024-08-07_478c7e7:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-08-14 | 2024-08-14_88cb63ce49_UP Data 2024-08-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-08-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-08-14_88cb63ce49_UP Data 2024-08-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-08-14 | 2024-08-14_88cb63c:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-08-21 | 2024-08-21_20c18eda2f_UP Data 2024-08-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-08-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-08-21_20c18eda2f_UP Data 2024-08-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-08-21 | 2024-08-21_20c18ed:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-08-28 | 2024-08-28_bad85af361_UP Data 2024-08-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-08-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-08-28_bad85af361_UP Data 2024-08-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-08-28 | 2024-08-28_bad85af:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-07-03 | 2024-07-03_281b0b31c6_UP Data 2024-07-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-07-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-07-03_281b0b31c6_UP Data 2024-07-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-07-03 | 2024-07-03_281b0b3:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-07-10 | 2024-07-10_d5a16733b0_UP Data 2024-07-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-07-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-07-10_d5a16733b0_UP Data 2024-07-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-07-10 | 2024-07-10_d5a1673:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-07-17 | 2024-07-17_894fdd392d_UP Data 2024-07-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-07-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-07-17_894fdd392d_UP Data 2024-07-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-07-17 | 2024-07-17_894fdd3:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-07-24 | 2024-07-24_763e42495f_UP Data 2024-07-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-07-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-07-24_763e42495f_UP Data 2024-07-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-07-24 | 2024-07-24_763e424:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-07-31 | 2024-07-31_d52bb0dd11_UP Data 2024-07-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-07-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-07-31_d52bb0dd11_UP Data 2024-07-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-07-31 | 2024-07-31_d52bb0d:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-06-05 | 2024-06-05_7fc71dca49_UP Data 2024-06-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-06-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-06-05_7fc71dca49_UP Data 2024-06-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-06-05 | 2024-06-05_7fc71dc:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-06-12 | 2024-06-12_4e5827ae13_UP Data 2024-06-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-06-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-06-12_4e5827ae13_UP Data 2024-06-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-06-12 | 2024-06-12_4e5827a:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-06-19 | 2024-06-19_f00f4bd2ce_UP Data 2024-06-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-06-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-06-19_f00f4bd2ce_UP Data 2024-06-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-06-19 | 2024-06-19_f00f4bd:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-06-26 | 2024-06-26_eca67addbe_UP Data 2024-06-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-06-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-06-26_eca67addbe_UP Data 2024-06-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-06-26 | 2024-06-26_eca67ad:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-05-01 | 2024-05-01_950356e71d_UP Data 2024-05-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-05-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-05-01_950356e71d_UP Data 2024-05-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-05-01 | 2024-05-01_950356e:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-05-08 | 2024-05-08_a5c6c9b120_UP Data 2024-05-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-05-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-05-08_a5c6c9b120_UP Data 2024-05-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-05-08 | 2024-05-08_a5c6c9b:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-05-15 | 2024-05-15_3568e146d2_UP Data 2024-05-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-05-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-05-15_3568e146d2_UP Data 2024-05-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-05-15 | 2024-05-15_3568e14:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-05-22 | 2024-05-22_66d31a6147_UP Data 2024-05-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-05-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-05-22_66d31a6147_UP Data 2024-05-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-05-22 | 2024-05-22_66d31a6:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-05-29 | 2024-05-29_e14c84edfb_UP Data 2024-05-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-05-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-05-29_e14c84edfb_UP Data 2024-05-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-05-29 | 2024-05-29_e14c84e:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-04-03 | 2024-04-03_fd809f588a_UP Data 2024-04-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-04-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-04-03_fd809f588a_UP Data 2024-04-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-04-03 | 2024-04-03_fd809f5:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-04-10 | 2024-04-10_0ede26acf0_UP Data 2024-04-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-04-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-04-10_0ede26acf0_UP Data 2024-04-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-04-10 | 2024-04-10_0ede26a:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-04-17 | 2024-04-17_bc07948102_UP Data 2024-04-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-04-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-04-17_bc07948102_UP Data 2024-04-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-04-17 | 2024-04-17_bc07948:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-04-24 | 2024-04-24_612c41c55b_UP Data 2024-04-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-04-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-04-24_612c41c55b_UP Data 2024-04-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-04-24 | 2024-04-24_612c41c:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-03-06 | 2024-03-06_26372a5edf_UP Data 2024-03-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-03-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-03-06_26372a5edf_UP Data 2024-03-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-03-06 | 2024-03-06_26372a5:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-03-13 | 2024-03-13_86de86afd6_UP Data 2024-03-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-03-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-03-13_86de86afd6_UP Data 2024-03-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-03-13 | 2024-03-13_86de86a:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-03-20 | 2024-03-20_ad07e9c169_UP Data 2024-03-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-03-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-03-20_ad07e9c169_UP Data 2024-03-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-03-20 | 2024-03-20_ad07e9c:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-03-27 | 2024-03-27_f4be4acaad_UP Data 2024-03-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-03-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-03-27_f4be4acaad_UP Data 2024-03-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-03-27 | 2024-03-27_f4be4ac:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-02-07 | 2024-02-07_9c2147c03f_UP Data 2024-02-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-02-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-02-07_9c2147c03f_UP Data 2024-02-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-02-07 | 2024-02-07_9c2147c:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-02-14 | 2024-02-14_9ab9956d31_UP Data 2024-02-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-02-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-02-14_9ab9956d31_UP Data 2024-02-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-02-14 | 2024-02-14_9ab9956:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-02-21 | 2024-02-21_5b6c0fc031_UP Data 2024-02-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-02-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-02-21_5b6c0fc031_UP Data 2024-02-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-02-21 | 2024-02-21_5b6c0fc:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-02-28 | 2024-02-28_1d7f935a47_UP Data 2024-02-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-02-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-02-28_1d7f935a47_UP Data 2024-02-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-02-28 | 2024-02-28_1d7f935:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-01-03 | 2024-01-03_2f43a361af_UP Data 2024-01-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-01-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-01-03_2f43a361af_UP Data 2024-01-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-01-03 | 2024-01-03_2f43a36:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-01-10 | 2024-01-10_b25198908f_UP Data 2024-01-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-01-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-01-10_b25198908f_UP Data 2024-01-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-01-10 | 2024-01-10_b251989:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-01-17 | 2024-01-17_4941acfeff_UP Data 2024-01-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-01-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-01-17_4941acfeff_UP Data 2024-01-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-01-17 | 2024-01-17_4941acf:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-01-24 | 2024-01-24_da4c3808de_UP Data 2024-01-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-01-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-01-24_da4c3808de_UP Data 2024-01-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-01-24 | 2024-01-24_da4c380:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2024-01-31 | 2024-01-31_a914b2c681_UP Data 2024-01-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202024-01-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2024\xlsx\2024-01-31_a914b2c681_UP Data 2024-01-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2024-01-31 | 2024-01-31_a914b2c:   0%|          | 0.00/40.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-12-06 | 2023-12-06_a3d6f14b93_UP Data 2023-12-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-12-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-12-06_a3d6f14b93_UP Data 2023-12-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-12-06 | 2023-12-06_a3d6f14:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-12-13 | 2023-12-13_484fd8b5ff_UP Data 2023-12-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-12-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-12-13_484fd8b5ff_UP Data 2023-12-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-12-13 | 2023-12-13_484fd8b:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-12-20 | 2023-12-20_74feecc975_UP Data 2023-12-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-12-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-12-20_74feecc975_UP Data 2023-12-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-12-20 | 2023-12-20_74feecc:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-12-27 | 2023-12-27_11cdc939e6_UP Data 2023-12-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-12-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-12-27_11cdc939e6_UP Data 2023-12-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-12-27 | 2023-12-27_11cdc93:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-11-01 | 2023-11-01_e345492e0d_UP Data 2023-11-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-11-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-11-01_e345492e0d_UP Data 2023-11-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-11-01 | 2023-11-01_e345492:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-11-08 | 2023-11-08_08dc621ceb_UP Data 2023-11-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-11-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-11-08_08dc621ceb_UP Data 2023-11-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-11-08 | 2023-11-08_08dc621:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-11-15 | 2023-11-15_65c28a0b1b_UP Data 2023-11-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-11-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-11-15_65c28a0b1b_UP Data 2023-11-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-11-15 | 2023-11-15_65c28a0:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-11-22 | 2023-11-22_02f80e0c0c_UP Data 2023-11-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-11-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-11-22_02f80e0c0c_UP Data 2023-11-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-11-22 | 2023-11-22_02f80e0:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-11-29 | 2023-11-29_9107f51ba2_UP Data 2023-11-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-11-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-11-29_9107f51ba2_UP Data 2023-11-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-11-29 | 2023-11-29_9107f51:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-10-04 | 2023-10-04_2738db64d8_UP Data 2023-10-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-10-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-10-04_2738db64d8_UP Data 2023-10-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-10-04 | 2023-10-04_2738db6:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-10-11 | 2023-10-11_f01fe97e87_UP Data 2023-10-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-10-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-10-11_f01fe97e87_UP Data 2023-10-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-10-11 | 2023-10-11_f01fe97:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-10-18 | 2023-10-18_89360ffac2_UP Data 2023-10-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-10-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-10-18_89360ffac2_UP Data 2023-10-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-10-18 | 2023-10-18_89360ff:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-10-25 | 2023-10-25_ddfdf49f0e_UP Data 2023-10-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-10-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-10-25_ddfdf49f0e_UP Data 2023-10-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-10-25 | 2023-10-25_ddfdf49:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-09-06 | 2023-09-06_bb62179cd3_UP Data 2023-09-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-09-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-09-06_bb62179cd3_UP Data 2023-09-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-09-06 | 2023-09-06_bb62179:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-09-13 | 2023-09-13_397168c315_UP Data 2023-09-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-09-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-09-13_397168c315_UP Data 2023-09-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-09-13 | 2023-09-13_397168c:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-09-20 | 2023-09-20_49b5881b27_UP Data 2023-09-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-09-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-09-20_49b5881b27_UP Data 2023-09-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-09-20 | 2023-09-20_49b5881:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-09-27 | 2023-09-27_05809fafc3_UP Data 2023-09-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-09-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-09-27_05809fafc3_UP Data 2023-09-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-09-27 | 2023-09-27_05809fa:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-08-02 | 2023-08-02_328b7ffb2d_UP Data 2023-08-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-08-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-08-02_328b7ffb2d_UP Data 2023-08-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-08-02 | 2023-08-02_328b7ff:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-08-09 | 2023-08-09_523da2089e_UP Data 2023-08-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-08-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-08-09_523da2089e_UP Data 2023-08-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-08-09 | 2023-08-09_523da20:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-08-16 | 2023-08-16_20919900f3_UP Data 2023-08-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-08-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-08-16_20919900f3_UP Data 2023-08-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-08-16 | 2023-08-16_2091990:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-08-23 | 2023-08-23_9e19f2d449_UP Data 2023-08-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-08-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-08-23_9e19f2d449_UP Data 2023-08-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-08-23 | 2023-08-23_9e19f2d:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-08-30 | 2023-08-30_54bfd0d044_UP Data 2023-08-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-08-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-08-30_54bfd0d044_UP Data 2023-08-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-08-30 | 2023-08-30_54bfd0d:   0%|          | 0.00/40.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-07-05 | 2023-07-05_9463a6a82a_UP Data 2023-07-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-07-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-07-05_9463a6a82a_UP Data 2023-07-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-07-05 | 2023-07-05_9463a6a:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-07-12 | 2023-07-12_5e89b21e53_UP Data 2023-07-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-07-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-07-12_5e89b21e53_UP Data 2023-07-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-07-12 | 2023-07-12_5e89b21:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-07-19 | 2023-07-19_d724b9d597_UP Data 2023-07-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-07-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-07-19_d724b9d597_UP Data 2023-07-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-07-19 | 2023-07-19_d724b9d:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-07-26 | 2023-07-26_f40c66a22f_UP Data 2023-07-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-07-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-07-26_f40c66a22f_UP Data 2023-07-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-07-26 | 2023-07-26_f40c66a:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-06-07 | 2023-06-07_37f163ac56_UP Data 2023-06-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-06-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-06-07_37f163ac56_UP Data 2023-06-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-06-07 | 2023-06-07_37f163a:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-06-14 | 2023-06-14_b47c792762_UP Data 2023-06-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-06-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-06-14_b47c792762_UP Data 2023-06-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-06-14 | 2023-06-14_b47c792:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-06-21 | 2023-06-21_28efeaef3e_UP Data 2023-06-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-06-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-06-21_28efeaef3e_UP Data 2023-06-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-06-21 | 2023-06-21_28efeae:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-06-28 | 2023-06-28_8ed8ba3edc_UP Data 2023-06-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-06-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-06-28_8ed8ba3edc_UP Data 2023-06-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-06-28 | 2023-06-28_8ed8ba3:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-05-03 | 2023-05-03_da3b4ced55_UP Data 2023-05-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-05-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-05-03_da3b4ced55_UP Data 2023-05-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-05-03 | 2023-05-03_da3b4ce:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-05-10 | 2023-05-10_252bec26ef_UP Data 2023-05-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-05-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-05-10_252bec26ef_UP Data 2023-05-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-05-10 | 2023-05-10_252bec2:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-05-17 | 2023-05-17_3008da581a_UP Data 2023-05-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-05-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-05-17_3008da581a_UP Data 2023-05-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-05-17 | 2023-05-17_3008da5:   0%|          | 0.00/40.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-05-24 | 2023-05-24_ed49b59925_UP Data 2023-05-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-05-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-05-24_ed49b59925_UP Data 2023-05-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-05-24 | 2023-05-24_ed49b59:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-05-31 | 2023-05-31_8eea78f6ac_UP Data 2023-05-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-05-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-05-31_8eea78f6ac_UP Data 2023-05-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-05-31 | 2023-05-31_8eea78f:   0%|          | 0.00/40.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-04-05 | 2023-04-05_ed75494f32_UP Data 2023-04-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-04-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-04-05_ed75494f32_UP Data 2023-04-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-04-05 | 2023-04-05_ed75494:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-04-12 | 2023-04-12_7624a2ec1f_UP Data 2023-04-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-04-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-04-12_7624a2ec1f_UP Data 2023-04-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-04-12 | 2023-04-12_7624a2e:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-04-19 | 2023-04-19_afa553f4dc_UP Data 2023-04-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-04-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-04-19_afa553f4dc_UP Data 2023-04-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-04-19 | 2023-04-19_afa553f:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-04-26 | 2023-04-26_96c6561ac6_UP Data 2023-04-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-04-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-04-26_96c6561ac6_UP Data 2023-04-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-04-26 | 2023-04-26_96c6561:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-03-01 | 2023-03-01_5e29001441_UP Data 2023-03-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-03-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-03-01_5e29001441_UP Data 2023-03-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-03-01 | 2023-03-01_5e29001:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-03-08 | 2023-03-08_624ec3fb96_UP Data 2023-03-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-03-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-03-08_624ec3fb96_UP Data 2023-03-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-03-08 | 2023-03-08_624ec3f:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-03-15 | 2023-03-15_43926116ee_UP Data 2023-03-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-03-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-03-15_43926116ee_UP Data 2023-03-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-03-15 | 2023-03-15_4392611:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-03-22 | 2023-03-22_39722eb103_UP Data 2023-03-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-03-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-03-22_39722eb103_UP Data 2023-03-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-03-22 | 2023-03-22_39722eb:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-03-29 | 2023-03-29_8b33700962_UP Data 2023-03-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-03-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-03-29_8b33700962_UP Data 2023-03-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-03-29 | 2023-03-29_8b33700:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-02-01 | 2023-02-01_f548920297_UP Data 2023-02-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-02-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-02-01_f548920297_UP Data 2023-02-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-02-01 | 2023-02-01_f548920:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-02-08 | 2023-02-08_dfa3d7bbf8_UP Data 2023-02-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-02-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-02-08_dfa3d7bbf8_UP Data 2023-02-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-02-08 | 2023-02-08_dfa3d7b:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-02-15 | 2023-02-15_29ff14f568_UP Data 2023-02-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-02-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-02-15_29ff14f568_UP Data 2023-02-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-02-15 | 2023-02-15_29ff14f:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-02-22 | 2023-02-22_79b8e56523_UP Data 2023-02-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-02-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-02-22_79b8e56523_UP Data 2023-02-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-02-22 | 2023-02-22_79b8e56:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-01-04 | 2023-01-04_a4196681a9_UP Data 2023-01-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-01-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-01-04_a4196681a9_UP Data 2023-01-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-01-04 | 2023-01-04_a419668:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-01-11 | 2023-01-11_ef95d691f6_UP Data 2023-01-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-01-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-01-11_ef95d691f6_UP Data 2023-01-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-01-11 | 2023-01-11_ef95d69:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-01-18 | 2023-01-18_3bc19d6d16_UP Data 2023-01-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-01-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-01-18_3bc19d6d16_UP Data 2023-01-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-01-18 | 2023-01-18_3bc19d6:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2023-01-25 | 2023-01-25_f586505d4f_UP Data 2023-01-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202023-01-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2023\xlsx\2023-01-25_f586505d4f_UP Data 2023-01-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2023-01-25 | 2023-01-25_f586505:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-12-07 | 2022-12-07_f971d624c3_UP Data 2022-12-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-12-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-12-07_f971d624c3_UP Data 2022-12-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-12-07 | 2022-12-07_f971d62:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-12-14 | 2022-12-14_b6f35d4104_UP Data 2022-12-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-12-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-12-14_b6f35d4104_UP Data 2022-12-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-12-14 | 2022-12-14_b6f35d4:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-12-21 | 2022-12-21_f0496e4586_UP Data 2022-12-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-12-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-12-21_f0496e4586_UP Data 2022-12-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-12-21 | 2022-12-21_f0496e4:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-12-28 | 2022-12-28_1222f56c78_UP Data 2022-12-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-12-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-12-28_1222f56c78_UP Data 2022-12-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-12-28 | 2022-12-28_1222f56:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-11-02 | 2022-11-02_7b0a76814c_UP Data 2022-11-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-11-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-11-02_7b0a76814c_UP Data 2022-11-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-11-02 | 2022-11-02_7b0a768:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-11-09 | 2022-11-09_162dcea50f_UP Data 2022-11-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-11-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-11-09_162dcea50f_UP Data 2022-11-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-11-09 | 2022-11-09_162dcea:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-11-16 | 2022-11-16_68f41a761a_UP Data 2022-11-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-11-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-11-16_68f41a761a_UP Data 2022-11-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-11-16 | 2022-11-16_68f41a7:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-11-23 | 2022-11-23_c44dca3aee_UP Data 2022-11-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-11-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-11-23_c44dca3aee_UP Data 2022-11-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-11-23 | 2022-11-23_c44dca3:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-11-30 | 2022-11-30_612096f61e_UP Data 2022-11-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-11-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-11-30_612096f61e_UP Data 2022-11-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-11-30 | 2022-11-30_612096f:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-10-05 | 2022-10-05_cbece1e957_UP Data 2022-10-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-10-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-10-05_cbece1e957_UP Data 2022-10-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-10-05 | 2022-10-05_cbece1e:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-10-12 | 2022-10-12_2b41681c16_UP Data 2022-10-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-10-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-10-12_2b41681c16_UP Data 2022-10-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-10-12 | 2022-10-12_2b41681:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-10-19 | 2022-10-19_28a6490e43_UP Data 2022-10-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-10-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-10-19_28a6490e43_UP Data 2022-10-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-10-19 | 2022-10-19_28a6490:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-10-26 | 2022-10-26_b865f756ae_UP Data 2022-10-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-10-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-10-26_b865f756ae_UP Data 2022-10-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-10-26 | 2022-10-26_b865f75:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-09-07 | 2022-09-07_dbf9eeded2_UP Data 2022-09-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-09-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-09-07_dbf9eeded2_UP Data 2022-09-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-09-07 | 2022-09-07_dbf9eed:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-09-14 | 2022-09-14_c6fd573d4d_UP Data 2022-09-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-09-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-09-14_c6fd573d4d_UP Data 2022-09-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-09-14 | 2022-09-14_c6fd573:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-09-21 | 2022-09-21_e11b529981_UP Data 2022-09-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-09-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-09-21_e11b529981_UP Data 2022-09-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-09-21 | 2022-09-21_e11b529:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-09-28 | 2022-09-28_89f3fa14ca_UP Data 2022-09-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-09-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-09-28_89f3fa14ca_UP Data 2022-09-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-09-28 | 2022-09-28_89f3fa1:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-08-03 | 2022-08-03_d8d9c58151_UP Data 2022-08-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-08-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-08-03_d8d9c58151_UP Data 2022-08-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-08-03 | 2022-08-03_d8d9c58:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-08-10 | 2022-08-10_011289167a_UP Data 2022-08-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-08-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-08-10_011289167a_UP Data 2022-08-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-08-10 | 2022-08-10_0112891:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-08-17 | 2022-08-17_8979ec671a_UP Data 2022-08-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-08-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-08-17_8979ec671a_UP Data 2022-08-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-08-17 | 2022-08-17_8979ec6:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-08-24 | 2022-08-24_28337c94b0_UP Data 2022-08-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-08-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-08-24_28337c94b0_UP Data 2022-08-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-08-24 | 2022-08-24_28337c9:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-08-31 | 2022-08-31_80d3e03d51_UP Data 2022-08-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-08-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-08-31_80d3e03d51_UP Data 2022-08-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-08-31 | 2022-08-31_80d3e03:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-07-06 | 2022-07-06_033d74f562_UP Data 2022-07-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-07-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-07-06_033d74f562_UP Data 2022-07-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-07-06 | 2022-07-06_033d74f:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-07-13 | 2022-07-13_7d96088ae9_UP Data 2022-07-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-07-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-07-13_7d96088ae9_UP Data 2022-07-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-07-13 | 2022-07-13_7d96088:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-07-20 | 2022-07-20_895aa68d25_UP Data 2022-07-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-07-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-07-20_895aa68d25_UP Data 2022-07-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-07-20 | 2022-07-20_895aa68:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-07-27 | 2022-07-27_2af503bc7e_UP Data 2022-07-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-07-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-07-27_2af503bc7e_UP Data 2022-07-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-07-27 | 2022-07-27_2af503b:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-06-01 | 2022-06-01_85354ff101_UP Data 2022-06-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-06-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-06-01_85354ff101_UP Data 2022-06-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-06-01 | 2022-06-01_85354ff:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-06-08 | 2022-06-08_0926104839_UP Data 2022-06-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-06-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-06-08_0926104839_UP Data 2022-06-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-06-08 | 2022-06-08_0926104:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-06-15 | 2022-06-15_39eeb78dc3_UP Data 2022-06-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-06-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-06-15_39eeb78dc3_UP Data 2022-06-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-06-15 | 2022-06-15_39eeb78:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-06-22 | 2022-06-22_c53ac5ac1b_UP Data 2022-06-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-06-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-06-22_c53ac5ac1b_UP Data 2022-06-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-06-22 | 2022-06-22_c53ac5a:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-06-29 | 2022-06-29_0dce3ec43f_UP Data 2022-06-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-06-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-06-29_0dce3ec43f_UP Data 2022-06-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-06-29 | 2022-06-29_0dce3ec:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-05-04 | 2022-05-04_32053f7d94_UP Data 2022-05-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-05-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-05-04_32053f7d94_UP Data 2022-05-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-05-04 | 2022-05-04_32053f7:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-05-11 | 2022-05-11_1a1331347e_UP Data 2022-05-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-05-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-05-11_1a1331347e_UP Data 2022-05-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-05-11 | 2022-05-11_1a13313:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-05-18 | 2022-05-18_f7063d7983_UP Data 2022-05-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-05-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-05-18_f7063d7983_UP Data 2022-05-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-05-18 | 2022-05-18_f7063d7:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-05-25 | 2022-05-25_11e81d1be0_UP Data 2022-05-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-05-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-05-25_11e81d1be0_UP Data 2022-05-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-05-25 | 2022-05-25_11e81d1:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-04-06 | 2022-04-06_247722097a_UP Data 2022-04-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-04-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-04-06_247722097a_UP Data 2022-04-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-04-06 | 2022-04-06_2477220:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-04-13 | 2022-04-13_faaf58262c_UP Data 2022-04-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-04-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-04-13_faaf58262c_UP Data 2022-04-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-04-13 | 2022-04-13_faaf582:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-04-20 | 2022-04-20_f11df9a836_UP Data 2022-04-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-04-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-04-20_f11df9a836_UP Data 2022-04-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-04-20 | 2022-04-20_f11df9a:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-04-27 | 2022-04-27_bee0ad8165_UP Data 2022-04-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-04-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-04-27_bee0ad8165_UP Data 2022-04-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-04-27 | 2022-04-27_bee0ad8:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-03-02 | 2022-03-02_49b124a486_UP Data 2022-03-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-03-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-03-02_49b124a486_UP Data 2022-03-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-03-02 | 2022-03-02_49b124a:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-03-09 | 2022-03-09_c8c6ccc427_UP Data 2022-03-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-03-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-03-09_c8c6ccc427_UP Data 2022-03-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-03-09 | 2022-03-09_c8c6ccc:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-03-16 | 2022-03-16_a606f68409_UP Data 2022-03-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-03-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-03-16_a606f68409_UP Data 2022-03-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-03-16 | 2022-03-16_a606f68:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-03-23 | 2022-03-23_e31df78b9c_UP Data 2022-03-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-03-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-03-23_e31df78b9c_UP Data 2022-03-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-03-23 | 2022-03-23_e31df78:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-03-30 | 2022-03-30_07af8a129f_UP Data 2022-03-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-03-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-03-30_07af8a129f_UP Data 2022-03-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-03-30 | 2022-03-30_07af8a1:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-02-02 | 2022-02-02_4e88d11527_UP Data 2022-02-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-02-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-02-02_4e88d11527_UP Data 2022-02-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-02-02 | 2022-02-02_4e88d11:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-02-09 | 2022-02-09_722da337dc_UP Data 2022-02-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-02-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-02-09_722da337dc_UP Data 2022-02-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-02-09 | 2022-02-09_722da33:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-02-16 | 2022-02-16_e021e5ee48_UP Data 2022-02-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-02-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-02-16_e021e5ee48_UP Data 2022-02-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-02-16 | 2022-02-16_e021e5e:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-02-23 | 2022-02-23_521429aac8_UP Data 2022-02-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-02-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-02-23_521429aac8_UP Data 2022-02-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-02-23 | 2022-02-23_521429a:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-01-05 | 2022-01-05_df156a08c5_UP Data 2022-01-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-01-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-01-05_df156a08c5_UP Data 2022-01-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-01-05 | 2022-01-05_df156a0:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-01-12 | 2022-01-12_0760ba8324_UP Data 2022-01-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-01-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-01-12_0760ba8324_UP Data 2022-01-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-01-12 | 2022-01-12_0760ba8:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-01-19 | 2022-01-19_a4703dcfa4_UP Data 2022-01-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-01-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-01-19_a4703dcfa4_UP Data 2022-01-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-01-19 | 2022-01-19_a4703dc:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2022-01-26 | 2022-01-26_ad2e013b3c_UP Data 2022-01-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202022-01-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2022\xlsx\2022-01-26_ad2e013b3c_UP Data 2022-01-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2022-01-26 | 2022-01-26_ad2e013:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-12-01 | 2021-12-01_3ab2bd0c15_UP Data 2021-12-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-12-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-12-01_3ab2bd0c15_UP Data 2021-12-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-12-01 | 2021-12-01_3ab2bd0:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-12-08 | 2021-12-08_c425588d4d_UP Data 2021-12-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-12-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-12-08_c425588d4d_UP Data 2021-12-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-12-08 | 2021-12-08_c425588:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-12-15 | 2021-12-15_974fdf42a4_UP Data 2021-12-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-12-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-12-15_974fdf42a4_UP Data 2021-12-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-12-15 | 2021-12-15_974fdf4:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-12-22 | 2021-12-22_fb75e923dc_UP Data 2021-12-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-12-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-12-22_fb75e923dc_UP Data 2021-12-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-12-22 | 2021-12-22_fb75e92:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-12-29 | 2021-12-29_46e8fb9cc9_UP Data 2021-12-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-12-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-12-29_46e8fb9cc9_UP Data 2021-12-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-12-29 | 2021-12-29_46e8fb9:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-11-03 | 2021-11-03_db8907ab91_UP Data 2021-11-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-11-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-11-03_db8907ab91_UP Data 2021-11-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-11-03 | 2021-11-03_db8907a:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-11-10 | 2021-11-10_87495ef411_UP Data 2021-11-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-11-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-11-10_87495ef411_UP Data 2021-11-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-11-10 | 2021-11-10_87495ef:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-11-17 | 2021-11-17_5141370cc3_UP Data 2021-11-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-11-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-11-17_5141370cc3_UP Data 2021-11-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-11-17 | 2021-11-17_5141370:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-11-24 | 2021-11-24_0400897090_UP Data 2021-11-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-11-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-11-24_0400897090_UP Data 2021-11-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-11-24 | 2021-11-24_0400897:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-10-06 | 2021-10-06_2ca1e2df17_UP Data 2021-10-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-10-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-10-06_2ca1e2df17_UP Data 2021-10-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-10-06 | 2021-10-06_2ca1e2d:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-10-13 | 2021-10-13_7e17056ae3_UP Data 2021-10-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-10-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-10-13_7e17056ae3_UP Data 2021-10-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-10-13 | 2021-10-13_7e17056:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-10-20 | 2021-10-20_935e4aa719_UP Data 2021-10-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-10-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-10-20_935e4aa719_UP Data 2021-10-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-10-20 | 2021-10-20_935e4aa:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-10-27 | 2021-10-27_0866d10c3e_UP Data 2021-10-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-10-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-10-27_0866d10c3e_UP Data 2021-10-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-10-27 | 2021-10-27_0866d10:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-09-01 | 2021-09-01_ae58022e01_UP Data 2021-09-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-09-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-09-01_ae58022e01_UP Data 2021-09-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-09-01 | 2021-09-01_ae58022:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-09-08 | 2021-09-08_83171991aa_UP Data 2021-09-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-09-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-09-08_83171991aa_UP Data 2021-09-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-09-08 | 2021-09-08_8317199:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-09-15 | 2021-09-15_8cc5282897_UP Data 2021-09-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-09-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-09-15_8cc5282897_UP Data 2021-09-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-09-15 | 2021-09-15_8cc5282:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-09-22 | 2021-09-22_d25547e867_UP Data 2021-09-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-09-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-09-22_d25547e867_UP Data 2021-09-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-09-22 | 2021-09-22_d25547e:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-09-29 | 2021-09-29_aa98431fd1_UP Data 2021-09-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-09-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-09-29_aa98431fd1_UP Data 2021-09-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-09-29 | 2021-09-29_aa98431:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-08-04 | 2021-08-04_19cf6862dc_UP Data 2021-08-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-08-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-08-04_19cf6862dc_UP Data 2021-08-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-08-04 | 2021-08-04_19cf686:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-08-11 | 2021-08-11_fa1f072bbd_UP Data 2021-08-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-08-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-08-11_fa1f072bbd_UP Data 2021-08-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-08-11 | 2021-08-11_fa1f072:   0%|          | 0.00/41.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-08-18 | 2021-08-18_cf78e8cdb6_UP Data 2021-08-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-08-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-08-18_cf78e8cdb6_UP Data 2021-08-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-08-18 | 2021-08-18_cf78e8c:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-08-25 | 2021-08-25_1f20fd82c5_UP Data 2021-08-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-08-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-08-25_1f20fd82c5_UP Data 2021-08-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-08-25 | 2021-08-25_1f20fd8:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-07-07 | 2021-07-07_daffa14af3_UP Data 2021-07-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-07-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-07-07_daffa14af3_UP Data 2021-07-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-07-07 | 2021-07-07_daffa14:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-07-14 | 2021-07-14_bff177f62f_UP Data 2021-07-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-07-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-07-14_bff177f62f_UP Data 2021-07-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-07-14 | 2021-07-14_bff177f:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-07-21 | 2021-07-21_0345b36b57_UP Data 2021-07-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-07-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-07-21_0345b36b57_UP Data 2021-07-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-07-21 | 2021-07-21_0345b36:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-07-28 | 2021-07-28_96d9e8971b_UP Data 2021-07-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-07-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-07-28_96d9e8971b_UP Data 2021-07-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-07-28 | 2021-07-28_96d9e89:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-06-02 | 2021-06-02_ea50230d9c_UP Data 2021-06-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-06-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-06-02_ea50230d9c_UP Data 2021-06-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-06-02 | 2021-06-02_ea50230:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-06-09 | 2021-06-09_f40c046c05_UP Data 2021-06-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-06-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-06-09_f40c046c05_UP Data 2021-06-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-06-09 | 2021-06-09_f40c046:   0%|          | 0.00/41.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-06-16 | 2021-06-16_80d09e1bce_UP Data 2021-06-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-06-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-06-16_80d09e1bce_UP Data 2021-06-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-06-16 | 2021-06-16_80d09e1:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-06-23 | 2021-06-23_e02f151104_UP Data 2021-06-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-06-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-06-23_e02f151104_UP Data 2021-06-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-06-23 | 2021-06-23_e02f151:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-06-30 | 2021-06-30_6db70a7d19_UP Data 2021-06-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-06-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-06-30_6db70a7d19_UP Data 2021-06-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-06-30 | 2021-06-30_6db70a7:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-05-05 | 2021-05-05_2984afce6d_UP Data 2021-05-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-05-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-05-05_2984afce6d_UP Data 2021-05-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-05-05 | 2021-05-05_2984afc:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-05-12 | 2021-05-12_1ee581beeb_UP Data 2021-05-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-05-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-05-12_1ee581beeb_UP Data 2021-05-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-05-12 | 2021-05-12_1ee581b:   0%|          | 0.00/40.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-05-19 | 2021-05-19_27c6facf30_UP Data 2021-05-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-05-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-05-19_27c6facf30_UP Data 2021-05-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-05-19 | 2021-05-19_27c6fac:   0%|          | 0.00/40.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-05-26 | 2021-05-26_9e705bfb9a_UP Data 2021-05-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-05-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-05-26_9e705bfb9a_UP Data 2021-05-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-05-26 | 2021-05-26_9e705bf:   0%|          | 0.00/41.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-04-07 | 2021-04-07_11e7f03f41_UP Data 2021-04-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-04-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-04-07_11e7f03f41_UP Data 2021-04-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-04-07 | 2021-04-07_11e7f03:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-04-14 | 2021-04-14_35b9cddb2d_UP Data 2021-04-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-04-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-04-14_35b9cddb2d_UP Data 2021-04-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-04-14 | 2021-04-14_35b9cdd:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-04-21 | 2021-04-21_e61c8c9bf9_UP Data 2021-04-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-04-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-04-21_e61c8c9bf9_UP Data 2021-04-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-04-21 | 2021-04-21_e61c8c9:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-04-28 | 2021-04-28_36ce212314_UP Data 2021-04-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-04-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-04-28_36ce212314_UP Data 2021-04-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-04-28 | 2021-04-28_36ce212:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-03-03 | 2021-03-03_42f85f2bc8_UP Data 2021-03-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-03-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-03-03_42f85f2bc8_UP Data 2021-03-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-03-03 | 2021-03-03_42f85f2:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-03-10 | 2021-03-10_67a637f138_UP Data 2021-03-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-03-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-03-10_67a637f138_UP Data 2021-03-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-03-10 | 2021-03-10_67a637f:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-03-17 | 2021-03-17_4efff710b8_UP Data 2021-03-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-03-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-03-17_4efff710b8_UP Data 2021-03-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-03-17 | 2021-03-17_4efff71:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-03-24 | 2021-03-24_1ed37d1d6a_UP Data 2021-03-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-03-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-03-24_1ed37d1d6a_UP Data 2021-03-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-03-24 | 2021-03-24_1ed37d1:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-03-31 | 2021-03-31_48d84cc2de_UP Data 2021-03-31.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-03-31.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-03-31_48d84cc2de_UP Data 2021-03-31.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-03-31 | 2021-03-31_48d84cc:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-02-03 | 2021-02-03_8b5a5eaaf2_UP Data 2021-02-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-02-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-02-03_8b5a5eaaf2_UP Data 2021-02-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-02-03 | 2021-02-03_8b5a5ea:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-02-10 | 2021-02-10_138bef24d9_UP Data 2021-02-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-02-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-02-10_138bef24d9_UP Data 2021-02-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-02-10 | 2021-02-10_138bef2:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-02-17 | 2021-02-17_e6ac998e01_UP Data 2021-02-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-02-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-02-17_e6ac998e01_UP Data 2021-02-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-02-17 | 2021-02-17_e6ac998:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-02-24 | 2021-02-24_6ee054b47f_UP Data 2021-02-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-02-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-02-24_6ee054b47f_UP Data 2021-02-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-02-24 | 2021-02-24_6ee054b:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-01-06 | 2021-01-06_5c4d0b7849_UP Data 2021-01-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-01-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-01-06_5c4d0b7849_UP Data 2021-01-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-01-06 | 2021-01-06_5c4d0b7:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-01-13 | 2021-01-13_f7c3a9ca8a_UP Data 2021-01-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-01-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-01-13_f7c3a9ca8a_UP Data 2021-01-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-01-13 | 2021-01-13_f7c3a9c:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-01-20 | 2021-01-20_a5326448b2_UP Data 2021-01-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-01-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-01-20_a5326448b2_UP Data 2021-01-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-01-20 | 2021-01-20_a532644:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2021-01-27 | 2021-01-27_e16d0d7633_UP Data 2021-01-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202021-01-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2021\xlsx\2021-01-27_e16d0d7633_UP Data 2021-01-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2021-01-27 | 2021-01-27_e16d0d7:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-12-02 | 2020-12-02_931651c0bd_UP Data 2020-12-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-12-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-12-02_931651c0bd_UP Data 2020-12-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-12-02 | 2020-12-02_931651c:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-12-09 | 2020-12-09_2fb6a5e7af_UP Data 2020-12-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-12-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-12-09_2fb6a5e7af_UP Data 2020-12-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-12-09 | 2020-12-09_2fb6a5e:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-12-16 | 2020-12-16_dd0abe4990_UP Data 2020-12-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-12-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-12-16_dd0abe4990_UP Data 2020-12-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-12-16 | 2020-12-16_dd0abe4:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-12-23 | 2020-12-23_eeeb92919c_UP Data 2020-12-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-12-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-12-23_eeeb92919c_UP Data 2020-12-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-12-23 | 2020-12-23_eeeb929:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-12-30 | 2020-12-30_ce9d20578b_UP Data 2020-12-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-12-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-12-30_ce9d20578b_UP Data 2020-12-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-12-30 | 2020-12-30_ce9d205:   0%|          | 0.00/35.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-11-04 | 2020-11-04_6bcd186e6e_UP Data 2020-11-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-11-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-11-04_6bcd186e6e_UP Data 2020-11-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-11-04 | 2020-11-04_6bcd186:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-11-11 | 2020-11-11_17e56c2133_UP Data 2020-11-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-11-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-11-11_17e56c2133_UP Data 2020-11-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-11-11 | 2020-11-11_17e56c2:   0%|          | 0.00/34.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-11-18 | 2020-11-18_4564edd9d3_UP Data 2020-11-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-11-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-11-18_4564edd9d3_UP Data 2020-11-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-11-18 | 2020-11-18_4564edd:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-11-25 | 2020-11-25_dc37ae475e_UP Data 2020-11-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-11-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-11-25_dc37ae475e_UP Data 2020-11-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-11-25 | 2020-11-25_dc37ae4:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-10-07 | 2020-10-07_59eb6e0bd9_UP Data 2020-10-07.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-10-07.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-10-07_59eb6e0bd9_UP Data 2020-10-07.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-10-07 | 2020-10-07_59eb6e0:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-10-14 | 2020-10-14_b5ad5a22a5_UP Data 2020-10-14.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-10-14.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-10-14_b5ad5a22a5_UP Data 2020-10-14.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-10-14 | 2020-10-14_b5ad5a2:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-10-21 | 2020-10-21_d907f0538a_UP Data 2020-10-21.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-10-21.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-10-21_d907f0538a_UP Data 2020-10-21.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-10-21 | 2020-10-21_d907f05:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-10-28 | 2020-10-28_d1776c7c2d_UP Data 2020-10-28.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-10-28.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-10-28_d1776c7c2d_UP Data 2020-10-28.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-10-28 | 2020-10-28_d1776c7:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-09-02 | 2020-09-02_3b3ddd3f9c_UP Data 2020-09-02.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-09-02.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-09-02_3b3ddd3f9c_UP Data 2020-09-02.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-09-02 | 2020-09-02_3b3ddd3:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-09-09 | 2020-09-09_35c3686196_UP Data 2020-09-09.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-09-09.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-09-09_35c3686196_UP Data 2020-09-09.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-09-09 | 2020-09-09_35c3686:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-09-16 | 2020-09-16_9857769cdb_UP Data 2020-09-16.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-09-16.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-09-16_9857769cdb_UP Data 2020-09-16.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-09-16 | 2020-09-16_9857769:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-09-23 | 2020-09-23_40450cbe11_UP Data 2020-09-23.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-09-23.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-09-23_40450cbe11_UP Data 2020-09-23.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-09-23 | 2020-09-23_40450cb:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-09-30 | 2020-09-30_922db1e509_UP Data 2020-09-30.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-09-30.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-09-30_922db1e509_UP Data 2020-09-30.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-09-30 | 2020-09-30_922db1e:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-08-05 | 2020-08-05_33b3d8f00e_UP Data 2020-08-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-08-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-08-05_33b3d8f00e_UP Data 2020-08-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-08-05 | 2020-08-05_33b3d8f:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-08-12 | 2020-08-12_7828bdb17d_UP Data 2020-08-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-08-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-08-12_7828bdb17d_UP Data 2020-08-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-08-12 | 2020-08-12_7828bdb:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-08-19 | 2020-08-19_70311c6c41_UP Data 2020-08-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-08-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-08-19_70311c6c41_UP Data 2020-08-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-08-19 | 2020-08-19_70311c6:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-08-26 | 2020-08-26_f0141c2c4e_UP Data 2020-08-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-08-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-08-26_f0141c2c4e_UP Data 2020-08-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-08-26 | 2020-08-26_f0141c2:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-07-01 | 2020-07-01_37e0e84ff6_up_data_2020-07-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-07-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-07-01_37e0e84ff6_up_data_2020-07-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-07-01 | 2020-07-01_37e0e84:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-07-08 | 2020-07-08_84c7c128ef_up_data_2020-07-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-07-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-07-08_84c7c128ef_up_data_2020-07-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-07-08 | 2020-07-08_84c7c12:   0%|          | 0.00/34.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-07-15 | 2020-07-15_fadc5f0287_up_data_2020-07-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-07-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-07-15_fadc5f0287_up_data_2020-07-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-07-15 | 2020-07-15_fadc5f0:   0%|          | 0.00/34.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-07-22 | 2020-07-22_dc5817edc6_up_data_2020-07-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-07-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-07-22_dc5817edc6_up_data_2020-07-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-07-22 | 2020-07-22_dc5817e:   0%|          | 0.00/35.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-07-29 | 2020-07-29_7a68009bdc_UP Data 2020-07-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/UP%20Data%202020-07-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-07-29_7a68009bdc_UP Data 2020-07-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-07-29 | 2020-07-29_7a68009:   0%|          | 0.00/35.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-06-03 | 2020-06-03_70276cdf3f_up_data_2020-06-03.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-06-03.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-06-03_70276cdf3f_up_data_2020-06-03.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-06-03 | 2020-06-03_70276cd:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-06-10 | 2020-06-10_b8f2eda60b_up_data_2020-06-10.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-06-10.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-06-10_b8f2eda60b_up_data_2020-06-10.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-06-10 | 2020-06-10_b8f2eda:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-06-17 | 2020-06-17_10405ef570_up_data_2020-06-17.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-06-17.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-06-17_10405ef570_up_data_2020-06-17.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-06-17 | 2020-06-17_10405ef:   0%|          | 0.00/40.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-06-24 | 2020-06-24_16da4b13f5_up_data_2020-06-24.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-06-24.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-06-24_16da4b13f5_up_data_2020-06-24.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-06-24 | 2020-06-24_16da4b1:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-05-06 | 2020-05-06_e2d6602625_up_data_2020-05-06.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-05-06.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-05-06_e2d6602625_up_data_2020-05-06.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-05-06 | 2020-05-06_e2d6602:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-05-13 | 2020-05-13_b75e960e4f_up_data_2020-05-13.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-05-13.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-05-13_b75e960e4f_up_data_2020-05-13.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-05-13 | 2020-05-13_b75e960:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-05-20 | 2020-05-20_3347f0f2d2_up_data_2020-05-20.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-05-20.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-05-20_3347f0f2d2_up_data_2020-05-20.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-05-20 | 2020-05-20_3347f0f:   0%|          | 0.00/36.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-05-27 | 2020-05-27_caf6f28cc4_up_data_2020-05-27.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-05-27.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-05-27_caf6f28cc4_up_data_2020-05-27.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-05-27 | 2020-05-27_caf6f28:   0%|          | 0.00/39.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-04-01 | 2020-04-01_55150975df_up_data_2020-04-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-04-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-04-01_55150975df_up_data_2020-04-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-04-01 | 2020-04-01_5515097:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-04-08 | 2020-04-08_e1232fa4dc_up_data_2020-04-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-04-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-04-08_e1232fa4dc_up_data_2020-04-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-04-08 | 2020-04-08_e1232fa:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-04-15 | 2020-04-15_c27b976da3_up_data_2020-04-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-04-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-04-15_c27b976da3_up_data_2020-04-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-04-15 | 2020-04-15_c27b976:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-04-22 | 2020-04-22_29a03682d7_up_data_2020-04-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-04-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-04-22_29a03682d7_up_data_2020-04-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-04-22 | 2020-04-22_29a0368:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-04-29 | 2020-04-29_bf7ccb89ad_up_data_2020-04-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-04-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-04-29_bf7ccb89ad_up_data_2020-04-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-04-29 | 2020-04-29_bf7ccb8:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-03-04 | 2020-03-04_8762c91ab0_up_data_2020-03-04.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-03-04.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-03-04_8762c91ab0_up_data_2020-03-04.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-03-04 | 2020-03-04_8762c91:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-03-11 | 2020-03-11_15da7ddb3f_up_data_2020-03-11.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-03-11.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-03-11_15da7ddb3f_up_data_2020-03-11.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-03-11 | 2020-03-11_15da7dd:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-03-18 | 2020-03-18_72fb112302_up_data_2020-03-18.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-03-18.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-03-18_72fb112302_up_data_2020-03-18.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-03-18 | 2020-03-18_72fb112:   0%|          | 0.00/40.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-03-25 | 2020-03-25_bae4b9d870_up_data_2020-03-25.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-03-25.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-03-25_bae4b9d870_up_data_2020-03-25.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-03-25 | 2020-03-25_bae4b9d:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-02-05 | 2020-02-05_9b7c1402e2_up_data_2020-02-05.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-02-05.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-02-05_9b7c1402e2_up_data_2020-02-05.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-02-05 | 2020-02-05_9b7c140:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-02-12 | 2020-02-12_20d9cade9e_up_data_2020-02-12.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-02-12.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-02-12_20d9cade9e_up_data_2020-02-12.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-02-12 | 2020-02-12_20d9cad:   0%|          | 0.00/34.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-02-19 | 2020-02-19_674519228b_up_data_2020-02-19.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-02-19.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-02-19_674519228b_up_data_2020-02-19.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-02-19 | 2020-02-19_6745192:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-02-26 | 2020-02-26_5b93f7322c_up_data_2020-02-26.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-02-26.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-02-26_5b93f7322c_up_data_2020-02-26.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-02-26 | 2020-02-26_5b93f73:   0%|          | 0.00/34.8k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-01-01 | 2020-01-01_d6f050dda0_up_data_2020-01-01.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-01-01.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-01-01_d6f050dda0_up_data_2020-01-01.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-01-01 | 2020-01-01_d6f050d:   0%|          | 0.00/34.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-01-08 | 2020-01-08_cd60097aee_up_data_2020-01-08.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-01-08.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-01-08_cd60097aee_up_data_2020-01-08.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-01-08 | 2020-01-08_cd60097:   0%|          | 0.00/34.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-01-15 | 2020-01-15_435f25700e_up_data_2020-01-15.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-01-15.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-01-15_435f25700e_up_data_2020-01-15.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-01-15 | 2020-01-15_435f257:   0%|          | 0.00/34.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-01-22 | 2020-01-22_21fb904e49_up_data_2020-01-22.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-01-22.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-01-22_21fb904e49_up_data_2020-01-22.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-01-22 | 2020-01-22_21fb904:   0%|          | 0.00/34.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] weekly_service_report | up | 2020-01-29 | 2020-01-29_2a2aebb720_up_data_2020-01-29.xlsx
URL: https://www.stb.gov/wp-content/uploads/files/rsir/UP/up_data_2020-01-29.xlsx
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\weekly_service_files\up\2020\xlsx\2020-01-29_2a2aebb720_up_data_2020-01-29.xlsx
----------------------------------------------------------------------------------------------------

weekly_service_report | up | 2020-01-29 | 2020-01-29_2a2aebb:   0%|          | 0.00/40.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] stb_1145_csv | bnsf |  | 6104cf3ad4_STB-1145-BNSF.csv
URL: https://www.stb.gov/wp-content/uploads/STB-1145-BNSF.csv
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\stb_1145_csv\bnsf\6104cf3ad4_STB-1145-BNSF.csv
----------------------------------------------------------------------------------------------------

stb_1145_csv | bnsf |  | 6104cf3ad4_STB-1145-BNSF.csv:   0%|          | 0.00/16.4k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] stb_1145_csv | cpkc |  | 1189020d6c_STB-1145-CPKC.csv
URL: https://www.stb.gov/wp-content/uploads/STB-1145-CPKC.csv
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\stb_1145_csv\cpkc\1189020d6c_STB-1145-CPKC.csv
----------------------------------------------------------------------------------------------------

stb_1145_csv | cpkc |  | 1189020d6c_STB-1145-CPKC.csv:   0%|          | 0.00/14.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] stb_1145_csv | csx |  | f87b34edda_STB-1145-CSXT.csv
URL: https://www.stb.gov/wp-content/uploads/STB-1145-CSXT.csv
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\stb_1145_csv\csx\f87b34edda_STB-1145-CSXT.csv
----------------------------------------------------------------------------------------------------

stb_1145_csv | csx |  | f87b34edda_STB-1145-CSXT.csv:   0%|          | 0.00/15.5k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] stb_1145_csv | stb_1145_all |  | 966c50a9f5_STB-1145-GTC.csv
URL: https://www.stb.gov/wp-content/uploads/STB-1145-GTC.csv
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\stb_1145_csv\stb_1145_all\966c50a9f5_STB-1145-GTC.csv
----------------------------------------------------------------------------------------------------

stb_1145_csv | stb_1145_all |  | 966c50a9f5_STB-1145-GTC.csv:   0%|          | 0.00/12.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] stb_1145_csv | stb_1145_all |  | 72a4e4c9d0_STB-1145-NS.csv
URL: https://www.stb.gov/wp-content/uploads/STB-1145-NS.csv
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\stb_1145_csv\stb_1145_all\72a4e4c9d0_STB-1145-NS.csv
----------------------------------------------------------------------------------------------------

stb_1145_csv | stb_1145_all |  | 72a4e4c9d0_STB-1145-NS.csv:   0%|          | 0.00/15.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] stb_1145_csv | stb_1145_all |  | 9c19c4c693_STB-1145-UP.csv
URL: https://www.stb.gov/wp-content/uploads/STB-1145-UP.csv
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\stb_1145_csv\stb_1145_all\9c19c4c693_STB-1145-UP.csv
----------------------------------------------------------------------------------------------------

stb_1145_csv | stb_1145_all |  | 9c19c4c693_STB-1145-UP.csv:   0%|          | 0.00/18.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] stb_1145_csv | stb_1145_all |  | 406f4ee39a_STB-1145-ALL-CARRIERS.csv
URL: https://www.stb.gov/wp-content/uploads/STB-1145-ALL-CARRIERS.csv
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\stb_1145_csv\stb_1145_all\406f4ee39a_STB-1145-ALL-CARRIERS.csv
----------------------------------------------------------------------------------------------------

stb_1145_csv | stb_1145_all |  | 406f4ee39a_STB-1145-ALL-CAR:   0%|          | 0.00/1.07M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] methodology_doc | cpkc |  | 611b766fb5_CPKC-Methodology.pdf
URL: https://www.stb.gov/wp-content/uploads/CPKC-Methodology.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\methodology_docs\cpkc\611b766fb5_CPKC-Methodology.pdf
----------------------------------------------------------------------------------------------------

methodology_doc | cpkc |  | 611b766fb5_CPKC-Methodology.pdf:   0%|          | 0.00/214k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] methodology_doc | bnsf |  | f9b2d569a7_BNSF_Methodology.pdf
URL: https://www.stb.gov/wp-content/uploads/BNSF_Methodology.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\methodology_docs\bnsf\f9b2d569a7_BNSF_Methodology.pdf
----------------------------------------------------------------------------------------------------

methodology_doc | bnsf |  | f9b2d569a7_BNSF_Methodology.pdf:   0%|          | 0.00/916k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] methodology_doc | cn |  | 8c3b0f1209_CN_Methodology.pdf
URL: https://www.stb.gov/wp-content/uploads/CN_Methodology.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\methodology_docs\cn\8c3b0f1209_CN_Methodology.pdf
----------------------------------------------------------------------------------------------------

methodology_doc | cn |  | 8c3b0f1209_CN_Methodology.pdf:   0%|          | 0.00/238k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] methodology_doc | cp |  | 1ea65ffc30_CP_Methodology.pdf
URL: https://www.stb.gov/wp-content/uploads/CP_Methodology.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\methodology_docs\cp\1ea65ffc30_CP_Methodology.pdf
----------------------------------------------------------------------------------------------------

methodology_doc | cp |  | 1ea65ffc30_CP_Methodology.pdf:   0%|          | 0.00/170k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] methodology_doc | csx |  | 185929301e_CSX_Methodology.pdf
URL: https://www.stb.gov/wp-content/uploads/CSX_Methodology.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\methodology_docs\csx\185929301e_CSX_Methodology.pdf
----------------------------------------------------------------------------------------------------

methodology_doc | csx |  | 185929301e_CSX_Methodology.pdf:   0%|          | 0.00/133k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] methodology_doc | kcs |  | d014c61467_KCS_Methodology.pdf
URL: https://www.stb.gov/wp-content/uploads/KCS_Methodology.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\methodology_docs\kcs\d014c61467_KCS_Methodology.pdf
----------------------------------------------------------------------------------------------------

methodology_doc | kcs |  | d014c61467_KCS_Methodology.pdf:   0%|          | 0.00/25.6k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] methodology_doc | ns |  | 661424d3ec_NS_Methodology.pdf
URL: https://www.stb.gov/wp-content/uploads/NS_Methodology.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\methodology_docs\ns\661424d3ec_NS_Methodology.pdf
----------------------------------------------------------------------------------------------------

methodology_doc | ns |  | 661424d3ec_NS_Methodology.pdf:   0%|          | 0.00/172k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] methodology_doc | up |  | b752a4671b_UP-Methodology-EP-724-03.01.22.pdf
URL: https://www.stb.gov/wp-content/uploads/UP-Methodology-EP-724-03.01.22.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\methodology_docs\up\b752a4671b_UP-Methodology-EP-724-03.01.22.pdf
----------------------------------------------------------------------------------------------------

methodology_doc | up |  | b752a4671b_UP-Methodology-EP-724-0:   0%|          | 0.00/127k [00:00<?, ?B/s]

====================================================================================================
STB RAIL SERVICE PERFORMANCE DOWNLOAD COMPLETE
====================================================================================================
Root: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance
Full link inventory: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\_metadata\stb_rail_service_link_inventory.csv
Selected links: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\_metadata\stb_rail_service_selected_download_links.csv
Download manifest: E:\NetworkOptimization\pythonProject1\Data\00_manifest\stb_rail_service_download_manifest.csv
Download log: E:\NetworkOptimization\pythonProject1\Data\00_manifest\stb_rail_service_download_log.jsonl
Sheet preview: E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\_metadata\stb_rail_service_xlsx_sheet_preview.csv
====================================================================================================

,dataset_group,carrier_guess,year,ext,status,n_files
0,methodology_doc,bnsf,NaN,.pdf,downloaded_or_exists,1
1,methodology_doc,cn,NaN,.pdf,downloaded_or_exists,1
2,methodology_doc,cp,NaN,.pdf,downloaded_or_exists,1
3,methodology_doc,cpkc,NaN,.pdf,downloaded_or_exists,1
4,methodology_doc,csx,NaN,.pdf,downloaded_or_exists,1
...,...,...,...,...,...,...
65,weekly_service_report,up,2022.0,.xlsx,downloaded_or_exists,52
66,weekly_service_report,up,2023.0,.xlsx,downloaded_or_exists,52
67,weekly_service_report,up,2024.0,.xlsx,downloaded_or_exists,52
68,weekly_service_report,up,2025.0,.xlsx,downloaded_or_exists,53
69,weekly_service_report,up,2026.0,.xlsx,downloaded_or_exists,19

Failed files:

,dataset_group,carrier_guess,year,ext,url,out_path,error
1655,weekly_service_report,ctco,2020.0,.xlsx,https://www.stb.gov/wp-content/uploads/files/r...,E:\NetworkOptimization\pythonProject1\Data\04_...,RuntimeError('HTTP 404 while downloading https...

Downloaded / existing file count: 2624
Total size GB: 0.097

In [1]:
# ============================================================
# FREIGHT-MNet: Download NOAA Storm Events Database
#
# Scope:
#   3.6 NOAA Storm Events only
#
# Years:
#   2018–2024
#
# Source:
#   NOAA NCEI Storm Events bulk CSV directory
#
# Save root:
#   E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events
#
# Downloads per year:
#   1. StormEvents_details-ftp_v1.0_dYYYY_c*.csv.gz
#   2. StormEvents_locations-ftp_v1.0_dYYYY_c*.csv.gz
#   3. StormEvents_fatalities-ftp_v1.0_dYYYY_c*.csv.gz
#
# Also downloads:
#   - README
#   - Storm-Data-Bulk-csv-Format.pdf
#   - Storm-Data-Export-Format.pdf
#
# Resume behavior:
#   - If a .csv.gz file already exists and passes gzip validation, it is skipped.
#   - If a .parquet file already exists and passes basic validation, conversion is skipped.
#   - Manifest is saved after every file.
#   - If interrupted, rerun the same cell.
# ============================================================

from pathlib import Path
from urllib.parse import urljoin
import re
import json
import time
import gzip
import hashlib
import traceback

import requests
import pandas as pd
from bs4 import BeautifulSoup
from tqdm.auto import tqdm
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

try:
    import polars as pl
    HAS_POLARS = True
except Exception:
    HAS_POLARS = False

# ------------------------------------------------------------
# 0. Configuration
# ------------------------------------------------------------

DATA_ROOT = Path(r"E:\NetworkOptimization\pythonProject1\Data")
NOAA_ROOT = DATA_ROOT / "05_noaa_storm_events"
MANIFEST_ROOT = DATA_ROOT / "00_manifest"

# Core model years. Keep this at 2018-2024 to match FMI / FAF supervised window.
YEARS = list(range(2018, 2025))

NOAA_INDEX_URL = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/"

TABLE_TYPES = {
    "details": {
        "subdir": "details",
        "pattern_prefix": "StormEvents_details-ftp_v1.0_d",
    },
    "locations": {
        "subdir": "locations",
        "pattern_prefix": "StormEvents_locations-ftp_v1.0_d",
    },
    "fatalities": {
        "subdir": "fatalities",
        "pattern_prefix": "StormEvents_fatalities-ftp_v1.0_d",
    },
}

DOC_FILES = [
    "README",
    "Storm-Data-Bulk-csv-Format.pdf",
    "Storm-Data-Export-Format.pdf",
]

# Output folders.
MANIFEST_ROOT.mkdir(parents=True, exist_ok=True)
NOAA_ROOT.mkdir(parents=True, exist_ok=True)

DIRS = {
    "details": NOAA_ROOT / "details",
    "locations": NOAA_ROOT / "locations",
    "fatalities": NOAA_ROOT / "fatalities",
    "docs": NOAA_ROOT / "docs",
    "metadata": NOAA_ROOT / "_metadata",
    "parquet": NOAA_ROOT / "parquet",
    "preview": NOAA_ROOT / "preview",
}

for d in DIRS.values():
    d.mkdir(parents=True, exist_ok=True)

for table_type in TABLE_TYPES:
    (DIRS["parquet"] / table_type).mkdir(parents=True, exist_ok=True)
    (DIRS["preview"] / table_type).mkdir(parents=True, exist_ok=True)

MANIFEST_PATH = MANIFEST_ROOT / "noaa_storm_events_download_manifest.csv"
LOG_PATH = MANIFEST_ROOT / "noaa_storm_events_download_log.jsonl"
INDEX_SNAPSHOT_PATH = DIRS["metadata"] / "noaa_storm_events_index_snapshot.html"
LINK_INVENTORY_PATH = DIRS["metadata"] / "noaa_storm_events_link_inventory_2018_2024.csv"

# Behavior switches.
RESUME = True
CONVERT_TO_PARQUET = True
SAVE_PREVIEWS = True
COMPUTE_SHA256 = False

# Download settings.
CHUNK_SIZE = 1024 * 1024
SLEEP_BETWEEN_DOWNLOADS = 0.25

print("=" * 100)
print("NOAA Storm Events downloader")
print("DATA_ROOT:", DATA_ROOT)
print("NOAA_ROOT:", NOAA_ROOT)
print("YEARS:", YEARS)
print("HAS_POLARS:", HAS_POLARS)
print("=" * 100)

# ------------------------------------------------------------
# 1. HTTP session with retry
# ------------------------------------------------------------

session = requests.Session()
session.headers.update(
    {
        "User-Agent": (
            "FREIGHT-MNet academic research downloader "
            "(NOAA NCEI Storm Events bulk CSV files)"
        )
    }
)

retry = Retry(
    total=8,
    connect=8,
    read=8,
    status=8,
    backoff_factor=1.5,
    status_forcelist=[408, 429, 500, 502, 503, 504],
    allowed_methods=["GET", "HEAD"],
    raise_on_status=False,
)

adapter = HTTPAdapter(max_retries=retry, pool_connections=8, pool_maxsize=8)
session.mount("http://", adapter)
session.mount("https://", adapter)

# ------------------------------------------------------------
# 2. Helpers
# ------------------------------------------------------------

def log_event(record: dict) -> None:
    record = dict(record)
    record["timestamp"] = pd.Timestamp.now().isoformat()
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def file_size_mb(path: Path) -> float:
    path = Path(path)
    if not path.exists():
        return 0.0
    return round(path.stat().st_size / 1024**2, 4)


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        while True:
            b = f.read(chunk_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def looks_like_valid_gzip_csv(path: Path) -> bool:
    """
    Basic validation:
      - file exists and nonempty
      - gzip can open it
      - first line contains comma-separated header
    """
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False

    try:
        with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
            header = f.readline()
        return "," in header and len(header.strip()) > 5
    except Exception:
        return False


def looks_like_valid_pdf(path: Path) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False
    try:
        with path.open("rb") as f:
            return f.read(5) == b"%PDF-"
    except Exception:
        return False


def looks_like_valid_text(path: Path) -> bool:
    path = Path(path)
    return path.exists() and path.stat().st_size > 0


def looks_like_valid_parquet(path: Path) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False

    try:
        if HAS_POLARS:
            n = pl.scan_parquet(str(path)).select(pl.len()).collect().item()
            return n >= 0
        else:
            sample = pd.read_parquet(path)
            return sample.shape[1] > 0
    except Exception:
        return False


def download_file(url: str, out_path: Path, kind: str, label: str, overwrite: bool = False) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    def valid_existing() -> bool:
        if kind == "gzip_csv":
            return looks_like_valid_gzip_csv(out_path)
        if kind == "pdf":
            return looks_like_valid_pdf(out_path)
        if kind == "text":
            return looks_like_valid_text(out_path)
        return out_path.exists() and out_path.stat().st_size > 0

    if RESUME and out_path.exists() and not overwrite and valid_existing():
        print(f"[skip existing valid] {label}: {out_path.name} ({file_size_mb(out_path)} MB)")
        log_event(
            {
                "status": "exists_valid",
                "kind": kind,
                "url": url,
                "path": str(out_path),
                "size_mb": file_size_mb(out_path),
                "label": label,
            }
        )
        return out_path

    part_path = out_path.with_suffix(out_path.suffix + ".part")
    if part_path.exists():
        part_path.unlink()

    print("\n" + "-" * 100)
    print("[download]", label)
    print("URL:", url)
    print("OUT:", out_path)
    print("-" * 100)

    with session.get(url, stream=True, timeout=300) as r:
        if r.status_code >= 400:
            raise RuntimeError(f"HTTP {r.status_code} while downloading {url}\n{r.text[:500]}")

        total = int(r.headers.get("content-length", 0))
        with part_path.open("wb") as f, tqdm(
            total=total,
            unit="B",
            unit_scale=True,
            desc=label[:70],
        ) as pbar:
            for chunk in r.iter_content(chunk_size=CHUNK_SIZE):
                if chunk:
                    f.write(chunk)
                    pbar.update(len(chunk))

    part_path.replace(out_path)

    if not valid_existing():
        raise RuntimeError(f"Downloaded file did not pass validation: {out_path}")

    log_event(
        {
            "status": "downloaded",
            "kind": kind,
            "url": url,
            "path": str(out_path),
            "size_mb": file_size_mb(out_path),
            "label": label,
        }
    )

    return out_path


def fetch_index_html() -> str:
    r = session.get(NOAA_INDEX_URL, timeout=120)
    r.raise_for_status()
    html = r.text
    INDEX_SNAPSHOT_PATH.write_text(html, encoding="utf-8")
    return html


def parse_noaa_index(html: str) -> pd.DataFrame:
    """
    Parse NOAA HTTP directory listing and return all StormEvents files.
    """
    soup = BeautifulSoup(html, "html.parser")
    rows = []

    for a in soup.find_all("a", href=True):
        href = a["href"]
        filename = href.split("/")[-1]

        if not filename.startswith("StormEvents_"):
            continue
        if not filename.endswith(".csv.gz"):
            continue

        m = re.match(
            r"StormEvents_(details|locations|fatalities)-ftp_v1\.0_d(\d{4})_c(\d{8})\.csv\.gz",
            filename,
        )

        if not m:
            continue

        table_type, year, creation_date = m.groups()
        year = int(year)
        url = urljoin(NOAA_INDEX_URL, filename)

        rows.append(
            {
                "table_type": table_type,
                "year": year,
                "creation_date": creation_date,
                "filename": filename,
                "url": url,
            }
        )

    df = pd.DataFrame(rows)

    if df.empty:
        raise RuntimeError("No StormEvents CSV.GZ files were found in NOAA index.")

    df = df.sort_values(["table_type", "year", "creation_date"]).reset_index(drop=True)
    return df


def select_latest_files_for_years(inventory: pd.DataFrame, years: list[int]) -> pd.DataFrame:
    """
    NOAA may keep only one creation version per year, but this safely selects latest cYYYYMMDD.
    """
    subset = inventory[inventory["year"].isin(years)].copy()
    needed_rows = []

    for table_type in TABLE_TYPES:
        for year in years:
            candidates = subset[(subset["table_type"] == table_type) & (subset["year"] == year)].copy()
            if len(candidates) == 0:
                needed_rows.append(
                    {
                        "table_type": table_type,
                        "year": year,
                        "status": "missing_in_index",
                        "filename": None,
                        "url": None,
                    }
                )
                continue

            latest = candidates.sort_values("creation_date").iloc[-1].to_dict()
            latest["status"] = "selected"
            needed_rows.append(latest)

    selected = pd.DataFrame(needed_rows)
    return selected


def preview_gzip_csv(gz_path: Path, preview_path: Path, nrows: int = 20) -> dict:
    preview_path = Path(preview_path)
    preview_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        df = pd.read_csv(gz_path, compression="gzip", nrows=nrows, low_memory=False)
        df.to_csv(preview_path, index=False, encoding="utf-8-sig")

        schema_path = preview_path.with_name(preview_path.stem + "_schema.csv")
        schema = pd.DataFrame(
            {
                "column": df.columns,
                "preview_dtype": [str(t) for t in df.dtypes],
            }
        )
        schema.to_csv(schema_path, index=False, encoding="utf-8-sig")

        return {
            "preview_status": "ok",
            "preview_path": str(preview_path),
            "schema_path": str(schema_path),
            "n_preview_rows": len(df),
            "n_preview_columns": len(df.columns),
            "columns": "|".join(df.columns),
        }

    except Exception as e:
        return {
            "preview_status": "failed",
            "preview_error": repr(e),
        }


def convert_gzip_csv_to_parquet(gz_path: Path, parquet_path: Path, table_type: str, year: int) -> dict:
    parquet_path = Path(parquet_path)
    parquet_path.parent.mkdir(parents=True, exist_ok=True)

    if RESUME and looks_like_valid_parquet(parquet_path):
        print(f"[skip existing parquet] {parquet_path.name} ({file_size_mb(parquet_path)} MB)")

        try:
            if HAS_POLARS:
                n_rows = pl.scan_parquet(str(parquet_path)).select(pl.len()).collect().item()
                columns = pl.scan_parquet(str(parquet_path)).collect_schema().names()
            else:
                tmp = pd.read_parquet(parquet_path)
                n_rows = len(tmp)
                columns = list(tmp.columns)
        except Exception:
            n_rows = None
            columns = []

        return {
            "parquet_status": "exists_valid",
            "parquet_path": str(parquet_path),
            "parquet_size_mb": file_size_mb(parquet_path),
            "parquet_rows": n_rows,
            "parquet_columns": "|".join(columns),
        }

    print("\n" + "-" * 100)
    print(f"[convert] NOAA {table_type} {year}: CSV.GZ -> Parquet")
    print("GZ:", gz_path)
    print("PARQUET:", parquet_path)
    print("-" * 100)

    try:
        if HAS_POLARS:
            df = pl.read_csv(
                str(gz_path),
                infer_schema_length=10000,
                ignore_errors=True,
                try_parse_dates=False,
            )

            n_rows = df.height
            columns = df.columns
            tmp_path = parquet_path.with_suffix(".parquet.part")
            df.write_parquet(str(tmp_path), compression="zstd")
            tmp_path.replace(parquet_path)
            del df

        else:
            # Fallback: pandas full read. For 2018-2024 this should still be manageable.
            df = pd.read_csv(gz_path, compression="gzip", low_memory=False)
            n_rows = len(df)
            columns = list(df.columns)
            tmp_path = parquet_path.with_suffix(".parquet.part")
            df.to_parquet(tmp_path, index=False)
            tmp_path.replace(parquet_path)
            del df

        return {
            "parquet_status": "converted",
            "parquet_path": str(parquet_path),
            "parquet_size_mb": file_size_mb(parquet_path),
            "parquet_rows": n_rows,
            "parquet_columns": "|".join(columns),
        }

    except Exception as e:
        return {
            "parquet_status": "failed",
            "parquet_path": str(parquet_path),
            "parquet_error": repr(e),
            "parquet_traceback": traceback.format_exc()[:3000],
        }


# ------------------------------------------------------------
# 3. Scrape NOAA index and select latest files
# ------------------------------------------------------------

html = fetch_index_html()
inventory = parse_noaa_index(html)
inventory.to_csv(DIRS["metadata"] / "noaa_storm_events_full_index_inventory.csv", index=False, encoding="utf-8-sig")

selected = select_latest_files_for_years(inventory, YEARS)
selected.to_csv(LINK_INVENTORY_PATH, index=False, encoding="utf-8-sig")

print("\nNOAA selected files:")
display(selected)

missing = selected[selected["status"] != "selected"]
if len(missing) > 0:
    print("\nMissing files in NOAA index:")
    display(missing)
    raise RuntimeError("Some required NOAA files were missing from the index. See table above.")

# ------------------------------------------------------------
# 4. Download documentation
# ------------------------------------------------------------

doc_manifest_rows = []

for doc_name in DOC_FILES:
    url = urljoin(NOAA_INDEX_URL, doc_name)
    out_path = DIRS["docs"] / doc_name
    kind = "pdf" if doc_name.lower().endswith(".pdf") else "text"

    rec = {
        "record_type": "doc",
        "filename": doc_name,
        "url": url,
        "out_path": str(out_path),
    }

    try:
        p = download_file(url, out_path, kind=kind, label=f"NOAA doc {doc_name}")
        rec["status"] = "downloaded_or_exists"
        rec["size_mb"] = file_size_mb(p)
        if COMPUTE_SHA256:
            rec["sha256"] = sha256_file(p)

    except Exception as e:
        rec["status"] = "failed"
        rec["error"] = repr(e)
        rec["traceback"] = traceback.format_exc()[:3000]
        print(f"[doc failed] {doc_name}: {e}")

    doc_manifest_rows.append(rec)
    time.sleep(SLEEP_BETWEEN_DOWNLOADS)

# ------------------------------------------------------------
# 5. Download data files, preview, and convert to Parquet
# ------------------------------------------------------------

manifest_rows = []

# Load previous manifest if rerunning.
if RESUME and MANIFEST_PATH.exists():
    try:
        old = pd.read_csv(MANIFEST_PATH)
        # Keep previous docs and data rows; final drop_duplicates at end.
        manifest_rows = old.to_dict("records")
        print(f"Loaded previous manifest with {len(manifest_rows)} rows.")
    except Exception:
        manifest_rows = []

# Add docs to manifest.
manifest_rows.extend(doc_manifest_rows)

for _, row in tqdm(list(selected.iterrows()), total=len(selected), desc="Downloading NOAA Storm Events"):
    table_type = row["table_type"]
    year = int(row["year"])
    filename = row["filename"]
    url = row["url"]

    out_dir = DIRS[table_type]
    out_path = out_dir / filename

    preview_path = DIRS["preview"] / table_type / f"noaa_stormevents_{table_type}_{year}_preview_first20.csv"
    parquet_path = DIRS["parquet"] / table_type / f"noaa_stormevents_{table_type}_{year}.parquet"

    label = f"NOAA StormEvents {table_type} {year}"

    rec = {
        "record_type": "data",
        "table_type": table_type,
        "year": year,
        "creation_date": row["creation_date"],
        "filename": filename,
        "url": url,
        "out_path": str(out_path),
        "preview_path": str(preview_path),
        "parquet_path": str(parquet_path),
    }

    try:
        gz_path = download_file(url, out_path, kind="gzip_csv", label=label)
        rec["status"] = "downloaded_or_exists"
        rec["size_mb"] = file_size_mb(gz_path)

        if COMPUTE_SHA256:
            rec["sha256"] = sha256_file(gz_path)

        if SAVE_PREVIEWS:
            preview_info = preview_gzip_csv(gz_path, preview_path, nrows=20)
            rec.update(preview_info)

        if CONVERT_TO_PARQUET:
            parquet_info = convert_gzip_csv_to_parquet(gz_path, parquet_path, table_type, year)
            rec.update(parquet_info)

    except Exception as e:
        rec["status"] = "failed"
        rec["error"] = repr(e)
        rec["traceback"] = traceback.format_exc()[:4000]
        print(f"\n[FAILED] {label}: {e}")

    manifest_rows.append(rec)

    # Save progress after each file.
    pd.DataFrame(manifest_rows).drop_duplicates(
        subset=["record_type", "table_type", "year", "filename", "out_path"],
        keep="last",
    ).to_csv(MANIFEST_PATH, index=False, encoding="utf-8-sig")

    time.sleep(SLEEP_BETWEEN_DOWNLOADS)

# ------------------------------------------------------------
# 6. Final manifest and summary
# ------------------------------------------------------------

manifest = pd.DataFrame(manifest_rows)

# Drop exact duplicated records from reruns.
dedup_cols = [c for c in ["record_type", "table_type", "year", "filename", "out_path"] if c in manifest.columns]
if dedup_cols:
    manifest = manifest.drop_duplicates(subset=dedup_cols, keep="last").reset_index(drop=True)

manifest.to_csv(MANIFEST_PATH, index=False, encoding="utf-8-sig")

print("\n" + "=" * 100)
print("NOAA STORM EVENTS DOWNLOAD COMPLETE")
print("=" * 100)
print("NOAA_ROOT:", NOAA_ROOT)
print("Manifest:", MANIFEST_PATH)
print("Log:", LOG_PATH)
print("Index snapshot:", INDEX_SNAPSHOT_PATH)
print("Link inventory:", LINK_INVENTORY_PATH)
print("=" * 100)

data_manifest = manifest[manifest["record_type"] == "data"].copy()
doc_manifest = manifest[manifest["record_type"] == "doc"].copy()

print("\nData files summary:")
if len(data_manifest) > 0:
    cols = [
        "table_type",
        "year",
        "status",
        "size_mb",
        "preview_status",
        "parquet_status",
        "parquet_rows",
        "out_path",
        "parquet_path",
    ]
    cols = [c for c in cols if c in data_manifest.columns]
    display(data_manifest[cols].sort_values(["table_type", "year"]))

print("\nDocs summary:")
if len(doc_manifest) > 0:
    cols = ["filename", "status", "size_mb", "out_path"]
    cols = [c for c in cols if c in doc_manifest.columns]
    display(doc_manifest[cols])

failed = manifest[manifest["status"] == "failed"].copy()
if len(failed) > 0:
    print("\nFAILED records:")
    display(failed)
    raise RuntimeError("Some NOAA files failed. Rerun the cell to resume.")
else:
    print("\nAll selected NOAA Storm Events files are present.")

====================================================================================================
NOAA Storm Events downloader
DATA_ROOT: E:\NetworkOptimization\pythonProject1\Data
NOAA_ROOT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events
YEARS: [2018, 2019, 2020, 2021, 2022, 2023, 2024]
HAS_POLARS: False
====================================================================================================

NOAA selected files:

,table_type,year,creation_date,filename,url,status
0,details,2018,20260323,StormEvents_details-ftp_v1.0_d2018_c20260323.c...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
1,details,2019,20260323,StormEvents_details-ftp_v1.0_d2019_c20260323.c...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
2,details,2020,20260323,StormEvents_details-ftp_v1.0_d2020_c20260323.c...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
3,details,2021,20260323,StormEvents_details-ftp_v1.0_d2021_c20260323.c...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
4,details,2022,20260323,StormEvents_details-ftp_v1.0_d2022_c20260323.c...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
5,details,2023,20260323,StormEvents_details-ftp_v1.0_d2023_c20260323.c...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
6,details,2024,20260421,StormEvents_details-ftp_v1.0_d2024_c20260421.c...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
7,locations,2018,20260323,StormEvents_locations-ftp_v1.0_d2018_c20260323...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
8,locations,2019,20260323,StormEvents_locations-ftp_v1.0_d2019_c20260323...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
9,locations,2020,20260323,StormEvents_locations-ftp_v1.0_d2020_c20260323...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
10,locations,2021,20260323,StormEvents_locations-ftp_v1.0_d2021_c20260323...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
11,locations,2022,20260323,StormEvents_locations-ftp_v1.0_d2022_c20260323...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
12,locations,2023,20260323,StormEvents_locations-ftp_v1.0_d2023_c20260323...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
13,locations,2024,20260421,StormEvents_locations-ftp_v1.0_d2024_c20260421...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
14,fatalities,2018,20260323,StormEvents_fatalities-ftp_v1.0_d2018_c2026032...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
15,fatalities,2019,20260323,StormEvents_fatalities-ftp_v1.0_d2019_c2026032...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
16,fatalities,2020,20260323,StormEvents_fatalities-ftp_v1.0_d2020_c2026032...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
17,fatalities,2021,20260323,StormEvents_fatalities-ftp_v1.0_d2021_c2026032...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
18,fatalities,2022,20260323,StormEvents_fatalities-ftp_v1.0_d2022_c2026032...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
19,fatalities,2023,20260323,StormEvents_fatalities-ftp_v1.0_d2023_c2026032...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected
20,fatalities,2024,20260421,StormEvents_fatalities-ftp_v1.0_d2024_c2026042...,https://www.ncei.noaa.gov/pub/data/swdi/storme...,selected

----------------------------------------------------------------------------------------------------
[download] NOAA doc README
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/README
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\docs\README
----------------------------------------------------------------------------------------------------

NOAA doc README:   0%|          | 0.00/2.01k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] NOAA doc Storm-Data-Bulk-csv-Format.pdf
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/Storm-Data-Bulk-csv-Format.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\docs\Storm-Data-Bulk-csv-Format.pdf
----------------------------------------------------------------------------------------------------

NOAA doc Storm-Data-Bulk-csv-Format.pdf:   0%|          | 0.00/341k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[download] NOAA doc Storm-Data-Export-Format.pdf
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/Storm-Data-Export-Format.pdf
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\docs\Storm-Data-Export-Format.pdf
----------------------------------------------------------------------------------------------------

NOAA doc Storm-Data-Export-Format.pdf:   0%|          | 0.00/151k [00:00<?, ?B/s]

Downloading NOAA Storm Events:   0%|          | 0/21 [00:00<?, ?it/s]

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents details 2018
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2018_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2018_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents details 2018:   0%|          | 0.00/9.59M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA details 2018: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2018_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2018.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents details 2019
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2019_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2019_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents details 2019:   0%|          | 0.00/11.6M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA details 2019: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2019_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2019.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents details 2020
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2020_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2020_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents details 2020:   0%|          | 0.00/10.4M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA details 2020: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2020_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2020.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents details 2021
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2021_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2021_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents details 2021:   0%|          | 0.00/10.6M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA details 2021: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2021_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2021.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents details 2022
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2022_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2022_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents details 2022:   0%|          | 0.00/11.8M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA details 2022: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2022_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2022.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents details 2023
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2023_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2023_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents details 2023:   0%|          | 0.00/12.9M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA details 2023: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2023_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2023.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents details 2024
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2024_c20260421.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2024_c20260421.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents details 2024:   0%|          | 0.00/12.7M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA details 2024: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\details\StormEvents_details-ftp_v1.0_d2024_c20260421.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2024.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents locations 2018
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2018_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2018_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents locations 2018:   0%|          | 0.00/1.73M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA locations 2018: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2018_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\locations\noaa_stormevents_locations_2018.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents locations 2019
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2019_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2019_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents locations 2019:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA locations 2019: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2019_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\locations\noaa_stormevents_locations_2019.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents locations 2020
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2020_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2020_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents locations 2020:   0%|          | 0.00/1.49M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA locations 2020: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2020_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\locations\noaa_stormevents_locations_2020.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents locations 2021
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2021_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2021_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents locations 2021:   0%|          | 0.00/1.25M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA locations 2021: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2021_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\locations\noaa_stormevents_locations_2021.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents locations 2022
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2022_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2022_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents locations 2022:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA locations 2022: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2022_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\locations\noaa_stormevents_locations_2022.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents locations 2023
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2023_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2023_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents locations 2023:   0%|          | 0.00/1.03M [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA locations 2023: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2023_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\locations\noaa_stormevents_locations_2023.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents locations 2024
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2024_c20260421.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2024_c20260421.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents locations 2024:   0%|          | 0.00/984k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA locations 2024: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\locations\StormEvents_locations-ftp_v1.0_d2024_c20260421.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\locations\noaa_stormevents_locations_2024.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents fatalities 2018
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2018_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2018_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents fatalities 2018:   0%|          | 0.00/11.9k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA fatalities 2018: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2018_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\fatalities\noaa_stormevents_fatalities_2018.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents fatalities 2019
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2019_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2019_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents fatalities 2019:   0%|          | 0.00/9.49k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA fatalities 2019: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2019_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\fatalities\noaa_stormevents_fatalities_2019.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents fatalities 2020
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2020_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2020_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents fatalities 2020:   0%|          | 0.00/10.0k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA fatalities 2020: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2020_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\fatalities\noaa_stormevents_fatalities_2020.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents fatalities 2021
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2021_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2021_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents fatalities 2021:   0%|          | 0.00/13.3k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA fatalities 2021: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2021_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\fatalities\noaa_stormevents_fatalities_2021.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents fatalities 2022
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2022_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2022_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents fatalities 2022:   0%|          | 0.00/12.2k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA fatalities 2022: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2022_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\fatalities\noaa_stormevents_fatalities_2022.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents fatalities 2023
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2023_c20260323.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2023_c20260323.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents fatalities 2023:   0%|          | 0.00/14.7k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA fatalities 2023: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2023_c20260323.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\fatalities\noaa_stormevents_fatalities_2023.parquet
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
[download] NOAA StormEvents fatalities 2024
URL: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2024_c20260421.csv.gz
OUT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2024_c20260421.csv.gz
----------------------------------------------------------------------------------------------------

NOAA StormEvents fatalities 2024:   0%|          | 0.00/13.1k [00:00<?, ?B/s]

----------------------------------------------------------------------------------------------------
[convert] NOAA fatalities 2024: CSV.GZ -> Parquet
GZ: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\fatalities\StormEvents_fatalities-ftp_v1.0_d2024_c20260421.csv.gz
PARQUET: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\fatalities\noaa_stormevents_fatalities_2024.parquet
----------------------------------------------------------------------------------------------------

====================================================================================================
NOAA STORM EVENTS DOWNLOAD COMPLETE
====================================================================================================
NOAA_ROOT: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events
Manifest: E:\NetworkOptimization\pythonProject1\Data\00_manifest\noaa_storm_events_download_manifest.csv
Log: E:\NetworkOptimization\pythonProject1\Data\00_manifest\noaa_storm_events_download_log.jsonl
Index snapshot: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\_metadata\noaa_storm_events_index_snapshot.html
Link inventory: E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\_metadata\noaa_storm_events_link_inventory_2018_2024.csv
====================================================================================================

Data files summary:

,table_type,year,status,size_mb,preview_status,parquet_status,parquet_rows,out_path,parquet_path
3,details,2018.0,downloaded_or_exists,9.1419,ok,converted,62699.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
4,details,2019.0,downloaded_or_exists,11.0651,ok,converted,67864.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
5,details,2020.0,downloaded_or_exists,9.9608,ok,converted,61281.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
6,details,2021.0,downloaded_or_exists,10.0746,ok,converted,61389.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
7,details,2022.0,downloaded_or_exists,11.2718,ok,converted,69887.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
8,details,2023.0,downloaded_or_exists,12.2910,ok,converted,75593.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
9,details,2024.0,downloaded_or_exists,12.1054,ok,converted,69801.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
17,fatalities,2018.0,downloaded_or_exists,0.0114,ok,converted,1072.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
18,fatalities,2019.0,downloaded_or_exists,0.0091,ok,converted,733.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
19,fatalities,2020.0,downloaded_or_exists,0.0095,ok,converted,905.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
20,fatalities,2021.0,downloaded_or_exists,0.0127,ok,converted,1266.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
21,fatalities,2022.0,downloaded_or_exists,0.0116,ok,converted,1223.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
22,fatalities,2023.0,downloaded_or_exists,0.0141,ok,converted,1466.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
23,fatalities,2024.0,downloaded_or_exists,0.0125,ok,converted,1141.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
10,locations,2018.0,downloaded_or_exists,1.6530,ok,converted,73123.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
11,locations,2019.0,downloaded_or_exists,1.7126,ok,converted,76338.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
12,locations,2020.0,downloaded_or_exists,1.4168,ok,converted,62421.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
13,locations,2021.0,downloaded_or_exists,1.1936,ok,converted,52192.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
14,locations,2022.0,downloaded_or_exists,1.0891,ok,converted,47530.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
15,locations,2023.0,downloaded_or_exists,0.9780,ok,converted,43572.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...
16,locations,2024.0,downloaded_or_exists,0.9383,ok,converted,41603.0,E:\NetworkOptimization\pythonProject1\Data\05_...,E:\NetworkOptimization\pythonProject1\Data\05_...

Docs summary:

,filename,status,size_mb,out_path
0,README,downloaded_or_exists,0.0019,E:\NetworkOptimization\pythonProject1\Data\05_...
1,Storm-Data-Bulk-csv-Format.pdf,downloaded_or_exists,0.3254,E:\NetworkOptimization\pythonProject1\Data\05_...
2,Storm-Data-Export-Format.pdf,downloaded_or_exists,0.1436,E:\NetworkOptimization\pythonProject1\Data\05_...

All selected NOAA Storm Events files are present.

In [2]:
# ============================================================
# FREIGHT-MNet: Download BTS Border Crossing Entry Data
#
# Scope:
#   3.7 BTS Border Crossing Entry Data only
#
# Source:
#   BTS / DOT Socrata dataset: keg4-3bc2
#
# Save root:
#   E:\NetworkOptimization\pythonProject1\Data\06_border_crossing
#
# What this cell produces:
#   1. Full raw CSV snapshot
#   2. Full raw Parquet snapshot
#   3. Resumable Socrata API chunk CSV files
#   4. Resumable Socrata API chunk Parquet files
#   5. Metadata JSON
#   6. Columns JSON + columns CSV
#   7. Preview CSV
#   8. Measure inventory
#   9. Core 2018–2024 freight subset:
#        truck / truck container / rail / train measures
#
# Resume behavior:
#   - Existing valid files are skipped.
#   - Existing valid chunks are skipped.
#   - If interrupted, rerun this same cell.
# ============================================================

from pathlib import Path
from urllib.parse import urljoin
import json
import time
import hashlib
import traceback
import math
import re

import requests
import pandas as pd
from tqdm.auto import tqdm
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

try:
    import polars as pl
    HAS_POLARS = True
except Exception:
    HAS_POLARS = False

# ------------------------------------------------------------
# 0. Configuration
# ------------------------------------------------------------

DATA_ROOT = Path(r"E:\NetworkOptimization\pythonProject1\Data")
BORDER_ROOT = DATA_ROOT / "06_border_crossing"
MANIFEST_ROOT = DATA_ROOT / "00_manifest"

DATASET_ID = "keg4-3bc2"

# Try BTS domain first, then DOT transportation domain.
SOCRATA_DOMAINS = [
    "https://data.bts.gov",
    "https://data.transportation.gov",
]

# Main modeling window. Raw full dataset is downloaded; this window is used for processed subset.
CORE_YEARS = list(range(2018, 2025))

# Chunk size for Socrata API paging.
# Dataset is not huge, but chunking gives true resume behavior.
CHUNK_SIZE = 50_000

# Behavior switches.
RESUME = True
DOWNLOAD_FULL_SNAPSHOT = True
DOWNLOAD_CHUNKS = True
CONVERT_TO_PARQUET = True
SAVE_CORE_2018_2024_FREIGHT_SUBSET = True
COMPUTE_SHA256 = False

# Folders.
DIRS = {
    "metadata": BORDER_ROOT / "_metadata",
    "raw_full": BORDER_ROOT / "raw_full_snapshot",
    "chunks_csv": BORDER_ROOT / "chunks_csv",
    "chunks_parquet": BORDER_ROOT / "chunks_parquet",
    "parquet": BORDER_ROOT / "parquet",
    "preview": BORDER_ROOT / "preview",
    "processed": BORDER_ROOT / "processed",
}

for d in DIRS.values():
    d.mkdir(parents=True, exist_ok=True)

MANIFEST_ROOT.mkdir(parents=True, exist_ok=True)

MANIFEST_PATH = MANIFEST_ROOT / "bts_border_crossing_download_manifest.csv"
LOG_PATH = MANIFEST_ROOT / "bts_border_crossing_download_log.jsonl"

FULL_CSV_PATH = DIRS["raw_full"] / f"border_crossing_entry_data_{DATASET_ID}_full.csv"
FULL_PARQUET_PATH = DIRS["parquet"] / f"border_crossing_entry_data_{DATASET_ID}_full.parquet"

METADATA_JSON_PATH = DIRS["metadata"] / f"border_crossing_entry_data_{DATASET_ID}_metadata.json"
COLUMNS_JSON_PATH = DIRS["metadata"] / f"border_crossing_entry_data_{DATASET_ID}_columns.json"
COLUMNS_CSV_PATH = DIRS["metadata"] / f"border_crossing_entry_data_{DATASET_ID}_columns.csv"
SOURCE_INFO_PATH = DIRS["metadata"] / f"border_crossing_entry_data_{DATASET_ID}_source_info.json"

PREVIEW_PATH = DIRS["preview"] / f"border_crossing_entry_data_{DATASET_ID}_preview_first50.csv"
MEASURE_INVENTORY_PATH = DIRS["processed"] / "border_crossing_measure_inventory.csv"
CORE_FREIGHT_PARQUET_PATH = DIRS["processed"] / "border_crossing_freight_measures_2018_2024.parquet"
CORE_FREIGHT_CSV_PATH = DIRS["processed"] / "border_crossing_freight_measures_2018_2024.csv"
MONTHLY_GATEWAY_PIVOT_PATH = DIRS["processed"] / "border_crossing_gateway_monthly_pivot_2018_2024.parquet"

print("=" * 100)
print("BTS Border Crossing Entry Data downloader")
print("DATA_ROOT:", DATA_ROOT)
print("BORDER_ROOT:", BORDER_ROOT)
print("DATASET_ID:", DATASET_ID)
print("CORE_YEARS:", CORE_YEARS)
print("HAS_POLARS:", HAS_POLARS)
print("=" * 100)

# ------------------------------------------------------------
# 1. HTTP session with retry
# ------------------------------------------------------------

session = requests.Session()
session.headers.update(
    {
        "User-Agent": (
            "FREIGHT-MNet academic research downloader "
            "(BTS Border Crossing Entry Data)"
        )
    }
)

retry = Retry(
    total=8,
    connect=8,
    read=8,
    status=8,
    backoff_factor=1.5,
    status_forcelist=[408, 429, 500, 502, 503, 504],
    allowed_methods=["GET", "HEAD"],
    raise_on_status=False,
)

adapter = HTTPAdapter(max_retries=retry, pool_connections=8, pool_maxsize=8)
session.mount("http://", adapter)
session.mount("https://", adapter)

# ------------------------------------------------------------
# 2. Helper functions
# ------------------------------------------------------------

def log_event(record: dict) -> None:
    record = dict(record)
    record["timestamp"] = pd.Timestamp.now().isoformat()
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


def file_size_mb(path: Path) -> float:
    path = Path(path)
    if not path.exists():
        return 0.0
    return round(path.stat().st_size / 1024**2, 4)


def sha256_file(path: Path, chunk_size: int = 1024 * 1024) -> str:
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        while True:
            b = f.read(chunk_size)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def request_json(url: str, params: dict | None = None, timeout: int = 180):
    r = session.get(url, params=params, timeout=timeout)
    if r.status_code >= 400:
        raise RuntimeError(f"HTTP {r.status_code}: {r.text[:500]}")
    return r.json()


def build_urls(domain: str) -> dict:
    return {
        "domain": domain,
        "landing": f"{domain}/d/{DATASET_ID}",
        "metadata": f"{domain}/api/views/{DATASET_ID}.json",
        "columns": f"{domain}/api/views/{DATASET_ID}/columns.json",
        "full_csv": f"{domain}/api/views/{DATASET_ID}/rows.csv?accessType=DOWNLOAD",
        "resource_csv": f"{domain}/resource/{DATASET_ID}.csv",
        "resource_json": f"{domain}/resource/{DATASET_ID}.json",
        "count": f"{domain}/resource/{DATASET_ID}.json?$select=count(*)",
    }


def choose_working_domain() -> dict:
    last_error = None

    for domain in SOCRATA_DOMAINS:
        urls = build_urls(domain)
        try:
            meta = request_json(urls["metadata"], timeout=120)
            if isinstance(meta, dict) and meta.get("id") == DATASET_ID:
                print("[OK] Working Socrata domain:", domain)
                return urls
        except Exception as e:
            last_error = repr(e)
            print("[WARN] domain failed:", domain, last_error)

    raise RuntimeError(f"No working Socrata domain found for {DATASET_ID}. Last error: {last_error}")


def looks_like_valid_csv(path: Path, min_rows: int = 1) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False
    try:
        df = pd.read_csv(path, nrows=min(5, max(min_rows, 1)))
        return df.shape[1] > 0
    except Exception:
        return False


def looks_like_valid_parquet(path: Path) -> bool:
    path = Path(path)
    if not path.exists() or path.stat().st_size <= 0:
        return False
    try:
        if HAS_POLARS:
            _ = pl.scan_parquet(str(path)).select(pl.len()).collect().item()
        else:
            _ = pd.read_parquet(path)
        return True
    except Exception:
        return False


def download_streaming_csv(url: str, out_path: Path, label: str, overwrite: bool = False) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if RESUME and out_path.exists() and not overwrite and looks_like_valid_csv(out_path):
        print(f"[skip existing valid] {label}: {out_path.name} ({file_size_mb(out_path)} MB)")
        log_event({
            "status": "exists_valid",
            "url": url,
            "path": str(out_path),
            "size_mb": file_size_mb(out_path),
            "label": label,
        })
        return out_path

    part_path = out_path.with_suffix(out_path.suffix + ".part")
    if part_path.exists():
        part_path.unlink()

    print("\n" + "-" * 100)
    print("[download]", label)
    print("URL:", url)
    print("OUT:", out_path)
    print("-" * 100)

    with session.get(url, stream=True, timeout=300) as r:
        if r.status_code >= 400:
            raise RuntimeError(f"HTTP {r.status_code} while downloading {url}\n{r.text[:500]}")

        total = int(r.headers.get("content-length", 0))
        with part_path.open("wb") as f, tqdm(
            total=total,
            unit="B",
            unit_scale=True,
            desc=label[:70],
        ) as pbar:
            for chunk in r.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    f.write(chunk)
                    pbar.update(len(chunk))

    part_path.replace(out_path)

    if not looks_like_valid_csv(out_path):
        raise RuntimeError(f"Downloaded file did not pass CSV validation: {out_path}")

    log_event({
        "status": "downloaded",
        "url": url,
        "path": str(out_path),
        "size_mb": file_size_mb(out_path),
        "label": label,
    })

    return out_path


def get_socrata_count(count_url: str) -> int:
    data = request_json(count_url, timeout=180)
    if isinstance(data, list) and len(data) > 0:
        first = data[0]
        if "count" in first:
            return int(first["count"])
        return int(list(first.values())[0])
    raise RuntimeError(f"Could not parse row count from response: {data}")


def save_metadata_and_columns(urls: dict) -> tuple[pd.DataFrame, dict]:
    metadata = request_json(urls["metadata"], timeout=120)
    columns = request_json(urls["columns"], timeout=120)

    METADATA_JSON_PATH.write_text(json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8")
    COLUMNS_JSON_PATH.write_text(json.dumps(columns, indent=2, ensure_ascii=False), encoding="utf-8")

    col_rows = []
    for c in columns:
        col_rows.append({
            "name": c.get("name"),
            "fieldName": c.get("fieldName"),
            "dataTypeName": c.get("dataTypeName"),
            "description": c.get("description"),
            "position": c.get("position"),
        })

    columns_df = pd.DataFrame(col_rows)
    columns_df.to_csv(COLUMNS_CSV_PATH, index=False, encoding="utf-8-sig")

    source_info = {
        "dataset_id": DATASET_ID,
        "domain": urls["domain"],
        "landing": urls["landing"],
        "metadata_url": urls["metadata"],
        "columns_url": urls["columns"],
        "full_csv_url": urls["full_csv"],
        "resource_csv_url": urls["resource_csv"],
        "metadata_name": metadata.get("name"),
        "metadata_description": metadata.get("description"),
        "metadata_rowsUpdatedAt": metadata.get("rowsUpdatedAt"),
        "metadata_viewLastModified": metadata.get("viewLastModified"),
        "metadata_totalTimesRated": metadata.get("totalTimesRated"),
    }
    SOURCE_INFO_PATH.write_text(json.dumps(source_info, indent=2, ensure_ascii=False), encoding="utf-8")

    print("[metadata saved]", METADATA_JSON_PATH)
    print("[columns saved]", COLUMNS_CSV_PATH)

    return columns_df, metadata


def infer_order_by_columns(columns_df: pd.DataFrame) -> str | None:
    """
    Build a stable-ish Socrata order-by clause from available field names.
    We do not assume the exact schema; we detect common field names.
    """
    field_names = set(columns_df["fieldName"].dropna().astype(str).tolist())

    preferred = [
        "date",
        "port_code",
        "port_name",
        "border",
        "state",
        "measure",
        "value",
    ]

    available = [c for c in preferred if c in field_names]

    if available:
        return ", ".join(available)

    # Fallback: use first few columns.
    fallback = list(field_names)[:3]
    if fallback:
        return ", ".join(fallback)

    return None


def query_chunk_csv(resource_csv_url: str, out_path: Path, limit: int, offset: int, order_by: str | None) -> dict:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if RESUME and looks_like_valid_csv(out_path):
        n_rows = len(pd.read_csv(out_path))
        return {
            "status": "exists_valid",
            "offset": offset,
            "limit": limit,
            "path": str(out_path),
            "n_rows": n_rows,
            "size_mb": file_size_mb(out_path),
        }

    params = {
        "$limit": limit,
        "$offset": offset,
    }

    if order_by:
        params["$order"] = order_by

    print(f"[chunk] offset={offset:,}, limit={limit:,}")

    r = session.get(resource_csv_url, params=params, timeout=300)

    if r.status_code >= 400:
        # If order-by caused an error, retry without order.
        if order_by:
            print(f"[warn] chunk query failed with order_by={order_by!r}; retrying without order.")
            params.pop("$order", None)
            r = session.get(resource_csv_url, params=params, timeout=300)

    if r.status_code >= 400:
        raise RuntimeError(f"HTTP {r.status_code}: {r.text[:500]}")

    part_path = out_path.with_suffix(out_path.suffix + ".part")
    part_path.write_bytes(r.content)
    part_path.replace(out_path)

    if not looks_like_valid_csv(out_path):
        raise RuntimeError(f"Chunk does not look like valid CSV: {out_path}")

    n_rows = len(pd.read_csv(out_path))

    return {
        "status": "downloaded",
        "offset": offset,
        "limit": limit,
        "path": str(out_path),
        "n_rows": n_rows,
        "size_mb": file_size_mb(out_path),
    }


def csv_to_parquet(csv_path: Path, parquet_path: Path) -> dict:
    parquet_path = Path(parquet_path)
    parquet_path.parent.mkdir(parents=True, exist_ok=True)

    if RESUME and looks_like_valid_parquet(parquet_path):
        if HAS_POLARS:
            n_rows = pl.scan_parquet(str(parquet_path)).select(pl.len()).collect().item()
        else:
            n_rows = len(pd.read_parquet(parquet_path))

        return {
            "parquet_status": "exists_valid",
            "parquet_path": str(parquet_path),
            "parquet_size_mb": file_size_mb(parquet_path),
            "parquet_rows": n_rows,
        }

    if HAS_POLARS:
        df = pl.read_csv(str(csv_path), infer_schema_length=10000, ignore_errors=True)
        n_rows = df.height
        tmp = parquet_path.with_suffix(".parquet.part")
        df.write_parquet(str(tmp), compression="zstd")
        tmp.replace(parquet_path)
        del df
    else:
        df = pd.read_csv(csv_path, low_memory=False)
        n_rows = len(df)
        tmp = parquet_path.with_suffix(".parquet.part")
        df.to_parquet(tmp, index=False)
        tmp.replace(parquet_path)
        del df

    return {
        "parquet_status": "converted",
        "parquet_path": str(parquet_path),
        "parquet_size_mb": file_size_mb(parquet_path),
        "parquet_rows": n_rows,
    }


def combine_chunks_to_dataframe(chunk_paths: list[Path]) -> pd.DataFrame:
    dfs = []
    for p in tqdm(chunk_paths, desc="Reading chunks"):
        dfs.append(pd.read_csv(p, low_memory=False))
    if not dfs:
        return pd.DataFrame()
    return pd.concat(dfs, ignore_index=True)


def normalize_column_lookup(df: pd.DataFrame) -> dict:
    return {c.lower().strip(): c for c in df.columns}


def find_col(df: pd.DataFrame, candidates: list[str]) -> str | None:
    lookup = normalize_column_lookup(df)
    for c in candidates:
        if c.lower() in lookup:
            return lookup[c.lower()]

    # Fuzzy fallback.
    norm = {re.sub(r"[^a-z0-9]+", "", k): v for k, v in lookup.items()}
    for c in candidates:
        key = re.sub(r"[^a-z0-9]+", "", c.lower())
        if key in norm:
            return norm[key]

    return None


def build_processed_outputs(full_df: pd.DataFrame) -> dict:
    """
    Creates:
      - measure inventory
      - 2018-2024 freight-only subset
      - monthly gateway pivot
    """
    result = {}

    if full_df.empty:
        return {"processed_status": "failed_empty_dataframe"}

    date_col = find_col(full_df, ["date", "Date"])
    measure_col = find_col(full_df, ["measure", "Measure"])
    value_col = find_col(full_df, ["value", "Value"])
    port_col = find_col(full_df, ["port_name", "Port Name", "Port"])
    state_col = find_col(full_df, ["state", "State"])
    border_col = find_col(full_df, ["border", "Border"])
    port_code_col = find_col(full_df, ["port_code", "Port Code"])

    required_cols = {
        "date": date_col,
        "measure": measure_col,
        "value": value_col,
    }

    missing_required = [k for k, v in required_cols.items() if v is None]
    if missing_required:
        return {
            "processed_status": "failed_missing_required_columns",
            "missing_required": missing_required,
            "available_columns": list(full_df.columns),
        }

    df = full_df.copy()

    df["_date"] = pd.to_datetime(df[date_col], errors="coerce")
    df["_year"] = df["_date"].dt.year
    df["_month"] = df["_date"].dt.month
    df["_value_numeric"] = pd.to_numeric(df[value_col], errors="coerce")

    # Measure inventory.
    measure_inventory = (
        df.groupby(measure_col, dropna=False)
        .agg(
            n_rows=(measure_col, "size"),
            min_year=("_year", "min"),
            max_year=("_year", "max"),
            total_value=("_value_numeric", "sum"),
        )
        .reset_index()
        .sort_values("n_rows", ascending=False)
    )
    measure_inventory.to_csv(MEASURE_INVENTORY_PATH, index=False, encoding="utf-8-sig")

    # Freight-relevant measures:
    # Keep trucks, truck containers, trains, rail containers.
    # Exclude passengers / pedestrians / personal vehicles / buses where possible.
    measure_text = df[measure_col].astype(str).str.lower()

    freight_mask = (
        measure_text.str.contains("truck", regex=False)
        | measure_text.str.contains("train", regex=False)
        | measure_text.str.contains("rail", regex=False)
    )

    exclude_mask = (
        measure_text.str.contains("passenger", regex=False)
        | measure_text.str.contains("pedestrian", regex=False)
        | measure_text.str.contains("bus", regex=False)
        | measure_text.str.contains("personal", regex=False)
        | measure_text.str.contains("privately owned", regex=False)
        | measure_text.str.contains("pov", regex=False)
    )

    core = df[
        df["_year"].isin(CORE_YEARS)
        & freight_mask
        & (~exclude_mask)
    ].copy()

    # Keep important columns plus any available location columns.
    keep_cols = []
    for c in [
        date_col,
        port_col,
        port_code_col,
        state_col,
        border_col,
        measure_col,
        value_col,
        "_date",
        "_year",
        "_month",
        "_value_numeric",
    ]:
        if c is not None and c not in keep_cols:
            keep_cols.append(c)

    # Add lat/lon if present.
    for c in ["latitude", "Latitude", "lat", "longitude", "Longitude", "lon", "Point", "point"]:
        fc = find_col(df, [c])
        if fc is not None and fc not in keep_cols:
            keep_cols.append(fc)

    core = core[keep_cols].copy()

    # Save core freight subset.
    core.to_csv(CORE_FREIGHT_CSV_PATH, index=False, encoding="utf-8-sig")
    core.to_parquet(CORE_FREIGHT_PARQUET_PATH, index=False)

    result["measure_inventory_path"] = str(MEASURE_INVENTORY_PATH)
    result["core_freight_csv_path"] = str(CORE_FREIGHT_CSV_PATH)
    result["core_freight_parquet_path"] = str(CORE_FREIGHT_PARQUET_PATH)
    result["core_freight_rows"] = len(core)

    # Create port-month-measure pivot if location columns exist.
    pivot_index = []
    for c in [date_col, port_col, port_code_col, state_col, border_col, "_year", "_month"]:
        if c is not None and c in core.columns and c not in pivot_index:
            pivot_index.append(c)

    if measure_col in core.columns and "_value_numeric" in core.columns and pivot_index:
        pivot = (
            core.pivot_table(
                index=pivot_index,
                columns=measure_col,
                values="_value_numeric",
                aggfunc="sum",
                fill_value=0,
            )
            .reset_index()
        )

        # Flatten columns.
        pivot.columns = [str(c).strip().replace(" ", "_").lower() for c in pivot.columns]
        pivot.to_parquet(MONTHLY_GATEWAY_PIVOT_PATH, index=False)

        result["monthly_gateway_pivot_path"] = str(MONTHLY_GATEWAY_PIVOT_PATH)
        result["monthly_gateway_pivot_rows"] = len(pivot)

    result["processed_status"] = "ok"
    return result


# ------------------------------------------------------------
# 3. Choose domain, save metadata, get count
# ------------------------------------------------------------

urls = choose_working_domain()
columns_df, metadata = save_metadata_and_columns(urls)

row_count = get_socrata_count(urls["count"])
print("Socrata row count:", row_count)

order_by = infer_order_by_columns(columns_df)
print("Order by clause:", order_by)

source_info = json.loads(SOURCE_INFO_PATH.read_text(encoding="utf-8"))
source_info.update({
    "row_count_from_socrata_api": row_count,
    "order_by_clause_used_for_chunks": order_by,
    "core_years_for_processed_subset": CORE_YEARS,
})
SOURCE_INFO_PATH.write_text(json.dumps(source_info, indent=2, ensure_ascii=False), encoding="utf-8")

# ------------------------------------------------------------
# 4. Download full raw CSV snapshot
# ------------------------------------------------------------

manifest_rows = []

if RESUME and MANIFEST_PATH.exists():
    try:
        old_manifest = pd.read_csv(MANIFEST_PATH)
        manifest_rows = old_manifest.to_dict("records")
        print(f"Loaded previous manifest with {len(manifest_rows)} rows.")
    except Exception:
        manifest_rows = []

if DOWNLOAD_FULL_SNAPSHOT:
    rec = {
        "record_type": "full_snapshot",
        "dataset_id": DATASET_ID,
        "url": urls["full_csv"],
        "out_path": str(FULL_CSV_PATH),
    }

    try:
        p = download_streaming_csv(urls["full_csv"], FULL_CSV_PATH, label="BTS Border Crossing full CSV snapshot")
        rec["status"] = "downloaded_or_exists"
        rec["size_mb"] = file_size_mb(p)
        if COMPUTE_SHA256:
            rec["sha256"] = sha256_file(p)

        # Save preview.
        preview = pd.read_csv(p, nrows=50, low_memory=False)
        preview.to_csv(PREVIEW_PATH, index=False, encoding="utf-8-sig")
        rec["preview_path"] = str(PREVIEW_PATH)
        rec["preview_columns"] = "|".join(preview.columns)

        # Convert full snapshot to Parquet.
        if CONVERT_TO_PARQUET:
            pq_info = csv_to_parquet(p, FULL_PARQUET_PATH)
            rec.update(pq_info)

    except Exception as e:
        rec["status"] = "failed"
        rec["error"] = repr(e)
        rec["traceback"] = traceback.format_exc()[:4000]
        print("[FAILED] full snapshot:", e)

    manifest_rows.append(rec)
    pd.DataFrame(manifest_rows).to_csv(MANIFEST_PATH, index=False, encoding="utf-8-sig")

# ------------------------------------------------------------
# 5. Download resumable API chunks
# ------------------------------------------------------------

chunk_records = []

if DOWNLOAD_CHUNKS:
    offsets = list(range(0, row_count, CHUNK_SIZE))

    for offset in tqdm(offsets, desc="Downloading Socrata chunks"):
        chunk_idx = offset // CHUNK_SIZE
        chunk_csv_path = DIRS["chunks_csv"] / f"border_crossing_{DATASET_ID}_chunk_{chunk_idx:05d}_offset_{offset}.csv"
        chunk_parquet_path = DIRS["chunks_parquet"] / f"border_crossing_{DATASET_ID}_chunk_{chunk_idx:05d}_offset_{offset}.parquet"

        rec = {
            "record_type": "chunk",
            "dataset_id": DATASET_ID,
            "chunk_idx": chunk_idx,
            "offset": offset,
            "limit": CHUNK_SIZE,
            "csv_path": str(chunk_csv_path),
            "parquet_path": str(chunk_parquet_path),
        }

        try:
            chunk_info = query_chunk_csv(
                resource_csv_url=urls["resource_csv"],
                out_path=chunk_csv_path,
                limit=CHUNK_SIZE,
                offset=offset,
                order_by=order_by,
            )
            rec.update(chunk_info)

            if CONVERT_TO_PARQUET:
                pq_info = csv_to_parquet(chunk_csv_path, chunk_parquet_path)
                rec.update(pq_info)

        except Exception as e:
            rec["status"] = "failed"
            rec["error"] = repr(e)
            rec["traceback"] = traceback.format_exc()[:3000]
            print(f"[FAILED] chunk offset={offset}: {e}")

        chunk_records.append(rec)

        # Save progress after every chunk.
        all_rows = manifest_rows + chunk_records
        pd.DataFrame(all_rows).to_csv(MANIFEST_PATH, index=False, encoding="utf-8-sig")

        time.sleep(0.15)

# ------------------------------------------------------------
# 6. Build processed outputs
# ------------------------------------------------------------

processed_rec = {
    "record_type": "processed",
    "dataset_id": DATASET_ID,
}

try:
    # Prefer full snapshot if it exists. Otherwise combine chunks.
    if FULL_CSV_PATH.exists() and looks_like_valid_csv(FULL_CSV_PATH):
        full_df = pd.read_csv(FULL_CSV_PATH, low_memory=False)
        processed_rec["source_used_for_processing"] = str(FULL_CSV_PATH)
    else:
        chunk_paths = sorted(DIRS["chunks_csv"].glob(f"border_crossing_{DATASET_ID}_chunk_*.csv"))
        full_df = combine_chunks_to_dataframe(chunk_paths)
        processed_rec["source_used_for_processing"] = "chunks_csv"

    processed_rec["full_rows_loaded_for_processing"] = len(full_df)
    processed_rec["full_columns"] = "|".join(full_df.columns)

    if SAVE_CORE_2018_2024_FREIGHT_SUBSET:
        processed_info = build_processed_outputs(full_df)
        processed_rec.update(processed_info)

except Exception as e:
    processed_rec["status"] = "failed"
    processed_rec["error"] = repr(e)
    processed_rec["traceback"] = traceback.format_exc()[:4000]
    print("[FAILED] processed outputs:", e)

manifest_rows = manifest_rows + chunk_records + [processed_rec]

manifest = pd.DataFrame(manifest_rows)

# Deduplicate reruns.
dedup_cols = [c for c in ["record_type", "dataset_id", "url", "out_path", "chunk_idx", "csv_path"] if c in manifest.columns]
if dedup_cols:
    manifest = manifest.drop_duplicates(subset=dedup_cols, keep="last").reset_index(drop=True)

manifest.to_csv(MANIFEST_PATH, index=False, encoding="utf-8-sig")

# ------------------------------------------------------------
# 7. Final summary
# ------------------------------------------------------------

print("\n" + "=" * 100)
print("BTS BORDER CROSSING ENTRY DATA DOWNLOAD COMPLETE")
print("=" * 100)
print("BORDER_ROOT:", BORDER_ROOT)
print("Manifest:", MANIFEST_PATH)
print("Log:", LOG_PATH)
print("Metadata:", METADATA_JSON_PATH)
print("Columns:", COLUMNS_CSV_PATH)
print("Full CSV:", FULL_CSV_PATH)
print("Full Parquet:", FULL_PARQUET_PATH)
print("Core freight subset Parquet:", CORE_FREIGHT_PARQUET_PATH)
print("=" * 100)

display_cols = [
    "record_type",
    "status",
    "size_mb",
    "parquet_status",
    "parquet_rows",
    "offset",
    "n_rows",
    "out_path",
    "csv_path",
    "parquet_path",
]
display_cols = [c for c in display_cols if c in manifest.columns]
display(manifest[display_cols].tail(30))

print("\nSource info:")
print(json.dumps(source_info, indent=2, ensure_ascii=False))

if MEASURE_INVENTORY_PATH.exists():
    print("\nMeasure inventory:")
    measure_inventory = pd.read_csv(MEASURE_INVENTORY_PATH)
    display(measure_inventory.head(30))

if CORE_FREIGHT_PARQUET_PATH.exists():
    print("\nCore 2018–2024 freight subset preview:")
    core_preview = pd.read_parquet(CORE_FREIGHT_PARQUET_PATH)
    display(core_preview.head(20))
    print("Rows:", len(core_preview))
    print("Columns:", list(core_preview.columns))

====================================================================================================
BTS Border Crossing Entry Data downloader
DATA_ROOT: E:\NetworkOptimization\pythonProject1\Data
BORDER_ROOT: E:\NetworkOptimization\pythonProject1\Data\06_border_crossing
DATASET_ID: keg4-3bc2
CORE_YEARS: [2018, 2019, 2020, 2021, 2022, 2023, 2024]
HAS_POLARS: False
====================================================================================================
[OK] Working Socrata domain: https://data.bts.gov
[metadata saved] E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\_metadata\border_crossing_entry_data_keg4-3bc2_metadata.json
[columns saved] E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\_metadata\border_crossing_entry_data_keg4-3bc2_columns.csv
Socrata row count: 273891
Order by clause: date, port_code, port_name, border, state, measure, value

----------------------------------------------------------------------------------------------------
[download] BTS Border Crossing full CSV snapshot
URL: https://data.bts.gov/api/views/keg4-3bc2/rows.csv?accessType=DOWNLOAD
OUT: E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\raw_full_snapshot\border_crossing_entry_data_keg4-3bc2_full.csv
----------------------------------------------------------------------------------------------------

BTS Border Crossing full CSV snapshot: 0.00B [00:00, ?B/s]

Downloading Socrata chunks:   0%|          | 0/6 [00:00<?, ?it/s]

[chunk] offset=0, limit=50,000
[chunk] offset=50,000, limit=50,000
[chunk] offset=100,000, limit=50,000
[chunk] offset=150,000, limit=50,000
[chunk] offset=200,000, limit=50,000
[chunk] offset=250,000, limit=50,000

C:\Users\Nick_James\AppData\Local\Temp\ipykernel_32072\1272047040.py:545: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["_date"] = pd.to_datetime(df[date_col], errors="coerce")

====================================================================================================
BTS BORDER CROSSING ENTRY DATA DOWNLOAD COMPLETE
====================================================================================================
BORDER_ROOT: E:\NetworkOptimization\pythonProject1\Data\06_border_crossing
Manifest: E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_border_crossing_download_manifest.csv
Log: E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_border_crossing_download_log.jsonl
Metadata: E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\_metadata\border_crossing_entry_data_keg4-3bc2_metadata.json
Columns: E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\_metadata\border_crossing_entry_data_keg4-3bc2_columns.csv
Full CSV: E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\raw_full_snapshot\border_crossing_entry_data_keg4-3bc2_full.csv
Full Parquet: E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\parquet\border_crossing_entry_data_keg4-3bc2_full.parquet
Core freight subset Parquet: E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\processed\border_crossing_freight_measures_2018_2024.parquet
====================================================================================================

,record_type,status,size_mb,parquet_status,parquet_rows,offset,n_rows,out_path,csv_path,parquet_path
0,full_snapshot,downloaded_or_exists,29.5511,converted,273891.0,NaN,NaN,E:\NetworkOptimization\pythonProject1\Data\06_...,NaN,E:\NetworkOptimization\pythonProject1\Data\06_...
1,chunk,downloaded,7.3214,converted,50000.0,0.0,50000.0,NaN,E:\NetworkOptimization\pythonProject1\Data\06_...,E:\NetworkOptimization\pythonProject1\Data\06_...
2,chunk,downloaded,7.3222,converted,50000.0,50000.0,50000.0,NaN,E:\NetworkOptimization\pythonProject1\Data\06_...,E:\NetworkOptimization\pythonProject1\Data\06_...
3,chunk,downloaded,7.3223,converted,50000.0,100000.0,50000.0,NaN,E:\NetworkOptimization\pythonProject1\Data\06_...,E:\NetworkOptimization\pythonProject1\Data\06_...
4,chunk,downloaded,7.3244,converted,50000.0,150000.0,50000.0,NaN,E:\NetworkOptimization\pythonProject1\Data\06_...,E:\NetworkOptimization\pythonProject1\Data\06_...
5,chunk,downloaded,7.4096,converted,50000.0,200000.0,50000.0,NaN,E:\NetworkOptimization\pythonProject1\Data\06_...,E:\NetworkOptimization\pythonProject1\Data\06_...
6,chunk,downloaded,3.5655,converted,23891.0,250000.0,23891.0,NaN,E:\NetworkOptimization\pythonProject1\Data\06_...,E:\NetworkOptimization\pythonProject1\Data\06_...
7,processed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Source info:
{
  "dataset_id": "keg4-3bc2",
  "domain": "https://data.bts.gov",
  "landing": "https://data.bts.gov/d/keg4-3bc2",
  "metadata_url": "https://data.bts.gov/api/views/keg4-3bc2.json",
  "columns_url": "https://data.bts.gov/api/views/keg4-3bc2/columns.json",
  "full_csv_url": "https://data.bts.gov/api/views/keg4-3bc2/rows.csv?accessType=DOWNLOAD",
  "resource_csv_url": "https://data.bts.gov/resource/keg4-3bc2.csv",
  "metadata_name": "Border Crossing Entry Data",
  "metadata_description": "The Bureau of Transportation Statistics (BTS) Border Crossing Data provide summary statistics for inbound crossings at the U.S.-Canada and the U.S.-Mexico border at the port level.  Data are available for trucks, trains, buses, personal vehicles, passengers, and pedestrians.  Border crossing data are collected at ports of entry by U.S. Customs and Border Protection (CBP).  The data reflect the number of vehicles, containers, passengers or pedestrians entering the United States.  CBP does not collect comparable data on outbound crossings.  Users seeking data on outbound counts may therefore want to review data from individual bridge operators, border state governments, or the Mexican and Canadian governments.",
  "metadata_rowsUpdatedAt": 1776884970,
  "metadata_viewLastModified": 1776884969,
  "metadata_totalTimesRated": 0,
  "row_count_from_socrata_api": 273891,
  "order_by_clause_used_for_chunks": "date, port_code, port_name, border, state, measure, value",
  "core_years_for_processed_subset": [
    2018,
    2019,
    2020,
    2021,
    2022,
    2023,
    2024
  ]
}

Measure inventory:

                       Measure  n_rows  min_year  max_year  total_value
0            Personal Vehicles   39190      1996      2026   3155947792
1  Personal Vehicle Passengers   39165      1996      2026   6520236589
2                       Trucks   37964      1996      2026    341681707
3                  Pedestrians   33306      1996      2026   1307746405
4                        Buses   32231      1996      2026      9553775
5               Bus Passengers   32212      1996      2026    160206184
6                       Trains   30227      1996      2026      1123143
7             Train Passengers   29596      1996      2026      7535981

Core 2018–2024 freight subset preview:

,Date,Port Name,Port Code,State,Border,Measure,Value,_date,_year,_month,_value_numeric,Latitude,Longitude,Point
0,Apr 2021,Otay Mesa,2506,California,US-Mexico Border,Trains,16,2021-04-01,2021,4,16,32.550,-116.939,POINT (-116.938538 32.55033)
1,Oct 2023,Otay Mesa,2506,California,US-Mexico Border,Trucks,92196,2023-10-01,2023,10,92196,32.550,-116.939,POINT (-116.938538 32.55033)
2,Dec 2021,Alexandria Bay,708,New York,US-Canada Border,Trucks,14090,2021-12-01,2021,12,14090,44.347,-75.984,POINT (-75.983592 44.347229)
3,Nov 2023,Wildhorse,3323,Montana,US-Canada Border,Trucks,9,2023-11-01,2023,11,9,48.999,-110.215,POINT (-110.215083 48.999361)
4,May 2024,International Falls,3604,Minnesota,US-Canada Border,Trucks,1414,2024-05-01,2024,5,1414,48.608,-93.401,POINT (-93.401355 48.6078)
5,Apr 2022,Roosville,3318,Montana,US-Canada Border,Trucks,707,2022-04-01,2022,4,707,49.000,-115.056,POINT (-115.056027 48.999638)
6,Nov 2021,Calais,115,Maine,US-Canada Border,Trucks,5753,2021-11-01,2021,11,5753,45.189,-67.275,POINT (-67.275381 45.188548)
7,Jul 2023,Otay Mesa,2506,California,US-Mexico Border,Trucks,89332,2023-07-01,2023,7,89332,32.550,-116.939,POINT (-116.938538 32.55033)
8,Dec 2024,Portal,3403,North Dakota,US-Canada Border,Trains,119,2024-12-01,2024,12,119,48.999,-102.552,POINT (-102.551944 48.998944)
9,Nov 2022,Skagway,3103,Alaska,US-Canada Border,Trucks,192,2022-11-01,2022,11,192,59.630,-135.164,POINT (-135.164444 59.629722)
10,Sep 2023,Richford,203,Vermont,US-Canada Border,Trucks,234,2023-09-01,2023,9,234,45.012,-72.589,POINT (-72.588559 45.01174)
11,Oct 2024,Northgate,3406,North Dakota,US-Canada Border,Trains,25,2024-10-01,2024,10,25,48.999,-102.275,POINT (-102.27475 48.998833)
12,Jan 2022,Hidalgo,2305,Texas,US-Mexico Border,Trucks,57327,2022-01-01,2022,1,57327,26.095,-98.271,POINT (-98.271092 26.095032)
13,Oct 2024,Del Rio,2302,Texas,US-Mexico Border,Trucks,6490,2024-10-01,2024,10,6490,29.327,-100.928,POINT (-100.927612 29.326784)
14,Nov 2022,Sarles,3409,North Dakota,US-Canada Border,Trucks,51,2022-11-01,2022,11,51,49.000,-98.938,POINT (-98.938361 49.000027)
15,Aug 2022,Laredo,2304,Texas,US-Mexico Border,Trains,392,2022-08-01,2022,8,392,27.500,-99.507,POINT (-99.507412 27.499561)
16,Jul 2024,Van Buren,108,Maine,US-Canada Border,Trucks,1526,2024-07-01,2024,7,1526,47.160,-67.931,POINT (-67.930799 47.159645)
17,Mar 2021,Oroville,3019,Washington,US-Canada Border,Trucks,2507,2021-03-01,2021,3,2507,49.000,-119.462,POINT (-119.461833 49.000083)
18,Jun 2021,Boundary,3015,Washington,US-Canada Border,Trucks,26,2021-06-01,2021,6,26,49.001,-117.628,POINT (-117.627583 49.00075)
19,Sep 2024,Trout River,715,New York,US-Canada Border,Trucks,1031,2024-09-01,2024,9,1031,44.992,-74.308,POINT (-74.308172 44.992058)

Rows: 10605
Columns: ['Date', 'Port Name', 'Port Code', 'State', 'Border', 'Measure', 'Value', '_date', '_year', '_month', '_value_numeric', 'Latitude', 'Longitude', 'Point']

In [4]:
# ============================================================
# Repair pyarrow.parquet / pandas residue for FREIGHT-MNet env
# Run this once, then RESTART kernel.
# ============================================================

import sys
import site
import shutil
import subprocess
from pathlib import Path

print("=" * 100)
print("Current Python executable:")
print(sys.executable)
print("=" * 100)

site_packages = Path(site.getsitepackages()[0])
print("site-packages:", site_packages)

# 1. Clean broken leftover folders, especially ~andas.
for pattern in ["~andas*", "~umpy*", "~andas-*.dist-info", "~umpy-*.dist-info"]:
    for p in site_packages.glob(pattern):
        print("Removing broken leftover:", p)
        try:
            if p.is_dir():
                shutil.rmtree(p)
            else:
                p.unlink()
        except Exception as e:
            print("  failed:", e)

# 2. Reinstall pandas and pyarrow cleanly.
# pandas==2.3.3 is safer because copulas requires pandas<3.
cmds = [
    [
        sys.executable, "-m", "pip", "install",
        "--upgrade",
        "--force-reinstall",
        "--no-cache-dir",
        "--prefer-binary",
        "pandas==2.3.3",
        "pyarrow",
    ],
    [
        sys.executable, "-m", "pip", "install",
        "--upgrade",
        "--no-cache-dir",
        "--prefer-binary",
        "fastparquet",
    ],
]

for cmd in cmds:
    print("\n" + "-" * 100)
    print("$", " ".join(cmd))
    print("-" * 100)
    subprocess.run(cmd, check=True)

print("\n" + "=" * 100)
print("Repair install finished.")
print("IMPORTANT: Restart the Jupyter kernel now, then run the verification cell below.")
print("=" * 100)

====================================================================================================
Current Python executable:
D:\apphome\anaconda3\python.exe
====================================================================================================
site-packages: D:\apphome\anaconda3

----------------------------------------------------------------------------------------------------
$ D:\apphome\anaconda3\python.exe -m pip install --upgrade --force-reinstall --no-cache-dir --prefer-binary pandas==2.3.3 pyarrow
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
$ D:\apphome\anaconda3\python.exe -m pip install --upgrade --no-cache-dir --prefer-binary fastparquet
----------------------------------------------------------------------------------------------------

====================================================================================================
Repair install finished.
IMPORTANT: Restart the Jupyter kernel now, then run the verification cell below.
====================================================================================================

In [1]:
# ============================================================
# FREIGHT-MNet: Full Data Inventory Console Printer
#
# Goal:
#   Traverse every subfolder and dataset under:
#       E:\NetworkOptimization\pythonProject1\Data
#
# Prints to console:
#   1. Root summary
#   2. Top-level folder summary
#   3. Expected dataset checklist
#   4. Full directory tree
#   5. Full file inventory with absolute paths
#
# Also saves:
#   E:\NetworkOptimization\pythonProject1\Data\00_manifest\data_inventory_console_output.txt
#   E:\NetworkOptimization\pythonProject1\Data\00_manifest\data_inventory_file_inventory.csv
# ============================================================

from pathlib import Path
from collections import Counter, defaultdict
from datetime import datetime
import os
import sys
import csv
import fnmatch
import platform

# ------------------------------------------------------------
# 0. Config
# ------------------------------------------------------------

DATA_ROOT = Path(r"E:\NetworkOptimization\pythonProject1\Data")
MANIFEST_DIR = DATA_ROOT / "00_manifest"
MANIFEST_DIR.mkdir(parents=True, exist_ok=True)

OUTPUT_TXT = MANIFEST_DIR / "data_inventory_console_output.txt"
OUTPUT_CSV = MANIFEST_DIR / "data_inventory_file_inventory.csv"

# Print all directories and all files.
PRINT_ALL_DIRECTORIES = True
PRINT_ALL_FILES = True

# Set to None to print all files.
# If output is too long, you can set e.g. MAX_FULL_FILE_LINES = 5000.
MAX_FULL_FILE_LINES = None

# Directory tree depth:
# None means print all directory levels.
TREE_MAX_DEPTH = None

# Extensions we consider important data artifacts.
IMPORTANT_EXTENSIONS = {
    ".csv", ".csv.gz", ".parquet", ".zip", ".gz",
    ".xlsx", ".xls", ".pdf",
    ".json", ".jsonl", ".geojson", ".gpkg",
    ".shp", ".shx", ".dbf", ".prj", ".cpg",
    ".txt", ".dat", ".mdb", ".accdb",
}

TEMP_OR_INCOMPLETE_SUFFIXES = {
    ".part", ".tmp", ".temp", ".crdownload"
}

# ------------------------------------------------------------
# 1. Helpers
# ------------------------------------------------------------

def now_str():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def size_human(num_bytes: int) -> str:
    if num_bytes is None:
        return "NA"
    x = float(num_bytes)
    units = ["B", "KB", "MB", "GB", "TB"]
    for u in units:
        if x < 1024 or u == units[-1]:
            if u == "B":
                return f"{int(x)} {u}"
            return f"{x:.3f} {u}"
        x /= 1024

def size_mb(num_bytes: int) -> float:
    return round((num_bytes or 0) / 1024**2, 6)

def rel_path(p: Path) -> str:
    try:
        return str(p.relative_to(DATA_ROOT))
    except Exception:
        return str(p)

def abs_path(p: Path) -> str:
    return str(p.resolve())

def file_type(path: Path) -> str:
    name = path.name.lower()

    if name.endswith(".csv.gz"):
        return ".csv.gz"
    if name.endswith(".tar.gz"):
        return ".tar.gz"

    return path.suffix.lower() if path.suffix else "<no_ext>"

def is_temp_or_incomplete(path: Path) -> bool:
    name = path.name.lower()
    return any(name.endswith(s) for s in TEMP_OR_INCOMPLETE_SUFFIXES)

def get_mtime(path: Path) -> str:
    try:
        return datetime.fromtimestamp(path.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        return "NA"

def get_size(path: Path) -> int:
    try:
        return path.stat().st_size
    except Exception:
        return 0

def is_under(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
        return True
    except Exception:
        return False

def matches_any_pattern(path: Path, patterns):
    if patterns is None:
        return True

    name = path.name
    rel = rel_path(path).replace("\\", "/")

    for pat in patterns:
        if fnmatch.fnmatch(name, pat) or fnmatch.fnmatch(rel, pat):
            return True

    return False

def path_depth(path: Path) -> int:
    try:
        return len(path.relative_to(DATA_ROOT).parts)
    except Exception:
        return 0

# ------------------------------------------------------------
# 2. Scan Data root
# ------------------------------------------------------------

if not DATA_ROOT.exists():
    raise FileNotFoundError(f"DATA_ROOT does not exist: {DATA_ROOT}")

all_dirs = []
all_files = []

for root, dirs, files in os.walk(DATA_ROOT):
    root_path = Path(root)

    # Stable order.
    dirs.sort()
    files.sort()

    all_dirs.append(root_path)

    for fname in files:
        p = root_path / fname
        if p.is_file():
            all_files.append(p)

all_dirs = sorted(set(all_dirs), key=lambda p: str(p).lower())
all_files = sorted(set(all_files), key=lambda p: str(p).lower())

# File metadata.
file_rows = []

for p in all_files:
    try:
        st = p.stat()
        size_bytes = st.st_size
        mtime = datetime.fromtimestamp(st.st_mtime).strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        size_bytes = 0
        mtime = "NA"

    rel = rel_path(p)
    parts = Path(rel).parts
    top_level = parts[0] if len(parts) > 0 else "<root>"

    file_rows.append({
        "absolute_path": abs_path(p),
        "relative_path": rel,
        "parent_dir": abs_path(p.parent),
        "top_level": top_level,
        "file_name": p.name,
        "extension": file_type(p),
        "size_bytes": size_bytes,
        "size_mb": size_mb(size_bytes),
        "modified_time": mtime,
        "is_temp_or_incomplete": is_temp_or_incomplete(p),
    })

total_bytes = sum(r["size_bytes"] for r in file_rows)

# Directory immediate file counts.
files_by_parent = defaultdict(list)
for p in all_files:
    files_by_parent[p.parent].append(p)

# Top-level stats.
top_stats = defaultdict(lambda: {
    "n_dirs": 0,
    "n_files": 0,
    "size_bytes": 0,
    "extensions": Counter(),
    "n_temp_or_incomplete": 0,
})

for d in all_dirs:
    rel = rel_path(d)
    parts = Path(rel).parts
    top = parts[0] if len(parts) > 0 and rel != "." else "<root>"
    top_stats[top]["n_dirs"] += 1

for r in file_rows:
    top = r["top_level"]
    top_stats[top]["n_files"] += 1
    top_stats[top]["size_bytes"] += r["size_bytes"]
    top_stats[top]["extensions"][r["extension"]] += 1
    if r["is_temp_or_incomplete"]:
        top_stats[top]["n_temp_or_incomplete"] += 1

# ------------------------------------------------------------
# 3. Prepare output writer
# ------------------------------------------------------------

out_f = OUTPUT_TXT.open("w", encoding="utf-8")

def emit(line=""):
    print(line)
    out_f.write(str(line) + "\n")

try:
    # --------------------------------------------------------
    # Header
    # --------------------------------------------------------

    emit("=" * 120)
    emit("FREIGHT-MNet DATA INVENTORY")
    emit("=" * 120)
    emit(f"Run time:                  {now_str()}")
    emit(f"Python executable:         {sys.executable}")
    emit(f"Python version:            {sys.version.replace(chr(10), ' ')}")
    emit(f"Platform:                  {platform.platform()}")
    emit(f"DATA_ROOT:                 {abs_path(DATA_ROOT)}")
    emit(f"Output TXT:                {abs_path(OUTPUT_TXT)}")
    emit(f"Output CSV:                {abs_path(OUTPUT_CSV)}")
    emit("-" * 120)
    emit(f"Total directories:         {len(all_dirs):,}")
    emit(f"Total files:               {len(all_files):,}")
    emit(f"Total size:                {size_human(total_bytes)}")
    emit("=" * 120)

    # --------------------------------------------------------
    # Global extension summary
    # --------------------------------------------------------

    ext_counter = Counter(r["extension"] for r in file_rows)
    temp_files = [r for r in file_rows if r["is_temp_or_incomplete"]]

    emit("")
    emit("=" * 120)
    emit("GLOBAL FILE TYPE SUMMARY")
    emit("=" * 120)
    for ext, n in sorted(ext_counter.items(), key=lambda x: (-x[1], x[0])):
        ext_size = sum(r["size_bytes"] for r in file_rows if r["extension"] == ext)
        emit(f"{ext:12s} | files={n:8,} | size={size_human(ext_size):>15s}")

    emit("")
    emit(f"Temporary / incomplete files detected: {len(temp_files):,}")
    if temp_files:
        emit("TEMP / INCOMPLETE FILES:")
        for r in temp_files[:100]:
            emit(f"  {r['extension']:10s} | {size_human(r['size_bytes']):>12s} | {r['absolute_path']}")
        if len(temp_files) > 100:
            emit(f"  ... {len(temp_files) - 100:,} more temp/incomplete files not shown here.")

    # --------------------------------------------------------
    # Top-level folder summary
    # --------------------------------------------------------

    emit("")
    emit("=" * 120)
    emit("TOP-LEVEL FOLDER SUMMARY")
    emit("=" * 120)
    emit(f"{'TOP_FOLDER':35s} | {'DIRS':>8s} | {'FILES':>8s} | {'TEMP':>6s} | {'SIZE':>15s} | EXTENSIONS")
    emit("-" * 120)

    for top in sorted(top_stats.keys()):
        s = top_stats[top]
        ext_summary = ", ".join(
            f"{k}:{v}" for k, v in sorted(s["extensions"].items(), key=lambda x: (-x[1], x[0]))[:10]
        )
        emit(
            f"{top:35s} | "
            f"{s['n_dirs']:8,} | "
            f"{s['n_files']:8,} | "
            f"{s['n_temp_or_incomplete']:6,} | "
            f"{size_human(s['size_bytes']):>15s} | "
            f"{ext_summary}"
        )

    # --------------------------------------------------------
    # Expected dataset checklist
    # --------------------------------------------------------

    dataset_checks = []

    def add_check(label, path, patterns=None):
        dataset_checks.append({
            "label": label,
            "path": Path(path),
            "patterns": patterns,
        })

    # Core folders.
    add_check("00_manifest", DATA_ROOT / "00_manifest")
    add_check("01_faf", DATA_ROOT / "01_faf")
    add_check("02_fmi", DATA_ROOT / "02_fmi")
    add_check("03_ntad_geospatial", DATA_ROOT / "03_ntad_geospatial")
    add_check("04_stb", DATA_ROOT / "04_stb")
    add_check("05_noaa_storm_events", DATA_ROOT / "05_noaa_storm_events")
    add_check("06_border_crossing", DATA_ROOT / "06_border_crossing")
    add_check("07_census_boundaries", DATA_ROOT / "07_census_boundaries")
    add_check("08_processed", DATA_ROOT / "08_processed")
    add_check("09_crosswalks", DATA_ROOT / "09_crosswalks")

    # FAF.
    add_check("FAF raw_zip", DATA_ROOT / "01_faf" / "raw_zip", ["*.zip"])
    add_check("FAF flows_regional", DATA_ROOT / "01_faf" / "flows_regional")
    add_check("FAF flows_state", DATA_ROOT / "01_faf" / "flows_state")
    add_check("FAF flows_regional_full", DATA_ROOT / "01_faf" / "flows_regional_full")
    add_check("FAF access_database", DATA_ROOT / "01_faf" / "access_database")
    add_check("FAF county_experimental", DATA_ROOT / "01_faf" / "county_experimental")
    add_check("FAF lookup_tables", DATA_ROOT / "01_faf" / "lookup_tables")

    # FMI by year.
    for y in range(2018, 2025):
        add_check(f"FMI {y}", DATA_ROOT / "02_fmi" / str(y), ["*.csv", "*.parquet", "*.json"])
    add_check("FMI metadata", DATA_ROOT / "02_fmi" / "_metadata")

    # NTAD layers.
    for layer in [
        "faf_regions",
        "faf_network_links",
        "faf_network_nodes",
        "narn_lines",
        "narn_nodes",
        "intermodal_rail_tofc_cofc",
    ]:
        add_check(f"NTAD {layer}", DATA_ROOT / "03_ntad_geospatial" / layer)
        add_check(f"NTAD {layer} parquet_chunks_v2", DATA_ROOT / "03_ntad_geospatial" / layer / "parquet_chunks_v2", ["*.parquet"])
        add_check(f"NTAD {layer} metadata_v2", DATA_ROOT / "03_ntad_geospatial" / layer / "metadata_v2")

    # STB Waybill by year.
    for y in range(2018, 2025):
        add_check(f"STB Waybill {y}", DATA_ROOT / "04_stb" / "waybill_public_use" / str(y))
        add_check(f"STB Waybill {y} sample_zip", DATA_ROOT / "04_stb" / "waybill_public_use" / str(y) / "sample_zip", ["*.zip"])
        add_check(f"STB Waybill {y} reference_guide", DATA_ROOT / "04_stb" / "waybill_public_use" / str(y) / "reference_guide", ["*.pdf"])
        add_check(f"STB Waybill {y} extracted", DATA_ROOT / "04_stb" / "waybill_public_use" / str(y) / "extracted")
        add_check(f"STB Waybill {y} preview", DATA_ROOT / "04_stb" / "waybill_public_use" / str(y) / "preview")

    # STB Rail Service.
    add_check("STB Rail Service root", DATA_ROOT / "04_stb" / "rail_service_performance")
    add_check("STB Rail weekly_service_files", DATA_ROOT / "04_stb" / "rail_service_performance" / "weekly_service_files")
    add_check("STB Rail STB-1145 CSV", DATA_ROOT / "04_stb" / "rail_service_performance" / "stb_1145_csv")
    add_check("STB Rail methodology_docs", DATA_ROOT / "04_stb" / "rail_service_performance" / "methodology_docs")
    add_check("STB Rail metadata", DATA_ROOT / "04_stb" / "rail_service_performance" / "_metadata")

    # NOAA.
    for table in ["details", "locations", "fatalities"]:
        add_check(f"NOAA {table} raw", DATA_ROOT / "05_noaa_storm_events" / table, ["*.gz", "*.csv.gz"])
        add_check(f"NOAA {table} parquet", DATA_ROOT / "05_noaa_storm_events" / "parquet" / table, ["*.parquet"])
        add_check(f"NOAA {table} preview", DATA_ROOT / "05_noaa_storm_events" / "preview" / table)
    add_check("NOAA docs", DATA_ROOT / "05_noaa_storm_events" / "docs")
    add_check("NOAA metadata", DATA_ROOT / "05_noaa_storm_events" / "_metadata")

    # Border.
    add_check("Border root", DATA_ROOT / "06_border_crossing")
    add_check("Border raw full snapshot", DATA_ROOT / "06_border_crossing" / "raw_full_snapshot")
    add_check("Border chunks_csv", DATA_ROOT / "06_border_crossing" / "chunks_csv")
    add_check("Border chunks_parquet", DATA_ROOT / "06_border_crossing" / "chunks_parquet")
    add_check("Border parquet", DATA_ROOT / "06_border_crossing" / "parquet")
    add_check("Border processed", DATA_ROOT / "06_border_crossing" / "processed")
    add_check("Border metadata", DATA_ROOT / "06_border_crossing" / "_metadata")

    # Census.
    add_check("Census counties_2024 root", DATA_ROOT / "07_census_boundaries" / "counties_2024")
    add_check("Census raw_zip", DATA_ROOT / "07_census_boundaries" / "counties_2024" / "raw_zip")
    add_check("Census extracted", DATA_ROOT / "07_census_boundaries" / "counties_2024" / "extracted")
    add_check("Census geoparquet", DATA_ROOT / "07_census_boundaries" / "counties_2024" / "geoparquet")
    add_check("Census processed", DATA_ROOT / "07_census_boundaries" / "counties_2024" / "processed")
    add_check("Census metadata", DATA_ROOT / "07_census_boundaries" / "counties_2024" / "_metadata")

    emit("")
    emit("=" * 120)
    emit("EXPECTED DATASET CHECKLIST")
    emit("=" * 120)

    for item in dataset_checks:
        label = item["label"]
        p = item["path"]
        patterns = item["patterns"]

        exists = p.exists()

        if exists and p.is_dir():
            matched = [
                f for f in all_files
                if is_under(f, p) and matches_any_pattern(f, patterns)
            ]
            all_under = [
                f for f in all_files
                if is_under(f, p)
            ]
        elif exists and p.is_file():
            matched = [p] if matches_any_pattern(p, patterns) else []
            all_under = [p]
        else:
            matched = []
            all_under = []

        matched_size = sum(get_size(f) for f in matched)
        all_size = sum(get_size(f) for f in all_under)

        ext_counts = Counter(file_type(f) for f in matched)
        ext_summary = ", ".join(f"{k}:{v}" for k, v in sorted(ext_counts.items(), key=lambda x: (-x[1], x[0]))[:8])

        status = "OK" if exists and len(matched if patterns else all_under) > 0 else ("EMPTY" if exists else "MISSING")

        emit("-" * 120)
        emit(f"DATASET: {label}")
        emit(f"STATUS:  {status}")
        emit(f"PATH:    {abs_path(p)}")
        emit(f"FILES_MATCHED: {len(matched):,} | FILES_ALL_UNDER: {len(all_under):,}")
        emit(f"SIZE_MATCHED:  {size_human(matched_size)} | SIZE_ALL_UNDER: {size_human(all_size)}")
        emit(f"EXTENSIONS: {ext_summary if ext_summary else 'NA'}")

        # Representative files: first 3 and largest 3.
        if matched:
            emit("REPRESENTATIVE FILES:")
            for f in sorted(matched, key=lambda x: str(x).lower())[:3]:
                emit(f"  FIRST   | {size_human(get_size(f)):>12s} | {abs_path(f)}")

            largest = sorted(matched, key=lambda x: get_size(x), reverse=True)[:3]
            for f in largest:
                emit(f"  LARGEST | {size_human(get_size(f)):>12s} | {abs_path(f)}")

    # --------------------------------------------------------
    # Directory tree
    # --------------------------------------------------------

    if PRINT_ALL_DIRECTORIES:
        emit("")
        emit("=" * 120)
        emit("FULL DIRECTORY TREE")
        emit("=" * 120)

        for d in all_dirs:
            depth = path_depth(d)

            if TREE_MAX_DEPTH is not None and depth > TREE_MAX_DEPTH:
                continue

            rel = rel_path(d)
            indent = "  " * max(depth - 1, 0)
            immediate_files = files_by_parent.get(d, [])
            immediate_size = sum(get_size(f) for f in immediate_files)

            emit(
                f"{indent}[DIR] {rel} | "
                f"immediate_files={len(immediate_files):,} | "
                f"immediate_size={size_human(immediate_size)} | "
                f"absolute={abs_path(d)}"
            )

    # --------------------------------------------------------
    # Full file inventory
    # --------------------------------------------------------

    if PRINT_ALL_FILES:
        emit("")
        emit("=" * 120)
        emit("FULL FILE INVENTORY")
        emit("=" * 120)
        emit("FORMAT:")
        emit("INDEX | EXTENSION | SIZE | MODIFIED_TIME | TEMP_FLAG | ABSOLUTE_PATH")
        emit("-" * 120)

        rows_to_print = file_rows
        if MAX_FULL_FILE_LINES is not None:
            rows_to_print = file_rows[:MAX_FULL_FILE_LINES]

        for idx, r in enumerate(rows_to_print, start=1):
            emit(
                f"{idx:08d} | "
                f"{r['extension']:12s} | "
                f"{size_human(r['size_bytes']):>12s} | "
                f"{r['modified_time']} | "
                f"temp={str(r['is_temp_or_incomplete']):5s} | "
                f"{r['absolute_path']}"
            )

        if MAX_FULL_FILE_LINES is not None and len(file_rows) > MAX_FULL_FILE_LINES:
            emit(f"... output truncated by MAX_FULL_FILE_LINES={MAX_FULL_FILE_LINES}.")
            emit(f"... total files available: {len(file_rows):,}")

    # --------------------------------------------------------
    # Save CSV
    # --------------------------------------------------------

    with OUTPUT_CSV.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "absolute_path",
                "relative_path",
                "parent_dir",
                "top_level",
                "file_name",
                "extension",
                "size_bytes",
                "size_mb",
                "modified_time",
                "is_temp_or_incomplete",
            ]
        )
        writer.writeheader()
        writer.writerows(file_rows)

    # --------------------------------------------------------
    # Footer
    # --------------------------------------------------------

    emit("")
    emit("=" * 120)
    emit("INVENTORY COMPLETE")
    emit("=" * 120)
    emit(f"Total directories: {len(all_dirs):,}")
    emit(f"Total files:       {len(all_files):,}")
    emit(f"Total size:        {size_human(total_bytes)}")
    emit(f"Output TXT:        {abs_path(OUTPUT_TXT)}")
    emit(f"Output CSV:        {abs_path(OUTPUT_CSV)}")
    emit("=" * 120)

finally:
    out_f.close()

========================================================================================================================
FREIGHT-MNet DATA INVENTORY
========================================================================================================================
Run time:                  2026-05-16 16:32:12
Python executable:         E:\NetworkOptimization\pythonProject1\env\.venv_freight_mnet_cuda\Scripts\python.exe
Python version:            3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
Platform:                  Windows-10-10.0.26200-SP0
DATA_ROOT:                 E:\NetworkOptimization\pythonProject1\Data
Output TXT:                E:\NetworkOptimization\pythonProject1\Data\00_manifest\data_inventory_console_output.txt
Output CSV:                E:\NetworkOptimization\pythonProject1\Data\00_manifest\data_inventory_file_inventory.csv
------------------------------------------------------------------------------------------------------------------------
Total directories:         277
Total files:               28,981
Total size:                15.074 GB
========================================================================================================================

========================================================================================================================
GLOBAL FILE TYPE SUMMARY
========================================================================================================================
.json        | files=  22,234 | size=       4.346 GB
.geojson     | files=   3,836 | size=     786.360 MB
.xlsx        | files=   2,614 | size=      95.969 MB
.csv         | files=     122 | size=       3.754 GB
.parquet     | files=      37 | size=     737.515 MB
.csv.gz      | files=      21 | size=      84.973 MB
.pdf         | files=      20 | size=      36.262 MB
.doc         | files=      16 | size=       1.127 MB
.txt         | files=      15 | size=       2.434 GB
.jpg         | files=      14 | size=      11.548 MB
.zip         | files=      14 | size=       1.437 GB
.docx        | files=      12 | size=     264.350 KB
.jsonl       | files=       8 | size=       1.187 MB
.xml         | files=       4 | size=     163.126 KB
.cpg         | files=       2 | size=           10 B
.dbf         | files=       2 | size=       2.074 MB
.html        | files=       2 | size=       1.756 MB
.prj         | files=       2 | size=          330 B
.shp         | files=       2 | size=     141.986 MB
.shx         | files=       2 | size=      50.742 KB
.accdb       | files=       1 | size=       1.246 GB
<no_ext>     | files=       1 | size=       1.966 KB

Temporary / incomplete files detected: 0

========================================================================================================================
TOP-LEVEL FOLDER SUMMARY
========================================================================================================================
TOP_FOLDER                          |     DIRS |    FILES |   TEMP |            SIZE | EXTENSIONS
------------------------------------------------------------------------------------------------------------------------
00_manifest                         |        1 |       19 |      0 |       20.666 MB | .csv:10, .jsonl:8, .txt:1
01_faf                              |        7 |       22 |      0 |        4.324 GB | .csv:11, .xlsx:5, .zip:5, .accdb:1
02_fmi                              |       16 |       42 |      0 |        2.188 GB | .csv:21, .json:14, .parquet:7
03_ntad_geospatial                  |       31 |   26,058 |      0 |        5.140 GB | .json:22207, .geojson:3836, .csv:15
04_stb                              |      179 |    2,708 |      0 |        2.880 GB | .xlsx:2609, .pdf:18, .doc:16, .jpg:14, .txt:14, .docx:12, .csv:10, .json:7, .zip:7, .html:1
05_noaa_storm_events                |       14 |       90 |      0 |      215.904 MB | .csv:44, .csv.gz:21, .parquet:21, .pdf:2, .html:1, <no_ext>:1
06_border_crossing                  |        8 |       23 |      0 |       82.890 MB | .csv:11, .parquet:9, .json:3
07_census_boundaries                |       10 |       19 |      0 |      235.386 MB | .xml:4, .json:3, .cpg:2, .dbf:2, .prj:2, .shp:2, .shx:2, .zip:2
08_processed                        |        5 |        0 |      0 |             0 B |
09_crosswalks                       |        5 |        0 |      0 |             0 B |
<root>                              |        1 |        0 |      0 |             0 B |

========================================================================================================================
EXPECTED DATASET CHECKLIST
========================================================================================================================
------------------------------------------------------------------------------------------------------------------------
DATASET: 00_manifest
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\00_manifest
FILES_MATCHED: 19 | FILES_ALL_UNDER: 19
SIZE_MATCHED:  14.475 MB | SIZE_ALL_UNDER: 14.475 MB
EXTENSIONS: .csv:10, .jsonl:8, .txt:1
REPRESENTATIVE FILES:
  FIRST   |        362 B | E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_border_crossing_download_log.jsonl
  FIRST   |     4.632 KB | E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_border_crossing_download_manifest.csv
  FIRST   |     5.418 KB | E:\NetworkOptimization\pythonProject1\Data\00_manifest\bts_fmi_download_log.jsonl
  LARGEST |    12.342 MB | E:\NetworkOptimization\pythonProject1\Data\00_manifest\data_inventory_file_inventory.csv
  LARGEST |     1.151 MB | E:\NetworkOptimization\pythonProject1\Data\00_manifest\stb_rail_service_download_log.jsonl
  LARGEST |   908.590 KB | E:\NetworkOptimization\pythonProject1\Data\00_manifest\stb_rail_service_download_manifest.csv
------------------------------------------------------------------------------------------------------------------------
DATASET: 01_faf
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\01_faf
FILES_MATCHED: 22 | FILES_ALL_UNDER: 22
SIZE_MATCHED:  4.324 GB | SIZE_ALL_UNDER: 4.324 GB
EXTENSIONS: .csv:11, .xlsx:5, .zip:5, .accdb:1
REPRESENTATIVE FILES:
  FIRST   |     1.246 GB | E:\NetworkOptimization\pythonProject1\Data\01_faf\access_database\FAF5.7.1_access.accdb
  FIRST   |    28.111 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\access_database\FAF5_metadata.xlsx
  FIRST   |   556.796 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\All_Experimental_Disaggregation_Factors.zip
  LARGEST |     1.246 GB | E:\NetworkOptimization\pythonProject1\Data\01_faf\access_database\FAF5.7.1_access.accdb
  LARGEST |     1.099 GB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_regional\FAF5.7.1.csv
  LARGEST |   663.039 MB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_state\FAF5.7.1_2018-2024.csv
------------------------------------------------------------------------------------------------------------------------
DATASET: 02_fmi
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\02_fmi
FILES_MATCHED: 42 | FILES_ALL_UNDER: 42
SIZE_MATCHED:  2.188 GB | SIZE_ALL_UNDER: 2.188 GB
EXTENSIONS: .csv:21, .json:14, .parquet:7
REPRESENTATIVE FILES:
  FIRST   |   131.977 MB | E:\NetworkOptimization\pythonProject1\Data\02_fmi\2018\bts_fmi_county_travel_times_2018_xx4g-5dg2.csv
  FIRST   |    46.312 MB | E:\NetworkOptimization\pythonProject1\Data\02_fmi\2018\bts_fmi_county_travel_times_2018_xx4g-5dg2.parquet
  FIRST   |   261.000 MB | E:\NetworkOptimization\pythonProject1\Data\02_fmi\2019\bts_fmi_county_travel_times_2019_sn4k-eiea.csv
  LARGEST |   281.613 MB | E:\NetworkOptimization\pythonProject1\Data\02_fmi\2020\bts_fmi_county_travel_times_2020_dggd-bg3y.csv
  LARGEST |   270.129 MB | E:\NetworkOptimization\pythonProject1\Data\02_fmi\2021\bts_fmi_county_travel_times_2021_mayv-2qfz.csv
  LARGEST |   261.000 MB | E:\NetworkOptimization\pythonProject1\Data\02_fmi\2019\bts_fmi_county_travel_times_2019_sn4k-eiea.csv
------------------------------------------------------------------------------------------------------------------------
DATASET: 03_ntad_geospatial
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial
FILES_MATCHED: 26,058 | FILES_ALL_UNDER: 26,058
SIZE_MATCHED:  5.140 GB | SIZE_ALL_UNDER: 5.140 GB
EXTENSIONS: .json:22207, .geojson:3836, .csv:15
REPRESENTATIVE FILES:
  FIRST   |     6.002 MB | E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\faf_network_links_chunk_manifest_v2.csv
  FIRST   |     1.669 KB | E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\faf_network_links_summary_v2.json
  FIRST   |     3.701 KB | E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_network_links\metadata\faf_network_links_fields.csv
  LARGEST |    65.569 MB | E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\raw_chunks_geojson\faf_regions__chunk_00001.geojson
  LARGEST |    65.564 MB | E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\raw_esri_json_chunks_v2\faf_regions__chunk_00001.json
  LARGEST |    47.839 MB | E:\NetworkOptimization\pythonProject1\Data\03_ntad_geospatial\faf_regions\raw_chunks_geojson\faf_regions__chunk_00001_b.geojson
------------------------------------------------------------------------------------------------------------------------
DATASET: 04_stb
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\04_stb
FILES_MATCHED: 2,708 | FILES_ALL_UNDER: 2,708
SIZE_MATCHED:  2.880 GB | SIZE_ALL_UNDER: 2.880 GB
EXTENSIONS: .xlsx:2609, .pdf:18, .doc:16, .jpg:14, .txt:14, .docx:12, .csv:10, .json:7
REPRESENTATIVE FILES:
  FIRST   |     1.026 MB | E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\_metadata\stb_rail_service_link_inventory.csv
  FIRST   |     1.704 MB | E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\_metadata\stb_rail_service_page_snapshot.html
  FIRST   |   429.391 KB | E:\NetworkOptimization\pythonProject1\Data\04_stb\rail_service_performance\_metadata\stb_rail_service_selected_download_links.csv
  LARGEST |   514.566 MB | E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2024\extracted\PublicUseWaybillSample2024.txt
  LARGEST |   500.634 MB | E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2023\extracted\PublicUseWaybillSample2023.txt
  LARGEST |   498.722 MB | E:\NetworkOptimization\pythonProject1\Data\04_stb\waybill_public_use\2022\extracted\PublicUseWaybillSample2022.txt
------------------------------------------------------------------------------------------------------------------------
DATASET: 05_noaa_storm_events
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events
FILES_MATCHED: 90 | FILES_ALL_UNDER: 90
SIZE_MATCHED:  215.904 MB | SIZE_ALL_UNDER: 215.904 MB
EXTENSIONS: .csv:44, .csv.gz:21, .parquet:21, .pdf:2, .html:1, <no_ext>:1
REPRESENTATIVE FILES:
  FIRST   |    43.584 KB | E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\_metadata\noaa_storm_events_full_index_inventory.csv
  FIRST   |    53.307 KB | E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\_metadata\noaa_storm_events_index_snapshot.html
  FIRST   |     4.195 KB | E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\_metadata\noaa_storm_events_link_inventory_2018_2024.csv
  LARGEST |    18.928 MB | E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2023.parquet
  LARGEST |    18.371 MB | E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2024.parquet
  LARGEST |    17.351 MB | E:\NetworkOptimization\pythonProject1\Data\05_noaa_storm_events\parquet\details\noaa_stormevents_details_2022.parquet
------------------------------------------------------------------------------------------------------------------------
DATASET: 06_border_crossing
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\06_border_crossing
FILES_MATCHED: 23 | FILES_ALL_UNDER: 23
SIZE_MATCHED:  82.890 MB | SIZE_ALL_UNDER: 82.890 MB
EXTENSIONS: .csv:11, .parquet:9, .json:3
REPRESENTATIVE FILES:
  FIRST   |     1.417 KB | E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\_metadata\border_crossing_entry_data_keg4-3bc2_columns.csv
  FIRST   |    23.463 KB | E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\_metadata\border_crossing_entry_data_keg4-3bc2_columns.json
  FIRST   |    31.488 KB | E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\_metadata\border_crossing_entry_data_keg4-3bc2_metadata.json
  LARGEST |    29.551 MB | E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\raw_full_snapshot\border_crossing_entry_data_keg4-3bc2_full.csv
  LARGEST |     8.065 MB | E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\parquet\border_crossing_entry_data_keg4-3bc2_full.parquet
  LARGEST |     7.410 MB | E:\NetworkOptimization\pythonProject1\Data\06_border_crossing\chunks_csv\border_crossing_keg4-3bc2_chunk_00004_offset_200000.csv
------------------------------------------------------------------------------------------------------------------------
DATASET: 07_census_boundaries
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\07_census_boundaries
FILES_MATCHED: 19 | FILES_ALL_UNDER: 19
SIZE_MATCHED:  235.386 MB | SIZE_ALL_UNDER: 235.386 MB
EXTENSIONS: .xml:4, .json:3, .cpg:2, .dbf:2, .prj:2, .shp:2, .shx:2, .zip:2
REPRESENTATIVE FILES:
  FIRST   |     1.004 KB | E:\NetworkOptimization\pythonProject1\Data\07_census_boundaries\counties_2024\_metadata\census_county_boundaries_2024_source_info.json
  FIRST   |     1.547 KB | E:\NetworkOptimization\pythonProject1\Data\07_census_boundaries\counties_2024\extracted\cartographic_500k\.extracted_cb_2024_us_county_500k.json
  FIRST   |          5 B | E:\NetworkOptimization\pythonProject1\Data\07_census_boundaries\counties_2024\extracted\cartographic_500k\cb_2024_us_county_500k.cpg
  LARGEST |   126.028 MB | E:\NetworkOptimization\pythonProject1\Data\07_census_boundaries\counties_2024\extracted\tigerline\tl_2024_us_county.shp
  LARGEST |    80.026 MB | E:\NetworkOptimization\pythonProject1\Data\07_census_boundaries\counties_2024\raw_zip\tl_2024_us_county.zip
  LARGEST |    15.958 MB | E:\NetworkOptimization\pythonProject1\Data\07_census_boundaries\counties_2024\extracted\cartographic_500k\cb_2024_us_county_500k.shp
------------------------------------------------------------------------------------------------------------------------
DATASET: 08_processed
STATUS:  EMPTY
PATH:    E:\NetworkOptimization\pythonProject1\Data\08_processed
FILES_MATCHED: 0 | FILES_ALL_UNDER: 0
SIZE_MATCHED:  0 B | SIZE_ALL_UNDER: 0 B
EXTENSIONS: NA
------------------------------------------------------------------------------------------------------------------------
DATASET: 09_crosswalks
STATUS:  EMPTY
PATH:    E:\NetworkOptimization\pythonProject1\Data\09_crosswalks
FILES_MATCHED: 0 | FILES_ALL_UNDER: 0
SIZE_MATCHED:  0 B | SIZE_ALL_UNDER: 0 B
EXTENSIONS: NA
------------------------------------------------------------------------------------------------------------------------
DATASET: FAF raw_zip
STATUS:  MISSING
PATH:    E:\NetworkOptimization\pythonProject1\Data\01_faf\raw_zip
FILES_MATCHED: 0 | FILES_ALL_UNDER: 0
SIZE_MATCHED:  0 B | SIZE_ALL_UNDER: 0 B
EXTENSIONS: NA
------------------------------------------------------------------------------------------------------------------------
DATASET: FAF flows_regional
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_regional
FILES_MATCHED: 2 | FILES_ALL_UNDER: 2
SIZE_MATCHED:  1.099 GB | SIZE_ALL_UNDER: 1.099 GB
EXTENSIONS: .csv:1, .xlsx:1
REPRESENTATIVE FILES:
  FIRST   |     1.099 GB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_regional\FAF5.7.1.csv
  FIRST   |    28.111 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_regional\FAF5_metadata.xlsx
  LARGEST |     1.099 GB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_regional\FAF5.7.1.csv
  LARGEST |    28.111 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_regional\FAF5_metadata.xlsx
------------------------------------------------------------------------------------------------------------------------
DATASET: FAF flows_state
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_state
FILES_MATCHED: 4 | FILES_ALL_UNDER: 4
SIZE_MATCHED:  957.935 MB | SIZE_ALL_UNDER: 957.935 MB
EXTENSIONS: .csv:2, .xlsx:2
REPRESENTATIVE FILES:
  FIRST   |   663.039 MB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_state\FAF5.7.1_2018-2024.csv
  FIRST   |   294.841 MB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_state\FAF5.7.1_State_2018-2024.csv
  FIRST   |    28.111 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_state\FAF5_metadata.xlsx
  LARGEST |   663.039 MB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_state\FAF5.7.1_2018-2024.csv
  LARGEST |   294.841 MB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_state\FAF5.7.1_State_2018-2024.csv
  LARGEST |    28.111 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_state\FAF5_metadata.xlsx
------------------------------------------------------------------------------------------------------------------------
DATASET: FAF flows_regional_full
STATUS:  MISSING
PATH:    E:\NetworkOptimization\pythonProject1\Data\01_faf\flows_regional_full
FILES_MATCHED: 0 | FILES_ALL_UNDER: 0
SIZE_MATCHED:  0 B | SIZE_ALL_UNDER: 0 B
EXTENSIONS: NA
------------------------------------------------------------------------------------------------------------------------
DATASET: FAF access_database
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\01_faf\access_database
FILES_MATCHED: 2 | FILES_ALL_UNDER: 2
SIZE_MATCHED:  1.246 GB | SIZE_ALL_UNDER: 1.246 GB
EXTENSIONS: .accdb:1, .xlsx:1
REPRESENTATIVE FILES:
  FIRST   |     1.246 GB | E:\NetworkOptimization\pythonProject1\Data\01_faf\access_database\FAF5.7.1_access.accdb
  FIRST   |    28.111 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\access_database\FAF5_metadata.xlsx
  LARGEST |     1.246 GB | E:\NetworkOptimization\pythonProject1\Data\01_faf\access_database\FAF5.7.1_access.accdb
  LARGEST |    28.111 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\access_database\FAF5_metadata.xlsx
------------------------------------------------------------------------------------------------------------------------
DATASET: FAF county_experimental
STATUS:  OK
PATH:    E:\NetworkOptimization\pythonProject1\Data\01_faf\county_experimental
FILES_MATCHED: 8 | FILES_ALL_UNDER: 8
SIZE_MATCHED:  2.090 MB | SIZE_ALL_UNDER: 2.090 MB
EXTENSIONS: .csv:8
REPRESENTATIVE FILES:
  FIRST   |   121.824 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\county_experimental\pipeline_destination_factors.csv
  FIRST   |    95.018 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\county_experimental\pipeline_origin_factors.csv
  FIRST   |   366.969 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\county_experimental\rail_destination_factors.csv
  LARGEST |   486.271 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\county_experimental\truck_origin_factors.csv
  LARGEST |   486.183 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\county_experimental\truck_destination_factors.csv
  LARGEST |   366.969 KB | E:\NetworkOptimization\pythonProject1\Data\01_faf\county_experimental\rail_destination_factors.csv
------------------------------------------------------------------------------------------------------------------------
DATASET: FAF lookup_tables
STATUS:  EMPTY
PATH:    E:\NetworkOptimization\pythonProject1\Data\01_faf\lookup_tables

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

========================================================================================================================
INVENTORY COMPLETE
========================================================================================================================
Total directories: 277
Total files:       28,981
Total size:        15.074 GB
Output TXT:        E:\NetworkOptimization\pythonProject1\Data\00_manifest\data_inventory_console_output.txt
Output CSV:        E:\NetworkOptimization\pythonProject1\Data\00_manifest\data_inventory_file_inventory.csv
========================================================================================================================